adobecom/milo

- libs/scripts/scripts.js
- libs/utils/lana.js
- libs/utils/lana.md
- test/libs/utils/lana.test.js
- test/libs/utils/lanaDefaultOptions.test.js
Resolves: MWPW-108402
Test URLs:
- After: https://<branch>--milo--adobecom.hlx.page/
> MWPW-108402 LANA logger script

- libs/utils/lana.js
Fix ugly code.  Simplifies parsing, no manually going over each property.
IE11 supports const, switch to that.
Test URLs:
- After: https://<branch>--milo--adobecom.hlx.page/
> Simplify parsing of the options obj; Forgot that IE11 supports const

- fonts/fonts.css
- libs/blocks/marquee/marquee.css
- libs/blocks/section-metadata/section-metadata.css
- libs/blocks/section-metadata/section-metadata.js
- libs/scripts/scripts.js
- libs/styles/styles.css
- libs/utils/utils.js
- test/scripts/scripts.test.js
* Ability to spec section style
* Ability to set background image
Resolves: MWPW-109312
Test URLs:
- After: https://section-meta--milo--adobecom.hlx.page/drafts/cmillar/section-container
> MWPW-109312 - Section Metadata

- libs/blocks/fragment/fragment.js
- libs/blocks/nofollow/nofollow.js
- libs/utils/utils.js
- test/blocks/nofollow/mocks/body.html
- test/blocks/nofollow/mocks/nofollow.json
- test/blocks/nofollow/nofollow.test.js
- test/utils/mocks/body.html
- test/utils/utils.test.js
* Ability to get list of nofollow domains
* Doesn't find relative links
* Supports fragments
Resolves: MWPW-110883
Test URLs:
- After: https://nofollow--milo--adobecom.hlx.page/drafts/cmillar/nofollow-demo
> MWPW-110883 - Nofollow Links

- .github/workflows/email-release.yaml
* Send a release email with release information
* Title of release
* Date of release
* Details of release
* Release approved by
* Released by
* Scope (files for now)
* Link to JIRA
* Link to test URLs
* Don't send if the PR has not been merged
* To email is configurable
* From email is configurable
Resolves: [MWPW-111018](https://jira.corp.adobe.com/browse/MWPW-111018)
Test URLs:
- After: https://main--milo--adobecom.hlx.page/
> MWPW-111018 - Automated Release Emails

- README.md
* Added npm command to README
Resolves: [MWPW-111132](https://jira.corp.adobe.com/browse/MWPW-111132)
**Test URLs:**
- After: https://libs-instructions--milo--adobecom.hlx.page/drafts/cmillar/marquee
> MWPW-111132 - Document libs development

- libs/blocks/caas-config/caas-config.js
- libs/utils/utils.js
- test/libs/blocks/caas/mocks/utils.js
- test/libs/blocks/caas/utils.test.js
- test/utils/utils.test.js
- web-test-runner.config.mjs
Caas-Configurator would sometimes not load for users who had used older versions.
Resolves: [MWPW-111602](https://jira.corp.adobe.com/browse/MWPW-111602)
**Test URLs:**
- After: https://caasLocalStor--milo--adobecom.hlx.page/
> MWPW-111602 Handle invalid local state

- libs/blocks/list.js
- libs/blocks/sabya/sabya.css
- libs/blocks/sabya/sabya.js
Updates libs to include all currently shipped blocks.
**Test URLs:**
- After: https://update-libs--milo--adobecom.hlx.page/
> Updating libs

- libs/blocks/columns/columns.css
- libs/styles/styles.css
- libs/styles/variables.css
* Enabling `table` option for column block.
* Setting up variables.css to share milo CSS variables with other helix sites.
Resolves: [MWPW-111569](https://jira.corp.adobe.com/browse/MWPW-111569)
**Test URLs:**
- Before: https://column-fix--business-website--adobe.hlx.page/blog/basics/business-case
- After: https://column-fix--business-website--adobe.hlx.page/blog/basics/business-case?milolibs=column-table
> Column table

- libs/ui/img/spectrum-back.svg
- libs/ui/img/spectrum-copy.svg
- libs/ui/library/library.css
- libs/ui/library/library.js
- tools/sidekick/config.js
* Supports block library
* Basic plumbing for tokens, templates, placeholders
* Triggered via Sidekick
Resolves: [MWPW-113016](https://jira.corp.adobe.com/browse/MWPW-113016)
> MWPW-113016 - Initial Library Support

- libs/ui/library/library.js
- tools/sidekick/config.js
* Add your
* Specicic
**Test URLs:**
- After: https://<branch>--milo--adobecom.hlx.page/
> Library fixes for extension

- libs/blocks/chart/chart.js
* Fetches chart data with basic processing
* Outputs results in pre tag, to be replaced later with chart
Resolves: [MWPW-112433](https://jira.corp.adobe.com/browse/MWPW-112433)
**Test URLs:**
- Before: https://main--milo--adobecom.hlx.page/drafts/bmarshal/chart
- After: https://fetch-chart-data--milo--adobecom.hlx.page/drafts/bmarshal/chart
> MWPW-112433 Fetch Chart Data

- libs/blocks/chart/chart.css
* Adding styles as is from charts.less
* Refactoring of styles should occur with development on chart since there is code/class duplication
Resolves: [112431](https://jira.corp.adobe.com/browse/MWPW-112431)
> Add chart.css

- libs/blocks/chart/chart.js
- libs/blocks/chart/chartLightTheme.js
- test/blocks/chart/chart.test.js
* Prevent unnecessary theme registrations
* Move bar-specific options out of theme
* Add tests
Resolves: [MWPW-112997](https://jira.corp.adobe.com/browse/MWPW-112997)
**Test URLs:**
- After: https://chart-theme--milo--adobecom.hlx.page/drafts/methomas/data-viz
> Clean up chart theme and add tests MWPW-112997

- libs/blocks/chart/chart.js
* Adding chart container
* Including container sizes as is for each chart type
* Parsing size from chart section metadata and adding/removing css classes
* [IN PROGRESS] Parsing color and container styles (will add in another PR)
Resolves: [MWPW-112994](https://jira.corp.adobe.com/browse/MWPW-112994) (Still in progress)
**Test URLs:**
- Before: https://data-viz--milo--adobecom.hlx.page/drafts/saravana/data-viz
- After: https://chart-section-metadata--milo--adobecom.hlx.page/drafts/saravana/data-viz
> MWPW-112994 Parsing size from chart section metadata

- libs/blocks/chart/chart.js
- libs/utils/utils.js
- test/utils/utils.test.js
* Lazy load charts
* Resolve loadScript promise for multiple calls
Resolves: [MWPW-112995](https://jira.corp.adobe.com/browse/MWPW-112995)
**Test URLs:**
- Before: https://main--milo--adobecom.hlx.page/drafts/bmarshal/chart
- After: https://lazy-load-chart--milo--adobecom.hlx.page/drafts/bmarshal/chart
> MWPW-112995 Adding chart lazy loading

- libs/blocks/chart/chart.js
- libs/utils/utils.js
* Add dynamic chart resize
* Make size responsive
* Cleanup
* Add throttle util
(Will add tests next)
Resolves: [MWPW-112996](https://jira.corp.adobe.com/browse/MWPW-112996)
**Test URLs:**
- After: https://chart-resize--milo--adobecom.hlx.page/drafts/methomas/data-viz
> add chart resize MWPW-112996

- libs/blocks/chart/chart.js
* Adding chart colors and container styles
* Cleaning up container sizes
Resolves: [MWPW-112994](https://jira.corp.adobe.com/browse/MWPW-112994)
**Test URLs:**
- Before: https://data-viz--milo--adobecom.hlx.page/drafts/saravana/data-viz
- After: https://chart-metadata--milo--adobecom.hlx.page/drafts/saravana/data-viz
> MWPW-112994 Chart metadata

- libs/blocks/chart/chart.css
- libs/blocks/chart/chart.js
- libs/blocks/chart/chartLightTheme.js
* Fix chart font
* Make sure title, subtitle, footnote styles are applied
* Fix chart css linter issues
Resolves: [MWPW-113663](https://jira.corp.adobe.com/browse/MWPW-113663)
**Test URLs:**
- Before: https://main--milo--adobecom.hlx.page/drafts/methomas/data-viz
- After: https://cleanup-bar-styles--milo--adobecom.hlx.page/drafts/methomas/data-viz
> Cleanup bar styles

- libs/blocks/fragment/fragment.js
- libs/scripts/scripts.js
- libs/utils/utils.js
- test/scripts/mocks/body.html
- test/scripts/scripts.test.js
- test/utils/mocks/body.html
- test/utils/utils.test.js
- tools/sidekick/config.js
* Made loadLCP extensible
* Removed redundant variant class cleanup (Helix V7)
* Made loadArea extensible and renamed it
* Made a loadDelayed test
* Made loadDelayed timeout extensible
Resolves: [MWPW-111268](https://jira.corp.adobe.com/browse/MWPW-111268)
**Test URLs:**
- Before: https://main--milo--adobecom.hlx.live/
- After: https://college--milo--adobecom.hlx.live/
- Before: https://main--milo--adobecom.hlx.live/drafts/cmillar/marquee
- After: https://college--milo--adobecom.hlx.live/drafts/cmillar/marquee
> MWPW-111268 - College Project Support

- libs/blocks/chart/chart.js
- test/blocks/chart/chart.test.js
* Add column chart options
* Fix chart type error
Resolves: [MWPW-113005](https://jira.corp.adobe.com/browse/MWPW-113005)
**Test URLs:**
- Before: https://main--milo--adobecom.hlx.page/drafts/methomas/data-viz
- After: https://column-chart--milo--adobecom.hlx.page/drafts/methomas/data-viz
> Add column chart

- libs/blocks/chart/chart.css
- libs/blocks/chart/chart.js
* Add chart section class
* Add 1-up, 2-up and 3-up
Resolves: [MWPW-113002 ](https://jira.corp.adobe.com/browse/MWPW-113002)
**Test URLs:**
- Before: https://data-viz--milo--adobecom.hlx.page/drafts/bmarshal/chart
- After: https://chart-123-up--milo--adobecom.hlx.page/drafts/bmarshal/chart
> MWPW-113002 Adding up patterns to charts

- libs/blocks/section-metadata/section-metadata.css
* Add section divider styles based on BACOM divider
* How to author: Add "divider" to section metadata style
Resolves: [MWPW-113003](https://jira.corp.adobe.com/browse/MWPW-113003)
**Test URLs:**
- After: https://section-divider--milo--adobecom.hlx.page/drafts/methomas/data-viz
> Add divider styles for section MWPW-113003

- libs/blocks/chart/chart.js
- test/blocks/chart/chart.test.js
* Add tests for chart color function
Resolves: [MWPW-112994](https://jira.corp.adobe.com/browse/MWPW-112994)
**Test URLs:**
- Before: https://data-viz--milo--adobecom.hlx.page/drafts/saravana/data-viz
- After: https://chart-color-tests--milo--adobecom.hlx.page/drafts/saravana/data-viz
> MWPW-112994 Add chart color tests

- libs/blocks/chart/chart.js
- libs/blocks/chart/chartLightTheme.js
* Add initial line chart options
* [Mark line TBD]
Resolves: [MWPW-113006](https://jira.corp.adobe.com/browse/MWPW-113006)
**Test URLs:**
- Before: https://main--milo--adobecom.hlx.page/drafts/methomas/data-viz
- After: https://line-chart--milo--adobecom.hlx.page/drafts/methomas/data-viz
> Add line chart MWPW-113006

- libs/blocks/chart/chart.js
- test/blocks/chart/chart.test.js
* Adding series data to line charts
Resolves: [MWPW-112702](https://jira.corp.adobe.com/browse/MWPW-112702)
**Test URLs:**
- Before: https://data-viz--milo--adobecom.hlx.page/drafts/bmarshal/data-viz
- After: https://chart-series-data--milo--adobecom.hlx.page/drafts/bmarshal/data-viz
> MWPW-112702 Process chart series data

- libs/blocks/chart/chart.js
* Add area chart
Resolves: [MWPW-113007](https://jira.corp.adobe.com/browse/MWPW-113007)
**Test URLs:**
- After: https://area-chart--milo--adobecom.hlx.page/drafts/data-viz/holiday-report-dev
> Add area chart

- libs/blocks/chart/chart.js
* Decrease line thickness on line chart
Resolves: [MWPW-111996](https://jira.corp.adobe.com/browse/MWPW-111996)
**Test URLs:**
- After: https://line-chart-enhancements--milo--adobecom.hlx.page/drafts/data-viz/holiday-report-dev
> Decrease line chart thickness MWPW-111996

- libs/blocks/chart/chart.js
- test/blocks/chart/chart.test.js
* Override bar chart colors per data point
Resolves: [MWPW-112290](https://jira.corp.adobe.com/browse/MWPW-112290)
**Test URLs:**
- Before: https://data-viz--milo--adobecom.hlx.page/drafts/bmarshal/column
- After: https://color-override--milo--adobecom.hlx.page/drafts/bmarshal/column
> MWPW-112290 Overriding chart colors

- libs/blocks/chart/chart.js
* Support 2nd y axis on column and line charts
Resolves: [MWPW-112060](https://jira.corp.adobe.com/browse/MWPW-112060)
**Test URLs:**
- After: https://right-axis--milo--adobecom.hlx.page/drafts/data-viz/holiday-report-dev
> Support 2nd y axis on column and line charts MWPW-112060

- libs/blocks/chart/chart.js
- test/blocks/chart/chart.test.js
- Split fetch data for use with both charts formats
- List chart data can be from single worksheet, multi-worksheet, or multi-worksheet with metadata table
- Added tests for both charts formats
Resolves: [MWPW-113983](https://jira.corp.adobe.com/browse/MWPW-113983)
Test URLs:
- Before: https://list-chart--milo--adobecom.hlx.page/drafts/bmarshal/list-chart
- After: https://list-chart-data--milo--adobecom.hlx.page/drafts/bmarshal/list-chart
> MWPW-113983 Process list chart data

- libs/blocks/chart/chart.js
- libs/blocks/chart/list.js
- libs/blocks/chart/utils.js
- test/blocks/chart/chart.test.js
- test/blocks/chart/list.test.js
- test/blocks/chart/utils.test.js
* Add single list chart
* Create chart/util file
Resolves: [MWPW-114086](https://jira.corp.adobe.com/browse/MWPW-114086)
**Test URLs:**
- After: https://single-list-chart--milo--adobecom.hlx.page/drafts/methomas/data-viz
> Add single list chart MWPW-114086

- .github/workflows/run-tests.yaml
- libs/utils/lana.js
- libs/utils/lana.md
- test/libs/utils/lana.test.js
* MWPW-114528 MWPW-112700 All dev/stage/author traffic goes to stage la…
* Update run-tests.yaml
Resolves:
**Test URLs:**
> Update data-viz with latest from main

- libs/blocks/chart/list.js
- test/blocks/chart/list.test.js
* Optimize turning list data keys lowercase
* Based on https://github.com/adobecom/milo/pull/110#discussion_r944708503
Resolves: [MWPW-114086](https://jira.corp.adobe.com/browse/MWPW-114086)
**Test URLs:**
- After: https://single-list-chart--milo--adobecom.hlx.page/drafts/methomas/data-viz
> Optimize list lowercase MWPW-114086

- libs/ui/library/library.js
- tools/sidekick/config.js
* Ability to use block library on a consumer
* Ability to iterate through a list of block sheets
* Google Docs support
Resolves: [MWPW-115006](https://jira.corp.adobe.com/browse/MWPW-115006)
> MWPW-115006 - Block Library Extensibility

- .github/workflows/run-tests.yaml
*  Add code coverage bot to data-viz branch PRs
Resolves: [MWPW-115146](https://jira.corp.adobe.com/browse/MWPW-115146)
> Add code coverage bot to data-viz branch PRs MWPW-115146

- libs/blocks/chart/chart.js
- test/blocks/chart/chart.test.js
* Add donut chart type
Resolves: [MWPW-114547](https://jira.corp.adobe.com/browse/MWPW-114547)
**Test URLs:**
- After: https://donut-chart--milo--adobecom.hlx.page/drafts/data-viz/holiday-report-dev
> Add donut chart

- libs/blocks/chart/list.js
- test/blocks/chart/list.test.js
- test/blocks/chart/mocks/list.html
- test/blocks/chart/mocks/listChartMulti.json
- test/blocks/chart/mocks/listChartMultiTable.json
- test/blocks/chart/mocks/listChartSingle.json
- test/blocks/chart/mocks/listChartSingleTable.json
* Adding tests for list chart, other charts to follow.
Resolves: [MWPW-115223](https://jira.corp.adobe.com/browse/MWPW-115223)
**Test URLs:**
- After: https://chart-tests-pt-2--milo--adobecom.hlx.page/drafts/data-viz/holiday-report-dev
> Adding list chart tests

- libs/blocks/chart/chart.js
- test/blocks/chart/chart.test.js
* Add tests to increase code coverage for chart
Resolves: [MWPW-115222](https://jira.corp.adobe.com/browse/MWPW-115222)
**Test URLs:**
- After: https://chart-test1--milo--adobecom.hlx.page/drafts/data-viz/holiday-report-dev
> add chart tests MWPW-115222

- libs/blocks/chart/chart.js
- test/blocks/chart/chart.test.js
* Add pie chart option to chart block
Resolves: [MWPW-113008](https://jira.corp.adobe.com/browse/MWPW-113008)
**Test URLs:**
- After: https://pie-chart--milo--adobecom.hlx.page/drafts/methomas/data-viz
> Add pie chart MWPW-113008

- libs/blocks/chart/chart.js
- libs/blocks/chart/utils.js
- test/blocks/chart/chart.test.js
- test/blocks/chart/mocks/barChart.json
- test/blocks/chart/mocks/columnChart.json
* Added new formatExcelDate util function to format date values
* Authors will need to include 'date' string in unit column to use dates on the x-axis (e.g `date-k`)
* Added logic to parse 'date' from unit and apply conditional logic when parsing data values
* Updated tests
Resolves: [MWPW-114540](https://jira.corp.adobe.com/browse/MWPW-114540)
**Test URLs:**
- Before: https://data-viz--milo--adobecom.hlx.page/drafts/saravana/column-qa
- After: https://chart-date-bugfix--milo--adobecom.hlx.page/drafts/saravana/column-qa
- Before: https://data-viz--milo--adobecom.hlx.page/drafts/saravana/line-qa
- After: https://chart-date-bugfix--milo--adobecom.hlx.page/drafts/saravana/line-qa
> MWPW-114540 Ensuring dates display correctly on the axis

- libs/blocks/chart/chart.js
- test/blocks/chart/chart.test.js
- test/blocks/chart/chartLightTheme.test.js
- test/blocks/chart/mocks/areaChart.json
- test/blocks/chart/mocks/chart.html
* Add tests for 100% code coverage for charts
Resolves: [MWPW-116043](https://jira.corp.adobe.com/browse/MWPW-116043)
**Test URLs:**
- After:  https://chart-tests-pt-3--milo--adobecom.hlx.page/drafts/data-viz/holiday-report-dev
> Adding chart tests part 3 MWPW-116043

- tools/send-to-caas/sidekick.js
- tools/sidekick/config.js
**Test URLs:**
- After: https://caasfullmilo--milo--adobecom.hlx.page/
> Use full milo domain for consuming sites

- libs/blocks/footer/footer.js
* Add your
* Specicic
**Test URLs:**
- After: https://<branch>--milo--adobecom.hlx.page/
> Fix footer icons for consumers

- libs/blocks/caas-config/caas-config.css
- libs/blocks/caas-config/caas-config.js
- libs/blocks/caas/utils.js
- libs/ui/controls/MultiField.js
- libs/ui/controls/TagSelector.js
- libs/ui/controls/formControls.js
- test/blocks/caas-config/caas-config.test.html
- test/blocks/caas-config/expectedConfigs/defaultConfig.js
- test/blocks/caas/caas.test.html
- test/blocks/caas/utils.test.js
- test/helpers/selectors.js
- tools/send-to-caas/send-to-caas.js
* Adds Filter Support to the CaaS Configurator
* Search field is displayed when enabled even if filters are not enabled
* Fix the Sort options
Resolves:
* Filters: [MWPW-114211](https://jira.corp.adobe.com/browse/MWPW-114211)
* Search Field: [MWPW-113743](https://jira.corp.adobe.com/browse/MWPW-113743)
**Test URLs:**
- Before: https://main--milo--adobecom.hlx.page/tools/caas-config
- After: https://caasSortFixAndMisc--milo--adobecom.hlx.page/tools/caas-config
> CaaS Filters & Bug fixes

- tools/send-to-caas/send-to-caas.css
- tools/send-to-caas/send-to-caas.js
- tools/send-to-caas/sendToCaasEventListener.js
- tools/send-to-caas/sidekick.js
* Add ability to choose CaaS env to publish to (prod, stage, dev)
* Fixed IMS issues with login
* Moved caas specific code out of sidekick config.js
Resolves: [MWPW-101325](https://jira.corp.adobe.com/browse/MWPW-101325)
**Test URLs:**
- After: https://sidekickims--milo--adobecom.hlx.page/
> MWPW-101325 Update sidekick for consumer support; IMS fixes

- libs/blocks/chart/list.js
* Fix list chart styles on consumer
Resolves: https://github.com/adobecom/milo/pull/149#issuecomment-1234685476
**Test URLs:**
- Before: https://main--bacom--adobecom.hlx.page/drafts/data-viz/holiday-report-dev?milolibs=data-viz
- After: https://main--bacom--adobecom.hlx.page/drafts/data-viz/holiday-report-dev?milolibs=tour-consumer
> Fix list chart styles for consumer

- libs/blocks/caas-config/caas-config.js
* Excluded card id's were not being excluded.
> Fix bug with excluded card ids not working

- libs/blocks/merch/merch.js
- libs/utils/utils.js
* Fix Safari module await loading bug
* Support for stage and production URLs
Resolves: MWPW-116458
> MWPW-116458 - MAS Follow Up (trivial)

- libs/blocks/carousel/carousel.css
- libs/blocks/carousel/carousel.js
- test/blocks/carousel/carousel.test.js
- test/blocks/carousel/mocks/body.html
Resolves: [MWPW-115742([MWPW-URL](https://jira.corp.adobe.com/browse/MWPW-115742))
**Test URLs:**
- Before: [https://main--milo--adobecom.hlx.page/](https://main--milo--adobecom.hlx.page/drafts/bradjohn/carousel?martech=off)
- After: [https://hide-carousel--milo--adobecom.hlx.page/](https://hide-carousel--milo--adobecom.hlx.page/drafts/bradjohn/carousel?martech=off)
> Hide carousel

- libs/blocks/chart/chart.js
- test/blocks/chart/chart.test.js
* Adding tooltip for donut chart
Resolves: [MWPW-116340](https://jira.corp.adobe.com/browse/MWPW-116340)
**Test URLs:**
- Before: https://main--milo--adobecom.hlx.page/drafts/saravana/chartsqa
- After: https://donut-chart-tooltip--milo--adobecom.hlx.page/drafts/saravana/chartsqa
> MWPW-116340 Adding tooltip for donut chart

- libs/blocks/chart/chart.css
- libs/blocks/chart/chart.js
- test/blocks/chart/chart.test.js
- test/blocks/chart/mocks/oversized-number.json
* Add oversized number chart type
* Refactor chart container size
Resolves: [MWPW-113009](https://jira.corp.adobe.com/browse/MWPW-113009)
**Test URLs:**
- Before: https://main--milo--adobecom.hlx.page/drafts/methomas/data-viz?martech=off
- After: https://oversized-number--milo--adobecom.hlx.page/drafts/methomas/data-viz?martech=off
> MWPW-113009 - Oversized Number Chart

- libs/blocks/footer/footer.js
- libs/blocks/gnav/gnav.js
- libs/utils/utils.js
Analytics parity with dexter adobe.com
**Test URLs:**
- After: https://footerdaa--milo--adobecom.hlx.page/
> Gnav and Footer Analytics

- libs/blocks/chart/chart.js
- test/blocks/chart/chart.test.js
- test/blocks/chart/mocks/donutChart.json
* Fix grainy donut chart labels
Resolves: [MWPW-116408](https://jira.corp.adobe.com/browse/MWPW-116408)
**Test URLs:**
- Before: https://main--milo--adobecom.hlx.page/drafts/bmarshal/chartsqa?martech=off
- After: https://grainy-donut--milo--adobecom.hlx.page/drafts/bmarshal/chartsqa?martech=off
> Fix grainy donut chart MWPW-116408

- libs/blocks/chart/chart.js
* Make chart tabbable
Resolves: [MWPW-116840](https://jira.corp.adobe.com/browse/MWPW-116840)
**Test URLs:**
- Before: https://main--milo--adobecom.hlx.page/drafts/data-viz/holiday-report-dev?martech=off
- After: https://chart-aria--milo--adobecom.hlx.page/drafts/data-viz/holiday-report-dev?martech=off
> Chart accessibility MWPW-116840

- libs/blocks/gnav/gnav-search.js
- libs/blocks/gnav/gnav.css
- libs/blocks/gnav/gnav.js
**Test URLs:**
- After: https://getsearchworking--milo--adobecom.hlx.page/?martech=off
> Wire up search

- libs/templates/featured-story/featured-story.js
* Add your
* Specicic
**Test URLs:**
> Fix featured story

- libs/utils/utils.js
- test/blocks/gnav/gnav.test.js
* Add privacy to the delayed list
* Remove broken gnav search tests
Before: https://main--milo--adobecom.hlx.page/drafts/cmillar/marquee
After: https://delay-privacy--milo--adobecom.hlx.page/drafts/cmillar/marquee
> Delay privacy

- libs/blocks/caas-config/caas-config.css
- libs/blocks/caas-config/caas-config.js
**Test URLs:**
- Before: https://main--milo--adobecom.hlx.page/tools/caas?martech=off
- After: https://caasShowIds--milo--adobecom.hlx.page/tools/caas?martech=off
> Add option to show card ids in configurator

- libs/blocks/manual-card/manual-card.js
- libs/utils/utils.js
- test/blocks/manual-card/manual-card.test.js
- test/blocks/manual-card/mocks/default.html
- test/blocks/manual-card/mocks/double-width.html
- test/blocks/manual-card/mocks/half-height.html
- test/blocks/manual-card/mocks/half.html
- test/blocks/manual-card/mocks/product.html
* Add manual card in consonant style to match CaaS cards
* Types: Half Card, Double Width Card, Product Card, and Half Height Card
* Border or no border supported
* 1-up to 4-up supported
Resolves: [MWPW-115384](https://jira.corp.adobe.com/browse/MWPW-115384)
**Test URLs:**
- Before: https://main--milo--adobecom.hlx.page/drafts/methomas/manual-card?martech=off
- After: https://manual-card--milo--adobecom.hlx.page/drafts/methomas/manual-card?martech=off
> Manual Card MWPW-115384

- libs/blocks/aside/aside.css
- libs/blocks/aside/aside.js
- test/blocks/aside/aside.test.js
- test/blocks/aside/mocks/body.html
* Add inline as option in Aside block
Resolves: [MWPW-115383](https://jira.corp.adobe.com/browse/MWPW-117317)
**Test URLs:**
- Before: https://main--milo--adobecom.hlx.page/drafts/methomas/inline-aside?martech=off
- After: https://aside-inline--milo--adobecom.hlx.page/drafts/methomas/inline-aside?martech=off
> Inline Aside MWPW-115383

- libs/blocks/caas-config/caas-config.js
- libs/ui/controls/Accordion.js
- libs/ui/controls/MultiField.js
- libs/ui/controls/TagSelector.js
- libs/utils/utils.js
**Test URLs:**
- Before: https://main--bacom--adobecom.hlx.page/tools/caas?martech=off
- After: https://main--bacom--adobecom.hlx.page/tools/caas?martech=off&milolibs=caasConfigAddBlock
> Add caas-config to MILO_BLOCKS so it can be used by consumers

- libs/blocks/caas-config/caas-config.js
- libs/blocks/caas/caas.css
* Adds white background to logos on cards
* This should be fixed by CaaS team, but for now fixing on our end
Resolves: [MWPW-118035](https://jira.corp.adobe.com/browse/MWPW-118035)
**Test URLs:**
- Before: https://main--milo--adobecom.hlx.page/tools/caas?martech=off
- After: https://caaswhitelogobg--milo--adobecom.hlx.page/tools/caas?martech=off
> MWPW-118035 White bg for card logos

- libs/blocks/pdf-viewer/pdf-viewer.css
- libs/blocks/pdf-viewer/pdf-viewer.js
- libs/scripts/scripts.js
- libs/utils/utils.js
- test/blocks/pdf-viewer/mocks/body.html
- test/blocks/pdf-viewer/pdf-viewer.test.js
- test/utils/mocks/body.html
- test/utils/utils.test.js
* Add new PDF Viewer block as a link block
Resolves: [MWPW-115380](https://jira.corp.adobe.com/browse/MWPW-115380)
**Test URLs:**
- Before: https://main--milo--adobecom.hlx.page/drafts/saravana/pdf-viewsdk?martech=off
- After: https://pdf-viewsdk--milo--adobecom.hlx.page/drafts/saravana/pdf-viewsdk?martech=off
> MWPW-115380 Adding pdf viewer block

- libs/blocks/caas-config/caas-config.js
- libs/blocks/caas/utils.js
- package.json
- test/blocks/caas-config/caas-config.test.html
- test/blocks/caas/mocks/utils.js
- test/blocks/gnav/gnav.test.js
- test/blocks/gnav/missing-gnav.test.js
- test/blocks/gnav/mocks/body.html
- test/blocks/gnav/mocks/head.html
- test/blocks/gnav/mocks/missing-gnav.html
* Increase gnav coverage
* Fix intermittent failures
* Increase amount of concurrent browsers used to speed tests up
**Test URLs:**
- After: https://gnav-tests--milo--adobecom.hlx.page/?martech=off
> Increase gnav test coverage

- libs/utils/martech.js
Write the implementation project in digitalData.
> MWPW-113517 - Tag pages as Milo

- libs/blocks/caas-config/caas-config.js
- libs/blocks/caas/caas.css
- libs/blocks/caas/caas.js
- libs/blocks/caas/utils.js
Support modal videos launched from CaaS cards
Resolves: [MWPW-117777](https://jira.corp.adobe.com/browse/MWPW-117777)
Test URLs:
Before: [main--milo--adobecom.hlx.page/drafts/cpeyer/mymilo?martech=off](https://main--milo--adobecom.hlx.page/drafts/cpeyer/mymilo?martech=off)
After: https://videos_caas--milo--adobecom.hlx.page/drafts/cpeyer/mymilo?martech=off
> MWPW-117777 Add support for modal videos

- libs/blocks/faas/utils.js
- test/blocks/faas/utils.test.js
This is a followup PR from previews faas fix.
> FaaS test fix.

- .github/workflows/run-janus.yml
* Ability to add @label to limit what tests Janus runs
Resolves: [MWPW-109693](https://jira.corp.adobe.com/browse/MWPW-109693)
**Test URLs:**
- After: https://janus-labels--milo--adobecom.hlx.page/?martech=off
> MWPW-109693 - Janus Feature Labels

- libs/utils/utils.js
* Add libs support for review block
> Review support

- .github/workflows/run-janus.yml
- libs/blocks/aside/aside.css
- libs/blocks/aside/aside.js
- test/blocks/aside/aside.test.js
- test/blocks/aside/mocks/body.html
* Add Notification version to Aside block
* Add light/dark options for Aside block
Resolves: [MWPW-116276](https://jira.corp.adobe.com/browse/MWPW-116276)
**Test URLs:**
- [Before](https://main--milo--adobecom.hlx.page/drafts/methomas/aside-notification?martech=off)
- [After](https://aside-notification--milo--adobecom.hlx.page/drafts/methomas/aside-notification?martech=off)
> MWPW-116276 - Notification Aside

- libs/blocks/faas/faas.css
- libs/blocks/faas/utils.js
Clearbit errorMessage fix.
Other bug fixed as well.
Before: https://main--bacom--adobecom.hlx.page/drafts/iscandar/fake-gated-offer-1
After: https://main--bacom--adobecom.hlx.page/drafts/iscandar/fake-gated-offer-1?milolibs=faas-fix
Expected result:
> Fixing the clearbit error message issue.

- libs/blocks/caas/utils.js
- test/blocks/caas-config/caas-config.test.html
- test/blocks/caas-config/expectedConfigs/defaultConfig.js
- test/blocks/caas/utils.test.js
- Added featured cards to config
- Updated unit tests to reflect these changes.
Resolves: [[MWPW-NUMBER](MWPW-URL)](https://jira.corp.adobe.com/browse/MWPW-118735)
**Test URLs:**
- Before: https://main--milo--adobecom.hlx.page/tools/caas?martech=off
- After: https://milo-featured-sort-issue--milo--adobecom.hlx.page/tools/caas?martech=off
> MWPW-118735: CaaS Config Featured Sort Issue

- libs/utils/utils.js
* Move martech to postlcp function
Resolves: [MWPW-119185](https://jira.corp.adobe.com/browse/MWPW-119185)
**Test URLs:**
- Before: https://main--milo--adobecom.hlx.page/drafts/cmillar/marquee
- After: https://postlcp-martech--milo--adobecom.hlx.page/drafts/cmillar/marquee
> MWPW-119185 - Move Martech to PostLCP

- libs/blocks/faas-config/faas-config.js
- libs/blocks/faas/faas.css
- libs/blocks/faas/utils.js
- Adding title styles on FaaS config.
Resolves: [MWPW-119394](https://jira.corp.adobe.com/browse/MWPW-119394)
**Test URLs:**
- Before: https://main--milo--adobecom.hlx.page/tools/faas-config
- After: https://faas-style--milo--adobecom.hlx.page/tools/faas-config
> Faas style

- libs/blocks/card/card.js
* Fix race condition in Card block
Resolves: [MWPW-119010](https://jira.corp.adobe.com/browse/MWPW-119010)
**Test URLs:**
- Before: https://main--milo--adobecom.hlx.page/drafts/methomas/half-height?martech=off
- After: https://methomas-card-race-condition--milo--adobecom.hlx.page/drafts/methomas/half-height?martech=off
> MWPW-119010 - Fix card race condition

- .hlxignore
- libs/utils/sidekick.js
- tools/sidekick/config.json
- tools/translation/config.js
- tools/translation/index.html
- tools/translation/project.js
- tools/translation/sharepoint.js
* Setup loc to use config.json
* Minor loc adjustments to support config.json
Resolves: [MWPW-120367](https://jira.corp.adobe.com/browse/MWPW-120367)
**Test URLs:**
> MWPW-120367 - Loc Mv3 Support

- libs/blocks/faas/utils.js
* Add user to Adobe Analytics Sandbox on FaaS submit if URL param `?faas-post-submit=aa-sandbox` is present
Resolves: [MWPW-116341](https://jira.corp.adobe.com/browse/MWPW-116341)
**Test URLs:**
- Before: https://main--milo--adobecom.hlx.page/drafts/methomas/resources/adobe-analytics-sandbox?martech=off
- After: https://methomas-faas-aa-sandbox--milo--adobecom.hlx.page/drafts/methomas/resources/adobe-analytics-sandbox?martech=off&faas-post-submit=aa-sandbox
> MWPW-116341 - FaaS AA Sandbox

- package.json
Mistakenly added when doing local node work.
> Remove type module

- libs/blocks/library-config/library-config.css
- libs/blocks/library-config/library-config.js
- libs/blocks/library-config/library-utils.js
- libs/blocks/library-config/lists/blocks.js
- libs/blocks/library-config/lists/placeholders.js
- libs/features/placeholders.js
- libs/templates/library/library.css
- libs/utils/utils.js
- test/features/placeholders/placeholders.json
- test/features/placeholders/placeholders.test.js
- test/utils/mocks/body.html
- test/utils/utils.test.js
- tools/sidekick/config.json
* Add support for placeholders via regex
* Add support for placeholders via key
* Update library to support placeholders
* Improve library AX
Resolves: [MWPW-109329](https://jira.corp.adobe.com/browse/MWPW-109329)
**Test URLs:**
- Before: https://main--milo--adobecom.hlx.page/tools/library
- After: https://placeholders--milo--adobecom.hlx.page/tools/library
> MWPW-109329 - Placeholders

- libs/blocks/chart/chart.js
- libs/blocks/chart/chartLightTheme.js
* Improve aria label for Chart (Item 1.2 in Accessibility Review)
* Uses placeholder functionality for localization support
Resolves: [MWPW-119523](https://jira.corp.adobe.com/browse/MWPW-119523)
**Test URLs:**
- Before: https://main--milo--adobecom.hlx.page/drafts/methomas/chart?martech=off
- After: https://methomas-chart-accessibility-1-2--milo--adobecom.hlx.page/drafts/methomas/chart?martech=off
> MWPW-119523 Chart Aria Label Improvement

- libs/templates/404/404.js
- libs/utils/samplerum.js
- libs/utils/utils.js
- test/utils/samplerum.test.js
Brings the Franklin SampleRum to Milo
**Test URLs:**
- After: https://c3-rum_again--milo--adobecom.hlx.page/?martech=off
> MWPW-106279 - Add Franklin RUM to Milo

- libs/utils/utils.js
* Prevent placeholder from clobbering head element
> HOTFIX - Placeholder

- tools/loc/rollout.js
- tools/loc/ui.js
- Disable Alert and instead add a message
- Disable Merge Logic temporarily until stable
Resolves: MWPW-121958
> MWPW-121958: Disable Alert on Override and Merge Logic

- libs/img/icons/icons.svg
Resolves: [MWPW-121791](https://jira.corp.adobe.com/browse/MWPW-121791)
**Test URLs:**
[Before](https://main--milo--adobecom.hlx.page/drafts/bradjohn/document1?martech=off)
[After](https://customer-story-icons--milo--adobecom.hlx.page/drafts/bradjohn/document1?martech=off)
Bacom:
https://bradjohn-customer-story-svg--bacom--adobecom.hlx.page/drafts/bradjohn/document?milolibs=customer-story-icons&martech=off
> Play and objectives icon addition

- libs/blocks/faas-config/faas-config.css
- libs/blocks/faas-config/faas-config.js
- libs/blocks/faas/utils.js
- Added validation for internal campaign id and  multi-campaign ids  fields.
- Added internal campaign id field for multi event forms.
- Bug fixes on radio style, hide pre-population.
Resolves: [MWPW-122243](https://jira.corp.adobe.com/browse/MWPW-122243)
**Test URLs:**
- Before: https://main--milo--adobecom.hlx.page/tools/faas?env=qa
- After: https://faas-fix--milo--adobecom.hlx.page/tools/faas?env=qa
> faas tool field validation added.

- libs/blocks/accordion/accordion.js
Update to allow accordion to maintain (parameters) for styling purposes. 
Resolves: [MWPW-122828](https://jira.corp.adobe.com/browse/MWPW-122828)
**Test URLs:**
https://main--milo--adobecom.hlx.page/docs/library/blocks/accordion?martech=off
- After: https://MWPW-122828--milo--adobecom.hlx.page/?martech=off
https://mwpw-122828--milo--adobecom.hlx.page/docs/library/blocks/accordion?martech=off
> MWPW-122828

- libs/scripts/scripts.js
- libs/scripts/scripts.md
- test/scripts/scripts.test.js
Resolves: [MWPW-119602](https://jira.corp.adobe.com/browse/MWPW-119602)
**Test URLs:**
- After: https://c3-milolana--milo--adobecom.hlx.page/?martech=off
> MWPW-119602 Load lana on first call to lana.log

- libs/blocks/modal/modal.js
- test/blocks/modals/mocks/milo.plain.html
- test/blocks/modals/mocks/paragraph.plain.html
- test/blocks/modals/mocks/title.plain.html
- test/blocks/modals/modals.test.js
* Adds focus trap to modal
* Adds tests to check the focus trap and first focusable items 
Resolves: [MWPW-120941](https://jira.corp.adobe.com/browse/MWPW-120941)
**Test URLs:**
- Before: https://main--milo--adobecom.hlx.page/drafts/slavin/complex-modal?martech=off
- After: https://modal-trap-focus--milo--adobecom.hlx.page/drafts/slavin/complex-modal?martech=off
> MWPW-120941 Add Modal Focus Trap

- libs/styles/variables.css
* Add JP font family styles
Resolves: [MWPW-122331](https://jira.corp.adobe.com/browse/MWPW-122331)
**Test URLs:**
- Before: https://main--milo--adobecom.hlx.page/jp/drafts/bmarshal/pga-tour-case-study?martech=off
- After: https://jp-font--milo--adobecom.hlx.page/jp/drafts/bmarshal/pga-tour-case-study?martech=off
> MWPW-122331 Add JP Font

- libs/blocks/modal/modal.js
- libs/utils/utils.js
* Fixes accessibility issue in the modal: When the modal closes, the focus should return to the button that opened the modal
Resolves: [MWPW-120863](https://jira.corp.adobe.com/browse/MWPW-120863)
**Test URLs:**
- Before: https://main--milo--adobecom.hlx.page/drafts/methomas/modal?martech=off
- After: https://methomas-modal-button-focus--milo--adobecom.hlx.page/drafts/methomas/modal?martech=off
> MWPW-120863 - Modal Button Focus Bug

- libs/blocks/section-metadata/section-metadata.css
- libs/blocks/section-metadata/section-metadata.js
- test/blocks/section-metadata/mocks/body.html
- test/blocks/section-metadata/section-meta.test.js
* Adding layout to section metadata, and css for new class additions
* Adding test to account for new function
Resolves: [MWPW-121471](https://jira.corp.adobe.com/browse/MWPW-121471)
**Test URLs:**
- Before: https://main--bacom--adobecom.hlx.page/drafts/slavin/layout-sample?martech=off
- After: https://main--bacom--adobecom.hlx.page/drafts/slavin/layout-sample?martech=off&milolibs=section-metadata-layout
- After:On Milo, with content originally set up by @ryanmparrish: https://section-metadata-layout--milo--adobecom.hlx.page/drafts/slavin/document
> MWPW-121471 Layout in section metadata

- .github/workflows/run-nala.yml
added the pulling in of missing secrets for Run-Nala executions for IMS Login Test
This is a GitHub Actions Workflow fix for executing the IMSLogin Test in the Milo Repository.
To test look into the github actions workflow run summary and see that there are no longer IMS Login test failures
> added the pulling in of missing secrets for Run-Nala

- tools/loc/ui.js
- update start button show condition to handle the case where there are no translation projects
Resolves: MWPW-124845
**Test URLs:**
- N/A
> MWPW-124845 - Start Project button missing for only some projects

- libs/blocks/review/review.js
* Add product schema to review block
Resolves: [MWPW-123893](https://jira.corp.adobe.com/browse/MWPW-123893)
**Test URLs:**
- Before: https://main--dc--adobecom.hlx.page/acrobat/online/pdf-to-ppt
- After: https://main--dc--adobecom.hlx.page/acrobat/online/pdf-to-ppt?milolibs=review-json
> MWPW-123893 - Review Schema

- libs/blocks/chart/chart.css
- libs/blocks/chart/chart.js
- test/blocks/chart/chart.test.js
- test/blocks/chart/mocks/lineChartSubheading.json
* Allow data authors to add a subheading in the data file that shows up under the chart subtitle
* (Use case is a date range)
Resolves: [MWPW-120858](https://jira.corp.adobe.com/browse/MWPW-120858)
**Test URLs:**
- Before: https://main--milo--adobecom.hlx.page/drafts/methomas/chart-date-range?martech=off
- After: https://methomas-chart-date-range--milo--adobecom.hlx.page/drafts/methomas/chart-date-range?martech=off
> MWPW-120858 - Chart Data Subheading

- libs/blocks/card-horizontal/card-horizontal.css
- libs/blocks/card-horizontal/card-horizontal.js
- test/blocks/card-horizontal/card-horizontal.test.js
- test/blocks/card-horizontal/mocks/body.html
* Add full-card click to horizontal card
* For authoring: add link to heading
Resolves: [MWPW-124814](https://jira.corp.adobe.com/browse/MWPW-124814)
**Test URLs:**
- Before: https://main--milo--adobecom.hlx.page/drafts/methomas/card-horizontal-video?martech=off
- After: https://methomas-horizontal-card-video--milo--adobecom.hlx.page/drafts/methomas/card-horizontal-video?martech=off
> MWPW-124814 Horizontal Card Link

- libs/utils/utils.js
- test/utils/mocks/body.html
- test/utils/utils.test.js
* Fix cookie preferences trigger to work on all geos
Resolves: [MWPW-125513](https://jira.corp.adobe.com/browse/MWPW-125513)
**Test URLs:**
- Before: https://main--bacom--adobecom.hlx.page/kr/customer-success-stories?martech=off
- After: https://main--bacom--adobecom.hlx.page/kr/customer-success-stories?milolibs=methomas-cookie-modal-bug&martech=off
- After: https://main--bacom--adobecom.hlx.page/customer-success-stories?milolibs=methomas-cookie-modal-bug&martech=off
- After: https://methomas-cookie-modal-bug--milo--adobecom.hlx.page/?martech=off
Note: You must wait until `privacy-standalone.js` has loaded for the modal trigger to work (abt 3 secs)
> MWPW-125513 - Cookie preferences bug

- libs/blocks/iframe/iframe.js
* Allow iframe permission to go fullscreen for the embedded product tour.
* Tour would stop while requesting fullscreen on tablet and mobile.
Resolves: [MWPW-125608](https://jira.corp.adobe.com/browse/MWPW-125608)
**Test URLs:**
- Before: https://main--milo--adobecom.hlx.page/drafts/bmarshal/fullscreen-tour?martech=off
- After: https://bmarshal-fullscreen-tour--milo--adobecom.hlx.page/drafts/bmarshal/fullscreen-tour?martech=off
> MWPW-125608 fullscreen embedded tour

- libs/utils/utils.js
- test/utils/mocks/head.html
- test/utils/utils.test.js
> Revert "MWPW-126165 - Clean up meta URLs"

- libs/blocks/footer/footer.js
* Clicking on footer titles reloads the page
Resolves: [MWPW-125923](https://jira.corp.adobe.com/browse/MWPW-125923)
**Test URLs:**
- After: https://bmarshal-footer-titles--milo--adobecom.hlx.page/?martech=off
**BACOM Test URLs:**
- Before: https://main--bacom--adobecom.hlx.page/customer-success-stories/the-home-depot-case-study?martech=off
- After: https://main--bacom--adobecom.hlx.page/customer-success-stories/the-home-depot-case-study?martech=off&milolibs=bmarshal-footer-titles
> MWPW-125923 Fix Footer Titles

- .github/codeql/codeql-config.yml
- tools/floodgate/css/floodgate.css
- tools/floodgate/index.html
- tools/floodgate/js/config.js
- tools/floodgate/js/floodgate.js
- tools/floodgate/js/project.js
- tools/floodgate/js/ui.js
- tools/floodgate/js/utils.js
- tools/loc/config.js
- tools/loc/glaas.js
- tools/loc/project.js
- tools/loc/sharepoint.js
- tools/loc/ui.js
- tools/loc/utils.js
- tools/sidekick/config.json
* The floodgate admin page follows the pattern of Milo Localization in terms of code/content setup and processing, especially given the overlap of functionalities and Sharepoint API usage.
* Creates a base admin page for Floodgate
* Authenticates with sharepoint
* Reads the Floodgate config and project excel file and renders the data on the page
* Checks for Source and Floodgated page in sharepoint and renders the link and status
Resolves: [MWPW-124568](https://jira.corp.adobe.com/browse/MWPW-124568)
**Test URLs:**
- Before: N/A
- After: [https://floodgate-base--milo--sukamat.hlx.page/tools/floodgate/index.html](https://floodgate-base--milo--sukamat.hlx.page/tools/floodgate/index.html?project=milo--adobecom&referrer=https%3A%2F%2Fadobe.sharepoint.com%2F%3Ax%3A%2Fr%2Fsites%2Fadobecom%2F_lay …
> MWPW-124568: Floodgate Admin Base Page

- libs/blocks/caas/utils.js
- libs/utils/utils.js
- test/blocks/caas-config/caas-config.test.html
- test/blocks/caas-config/expectedConfigs/defaultConfig.js
- test/blocks/caas/utils.test.js
- tools/send-to-caas/send-utils.js
Resolves: [MWPW-127136](https://jira.corp.adobe.com/browse/MWPW-127136)
**Test URLs:**
> MWPW-127136 Set correct country and lang on publish

- libs/blocks/fallback/fallback.js
- fixes the failing fallback test
> fix: fallback test

- .eslintrc-code-compatibility.js
- explicitly add `eslint-plugin-import` plugin
> Fix eslint import errors

- libs/blocks/footer/footer.js
This is for fixing small bug in case footer is empty.
> Fixing bug when there is no firstelementchild on footer div.

- libs/utils/utils.js
Load Privacy using different configurations and allow end to end functionality on all domains.
Resolves: [MWPW-127078](https://jira.corp.adobe.com/browse/MWPW-127078)
**Test URLs:**
- After: https://privacy--milo--adobecom.hlx.page/?martech=off
> MWPW-127078: Implement Privacy on all domains

- libs/blocks/preflight/panels/general.js
- libs/blocks/preflight/preflight.css
* Display list of found URLs immediately
* Lazily load helix admin statuses
Resolves: [MWPW-127611](https://jira.corp.adobe.com/browse/MWPW-127611)
**Test URLs**
- Before: https://main--milo--adobecom.hlx.page/drafts/cmillar/preflight?martech=off
- After: https://preflight-perf--milo--adobecom.hlx.page/drafts/cmillar/preflight?martech=off
**Acrobat URLs**
- Before: https://main--dc--adobecom.hlx.page/acrobat/online/pdf-to-ppt
- After: https://main--dc--adobecom.hlx.page/acrobat/online/pdf-to-ppt?milolibs=preflight-perf
---
**Steps to reproduce**
1. Open any _before_ page.
2. Click `Preflight` in Sidekick.
3. Observe time it takes for URLs to appear.
**Steps to see fix**
1. Open any _after_ page.
2. Click `Preflight` in Sidekick.
3. Observe time it takes for URLs to appear.
> MWPW-127611 - Preflight Performance

- tools/floodgate/index.html
- tools/floodgate/js/floodgate.js
- tools/floodgate/js/ui.js
- tools/loc/sharepoint.js
- tools/loc/ui.js
- tools/loc/utils.js
* Copy Action button added to the Floodgate Admin page
* Copies the file from the source tree to the floodgate equivalent pink tree
* Checks the existence of the file at the source and ignores if 404
* Checks for the existence of the file at the destination. 
* If not available, copies the file at the destination
* If available, overwrites the file using rename->copy->delete method
* Creates missing folders at the destination as necessary
* Once copy is completed, updates the status of the copy in the project excel sheet with the start and end timestamp and logs list of pages where copy could not be performed
Resolves: [MWPW-124571](https://jira.corp.adobe.com/browse/MWPW-124571)
**Test URLs:**
- Before: [https://main--milo--adobecom.hlx.page/tools/floodgate/index.html](https://main--milo- …
> MWPW-124571: FG Copy Action

- libs/blocks/gnav/gnav.css
* Adding styles for current page on breadcrumbs 
Resolves: [MWPW-126734](https://jira.corp.adobe.com/browse/MWPW-126734)
**Test URLs:**
- Before: https://main--milo--adobecom.hlx.page/drafts/bmarshal/breadcrumbs?martech=off
- After: https://bmarshal-breadcrumbs-active--milo--adobecom.hlx.page/drafts/bmarshal/breadcrumbs?martech=off
**BACOM Test URLs:**
- Before: https://main--bacom--adobecom.hlx.page/de/customer-success-stories/wvv-case-study?martech=off
- After: https://main--bacom--adobecom.hlx.page/de/customer-success-stories/wvv-case-study?martech=off&milolibs=bmarshal-breadcrumbs-active
> MWPW-126734 Breadcrumbs active style for current page

- libs/blocks/caas-config/caas-config.js
- libs/ui/controls/formControls.js
Resolves: [MWPW-127797](https://jira.corp.adobe.com/browse/MWPW-127797)
**Test URLs:**
- After: https://c3-caaslang--milo--adobecom.hlx.page/?martech=off
> MWPW-127797 Manually override incorrect caas lang and country tags

- libs/blocks/author-header/author-header.js
* Fix null element on author-header block when no social links are provided
**Test URLs:**
- Before: https://main--blog--adobecom.hlx.page/drafts/smalla/adam-morgan
- After: https://main--blog--adobecom.hlx.page/drafts/smalla/adam-morgan?milolibs=authors&martech=off
> fix: author-header no social links

- libs/blocks/caas/utils.js
Resolves: [MWPW-127286](https://jira.corp.adobe.com/browse/MWPW-127286)
**Test URLs:**
- Before: https://main--bacom--adobecom.hlx.page/jp/customer-success-stories?martech=off
- After:    https://main--bacom--adobecom.hlx.page/jp/customer-success-stories?martech=off&milolibs=c3-filtertitles
> MWPW-127286 Localize filter titles

- tools/floodgate/css/floodgate.css
- tools/floodgate/index.html
- tools/floodgate/js/floodgate.js
- tools/floodgate/js/promote.js
- tools/floodgate/js/ui.js
- tools/floodgate/js/utils.js
- tools/loc/sharepoint.js
* Promote Action button added to the Floodgate Admin page
* Iterates the FG tree and promotes the file from the FG tree to the app equivalent main tree
* Checks for the existence of the file at the destination. 
* If not available, copies the file at the destination
* If available, overwrites the file using rename->copy->delete method
* Creates missing folders at the destination as necessary
* Once promote is completed, updates the status of the promote in the project excel sheet with the start and end timestamp and logs list of pages where promote could not be performed
Resolves: [MWPW-124574](https://jira.corp.adobe.com/browse/MWPW-124574)
**Test URLs:**
- Before: [https://main--milo--adobecom.hlx.page/tools/floodgate/index.html](https://main--milo--adobecom.hlx.page/tools/floodgate/inde …
> MWPW-124574: FG Promote Action

- tools/send-to-caas/send-utils.js
Resolves: [MWPW-127806](https://jira.corp.adobe.com/browse/MWPW-127806)
**Test URLs:**
- After: https://c3-tagdelimiters--milo--adobecom.hlx.page/?martech=off
> MWPW-127806 Better CaaS tag delimiter support

- test/blocks/caas-config/caas-config.test.html
* Add your
* Specicic
**Test URLs:**
-  https://caas-test-changes--milo--sheridansunier.hlx.page?martech=off
> small caas unit test change

- tools/floodgate/css/floodgate.css
- tools/floodgate/index.html
- tools/floodgate/js/floodgate.js
- tools/floodgate/js/project.js
- tools/floodgate/js/ui.js
* Displays status of the FG actions run by the author for a specific project.
Resolves: [MWPW-127882](https://jira.corp.adobe.com/browse/MWPW-127882)
**Test URLs:**
- Before: [https://main--milo--adobecom.hlx.page/tools/floodgate/index.html](https://main--milo--adobecom.hlx.page/tools/floodgate/index.html?project=milo--adobecom&referrer=https%3A%2F%2Fadobe.sharepoint.com%2F%3Ax%3A%2Fr%2Fsites%2Fadobecom%2F_layouts%2F15%2FDoc.aspx%3Fsourcedoc%3D%257B4EBD6F30-D51F-419B-BD0A-7485D4081302%257D%26file%3Dsample_fg_project.xlsx%26action%3Ddefault%26mobileredirect%3Dtrue)
- After: [https://project-status--milo--sukamat.hlx.page/tools/floodgate/index.html](https://project-status--milo--sukamat.hlx.page/tools/floodgate/index.html?project=milo--adobecom&referrer=https%3A%2F%2Fadobe.sharepoint.com%2F% …
> MWPW-127882: FG Project Status

- libs/blocks/faas-config/faas-config.js
- libs/blocks/faas/utils.js
Resolves: [MWPW-128249](https://jira.corp.adobe.com/browse/MWPW-128249)
**Test URLs:**
- Before: https://main--milo--adobecom.hlx.page/tools/faas?martech=off
- after: https://faas-fix--milo--adobecom.hlx.page/tools/faas?martech=off
> [FAAS] Auto submit disable on config page.

- tools/floodgate/js/copy.js
- tools/floodgate/js/floodgate.js
* Copy action moved to a separate file for better organization
* No changes in business logic
Resolves: [MWPW-124572](https://jira.corp.adobe.com/browse/MWPW-124572)
**Test URLs:**
- Before: [https://main--milo--adobecom.hlx.page/tools/floodgate/index.html](https://main--milo--adobecom.hlx.page/tools/floodgate/index.html?project=milo--adobecom&referrer=https%3A%2F%2Fadobe.sharepoint.com%2F%3Ax%3A%2Fr%2Fsites%2Fadobecom%2F_layouts%2F15%2FDoc.aspx%3Fsourcedoc%3D%257B4EBD6F30-D51F-419B-BD0A-7485D4081302%257D%26file%3Dsample_fg_project.xlsx%26action%3Ddefault%26mobileredirect%3Dtrue)
- After: [https://copy-clean--milo--sukamat.hlx.page/tools/floodgate/index.html](https://copy-clean--milo--sukamat.hlx.page/tools/floodgate/index.html?project=milo--adobecom&referrer=https%3A%2F%2Fadobe.sharepoint …
> MWPW-124572: FG Copy action cleanup

- libs/blocks/faas/utils.js
- Adding auto response as exception as well for the configurator.
- Always setting Destination URL as absolute 
Resolves: 
- [MWPW-128249](https://jira.corp.adobe.com/browse/MWPW-128249)
- [MWPW-128242](https://jira.corp.adobe.com/browse/MWPW-128242)
> Adding auto response as exception as well.

- libs/blocks/table-of-contents/table-of-contents.css
* Modifies marquee when paired with toc block to more closely match business.adobe.com current styles
* Fixes additional stylistic issues with mobile in order to match b.a.com 
* b.a.com url for parity example: https://business.adobe.com/solutions/customer-journeys.html
Resolves: [MWPW-127876](https://jira.corp.adobe.com/browse/MWPW-127876)
**Test URLs:**
- Before: https://main--milo--adobecom.hlx.page/drafts/slavin/solutions?martech=off
- After: https://slavin-toc-gap-bug--milo--adobecom.hlx.page/drafts/slavin/solutions?martech=off
> MWPW-127876: Gap issue Table of Contents

- libs/blocks/carousel/carousel.css
Adding transition for carousel: Fade, None. 
Related ticket: [MWPW-122649](https://jira.corp.adobe.com/browse/MWPW-122649)
**Test URLs:**
- https://carousel-transition-update--milo--adobecom.hlx.page/drafts/seanchoi/carousel-demo?martech=off
*Other part of ticket will be addressed by @rgclayton .
> MWPW-122649 - Carousel transition update

- tools/send-to-caas/send-utils.js
Resolves: [MWPW-128387](https://jira.corp.adobe.com/browse/MWPW-128387)
**Test URLs:**
- After: https://c3-128387--milo--adobecom.hlx.page/?martech=off
> MWPW-128387 Remove custom date logic

- tools/floodgate/js/project.js
- tools/floodgate/js/utils.js
* Fixes an issue when reading the project file with excel path
Resolves: [MWPW-128369](https://jira.corp.adobe.com/browse/MWPW-128369)
**Test URLs:**
- Before: [https://main--milo--adobecom.hlx.page/tools/floodgate/index.html](https://main--milo--adobecom.hlx.page/tools/floodgate/index.html?project=milo--adobecom&referrer=https%3A%2F%2Fadobe.sharepoint.com%2F%3Ax%3A%2Fr%2Fsites%2Fadobecom%2F_layouts%2F15%2FDoc.aspx%3Fsourcedoc%3D%257B4EBD6F30-D51F-419B-BD0A-7485D4081302%257D%26file%3Dsample_fg_project.xlsx%26action%3Ddefault%26mobileredirect%3Dtrue)
- After: [https://fg-excel--milo--sukamat.hlx.page/tools/floodgate/index.html](https://fg-excel--milo--sukamat.hlx.page/tools/floodgate/index.html?project=milo--adobecom&referrer=https%3A%2F%2Fadobe.sharepoint.com%2F%3Ax%3A%2Fr%2Fsites%2Fadobec …
> MWPW-128369: Excel FG issue fix

- libs/blocks/locale-nav/locale-nav.js
Resolves: [MWPW-128597](https://jira.corp.adobe.com/browse/MWPW-128597)
**TEST URLs**:
- Before: https://main--milo--adobecom.hlx.page/tools/locale-nav?ref=main&repo=bacom&owner=adobecom&referrer=https://adobe.sharepoint.com/:w:/r/sites/adobecom/_layouts/15/Doc.aspx?sourcedoc=%7BEC9ED2CF-7532-43C6-B9B2-608CBCF524E7%7D&cid=c8cdcb33-9caa-41ce-bc09-d96e87f215b7
- After: https://locales-search-fix--milo--adobecom.hlx.page/tools/locale-nav?ref=main&repo=bacom&owner=adobecom&referrer=https://adobe.sharepoint.com/:w:/r/sites/adobecom/_layouts/15/Doc.aspx?sourcedoc=%7BEC9ED2CF-7532-43C6-B9B2-608CBCF524E7%7D&cid=c8cdcb33-9caa-41ce-bc09-d96e87f215b7
> fixing the case issue in search

- libs/blocks/table-metadata/table-metadata.css
- libs/blocks/table-metadata/table-metadata.js
- libs/blocks/table/table.css
- libs/blocks/table/table.js
* Add your
* Specicic
Resolves: [MWPW-129568](https://jira.corp.adobe.com/browse/MWPW-129568)
**Test URLs:**
> MWPW-129568 : Table Block

- libs/blocks/global-navigation/blocks/search/gnav-search.js
- libs/blocks/global-navigation/utilities/getUserEntitlements.js
- libs/blocks/global-navigation/utilities/getUserEventHistory.js
- libs/blocks/global-navigation/utilities/utilities.js
Address some of the PR feedback in https://github.com/adobecom/milo/pull/601
**Test URLs:**
- Before: https://main--milo--adobecom.hlx.page/drafts/ramuntea/prev/gnav-refactor?martech=off
- After: https://feedback-gnav--milo--mokimo.hlx.page/drafts/ramuntea/gnav-refactor?martech=off
> Address Viktor's gnav PR feedback

- tools/floodgate/js/project.js
* Fixes an issue where promote status was not correctly updating with start/end data after first run
Resolves: [MWPW-129961](https://jira.corp.adobe.com/browse/MWPW-129961)
**Test URLs:**
- Before: [https://main--milo--adobecom.hlx.page/tools/floodgate/index.html](https://main--milo--adobecom.hlx.page/tools/floodgate/index.html?project=milo--adobecom&referrer=https%3A%2F%2Fadobe.sharepoint.com%2F%3Ax%3A%2Fr%2Fsites%2Fadobecom%2F_layouts%2F15%2FDoc.aspx%3Fsourcedoc%3D%257B2A168441-F440-4552-A195-90CB12A418A0%257D%26file%3Ddemo-fg.xlsx%26action%3Ddefault%26mobileredirect%3Dtrue)
- After: [https://promote-status--milo--sukamat.hlx.page/tools/floodgate/index.html](https://promote-status--milo--sukamat.hlx.page/tools/floodgate/index.html?project=milo--adobecom&referrer=https%3A%2F%2Fadobe.share …
> MWPW-129961: promote status update

- libs/utils/utils.js
remove ost from AUTO_BLOCKS
Resolves: [MWPW-130197](https://jira.corp.adobe.com/browse/MWPW-130197)
**Test URLs:**
- Before: https://main--milo--adobecom.hlx.page/drafts/ilyas/merch#
- After: https://mwpw-130197--milo--adobecom.hlx.page/drafts/ilyas/merch#
> MWPW-130197 remove ost from AUTO_BLOCKS

- libs/blocks/quiz/quiz.css
- libs/blocks/quiz/quiz.js
- libs/blocks/quiz/quizcontainer.js
- libs/blocks/quiz/quizoption.js
- libs/blocks/quiz/utils.js
**Not at all ready for the main branch**
* First commit towards the quiz block
* Basic styling
* Includes handling of `questions.xlsx`, `strings.xlsx`, and `results.xlsx`
Resolves: Multiple stories
**Test URLs:**
Before - https://main--milo--adobecom.hlx.page/drafts/sabya/quiz-2/?martech=off
After - https://uarq--milo--sabyamon.hlx.page/drafts/sabya/quiz-2/?martech=off
> UAR Quiz Block Initial Commit

- libs/blocks/global-navigation/blocks/profile/dropdown.css
* Add your
* Specicic
**Test URLs:**
> MWPW-130523 - Provide proper text height in Profile Menu user details

- libs/blocks/footer/footer.js
* Matching footer content logic as gnav does by using contentRoot
**Test URLs:**
- Before: https://stage--dc--adobecom.hlx.live/acrobat/online/bad-url
- After: https://stage--dc--adobecom.hlx.live/acrobat/online/bad-url?milolibs=footer-fix
> Let the footer use contentRoot instead.

- libs/blocks/global-navigation/global-navigation.js
- libs/blocks/global-navigation/utilities/menu/menu.css
- libs/blocks/global-navigation/utilities/utilities.js
This addresses a first round of feedback from https://github.com/adobecom/milo/pull/705 regarding the footer block refactor.
Resolves: [MWPW-117909](https://jira.corp.adobe.com/browse/MWPW-117909)
**Test URLs:**
- Before: https://main--milo--adobecom.hlx.page/drafts/ramuntea/gnav-refactor?martech=off
- After: https://footer-refactor-review-1--milo--overmyheadandbody.hlx.page/drafts/ramuntea/gnav-refactor?martech=off
> [MWPW-117909] Footer refactor PR review 1

- libs/templates/404/404.js
> Minor 404 fix

- libs/blocks/article-header/article-header.css
- libs/blocks/article-header/article-header.js
* Bug fix for article header author image not displaying correct image.
* Article feature image update for screen size wider than 1440px
Resolves: [MWPW-129907](https://jira.corp.adobe.com/browse/MWPW-129907)
**Test URLs:**
- Before: https://main--blog--adobecom.hlx.page/jp/publish/2022/06/16/cc-design-adobefonts-partner-05-showa?martech=off
- After: https://main--blog--adobecom.hlx.page/jp/publish/2022/06/16/cc-design-adobefonts-partner-05-showa?milolibs=blog-article-header&martech=off
**Screen shot of problem areas before fix:**
* Author image not displaying if an author image exists. 
* Featured image getting cut off on larger screens
> MWPW-129907 - Blog Migration

- tools/floodgate/css/floodgate.css
- tools/floodgate/index.html
- tools/floodgate/js/floodgate.js
- Added Promote Publish Option for Promote Floodgate Modal
- Passing this to Promote Action in MiloFG AdobeIO Action
Resolves: [MWPW-124580](https://jira.corp.adobe.com/browse/MWPW-124580)
**Test URLs:**
- Before: https://main--milo--adobecom.hlx.page/tools/floodgate/index.html?project=milo--adobecom&referrer=https%3A%2F%2Fadobe.sharepoint.com%2F%3Ax%3A%2Fr%2Fsites%2Fadobecom%2F_layouts%2F15%2FDoc.aspx%3Fsourcedoc%3D%257B608F4D87-157E-48BF-AC47-2C5EDBD184FB%257D%26file%3Dbook.xlsx%26action%3Ddefault%26mobileredirect%3Dtrue
- After: https://main--milo--arshadparwaiz.hlx.page/tools/floodgate/index.html?project=milo--adobecom&referrer=https%3A%2F%2Fadobe.sharepoint.com%2F%3Ax%3A%2Fr%2Fsites%2Fadobecom%2F_layouts%2F15%2FDoc.aspx%3Fsourcedoc%3D%257B608F4D87-157E-48BF-AC47-2C5EDBD184FB%257D%26fi …
> MWPW-124580 - Promote Publish Milo changes

- libs/blocks/ost/ost.css
- libs/blocks/ost/ost.js
* consumes latest OST version
* optimizes OST for smaller screens.
Resolves: [MWPW-131637](https://jira.corp.adobe.com/browse/MWPW-131637)
**Test URLs:**
- Before: https://main--milo--adobecom.hlx.page/tools/ost?token=
- After: https://mwpw-131637--milo--yesil.hlx.page/tools/ost?token=
> MWPW-131637: improve OST for small screens

- tools/floodgate/index.html
- tools/floodgate/js/floodgate.js
* resolves the issue with triggering PromoteAction from MiloUI
Resolves: [MWPW-131804](https://jira.corp.adobe.com/browse/MWPW-131804)
**Test URLs:**
- Before: https://main--milo--adobecom.hlx.page/tools/floodgate/index.html?project=milo--adobecom&referrer=https%3A%2F%2Fadobe.sharepoint.com%2F%3Ax%3A%2Fr%2Fsites%2Fadobecom%2F_layouts%2F15%2FDoc.aspx%3Fsourcedoc%3D%257B608F4D87-157E-48BF-AC47-2C5EDBD184FB%257D%26file%3Dbook.xlsx%26action%3Ddefault%26mobileredirect%3Dtrue%26cid%3D56ea577f-07f0-4c48-aafe-225580a98204
- After: https://main--milo--arshadparwaiz.hlx.page/tools/floodgate/index.html?project=milo--adobecom&referrer=https%3A%2F%2Fadobe.sharepoint.com%2F%3Ax%3A%2Fr%2Fsites%2Fadobecom%2F_layouts%2F15%2FDoc.aspx%3Fsourcedoc%3D%257B608F4D87-157E-48BF-AC47-2C5EDBD184FB%257D%26file%3Dbook …
> MWPW-131804 - PromoteAction call fix from MiloUI

- libs/blocks/global-navigation/features/search/gnav-search.css
Affected browsers: Safari 15
Resolves: [MWPW-130480](https://jira.corp.adobe.com/browse/MWPW-130480)
**Test URLs:**
- After: https://mwpw-130480--milo--narcis-radu.hlx.page/drafts/narcis/default?martech=off
> Remove all margins from search input

- libs/blocks/global-navigation/utilities/menu/menu.js
Resolves: [MWPW-131852](https://jira.corp.adobe.com/browse/MWPW-131852)
**Test URLs:**
- After: https://mwpw-131852--milo--narcis-radu.hlx.page/drafts/narcis/default?martech=off
> [MWPW-131852] Remove footer highlight when element is collapsed on mobile

- libs/blocks/bulk-publish/bulk-publish.js
- support a request parameter (`limit`) to dynamically set the maximum number of URL entries
Resolves: [MWPW-125675](https://jira.corp.adobe.com/browse/MWPW-125675)
**Test URLs:**
- Before: https://main--milo--adobecom.hlx.page/tools/bulk-publish?martech=off&limit=25
- After: https://bulk-limit--milo--adobecom.hlx.page/tools/bulk-publish?martech=off&limit=25
> MWPW-125675 - [Core] Milo Bulk Publish

- tools/floodgate/js/floodgate.js
* Refactored Toggle publishpromote visibility
Resolves: [MWPW-124580](https://jira.corp.adobe.com/browse/MWPW-124580)
**Test URLs:**
- Before: https://main--milo--adobecom.hlx.page/tools/floodgate/index.html?project=milo--adobecom&referrer=https%3A%2F%2Fadobe.sharepoint.com%2F%3Ax%3A%2Fr%2Fsites%2Fadobecom%2F_layouts%2F15%2FDoc.aspx%3Fsourcedoc%3D%257B608F4D87-157E-48BF-AC47-2C5EDBD184FB%257D%26file%3Dbook.xlsx%26action%3Ddefault%26mobileredirect%3Dtrue%26cid%3D56ea577f-07f0-4c48-aafe-225580a98204
- After: https://main--milo--arshadparwaiz.hlx.page/tools/floodgate/index.html?project=milo--adobecom&referrer=https%3A%2F%2Fadobe.sharepoint.com%2F%3Ax%3A%2Fr%2Fsites%2Fadobecom%2F_layouts%2F15%2FDoc.aspx%3Fsourcedoc%3D%257B608F4D87-157E-48BF-AC47-2C5EDBD184FB%257D%26file%3Dbook.xlsx%26action%3D …
> Publish Promote Visibility

- libs/blocks/gist/gist.css
- libs/blocks/gist/gist.js
- test/blocks/gist/gist.test.js
- test/blocks/gist/mocks/body.html
* Add gists to your page
Resolves: [MWPW-132152](https://jira.corp.adobe.com/browse/MWPW-132152)
**FYI: This will definitely not pass PSI as it is an embed in LCP of a 3rd party service.**
**Test URLs:**
- Before: https://main--milo--adobecom.hlx.page/drafts/cmillar/gist?martech=off
- After: https://gist--milo--adobecom.hlx.page/drafts/cmillar/gist?martech=off
> MWPW-132152 - Gist block

- tools/send-to-caas/bulk-publish-to-caas.js
- tools/send-to-caas/bulkpublisher.html
- tools/send-to-caas/send-utils.js
* Add your
* Specicic
**Test URLs:**
- After: https://c3-bulkhtml--milo--adobecom.hlx.page/?martech=off
> MWPW-132176 .html send to caas toggle

- tools/send-to-caas/send-utils.js
**Test URLs:**
- After: https://c3-entityid--milo--adobecom.hlx.page/?martech=off
> MWPW-132176 revert entityid change

- .github/workflows/email-release.yaml
To allow PRs from forks to be able to send emails.
> Update email release to use pull_request_target

- libs/blocks/text/text.css
Resolves: [MWPW-132468](https://jira.corp.adobe.com/browse/MWPW-132468)
**Test URLs:**
- Before: https://main--milo--adobecom.hlx.page/drafts/Soujanya/cc/textblock
- After: https://legalblockfix--milo--drashti1712.hlx.page/drafts/Soujanya/cc/textblock
> [MWPW-132468] Legal Block Content Not rendered in italics - Bug Fix

- libs/blocks/quiz/quiz.css
Resolves: https://jira.corp.adobe.com/browse/MWPW-124676 
**Test URLs:**
- Before: https://uar-integration--milo--adobecom.hlx.page/drafts/sabya/quiz-2/?martech=off
- After: https://uar-card-refinment--milo--fullcolorcoder.hlx.page/drafts/sabya/quiz-2/?martech=off
> [UAR] Card refinement 

- libs/blocks/marketo/marketo.css
Removing the form wrapper margin and adding styles for the checkboxes on demo pages. 
Resolves: [MWPW-131421](https://jira.corp.adobe.com/browse/MWPW-131421)
**Test URLs:**
- Before: https://main--milo--adobecom.hlx.page/drafts/slavin/marketo/digital-marketing-strategy
- After: https://mkto-form-style-update--milo--adobecom.hlx.page/drafts/slavin/marketo/digital-marketing-strategy
> MWPW-131421 - Marketo Form Style Changes 

- tools/floodgate/js/config.js
- tools/floodgate/js/utils.js
- Sends the list of paths to ignore to AIO action
Resolves: [MWPW-128375](https://jira.corp.adobe.com/browse/MWPW-128375)
**Test URLs:**
- Before: [https://main--milo--adobecom.hlx.page/tools/floodgate/index.html](https://main--milo--adobecom.hlx.page/tools/floodgate/index.html?project=milo--adobecom&referrer=https%3A%2F%2Fadobe.sharepoint.com%2F%3Ax%3A%2Fr%2Fsites%2Fadobecom%2F_layouts%2F15%2FDoc.aspx%3Fsourcedoc%3D%257BFF6518DD-EFA8-4676-9B57-892C6E3C2D2F%257D%26file%3Dlarge-50.xlsx%26action%3Ddefault%26mobileredirect%3Dtrue)
- After: [https://ignore-prom-list--milo--sukamat.hlx.page/tools/floodgate/index.html](https://ignore-prom-list--milo--sukamat.hlx.page/tools/floodgate/index.html?project=milo--adobecom&referrer=https%3A%2F%2Fadobe.sharepoint.com%2F%3Ax%3A%2Fr%2Fsites%2Fadobecom%2F_ …
> MWPW-128375: Ignore list for FG

- libs/blocks/quiz/quiz.js
- libs/blocks/quiz/quizoption.js
- libs/blocks/quiz/utils.js
- Adding analytics data for the next button.
- Updated the URL on card click.
- Refactored some code to use better naming conventions.
- Passing the analytics data to the result page as part of local storage.
Resolves: https://jira.corp.adobe.com/browse/MWPW-125274
**Test URLs:**
- Before: https://uar-integration--milo--adobecom.hlx.page/drafts/sabya/quiz-2/?martech=off
- After: https://uar-analytics--milo--sabyamon.hlx.page/drafts/sabya/quiz-2/?martech=off
> MWPW-125274 - UAR Analytics

- libs/blocks/marketo/marketo.js
- test/blocks/marketo/marketo.test.js
- test/blocks/marketo/mocks/body.html
* Allow setting or overriding specific from configurations.
* Decorating destination URL for form success redirect.
Resolves: [MWPW-129660](https://jira.corp.adobe.com/browse/MWPW-129660)
**Test URLs:**
- Before: https://main--milo--adobecom.hlx.page/drafts/bmarshal/mcz/marketo-block?martech=off
- After: https://bmarshal-marketo-overrides--milo--adobecom.hlx.page/drafts/bmarshal/mcz/marketo-block?martech=off
- Before: https://main--bacom--adobecom.hlx.live/uk/resources/reports/state-of-marketing-automation-b?martech=off
- After: https://main--bacom--adobecom.hlx.live/uk/resources/reports/state-of-marketing-automation-b?milolibs=bmarshal-marketo-overrides&martech=off
> MWPW-129660 Override Marketo Form Params

- libs/blocks/quiz/quiz.js
- libs/blocks/quiz/quizcontainer.js
* Add your
* Specific
Fragments is being added here for this quiz sample
[strings.json](https://adobe.sharepoint.com/:x:/r/sites/adobecom/Shared%20Documents/milo/drafts/borges/end-to-end/data/[strings.xlsx](https://adobe.sharepoint.com/:x:/r/sites/adobecom/Shared%20Documents/milo/drafts/borges/end-to-end/data/strings.xlsx?d=w159229762b524db9be5f101b035e9380&csf=1&web=1&e=OCNbCn)?d=w159229762b524db9be5f101b035e9380&csf=1&web=1&e=OCNbCn)
Resolves: https://jira.corp.adobe.com/browse/MWPW-127110
**Test URLs:**
- Before: https://uar-integration--milo--adobecom.hlx.page/drafts/borges/end-to-end/?martech=off&hideGeorouting=on
- After: https://uar-footer--milo--elaineskpt.hlx.page/drafts/borges/end-to-end/?martech=off&hideGeorouting=on
> MWPW-127110 - Quiz footer fragment based on string.json

- libs/utils/utils.js
Details coming, this is a cso situation. Blank pages 
Added a [nco](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Nullish_coalescing) to fix issue
Resolves: [MWPW-NUMBER](https://jira.corp.adobe.com/browse/MWPW-NUMBER) will be updated when ticket is filed
**Test URLs:**
Before: https://main--milo--overmyheadandbody.hlx.page/drafts/ramuntea/gnav-refactor?martech=off
After: https://update-htmlpostfix--milo--overmyheadandbody.hlx.page/drafts/ramuntea/gnav-refactor?martech=off
> MWPW-133653 Extra checks for decorateHTML

- libs/martech/martech.js
minor bug fix
**Test URLs:**
- Before: https://main--milo--adobecom.hlx.page/drafts/vgoodric/experiments/milo0005/originalv2?p0=
- After: https://targetutils--milo--adobecom.hlx.page/drafts/vgoodric/experiments/milo0005/originalv2?p0=
> Target Personalization: Correctly pass in utils

- libs/blocks/table/table.css
- libs/blocks/table/table.js
- rowheader role added on `section-head-title` cell for better accessibility.
- Fixed some style bugs : 
**Test URLs:**
- Before: https://main--milo--adobecom.hlx.page/docs/library/blocks/table?martech=off
- After: https://tableblock--milo--adobecom.hlx.page/docs/library/blocks/table?martech=off
> Minor Bug fix for Table block

- libs/blocks/quiz/quiz.js
- libs/blocks/quiz/utils.js
- test/blocks/quiz/mocks/quiz.html
- test/blocks/quiz/quiz.test.js
- Allows query param to drive json data sources 
- Refactored setting window.location.search params with layout effect for async 
- Fixes step indicator bug
Resolves:  [MWPW-126143](https://jira.corp.adobe.com/browse/MWPW-126143)
Resolves: [MWPW-131592](https://jira.corp.adobe.com/browse/MWPW-131592)
**Test URLs:**
Before: https://uar-integration--milo--adobecom.hlx.page/drafts/bradjohn/quiz-22/?martech=off
After: https://alternate-quiz-data--milo--fullcolorcoder.hlx.page/drafts/bradjohn/quiz-22/?quiz-data=alternate-data&martech=off
> [UAR] - Alternate quiz data

- libs/blocks/card/card.js
- test/blocks/card/card.test.js
* Add tracking attributes to links in card block
Resolves: [MWPW-134082](https://jira.corp.adobe.com/browse/MWPW-134082)
**Test URLs:**
- Before: https://main--milo--ruchika4.hlx.page/drafts/ruchika/card-analytics?martech=off
- After: https://analytics--milo--ruchika4.hlx.page/drafts/ruchika/card-analytics?martech=off
CC
- Before: https://main--cc--adobecom.hlx.page/creativecloud/animation/discover?martech=off
- After: https://main--cc--adobecom.hlx.page/creativecloud/animation/discover?milolibs=analytics--milo--ruchika4&martech=off
> Add tracking attributes to links in card block

- libs/blocks/ost/ost.js
Resolves: [MWPW-130838](https://jira.corp.adobe.com/browse/MWPW-130838)
> MWPW-130838 OST version rump up

- libs/blocks/global-navigation/global-navigation.js
Correctly localise global navigation logo links. Open the first link on both pages and see if the brand/logo are correctly localised
Resolves: [MWPW-133465](https://jira.corp.adobe.com/browse/MWPW-134299)
**Test URLs:**
- Before: - https://mwpw-134299--milo--mokimo.hlx.live?martech=off
- Before: https://main--bacom--adobecom.hlx.live/jp/customer-success-stories?headerqa=global-navigation
- After: https://main--bacom--adobecom.hlx.live/jp/customer-success-stories?headerqa=global-navigation&milolibs=mwpw-134299--milo--mokimo
> mwpw-134299 - localize global navigation logo links

- libs/blocks/share/share.js
- test/blocks/share/share.test.js
* Add tracking attributes in share block for analytics
Resolves: [MWPW-134287](https://jira.corp.adobe.com/browse/MWPW-134287)
**Test URLs:**
- Before: https://main--milo--adobecom.hlx.page/drafts/ruchika/share-analytics
- After: https://share-analytics--milo--ruchika4.hlx.page/drafts/ruchika/share-analytics
> Add tracking attributes in share block

- tools/send-to-caas/bulk-publish-to-caas.js
- tools/send-to-caas/bulkpublisher.html
- tools/send-to-caas/send-to-caas.js
- tools/send-to-caas/send-utils.js
Adds Content Type field for author to assign to the list of urls being published
Removes code in showConfirm that was specific to only the sidekick button.
> Bug: Fix bulk publisher

- libs/blocks/share/share.js
- test/blocks/share/share.test.js
* Adding a fix for an issue reported about tracking not working for copy link to clipboard in share block
Resolves: [MWPW-134287](https://jira.corp.adobe.com/browse/MWPW-134287)
**Test URLs:**
- Before: https://main--milo--adobecom.hlx.page/drafts/ruchika/share-analytics
- After: https://share-analytics--milo--ruchika4.hlx.page/drafts/ruchika/share-analytics
> Add tracking for copy link to clipboard in share block

- libs/utils/utils.js
- tools/send-to-caas/bulkpublisher.html
- tools/send-to-caas/send-to-caas.js
- tools/send-to-caas/send-utils.js
Adds auto-detection of contentType if not explicitly specified.
The contentType will be set to the first contentType found in tags.
Resolves: [MWPW-134412](https://jira.corp.adobe.com/browse/MWPW-134412)
**Test URLs:**
N/A for caas tools
> MWPW-134412 Fix sidekick send-to-caas

- .eslintrc.js
- libs/features/personalization/add-preview-to-config.js
- libs/features/personalization/manifest-utils.js
- libs/features/personalization/personalization.js
- libs/features/personalization/preview.js
- libs/martech/martech.js
- libs/utils/utils.js
* Remove no-cycle warning.
* Remove passing of utils and import instead
* Fix loading of preview.css
**Test URLs:**
- After: https://loadpreviewcss--milo--adobecom.hlx.page/?martech=off
> Personalization cleanup

- libs/blocks/columns/columns.css
- libs/blocks/columns/columns.js
Resolves: [MWPW-134655](https://jira.corp.adobe.com/browse/MWPW-134655)
**Test URLs:**
- Before: https://main--milo--adobecom.hlx.page/drafts/klee/test-table?martech=off
- After: https://MWPW-134655--milo--adobecom.hlx.page/drafts/klee/test-table?martech=off
> Rename table to columns-table to avoid conflicting table block's css.

- libs/blocks/aside/aside.css
- libs/blocks/table-metadata/table-metadata.js
- libs/blocks/table/table.css
- libs/blocks/table/table.js
- libs/features/icons/icons.js
- libs/utils/utils.js
- test/blocks/table/mocks/body.html
- test/blocks/table/table.test.js
* Issue fixed with duplicated icon rendered on fragments
* Not loading icon issues due to async.
* Other table style issue on mobile fixed when it has only 2 columns.
Resolves: 
- [MWPW-134676](https://jira.corp.adobe.com/browse/MWPW-134676)
- [MWPW-133904](https://jira.corp.adobe.com/browse/MWPW-133904)
- [MWPW-134073](https://jira.corp.adobe.com/browse/MWPW-134073)
- https://adobe-mwp.slack.com/archives/C03B0BUA75E/p1690483368480649
**Test URLs:**
- Before: https://main--milo--adobecom.hlx.page/drafts/rclayton/double-icon?martech=off
- After: https://MWPW-133904--milo--adobecom.hlx.page/drafts/rclayton/double-icon?martech=off
- Before: https://main--bacom--adobecom.hlx.page/products/product-analytics/pricing?martech=off
- After: …
> [MWPW-133904] Fixing duplicated icon issue and other table issues

- libs/blocks/global-navigation/utilities/utilities.js
Adding more context to a few lana logs we have been seeing. [MWPW-134861](https://jira.corp.adobe.com/browse/MWPW-134861)
**Test URLs:**
- Before: https://main--milo--adobecom.hlx.page/drafts/ramuntea/gnav-refactor?martech=off#
- After: https://add-more-gnav-lana-logs--milo--mokimo.hlx.page/drafts/ramuntea/gnav-refactor?martech=off#
> Add gnav-source to gnav lana logs

- libs/blocks/quiz/utils.js
Fixing the issue of the first rule getting picked when there was more than one rule with the same number of grouping.
Resolves: https://jira.corp.adobe.com/browse/MWPW-134131
**Test URLs:**
- Before: https://uar-integration--milo--adobecom.hlx.page/drafts/sabya/quiz-issue/?martech=off&hideGeorouting=on
- After: https://uar-same-number-group--milo--sabyamon.hlx.page/drafts/sabya/quiz-issue/?martech=off&hideGeorouting=on
> MWPW-134131 - Fixing issue when there are more than one rule with same number of grouping

- libs/blocks/global-navigation/features/profile/dropdown.js
- libs/features/personalization/personalization.js
Adds event for gnav logout: `feds:signOut`
Resolves: [MWPW-131211](https://jira.corp.adobe.com/browse/MWPW-131211)
**Test URLs:**
- After: https://clearls--milo--adobecom.hlx.page/?martech=off
> MWPW-131211 Clear entitlements from localStorage on logout

- libs/blocks/figure/figure.js
* fix issue of video not loading in figure block
Resolves: [MWPW-129910](https://jira.corp.adobe.com/browse/MWPW-129910)
**Test URLs:**
- Before: https://main--milo--adobecom.hlx.page/drafts/ruchika/figure?martech=off
- After: https://figureblock--milo--ruchika4.hlx.page/drafts/ruchika/figure?martech=off
> fix video loading issue in figure block

- libs/blocks/figure/figure.js
* Fix issue of video not loading in figure block intermittently
Resolves: [MWPW-135364](https://jira.corp.adobe.com/browse/MWPW-135364)
**Test URLs:**
- Before: https://main--milo--adobecom.hlx.page/drafts/ruchika/video-figureblock?martech=off
- After: https://figure-block--milo--ruchika4.hlx.page/drafts/ruchika/video-figureblock?martech=off
> fix issue of video not loading in figure block

- libs/blocks/modal/modal.css
- libs/blocks/modal/modal.js
* Geo routing popup overlaps commerce frame modal.
* To Match the functionality in adobe.com, The geo routing popup has been sent behind the commerce-frame modal.
Resolves: [MWPW-135206](https://jira.corp.adobe.com/browse/MWPW-135206)
**Test URLs:**
- Before: https://stage--cc--adobecom.hlx.page/drafts/ruchika/discover1#animate
- After: https://stage--cc--adobecom.hlx.page/drafts/ruchika/discover1?milolibs=MWPW-135206--milo--sharath-kannan#animate
> Mwpw 135206 geo routing popup is displayed on top of the commerce iframe modal.

- libs/blocks/action-item/action-item.css
- libs/blocks/action-item/action-item.js
- libs/blocks/action-scroller/action-scroller.css
- libs/blocks/action-scroller/action-scroller.js
- libs/blocks/icon-block/icon-block.css
- test/blocks/action-item/action-item.test.js
- test/blocks/action-item/mocks/body.html
- test/blocks/action-scroller/action-scroller.test.js
- test/blocks/action-scroller/mocks/body.html
New consonant blocks for building a set of clickable images with adjoining buttons, icons, and text.
1. Action Item Block: block for rendering an image with wrapped link with a few variants for floating buttons and icons.
2. Action Scroller Block: block for putting action items in a horizontal scrolling container with variant for navigation.
Resolves: [MWPW-129922](https://jira.corp.adobe.com/browse/MWPW-129922)
**Test URLs:**
- Before: https://main--milo--adobecom.hlx.page/drafts/sarchibeque/action-blocks?martech=off
- After: https://sarchibeque-actions-blocks--milo--adobecom.hlx.page/drafts/sarchibeque/action-blocks?martech=off
> MWPW-129922 - Consonant Actions Blocks

- libs/blocks/fragment/fragment.js
- libs/utils/utils.js
#_dnt with other link features (#_blank, #_dnb) was not working.
Resolves: [MWPW-135413](https://jira.corp.adobe.com/browse/MWPW-135413)
**Test URLs:**
- After: https://dntlinks--milo--adobecom.hlx.page/?martech=off
> MWPW-135413 Support multiple link features

- libs/features/georoutingv2/georoutingv2.js
- test/features/georoutingv2/georoutingv2.test.js
* Modify hideGeorouting cookie 
* More discussion regarding the request can be seen here https://adobe-mwp.slack.com/archives/C03HAU5SU2E/p1686757083623149
Resolves: [MWPW-128543](https://jira.corp.adobe.com/browse/MWPW-128543)
**Test URLs:**
- Before: https://main--milo--adobecom.hlx.page/au/drafts/ruchika/document16?georouting=off
- After: https://hide-georouting--milo--ruchika4.hlx.page/au/drafts/ruchika/document16?georouting=off
> Modify Hide Georouting Cookie

- libs/blocks/ost/ost.js
* Add your
* Specific
Resolves: [MWPW-130835](https://jira.corp.adobe.com/browse/MWPW-130835 )
**Test URLs:**
- Before: https://main--milo--adobecom.hlx.page/tools/ost?milolibs=local#?martech=off
- After: https://MWPW-130835--milo--adobecom.hlx.page/tools/ost?martech=off
> MWPW-130835 search osi in OST

- libs/blocks/firefly/firefly-api-conversations.js
* Add your
* Specific
**Test URLs:**
> minor updates to llm recommendations

- libs/utils/utils.js
- test/utils/richresults.test.js
**Test URLs:**
- After: https://fix-failing-tests--milo--narcis-radu.hlx.page/drafts/narcis/default?martech=off
> Fix failing tests

- tools/floodgate/js/utils.js
The data will be read and used by the AdobeIO service.
Resolves: [MWPW-131688](https://jira.corp.adobe.com/browse/MWPW-131688)
**Test URLs:**
- Before: [https://main--milo--adobecom.hlx.page](https://main--milo--adobecom.hlx.page/tools/floodgate/index.html?project=cc--adobecom&referrer=https%3A%2F%2Fadobe.sharepoint.com%2F%3Ax%3A%2Fr%2Fsites%2Fadobecom%2F_layouts%2F15%2FDoc.aspx%3Fsourcedoc%3D%257BE569F70E-CBDD-4376-B9C8-527CE7329B69%257D%26file%3Dfg-cc.xlsx%26action%3Ddefault%26mobileredirect%3Dtrue)
- After: [https://mwpw-131688--milo--adobecom.hlx.page](https://mwpw-131688--milo--adobecom.hlx.page/tools/floodgate/index.html?project=cc--adobecom&referrer=https%3A%2F%2Fadobe.sharepoint.com%2F%3Ax%3A%2Fr%2Fsites%2Fadobecom%2F_layouts%2F15%2FDoc.aspx%3Fsourcedoc%3D%257BE569F70E-CBDD-4376-B9 …
> MWPW-131688: FG support for other drives

- libs/blocks/quiz/quiz.css
*Fixing the responsive behavior for the quiz button
https://jira.corp.adobe.com/browse/MWPW-135125
Bahavior for mobile
Button should be 100% as per design 
Space for tablet and button size
Space for Desktop
cleaned double style
Resolves: https://jira.corp.adobe.com/browse/MWPW-135125
**Test URLs:**
- Before: https://uar-integration--milo--adobecom.hlx.page/drafts/borges/end-to-end/?
- After: https://quiz-buttonresponsive--milo--elaineskpt.hlx.page/drafts/borges/end-to-end/
> MWPW-135125 Quiz button fix 

- tools/floodgate/js/floodgate.js
Updates the payload to match the latest changes made for the FG status API.
Resolves: [MWPW-135603](https://jira.corp.adobe.com/browse/MWPW-135603)
**Test URLs:**
- Before: [https://main--milo--adobecom.hlx.page/tools/floodgate/index.html](https://main--milo--adobecom.hlx.page/tools/floodgate/index.html?project=milo--adobecom&referrer=https%3A%2F%2Fadobe.sharepoint.com%2F%3Ax%3A%2Fr%2Fsites%2Fadobecom%2F_layouts%2F15%2FDoc.aspx%3Fsourcedoc%3D%257B4EBD6F30-D51F-419B-BD0A-7485D4081302%257D%26file%3Dsample_fg_project.xlsx%26action%3Ddefault%26mobileredirect%3Dtrue)
- After: [https://mwpw-135603--milo--adobecom.hlx.page/tools/floodgate/index.html](https://mwpw-135603--milo--adobecom.hlx.page/tools/floodgate/index.html?project=milo--adobecom&referrer=https%3A%2F%2Fadobe.sharepoint.com%2F%3Ax%3A …
> MWPW-135603: FG Status API payload update

- libs/blocks/marketo/marketo.js
* Removes scroll when clicking on or tabbing to fields on desktop
* Keeps scroll functionality on mobile
* Keeps scroll functionality on all devices when clicking submit with errors
Resolves: [MWPW-135595](https://jira.corp.adobe.com/browse/MWPW-135595)
**Test URLs:**
- Before: https://main--milo--adobecom.hlx.page/drafts/bmarshal/mcz/marketo-block?martech=off
- After: https://methomas-marketo-scroll--milo--adobecom.hlx.page/drafts/bmarshal/mcz/marketo-block?martech=off
BACOM:
- Before: https://main--bacom--adobecom.hlx.live/uk/resources/reports/state-of-marketing-automation-b?martech=off
- After: https://main--bacom--adobecom.hlx.live/uk/resources/reports/state-of-marketing-automation-b?milolibs=methomas-marketo-scroll&martech=off
> MWPW-135595 Marketo - Remove focus scroll on desktop

- libs/blocks/bulk-publish/bulk-publish-utils.js
- libs/blocks/bulk-publish/bulk-publish.css
- libs/blocks/bulk-publish/bulk-publish.js
- test/blocks/bulk-publish/bulk-publish-utils.test.js
* Add bulk index option to bulk publish
* Update status timestamps to reflect the time of request
Resolves: [MWPW-134632](https://jira.corp.adobe.com/browse/MWPW-134632)
**Test URLs:**
- Before: https://main--milo--adobecom.hlx.page/tools/bulk-publish?martech=off
- After: https://bmarshal-bulk-index--milo--adobecom.hlx.page/tools/bulk-publish?martech=off
- Before: https://main--bacom--adobecom.hlx.live/tools/bulk-publish?martech=off
- After: https://main--bacom--adobecom.hlx.live/tools/bulk-publish?martech=off&milolibs=bmarshal-bulk-index
> MWPW-134632 Bulk Index

- libs/blocks/carousel/carousel.js
- libs/blocks/table/table.js
- libs/blocks/tabs/tabs.js
- libs/features/personalization/preview.js
- libs/utils/utils.js
- test/blocks/table/table.test.js
Prevents possible typos from breaking things.
Also fixes some linting errors.
**Test URLs:**
- After: https://miloevents--milo--adobecom.hlx.page/?martech=off
> Use constants for milo events

- libs/blocks/article-feed/article-feed.js
- libs/blocks/featured-article/featured-article.css
- libs/blocks/featured-article/featured-article.js
* Set category link to be asynchronously created
**Context:**
That category link is generated by loading taxonomy then looking up the category and associated link. Loading taxonomy was set to await which was blocking the block from loading until complete.
Moved all the category link details to load after all the other block content is in place and set category link to load asynchronously to avoid blocking. 
Resolves: No ticket
**Test URLs**
- Before: https://main--milo--adobecom.hlx.page/drafts/rclayton/blog-migration/blog-samples/test-pages/?martech=off
- After: https://featured-article-timing--milo--adobecom.hlx.page/drafts/rclayton/blog-migration/blog-samples/test-pages/?martech=off
**Blog Test URLs:**
- Before: https://main--blog--adobecom.hlx.live/?martech=off
- After: …
> [Blog Migration] Featured Article LCP help

- libs/blocks/ost/ost.js
The ost version is changed in milo to consume the latest changes.
* OST version changed to 1.14.0
Resolves: [MWPW-134916](https://jira.corp.adobe.com/browse/MWPW-134916)
**Test URLs:**
- Before: https://main--milo--adobecom.hlx.page/tools/ost?martech=off
- After: https://mwpw-134916--milo--sharath-kannan.hlx.page/tools/ost?martech=off
> ost version changed in milo

- tools/loc/rollout.js
Codepen: https://codepen.io/amitio/full/BavQXYQ
https://wiki.corp.adobe.com/pages/viewpage.action?spaceKey=WP4&title=Regional+Edits+-+Merge+Logic
> New Merge strategy

- libs/blocks/columns/columns.js
- libs/blocks/merch/merch.js
- libs/martech/attributes.js
* Add tracking attributes for links and buttons in merch and columns block
Resolves: [MWPW-136280](https://jira.corp.adobe.com/browse/MWPW-136280)
**Test URLs:**
Milo:
- Before: https://main--milo--adobecom.hlx.page/drafts/ruchika/merch
- After: https://merch-analytics--milo--ruchika4.hlx.page/drafts/ruchika/merch
CC
- Before: https://main--cc--adobecom.hlx.page/creativecloud/file-types/image/raster/heic-file
- After: https://main--cc--adobecom.hlx.page/creativecloud/file-types/image/raster/heic-file?milolibs=merch-analytics--milo--ruchika4
> Add analytics tracking attributes for columns and merch

- libs/blocks/quiz/quiz.css
- libs/blocks/quiz/quiz.js
- libs/blocks/quiz/quizoption.js
* Accessibility adjustments added to quiz option markup
* Quiz options can now be tabbed to with the keyboard
* Quiz options can be activated with space or enter keys
* Focus is reset to the top of the quiz when moving to the next question
Resolves: [MWPW-125774](https://jira.corp.adobe.com/browse/MWPW-125774)
**Test URLs:**
- Before: https://uar-integration--milo--adobecom.hlx.page/drafts/delta/app-recommender-test/?martech=off
- After: https://mwpw-125774-quiz-accessibility--milo--colloyd.hlx.page/drafts/delta/app-recommender-test/?martech=off
> MWPW-125774 - Quiz block accessibility

- libs/blocks/caas-config/caas-config.css
This PR resolves the issue reported on Jira ticket  MWPW-131760 where the max-height of the accordion is limiting the number of elements an author can add.
Resolves: [MWPW-131760](https://jira.corp.adobe.com/browse/MWPW-131760)
**Test URLs:**
- Before: [Content as a Service - Thursday, August 3, 2023 at 15:24 (no-lazy)](https://milo.adobe.com/tools/caas#eyJhbmFseXRpY3NUcmFja0ltcHJlc3Npb24iOmZhbHNlLCJhbmFseXRpY3NDb2xsZWN0aW9uTmFtZSI6IiIsImFuZExvZ2ljVGFncyI6W3siaW50cmFUYWdMb2dpYyI6Ik9SIiwiYW5kVGFncyI6WyJjYWFzOmNvbnRlbnQtdHlwZS9yZXBvcnQiLCJjYWFzOmNvbnRlbnQtdHlwZS92aWRlbyIsImNhYXM6Y29udGVudC10eXBlL2FydGljbGUiLCJjYWFzOmNvbnRlbnQtdHlwZS93ZWJpbmFyIiwiY2Fhczpjb250ZW50LXR5cGUvaW5mb2dyYXBoaWMiLCJjYWFzOmNvbnRlbnQtdHlwZS9lYm9vayIsImNhYXM6Y29udGVudC10eXBlL2d1aWRlIiwiY2Fhczpjb250ZW50LXR5cGUvd2hpdGUtcGFw …
> MWPW-131760: fixes max-height limiting number of entries

- libs/blocks/accordion/accordion.js
- test/blocks/accordion/accordion.test.js
- test/blocks/accordion/mocks/body.html
Changes:
- Changed the `daa-ll` attribute of the accordion button to the format that was requested in the ticket.
Resolves: [MWPW-135027](https://jira.corp.adobe.com/browse/MWPW-135027)
**Test URLs:**
- Before: https://main--milo--adobecom.hlx.page/drafts/ratko/accordion
- After: https://accordion-analytics--milo--zagi25.hlx.page/drafts/ratko/accordion
> Changed accordion analytics tracking

- libs/blocks/marquee/marquee.js
Update marquee videos to work with new inline fragments ( #1242 )
Resolves: [MWPW-135675](https://jira.corp.adobe.com/browse/MWPW-135675)
Homepage test url:
- Before: https://homepage-brick--homepage--adobecom.hlx.live/homepage/index-loggedout
- After: https://homepage-brick--homepage--adobecom.hlx.live/homepage/index-loggedout?milolibs=marqinlinefrag
**Test URLs:**
- Before: https://main--milo--adobecom.hlx.page/drafts/tat28144/regional-edits/marqueevideo?martech=off
- After: https://marqinlinefrag--milo--adobecom.hlx.page/drafts/tat28144/regional-edits/marqueevideo?martech=off
> MWPW-135675 Fix marquee video

- .github/workflows/run-nala.yml
* Adds PRs URL, Branch, Repo, and Org details to GitHub environment variables,
* These are required to `run-nala` test job on PR branch
Resolves: [MWPW-136624](https://jira.corp.adobe.com/browse/MWPW-136624)
**Test URLs:**
- Before: https://main--milo--adobecom.hlx.page/drafts/nala/blocks/icon/document
- After: https://main--milo--adobecom.hlx.page/drafts/nala/blocks/icon/document
> MWPW-136624 | Update run-nala.yml 

- libs/blocks/quiz/quiz.js
Resolves quiz.js feedback in PR #1264 
**Test URLs:**
- Before: https://uar-integration--milo--adobecom.hlx.page/drafts/xiasun/quiz-2/?martech=off
- After: https://quizjs-refactor--milo--fullcolorcoder.hlx.page/drafts/xiasun/quiz-2/?martech=off
> PR 1264 quiz.js feedback refactor

- libs/utils/utils.js
Quickly adding quiz and quiz-results blocks to utils.js list. 
Resolves [MWPW-136688](https://jira.corp.adobe.com/browse/MWPW-136688)
> MWPW-136688 Added quiz and quiz results to MILO_BLOCKS

- libs/blocks/quiz-results/quiz-results.js
- test/blocks/quiz-results/quiz-results.test.js
Resolves quiz-results.js feedback in PR #1264
**Test URLs:**
- Before: https://uar-integration--milo--adobecom.hlx.page/drafts/xiasun/quiz-2/?martech=off
- After: https://mwpw-115213-quiz-results-feedback--milo--colloyd.hlx.page/drafts/xiasun/quiz-2/?martech=off
Follow a quiz all the way through to view the quiz results page
> PR 1264 quiz_results.js feedback

- libs/blocks/quiz-results/quiz-results.css
- libs/blocks/quiz/quiz.js
Addressing review comments on #1264
Creating Uber App Recommender a.k.a. Quiz.
Data Model - https://wiki.corp.adobe.com/pages/viewpage.action?spaceKey=WEBT&title=UAR+Excel+Data+Model
Resolves: https://jira.corp.adobe.com/browse/MWPW-115213
Test URLs:
Before: https://uar-integration--milo--adobecom.hlx.page/drafts/xiasun/quiz-2/?martech=off
After: https://mwpw-115213-comments--milo--echampio-at-adobe.hlx.page/drafts/xiasun/quiz-2/?martech=off
> MWPW-115213 - Addressing review comments

- libs/blocks/faas/utils.js
- test/blocks/faas/utils.test.js
* Localize the faas destination url
Resolves: [MWPW-136232](https://jira.corp.adobe.com/browse/MWPW-136232)
**Test URLs:**
- Before: https://main--milo--adobecom.hlx.page/ae_ar/drafts/methomas/faas
- After: https://methomas-faas-thank-you--milo--adobecom.hlx.page/ae_ar/drafts/methomas/faas?martech=off
> MWPW-136232 Localize faas destination url

- tools/sidekick/config.json
This reverts commit 45aa2031d46dd16278699bd6c6564b384ba0155a.
The sidekick bug has been fixed by Franklin in v6.30.4, thus reverting the temp fix that was added.
https://github.com/adobe/helix-sidekick-extension/issues/550 
Resolves: [MWPW-137171](https://jira.corp.adobe.com/browse/MWPW-137171)
> Revert "MWPW-137171: Temp Fix for Sidekick (#1368)"

- libs/scripts/taxonomy.js
* Applies taxonomyRoot to tag links authored in the taxonomy.xlsx sheet
* Specifically fixes jp tag links on bacom blog
Resolves: [MWPW-136469](https://jira.corp.adobe.com/browse/MWPW-136469)
**Test URLs:**
(Regression)
- Before: https://main--milo--adobecom.hlx.page/drafts/methomas/taxonomy?martech=off
- After: https://methomas-jp-tags--milo--adobecom.hlx.page/drafts/methomas/taxonomy?martech=off
Bacom blog:
- Before: https://main--bacom-blog--adobecom.hlx.page/jp/blog/the-latest/dx-marketo-studio-smarthr
- After: https://main--bacom-blog--adobecom.hlx.page/jp/blog/the-latest/dx-marketo-studio-smarthr?milolibs=methomas-jp-tags
Adobe blog (regression):
- https://main--blog--adobecom.hlx.page/?milolibs=methomas-jp-tags
- https://main--blog--adobecom.hlx.page/en/publish/2023/08/15/discover-k …
> MWPW-136469 Fix authored tag link

- libs/blocks/quiz/quiz.js
Adds a more reliable signal to indicate last step of quiz is present for step indicators. 
Resolves: [MWPW-137456](https://jira.corp.adobe.com/browse/MWPW-137456)
**Test URLs:**
- Before: https://main--milo--adobecom.hlx.page/drafts/xiasun/quiz-2/?martech=off
- After: https://mwpw-137456-step-indicator-bugfix--milo--fullcolorcoder.hlx.page/drafts/xiasun/quiz-2/?martech=off
> MWPW-137456 refactored for last step detection

- libs/blocks/quiz/utils.js
* Renamed properties to make them more author friendly
Resolves: [MWPW-137651](https://jira.corp.adobe.com/browse/MWPW-137651)
**Test URLs:**
- Before: https://main--milo--adobecom.hlx.page/drafts/xiasun/quiz-2/?martech=off
- After: https://quiz-property-names--milo--colloyd.hlx.page/drafts/colloyd/quiz/?martech=off
> Quiz property name updates

- libs/blocks/how-to/how-to.css
Fixing how to ordered lists for RTL language pages.
Resolves: [MWPW-137755](https://jira.corp.adobe.com/browse/MWPW-137755)
**Test URLs:**
- Before: https://main--milo--adobecom.hlx.live/mena_ar/drafts/doreswam/how-to?martech=off
- After: https://mwpw-137755--milo--puruadobe.hlx.live/mena_ar/drafts/doreswam/how-to?martech=off
> MWPW-137755 Fix RTL text issue -how-to ordered lists

- libs/blocks/article-header/article-header.js
- test/blocks/article-header/article-header.test.js
* Remove invalid article header date red and yellow border in production
Resolves: [MWPW-137777](https://jira.corp.adobe.com/browse/MWPW-137777)
**Test URLs:**
- Before: https://main--milo--adobecom.hlx.page/drafts/bmarshal/article-header?martech=off
- After: https://bmarshal-prod-article-date--milo--adobecom.hlx.page/drafts/bmarshal/article-header?martech=off&env=prod
**BACOM Blog**
- Before: https://main--bacom-blog--adobecom.hlx.page/fr/drafts/staged-content/blog/how-to/eight-steps-to-creating-a-great-event-marketing-plan-template?martech=off&georouting=off
- After: https://main--bacom-blog--adobecom.hlx.page/fr/drafts/staged-content/blog/how-to/eight-steps-to-creating-a-great-event-marketing-plan-template?milolibs=bmarshal-prod-article-date&env=prod&martech=off&georouting=off
**Blog** …
> MWPW-137777 Show Article Header Dates in Production

- libs/blocks/marquee/marquee.css
Breaking marquee styles.
Reverts adobecom/milo#1454
> Revert "[MWPW-137523] Add dark and large styles for quiet marquee"

- libs/features/loc/rollout.js
- tools/loc/rollout.js
Resolves: [MWPW-136896](https://jira.corp.adobe.com/browse/MWPW-136896)
This PR copies loc changes to libs. This change skips adding anchors for Heading & Bookmarks in langstore version. This is done to have the link point to regional heading which is shown in preview by default.
> MWPW-136896: copying loc changes from tools/loc to libs

- libs/blocks/quiz/quiz.js
The preact code in the quiz block that renders the step indicator has a bogus dependency on a background image that belongs on the following background image element.
Resolves: MWPW-138713
Test URLs:
Before: https://uar-integration--milo--adobecom.hlx.page/drafts/quiz/quiz-2/?martech=off
After: https://mwpw-138713--milo--echampio-at-adobe.hlx.page/drafts/quiz/quiz-2/?martech=off
> MWPW-138713: [Q] Bogus dependency of step indicator on background

- libs/blocks/quiz-dynamic-tutorials/quiz-dynamic-tutorials-utils.js
- libs/blocks/quiz-dynamic-tutorials/quiz-dynamic-tutorials.css
- libs/blocks/quiz-dynamic-tutorials/quiz-dynamic-tutorials.js
* add two api calls
* add some basic for cards to update
Resolves: [MWPW-138337](https://jira.corp.adobe.com/browse/MWPW-138337)
**Test URLs:**
- Before: https://uar-ai--milo--adobecom.hlx.page/drafts/quiz/quiz-ai/?martech=off
- After: [https://uar-ai-local--milo--jackysun9.hlx.page/drafts/quiz/quiz-ai/?martech=off](https://uar-ai-local--milo--jackysun9.hlx.page/drafts/quiz/quiz-ai/?martech=off)
> MWPW-138337: initial commit for dynamic tutorials

- libs/blocks/quiz/quiz.js
- libs/blocks/quiz/quizoption.js
- libs/blocks/quiz/utils.js
Hacking the way to support fi code for userinput
> Adding fi code support in the question flow

- libs/blocks/quiz/quiz.js
Taking care of situations where the fi code does not match with the defined ficodes
> Hackathon - No fi code match usecase

- libs/blocks/quiz-dynamic-tutorials/quiz-dynamic-tutorials-utils.js
- libs/blocks/quiz-dynamic-tutorials/quiz-dynamic-tutorials.css
- libs/blocks/quiz-dynamic-tutorials/quiz-dynamic-tutorials.js
* Displays cards based on results from the api
* Prioritize local storage values from quizzes, but fallback to block settings if there's no local storage
Resolves: [MWPW-138337](https://jira.corp.adobe.com/browse/MWPW-138337)
**Test URLs:**
- Before: https://uar-ai--milo--adobecom.hlx.page/fragments/quiz/sample-uar-fragments/quiz-dynamic-tutorials/ps?quizKey=uar-ai&martech=off
- After: https://uar-ai-cards--milo--colloyd.hlx.page/fragments/quiz/sample-uar-fragments/quiz-dynamic-tutorials/ps?quizKey=uar-ai&martech=off
To test with local storage, set the following in your local storage:
* **Key**: uar-ai
* **Value**: {"mlFlowData":{"fiCodes":["photoshop_web", "adobe_photoshop_on_ipad", "photoshop_cc"],"userInput": "after effects"}}
> MWPW-138337 - Dynamic tutorial cards

- libs/blocks/quiz/quiz.css
- libs/blocks/quiz/quizoption.js
Adding styles to make the input a tad more stylish
> Adding styles to make the input a tad more stylish

- libs/blocks/marketo/marketo.js
* Improve form performance by loading earlier.
Resolves: [MWPW-138185](https://jira.corp.adobe.com/browse/MWPW-138185)
**Test URLs:**
- Before: https://main--milo--adobecom.hlx.page/drafts/bmarshal/marketo?martech=off
- After: https://bmarshal-marketo-loading--milo--adobecom.hlx.page/drafts/bmarshal/marketo?martech=off
**BACOM**
- Before: https://main--bacom--adobecom.hlx.page/resources/state-of-cx-research-report?martech=off
- After: https://main--bacom--adobecom.hlx.page/resources/state-of-cx-research-report?milolibs=bmarshal-marketo-loading
> MWPW-138185 Update Marketo Intersection Observer

- libs/blocks/gnav/gnav-contextual-search.js
- libs/blocks/gnav/gnav.css
- libs/blocks/gnav/gnav.js
* Prevent Enter from creating a new tab when advanced search is not set.
* Add no results placeholder.
Resolves: [MWPW-129984](https://jira.corp.adobe.com/browse/MWPW-129984)
**Test URLs:**
- Before: https://main--milo--adobecom.hlx.page/drafts/bmarshal/search/contextual-search?martech=off
- After: https://bmarshal-search-results--milo--adobecom.hlx.page/drafts/bmarshal/search/contextual-search?martech=off
**Bacom Blog**
- Before: https://main--bacom-blog--adobecom.hlx.page/drafts/bmarshal/?martech=off
- After: https://main--bacom-blog--adobecom.hlx.page/drafts/bmarshal/?martech=off&milolibs=bmarshal-search-results
**Blog**
- Before: https://main--blog--adobecom.hlx.page/?martech=off
- After: https://main--blog--adobecom.hlx.page/?martech=off&milolibs=bmarshal-search-results
> MWPW-129984 Contextual Search without Helpx

- libs/blocks/merch-card/merch-card.css
- libs/blocks/merch-card/merch-card.js
- test/blocks/merch-card/merch-card.test.js
Resolves: [MWPW-138882](https://jira.corp.adobe.com/browse/MWPW-138882)
this PR addresses  issues I found w.r.t styles.
fixes failing tests.
> PR review change suggestions

- libs/blocks/merch-card/merch-card.css
- libs/blocks/merch-card/merch-card.js
- test/blocks/merch-card/merch-card.test.js
Resolves: [MWPW-138882](https://jira.corp.adobe.com/browse/MWPW-138882)
> MWPW-138882: pr review feedbacks

- libs/deps/merch-card.js
Resolves: [MWPW-138882](https://jira.corp.adobe.com/browse/MWPW-138882)
> MWPW-138882: update merch-card web-component

- libs/blocks/preflight/panels/seo.js
* Fix canonical being absent hanging all other SEO checks
Resolves: [MWPW-139365](https://jira.corp.adobe.com/browse/MWPW-139365)
**Test URLs**
- Before: https://main--milo--adobecom.hlx.page/drafts/cmillar/sap-demo?martech=off
- After: https://preflight-canonical--milo--adobecom.hlx.page/drafts/cmillar/sap-demo?martech=off
**Steps to reproduce on main**
1. Open page.
2. Open preflight
3. Select SEO tab
4. Watch SEO checks spin (they will not complete)
**Steps to test**
1. Open page.
2. Open preflight
3. Select SEO tab
4. Watch SEO checks complete
> MWPW-139365 - SEO Tab Canonical Fix

- LICENSE
- libs/blocks/global-navigation/base.css
- libs/blocks/global-navigation/global-navigation.css
- libs/blocks/global-navigation/utilities/keyboard/utils.js
- libs/blocks/global-navigation/utilities/menu/menu.css
- libs/blocks/global-navigation/utilities/menu/menu.js
- test/blocks/global-navigation/global-navigation.test.js
- test/blocks/global-navigation/mocks/global-navigation-wide-column.plain.js
- test/blocks/global-navigation/mocks/large-menu-wide-column.plain.js
- test/blocks/global-navigation/test-utilities.js
Initial implementation detailed in https://github.com/adobecom/milo/pull/1532
> [MWPW-136943] Merge stage to main

- tools/loc/rollout.js
This allows accepting/rejecting a group of block together
Resolves: [MWPW-138179](https://jira.corp.adobe.com/browse/MWPW-138179)
**Test URLs:**
- Before: [Doc group individual accept reject](https://adobe.sharepoint.com/:w:/r/sites/adobecom/_layouts/15/Doc.aspx?sourcedoc=%7B836877D5-9CB5-4091-BB22-729F0B5B3705%7D&file=before.docx&action=default&mobileredirect=true)
- After: [Doc group accept/reject](https://adobe.sharepoint.com/:w:/r/sites/adobecom/_layouts/15/Doc.aspx?sourcedoc=%7B10C857B2-2C5D-417E-B92D-EBB079AB7E14%7D&file=after.docx&action=default&mobileredirect=true)
> MWPW-138179

- libs/blocks/merch-card/merch-card.css
- libs/blocks/merch-card/merch-card.js
- libs/blocks/merch-card/offer-selection.js
- test/blocks/merch-card/mocks/acrobat-card.html
- test/blocks/merch-card/offer-selection.test.js
Add Offer Selection to the Merch Card block.
User can switch between Offers radio buttons and trigger description, badge CTA and Price updates.
Resolves: [MWPW-136867](https://jira.corp.adobe.com/browse/MWPW-136867)
**Test URLs:**
- Before: https://main--milo--adobecom.hlx.live/drafts/mariia/PR/acrobatcard?martech=off
- After: https://offerselection--milo--adobecom.hlx.live/drafts/mariia/PR/acrobatcard?martech=off
> MWPW-136867: Merch-Card Offer Selection

- libs/blocks/merch-card/merch-card.js
- Introduces image variant of merch card 
Resolves: [MWPW-138522](https://jira.corp.adobe.com/browse/MWPW-138522)
**Test URLs:**
- Before: https://milo--milo--adobecom.hlx.page/drafts/axel/image-card
- After:https://mwpw-138522--milo--adobecom.hlx.page/drafts/axel/image-card
> MWPW-138522: Merch card image variant

- libs/blocks/quiz/quiz.css
* Fix card text alignment issue under mobile view
Resolves: [MWPW-140445](https://jira.corp.adobe.com/browse/MWPW-140445)
**Test URLs:**
- Before: https://main--milo--adobecom.hlx.live/drafts/quiz/solution-finder/?martech=off
- After: https://mwpw-140445--milo--jackysun9.hlx.live/drafts/quiz/solution-finder/?martech=off
Screenshot Before:
Screenshot After:
> MWPW-140445: Fix card text alignment issue under mobile view

- libs/features/personalization/entitlements.js
* Add your
* Specific
**Test URLs:**
> Update entitlement codes

- libs/blocks/quiz-results/quiz-results.css
* Fix multiple merch cards width issue on result page
Resolves: [MWPW-140499](https://jira.corp.adobe.com/browse/MWPW-140499)
**Test URLs:**
- Before: https://main--milo--adobecom.hlx.live/drafts/quiz/quiz-2/?martech=off
- After: https://mwpw-140499-jacky--milo--jackysun9.hlx.live/drafts/quiz/quiz-2/?martech=off
Debug path:
Before: 
https://main--milo--adobecom.hlx.live/drafts/quiz/quiz-2/?debug-results=%5B%7B%22selectedQuestion%22%3A%7B%22questions%22%3A%22q-category%22%2C%22max-selections%22%3A%223%22%2C%22min-selections%22%3A%221%22%7D%2C%22selectedCards%22%3A%7B%22photo%22%3Atrue%2C%22video%22%3Atrue%2C%22design%22%3Atrue%7D%7D%2C%7B%22selectedQuestion%22%3A%7B%22questions%22%3A%22q-rather%22%2C%22max-selections%22%3A%221%22%2C%22min-selections%22%3A%221%22%7D%2C%22selectedCards%22%3A% …
> MWPW-140499: fix multiple merch card width issue on result page

- libs/blocks/marquee/marquee.css
- libs/blocks/marquee/marquee.js
Reverts adobecom/milo#1654
Breaking layout on https://main--homepage--adobecom.hlx.page/ae_ar/homepage/index-loggedout
> Revert "MWPW-137523 - Allow dark quiet marquees"

- libs/blocks/ost/README.md
just docu updates, no before/after.
> document OST overrides

- libs/blocks/merch/README.md
start dev documentation for the merch block. no before/after diff.
After: https://3ch023-docu-merch--milo--adobecom.hlx.page/?martech=off
> Create merch block README.md

- libs/blocks/global-navigation/global-navigation.css
- libs/blocks/global-navigation/global-navigation.js
- libs/scripts/scripts.js
Integrate the Universal Navigation via metadata property.
**Note:** This is part of the Universal Navigation integration initiative. Additional PRs will be open against the `gnav` branch until full functionality is implemented.
VPN is needed to test
Resolves: [MWPW-140227](https://jira.corp.adobe.com/browse/MWPW-140227)
**Test URLs:**
- Before: https://gnav--milo--adobecom.hlx.page/drafts/narcis/default?martech=off
- After: https://utilnav--milo--narcis-radu.hlx.page/drafts/narcis/default?martech=off
> Integrate Universal Navigation

- CODEOWNERS
* Update magma codeowners: remove old teammates, add full team to all magma blocks, add owners for blog2milo blocks
> Update magma codeowners

- libs/blocks/tabs/tabs.css
- libs/blocks/tabs/tabs.js
- test/blocks/tabs/mocks/body.html
- test/blocks/tabs/tabs.test.js
* Improve mobile experience for tab scrolling by adding scroll indicator buttons.
Resolves: [MWPW-139379](https://jira.corp.adobe.com/browse/MWPW-139379)
**Test URLs:**
- Before: https://main--milo--adobecom.hlx.page/drafts/bmarshal/tabs-scrolling?martech=off
- After: https://bmarshal-tabs-scrolling--milo--adobecom.hlx.page/drafts/bmarshal/tabs-scrolling?martech=off
- Before: https://main--milo--adobecom.hlx.page/drafts/bmarshal/tabs-scrolling-dark?martech=off
- After: https://bmarshal-tabs-scrolling--milo--adobecom.hlx.page/drafts/bmarshal/tabs-scrolling-dark?martech=off
- Before: https://main--bacom--adobecom.hlx.page/?martech=off
- After: https://main--bacom--adobecom.hlx.page/?martech=off&milolibs=bmarshal-tabs-scrolling
> MWPW-139379 Improve Tab Scrolling for Mobile

- libs/blocks/tabs/tabs.css
- libs/blocks/tabs/tabs.js
- test/blocks/tabs/mocks/body.html
- test/blocks/tabs/tabs.test.js
Reverts adobecom/milo#1624 due to an issue found in https://jira.corp.adobe.com/browse/MWPW-141245
> Revert "MWPW-139379 Improve Tab Scrolling for Mobile"

- .github/workflows/run-nala-milolibs.yaml
PR includes 
1.    Provide a GitHub action workflow to support to run nala tests on different Env and Milo libs combination
2.    Examples:
- https://main--project--owner.hlx.page/?milolibs=local (prod code, stage content)
- https://main--project--owner.hlx.live/?milolibs=local (prod code, prod content)
**Workflow screenshot:**
Resolves: [MWPW-141223](https://jira.corp.adobe.com/browse/MWPW-141223)
**Test URLs:**
- Before: https://main--milo--adobecom.hlx.page
- After: https://main--milo--adobecom.hlx.page
> [MILOLIBS RUN : MWPW-141223] Provide support to run nala tests on a given milo libs

- libs/blocks/global-navigation/global-navigation.css
- libs/blocks/global-navigation/global-navigation.js
Pick up Universal Navigation integration from https://github.com/adobecom/milo/pull/1690
**Test URLs:**
- After: https://gnav--milo--adobecom.hlx.page/?martech=off
> Universal Navigation

- libs/blocks/quiz-results/quiz-results.js
- libs/blocks/quiz/utils.js
- test/blocks/quiz/quiz.test.js
- test/blocks/quiz/utils.test.js
* Remove the locale from the quiz key in the URL
* continue to use quiz key with locale in the background
* normalize other chars and use lowercase key and value in URL
Resolves: [MWPW-141446](https://jira.corp.adobe.com/browse/MWPW-141446)
**Test URLs:**
- Before: https://uar-integration--milo--adobecom.hlx.page/drafts/quiz/quiz-2/?martech=off
- After: https://mwpw-141446--milo--jackysun9.hlx.page/drafts/quiz/quiz-2/?martech=off
> MWPW-141446: Remove the locale from the quiz key in the URL; continue to use it in the background; normalize other chars

- libs/blocks/global-navigation/global-navigation.js
- libs/scripts/scripts.js
This PR changes the IETF language tag, for Norway, that is sent as config to the universal navigation.
Resolves: [MWPW-141609](https://jira.corp.adobe.com/browse/MWPW-141609)
**Before:**
**After:**
**Milo:**
- Before:  https://gnav--milo--adobecom.hlx.page/no/drafts/sghimpos/gnav-refactor-1-1
- After: https://mwpw-141609-unav-no-localization--milo--robert-bogos.hlx.page/no/drafts/sghimpos/gnav-refactor-1-1
> MWPW-141609: Universal navigation NO localization tag

- libs/blocks/global-navigation/global-navigation.js
This PR changes the expected `dev` value for `config.env.name` with `stage`.
> replaced dev env with stage for unav

- test/blocks/merch-card/merch-offer-select.test.js
Fixing randomly failing tests. 
Resolves: [MWPW-141771](https://jira.corp.adobe.com/browse/MWPW-141771)
> MWPW-141771 fix tests.

- libs/blocks/merch-card/merch-card.css
- libs/deps/merch-card.js
Fixes outline CTAs not displaying (transparent) in dark sections.
Resolves: [MWPW-140539](https://jira.corp.adobe.com/browse/MWPW-140539)
**Test URLs:**
- Before: https://main--milo--adobecom.hlx.page/drafts/axel/bug-fixes/mwpw-140539?martech=off
- After: https://mwpw-140539--milo--axelcureno.hlx.page/drafts/axel/bug-fixes/mwpw-140539?martech=off
> MWPW-140539: Outline CTA merch card styles in dark section

- libs/blocks/global-navigation/global-navigation.js
**Test URLs:**
- After: https://gnav--milo--adobecom.hlx.page/drafts/narcis/default?martech=off
> Allow Profile Menu to show a local section

- libs/blocks/merch-card/merch-card.js
- libs/deps/merch-card.js
- test/blocks/merch-card/merch-card.test.js
- test/blocks/merch-card/mocks/mini-compare-chart.html
Resolves: [MWPW-141691](https://jira.corp.adobe.com/browse/MWPW-141691)
Includes:
* https://git.corp.adobe.com/wcms/tacocat.js/pull/520
**Test URLs:**
- Before: https://main--milo--adobecom.hlx.page/drafts/axel/mini-compare-chart?martech=off
- After: https://mwpw-141691--milo--yesil.hlx.page/drafts/axel/mini-compare-chart?martech=off
**CC**
https://main--cc--adobecom.hlx.page/drafts/axel/mini-compare-chart?milolibs=mwpw-141691--milo--yesil
> MWPW-141691: Merch card: align footer rows

- libs/blocks/merch-card/merch-card.css
Resolves: [MWPW-140867](https://jira.corp.adobe.com/browse/MWPW-140867)
**Test URLs:**
- Before: https://main--milo--adobecom.hlx.page/drafts/klee/test-layout/grouped/merch-cards?martech=off
- After: https://mwpw-140867--milo--yesil.hlx.page/drafts/klee/test-layout/grouped/merch-cards?artech=off
> MWPW-140867: remove conflicting padding

- libs/blocks/quiz-dynamic-tutorials/quiz-dynamic-tutorials-utils.js
- libs/blocks/quiz-dynamic-tutorials/quiz-dynamic-tutorials.js
- libs/blocks/quiz/quiz.js
- libs/blocks/quiz/utils.js
MWPW-139157,MWPW-139158:Ignore ficodes with low correlation &
MWPW-139422: new model api with product filters
* Ignore ficodes with low correlation
* Ignore tutorials with low correlation
* use new apis from model team with product filters
Resolves: 
[MWPW-139157](https://jira.corp.adobe.com/browse/MWPW-139157)
[MWPW-139158](https://jira.corp.adobe.com/browse/MWPW-139158)
[MWPW-139422](https://jira.corp.adobe.com/browse/MWPW-139422)
**Test URLs:**
- Before: https://uar-ai--milo--adobecom.hlx.page/drafts/quiz/quiz-ai/?martech=off
- After: https://uar-ai--milo--jackysun9.hlx.page/drafts/quiz/quiz-ai/?martech=off
How to test?
1. Ignore ficodes with low correlation, prob < 0.2 will fallback, so try to search "I am testing"
2. Ignore tutorials with low correlation, prob < 0.2 will drop, I am …
> Ignore ficodes with low correlation and new apis

- test/blocks/quiz-results/mocks/body.html
- test/blocks/quiz-results/mocks/fragments/basic-frag.plain.html
- test/blocks/quiz-results/quiz-results.test.js
* Unit tests to cover new tagging intoduced in this PR: https://github.com/adobecom/milo/pull/1778
Resolves: [MWPW-142027](https://jira.corp.adobe.com/browse/MWPW-142027)
**Test URLs:**
- Before: https://main--milo--adobecom.hlx.page/drafts/colloyd/quiz/?martech=off?martech=off
- After: https://mwpw-142027-results-analytics-unit-tests--milo--colloyd.hlx.page/drafts/colloyd/quiz/?martech=off
Testing notes: This is all unit tests, so if the unit tests pass on the PR, we should be good to go.
> MWPW-142027 - Unit tests for quiz-results tagging

- libs/blocks/global-navigation/global-navigation.js
Send correct analytics values
Resolves: [MWPW-142314](https://jira.corp.adobe.com/browse/MWPW-142314)
**Test URLs:**
- After: https://gnav--milo--narcis-radu.hlx.page/?martech=off
> [MWPW-142314] Send correct analytics values

- libs/blocks/merch/merch.css
- libs/blocks/merch/merch.js
Removed opacity 0 from CTA styles causing the text to be invisible
Resolves: [MWPW-142568](https://jira.corp.adobe.com/browse/MWPW-142568)
**Test URLs:**
- Before: https://main--milo--axelcureno.hlx.page/drafts/axel/mini-compare-chart
- After: https://MWPW-142568--milo--axelcureno.hlx.page/drafts/axel/mini-compare-chart
> Mwpw 142568: OST-generated Merch CTA text not displaying

- libs/blocks/icon-block/icon-block.css
- libs/blocks/icon-block/icon-block.js
- libs/blocks/merch-card/merch-card.css
- libs/blocks/merch-card/merch-card.js
- libs/blocks/merch-card/merch-offer-select.js
- libs/blocks/merch/merch.css
- libs/deps/merch-card.js
* Add your
* Specific
**Test URLs:**
> Main to Stage

- libs/features/webapp-prompt/webapp-prompt.css
- libs/features/webapp-prompt/webapp-prompt.js
- libs/scripts/delayed.js
This adds the remaining authoring logic required to build the PEP prompt.
Main story: [MWPW-141023](https://jira.corp.adobe.com/browse/MWPW-141023)
Minor bug: [MWPW-142619](https://jira.corp.adobe.com/browse/MWPW-142619)
Minor bug: [MWPW-142618](https://jira.corp.adobe.com/browse/MWPW-142618)
Log in on a desktop viewport and wait for the PEP prompt to be shown. Ensure the authored Sharepoint document content reflects well in the prompt.
**Milo:**
- Before: https://project-pep--milo--adobecom.hlx.page/drafts/ramuntea/pep-prompt?imsClientId=fedsmilo&martech=off
- After: https://project-pep--milo--overmyheadandbody.hlx.page/drafts/ramuntea/pep-prompt?imsClientId=fedsmilo&martech=off
> [MWPW-141023] PEP authoring

- head.html
- libs/martech/martech.js
- libs/utils/utils.js
Reverts adobecom/milo#1843
Placeholders broken.
> Revert "MWPW-142070 Performance improvements for target"

- libs/blocks/marquee/marquee.css
- libs/blocks/marquee/marquee.js
Reverts adobecom/milo#1867
Caused regression with static links.
> Revert "MWPW-142630 - [Marquee] media style CLS"

- head.html
- libs/martech/martech.js
- libs/utils/utils.js
Reverts adobecom/milo#1891
Intermittent issues with modals in a fragment loading
> Revert "MWPW-142070 MEP Target Performance Improvements"

- libs/blocks/caas-marquee/caas-marquee.js
* Add your
* Specific
**Test URLs:**
> Fixes eslint issues

- libs/blocks/caas-marquee-metadata/caas-marquee-metadata.js
- libs/blocks/caas-marquee/caas-marquee.css
- libs/blocks/caas-marquee/caas-marquee.js
New design of marquees where an author can author a center/left and right marquee.
Resolves: [MWPW-143460](https://jira.corp.adobe.com/browse/MWPW-NUMBER)
**Test URLs:**
- Before: https://main--homepage--adobecom.hlx.page/homepage/fragments/loggedout/tests/2024/q2/ace0860/marquee-viewer
- After: https://caas-mashup--homepage--adobecom.hlx.page/homepage/fragments/loggedout/tests/2024/q2/ace0860/marquee-viewer?milolibs=caas-mashup
- URL for testing:
- https://caas-mashup--milo--adobecom.hlx.page/
> UnRevert MWPW-143460: Add support for Mash-Up marquee 1924

- libs/blocks/merch-card/merch-card.js
- libs/blocks/merch-card/merch-offer-select.js
- libs/deps/merch-card.js
- libs/deps/merch-offer-select.js
- libs/deps/merch-quantity-select.js
Reverts adobecom/milo#1887
Reverting as this has been merged without following the process.
> Revert "MWPW-142003: Mini Compare Chart Mobile styling"

- libs/blocks/caas-marquee/caas-marquee.js
- libs/blocks/chart/chart.js
- libs/blocks/fragment/fragment.js
- libs/blocks/global-navigation/utilities/utilities.js
- libs/blocks/library-container-end/library-container-end.css
- libs/blocks/library-container-start/library-container-start.css
- libs/blocks/library-metadata/library-metadata.css
- libs/blocks/library-metadata/library-metadata.js
- libs/features/footer-promo.js
- libs/features/icons/icons.js
- libs/features/placeholders.js
- libs/utils/helpers.js
- test/blocks/chart/chart.test.js
- test/blocks/fragment/fragment.test.js
- test/blocks/fragment/mocks/body.html
- test/blocks/fragment/mocks/fragments/frag-cache.plain.html
- test/blocks/global-navigation/global-navigation.test.js
- test/blocks/global-navigation/test-utilities.js
- test/blocks/global-navigation/utilities/utilities.test.js
- test/features/icons/icons.test.js
- test/features/placeholders/placeholders.json
- test/features/placeholders/placeholders.test.js
- test/utils/helpers.test.js
- https://github.com/adobecom/milo/pull/1931
- https://github.com/adobecom/milo/pull/1970
- https://github.com/adobecom/milo/pull/1968
- https://github.com/adobecom/milo/pull/1977
- https://github.com/adobecom/milo/pull/1973
> [Release] Stage to Main

- .kodiak/config.yaml
Adds initial auto-ticketing for Kodiak issues found in Milo
Resolves: 
* [MWPW-143708](https://jira.corp.adobe.com/browse/MWPW-143708)
* [MWPW-143712](https://jira.corp.adobe.com/browse/MWPW-143712)
**Test URLs:**
- https://mwpw-143708--milo--adobecom.hlx.page/
> MWPW-143708 and MWPW-143712 add kodiak auto-ticketing

- libs/features/loc/fragments.js
- libs/features/loc/rollout.js
This PR copies loc changes to libs. 
Resolves: [MWPW-141354](https://jira.corp.adobe.com/browse/MWPW-141354) For V1
> copy loc v1 changes to libs for consumers

- libs/features/personalization/personalization.js
Fix 'replaceFragment' action not working on promo.
Resolves: https://jira.corp.adobe.com/browse/MWPW-145171
**Test URLs:**
- Before: https://main--milo--adobecom.hlx.page/drafts/mariia/promo/replace/page
- After: https://mwpw-145171-mepfix--milo--adobecom.hlx.page/drafts/mariia/promo/replace/page
**Homepage Test URLs:**
- Before: [JP Homepage](https://main--homepage--adobecom.hlx.page/jp/homepage/index-loggedout?mep=%2Fhomepage%2Ffragments%2Floggedout%2Fpromos%2F2024%2Frow%2Fsummit-24%2Fhp-summit-24-row-114997.json--all---%2Fhomepage%2Ffragments%2Floggedout%2Fpromos%2F2024%2Frow%2Fsummit-24%2Fhp-genstudio-24-row-113170.json--all---%2Fhomepage%2Ffragments%2Floggedout%2Fpromos%2F2024%2Frow%2Fsummit-24%2Fhp-summit-ffe-24-row-116493.json--all---%2Fhomepage%2Ffragments%2Floggedout%2Fpromos%2F20 …
> MWPW-145171: mep fix for replace action

- libs/blocks/locui/langs/view.js
* The total number of translated/rolled out documents was inconsistent with the total count delivered via the status response. This PR corrects that.
Resolves: [MWPW-144236](https://jira.corp.adobe.com/browse/MWPW-144236)
**Test URLs:**
- Before: https://locui--milo--adobecom.hlx.page/tools/loc?ref=main&repo=milo&owner=adobecom&host=milo.adobe.com&project=Milo&referrer=https%3A%2F%2Fadobe.sharepoint.com%2F%3Ax%3A%2Fr%2Fsites%2Fadobecom%2F_layouts%2F15%2FDoc.aspx%3Fsourcedoc%3D%257B08E1FC5E-2434-497D-9789-992E4190304A%257D%26file%3Delan-test.xlsx%26action%3Ddefault%26mobileredirect%3Dtrue
- After: https://ebartholomew-locui--milo--adobecom.hlx.page/tools/loc?ref=main&repo=milo&owner=adobecom&host=milo.adobe.com&project=Milo&referrer=https%3A%2F%2Fadobe.sharepoint.com%2F%3Ax%3A%2Fr%2Fsites%2 …
> MWPW-144236 - [locui] Fix inconsistency with total count

- libs/blocks/locui/actions/index.js
- libs/blocks/locui/utils/miloc.js
When a 500 internal server error is returned from the create project API call, parse the error message that is returned and set the status display with the message for the user.
Resolves: [MWPW-137053](https://jira.corp.adobe.com/browse/MWPW-137053)
**Test URLs:**
- Before: https://locui--milo--adobecom.hlx.page/tools/loc?ref=main&repo=milo&owner=adobecom&host=milo.adobe.com&project=Milo&referrer=https%3A%2F%2Fadobe.sharepoint.com%2F%3Ax%3A%2Fr%2Fsites%2Fadobecom%2F_layouts%2F15%2FDoc.aspx%3Fsourcedoc%3D%257Bdd05bc5c-ed6d-4241-a95f-7f37d1971993%257D%26action%3Deditnew?martech=off
- After: https://sarchibeque-mwpw-137035--milo--adobecom.hlx.page/tools/loc?ref=main&repo=milo&owner=adobecom&host=milo.adobe.com&project=Milo&referrer=https%3A%2F%2Fadobe.sharepoint.com%2F%3Ax%3A%2Fr%2Fsites%2Fad …
> MWPW-137053 - [LocUI v2] Display create project errors

- libs/blocks/quiz-entry/mlField.js
- libs/blocks/quiz-entry/quiz-entry.css
- libs/blocks/quiz-entry/quiz-entry.js
- libs/blocks/quiz-entry/quizoption.js
- libs/blocks/quiz-entry/utils.js
* Quiz Entry - Add option cards and text to the block
Resolves: [MWPW-144810](https://jira.corp.adobe.com/browse/MWPW-144810)
**Test URLs:**
- Before: https://quiz-entry-block--milo--adobecom.hlx.page/drafts/colloyd/quiz-entry/?martech=off
- After: https://quiz-entry-block--milo--jackysun9.hlx.page/drafts/colloyd/quiz-entry/?martech=off
> MWPW-144810: Quiz Entry - Add option cards and text to the block

- libs/blocks/modal/modal.css
Reverts adobecom/milo#2048
Reverting based on comments in 
https://github.com/adobecom/milo/pull/2107#pullrequestreview-1980989748
> Revert "MWPW-144813: Add 'xl-size' class for dialog-modal"

- libs/blocks/modal/modal.css
Reverts adobecom/milo#2112
- https://github.com/adobecom/milo/pull/2048 
**Test URLs:**
- Before:
https://main--milo--adobecom.hlx.live/drafts/mirafedas/all-modals#cci-all-apps-whats-included
- After:
https://revert-2112-revert-2048-mwpw-144813-whatsincluded-styles--milo--adobecom.hlx.page/drafts/mirafedas/all-modals#see-whats-included-xl
> Revert "Revert "MWPW-144813: Add 'xl-size' class for dialog-modal""

- .kodiak/config.yaml
Change default assignee to Silviu per Narcis' request. Also adds documentation in the file.
Resolves: [MWPW-143712](https://jira.corp.adobe.com/browse/MWPW-143712)
**Test URLs:**
- After: https://thedoc31-patch-1--milo--adobecom.hlx.page/?martech=off
> Update Kodiak config.yaml

- libs/blocks/quiz-entry/mlField.js
- libs/blocks/quiz-entry/quiz-entry.css
- libs/blocks/quiz-entry/quiz-entry.js
- libs/blocks/quiz-entry/quizoption.js
- libs/blocks/quiz-entry/utils.js
* Restores code optimization that was lost in previous PRs
Resolves: [MWPW-146243](https://jira.corp.adobe.com/browse/MWPW-146243)
**Test URLs:**
- Before: https://quiz-entry-block--milo--adobecom.hlx.page/drafts/colloyd/quiz-entry/?martech=off
- After: https://quiz-entry-optimization--milo--colloyd.hlx.page/drafts/colloyd/quiz-entry/?martech=off
> MWPW-146243 - Quiz entry code optimization

- libs/utils/utils.js
- https://github.com/adobecom/milo/pull/2124
> [Release to Main] 

- .github/workflows/enforce-labels.yml
Add the new zero impact label label to the enforce label workflow
**Test URLs:**
- After: https://add-zero-impact-label--milo--mokimo.hlx.live/?martech=off
> Add zero impact to the enforce labels workflow

- .github/workflows/pr-reminders.js
- .github/workflows/pr-reminders.yaml
Remind a PR initiator _once_ to:
- Pass all checks if they are not passing - [example message on PR](https://github.com/adobecom/milo/pull/2078#issuecomment-2022685278)
- Get their PR verified, if approved & checks passed - [example message  on PR](https://github.com/adobecom/milo/pull/2067#issuecomment-2022685437)
- Add the ready for stage label, verified & approved & checks passed - [example message on PR (this would be by the Github User not mine)](https://github.com/adobecom/milo/pull/2071#issuecomment-2022585786)
Output example of a dry local run:
```
Local execution SKIPPED: Commenting on #2078... This pull request is not passing all required checks. Please see [this discussion](https://github.com/orgs/adobecom/discussions/997) for information on how to get all checks passing. …
```
> MWPW-145709 - [Repo automation] Add PR reminders

- .github/workflows/enforce-labels.yml
- .github/workflows/mark-stale-prs.yaml
- .github/workflows/pr-reminders.js
- .github/workflows/pr-reminders.yaml
- libs/blocks/preflight/panels/martech.js
- libs/utils/utils.js
Zero Impact Release 
- https://github.com/adobecom/milo/pull/2091
- https://github.com/adobecom/milo/pull/2079
- https://github.com/adobecom/milo/pull/2072
- https://github.com/adobecom/milo/pull/2071
> [Release to Main]

- libs/deps/merch-card.js
> Revert "MWPW-136885: Merch Card Accessibility"

- libs/martech/martech.js
I created a PR recently https://github.com/adobecom/milo/pull/2140 that increased the timeout and improved error handling.  We're seeing some unexpected results and want to dig in a little further.  So I'm also adding the set timeout value to help us better analyze our results.
Fast follow for: [MWPW-146491](https://jira.corp.adobe.com/browse/MWPW-146491)
Test URLs:
After: https://meptimeoutv3--milo--adobecom.hlx.page/?martech=off
Page with Target on:
https://main--homepage--adobecom.hlx.page/homepage/index-loggedout
https://main--homepage--adobecom.hlx.page/homepage/index-loggedout?milolibs=meptimeoutv3
Note: this is listed as high priority because in Dexter, if a Target response came in quite late, the page would "flicker" but …
> MWPW-146491 Fast follow to add timeout value

- libs/blocks/aside/aside.css
- libs/blocks/card-horizontal/card-horizontal.css
Add RTL support for some notifications and horizontal cards on mobile and desktop.
Resolves: [MWPW-146756](https://jira.corp.adobe.com/browse/MWPW-146756)
**Test URLs:**
- Before: https://main--milo--adobecom.hlx.page/eg_ar/drafts/narcis/page?martech=off
- After: https://mwpw-146756--milo--narcis-radu.hlx.page/eg_ar/drafts/narcis/page?martech=off
**Horizontal cards**
- After: https://main--cc--adobecom.hlx.page/eg_ar/cc-shared/fragments/products/illustrator/what-can-you-create-in-illustrator?martech=off&milolibs=mwpw-146756--milo--narcis-radu
**Notifications**
- After: https://main--cc--adobecom.hlx.page/eg_ar/products/illustrator/pricing-info?martech=off&milolibs=mwpw-146756--milo--narcis-radu
> [MWPW-146756] Add support for RTL in aside notifications, horizontal cards

- libs/blocks/aside/aside.css
- libs/blocks/card-horizontal/card-horizontal.css
Reverts adobecom/milo#2167 as merged it by mistake. Will be raising main sync PR for this one after  https://github.com/adobecom/milo/pull/2168 is merged to main
> Revert "[MWPW-146756] Add support for RTL in aside notifications, horizontal cards"

- libs/blocks/aside/aside.css
- libs/blocks/card-horizontal/card-horizontal.css
Reintroduction of 
- https://github.com/adobecom/milo/pull/2167
> MWPW-146756] Add support for RTL in aside notifications, horizontal cards""

- libs/blocks/global-navigation/global-navigation.js
Reverts adobecom/milo#2123
Reverting this PR as the changes are getting reflected in the Release PR as well.
These changes can be merged once the Release PR gets merged
> Revert "MWPW-146129 App Launcher overlaps the menu in Unav in the devices"

- libs/blocks/mobile-app-banner/mobile-app-banner.js
* keep gnav sticky when branch banner is displayed
Resolves: [MWPW-146494](https://jira.corp.adobe.com/browse/MWPW-146494)
**Test URLs:**
- Before: https://main--milo--adobecom.hlx.page/drafts/ruchika/branch-io/branch-io-page1?martech=off
- After: https://stickygnav--milo--adobecom.hlx.page/drafts/ruchika/branch-io/branch-io-page1?martech=off
CC
- Before: https://main--cc--adobecom.hlx.page/drafts/ruchika/mobile-app-banner?martech=off
- After: https://main--cc--adobecom.hlx.page/drafts/ruchika/mobile-app-banner?milolibs=stickygnav&martech=off
> MWPW-146494-keep gnav sticky when branch banner is displayed

- libs/blocks/icon-block/icon-block.css
- libs/blocks/icon-block/icon-block.js
- libs/blocks/media/media.css
- libs/blocks/media/media.js
- libs/blocks/text/text.css
- libs/blocks/text/text.js
- test/blocks/icon-block/icon-block.test.js
- test/blocks/icon-block/mocks/body.html
- test/blocks/media/media.test.js
- test/blocks/media/mocks/body.html
- test/blocks/text/mocks/body.html
- test/blocks/text/text.test.js
Reverts adobecom/milo#2098
An issue has been found on stage hence reverting this PR. Please see details for issue related to the PR in comment section of https://github.com/adobecom/milo/pull/2203
> Revert "MWPW-144549 CTA alignment for Text, Icon, and Media Blocks"

- CODEOWNERS
**Test URLs:**
- After: https://tattva--milo--narcis-radu.hlx.page/?martech=off
> Update code owners for feds

- libs/utils/sidekick.js
* Moved the publish button to right side of the sidekick to help avoid accidentally clicking.
* Added a warning pop up message on hover.
Resolves: [MWPW-146126](https://jira.corp.adobe.com/browse/MWPW-146126)
**Test URLs:**
- Before: https://main--milo--adobecom.hlx.page/drafts/rclayton/test-template?martech=off
- After: https://sidekick-publish-alt--milo--adobecom.hlx.page/drafts/rclayton/test-template?martech=off
> Sidekick publish button updates

- libs/features/richresults.js
- test/utils/mocks/head-rich-results-article.html
- test/utils/richresults.test.js
We refactor feature to also allow Article. Zero impact because minor change to interface version.
Resolves: [MWPW-146782](https://jira.corp.adobe.com/browse/MWPW-146782)
**Test URLs:**
- Before: https://main--milo--adobecom.hlx.page/drafts/jck/test1?martech=off (NewsArticle)
- After: https://MWPW-146782-1--milo--hparra.hlx.live/drafts/hgpa/test/richresults/article?martech=off (Article)
Quick QA Test:
```js
window.origin
document.querySelector('meta[name="richresults"]')
Array.from(document.querySelectorAll('script[type="application/ld+json"]')).map((e) => e.innerText)
```
> MWPW-146782: feat(utils/richersults): Add Article support

- libs/blocks/quiz-entry/quiz-entry.css
- libs/blocks/quiz-entry/quizoption.js
Adds carousel functionality to quiz entry block
Resolves: [MWPW-144022](https://jira.corp.adobe.com/browse/MWPW-144022)
Todo: Style refinement and test coverage will follow this PR. 
**Test URLs:**
- Before: https://quiz-entry-block--milo--adobecom.hlx.page/drafts/colloyd/quiz-entry/
- After: [https://<branch>--milo--adobecom.hlx.page/?martech=off](https://quiz-entry-block--milo--fullcolorcoder.hlx.page/drafts/colloyd/quiz-entry/?martech=off)
> MWPW-144022: Quiz entry block

- libs/features/personalization/personalization.js
Prevent MEP errors from breaking the page
Resolves: [MWPW-147455](https://jira.corp.adobe.com/browse/MWPW-147455)
Broken page: https://main--cc--adobecom.hlx.page/products/illustrator
Fixed page with a 'warn' message: https://main--cc--adobecom.hlx.page/products/illustrator?milolibs=mepmuteerror
**Test URLs:**
- Before: https://main--cc--adobecom.hlx.page/products/illustrator
- After: https://main--cc--adobecom.hlx.page/products/illustrator?milolibs=mepmuteerror
- After: https://mepmuteerror--milo--adobecom.hlx.page/drafts/mariia/promo/replace/page
> MWPW-147455: Prevent MEP errors from breaking the page

- libs/deps/merch-card.js
Resolves: MWPW-147027
Fixes alignment of footer CTAs in Mini compare chart merch card when length of content is bigger than card width.
Resolves: [MWPW-147027](https://jira.corp.adobe.com/browse/MWPW-147027)
Test URL: https://main--cc--adobecom.hlx.live/eg_ar/products/illustrator?milolibs=MWPW-147027--milo--adobecom&martech=off
**Before**
**After**
**Test URLs:**
- Before: https://main--milo--adobecom.hlx.page/docs/library/kitchen-sink/merch-card?martech=off
- After: https://MWPW-147027--milo--adobecom.hlx.page/docs/library/kitchen-sink/merch-card?martech=off
> MWPW-147027: CTA flowing out of mini compare card (due to long strings)

- libs/features/footer-promo.js
- libs/utils/utils.js
- test/utils/utils.test.js
* Setup footer promo so it can be localized in locv2
* (No change to functionality)
Resolves: [MWPW-146845](https://jira.corp.adobe.com/browse/MWPW-146845)
**Test URLs:**
Regression only. Should be no difference in functionality.
- Before: https://main--milo--adobecom.hlx.page/drafts/methomas/footer-promo-page
- After: https://methomas-promo-footer-doc--milo--adobecom.hlx.page/drafts/methomas/footer-promo-page?martech=off
- Before: https://main--milo--adobecom.hlx.page/drafts/cmillar/footer-fragment-promo-thing
- After: https://methomas-promo-footer-doc--milo--adobecom.hlx.page/drafts/cmillar/footer-fragment-promo-thing?martech=off
> MWPW-146845 Setup Footer Promo for Localization

- test/blocks/marketo/mocks/marketo-utils.js
* Fix broken Marketo unit test introduced in #2200 
Resolves: [MWPW-146796](https://jira.corp.adobe.com/browse/MWPW-146796)
**Test URLs:**
N/A
> MWPW-146796 Fix Marketo unit test

- .github/workflows/merge-to-stage.js
**Test URLs:**
- After: https://add-squash-merge--milo--adobecom.hlx.live/?martech=off
> Squash merges

- .github/workflows/merge-to-stage.js
- .github/workflows/merge-to-stage.yaml
**Test URLs:**
- After: https://milo-bot-test--milo--adobecom.hlx.live/?martech=off
> Use a github app token for the auto merge to stage workflow

- .github/workflows/merge-to-stage.js
- .github/workflows/merge-to-stage.yaml
**Test URLs:**
- After: https://update-permissions--milo--adobecom.hlx.live/?martech=off
> Update github permissions to use the env token

- .github/workflows/merge-to-stage.js
- .github/workflows/merge-to-stage.yaml
**Test URLs:**
- After: https://milo-bot-testing--milo--adobecom.hlx.live/?martech=off
> Milo PR merge bot - add the correct permissions

- README.md
**Test URLs:**
- After: https://stage-automation-test--milo--adobecom.hlx.live/?martech=off
> Test the stage automation workflow

- libs/blocks/action-item/action-item.css
- libs/blocks/action-scroller/action-scroller.css
- libs/blocks/action-scroller/action-scroller.js
- libs/blocks/icon-block/icon-block.css
- libs/blocks/section-metadata/section-metadata.css
- test/blocks/action-scroller/action-scroller.test.js
- test/blocks/action-scroller/mocks/body.html
Reverts adobecom/milo#2237
As per messages in milo-stage there is a request to revert the PR 
Please see details for issue related to the PR in comment section of https://github.com/adobecom/milo/pull/2284
(Jira- MWPW-148020)
> Revert "MWPW-137282 - [Action Items] Centered in the grid/scroller"

- libs/blocks/merch/merch.css
- libs/blocks/merch/merch.js
- libs/blocks/modal/modal.merch.js
- test/blocks/modals/mocks/iframe.plain.html
- test/blocks/modals/modal.merch.test.js
> Revert "MWPW-147472: auto adjust commerce iframe"

- .github/workflows/label-zero-impact.js
Improve feedback for the zero impact github PR workflow
> [Github Workflow] Improve zero impact workflow logging

- libs/features/personalization/entitlements.js
- Add 2 properties to the entitlements object
- There are no stage counterparts yet
Resolves: [MWPW-148426](https://jira.corp.adobe.com/browse/MWPW-148426)
Duplicate ticket: [MWPW-147803](https://jira.corp.adobe.com/browse/MWPW-147803)
**Test URLs:**
- After: https://mep-free-users--milo--adobecom.hlx.page/?martech=off
> MWPW-148426 [MEP] Request for New Personalization Tag: Free users, individuals, US and CA

- libs/blocks/quiz-entry/quiz-entry.js
* Send mlField fiCodes with continue button click event
Resolves: [MWPW-149113](https://jira.corp.adobe.com/browse/MWPW-149113)
**Test URLs:**
- After: https://mwpw-149113--milo--jackysun9.hlx.page/drafts/quiz/quiz-entry/
> MWPW-149113: UAR Interactive Front Door click event not registering

- libs/blocks/quiz-entry/quiz-entry.js
* sending user prompts in ML field to Adobe Analytics
Resolves: [MWPW-147601](https://jira.corp.adobe.com/browse/MWPW-147601)
**Test URLs:**
- Before: https://main--milo--adobecom.hlx.page/drafts/quiz/quiz-entry/?martech=off
- After: https://stage--milo--jackysun9.hlx.page/drafts/quiz/quiz-entry/?martech=off&debug=quiz-entry
How to test:
1. use debug link: https://stage--milo--jackysun9.hlx.page/drafts/quiz/quiz-entry/?martech=off&debug=quiz-entry
2. check network log with filter "/ee"
3. You can also check the sending value in console log
> MWPW-147601: sending ML field text to Analytics

- libs/features/personalization/stage-entitlements.js
Adding id for stage
Resolves: [MWPW-150614](https://jira.corp.adobe.com/browse/MWPW-150614)
**Test URLs:**
- After: https://mepstagefreeuser--milo--adobecom.hlx.page/?martech=off
> MWPW-150614 [MEP] Stage - Request for New Personalization Tag: Free users, individuals, US and CA

- .github/workflows/helpers.js
- .github/workflows/mark-stale-prs.yaml
- .github/workflows/merge-to-main.js
- .github/workflows/merge-to-main.yaml
- .github/workflows/merge-to-stage.js
- .github/workflows/merge-to-stage.yaml
Merge PRs from stage->main automatically given 4 sign-offs, as long as it's monday-thursday 8AM UTC to 8PM UTC
Resolves: [MWPW-148050](https://jira.corp.adobe.com/browse/MWPW-148050)
**Test URLs:**
- Before: https://main--milo--mokimo.hlx.page/?martech=off
- After: https://merge-process--milo--mokimo.hlx.live/?martech=off
> MWPW-148050: auto merge stage to main

- test/utils/utils.test.js
This PR fixes the `Custom Link Actions` unit test failing from `utils.test.js`
**Milo:**
- Before: https://main--milo--robert-bogos.hlx.page/drafts/rbogos/page-default?martech=off
- After: https://fix-unit-tests--milo--robert-bogos.hlx.page/drafts/rbogos/page-default?martech=off
> Fixed failing unit tests

- libs/martech/martech.js
Currently in Milo MEP, the Target propositionDisplay call is not happenning after the Target propositions are rendered on the page.
This change is to make the Target propositionDisplay call from the MEP Martech.js file once the Target propositions are applied.
This wiki explains the changes in detail (Testing Instruction is available in this wiki):
https://wiki.corp.adobe.com/pages/viewpage.action?pageId=3169882054
Resolves: [MWPW-152627](https://jira.corp.adobe.com/browse/MWPW-152627)
> Martech codeupdate

- .github/workflows/label-zero-impact.js
- package-lock.json
This is a dependency update to address Kodiak stories, more details can be found in JIRA.
Resolves: [MWPW-151172](https://jira.corp.adobe.com/browse/MWPW-151172)
**Test URLs:**
- After: https://mwpw-151172-kodiak--milo--overmyheadandbody.hlx.page/?martech=off
> [MWPW-151172][Kodiak] Package updates

- libs/utils/utils.js
Set STAGE as default environment for all `graybox` URLs
Resolves: [MWPW-152676](https://jira.corp.adobe.com/browse/MWPW-152676)
**Test URLs:**
- After: https://graybox-stage--milo--narcis-radu.hlx.page/drafts/narcis/default?martech=off
> [MWPW-152676] Ensure all Graybox URLs use STAGE environment

- libs/blocks/graybox-promote/components/graybox-promote-lit.js
- libs/blocks/graybox-promote/graybox-promote.css
- tools/sidekick/config.json
> Mwpw 142558 graybox sidekick promote

- libs/features/richresults.js
- test/utils/mocks/head-rich-results-article.html
- test/utils/mocks/head-rich-results.html
- test/utils/richresults.test.js
Resolves: [MWPW-146782](https://jira.corp.adobe.com/browse/MWPW-146782)
**Test URLs:**
- Before: https://main--milo--adobecom.hlx.page/drafts/spandit/mwpw-146782-richresults?martech=off
- After: https://MWPW-146782--milo--spandit22.hlx.live/drafts/spandit/mwpw-146782-richresults?martech=off
- Check: `Array.from(document.querySelectorAll("script[type='application/ld+json']")).map((e) => JSON.parse(e.innerText))[0]`
> MWPW-146782: Add Description to Article richresults

- libs/blocks/table/table.css
- libs/blocks/table/table.js
* header button vertical alignment matches across all header cells
* content cell horizontal alignment matches what is set in headers, defaulting to center
* header style updates including: color, font-size, etc.
Resolves: [MWPW-151826](https://jira.corp.adobe.com/browse/MWPW-151826)
Resolves: [MWPW-152313](https://jira.corp.adobe.com/browse/MWPW-152313)
**Test URLs:**
- Before: https://table-review--milo--adobecom.hlx.page/drafts/colloyd/table/sample-table?martech=off
- After: https://table-header-and-cell-alignment--milo--colloyd.hlx.page/drafts/colloyd/table/sample-table?martech=off
> MWPW-151826 - Table header and cell alignment

- libs/blocks/caas/utils.js
* Add your
* Specific
**Test URLs:**
> Support pills

- libs/blocks/graybox-promote/components/graybox-promote-lit.js
This PR sets the default promote API endpoint to the PROD variant.
Resolves: [MWPW-153238](https://jira.corp.adobe.com/browse/MWPW-153238)
> [MWPW-153238] Default Graybox promote API to PROD endpoint

- libs/blocks/graybox-promote/components/graybox-promote-lit.js
This PR adds the POST api call that triggers the Graybox promote.
Resolves: [MWPW-153654](https://jira.corp.adobe.com/browse/MWPW-153654)
> [MWPW-153654] POST api call for promote

- libs/blocks/locui/loc/index.js
- libs/blocks/locui/utils/miloc.js
Adds support for the new Transcreate action.
Resolves: [MWPW-153573](https://jira.corp.adobe.com/browse/MWPW-153573)
> MWPW-153573 - [LocUI] Transcreate UI

- libs/blocks/marketo/marketo.css
* Fix missing Marketo button font
Resolves: [MWPW-152918](https://jira.corp.adobe.com/browse/MWPW-152918)
**Test URLs:**
- Before: https://main--milo--adobecom.hlx.page/drafts/bmarshal/mcz/marketo?martech=off
- After: https://bmarshal-marketo-font--milo--adobecom.hlx.page/drafts/bmarshal/mcz/marketo?martech=off
- Before: https://main--bacom--adobecom.hlx.live/fr/?martech=off
- After: https://main--bacom--adobecom.hlx.live/fr/?martech=off&milolibs=bmarshal-marketo-font
> MWPW-152918 Fix Marketo button font

- libs/blocks/graybox-promote/components/graybox-promote-lit.js
- tools/sidekick/config.json
This PR enables promote from an Excel file, instead of the JSON file.
Resolves: [MWPW-153224](https://jira.corp.adobe.com/browse/MWPW-153224)
Before: https://grayboxui--milo--adobecom.hlx.page/drafts/rbogos/page-default?martech=off
After: https://grayboxui--milo--robert-bogos.hlx.page/drafts/rbogos/page-default?martech=off
> [MWPW-153224] Promote from the excel file

- test/blocks/caas-config/caas-config.test.html
Fixes test so that it works on all platforms
Resolves: [MWPW-154556](https://jira.corp.adobe.com/browse/MWPW-154556)
**Test URLs:**
- After: https://caas-local-fail--milo--adobecom.hlx.page/?martech=off
> MWPW-154556 Update caas-config.test.html to work on all platforms

- libs/blocks/graybox-promote/components/graybox-promote-lit.js
- tools/sidekick/config.json
This PR adds sharepoint authentication for the Graybox promote feature.
Resolves: [MWPW-153223](https://jira.corp.adobe.com/browse/MWPW-153223)
Before: https://grayboxui--milo--adobecom.hlx.page/drafts/rbogos/page-default?martech=off
After: https://grayboxui--milo--robert-bogos.hlx.page/drafts/rbogos/page-default?martech=off
> [MWPW-153223] Sharepoint auth for Graybox promote

- CODEOWNERS
- libs/blocks/notification/notification.css
- libs/blocks/notification/notification.js
- libs/utils/decorate.js
- libs/utils/utils.js
- test/blocks/notification/mocks/body.html
- test/blocks/notification/notification.test.js
In an effort to overhaul the Aside block, certain variants of the Aside have been broken off into their own block: The Notification Block. These map to:
```
aside (notification) -> notification
aside (promo-bar) -> notification (ribbon)
aside (promo-bar, popup) -> notification (pill)
```
Furthermore, these new variants improve on the old ones in certain ways, such as the ability to remove the close button on non-sticky notifications, and fine-grained control over font sizes (l-heading, s-body, etc). Click the "After" links below to see full examples of each variant of the block.
Resolves: [MWPW-151863](https://jira.corp.adobe.com/browse/MWPW-151863), [MWPW-151832](https://jira.corp.adobe.com/browse/MWPW-151832), and [MWPW-151868](https://jira.corp.adobe.com/browse/MWPW-151868)
**Test …
> MWPW-151863 - 🆕 Notification Block

- libs/features/personalization/entitlements.js
* Add new tag for cc-paid
Resolves: [MWPW-143053](https://jira.corp.adobe.com/browse/MWPW-143053)
**Test URLs:**
- After: https://addccpaid--milo--adobecom.hlx.page/?martech=off
> MWPW-143053 [MEP] Request for New Personalization Tag - CC Paid

- libs/navigation/navigation.js
- test/navigation/bootstrapper.test.js
- test/navigation/navigation.test.js
* Fixing errors while importing dynamic files in test cases
**Test URLs:**
- After: https://feds-test--milo--bandana147.hlx.page/?martech=off
> Fix for errors in dynamically loaded scripts in test cases

- libs/blocks/locale-nav/locale-nav.js
Langstore locale now shows langstore/en files and properly generates links.
Resolves: [MWPW-128600](https://jira.corp.adobe.com/browse/MWPW-128600)
**Test URLs:**
- After: https://loc_langstore_128600--milo--adobecom.hlx.page/?martech=off
> MWPW-128600 Locale Tool: Langstore points to langstore/en

- libs/martech/martech.js
* Send additional information into the language object
Resolves: [MWPW-145131](https://jira.corp.adobe.com/browse/MWPW-145131)
**Test URLs:**
- After: https://mwpw-145131--milo--narcis-radu.hlx.page/drafts/narcis/default?martech=off
Note: to test, remove ?martech=off
> [MWPW-145131] Send locale and language code to analytics

- libs/blocks/locui/actions/index.js
- libs/blocks/locui/loc/index.js
- libs/blocks/locui/utils/url.js
Add a layer of validation for media files against URLs and fragment URLs on init and in fragment search.
Resolves: [MWPW-154891](https://jira.corp.adobe.com/browse/MWPW-154891)
**Test URLs:**
https://main--cc--adobecom.hlx.page/tools/loc?milolibs=sean-loc&ref=main&repo=cc&owner=aishwaryamathuria&host=www.adobe.com&project=Creative+Cloud&referrer=https%3A%2F%2Fadobe.sharepoint.com%2F%3Ax%3A%2Fr%2Fsites%2Fadobecom%2F_layouts%2F15%2FDoc.aspx%3Fsourcedoc%3D%257B684b46f2-c806-465e-8568-44f1bbb608e9%257D%26action%3Deditnew
> MWPW-154891 - [LocUI] Check if media in URL Validation

- .github/workflows/fg-sync-repos.yml
* Push sync for floodgate, skipping sync for excluded files.
Resolves: [MWPW-145389](https://jira.corp.adobe.com/browse/MWPW-145389)
**Test URLs:**
- After: https://bmarshal-push-sync--milo--adobecom.hlx.page/?martech=off
> MWPW-145389 Push sync for floodgate

- libs/martech/martech.js
Reverts adobecom/milo#2600
**Test URLs:**
- After: https://revert-2600-mwpw-145131--milo--adobecom.hlx.page/drafts/narcis/default?martech=off
> Revert "[MWPW-145131] Send locale and language code to analytics"

- libs/blocks/locui/url/tabs.js
- libs/blocks/locui/url/view.js
- libs/blocks/locui/utils/miloc.js
Update URL action button state when a sync to langstore is completed
Resolves: [MWPW-153586](https://jira.corp.adobe.com/browse/MWPW-153586)
**Test URLs:**
https://sean-loc--milo--adobecom.hlx.page/tools/loc?ref=main&repo=milo&owner=adobecom&host=milo.adobe.com&project=Milo&referrer=https%3A%2F%2Fadobe.sharepoint.com%2F%3Ax%3A%2Fr%2Fsites%2Fadobecom%2F_layouts%2F15%2FDoc.aspx%3Fsourcedoc%3D%257B1D94730C-C698-48C0-85E5-DBCA710C4150%257D%26file%3Dbranch%2520urls%25202.xlsx%26action%3Ddefault%26mobileredirect%3Dtrue%26wdsle%3D0
> MWPW-153586 - [LocUI] Get url status on sync to langstore

- .browserslistrc
- .github/workflows/label-zero-impact.js
Update the supported browser list based on NALA's [browser support matrix](https://wiki.corp.adobe.com/display/WP4/Test+Automation+Framework#browser--platform-support-matrix).
Resolves: [MWPW-150579](https://jira.corp.adobe.com/browse/MWPW-150579)
**Test URLs:**
- Before: https://main--milo--overmyheadandbody.hlx.page/?martech=off
- After: https://browserlist-update--milo--overmyheadandbody.hlx.page/?martech=off
> [MWPW-150579] Update supported browser list

- libs/blocks/graybox-promote/components/graybox-promote-lit.js
- libs/tools/sharepoint/login.js
- libs/tools/sharepoint/msal.js
- tools/sidekick/config.json
This PR is enhancing the promote feature to handle reading JSONs behind authentication. 
Resolves: [MWPW-156075](https://jira.corp.adobe.com/browse/MWPW-156075)
Before: https://grayboxui--milo--adobecom.hlx.page/drafts/rbogos/page-default?martech=off
After: https://mwpw-156075-graybox-auth--milo--robert-bogos.hlx.page/drafts/rbogos/page-default?martech=off
> [MWPW-156075] [Graybox] Enhance promote to read JSONs behind auth

- libs/navigation/bootstrapper.js
- libs/navigation/navigation.css
- libs/navigation/navigation.js
- test/navigation/bootstrapper.test.js
- test/navigation/navigation.test.js
* Adding standalone header support 
Resolves: [MWPW-155072](https://jira.corp.adobe.com/browse/MWPW-155072)
**Test URLs:**
- After: https://gnav--milo--adobecom.hlx.page/?martech=off
QA: https://adobecom.github.io/nav-consumer/navigation.html?env=stage&navbranch=gnav
> Standalone GNav for Non-Milo Consumers

- libs/blocks/marketo/marketo.js
- test/blocks/marketo/marketo.test.html
* Add authorable success section to display content without redirecting
* Guide: https://main--milo--adobecom.hlx.page/docs/authoring/marketo#one-page-experience
Resolves: [MWPW-142166](https://jira.corp.adobe.com/browse/MWPW-142166)
**Test URLs:**
- Before: https://main--milo--adobecom.hlx.page/drafts/bmarshal/one-page/one-page-video-stage?martech=off
- After: https://bmarshal-one-page--milo--adobecom.hlx.page/drafts/bmarshal/one-page/one-page-video-stage?martech=off
- Before: https://main--bacom--adobecom.hlx.live/drafts/bmarshal/one-page/one-page-video-stage?martech=off
- After: https://main--bacom--adobecom.hlx.live/drafts/bmarshal/one-page/one-page-video-stage?martech=off&milolibs=bmarshal-one-page
> MWPW-142166 One Page Gated

- libs/blocks/accordion/accordion.css
- libs/blocks/accordion/accordion.js
- libs/blocks/aside/aside.css
- libs/blocks/aside/aside.js
- libs/blocks/editorial-card/editorial-card.css
- libs/blocks/editorial-card/editorial-card.js
- libs/blocks/footer/footer.css
- libs/blocks/global-footer/global-footer.css
- libs/blocks/global-navigation/base.css
- libs/blocks/global-navigation/global-navigation.css
- libs/blocks/icon-block/icon-block.css
- libs/blocks/icon-block/icon-block.js
- libs/blocks/marquee/marquee.css
- libs/blocks/region-nav/region-nav.css
- libs/blocks/text/text.css
- libs/deps/caas.css
- libs/styles/rounded-corners.css
- libs/styles/styles.css
- Creates Spectrum 2 Integration Demo Page. This work includes token integration and related style adjustments for:
- `Marquee` 
- `Accordion`
- `Aside`
- adds `mobile-row-reverse` option: applies reverse order on mobile blocks  
- `Editorial card`
- adds `max-width` option: applies 376px max-width to editorial card
- `Icon block`
- adds black background to dark mode
- `Footer`
Resolves: [MWPW-151456](https://jira.corp.adobe.com/browse/MWPW-151456)
**Test URLs:**
- After: https://saasha-mwpw-151456-spectrum2-demo--milo--adobecom.hlx.page/drafts/ramuntea/spectrum-showcase
> MWPW-151456: Spectrum 2 Token Integration Demo

- test/blocks/modals/mocks/body.html
- test/blocks/modals/mocks/federal/geo.plain.html
- test/blocks/modals/modals.test.js
* Covering test case for federated modal
Resolves: [MWPW-154608](https://jira.corp.adobe.com/browse/MWPW-154608)
**Test URLs:**
- Before: https://main--milo--adobecom.hlx.page/document?martech=off
- After: https://mwpw-154608--milo--bandana147.hlx.page/document?martech=off
> Adding test case for federated modal

- libs/features/personalization/personalization.js
- libs/features/personalization/preview.js
* Massage prefix value and add to MEP config for use in placeholders and MEP button
* Add prefix as an option for placeholders to use
* Add prefix as a displayed value in MEP button
Resolves: [MWPW-156624](https://jira.corp.adobe.com/browse/MWPW-156624)
**Test URLs:**
- Before: https://main--cc--adobecom.hlx.page/th_en/products/indesign?mep=%2Fproducts%2Findesign.json--default---%2Fcc-shared%2Ffragments%2Ftests%2F2024%2Fq3%2Fintl0075%2Fintl0075.json--target-var1-challenger
- https://main--cc--adobecom.hlx.page/th_en/products/indesign?mep=%2Fproducts%2Findesign.json--default---%2Fcc-shared%2Ffragments%2Ftests%2F2024%2Fq3%2Fintl0075%2Fintl0075.json--target-var1-challenger
- After: https://main--cc--adobecom.hlx.page/th_en/products/indesign?milolibs=mepgeofolder&mep=%2Fproducts%2Findesign.jso …
> MWPW-156624 [MILO][MEP] Add locale prefix as an option for placeholder feature

- libs/blocks/marquee/marquee.css
- libs/features/placeholders.js
Resolves: [MWPW-155687](https://jira.corp.adobe.com/browse/MWPW-155687)
Adding placeholders to the window in an object called `mph` (MILO Place Holders).
This will when building blocks that have error states or status messages that need be localized and would be too burdensome to ask Web Publisher to maintain on a page to page basis.
**Test URLs:**
- After: https://mwpw-155687--milo--adobecom.hlx.page/?martech=off
> MWPW-155687

- libs/blocks/floodgateui/actions/index.js
- libs/blocks/floodgateui/floodgateui.css
Ability to find nested fragments. The test project contains a fragment that will return 4 nested fragments, levels deep.
Resolves: [MWPW-155604](https://jira.corp.adobe.com/browse/MWPW-155604)
**Test URL:**
https://main--cc--adobecom.hlx.page/tools/floodgate?milolibs=sean-loc&ref=main&repo=cc&owner=adobecom&host=www.adobe.com&project=Creative+Cloud&referrer=https%3A%2F%2Fadobe.sharepoint.com%2F%3Ax%3A%2Fr%2Fsites%2Fadobecom%2F_layouts%2F15%2FDoc.aspx%3Fsourcedoc%3D%257B3822da29-13ba-41a4-b597-345482d4a26d%257D%26action%3Deditnew#
> MWPW-155604 - [FloodgateUI] Find nested fragments

- libs/blocks/locui/actions/index.js
- libs/blocks/locui/loc/index.js
- libs/blocks/locui/utils/url.js
Another layer of validation against AEM Url formatting in the format validate function.
Resolves: [MWPW-155770](https://jira.corp.adobe.com/browse/MWPW-155770)
**Test URLs:**
https://sean-loc--milo--adobecom.hlx.page/tools/loc?ref=main&repo=milo&owner=adobecom&host=milo.adobe.com&project=Milo&referrer=https%3A%2F%2Fadobe.sharepoint.com%2F%3Ax%3A%2Fr%2Fsites%2Fadobecom%2F_layouts%2F15%2FDoc.aspx%3Fsourcedoc%3D%257B183689E0-DE1C-41A7-BE6F-CC16E477B2FC%257D%26file%3DBetter%2520Validation.xlsx%26action%3Ddefault%26mobileredirect%3Dtrue
> MWPW-155770 - [LocUI] AEM URL Validation

- libs/blocks/locui/utils/miloc.js
Pass loc ui url during create project. This will be stored in data.json and passed over.
Resolves: [MWPW-156265](https://jira.corp.adobe.com/browse/MWPW-156265)
**Test URLs:**
Before: https://locui-debug--milo--raga-adbe-gh.hlx.page/tools/loc?ref=main&repo=milo&owner=adobecom&host=milo.adobe.com&project=Milo&referrer=https%3A%2F%2Fadobe.sharepoint.com%2F%3Ax%3A%2Fr%2Fsites%2Fadobecom%2F_layouts%2F15%2FDoc.aspx%3Fsourcedoc%3D%257B21F1B612-F4BD-484C-8C0E-8D0DBEF3AC03%257D%26file%3Dmilocragatwo1.xlsx%26action%3Ddefault%26mobileredirect%3Dtrue
After: https://locui-debug--milo--raga-adbe-gh.hlx.page/tools/loc?ref=main&repo=milo&owner=adobecom&host=milo.adobe.com&project=Milo&referrer=https%3A%2F%2Fadobe.sharepoint.com%2F%3Ax%3A%2Fr%2Fsites%2Fadobecom%2F_layouts%2F15%2FDoc.aspx%3Fsourcedoc%3D%25 …
> MWPW-156265 - [LocUI] Pass loc ui url during create-project to loc service

- libs/blocks/adobetv/adobetv.js
- libs/blocks/figure/figure.js
- libs/blocks/video/video.js
- libs/utils/decorate.js
- test/blocks/adobetv/adobetv.test.js
- test/blocks/adobetv/mocks/body.html
- test/blocks/marquee/marquee.test.js
- test/blocks/video/mocks/body.html
- test/blocks/video/video.test.js
Reverts adobecom/milo#2750 - based on https://github.com/adobecom/milo/pull/2821#pullrequestreview-2278519273
> Revert "Fix video CLS netting +10 lighthouse points"

- libs/blocks/global-navigation/global-navigation.css
* Fixed Sign In button text center alignment in UNAV 
Resolves: [MWPW-146258](https://jira.corp.adobe.com/browse/MWPW-146258)
**Test URLs:**
- After: https://mwpw-146258--milo--adobecom.hlx.page/?martech=off
**US**
- Before: https://main--cc--adobecom.hlx.page/products/illustrator?&martech=off
- After: https://main--cc--adobecom.hlx.page/products/illustrator?milolibs=mwpw-146258--milo--sivasadobe&martech=off
**Korean**
- Before: https://main--cc--adobecom.hlx.page/kr/products/illustrator?&martech=off
- After: https://main--cc--adobecom.hlx.page/kr/products/illustrator?milolibs=mwpw-146258--milo--sivasadobe&martech=off
**Hindi**
- Before: https://main--cc--adobecom.hlx.page/in_hi/products/illustrator?&martech=off
- After: …
> MWPW-146258: [UNav] CTA text alignment is not center in CTA in UNAV for some locales.

- libs/navigation/navigation.js
- libs/utils/utils.js
> Revert "Adding support for getting env config through client env"

- libs/features/webapp-prompt/webapp-prompt.css
- libs/features/webapp-prompt/webapp-prompt.js
* Made the pep close button focus a consistent color
Resolves: [MWPW-151534](https://jira.corp.adobe.com/browse/MWPW-151534)
**Test URLs:**
- After: https://pep-dialog-close--milo--sharmrj.hlx.page/?martech=off
- qa: https://main--cc--adobecom.hlx.page/products/photoshop/ai?milolibs=pep-dialog-close--milo--sharmrj&skipPepEntitlements=true
> MWPW-151534 [PEP Prompt] Dismissal action on close button of prompt not seen in windows

- libs/blocks/floodgateui/actions/index.js
- libs/blocks/floodgateui/floodgate/index.js
- libs/blocks/floodgateui/floodgateui.css
- libs/blocks/floodgateui/url/view.js
- libs/blocks/floodgateui/utils/url.js
Setup validation of configured URLs and found fragment URLs in floodgate UI. Including UI to let the user know what error was returned in validation.
Will validate URLs for the following:
- NOT FOUND (404)
- NOT AEM URL
- NOT SAME DOMAIN
- MEDIA FILES (gif, jpg, jpeg, tiff, png, and webp)
Resolves: [MWPW-155333](https://jira.corp.adobe.com/browse/MWPW-155333)
**Test URLs:**
- Before: https://main--cc--adobecom.hlx.page/tools/floodgate?milolibs=floodgateui&ref=main&repo=cc&owner=adobecom&host=www.adobe.com&project=Creative+Cloud&referrer=https%3A%2F%2Fadobe.sharepoint.com%2F%3Ax%3A%2Fr%2Fsites%2Fadobecom%2F_layouts%2F15%2FDoc.aspx%3Fsourcedoc%3D%257B7efa1bf3-89fb-4f5a-95be-dbc80f596074%257D%26action%3Deditnew
- After: https://main--cc--adobecom.hlx.page/tools/floodgate?milolibs=sean-loc&ref …
> MWPW-155333 - [FloodgateUI] URL validation

- libs/blocks/adobetv/adobetv.js
- libs/blocks/figure/figure.js
- libs/blocks/video/video.js
- libs/utils/decorate.js
- test/blocks/adobetv/adobetv.test.js
- test/blocks/adobetv/mocks/body.html
- test/blocks/figure/figure.test.js
- test/blocks/figure/mocks/body.html
- test/blocks/marquee/marquee.test.js
- test/blocks/video/mocks/body.html
- test/blocks/video/video.test.js
Reverts adobecom/milo#2849
Before
https://main--cc--adobecom.hlx.live/creativecloud/buy/education
https://main--cc--adobecom.hlx.live/creativecloud/buy/education?milolibs=revert-2849-marquee-cls
> Revert "MWPW-156749: Fix video CLS "

- libs/blocks/adobetv/adobetv.js
- libs/blocks/figure/figure.js
- libs/blocks/video/video.js
- libs/utils/decorate.js
- test/blocks/adobetv/adobetv.test.js
- test/blocks/adobetv/mocks/body.html
- test/blocks/figure/figure.test.js
- test/blocks/figure/mocks/body.html
- test/blocks/marquee/marquee.test.js
- test/blocks/video/mocks/body.html
- test/blocks/video/video.test.js
Fixes issues on production with certain video marquees. Stage PR: https://github.com/adobecom/milo/pull/2899
**Test URLs:**
- Before: https://main--cc--adobecom.hlx.live/creativecloud/buy/education
- After: https://main--cc--adobecom.hlx.live/creativecloud/buy/education?milolibs=revert-2849-marquee-cls
> Revert "MWPW-156749: Fix video CLS " (#2899)

- libs/blocks/quiz-entry/quiz-entry.js
- libs/blocks/quiz-entry/quizoption.js
- libs/blocks/quiz-entry/utils.js
* Add local paths for doc file and excels
* Fix bug for JP - Page jumps, enlarges the cards and duplicates copy
* Clean up LTRM in URLs
Resolves: [MWPW-157450](https://jira.corp.adobe.com/browse/MWPW-157450)
**Test URLs:**
- Before: https://main--milo--adobecom.hlx.page/drafts/quiz/quiz-entry/?martech=off
- After: https://stage--milo--jackysun9.hlx.page/drafts/quiz/quiz-entry/?martech=off
How to test?
Test EN:
https://main--cc--adobecom.hlx.page/cc-shared/fragments/uar/front-doors/quiz-entry/quiz?martech=off&milolibs=stage--milo--JackySun9
Test CA:
https://main--cc--adobecom.hlx.page/ca/cc-shared/fragments/uar/front-doors/quiz-entry/quiz?martech=off&milolibs=stage--milo--JackySun9
Test JP:
https://main--cc--adobecom.hlx.page/jp/cc-shared/fragments/uar/front-doors/quiz-entry/quiz?martech=of …
> MWPW-157450: Localization Enhancements for quiz-entry block needed

- libs/features/mas/web-components/test/merch-card.mini-compare.test.html.js
Fixed MAS unit test related to mini-compare card variation
**Test URLs:**
- After: https://mas-unit-test-fix--milo--adobecom.hlx.page/?martech=off
> Fixed MAS unit test related to mini-compare card variation

- nala/utils/nala.run.js
* Update the Nala run command to allow running on a feature branch with an owner other than `adobecom`.
Resolves: [MWPW-159287](https://jira.corp.adobe.com/browse/MWPW-159287)
**Test URLs:**
- After: https://nala-commands--milo--adobecom.hlx.page/?martech=off
> [MWPW-159287 : NALA] Enhance Nala Run Command to Support Feature Branches with with an owner other than 'adobecom'

- libs/blocks/global-navigation/global-navigation.js
This PR is to address review comments for below PR:
https://github.com/adobecom/milo/pull/2942 (with added comments)
Resolves: [MWPW-159262](https://jira.corp.adobe.com/browse/MWPW-159262)
**Test URLs:**
- After: https://mwpw-159262--milo--deva309.hlx.page/?martech=off
QA: 
https://adobecom.github.io/nav-consumer/navigation.html?env=stage&navbranch=MWPW-159262&authoringpath=/federal/dev/devashish&customlinks=home,learn
> Fixed review comments of previous PR of custom Links setup for GNAV

- libs/utils/decorate.js
Fixes quiz video marquees
Resolves: https://jira.corp.adobe.com/browse/MWPW-159903
**Test URLs:**
- After: https://fix-quiz-marquee--milo--mokimo.hlx.page/?martech=off
Quiz Marquees
Before: https://main--cc--adobecom.hlx.page/cc-shared/fragments/uar/marquee/illustrator?debug=quiz-results
After: https://main--cc--adobecom.hlx.page/cc-shared/fragments/uar/marquee/illustrator?debug=quiz-results&milolibs=fix-quiz-marquee--milo--mokimo
> [MWPW-159903] Fix quiz video marquees

- libs/blocks/fragment/fragment.js
- libs/blocks/global-navigation/utilities/utilities.js
- libs/blocks/merch-card-collection/merch-card-collection.js
- libs/features/personalization/personalization.js
- test/blocks/fragment/fragment.test.js
- test/blocks/merch-card-collection/merch-card-collection.test.js
- test/features/personalization/actions.test.js
- test/features/personalization/actionsTargetManifestId.test.js
- test/features/personalization/parseNestedPlaceholders.test.js
- test/features/personalization/personalization.test.js
This needs to be fast-tracked to `main` as it contains essential updates for MAX.
Initial `stage` PR: https://github.com/adobecom/milo/pull/2976
Included in the approved batch for `main`: https://github.com/adobecom/milo/pull/3004
Resolves: [MWPW-146211](https://jira.corp.adobe.com/browse/MWPW-146211) & [MWPW-146210](https://jira.corp.adobe.com/browse/MWPW-146210)
**Test URLs (check original PR for more details):**
- After: https://mep-to-main--milo--overmyheadandbody.hlx.page/?martech=off
> MWPW-146211 [MILO][MEP] Option to select all elements (#2976)

- libs/blocks/section-metadata/section-metadata.css
This needs to be fast-tracked to `main` as it contains essential updates for MAX.
Initial stage PR: https://github.com/adobecom/milo/pull/2991
Included in the batch for main: https://github.com/adobecom/milo/pull/3004
Resolves: [MWPW-158455](https://jira.corp.adobe.com/browse/MWPW-158455) & [MWPW-159426](https://jira.corp.adobe.com/browse/MWPW-159426)
**Test URLs:**
- After: https://promobar-index-fix--milo--overmyheadandbody.hlx.page/?martech=off
> MWPW-158455: Promobar overlays with localnav elements in devices (#2991)

- libs/blocks/global-navigation/utilities/utilities.js
- test/blocks/global-navigation/mocks/mep-config.js
* Update JSON to restore code coverage
Resolves: [MWPW-146211](https://jira.corp.adobe.com/browse/MWPW-146211)
**Test URLs:**
- After: https://mepallcodecov--milo--adobecom.hlx.page/?martech=off
> MWPW-146211 add code coverage

- libs/blocks/graybox/graybox.css
*graybox no-click now properly restricts clicks and selection
Resolves: [MWPW-157690](https://jira.corp.adobe.com/browse/MWPW-157690)
**Test URLs:**
- Before: https://main--milo--adobecom.hlx.page/drafts/colloyd/graybox/graybox-changed?graybox=on&martech=off
- After: https://graybox-no-click-fix--milo--colloyd.hlx.page/drafts/colloyd/graybox/graybox-changed?graybox=on&martech=off
> graybox no-click fix

- libs/blocks/media/media.js
Make the app store and play store links clickable again which got lost as part of https://github.com/adobecom/milo/pull/1768
Resolves: [MWPW-160061](https://jira.corp.adobe.com/browse/MWPW-160061)
**Test URLs:**
- Before: https://main--milo--adobecom.hlx.page/drafts/sara/media?martech=off
- After: https://mwpw-160061-qr-code-media--milo--mokimo.hlx.page/drafts/sara/media?martech=off
> MWPW-160061: Clickable App and Playstore links

- playwright.config.js
* Add the following Nala-specific user agent to nala automation tests across test projects/platforms
* DESKTOP = `'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.6613.18 Safari/537.36 NALA-Acom';`
* MOBILE_CHROME = `'Mozilla/5.0 (Linux; Android 11; Pixel 5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.114 Mobile Safari/537.36 NALA-Acom';`
* MOBILE_SAFARI = `'Mozilla/5.0 (iPhone; CPU iPhone OS 14_6 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.1.1 Mobile/15E148 Safari/604.1 NALA-Acom';`
Resolves: [MWPW-160735](https://jira.corp.adobe.com/browse/MWPW-160735)
**Test URLs:**
- After: https://nala-useragent--milo--adobecom.hlx.page/?martech=off
> [MWPW-160735][NALA] Add Nala-specific user-agent

- nala/blocks/marquee-anchors/marquee-anchors.test.js
- nala/blocks/marquee/marquee.test.js
- nala/blocks/media/media.test.js
- nala/blocks/merchcard/merchcard.test.js
- nala/blocks/modal/modal.test.js
- nala/blocks/quote/quote.test.js
- nala/blocks/review/review.test.js
- nala/blocks/table/table.test.js
- nala/blocks/tabs/tabs.test.js
- nala/blocks/text/text.test.js
- nala/blocks/video/video.test.js
- nala/blocks/zpattern/zpattern.test.js
- nala/libs/accessibility.js
* Added accessibility automation test scripts for following Milo blocks
* Media
* Merchchard
* Modal
* Quote
* Review
* Table
* Tabs
* Text
* Video
* Zpattern
Resolves: [MWPW-161069](https://jira.corp.adobe.com/browse/MWPW-161069)
**Test URLs:**
- After: https://accessibility-batch-2--milo--adobecom.hlx.page/?martech=off
> [MWPW-161069][NALA][A11Y] Add accessibility automation test for Milo blocks

- libs/features/georoutingv2/georoutingv2.js
Refactors promises in georoutingv2
Resolves: [MWPW-152228](https://jira.corp.adobe.com/browse/MWPW-152228)
Test URLs:
After: https://mwpw-152228--milo--adobecom.hlx.page/?martech=off
QA:
Before: https://main--cc--adobecom.hlx.page/products/illustrator
After: https://main--cc--adobecom.hlx.page/products/illustrator?milolibs=mwpw-152228&martech=off
> MWPW-152228: refactor georouting promises call

- libs/blocks/floodgateui/floodgate/promoteStatus.js
- libs/blocks/floodgateui/utils/miloc.js
Reduce the number of parameters passed to floodgate action. Actions would pick extract those parameter from .milo/config.json
Also, Replace shareUrls with adminPage urls to determine the tenant (repo/owner)
Resolves: [MWPW-160240](https://jira.corp.adobe.com/browse/MWPW-160240)
Test URLs:
Before: https://floodgateui--milo--adobecom.hlx.page/tools/floodgate?milolibs=floodgateui&ref=main&repo=milo&owner=adobecom&host=www.adobe.com&project=Milo&referrer=https%3A%2F%2Fadobe.sharepoint.com%2F%3Ax%3A%2Fr%2Fsites%2Fadobecom%2F_layouts%2F15%2FDoc.aspx%3Fsourcedoc%3D%257Bc9ee60aa-0f0a-4b44-8a61-49d3d06a91ed%257D%26action%3Deditnew
After: https://floodgateui--milo--raga-adbe-gh.hlx.page/tools/floodgate?milolibs=floodgateui&ref=main&repo=milo&owner=adobecom&host=www.adobe.com&project=Milo&referrer=ht …
> [MWPW-160240][FloodgateUI] Reduce parameters passed to floodgate

- libs/navigation/navigation.js
* Making stageDomainsMap configurable through consuming client
Resolves: [MWPW-161164](https://jira.corp.adobe.com/browse/MWPW-161164)
**Test URLs:**
- After: https://stage-domain-config--milo--adobecom.hlx.page/?martech=off
**QA:** 
- https://adobecom.github.io/nav-consumer/navigation.html?navbranch=stage-domain-config
> Adding support for clients to add their own stage domain maps

- .github/workflows/check-feds-files.js
- .github/workflows/check-feds-files.yaml
We need to be sure no files that affect the standalone gnav are merged on the 14th of November, 2024.  This workflow helps us identify PRs that touch standalone gnav related files.
**Test URLs:**
- After: https://feds-filecheck-workflow--milo--sharmrj.hlx.page/?martech=off
> Temporary workflow to watch for any feds files being changed

- libs/blocks/carousel/carousel.css
- libs/blocks/carousel/carousel.js
New feature enhancements to carousel to help support Ps mobile launch. Focusing on mobile enhancements.
* Rounded corners variants (s, m, l, full)
* Hinting on mobile
* * Two options. Hinting on right side (hinting-mobile) and centered hinting (hinting-center-mobile)
* Vertical alignment adjustment on mobile
* Gap variant (m-gap)
* Mobile swipe - pause video playing for videos using `<video>` tag.
* Conversion of MPC.mp4's to use `<video>` tag when link is set to `#_dnb` for better mobile support (touch control) and performance.
* CSS clean up
Resolves: 
[MWPW-160544](https://jira.corp.adobe.com/browse/MWPW-160544)
[MWPW-160721](https://jira.corp.adobe.com/browse/MWPW-160721)
[MWPW-159877](https://jira.corp.adobe.com/browse/MWPW-159877) …
> Carousel mWeb Enhancements

- libs/blocks/global-navigation/global-navigation.css
- libs/blocks/global-navigation/utilities/utilities.js
* Added breadcrumbs to sections
* Hidden breadcrumbs on first screen of sidebar
Resolves: [MWPW-161558](https://jira.corp.adobe.com/browse/MWPW-161558)
**Test URLs:**
- After: https://mobile-gnav-breadcrumbs--milo--adobecom.hlx.page/?martech=off
QA: https://main--federal--adobecom.hlx.page/federal/dev/blaishram/page-with-localnav?milolibs=mobile-gnav-breadcrumbs&newNav=true
> Mobile gnav breadcrumbs new design

- libs/blocks/review/components/review/Comments.js
- libs/blocks/review/review.css
- Adds a floating label as accessibility requirements for comments field
Resolves: [MWPW-159032](https://jira.corp.adobe.com/browse/MWPW-159032)
Test URLs:
Before: https://main--dc--adobecom.hlx.page/drafts/rivero/ratings&martech=off
After: https://mwpw-159032-ratings--milo--joaquinrivero.hlx.page/drafts/rivero/ratings&martech=off
> MWPW-159032: Accessibility requirements floating label

- libs/blocks/global-navigation/utilities/keyboard/mainNav.js
- libs/blocks/global-navigation/utilities/keyboard/mobilePopup.js
- libs/blocks/global-navigation/utilities/keyboard/utils.js
- libs/blocks/global-navigation/utilities/utilities.js
Requirements:  https://jira.corp.adobe.com/browse/MWPW-160542
Currently the requirements don't specify requirements for arrow keys so arrow keys don't do anything on the mobile gnav. 
https://main--homepage--adobecom.hlx.live/homepage/index-loggedout?milolibs=mobile-gnav-keyboard--milo--sharmrj&newNav=true
> Keyboard navigation for mobile gnav redesign

- libs/features/mas/docs/ccd.html
Gallery: mwpw-161176--milo--adobecom.hlx.page/libs/features/mas/docs/ccd.html
Resolves: [MWPW-161176](https://jira.corp.adobe.com/browse/MWPW-161176)
**Test URLs:**
- After: https://MWPW-161176--milo--adobecom.hlx.page/?martech=off
> MWPW-161176: restructure ccd gallery

- libs/blocks/text/text.css
- libs/features/georoutingv2/georoutingv2.css
- libs/features/georoutingv2/georoutingv2.js
- libs/features/icons/icons.js
- libs/styles/styles.css
- libs/utils/utils.js
- test/features/icons/icons.test.js
- test/features/icons/mocks/body.html
This reverts https://github.com/adobecom/milo/pull/2986
> Revert "MWPW-140452 - Icon authoring in milo using the federal repo and individual SVG assets

- libs/blocks/locui-create/fragments/view.js
- libs/blocks/locui-create/input-urls/index.js
- libs/blocks/locui-create/input-urls/view.js
* Fixes validation when no fragment is there
Resolves: https://jira.corp.adobe.com/browse/MWPW-161619
**Test URLs:**
- After: https://mwpw-158881-loc-include-fragments--milo--saurabhsircar11.aem.page/drafts/sircar/locui-create?martech=off
> [LOC] MWPW-161619 - Handled validation when no fragment is there

- libs/blocks/locui-create/locui-create.css
* Updated the css styles for loc language selection screen
* Specific
Resolves: https://jira.corp.adobe.com/browse/MWPW-160919
**Test URLs:**
- Before: https://main--milo--hnvadobe.hlx.page/drafts/arnab/locui-create?martech=off
- After: https://language-selection-ui--milo--hnvadobe.hlx.page/drafts/hnv/document1?martech=off
> MWPW-160919: [Loc] CSS updation for the language selection screen.

- libs/blocks/fallback/fallback.js
- libs/blocks/global-navigation/global-navigation.js
- libs/blocks/global-navigation/utilities/menu/menu.css
- libs/blocks/global-navigation/utilities/menu/menu.js
* Adding image support for large menu and medium menus . 
Resolves: [MWPW-161192](https://jira.corp.adobe.com/browse/MWPW-161192)
**Test URLs:**
- After: https://mgnav-image--milo--adobecom.aem.page/?martech=off
QA: https://main--federal--adobecom.hlx.page/federal/dev/blaishram/express/express?milolibs=mgnav-image
Authored doc - https://adobe.sharepoint.com/:w:/r/sites/adobecom/_layouts/15/Doc.aspx?sourcedoc=%7BCF7050C1-A996-42F9-888A-F5C083A97898%7D&file=gnav.docx&action=default&mobileredirect=true
> Adding image support for large menu and medium menus on gnav

- libs/deps/mas/mas.js
- libs/deps/mas/merch-card.js
- libs/features/mas/mas/dist/mas.js
- libs/features/mas/web-components/src/global.css.js
Adds specificity to merch card styles to avoid styling conflicts.
Resolves: [MWPW-161804](https://jira.corp.adobe.com/browse/MWPW-161804)
**Test URLs:**
- Before: https://main--mas--adobecom.hlx.live/studio.html?milolibs=ccd--milo--adobecom#path=ccd
- After: https://main--mas--adobecom.hlx.live/studio.html?milolibs=mwpw-161804--milo--adobecom#path=ccd
> MWPW-161804: Merch card style auditing

- tools/floodbox/floodgate/floodgate.css
- tools/floodbox/floodgate/floodgate.js
- Initial draft with high-level flow
- Promote action support
- Preview/Publish on promoted content
- Ignore paths option on promote
- central config option (pending)
- copy and delete action (pending)
- UI / UX changes (pending)
Resolves: [MWPW-161575](https://jira.corp.adobe.com/browse/MWPW-161575)
**Test URLs:**
- After: https://da.live/app/adobecom/milo/tools/floodgate?ref=dafloodgate
> MWPW-161575: Floodgate app on DA - initial draft

- test/tools/floodbox/floodgate/floodgate-config.test.js
- tools/floodbox/floodgate/floodgate-config.js
- tools/floodbox/floodgate/floodgate.js
Resolves: [MWPW-161911](https://jira.corp.adobe.com/browse/MWPW-161911)
**Test URLs:**
- Before: https://da.live/app/adobecom/milo/tools/floodgate?ref=floodbox 
- After: https://da.live/app/adobecom/milo/tools/floodgate?ref=da-fg-config
> MWPW-161911: DA FG App Configuration

- libs/blocks/locui-create/input-actions/index.js
- libs/blocks/locui-create/input-actions/modal.js
- libs/blocks/locui-create/input-actions/view.js
- libs/blocks/locui-create/locui-create.css
* Table heading count for languages
* Fixed bug with actions table
* Added validation for in input actions screen "Create Project"
* Fixed alignment for "View" button
Resolves: [MWPW-162813](https://jira.corp.adobe.com/browse/MWPW-162813)
**Test URLs:**
- Before: https://main--milo--maagrawal16.hlx.page/drafts/arnab/locui-create?martech=off
- After: https://MWPW-162813-screen3-fixes--milo--maagrawal16.hlx.page/drafts/arnab/locui-create?martech=off
> [Loc][MWPW-162813] Fixed action screen ui, added validation

- tools/floodbox/floodbox.css
- tools/floodbox/floodbox.js
- tools/floodbox/graybox/graybox.css
- tools/floodbox/graybox/graybox.js
- tools/graybox.html
* Tab UI for each step to promote
* Detail cards for each step
* Cleaned up the existing UI buttons and options
Resolves: [MWPW-161925](https://jira.corp.adobe.com/browse/MWPW-161925)
**Test URLs:**
- After: https://da.live/app/colloyd/milo/tools/graybox?ref=da-graybox-ui
> DA Graybox UI

- libs/blocks/locui-create/input-locale/view.js
*  Fixed padding 2nd screen
Resolves: https://jira.corp.adobe.com/browse/MWPW-162810
**Test URLs:**
- Before: https://main--milo--adobecom.hlx.page/drafts/sircar/locui-create?martech=off
- After: https://mwpw-162810-fix-second-padding--milo--saurabhsircar11.hlx.page/drafts/sircar/locui-create?martech=off
> [LOC]Mwpw 162810 fixed padding issue

- nala/features/personalization/allowhtml.spec.js
- nala/features/personalization/allowhtml.test.js
This nala tests checks for features added by PR 2683, https://github.com/adobecom/milo/pull/2683
Resolves: [MWPW-162057](https://jira.corp.adobe.com/browse/MWPW-162057)
**Test URLs:**
- After: https://allowhtml2--milo--adobecom.hlx.page/?martech=off
> MWPW-162057 [MEP][NALA]add nala test for new features from PR 2683 "allow HTML"

- nala/utils/nala.run.js
* Provide an option to run Milo UI Tests on the DA-BACOM repo and branches
* Provide an option to run Milo UI Tests on any repo and branches
* commands :
*  `npm run nala [branchname] repo=<reponame>`
*   `npm run nala hlx-5 repo=da-bacom`
*   `npm run nala main repo=da=bacom @marquee` so on....
Resolves: [MWPW-162670](https://jira.corp.adobe.com/browse/MWPW-162670)
**Test URLs:**
- After: https://da--milo--adobecom.aem.page/?martech=off
> [NALA][MWPW-162670] Enhance Nala Framework and Tests for Execution on DA-BACOM Repository and Branches

- libs/mep/sample-block-code/marquee/marquee.css
In order to properly test the useBlockCode feature of MEP, the CSS file needs to provide a CSS update.
Resolves: [MWPW-162777](https://jira.corp.adobe.com/browse/MWPW-NUMBER)
**Test URLs:**
- Before: https://main--milo--adobecom.hlx.page/drafts/nala/features/personalization/mep-actions/use-block-code
- After: https://use-block-code--milo--adobecom.hlx.page/drafts/nala/features/personalization/mep-actions/use-block-code
- PSI check: https://use-block-code--adobecom.aem.page/?martech=off
The before URL shows the text in black.
The after URL shows the text in purple, applying a CSS code change.
> MWPW-162777  [MEP] [NALA] add code to marquee.css for CSS change

- libs/styles/consonant-play-button.css
- libs/utils/image-video-link.js
Update to change the poster image play button when linking to a modal.
* Change the play button icon and color
Resolves: [MWPW-162410](https://jira.corp.adobe.com/browse/MWPW-162410)
**Test URLs:**
- Before: https://main--milo--adobecom.hlx.page/drafts/rclayton/poster-play-button?martech=off
- After: https://poster-play-icon--milo--adobecom.hlx.page/drafts/rclayton/poster-play-button?martech=off
> Poster play button update

- test/tools/floodbox/crawl-tree.test.js
- test/tools/floodbox/request-handler.test.js
- test/tools/floodbox/search-replace.test.js
- tools/floodbox/floodgate/floodgate.js
- tools/floodbox/graybox/graybox.js
- tools/floodbox/request-handler.js
- tools/floodbox/search-replace.js
Resolves: [MWPW-161576](https://jira.corp.adobe.com/browse/MWPW-161576)
**Test URLs:**
- After: https://da.live/app/adobecom/milo/tools/graybox?ref=floodbox-ut
> MWPW-161576: DA Floodbox UTs

- libs/martech/martech.js
* proxy marketing scripts for newsroom for performance improvement
Resolves: [MWPW-163002](https://jira.corp.adobe.com/browse/MWPW-163002)
**Test URLs:**
- After: https://news-proxy--milo--adobecom.aem.page/?martech=off
Note: Proxy at akamai level has been implemented as part of https://jira.corp.adobe.com/browse/WPS-26769
Code cannot be tested on feature branch.
> MWPW-163002-proxy marketing scripts for newsroom

- test/tools/floodbox/utils.test.js
- tools/floodbox/floodgate/fg-copy.js
- tools/floodbox/floodgate/floodgate.js
- tools/floodbox/floodgate/utils.js
- tools/floodbox/references.js
- tools/floodbox/utils.js
Features implemented:
- Copy Action - to copy from source to pink site - with link reference updates
- Version creation at the destination pre-copy
- Helix Preview post-copy 
- Finds Fragments and Asset References in the document and preps for Copy
- DA Floodgate App UI Updates
Resolves: [MWPW-163511](https://jira.corp.adobe.com/browse/MWPW-163511)
**Test URLs:**
- After: https://da.live/app/adobecom/milo/tools/floodgate?ref=fgcopy
> MWPW-163511: DA Floodgate Copy Action

- test/tools/floodbox/floodgate/fg-copy.test.js
- test/tools/floodbox/floodgate/utils.test.js
- test/tools/floodbox/graybox/utils.test.js
- test/tools/floodbox/references.test.js
Resolves: [MWPW-161575](https://jira.corp.adobe.com/browse/MWPW-161575)
**Test URLs:**
- After: https://da.live/app/adobecom/milo/tools/floodgate?ref=floodbox-ut1
> MWPW-161575: Unit tests for FG and GB

- libs/blocks/global-navigation/base.css
- libs/blocks/global-navigation/dark-nav.css
- libs/blocks/global-navigation/global-navigation.css
- libs/blocks/global-navigation/global-navigation.js
- libs/blocks/global-navigation/utilities/keyboard/mainNav.js
- libs/blocks/global-navigation/utilities/keyboard/mobilePopup.js
- libs/blocks/global-navigation/utilities/keyboard/utils.js
- libs/blocks/global-navigation/utilities/utilities.js
Added dark mode changes and scope to test it with only adobe home.
Resolves: [MWPW-159667](https://jira.corp.adobe.com/browse/MWPW-159667)
**Test URLs:**
- After: https://mwpw-159667-dark-mode--milo--deva309.aem.page/?martech=off
QA:
https://adobecom.github.io/nav-consumer/navigation.html?env=stage&navbranch=mwpw-159667-dark-mode&authoringpath=/federal/dev/devashish&theme=dark&newNav=true&customLinks=home&customlinks=home,apps,learn
> [MWPW-159667] - Add dark mode fixes

- libs/features/dynamic-navigation/dynamic-navigation.js
- libs/features/dynamic-navigation/status.js
- test/features/dynamic-nav/dynamicNav.test.js
- test/features/dynamic-nav/status.test.js
Reverts adobecom/milo#3124 - bug found while testing
- Before: https://main--bacom--adobecom.hlx.page/?milolibs=stage
- After: https://main--bacom--adobecom.hlx.page/?milolibs=revert-3124-dynamic-nav-groups
> Revert "MWPW-155723 - Adds group metadata to ensure dyanmic nav continuity "

- libs/blocks/locui-create/input-actions/index.js
- libs/blocks/locui-create/input-actions/view.js
- libs/blocks/locui-create/input-locale/index.js
- libs/blocks/locui-create/input-locale/view.js
- libs/blocks/locui-create/locui-create.css
- libs/blocks/locui-create/store.js
- libs/blocks/locui-create/utils/utils.js
The UI flow has been updated based on the selection of Rollout or Translate. For Rollout, both locale and language selection are available, while for Translate, only language selection is available.
Resolves: https://jira.corp.adobe.com/browse/MWPW-160919
Test URLs:
Before: https://main--milo--hnvadobe.hlx.page/drafts/arnab/locui-create?martech=off
After: https://language-selection--milo--hnvadobe.hlx.page/drafts/hnv/document1?martech=off
> [MWPW-160919]:- LocV3 Rollout-Translate flow Language selection UI flow.

- libs/blocks/locui-create/input-urls/index.js
- libs/blocks/locui-create/input-urls/view.js
- libs/blocks/locui-create/locui-create.css
* Added project type switcher controls
* Bifurcated step 1 workflow based on the project type switch
Resolves: [MWPW-163463](https://jira.corp.adobe.com/browse/MWPW-163463), [MWPW-163461](https://jira.corp.adobe.com/browse/MWPW-163461)
**Test URLs:**
- After: https://MWPW-163463-project-type--milo--zweihand3r.hlx.page/drafts/arnab/locui-create?martech=off
> MWPW-163463: Added project type switcher and bifurcated 1st step

- nala/blocks/table/table.page.js
* Update table tooltip locator
Resolves: [MWPW-163847](https://jira.corp.adobe.com/browse/MWPW-163847)
**Test URLs:**
- After: https://table-tooltip-update--milo--adobecom.aem.page/?martech=off
> [NALA][Table-Tooltip] Update tooltip locator

- tools/floodbox/floodbox.css
- tools/floodbox/graybox/graybox.js
---
Resolves: [MWPW-163865](https://jira.corp.adobe.com/browse/MWPW-163865)
**Test URLs:**
- After: https://da.live/app/adobecom/milo/tools/graybox?ref=ribbon
> MWPW-163865: Ribbon UI for DA Graybox

- tools/floodbox/graybox/graybox.js
- tools/floodbox/graybox/utils.js
* fix for reset tokens
* fix for promote count with errors
Resolves: [MWPW-164020](https://jira.corp.adobe.com/browse/MWPW-164020)
Resolves: [MWPW-163995](https://jira.corp.adobe.com/browse/MWPW-163995)
**Test URLs:**
- After: https://da.live/app/colloyd/milo/tools/graybox?ref=da-graybox-bug-fixes
> DA Graybox UI Bug Fixes

- libs/blocks/global-navigation/global-navigation.js
- libs/blocks/global-navigation/utilities/keyboard/index.js
- libs/blocks/global-navigation/utilities/utilities.js
- test/blocks/global-navigation/global-navigation.test.js
- test/blocks/global-navigation/gnav-cross-cloud.test.js
- test/blocks/global-navigation/gnav-main-nav-popup.test.js
- test/blocks/global-navigation/keyboard/keyboard.test.js
- test/blocks/global-navigation/keyboard/mocks/global-new-nav-mobile-localnav.html
- test/blocks/global-navigation/keyboard/mocks/global-new-nav-mobile.html
- test/blocks/global-navigation/keyboard/mocks/localnav-mock.html
- test/blocks/global-navigation/mocks/gnav-with-localnav.plain.js
- test/blocks/global-navigation/mocks/mock-cc-column-1.plain.js
- test/blocks/global-navigation/mocks/mock-cc-column-2.plain.js
- test/blocks/global-navigation/mocks/mock-megamenu.plain.js
- test/blocks/global-navigation/test-utilities.js
- test/blocks/global-navigation/utilities/utilities.test.js
- test/navigation/bootstrapper.test.js
Cover Unit test cases for the functionality for new mobile redesign.
Resolves: [MWPW-164088](https://jira.corp.adobe.com/browse/MWPW-164088)
**Test URLs:**
- After: https://mobile-gnav-unit-tests--milo--deva309.aem.page/?martech=off
> [MWPW-164088] - UT for mobile GNAV redesign

- test/tools/floodbox/graybox/utils.test.js
- tools/floodbox/floodgate/floodgate.css
- tools/floodbox/floodgate/floodgate.js
- tools/floodbox/floodgate/utils.js
- tools/floodbox/graybox/utils.js
Resolves: [MWPW-161575](https://jira.corp.adobe.com/browse/MWPW-161575)
**Test URLs:**
- After: https://da.live/app/adobecom/milo/tools/floodgate?ref=path-bugfix
> MWPW-161575: Path validation fix

- libs/blocks/locui-create/utils/utils.js
* Added env in settings for edit and create flows
Resolves: https://jira.corp.adobe.com/browse/MWPW-164054
**Test URLs:**
- Before: https://main--milo--adobecom.hlx.page/drafts/sircar/locui-create?martech=off
- After: https://mwpw-164054-passing-env--milo--saurabhsircar11.hlx.page/drafts/sircar/locui-create?martech=off
> [Loc] MWPW-164054: added env for edit and create flows

- test/tools/floodbox/floodgate/utils.test.js
- test/tools/floodbox/request-handler.test.js
- tools/floodbox/floodbox.css
- tools/floodbox/floodgate/floodgate.css
- tools/floodbox/floodgate/floodgate.js
- tools/floodbox/request-handler.js
- Provides an option to delete content in pink tree
- Crawls the pink site
- Unpublishes the pink content from Helix
- Deletes the files from DA pink content tree
https://github.com/user-attachments/assets/ed6d0a3c-8229-415c-bd24-7c2e78dee4d2
Resolves: [MWPW-164330](https://jira.corp.adobe.com/browse/MWPW-164330)
**Test URLs:**
- After: https://da.live/app/adobecom/milo/tools/floodgate?ref=fgdelete
> MWPW-164330: Delete Option in DA FG App

- libs/blocks/locui-create/input-actions/view.js
- libs/blocks/locui-create/locui-create.js
- libs/blocks/locui-create/store.js
- libs/blocks/locui-create/utils/utils.js
* Initialized selected language and locale
Resolves: https://jira.corp.adobe.com/browse/MWPW-164318
**Test URLs:**
- After:  https://mwpw-164318-edit-flow-lang--milo--saurabhsircar11.hlx.page/drafts/sircar/locui-create?martech=off
> Mwpw 164318 edit flow lang

- libs/blocks/global-navigation/global-navigation.js
…o account when opening
* Take scroll into account when opening the mega menu in mobile gnav
Resolves: [MWPW-164385](https://jira.corp.adobe.com/browse/MWPW-164385)
**Test URLs:**
- After: https://mobile-gnav-bugfixes--milo--sharmrj.aem.page/?martech=off
https://main--cc--adobecom.hlx.live/products/indesign?milolibs=mobile-gnav-bugfixes--milo--sharmrj
> MWPW-164385 [Mobile Gnav]when the megamenu is opened and scrolled seen the overlapping issue on the content and screen is freezed

- libs/blocks/locui-create/input-locale/index.js
- libs/blocks/locui-create/input-locale/view.js
- libs/blocks/locui-create/store.js
- libs/blocks/locui-create/utils/constant.js
* Removed English in language selection
* Removed English livecopies from region selection
Resolves: https://jira.corp.adobe.com/browse/MWPW-164481
**Test URLs:**
- After: https://MWPW-164481-english-translate--milo--saurabhsircar11.hlx.page/drafts/sircar/locui-create?martech=off
>  [LOC] MWPW-164481 - For English language only "Rollout" action option should be available when author creates translation project.

- libs/blocks/locui-create/input-actions/view.js
- libs/blocks/locui-create/utils/constant.js
* Removed English copy action for english alt
Resolves: https://jira.corp.adobe.com/browse/MWPW-164574
**Test URLs:**
- After: https://MWPW-164574-english-alt--milo--saurabhsircar11.hlx.page/drafts/sircar/locui-create?martech=off
> [LOC] MWPW-164574 - For English altlang in Translation flow should allow either "Translate" or "Rollout"

- libs/blocks/global-navigation/global-navigation.js
* Add unc activity feed support for standalone gnav
Resolves: [MWPW-163946](https://jira.corp.adobe.com/browse/MWPW-163946)
**Test URLs:**
- After: https://gnav-unc--milo--adobecom.aem.page/?martech=off
> Add unc activity feed support for standalone gnav

- libs/blocks/global-navigation/features/aside/aside.js
- libs/blocks/global-navigation/global-navigation.css
- libs/blocks/global-navigation/global-navigation.js
- libs/styles/styles.css
- libs/utils/utils.js
- test/blocks/global-navigation/gnav-promo.test.js
- test/blocks/global-navigation/test-utilities.js
* Moved promo bar out of header to make it sticky on scroll
Resolves: [MWPW-163972](https://jira.corp.adobe.com/browse/MWPW-163972)
**Test URLs:**
- After: https://mgnav-promo-sticky--milo--adobecom.aem.page/?martech=off
QA: https://main--cc--adobecom.hlx.page/drafts/blaishram/document2?milolibs=mgnav-promo-sticky&newNav=true
> Making gnav promo sticky

- libs/blocks/global-navigation/global-navigation.css
- libs/blocks/global-navigation/global-navigation.js
Fixes this page: https://main--cc--adobecom.hlx.page/ae_ar/creativecloud/photography/discover/how-to-read-a-histogram?milolibs=mobile-gnav-popup-promo&newNav=true
**Test URLs:**
- After: https://mobile-gnav-popup-promo--milo--adobecom.aem.page/?martech=off
> Fixed popup with promo

- libs/blocks/locui-create/input-urls/view.js
- libs/blocks/locui-create/locui-create.css
* Darker text colour for urls
* Changed labels
Resolves: https://jira.corp.adobe.com/browse/MWPW-164734
**Test URLs:**
- After: https://MWPW-164734-single-rollout--milo--saurabhsircar11.hlx.page/drafts/sircar/locui-create?martech=off
> [LOC]MWPW-164734 - minor css changes for input urls screen

- libs/blocks/global-navigation/global-navigation.css
- libs/blocks/global-navigation/global-navigation.js
- libs/blocks/global-navigation/utilities/utilities.js
Fixed popup on a main menu + promo page
Fixed iOS Safari bug where localnav wasn't at the correct height when open below a certain scrollY
> Mobile gnav bugfixes

- libs/blocks/locui-create/input-actions/modal.js
- libs/blocks/locui-create/input-locale/view.js
- libs/blocks/locui-create/locui-create.css
- libs/blocks/locui-create/store.js
* Shifted additional cta div
* Css changes to make button appear like a link
Resolves: https://jira.corp.adobe.com/browse/MWPW-164699
**Test URLs:**
- After: https://MWPW-164699-select-all--milo--saurabhsircar11.hlx.page/drafts/sircar/locui-create?martech=off
- Before: https://main--bacom--adobecom.hlx.page/tools/locui-create?milolibs=milostudio-stage&ref=main&repo=bacom&owner=adobecom&host=business.adobe.com&project=BACOM&env=local
- After: https://main--bacom--adobecom.hlx.page/tools/locui-create?milolibs=MWPW-164699-select-all--milo--saurabhsircar11&ref=main&repo=bacom&owner=adobecom&host=business.adobe.com&project=BACOM&env=local
> [LOC]MWPW-164699 - Changed css of select all and reset all

- libs/blocks/global-footer/global-footer.js
Accessibility bug - States/Properties: The element has missing or incorrect states or properties - Change Region
* Ref ticket : [DOTCOM-128840](https://jira.corp.adobe.com/browse/DOTCOM-128840)
Resolves: [MWPW-164735](https://jira.corp.adobe.com/browse/MWPW-164735)
**Test URLs:**
- Before: https://main--milo--adobecom.aem.page/drafts/snehal/illustrator?marchtech=off
- After: https://mwpw-164735--milo--adobecom.aem.page/drafts/snehal/illustrator?marchtech=off
> MWPW-164735 - States/Properties: The element has missing or incorrect states or properties - Change Region

- libs/blocks/locui-create/fragments/view.js
- libs/blocks/locui-create/input-actions/modal.js
- libs/blocks/locui-create/input-locale/view.js
- libs/blocks/locui-create/input-urls/index.js
- libs/blocks/locui-create/locui-create.css
- libs/blocks/locui-create/store.js
* Syncing changes from milostudio-stage to milostudio.
**Test URLs:**
- Before:  https://milostudio--milo--adobecom.hlx.page/drafts/sircar/locui-create?martech=off
- After: https://milostudio-stage--milo--saurabhsircar11.hlx.page/drafts/sircar/locui-create?martech=off
> [LOC] Milostudio stage to milostudio

- libs/blocks/locui-create/input-urls/view.js
* Updated label for Custom Merge Option in Region Edit Behaviour dropdown
Resolves: https://jira.corp.adobe.com/browse/MWPW-165749
**Test URLs:**
- After: https://MWPW-165749-custom-merge-label--milo--adobecom.hlx.page/drafts/sircar/locui-create?martech=off
> MWPW-165749 Updated label for custom merge

- libs/blocks/preflight/panels/seo.js
- libs/utils/utils.js
- test/utils/mocks/body.html
- test/utils/utils.test.js
* Adds a data attribute to links if the link was authored with http instead of https
* Adds error messaging in preflight if the http data attribute is found
Resolves: [MWPW-161867](https://jira.corp.adobe.com/browse/MWPW-161867)
**Test URLs:**
- Before: https://main--milo--jasonhowellslavin.hlx.live/drafts/slavin/bacom-pages/rtcdp?martech=off
- After: https://add-http-check-to-preflight--milo--jasonhowellslavin.hlx.live/drafts/slavin/bacom-pages/rtcdp?martech=off
> MWPW-161867: Add http check to preflight

- libs/styles/styles.css
Resolves: [MWPW-161948](https://jira.corp.adobe.com/browse/MWPW-161948)
**Test URLs:**
- Before: https://main--milo--adobecom.hlx.page/drafts/ratko/mwpw-161948/xxs-heading?martech=off
- After: https://mwpw-161948-xxs-heading--milo--adobecom.hlx.page/drafts/ratko/mwpw-161948/xxs-heading?martech=off
> MWPW-161948: Added .heading-xxs selector

- libs/blocks/locui/actions/index.js
- libs/blocks/locui/loc/index.js
- libs/blocks/locui/utils/franklin.js
- libs/tools/sharepoint/shared.js
- libs/utils/sidekick.js
> Locui hlx5 upgrade

- libs/blocks/bulk-publish-v2/services.js
- libs/blocks/preflight/panels/general.js
Add support for the next gen sidekick for the bulk publishing tool
Both signing in via the old and new sidekick should work.
Resolves: [MWPW-166739](https://jira.corp.adobe.com/browse/MWPW-166739)
**Test URLs:**
- Before: https://main--milo--adobecom.aem.live/tools/bulk-publish
- After: https://mwpw-166739--milo--mokimo.aem.live/tools/bulk-publish
> Bulk publish sidekick v7 support

- libs/blocks/global-navigation/global-navigation.css
- libs/blocks/global-navigation/global-navigation.js
- libs/utils/utils.js
- test/blocks/global-navigation/global-navigation.test.js
- test/blocks/global-navigation/test-utilities.js
Reverts adobecom/milo#3367 as we discussed this to be included in the batch on monday.
> Revert "MWPW-158537 : Upgrade Universal Nav to version 1.4"

- tools/floodbox/floodgate/floodgate.js
- tools/floodbox/graybox/graybox.js
Resolves: [MWPW-161576](https://jira.corp.adobe.com/browse/MWPW-161576)
**Test URLs:**
- After: https://da.live/app/adobecom/milo/tools/graybox?ref=stage
https://lint-fix--milo--adobecom.hlx.page/drafts/sukamat/abc?martech=off
> MWPW-161576: eslint fix

- libs/blocks/locui-create/store.js
- libs/blocks/locui-create/utils/utils.js
* Removed get tenant function and used origin instead.
Resolves: https://jira.corp.adobe.com/browse/MWPW-166771
**Test URLs:**
- After: https://MWPW-166771-tenant-specific-lang--milo--saurabhsircar11.hlx.page/drafts/sircar/locui-create?martech=off
> [LOC]MWPW-166771 - fetch tenant specific locales

- libs/blocks/modal/modal.css
This reverts commit 3b7b598d95b246447d8948549973078c789b753d.
This reverts the changes from [this PR](https://github.com/adobecom/milo/pull/3574).
Resolves: [MWPW-166092](https://jira.corp.adobe.com/browse/MWPW-166092)
**Milo:**
- Before: https://main--milo--adobecom.hlx.page/drafts/rbogos/page-default?martech=off
- After: https://mwpw-166092-revert--adobecom.hlx.page/drafts/rbogos/page-default?martech=off
> [MWPW-166092] Revert "fix for modal video not showing"

- libs/features/webapp-prompt/webapp-prompt.js
- test/features/webapp-prompt/mocks/pep-prompt-content.js
- test/features/webapp-prompt/test-utilities.js
- test/features/webapp-prompt/webapp-prompt.test.js
Clear Timeout issue fix for the scenario when pause on hover feature is off.
Resolves: [MWPW-166884](https://jira.corp.adobe.com/browse/MWPW-166884)
**Test URLs:**
- After: https://feds--milo--adobecom.aem.page/?martech=off
QA:
- https://feds--milo--adobecom.hlx.page/drafts/devashish/pep/pep-prompt?skipPepEntitlements=true (without pause on hover)
- https://feds--milo--adobecom.hlx.page/drafts/devashish/pep/pause/pep-prompt-pause-animation?skipPepEntitlements=true (with pause on hover)
> [MWPW-166884] - PEP Bug fix

- libs/blocks/global-navigation/global-navigation.css
- libs/blocks/global-navigation/global-navigation.js
- libs/utils/utils.js
- test/blocks/global-navigation/global-navigation.test.js
- test/blocks/global-navigation/test-utilities.js
Reverts #3604 , as there is change in timeline
> Revert "MWPW-158537 : Upgrade Universal Nav to version 1.4 (#3604)"

- libs/features/personalization/personalization.js
- libs/martech/helpers.js
- libs/martech/helpers.md
- libs/utils/utils.js
- test/martech/helpers.test.js
- Add page view call and propositionDisplay instead of propositionFetch
- Remove Comments from Helpers
https://main--cc--adobecom.hlx.live/drafts/suhjain/swati-pages/photoshop-v2?target=on&milolibs=ENB-7656-hybrid-personalization-v2--milo--swamu
Resolves: [ENB-7656](https://jira.corp.adobe.com/browse/ENB-7656)
Test URLs:
After: https://enb-7656-hybrid-personalization-v2--milo--swamu.aem.page/?martech=off
> [ENB-7656] Hybrid Personalization - Move Page View Call to Milo Api Approach

- libs/blocks/tabs/tabs.css
This resolves a11y contrast problems for tabs.
Resolves: [MWPW-166631](https://jira.corp.adobe.com/browse/MWPW-166631)
**Test URLs:**
- Before: https://main--milo--adobecom.aem.page/docs/library/kitchen-sink/tab-block?martech=off
- After: https://tab-color-contrast--milo--adobecom.aem.page/docs/library/kitchen-sink/tab-block?martech=off
> [MWPW-166631] Tab color contrast

- libs/blocks/aside/aside.css
- libs/blocks/video/video.css
Resolves: [MWPW-162345](https://jira.corp.adobe.com/browse/MWPW-162345)
**Test URLs:**
- Before: https://main--milo--adobecom.hlx.page/drafts/ratko/mwpw-162345/aside-video?martech=off
- After: https://mwpw-162345-aside-video-tablet--milo--adobecom.hlx.page/drafts/ratko/mwpw-162345/aside-video?martech=off
> MWPW-162345: Fix aside video on tablet

- libs/blocks/global-navigation/global-navigation.css
> Revert "Prevent a console error from the global navigation main menu"

- libs/blocks/locui-create/utils/utils.js
* Removed sdl check if the page was hlx or aem
* Input urls and fragment validation will accept all hlx and aem pages for all tenants
Resolves: https://jira.corp.adobe.com/browse/MWPW-166672
**Test URLs:**
- After: https://MWPW-166672-hlx-sup-all--milo--saurabhsircar11.hlx.page/drafts/sircar/locui-create?martech=off
> [LOC]MWPW-166672 - Providing hlx support for all tenants

- libs/blocks/table/table.css
- libs/features/icons/icons.js
- test/features/icons/icons.test.js
This solution allows use of tooltips for all icons.
Resolves: [MWPW-160510](https://jira.corp.adobe.com/browse/MWPW-160510)
**Test URLs:**
- Before: https://main--milo--adobecom.hlx.page/drafts/dusan/icon-tooltip-enhancement?martech=off
- After: https://icon-tooltip-enhancement--milo--adobecom.hlx.page/drafts/dusan/icon-tooltip-enhancement?martech=off
> [MWPW-160510] tooltip enabled on all icons

- libs/blocks/locui/locui.css
* added margin for header
* increased the specificity of locui css
Resolves: https://jira.corp.adobe.com/browse/MWPW-166771
**Test URLs:**
- Before: https://locui--milo--adobecom.hlx.page/tools/loc?martech=off
- After: https://mwpw-166771-locui-css-spec--milo--saurabhsircar11.hlx.page/tools/loc?martech=off
> [LOC]Mwpw 166771 - Fixed css for card and header for express

- libs/blocks/global-navigation/global-navigation.js
- libs/navigation/build.mjs
- libs/navigation/package.json
* Adding new config to support unav 1.4 features
Resolves: [MWPW-167283](https://jira.corp.adobe.com/browse/MWPW-167283)
**Test URLs:**
- After: https://gnav--milo--adobecom.aem.page/?martech=off
QA: https://adobecom.github.io/nav-consumer/navigation.html?env=stage&navbranch=gnav&authoringpath=/federal/home&customlinks=home,apps,learn,files,discover&unav=help,profile,cart
> Upgrading standalone gnav with unav 1.4

- libs/blocks/mmm/mmm.css
- libs/blocks/mmm/mmm.js
- libs/features/personalization/personalization.js
- test/blocks/mmm/mmm.test.js
* Added filter option by Subdomain (options: www, business, all)
* Added Local Storage cacheing for filter settings
* Converted search by url to search by : page URL, manifest URL, manifest experience name or Target activity name (comma separated and stands for OR only for now)
* converted GET call to POST for `get-pages`
Resolves: [MWPW-166793](https://jira.corp.adobe.com/browse/MWPW-166793)
**Test URLs:**
- Before: https://main--milo--adobecom.hlx.page/drafts/mepdev/2025/q1/mmm/
- Psi check: https://mmm-subdomain-filter--milo--adobecom.hlx.page/drafts/mepdev/2025/q1/mmm/
> [MWPW-166793] MMM subdomain filter + local storage cacheing

- libs/blocks/text/text.css
Resolves: [MWPW-157733](https://jira.corp.adobe.com/browse/MWPW-157733)
**Test URLs:**
- Before: https://main--milo--adobecom.hlx.page/drafts/ratko/mwpw-157733/ul-checkmark?martech=off
- After: https://mwpw-157733-ul-checkmark--milo--adobecom.hlx.page/drafts/ratko/mwpw-157733/ul-checkmark?martech=off
> MWPW-157733: Fix checkmark with bold text

- libs/blocks/table/table.css
- libs/features/icons/icons.css
Resolves: [MWPW-155282](https://jira.corp.adobe.com/browse/MWPW-155282)
**Test URLs:**
- After: https://table-tooltip-enhancement--milo--adobecom.aem.page/docs/library/kitchen-sink/table?martech=off
> [MWPW-155282] table tooltip enhancements

- libs/blocks/locui-create/input-locale/index.js
* added check for adding regions if there are locales
Resolves: https://jira.corp.adobe.com/browse/MWPW-167503
**Test URLs:**
- After: https://MWPW-167503-removed-filters--milo--saurabhsircar11.hlx.page/drafts/sircar/locui-create?martech=off
> MWPW-167503 - Removed filter when no locales are there

- libs/blocks/global-footer/global-footer.js
- libs/blocks/global-navigation/features/breadcrumbs/breadcrumbs.js
- libs/blocks/global-navigation/features/profile/dropdown.js
- libs/blocks/global-navigation/features/search/gnav-search.js
- libs/blocks/global-navigation/global-navigation.js
- libs/blocks/global-navigation/utilities/keyboard/index.js
- libs/blocks/global-navigation/utilities/keyboard/mainNav.js
- libs/blocks/global-navigation/utilities/keyboard/mobilePopup.js
- libs/blocks/global-navigation/utilities/keyboard/popup.js
- libs/blocks/global-navigation/utilities/menu/menu.js
- libs/blocks/global-navigation/utilities/utilities.js
- libs/navigation/bootstrapper.js
- libs/navigation/navigation.js
- test/blocks/global-footer/global-footer.test.js
- test/blocks/global-navigation/features/breadcrumbs.test.js
- test/blocks/global-navigation/global-navigation.test.js
- test/blocks/global-navigation/utilities/utilities.test.js
- test/navigation/navigation.test.js
* Updating the error tags to module and error type separately
* Added gnav source to standalone gnav as gnav source in lana log was showing null
* Added an additional lana log for onError callback 
Resolves:
[MWPW-166224](https://jira.corp.adobe.com/browse/MWPW-166224)
[MWPW-164706](https://jira.corp.adobe.com/browse/MWPW-164706)
[MWPW-164707](https://jira.corp.adobe.com/browse/MWPW-164707)
[MWPW-164709](https://jira.corp.adobe.com/browse/MWPW-164709)
[MWPW-164711](https://jira.corp.adobe.com/browse/MWPW-164711)
[MWPW-164712](https://jira.corp.adobe.com/browse/MWPW-164712)
**Test URLs:**
- After: https://gnav-lana--milo--adobecom.aem.live/?martech=off
**Standalone gnav** - …
> Gnav Lana log error tags fix 

- libs/features/personalization/personalization.js
- test/features/personalization/actions.test.js
- test/features/personalization/mocks/actions/manifestUpdateAttribute.json
- test/features/personalization/modifyNonFragmentSelector.test.js
- test/features/personalization/personalization.test.js
Includes 2 complete and vetted PRs:
* [[MWPW-166126] Add new "updateAttribute" action to MEP](https://github.com/adobecom/milo/pull/3670)
* [MWPW-168109: do not modify absolute path to a script hosted in DAM when using insertScript action](https://github.com/adobecom/milo/pull/3708)
Resolves: 
[MWPW-166126](https://jira.corp.adobe.com/browse/MWPW-166126)
[MWPW-168109](https://jira.corp.adobe.com/browse/MWPW-168109)
**Test URLs:**
- After: https://mepstage--milo--adobecom.aem.page/?martech=off
> MWPW-168109, 166126 MEP Stage Batch

- .github/workflows/run-nala-default.yml
- nala/utils/pr.run.sh
* Purge pr branch cache before running NALA tests on PR
* Provide options to trigger in NALA tests manually 
Resolves: [MWPW-168075](https://jira.corp.adobe.com/browse/MWPW-168075)
**Test URLs:**
- After: https://nala-cache--milo--adobecom.aem.page/?martech=off
> [NALA][MWPW-168075] Purge cache before running NALA tests on PR

- libs/blocks/mmm/mmm.css
- libs/blocks/mmm/mmm.js
This PR introduces a more attractive and user friendly pagination design to MMM. 
* Replaced page number links with arrow navigation UI
* Arrows will automatically gray out and be _disabled_ if user is at the start or end of list
* Range numbers have commas via toLocaleString()
* Dropdown options to show x number of records per page: 25 (default), 50, 100
* Share url will only copy search values, not current perPage or pageNum setting
Resolves: [MWPW-164728](https://jira.corp.adobe.com/browse/MWPW-164728)
**Test URLs:**
- PSI check: https://mmm-pagination-style--milo--adobecom.aem.page/?martech=off
------
**QA URLs**
**base url (check functionality and use share button as needed):** …
> MWPW-164728 [MMM] Improve design of pagination

- libs/blocks/tabs/tabs.css
Resolves: [MWPW-168041](https://jira.corp.adobe.com/browse/MWPW-168041)
|----------|----------|
| <img width="182" alt="Screenshot 2025-02-18 at 16 56 08" src="https://github.com/user-attachments/assets/cd362f71-ec12-4f72-9bb2-d54bd5268bda" />  | <img width="167" alt="Screenshot 2025-02-18 at 16 56 22" src="https://github.com/user-attachments/assets/ec82bbd2-755e-452b-9f5d-5a1e1d612ad0" /> |
**Milo:**
- Before: https://main--milo--adobecom.hlx.page/docs/library/kitchen-sink/brick?martech=off
- After: https://pill-tab-border--milo--adobecom.hlx.page/docs/library/kitchen-sink/brick?martech=off
> [MWPW-168041] pill tab border removal

- libs/blocks/locui-create/input-locale/view.js
- libs/blocks/locui-create/input-urls/index.js
- libs/blocks/locui-create/input-urls/view.js
- libs/blocks/locui-create/locui-create.js
- libs/blocks/locui-create/store.js
- libs/blocks/locui-create/utils/constant.js
* Added the Promote rollout workflow for loc.
Resolves: [MWPW-168395](https://jira.corp.adobe.com/browse/MWPW-168395)
**Test URLs:**
- Before: https://milostudio-stage--milo--adobecom.hlx.page/drafts/sircar/locui-create?martech=off
- After: https://mwpw-168395-promote-workflow--milo--maagrawal16.hlx.page/drafts/sircar/locui-create?martech=off
> [MWPW-168395] Add Promote workflow in Miloc

- libs/blocks/locui/actions/index.js
- libs/blocks/locui/actions/view.js
- libs/blocks/locui/loc/index.js
- libs/blocks/locui/utils/franklin.js
- libs/blocks/locui/utils/miloc.js
- libs/blocks/locui/utils/state.js
* Added specific flow flag to check if project is translation and v3.
* Introduced handleRolloutClick to check for v3 and v2, and run logic according to it.
Resolves: https://jira.corp.adobe.com/browse/MWPW-168413
**Test URLs:**
- Before: https://stage--milo--adobecom.hlx.page/tools/loc?martech=off
- After: https://MWPW-168413-rollout-all-v3--milo--saurabhsircar11.hlx.page/tools/loc?martech=off
> [LOC]MWPW-168413 - Promote rollout for translation project

- libs/blocks/locui/actions/index.js
- libs/blocks/locui/langs/index.js
- libs/blocks/locui/langs/view.js
- Single Language Rollout functionality in Project Details page for translate project created in V3
Resolves: https://jira.corp.adobe.com/browse/MWPW-168415
**Test URLs:**
- Before: https://locui-stage--milo--adobecom.hlx.page/tools/loc?martech=off
- After: https://mwpw-168415-single-language-rollout-v3--milo--varunpats.hlx.page/tools/loc?martech=off
> MWPW 168415 single language rollout v3

- libs/blocks/locui/utils/miloc.js
* Fixed sync issue.
Resolves: https://jira.corp.adobe.com/browse/MWPW-168413
**Test URLs:**
- Before: https://stage--milo--adobecom.hlx.page/tools/loc?martech=off
- After: https://MWPW-168413-fixed-sync-issue--milo--saurabhsircar11.hlx.page/tools/loc?martech=off
> [LOC] MWPW-168413 - fixed sync issue

- libs/blocks/table/table.css
- libs/blocks/table/table.js
This resolves the issue where the top tooltip was not properly displayed for right-to-left languages.
Resolves: [MWPW-167031](https://jira.corp.adobe.com/browse/MWPW-167031)
**Test URLs:**
- After: https://tooltip-rtl-position--milo--adobecom.aem.page/docs/library/kitchen-sink/table?martech=off
> [MWPW-167031] top tooltip rtl fix

- libs/utils/decorate.js
* Handled an error in decorate.js
Resolves: [MWPW-168006](https://jira.corp.adobe.com/browse/MWPW-168006)
**Test URLs:**
- Before: https://main--milo--adobecom.aem.page/drafts/sharathkannan/video-accessibility/fragments/hero-marquee1?martech=off
- After: https://mwpw-168006--milosh--sharath-kannan.hlx.page/drafts/sharathkannan/video-accessibility/fragments/hero-marquee1?martech=off
> Fix(mwpw-168006): Viewport bug fix.

- libs/blocks/locui-create/input-locale/index.js
- libs/blocks/locui-create/locui-create.js
- libs/blocks/locui-create/store.js
- libs/blocks/locui-create/utils/constant.js
- libs/blocks/locui-create/utils/utils.js
* Added Single Language Rollout.
* Fixed bug for [MWPW-168679](https://jira.corp.adobe.com/browse/MWPW-168679)
Resolves: [MWPW-168684](https://jira.corp.adobe.com/browse/MWPW-168684)
**Test URLs:**
- Before: https://milostudio-stage--milo--adobecom.aem.page?martech=off
- After: https://mwpw-168684-single-language-rollout--milo--maagrawal16.aem.page?martech=off
> [Loc][MWPW-168684] Single Language Rollout

- libs/features/webapp-prompt/webapp-prompt.js
* Updating tags and errortype for PEP lana logs
Resolves: [MWPW-168045](https://jira.corp.adobe.com/browse/MWPW-168045)
**Test URLs:**
- After: https://pep-lana--milo--adobecom.hlx.page/drafts/devashish/pep/pause/pep-prompt-pause-animation?skipPepEntitlements=true
> Updating tags and errortype for PEP lana logs

- libs/blocks/tabs/tabs.css
- libs/blocks/tabs/tabs.js
This PR adjusts colors for pill tabs to be in line with the updated design.
Resolves: [MWPW-166184](https://jira.corp.adobe.com/browse/MWPW-166184)
**Test URLs:**
- Before: https://main--milo--adobecom.aem.page/docs/library/kitchen-sink/tab-block?martech=off
- After: https://pill-tab-color--milo--adobecom.aem.page/docs/library/kitchen-sink/tab-block?martech=off
> [MWPW-166184] - Pill tab color change

- libs/blocks/locui/loc/index.js
- libs/blocks/locui/utils/franklin.js
Sync back locui to locui-stage
Resolves: [MWPW-166940](https://jira.corp.adobe.com/browse/MWPW-166940)
**Test URLs:**
- Before: https://locui--milo--adobecom.aem.page/tools/loc?ref=main&repo=milo&owner=adobecom&host=milo.adobe.com&project=Milo&referrer=https%3A%2F%2Fadobe.sharepoint.com%2F%3Ax%3A%2Fr%2Fsites%2Fadobecom%2F_layouts%2F15%2FDoc.aspx%3Fsourcedoc%3D%257B21a05280-fe1b-4d36-84cc-e301c6416083%257D%26action%3Deditnew
- After: https://locui--milo--raga-adbe-gh.aem.page/tools/loc?ref=main&repo=milo&owner=adobecom&host=milo.adobe.com&project=Milo&referrer=https%3A%2F%2Fadobe.sharepoint.com%2F%3Ax%3A%2Fr%2Fsites%2Fadobecom%2F_layouts%2F15%2FDoc.aspx%3Fsourcedoc%3D%257B21a05280-fe1b-4d36-84cc-e301c6416083%257D%26action%3Deditnew
> [LOC UI] MWPW-166940 - Sync to LocUI Stage

- tools/da-apps/auth.js
* Added support for da-bacom-blog as a valid tenant to access MiloStudio DA Apps by adding it's entry in ORG_MAP
**Test URLs:**
- After: https://mwpw-169452-support-da-bacom-blog--milo--nkthakur48.aem.page/?martech=off
> MWPW-169452 [DA] Add support for da-bacom-blog tenant to access MS DA Apps

- libs/blocks/article-header/article-header.js
* Update invalid lana tag in article header
Resolves: [MWPW-165253](https://jira.corp.adobe.com/browse/MWPW-165253)
**Test URLs:**
- After: https://lana-article--milo--meganthecoder.aem.page/?martech=off
> MWPW-165253 Update invalid lana tag

- libs/blocks/caas-config/caas-config.js
- libs/blocks/caas/utils.js
- test/blocks/caas-config/expectedConfigs/defaultConfig.js
- test/blocks/caas/utils.test.js
Description:
MWPW-169786: fixes label capitalization
Resolves: [MWPW-169786](https://jira.corp.adobe.com/browse/MWPW-169786)
**Test URLs:**
- Before: https://main--milo--adobecom.aem.page/drafts/cmiqueo/test-page?martech=off
- After: https://MWPW-169786--milo--adobecom.aem.page/drafts/cmiqueo/test-page?martech=off
> MWPW-169786: fixes label capitalization

- libs/blocks/caas-config/caas-config.js
Description:
Nests Show Pagination Quantity inside Pagination option
Resolves: [MWPW-169945](https://jira.corp.adobe.com/browse/MWPW-169945)
- https://MWPW-169314--milo--adobecom.aem.page/drafts/cmiqueo/test-page
- https://main--milo--adobecom.aem.page/drafts/cmiqueo/test-page
Image
Image
> Nests Show Pagination Quantity inside Pagination option

- libs/blocks/merch/merch.js
Resolves: [MWPW-168447](https://jira.corp.adobe.com/browse/MWPW-168447)
**Test URLs:**
- Before: https://main--milo--adobecom.aem.page/drafts/seanchoi/merch-card-special-offers?martech=off
- After: https://mwpw-168447--milo--adobecom.aem.page/drafts/seanchoi/merch-card-special-offers?martech=off
> MWPW-168447: Enable to override aria-label on checkout link via word doc

- tools/sidekick/config.json
sidekick config changes for helix 5
Resolves: [MWPW-166785](https://jira.corp.adobe.com/browse/MWPW-166785)
**Test URLs:**
- After: https://floodgateui-helix-5--milo--adobecom.aem.page/?martech=off
> sidekick config changes for helix 5

- libs/blocks/graybox-promote/components/graybox-promote-lit.js
- tools/sidekick/config.json
* changed all .hlx. references if .aem. for graybox promote
Resolves: [MWPW-166787](https://jira.corp.adobe.com/browse/MWPW-166787)
**Test URLs:**
- After: https://graybox-promote-helix5--milo--adobecom.aem.page/?martech=off
> Graybox Promote - Helix 5 upgrade

- libs/blocks/quiz/quiz.css
- libs/blocks/quiz/quiz.js
- libs/blocks/quiz/stepIndicator.js
* changed position of step indicator to avoid collision with promos
* removed bottom indicator
* small accessibility changes
Resolves - bug: [mwpw-168732](https://jira.corp.adobe.com/browse/MWPW-168732)
Resolves - accessibility: [mwpw-170398](https://jira.corp.adobe.com/browse/MWPW-170398)
**Test URLs:**
- After: https://quiz-step-indicator-enhancement--milo--colloyd.aem.page/drafts/colloyd/quiz/?martech=off
> Quiz step indicator enhancement

- libs/utils/utils.js
fix nala
Resolves: [MWPW-169933](https://jira.corp.adobe.com/browse/MWPW-169933)
**Test URLs:**
- After: https://vhargrave-fix-nala--milo--adobecom.aem.page/?martech=off
> MWPW-169933 catch case for no region match / fix nala

- libs/blocks/mmm/mmm.css
- libs/blocks/mmm/mmm.js
Added link to target activity manifest insides Target Report
Resolves: [N/A](https://jira.corp.adobe.com/browse/MWPW-NUMBER)
**Test URLs:**
- Before: https://main--milo--adobecom.hlx.page/docs/authoring/features/mmm-target-cleanup
- After: https://mmm-report-target-activity-name--milo--adobecom.hlx.page/docs/authoring/features/mmm-target-cleanup
> Added link to target activity manifest inside Target Report

- libs/blocks/preflight/panels/seo.js
* Exclude non content text
Resolves: [MWPW-171023](https://jira.corp.adobe.com/browse/MWPW-171023)
**Test URLs:**
- Before: https://main--milo--adobecom.aem.page/drafts/narcis/applauncher?martech=off
- After: https://mwpw-171023-seo-body-size--milo--adobecom.aem.page/drafts/narcis/applauncher?martech=off
- Before: https://main--milo--adobecom.aem.page/drafts/ratko/mwpw-171023-seo/seo?martech=off
- After: https://mwpw-171023-seo-body-size--milo--adobecom.aem.page/drafts/ratko/mwpw-171023-seo/seo?martech=off
> MWPW-171023: Fix seo body size check

- libs/blocks/region-nav/region-nav.js
* Add your
* Specific
Resolves: [MWPW-171040](https://jira.corp.adobe.com/browse/MWPW-171040)
**Test URLs:**
- After: https://<branch>--milo--adobecom.aem.page/?martech=off
> MWPW-171040-region-nav-lang: support for url formats lan/reg

- libs/utils/automated-aria.js
Fixes an error occuring with some nala tests - https://github.com/adobecom/milo/pull/4025
Resolves: [MWPW-165540](https://jira.corp.adobe.com/browse/MWPW-165540)
**Test URLs:**
After: https://vhargrave-fix-console-error-aria--milo--adobecom.aem.page/?martech=off
look at the primary CTAs in the hero-marquee
Before: https://main--cc--adobecom.aem.live/products/photoshop-lightroom/edit-photos/?martech=off
After: https://main--cc--adobecom.aem.live/products/photoshop-lightroom/edit-photos?milolibs=vhargrave-fix-console-error-aria
look at the CTAs in the hero-marquee
Before: https://main--cc--adobecom.aem.live/ch_de/products/photoshop-lightroom/edit-photos/?martech=off
After: https://main--cc--adobecom.aem.live/ch_de/products/photoshop- …
> MWPW-165540 fix error if cta has no href

- libs/blocks/global-footer/global-footer.css
- libs/blocks/global-footer/global-footer.js
* Adding old adobe A icon to footer if authored
Resolves: [MWPW-167956](https://jira.corp.adobe.com/browse/MWPW-167956)
**Test URLs:**
- After: https://footer-old-logo--milo--adobecom.aem.page/?martech=off
Qa: https://main--federal--adobecom.aem.page/drafts/blaishram/page-footer-logo?milolibs=footer-old-logo
- Acrobat: https://main--dc--adobecom.hlx.live/acrobat?martech=off&milolibs=footer-old-logo--milo--adobecom
- BACOM: https://main--bacom--adobecom.hlx.live/?martech=off&milolibs=footer-old-logo--milo--adobecom
- CC: https://main--cc--adobecom.aem.live/creativecloud?martech=off&milolibs=footer-old-logo--milo--adobecom
- Milo: https://footer-old-logo--milo--adobecom.aem.page/drafts/blais …
> [Footer] | Add legacy Adobe "A" logo to footer (Mobile & Desktop)

- libs/blocks/global-navigation/base.css
- libs/blocks/global-navigation/dark-nav.css
- libs/blocks/global-navigation/global-navigation.css
- libs/blocks/global-navigation/utilities/utilities.js
*  Making sub header visible on mobile
Resolves: [MWPW-164532](https://jira.corp.adobe.com/browse/MWPW-164532)
**Test URLs:**
- After: https://mgnav-subheading--milo--adobecom.aem.page/?martech=off
QA: https://main--homepage--adobecom.aem.live/homepage/index-loggedout?martech=off&milolibs=mgnav-subheading
- Acrobat: https://main--dc--adobecom.hlx.live/acrobat?martech=off&milolibs=mgnav-subheading--milo--adobecom
- BACOM: https://main--bacom--adobecom.hlx.live/?martech=off&milolibs=mgnav-subheading--milo--adobecom
- CC: https://main--cc--adobecom.aem.live/creativecloud?martech=off&milolibs=mgnav-subheading--milo--adobecom
- Milo: https://mgnav-subheading--milo--adobecom.aem.page/drafts/blai …
> New Mobile Sub-header Enhancement - Making sub header visible on mobile

- libs/blocks/quiz/quiz.css
- libs/blocks/quiz/quizoption.js
* Card text and image order swapped, visual checkbox added, and focus-visibility adjusted
* Quiz Button focus visible set to match the new card style
Resolves: [MWPW-170399](https://jira.corp.adobe.com/browse/MWPW-170399)
**Test URLs:**
- After: https://quiz-card-accessibility--milo--colloyd.aem.page/drafts/colloyd/quiz/?martech=off
> Quiz card accessibility

- libs/blocks/global-footer/global-footer.js
- libs/blocks/global-navigation/features/breadcrumbs/breadcrumbs.js
- libs/blocks/global-navigation/features/profile/dropdown.js
- libs/blocks/global-navigation/features/search/gnav-search.js
- libs/blocks/global-navigation/global-navigation.js
- libs/blocks/global-navigation/utilities/keyboard/index.js
- libs/blocks/global-navigation/utilities/keyboard/mainNav.js
- libs/blocks/global-navigation/utilities/keyboard/mobilePopup.js
- libs/blocks/global-navigation/utilities/keyboard/popup.js
- libs/blocks/global-navigation/utilities/menu/menu.js
- libs/blocks/global-navigation/utilities/utilities.js
- libs/features/webapp-prompt/webapp-prompt.js
* Put severity level as Tag(s) for LANA messages
Resolves: [MWPW-168539](https://jira.corp.adobe.com/browse/MWPW-168539)
**Test URLs:**
- After: https://gnav-lana--milo--adobecom.aem.page/?martech=off
- Acrobat: https://main--dc--adobecom.hlx.live/acrobat?martech=off&milolibs=gnav-lana--milo--adobecom
- BACOM: https://main--bacom--adobecom.hlx.live/?martech=off&milolibs=gnav-lana--milo--adobecom
- CC: https://main--cc--adobecom.aem.live/creativecloud?martech=off&milolibs=gnav-lana--milo--adobecom
- Milo: https://gnav-lana--milo--adobecom.aem.page/drafts/blaishram/test-urls/page?martech=off
- Express: https://main--express-milo--adobecom.aem.live/express/?martech=off&milolibs=gnav-lana--mil …
> Gnav lana: Put severity level as Tag(s) for LANA messages

- libs/blocks/tabs/tabs.js
This resolves the issue found in stage->main release https://github.com/adobecom/milo/pull/4091#pullrequestreview-2822074190
Resolves: [MWPW-172157](https://jira.corp.adobe.com/browse/MWPW-172157)
**Test URLs:**
Before: https://main--milo--adobecom.aem.page/docs/library/kitchen-sink/tab-block?martech=off
After: https://fix-tab-mobile-scroll--milo--adobecom.aem.page/docs/library/kitchen-sink/tab-block?martech=off
**DC Test URLs:**
Before: https://main--dc--adobecom.aem.live/acrobat/features?milolibs=stage
After: https://main--dc--adobecom.aem.live/acrobat/features?milolibs=fix-tab-mobile-scroll
> [MWPW-172157] - fix tab error

- libs/blocks/locui/actions/index.js
- libs/blocks/locui/actions/modal.js
- libs/blocks/locui/langs/index.js
- libs/blocks/locui/langs/view.js
- libs/blocks/locui/utils/miloc.js
Adding support for cancelling the language when in translation or rolling-out.
Resolves: [MWPW-167155](https://jira.corp.adobe.com/browse/MWPW-167155)
**Test URLs:**
- Before: https://locui--milo--adobecom.aem.page/tools/loc?ref=main&repo=milo&owner=adobecom&host=milo.adobe.com&project=Milo&referrer=https%3A%2F%2Fadobe.sharepoint.com%2F%3Ax%3A%2Fr%2Fsites%2Fadobecom%2F_layouts%2F15%2FDoc.aspx%3Fsourcedoc%3D%257B21a05280-fe1b-4d36-84cc-e301c6416083%257D%26action%3Deditnew
- After: https://locui-debug--milo--raga-adbe-gh.aem.page/tools/loc?ref=main&repo=milo&owner=adobecom&host=milo.adobe.com&project=Milo&referrer=https%3A%2F%2Fadobe.sharepoint.com%2F%3Ax%3A%2Fr%2Fsites%2Fadobecom%2F_layouts%2F15%2FDoc.aspx%3Fsourcedoc%3D%257B21a05280-fe1b-4d36-84cc-e301c6416083%257D%26action%3Deditnew
> [LOC UI] MWPW-167155 Cancel language support

- libs/blocks/columns/columns.css
- libs/blocks/columns/columns.js
* Move row title to the top
Resolves: [MWPW-170339](https://jira.corp.adobe.com/browse/MWPW-170339)
Screenshots:
**Test URLs:**
- Before: https://main--milo--adobecom.aem.page/drafts/ratko/mwpw-170339-columns-table/columns-table?martech=off
- After: https://mwpw-170339-column-block-320--milo--adobecom.aem.page/drafts/ratko/mwpw-170339-columns-table/columns-table?martech=off
- Before: https://main--milo--adobecom.hlx.page/docs/library/blocks/columns?martech=off
- After: https://mwpw-170339-column-block-320--milo--adobecom.hlx.page/docs/library/blocks/columns?martech=off
- Before: https://main--bacom--adobecom.aem.page/customers/consulting-services/premier-support
- After: https://main--bacom--adobecom.aem.page/customers/consulting-services/premier-support?milolibs=mwpw-17033 …
> MWPW-170339: Move row title

- libs/blocks/adobetv/adobetv.js
- libs/blocks/iframe/iframe.js
- libs/blocks/modal/modal.js
- libs/blocks/vimeo/vimeo.js
- libs/blocks/youtube/youtube.js
- libs/scripts/accessibility.js
- libs/utils/utils.js
- test/blocks/instagram/mocks/embed-utils.js
This resolves the issue where the dialog container was missing multiple necessary accessability attributes.
Resolves: [MWPW-170305](https://jira.corp.adobe.com/browse/MWPW-170305)
**Test URLs:**
- Before: https://main--milo--adobecom.hlx.page/drafts/dusan/dialog-role-aria-label?martech=off
- After: https://dialog-role-title--milo--adobecom.aem.page/drafts/dusan/dialog-role-aria-label?martech=off
- Before: https://main--cc--adobecom.aem.page/products/catalog
- After: https://main--cc--adobecom.aem.page/products/catalog?milolibs=dialog-role-title
> [MWPW-170305] - Dialog attributes

- libs/mep/ace1052/hero-marquee/hero-marquee.css
- libs/mep/ace1052/hero-marquee/hero-marquee.js
- Allow for Center alignment of text link in hero-marquee block
- Allow for icons within con-block-row-list variant within the hero-marquee (or an alternative way to achieve icons in a listed format within that block)
- Allow for con-block-text to center when a hero-marquee is left aligned (or an alternative way to achieve center alignment for the blurb within that block)
Resolves: [MWPW-171432](https://jira.corp.adobe.com/browse/MWPW-171432)
**Test URLs:**
- After: https://<branch>--milo--adobecom.aem.page/?martech=off
> MWPW-171432 | Hero Marquee mweb changes in mep test

- libs/mep/ace1052/carousel/carousel.css
- libs/mep/ace1052/carousel/carousel.js
- libs/mep/ace1052/hero-marquee/hero-marquee.css
- libs/mep/ace1052/hero-marquee/hero-marquee.js
We are not able to test the changes from the mweb branch, so pushing it to stage. It is zero impact as the changes are in the test folder.
* Carousel changes
* Hero marquee changes
Resolves: [MWPW-171542](https://jira.corp.adobe.com/browse/MWPW-171542)
[MWPW-171432](https://jira.corp.adobe.com/browse/MWPW-171432)
**Test URLs:**
- After: https://mweb--milo--adobecom.aem.page/?martech=off
> Merging the mweb changes to stage

- libs/blocks/preflight/panels/seo.js
- libs/blocks/preflight/preflight.js
Sync of a feature branch from a fork to the main repo.
> preflight-poc

- libs/utils/utils.js
* Fix localized links getting localized for language based site urls
Resolves: [MWPW-172825](https://jira.corp.adobe.com/browse/MWPW-172825)
**Test URLs:**
Milo
- Before: https://stage--milo--adobecom.hlx.page/en/apac/?martech=off
- After: https://mwpw-172825--milo--adobecom.hlx.page/en/apac/?martech=off
News
- Before: https://stage--news--adobecom.hlx.page/en/apac/?milolibs=stage&martech=off
- After: https://stage--news--adobecom.hlx.page/en/apac/?milolibs=MWPW-172825&martech=off
> [MWPW-172825] Fix localized links getting localized again for language based site urls

- libs/blocks/share/share.css
* Share Block: Consonant & A11Y Enhancements
Resolves: [MWPW-170326](https://jira.corp.adobe.com/browse/MWPW-170326)
**Test URLs:**
- After: https://mwpw-170326--milo--hkuraware.aem.page/?martech=off
> MWPW-170326: Consonant & A11Y Enhancements

- libs/blocks/global-navigation/utilities/menu/menu.js
* Fixed Visual list is not marked up as list a11y issue. 
Resolves: [MWPW-170454](https://jira.corp.adobe.com/browse/MWPW-170454)
**Test URLs:**
- After: https://mwpw-170454--milo--hkuraware.aem.page/?martech=off
> MWPW-170454 : Visual list is not marked up as list

- libs/blocks/global-navigation/utilities/utilities.js
CSO Fix because the current sampleRate of 50% is DOSing the lana service.  We're getting  6-7,000 requests / minute to lana and the limit is 2k / minute.  This should reduce the requests to ~140 / minute.
- Acrobat: https://main--dc--adobecom.hlx.live/acrobat?martech=off&milolibs=gnav-lanaflood--milo--adobecom
- BACOM: https://main--bacom--adobecom.hlx.live/?martech=off&milolibs=gnav-lanaflood--milo--adobecom
- CC: https://main--cc--adobecom.aem.live/creativecloud?martech=off&milolibs=gnav-lanaflood--milo--adobecom
- Milo: https://gnav-lanaflood--milo--adobecom.aem.page/drafts/blaishram/test-urls/page?martech=off
- Express: https://main--express-milo--adobecom.aem.live/express/?martech=off&milolibs=gnav-lanaflood--milo--adobecom
- News: …
> Reduce gnav lana sampleRate to 0.01%

- libs/blocks/locui-create/store.js
- libs/blocks/locui-create/utils/constant.js
- tools/da-apps/auth.js
Add Transcreation Locales in Select Languages Screen in dev
Resolves: [MWPW-173377](https://jira.corp.adobe.com/browse/MWPW-173377)
**Test URLs:**
- Before: https://milostudio-dev--milo--adobecom.aem.page/?martech=off
- After: https://dev-mwpw-173377-transcreation-locales--milo--adobecom.aem.page/?martech=off
> [Dev][Loc][MWPW 173377] Add Transcreation Locales in Select Languages Screen

- libs/blocks/locui-create/store.js
- libs/blocks/locui-create/utils/constant.js
* Removed filter to add transcreation locales
Resolves: [MWPW-173377](https://jira.corp.adobe.com/browse/MWPW-173377)
**Test URLs:**
- After: https://MWPW-173377-transcreation-locales--milo--maagrawal16.aem.page/?martech=off
> [Loc][MWPW-173377] Add Transcreation Locales in Select Languages Screen

- libs/utils/utils.js
Reverts adobecom/milo#4071 as it breaks the gnav for the partner portal.
- https://revert-4071-favicon-perf--milo--adobecom.aem.page/
> Revert "MWPW-171825 Improve lcp performance for favicon and breadcrumb"

- libs/blocks/mmm/mmm.css
- libs/blocks/mmm/mmm.js
- libs/features/personalization/preview.js
* Added ability to lookup searched pages' Target status from metadata files and update MMM DB with that information
Resolves: [MWPW-172083](https://jira.corp.adobe.com/browse/MWPW-172083)
**Test URLs:**
- Before: https://main--milo--adobecom.hlx.page/docs/authoring/features/mmm-target-metadata-lookup
- After: https://mmm-metadata-lookup--milo--adobecom.hlx.page/docs/authoring/features/mmm-target-metadata-lookup
> MWPW-172083 [MMM]: Target Metadata lookup

- libs/blocks/locui-create/components/dateTimePicker.js
- libs/blocks/locui-create/input-urls/index.js
- libs/blocks/locui-create/input-urls/view.js
- libs/blocks/locui-create/locui-create.css
- libs/blocks/locui-create/utils/utils.js
Resolves: [MWPW-173379](https://jira.corp.adobe.com/browse/MWPW-173379)
https://github.com/user-attachments/assets/ea3b43bf-0cc3-43a6-8b89-5cff502d8833
**Test URLs:**
- Before: https://milostudio-dev--milo--adobecom.aem.page/?martech=off
- After: https://mwpw-173379-date-time-picker--milo--adobecom.aem.page/?martech=off
> [Loc][MWPW-173379] Add Date Time Picker in Enter URLs Screen

- libs/blocks/locui-create/components/dateTimePicker.js
- libs/blocks/locui-create/input-urls/index.js
- libs/blocks/locui-create/input-urls/view.js
- libs/blocks/locui-create/locui-create.css
- libs/blocks/locui-create/utils/utils.js
Resolves: [MWPW-173379](https://jira.corp.adobe.com/browse/MWPW-173379)
https://github.com/user-attachments/assets/ea3b43bf-0cc3-43a6-8b89-5cff502d8833
**Test URLs:**
- Before: https://milostudio-dev--milo--adobecom.aem.page/?martech=off
- After: https://dev-mwpw-173379-date-time-picker--milo--adobecom.aem.page/?martech=off
> [Dev][Loc][MWPW-173379] Add Date Time Picker in Enter URLs Screen

- libs/blocks/global-navigation/global-navigation.js
- libs/blocks/global-navigation/utilities/keyboard/localNav.js
- libs/blocks/global-navigation/utilities/keyboard/utils.js
- libs/blocks/global-navigation/utilities/utilities.js
* Adding arrow Up/Down navigation for localnav items
* Localnav will open on arrow down
* If the focus is on last item when pressed arrow down the focus will go to localnav header
Resolves: [MWPW-164678](https://jira.corp.adobe.com/browse/MWPW-164678)
**Test URLs:**
- After: https://localnav-arrow--milo--adobecom.aem.page/?martech=off
QA: https://main--cc--adobecom.hlx.live/jp/creativecloud?milolibs=localnav-arrow
- Acrobat: https://main--dc--adobecom.hlx.live/acrobat?martech=off&milolibs=localnav-arrow--milo--adobecom
- BACOM: https://main--bacom--adobecom.hlx.live/?martech=off&milolibs=localnav-arrow--milo--adobecom
- CC: https://main--cc--adobecom.aem.live/creativecloud?martech=off&milo …
> Adding arrow Up/Down navigation for localnav

- libs/blocks/locui-create/input-urls/view.js
Resolves: [MWPW-173721](https://jira.corp.adobe.com/browse/MWPW-173721)
**Test URLs:**
- Before: https://milostudio-stage--milo--adobecom.aem.page/tools/locui-create?ref=main&repo=milo&owner=adobecom&host=milo.adobe.com&project=Milo&env=local&workflow=normal
- After: https://mwpw-173721-a11y-selector--milo--nkthakur48.aem.page/tools/locui-create?ref=main&repo=milo&owner=adobecom&host=milo.adobe.com&project=Milo&env=local&workflow=normal
> MWPW-173721 [Locv3] Made Translation/Rollout selection pill accessible

- libs/blocks/carousel/carousel.css
- libs/blocks/carousel/carousel.js
- nala/blocks/carousel/carousel.page.js
- nala/blocks/carousel/carousel.test.js
> Revert "Improve carousel accessibility"

- libs/blocks/carousel/carousel.css
- libs/blocks/carousel/carousel.js
- nala/blocks/carousel/carousel.page.js
- nala/blocks/carousel/carousel.test.js
Reverts adobecom/milo#4103
URL for the PSI check:
- https://revert-from-main--milo--mokimo.aem.live/
> Revert "Improve carousel accessibility (#4103)" from prod

- libs/blocks/region-nav/region-nav.css
* Overriding the default link text-decoration to none for region nav links
Resolves: [MWPW-173661](https://jira.corp.adobe.com/browse/MWPW-173661)
**Test URLs:**
- After: https://region-nav-link--milo--adobecom.aem.page/?martech=off
- Acrobat: https://main--dc--adobecom.hlx.live/acrobat?martech=off&milolibs=region-nav-link--milo--adobecom
- BACOM: https://main--bacom--adobecom.hlx.live/?martech=off&milolibs=region-nav-link--milo--adobecom
- CC: https://main--cc--adobecom.aem.live/creativecloud?martech=off&milolibs=region-nav-link--milo--adobecom
- Milo: https://region-nav-link--milo--adobecom.aem.page/drafts/blaishram/test-urls/page?martech=off
- Express: …
> Removing text decoration none from region nav links

- libs/blocks/global-navigation/features/breadcrumbs/breadcrumbs.js
- test/blocks/global-navigation/features/breadcrumbs.test.js
* Adds the last item value in the ld+json as current window url if it is not a link
Resolves: [MWPW-171709](https://jira.corp.adobe.com/browse/MWPW-171709)
**Test URLs:**
- After: https://breadcrumbs-last-item--milo--adobecom.aem.page/?martech=off
- Acrobat: https://main--dc--adobecom.hlx.live/acrobat?martech=off&milolibs=breadcrumbs-last-item--milo--adobecom
- BACOM: https://main--bacom--adobecom.hlx.live/?martech=off&milolibs=breadcrumbs-last-item--milo--adobecom
- CC: https://main--cc--adobecom.aem.live/creativecloud?martech=off&milolibs=breadcrumbs-last-item--milo--adobecom
- Milo: https://breadcrumbs-last-item--milo--adobecom.aem.page/drafts/blaishram/test-urls/page?martech=off
- …
> Breadcrumb last item value as current window url if not a link

- libs/blocks/quiz/quiz.css
* show titles on mobile
* add support for rtl for option titles
Resolves: [MWPW-173478](https://jira.corp.adobe.com/browse/MWPW-173478)
**Test URLs:**
- After: https://quiz-option-titles--milo--colloyd.aem.page/drafts/colloyd/quiz/?martech=off
> Quiz option titles on mobile

- CODEOWNERS
* Updating code owners for region nav and navigation folder
**Test URLs:**
- After: https://feds-codeowners--milo--adobecom.aem.page/?martech=off
> Updating code owners for region nav and navigation folder

- libs/blocks/global-navigation/utilities/keyboard/index.js
- libs/blocks/global-navigation/utilities/keyboard/mainNav.js
MWPW-170753 : [Mobile NAV][A11Y] | RWD Tablet Mobile - Fix for shiftTab and escape functionality
Resolves: [[MWPW-170753](https://jira.corp.adobe.com/browse/MWPW-170753)]
**Test URLs:**
- After: https://mwpw170753--milo--adobecom.aem.page/?martech=off
QA: https://main--homepage--adobecom.aem.live/homepage/index-loggedout?milolibs=mwpw170753
- Acrobat: https://main--dc--adobecom.hlx.live/acrobat?martech=off&milolibs=mwpw170753--milo--adobecom
- BACOM: https://main--bacom--adobecom.hlx.live/?martech=off&milolibs=mwpw170753--milo--adobecom
- CC: https://main--cc--adobecom.aem.live/creativecloud?martech=off&milolibs=mwpw170753--milo--adobecom
- Milo: …
> MWPW-170753 : [Mobile NAV][A11Y] | RWD Tablet Mobile

- libs/blocks/global-navigation/global-navigation.js
[Mobile NAV][A11Y] | Able to browse outside modal with screen reader
Resolves: [MWPW-170752](https://jira.corp.adobe.com/browse/MWPW-170752)
**Test URLs:**
- After: https://pagecontent--milo--adobecom.aem.page/?martech=off
QA: https://main--homepage--adobecom.aem.live/homepage/index-loggedout?milolibs=pagecontent
- Acrobat: https://main--dc--adobecom.hlx.live/acrobat?martech=off&milolibs=pagecontent--milo--adobecom
- BACOM: https://main--bacom--adobecom.hlx.live/?martech=off&milolibs=pagecontent--milo--adobecom
- CC: https://main--cc--adobecom.aem.live/creativecloud?martech=off&milolibs=pagecontent--milo--adobecom
- Milo: https://pagecontent--milo--adobecom.aem.page/drafts/blaishram/test-u …
> [Mobile NAV][A11Y] | RWD Tablet Mobile -Able to browse outside modal with screen reader

- libs/blocks/global-navigation/utilities/utilities.js
- libs/blocks/merch/merch.js
- libs/utils/decorate.js
- libs/utils/utils.js
Reverts adobecom/milo#4185
- Acrobat: https://main--dc--adobecom.hlx.live/acrobat?martech=off&milolibs=revert-4185-korea-free-trial-restrict--milo--adobecom
- BACOM: https://main--bacom--adobecom.hlx.live/?martech=off&milolibs=revert-4185-korea-free-trial-restrict--milo--adobecom
- CC: https://main--cc--adobecom.aem.live/creativecloud?martech=off&milolibs=revert-4185-korea-free-trial-restrict--milo--adobecom
- Milo: https://revert-4185-korea-free-trial-restrict--milo--adobecom.aem.page/drafts/blaishram/test-urls/page?martech=off
- Express: https://main--express-milo--adobecom.aem.live/express/?martech=off&milolibs=revert-4185-korea-free-trial-restrict--milo--adobecom
- News: …
> Revert "[MWPW-173470] - Korea free trial restrict" (stage)

- libs/blocks/mmm/mmm.js
- removed a line at the end of the report that appears after REPOS select has been toggled.
Resolves: [MWPW-174288](https://jira.corp.adobe.com/browse/MWPW-174288)
**Test URLs:**
- Before: https://main--milo--adobecom.hlx.page/docs/authoring/features/mmm/target-metadata-lookup?martech=off
- After: https://mmm-metadata-target-report-style-fix--milo--adobecom.hlx.page/docs/authoring/features/mmm/target-metadata-lookup?martech=off
Steps to reproduce the bug:
- Open report 
- Switch to a different repo 
- Observe the line showing right above the footer section of the page
> MWPW-174288 [MMM][MEP] Fix stying and DOM issue in new MMM report

- libs/blocks/global-navigation/utilities/utilities.js
- libs/blocks/merch/merch.js
- libs/utils/decorate.js
- libs/utils/utils.js
See https://github.com/adobecom/milo/pull/4264 for all details.
Resolves: [MWPW-173470](https://jira.corp.adobe.com/browse/MWPW-173470)
**Test URLs:**
**Test URLs:**
- Before: https://main--milo--adobecom.aem.page/kr/drafts/dusan/test-cta-removal?martech=off
- After: https://kr-free-trial-pack--milo--adobecom.aem.page/kr/drafts/dusan/test-cta-removal?martech=off
- Before: https://main--cc--adobecom.aem.page/kr/creativecloud/business/teams/free-trial-download
- After: https://main--cc--adobecom.aem.page/kr/creativecloud/business/teams/free-trial-download?milolibs=kr-free-trial-pack
**CC 2nd Test URLs:**
- Before: https://main--cc--adobecom.hlx.page/kr/products/photoshop?mep=off
- After: https://main--cc--adobecom.hlx.page/kr/products/photoshop?milolibs=kr-free-trial-pack&m …
> Korea free trial restrict (#4282)

- libs/mep/ace1052/carousel/carousel.css
- libs/mep/ace1052/carousel/carousel.js
- libs/mep/ace1052/editorial-card/editorial-card.css
Making the hinting card's height smaller that the rest.
Resolves: [[MWPW-171542]](https://jira.corp.adobe.com/browse/MWPW-171542)
Test URLs:
After: https://carousel-hinting-card-height--milo--suhjainadobe.aem.page/drafts/suhjain/m2-folder/carousel/document1?mep=/drafts/suhjain/ace1052.json&martech=off&georouting=off
> Carousel hinting card height

- libs/styles/styles.css
Reverts adobecom/milo#4199
- Acrobat: https://main--dc--adobecom.hlx.live/acrobat?martech=off&milolibs=main-revert-hyph--milo--adobecom
- BACOM: https://main--bacom--adobecom.hlx.live/?martech=off&milolibs=main-revert-hyph--milo--adobecom
- CC: https://main--cc--adobecom.aem.live/creativecloud?martech=off&milolibs=main-revert-hyph--milo--adobecom
- Milo: https://main-revert-hyph--milo--adobecom.aem.page/drafts/blaishram/test-urls/page?martech=off
- Express: https://main--express-milo--adobecom.aem.live/express/?martech=off&milolibs=main-revert-hyph--milo--adobecom
- News: https://main--news--adobecom.aem.live/?martech=off&milolibs=main-revert-hyph--milo--adobecom
- Homepage: …
> Revert "[MWPW-173717] Hyphenate large headings on mobile"

- libs/blocks/global-navigation/dark-nav.css
Added dark mode fixes for Promo .
Resolves: [MWPW-173984](https://jira.corp.adobe.com/browse/MWPW-173984)
**Test URLs:**
- After: https://mwpw-173984--milo--adobecom.aem.page/?martech=off
QA:
https://adobecom.github.io/nav-consumer/navigation.html?authoringpath=/federal/home&theme=dark&newNav=true&navbranch=mwpw-173984
- Acrobat: https://main--dc--adobecom.hlx.live/acrobat?martech=off&milolibs=mwpw-173984--milo--adobecom
- BACOM: https://main--bacom--adobecom.hlx.live/?martech=off&milolibs=mwpw-173984--milo--adobecom
- CC: https://main--cc--adobecom.aem.live/creativecloud?martech=off&milolibs=mwpw-173984--milo--adobecom
- Milo: …
> [MWPW-173984] - Added fix for dark theme for promo

- libs/mep/ace1052/aside/aside.css
- libs/mep/ace1052/notification/notification.css
- libs/mep/ace1052/tabs/tabs.css
Original PR was somehow lost, re-adding those changes to the feature branch - https://github.com/adobecom/milo/pull/4296
> Re-merge: limit tabs upates; lower aside margins

- libs/mep/ace1052/carousel/carousel.css
- libs/mep/ace1052/carousel/carousel.js
- libs/mep/ace1052/editorial-card/editorial-card.css
- libs/mep/ace1052/editorial-card/editorial-card.js
Expanding the height of the carousel according to the grid of the screen
Resolves: [[MWPW-171542]](https://jira.corp.adobe.com/browse/MWPW-171542)
After: https://mweb-new--milo--suhjainadobe.aem.page/drafts/suhjain/m2-folder/carousel/document1?mep=/drafts/suhjain/ace1052.json&martech=off&georouting=off
> editorial css and carousel width changes

- .github/workflows/dynamic-pr-template.yml
* Fixing replace check for Gnav test url
**Test URLs:**
- After: https://gnav-template--milo--adobecom.aem.page/?martech=off
> Fixing replace check for Gnav test url

- libs/blocks/global-navigation/global-navigation.js
- libs/navigation/navigation.js
* Providing a callback for clients to close the GNav, as it's required for those implementing their own UNav
Resolves: [MWPW-174014](https://jira.corp.adobe.com/browse/MWPW-174014)
**Test URLs:**
- After: https://sgnav-close--milo--adobecom.aem.page/?martech=off
QA: https://adobecom.github.io/nav-consumer/navigation.html?env=stage&navbranch=sgnav-close
- Acrobat: https://main--dc--adobecom.hlx.live/acrobat?martech=off&milolibs=sgnav-close--milo--adobecom
- BACOM: https://main--bacom--adobecom.hlx.live/?martech=off&milolibs=sgnav-close--milo--adobecom
- CC: https://main--cc--adobecom.aem.live/creativecloud?martech=off&milolibs=sgna …
> Exposing close gnav function for clients

- libs/blocks/locui-create/input-urls/view.js
Dev PR - https://github.com/adobecom/milo/pull/4189
Resolves: [MWPW-173721](https://jira.corp.adobe.com/browse/MWPW-173721)
**Test URLs:**
- Before: https://milostudio-stage--milo--adobecom.aem.page/tools/locui-create?ref=main&repo=milo&owner=adobecom&host=milo.adobe.com&project=Milo&env=local&workflow=normal
- After: https://mwpw-173721-stage--milo--nkthakur48.aem.page/tools/locui-create?ref=main&repo=milo&owner=adobecom&host=milo.adobe.com&project=Milo&env=local&workflow=normal
> [Locv3][Stage] MWPW-173721 A11Y Translation/Rollout selection pill

- libs/mep/ace1052/carousel/carousel.css
- libs/mep/ace1052/tabs/tabs.css
* Add your
* Specific
Resolves: [MWPW-174782](https://jira.corp.adobe.com/browse/MWPW-NUMBER)
After: https://mweb-errors--milo--suhjainadobe.aem.page/drafts/suhjain/m2-folder/carousel/photoshop-page?mep=/drafts/suhjain/ace1052.json&martech=off&georouting=off
> MWPW-174782 and MWPW-174694

- libs/blocks/global-navigation/utilities/keyboard/popup.js
- libs/blocks/global-navigation/utilities/keyboard/utils.js
- libs/blocks/language-selector/language-selector.css
- libs/blocks/language-selector/language-selector.js
- libs/utils/utils.js
- test/blocks/language-selector/language-selector.test.js
- test/blocks/language-selector/mocks/languages.html
* Language selector block for language based sites
Resolves: [MWPW-169805](https://jira.corp.adobe.com/browse/MWPW-169805)
**Test URLs:**
- Before: https://main--milo--adobecom.aem.page/drafts/ruchika/language/document1?martech=off
- After: https://mwpw-169805--milo--adobecom.aem.page/drafts/ruchika/language/document1?martech=off
News
- Before: https://main--news--adobecom.hlx.page/drafts/ruchika/lang-selector?milolibs=stage&martech=off
- After: https://main--news--adobecom.hlx.page/drafts/ruchika/lang-selector?milolibs=MWPW-169805&martech=off
Note: 
1. Expected behavior can be properly tested on newsroom link provided above as that has proper language object created in config.
2. Changes in libs/blocks/global-navigation/utilities/keyboard/popup.js and …
> [MWPW-169805]Language selector block for language based sites

- libs/mep/ace1052/brick/brick.js
Update Brick block to body-s
* Add your
* Specific
Resolves: [[MWPW-174950]](https://jira.corp.adobe.com/browse/MWPW-NUMBER)
**Test URLs:**
After: https://mweb-brick--milo--suhjainadobe.aem.page/drafts/suhjain/m2-folder/carousel/photoshop-page?mep=/drafts/suhjain/ace1052.json&martech=off&georouting=off
> [MWPW-174950] Update Brick block to body-s

- test/blocks/fire-drill-ryan/README.md
As part of offering a robust team of capable engineers, we are conducting "fire-drills" to emergency revert something from production.
Team members that have not recently gone through this exercise in a real case, will get a simplified case where they'll have to go through the steps to remove code from production outside of a normal automated batched-release.
Resolves: No MWPW
**Test URLs:**
- After: https://ryan-fire-drill--milo--adobecom.aem.page/?martech=off
> [Fire-Drill] This will have to get reverted by ryan

- libs/blocks/marketo/marketo-multi.js
- test/blocks/marketo/marketo-multi.test.js
* Turn "back" and "step" into placeholders
* Change from "Step 1 of 2" to "Step 1 / 2"
Resolves: [MWPW-168314](https://jira.corp.adobe.com/browse/MWPW-168314)
**Test URLs:**
- Before: https://main--milo--adobecom.aem.page/de/drafts/methomas/multi-3?martech=off
- After: https://multistep-loc--milo--meganthecoder.aem.page/de/drafts/methomas/multi-3?martech=off
> MWPW-168314 Localize Marketo Multi-Step

- libs/blocks/global-navigation/global-navigation.js
* Currently if the first element of localnav is a button instead of an anchor tag the localnav title is showing empty
* With this fix, Lnav title now checks for immediate anchor tag or button element
* Also adding support for localnav first item being a non clickable item which is neither anchor tag nor button.
Resolves: https://jira.corp.adobe.com/browse/MWPW-174795
https://jira.corp.adobe.com/browse/MWPW-166257
**Test URLs:**
- After: https://lnav-title--milo--adobecom.aem.page/?martech=off
QA: 
- Before: https://main--bacom--adobecom.hlx.live/resources/reports/personalization-at-scale.html
- After: https://main--bacom--adobecom.hlx.live/resources/reports/personalization-at-scale.html?milolibs=lnav-title
-
- Before: …
> Lnav title should be immediate child either anchor link or button

- .github/workflows/helpers.js
updated the zero_impact_prefix
**Test URLs:**
- After: https://zero-impact-prefix--milo--skholkhojaev.aem.page/?martech=off
> updated ZERO_IMPACT_PREFIX in helpers.js

- .github/workflows/helpers.js
- .github/workflows/merge-to-stage.js
- .github/workflows/pr-manual-merge.js
Correct counting of zero impact PRs
**Test URLs:**
- After: https://correctly-count-prs-in-stage--milo--mokimo.aem.live/?martech=off
> Correct counting of zero impact PRs

- libs/blocks/global-navigation/global-navigation.css
Added fix for close icon positon for rtl
Before:
After:
Resolves: [MWPW-175210](https://jira.corp.adobe.com/browse/MWPW-175210)
**Test URLs:**
- After: https://mwpw-175210-bug--milo--deva309.aem.page/?martech=off
- Acrobat: https://main--dc--adobecom.hlx.live/acrobat?martech=off&milolibs=mwpw-175210-bug--milo--adobecom
- BACOM: https://main--bacom--adobecom.hlx.live/?martech=off&milolibs=mwpw-175210-bug--milo--adobecom
- CC: https://main--cc--adobecom.aem.live/creativecloud?martech=off&milolibs=mwpw-175210-bug--milo--adobecom
- Milo: https://mwpw-175210-bug--milo--adobecom.aem.page/drafts/blaishram/test-urls/page?martech=off
- …
> [MWPW-175210] - Added fix for close icon positon for rtl

- libs/mep/ace1052/notification/notification.css
- libs/mep/ace1052/section-metadata/section-metadata.css
Resolves: [MWPW-174690](https://jira.corp.adobe.com/browse/MWPW-174690)
**Test URLs:**
- After: https://notif--milo--drashti1712.aem.live/?martech=off
> [MWPW-174690] Do not see the block functionality working when the sticky cta is present

- libs/mep/ace1052/carousel/carousel.css
- libs/mep/ace1052/carousel/carousel.js
* Add your
* Specific
Resolves: [[MWPW-175310]](https://jira.corp.adobe.com/browse/MWPW-NUMBER)
**Test URLs:**
- Before: https://main--milo--adobecom.aem.page/drafts/suhjain/m2-folder/carousel/photoshop-page?mep=/drafts/suhjain/ace1052.json&martech=off&georouting=off
- After: https://swipping-carosue-bug--milo--adobecom.aem.page/drafts/suhjain/m2-folder/carousel/photoshop-page?mep=/drafts/suhjain/ace1052.json&martech=off&georouting=off
> Ps Mweb Journey | Carousel swiping

- libs/blocks/table/table.js
Resolves: [MWPW-174860](https://jira.corp.adobe.com/browse/MWPW-174860)
**Test URLs:**
- Before: https://main--milo--adobecom.aem.page/drafts/dusan/table-in-tab-expand?martech=off
- After: https://table-expanding-mobile-fix--milo--adobecom.aem.page/drafts/dusan/table-in-tab-expand?martech=off
**Table kitchen sink Test URLs:**
- After: https://table-expanding-mobile-fix--milo--adobecom.aem.page/docs/library/kitchen-sink/table?martech=off
> [MWPW-174860] - table mobile expanding fix, highlight column not in mobile filter fix 

- libs/blocks/global-navigation/utilities/utilities.js
MWPW-175149: Expand/collapse state of appswitcher is incorrect
Resolves: [MWPW-175149](https://jira.corp.adobe.com/browse/MWPW-175149)
**Test URLs:**
- After: https://mwpw175149--milo--adobecom.aem.page/?martech=off
- Acrobat: https://main--dc--adobecom.hlx.live/acrobat?martech=off&milolibs=mwpw175149--milo--adobecom
- BACOM: https://main--bacom--adobecom.hlx.live/?martech=off&milolibs=mwpw175149--milo--adobecom
- CC: https://main--cc--adobecom.aem.live/creativecloud?martech=off&milolibs=mwpw175149--milo--adobecom
- Milo: https://mwpw175149--milo--adobecom.aem.page/drafts/blaishram/test-urls/page?martech=off
- Express: …
> Fix for Expand/collapse state of appswitcher

- .github/workflows/track-express-publishes-for-da.yaml
Run the auto import to DA once a day for express. Practically a copy of https://github.com/adobecom/milo/blob/stage/.github/workflows/track-bacom-publishes-for-da.yaml with different secrets
Resolves: [MWPW-175519](https://jira.corp.adobe.com/browse/MWPW-175519)
**Test URLs:**
- After: https://enable-auto-importer-for-express--milo--mokimo.aem.live/
> Enable auto importer from express-milo to da-express-milo

- nala/blocks/mnemonic/mnemonic.page.js
- nala/blocks/mnemonic/mnemonic.spec.js
- nala/blocks/mnemonic/mnemonic.test.js
This PR include automation scripts for different variants of the Mnemonic List
Test pages for Mnemonic List variants [MnemonicList](https://adobe.sharepoint.com/sites/adobecom/Shared%20Documents/Forms/AllItems.aspx?id=%2Fsites%2Fadobecom%2FShared%20Documents%2Fmilo%2Fdrafts%2Fnala%2Fblocks%2Fmnemonic&viewid=d776cf70%2D9b7e%2D4ab7%2Db9da%2D9e0f8e03a7d2&newTargetListUrl=%2Fsites%2Fadobecom%2FShared%20Documents&viewpath=%2Fsites%2Fadobecom%2FShared%20Documents%2FForms%2FAllItems%2Easpx)
Tests are successfully running as part of the Nala CI/CD pipeline
Test scripts validate Mnemonic List across Chrome, Firefox, and Webkit browsers
Resolves: [MWPW-173103](https://jira.corp.adobe.com/browse/MWPW-173103)
**Test URLs:**
- After: …
> [MWPW-173103][NALA] Automation test script for Mnemonic List

- libs/blocks/merch/merch.js
Prevents a duplicate three in one
Resolves: [MWPW-175712](https://jira.corp.adobe.com/browse/MWPW-175712)
**Test URLs:**
- After: https://mwpw-175712--milo--adobecom.aem.page/?martech=off
> MWPW-175712: Prevents duplicate three-in-one

- libs/blocks/table/table.js
- test/blocks/table/table.test.js
Fixes flaky/failing table tests introduced in https://github.com/adobecom/milo/pull/4374
**Test URLs:**
- After: https://table-flaky-tests-fix--milo--adobecom.aem.page/?martech=off
> Table flaky/failing tests fix

- libs/blocks/table/table.js
Resolves: [MWPW-175093](https://jira.corp.adobe.com/browse/MWPW-175093)
**Test URLs:**
- After: https://table-sticky-header-extension-fix--milo--adobecom.aem.page/docs/library/kitchen-sink/table?martech=off
- Before: https://main--cc--adobecom.aem.page/products/photoshop-lightroom/plans
- After: https://main--cc--adobecom.aem.page/products/photoshop-lightroom/plans?milolibs=table-sticky-header-extension-fix
> [MWPW-175093] - Table sticky header font size upscale with extension fix

- libs/blocks/table/table.css
- libs/blocks/table/table.js
Resolves: [MWPW-174959](https://jira.corp.adobe.com/browse/MWPW-174959)
**Test URLs:**
- Before: https://main--milo--adobecom.aem.page/drafts/dusan/table-in-tab-expand?martech=off
- After: https://table-border-fix--milo--adobecom.aem.page/drafts/dusan/table-in-tab-expand?martech=off
**Table Kitchen sink Test URLs:**
- After: https://table-border-fix--milo--adobecom.aem.page/docs/library/kitchen-sink/table?martech=off
> [MWPW-174959] - Table border fix

- libs/blocks/pdf-viewer/pdf-viewer.js
* Sets element min height to ensure scroll to functionality works as expected on slower load speeds
Resolves: [MWPW-174353](https://jira.corp.adobe.com/browse/MWPW-174353
**Test URLs:**
- Before: https://main--milo--jasonhowellslavin.aem.page/drafts/slavin/bacom-pages/?martech=off
- After: https://pdf-scroll-to-issue--milo--jasonhowellslavin.aem.page/drafts/slavin/bacom-pages/?martech=off
> MWPW-174353: Fix scroll to behavior for pdf viewer

- .github/workflows/import/index.js
Sync with the nexter importer 
- https://github.com/adobe/da-nx/commit/8ed4585617806b623dbf48baf8c039157b27ae07
- https://github.com/adobe/da-nx/pull/15
**Test URLs:**
- After: https://pull-in-importer-changes--milo--mokimo.aem.live/?martech=off
> Sync milo auto importer with the nexter importer

- libs/blocks/merch/merch.js
- libs/blocks/merch/three-in-one.js
- libs/blocks/modal/modal.js
- nala/blocks/merch/three-in-one.test.js
- test/blocks/merch/merch.test.js
- test/blocks/merch/three-in-one.test.js
This PR fixes modal functionality for the following scenarios:
1. Browser navigation with modals: When a user opens a modal, navigates to another page, then clicks the browser's back button (or directly visits a URL with a modal hash), the modal will now properly reopen.
2. Filter preservation on catalog page (and any page that uses the merch-card-collection with the merch-sidebar):
When users have applied filters on the catalog page (like https://main--cc--adobecom.aem.live/products/catalog#category=graphic-design&types=desktop), opened the modal and clicked "Back" in the browser- the hash should change to the previous one (it does), and the modal should get closed (this was not working). Also added checking to make sure the modal gets (re)opened only once, even if there are multiple …
> MWPW-176125: Merch modal follow-up

- libs/features/seotech/seotech.js
- test/features/seotech/seotech.test.js
- test/utils/utils.test.js
* Make error messages more descriptive
* Fix invalid tag key-value pair
* Add error severity to LANA message
* Fix broken tests
Resolves: 
[MWPW-176169](https://jira.corp.adobe.com/browse/MWPW-176169)
[MWPW-176077](https://jira.corp.adobe.com/browse/MWPW-176077)
[MWPW-176072](https://jira.corp.adobe.com/browse/MWPW-176072)
**Test URLs:**
- After: https://MWPW-176072--milo--adobecom.aem.page/?martech=off
> MWPW-176072, MWPW-176077, MWPW-176169 seotech fixes

- libs/blocks/brick/brick.js
* Updates brick block to render if the only content is an image or video (foreground content empty).
* Align with Consonant Figma designs.
Resolves: [MWPW-176498](https://jira.corp.adobe.com/browse/MWPW-176498)
**Test URLs:**
- Before: https://main--milo--adobecom.aem.page/drafts/rclayton/poc/bricks-media-only?martech=off
- After: https://brick-media-only--milo--adobecom.aem.page/drafts/rclayton/poc/bricks-media-only?martech=off
- Before: https://main--milo--adobecom.aem.page/drafts/rclayton/bricks-update?martech=off
- After: https://brick-media-only--milo--adobecom.aem.page/drafts/rclayton/bricks-update?martech=off
**Test URLs CC:**
- Before: https://main--cc--adobecom.aem.page/creativecloud/?martech=off
- After: https://main--cc--adobecom.aem.page/creativecloud/?milolibs=brick-media-only …
> MPWP-176498 - Media only brick

- libs/blocks/modal/modal.css
Reverts adobecom/milo#4594 due to https://github.com/adobecom/milo/pull/4608#issuecomment-3131038445
> Revert "[MWPW-174911] - Modal phone close issue"

- libs/blocks/accordion/accordion.css
- libs/blocks/accordion/accordion.js
Resolves: [MWPW-175505](https://jira.corp.adobe.com/browse/MWPW-175505)
**Example with Image Test URLs:**
- Before: https://main--milo--adobecom.hlx.page/docs/library/kitchen-sink/accordion
- After: https://accordion-image-tablet-video-fix--milo--adobecom.aem.page/docs/library/kitchen-sink/accordion
**Example with Video Test URLs:**
- Before: https://main--cc--adobecom.aem.live/au/cc-shared/fragments/tests/2025/q2/apac0419/riverflow-premiere
- After: https://main--cc--adobecom.aem.live/au/cc-shared/fragments/tests/2025/q2/apac0419/riverflow-premiere?milolibs=accordion-image-tablet-video-fix
**Video pause/play Test URLs:**
- Before: https://main--milo--adobecom.aem.page/drafts/dusan/accordion-video-a11y
- After: https://accordion-image-tablet-video-fix--milo--adobecom.aem.page/drafts/dusan/ …
> [MWPW-175505] - Accordion image/video tablet/mobile fix

- libs/blocks/hero-marquee/hero-marquee.css
- libs/mep/emea1443/hero-marquee/hero-marquee.css
Resolves: [MWPW-174201](https://jira.corp.adobe.com/browse/MWPW-174201)
**QA Note**
Test results and noted performance improvements can be found in the comments of the ticket.
**no-min-height-desktop Test URLs:**
- Before: https://main--milo--adobecom.aem.page/drafts/dusan/hero-marquee-height1
- After: https://hero-marquee-no-min-h-d--milo--adobecom.aem.page/drafts/dusan/hero-marquee-height1
**no-min-heightTest URLs:**
- Before: https://main--milo--adobecom.aem.page/drafts/dusan/hero-marquee-height
- After: https://hero-marquee-no-min-h-d--milo--adobecom.aem.page/drafts/dusan/hero-marquee-height
> [MWPW-174201] - Hero marquee no min height desktop

- libs/blocks/modal/modal.css
Resolves: [MWPW-174911](https://jira.corp.adobe.com/browse/MWPW-174911)
**Video Test URLs:**
Before: https://main--milo--adobecom.aem.page/drafts/ratko/mwpw-170384-modal-overflow/modal-overflow
After: https://modal-overflow-phone--milo--adobecom.aem.page/drafts/ratko/mwpw-170384-modal-overflow/modal-overflow
**Ticket CC Test URLs:**
Before: https://main--dc--adobecom.aem.live/acrobat/pricing/students
After: https://main--dc--adobecom.aem.live/acrobat/pricing/students?milolibs=modal-overflow-phone
**CC Commerce Modal Test URLs:**
Before: https://main--cc--adobecom.aem.live/ae_ar/creativecloud
After: https://main--cc--adobecom.aem.live/ae_ar/creativecloud?milolibs=modal-overflow-phone
**CC - Last CTA - Upgrade flow Modal Test URLs:**
Before: …
> [MWPW-174911] - phone modal overflow fix

- libs/blocks/merch-card-collection-autoblock/merch-card-collection-autoblock.js
- libs/blocks/merch/autoblock.js
- libs/blocks/modal/modal.css
- libs/blocks/modal/modal.js
- libs/blocks/notification/notification.css
- libs/blocks/notification/notification.js
- libs/blocks/section-metadata/section-metadata.css
- libs/blocks/share/share.css
- libs/blocks/share/share.js
- libs/scripts/accessibility.js
- nala/blocks/merch/three-in-one.spec.js
- nala/blocks/merch/three-in-one.test.js
- test/blocks/merch-card-collection-autoblock/merch-card-collection-autoblock.test.js
- test/blocks/merch-card-collection-autoblock/mocks/fragment.json
- test/blocks/merch/autoblock.test.js
- test/blocks/modals/modals.test.js
* Add your
* Specific
**Test URLs:**
- After: https://<branch>--milo--adobecom.aem.page/?martech=off
> Sync stage to geo

- .github/workflows/track-bacom-publishes-for-da.yaml
- .github/workflows/track-dc-publishes-for-da.yaml
Start the rolling importer for DC
Resolves: [MWPW-174328](https://jira.corp.adobe.com/browse/MWPW-174328)
Ran this locally, to confirm all the env variables are set and we import the articles, here's a few examples:
PS: Navs & a bit of content might be missing as DC has not imported the whole project yet. Thats expected.
https://main--da-dc--adobecom.aem.live/acrobat/resources/how-to-delete-blank-page-in-word
https://main--da-dc--adobecom.aem.live/acrobat/resources/how-to-summarize-an-article
https://main--da-dc--adobecom.aem.live/acrobat/resources/how-to-write-the-date
**Test URLs:**
- After: https://dc-rolling-importer--milo--mokimo.aem.page/?martech=off
> Enable the DC/DA rolling importer

- libs/utils/sidekick.js
* Add your
* Specific
**Test URLs:**
- After: https://<branch>--milo--adobecom.aem.page/?martech=off
> fix: adding preflight mfe

- libs/blocks/faas/faas.js
Resolves: [MWPW-176965](https://jira.corp.adobe.com/browse/MWPW-176965)
**PSI URLs:**
- After: https://faas-a11y-voiceover--milo--adobecom.aem.page/?martech=off
**Form Test URLs:**
- Before: https://main--cc--adobecom.aem.live/creativecloud/business/teams/request-information?georouting=off
- After: https://main--cc--adobecom.aem.live/creativecloud/business/teams/request-information?georouting=off&milolibs=faas-a11y-voiceover
> [MWPW-176965] - faas form error announcement order

- libs/scripts/delayed.js
* Picking valid privacyEnv from allowed list
Resolves: [VULN-31785](https://jira.corp.adobe.com/browse/VULN-31785)
**Test URLs:**
- After: https://privacy-env--milo--adobecom.aem.page/?martech=off
QA: https://main--cc--adobecom.hlx.live/products/photoshop/ai?privacyEnv=jp3.eu/adobe/token.js&milolibs=privacy-env
> Picking valid privacyEnv from allowed list

- libs/blocks/global-navigation/global-navigation.css
when more than 2 secondary cta is present alignment issue is seen in mobile
Resolves: [MWPW-175394](https://jira.corp.adobe.com/browse/MWPW-175394)
**Test URLs:**
- After: https://mwpw-175394--milo--patel-prince.aem.page/?martech=off
**QA URL:**
- https://adobecom.github.io/nav-consumer/navigation.html?env=stage&theme=light&authoringpath=/federal/dev/tat28144&navbranch=MWPW-175394
- Acrobat: https://main--dc--adobecom.hlx.live/acrobat?martech=off&milolibs=MWPW-175394--milo--adobecom
- BACOM: https://main--bacom--adobecom.hlx.live/?martech=off&milolibs=MWPW-175394--milo--adobecom
- CC: …
> when more than 2 secondary cta is present alignment issue is seen in mobile

- libs/blocks/global-footer/global-footer.css
* Removing iphone landscape font increase default behavior
Resolves: [MWPW-177017](https://jira.corp.adobe.com/browse/MWPW-177017)
**Test URLs:**
- After: https://footer-text--milo--adobecom.aem.page/?martech=off
- Acrobat: https://main--dc--adobecom.hlx.live/acrobat?martech=off&milolibs=footer-text--milo--adobecom
- BACOM: https://main--bacom--adobecom.hlx.live/?martech=off&milolibs=footer-text--milo--adobecom
- CC: https://main--cc--adobecom.aem.live/creativecloud?martech=off&milolibs=footer-text--milo--adobecom
- Milo: https://footer-text--milo--adobecom.aem.page/drafts/blaishram/test-urls/page?martech=off
- Express: …
> Removing iphone landscape font increase default behavior

- libs/blocks/merch/merch.js
Resolves: [MWPW-180119](https://jira.corp.adobe.com/browse/MWPW-180119)
**Test URLs:**
- Before: https://main--milo--adobecom.aem.live/drafts/nala/features/commerce/plans?martech=off
- After: https://MWPW-180119--milo--npeltier.aem.live/drafts/nala/features/commerce/plans?martech=off
> MWPW-180119 shielding country detection in merch.js

- libs/blocks/faas-config/faas-config.js
Initial context value was unhandled.
Resolves: [MWPW-178158](https://jira.corp.adobe.com/browse/MWPW-178158)
**Test URLs:**
- After: https://mwpw-178158--milosh--sharath-kannan.aem.page/?martech=off
> Fix(mwpw-178158): Bug fix for faas tool.

- libs/blocks/brand-concierge/chat-ui-config.js
* Update hover background color of prompt suggestion buttons in BC chat
Resolves: [MWPW-180646](https://jira.corp.adobe.com/browse/MWPW-180646)
**Test URLs:**
- After: https://bc-prompt-hover--milo--adobecom.aem.page/drafts/methomas/brand-concierge?martech=off
> MWPW-180646 Brand Concierge - Update prompt button hover

- libs/blocks/global-navigation/global-navigation.js
- test/blocks/global-navigation/global-navigation.test.js
- test/blocks/global-navigation/test-utilities.js
Duplicate analytics events are being generated. Currently, the AEP event is being sent both from the GNAV surface and centrally. Since the event is already handled centrally, the GNAV surface should no longer emit it to avoid duplication.
Resolves: [MWPW-181107](https://jira.corp.adobe.com/browse/MWPW-181107)
**Test URLs:**
- After: https://mwpw-181107--milo--deva309.aem.page/?martech=off
QA:
https://main--cc--adobecom.aem.page/products/photoshop?milolibs=mwpw-181107--milo--deva309
- Acrobat: https://main--dc--adobecom.hlx.live/acrobat?martech=off&milolibs=mwpw-181107--milo--adobecom
- BACOM: …
> [MWPW-181107] - Remove UNAV analytics call from GNAV

- libs/blocks/brand-concierge/brand-concierge.css
* Add a bottom border to the header in the Brand Concierge modal
Resolves: [MWPW-180356](https://jira.corp.adobe.com/browse/MWPW-180356)
**Test URLs:**
- After: https://bc-border--milo--adobecom.aem.page/drafts/methomas/brand-concierge?martech=off
> MWPW-180356 Brand Concierge - Modal Header Border

- libs/martech/alloy-links.js
* fixed payload for alloy links event
Resolves: [MWPW-174157](https://jira.corp.adobe.com/browse/MWPW-174157)
**Test URLs:**
- After: https://alloy-fix--milo--adobecom.aem.page/?martech=off
> Added fix to Alloy payload

- nala/features/mas/express/express.spec.js
Nala: Fix for test failure at https://github.com/adobecom/milo/actions/runs/18307995372/job/52129713874?pr=4953
> Nala:Fix for MAS-Full-Pricing-Express-Pro

- .github/workflows/import/index.js
* Skipping redirects for express da content sync
**Test URLs:**
- Before: https://stage--milo--adobecom.aem.live/?martech=off
- After: https://da-express-import-skip-redirects--milo--adobecom.aem.live/?martech=off
> [DA Express Migration] Exclude Redirects from Sync
