libs/blocks/global-navigation/base.css, libs/blocks/global-navigation/global-navigation.css, libs/blocks/global-navigation/global-navigation.js
On a slow network, the global navigation (gnav) is visible before the complete styling is applied, as the CSS to make it visible is in global-navigation.css. 
To resolve this, the CSS is moved to base.css.
Resolves: [MWPW-154887](https://jira.corp.adobe.com/browse/MWPW-154887)
**Test URLs:**
- Before: https://main--milo--adobecom.hlx.page/drafts/snehal/unav11?martech=off
- After: https://mwpw-154887--milo--bandana147.hlx.page/drafts/snehal/unav11?martech=off
=> Mwpw 154887: Making gnav visible in base.css 

libs/blocks/marquee/marquee.css
Added an opt in variant `support-rtl` to the [marquee] block to better support localization.
Text alignment in marquee block used on [this page ](https://main--cc--adobecom.hlx.page/mena_ar/products/illustrator/generative-recolor) are not working correctly with RTL geos rollout. 
Variation: marquee (split, dark, one-third, xl-button, static-links) 
Image and color is used as background.
expected result
actual result
URL: https://main--cc--adobecom.hlx.page/mena_ar/products/illustrator/generative-recolor
Resolves: [MWPW-147867](https://jira.corp.adobe.com/browse/MWPW-147867)
**Test URLs:**
- Before: https://main--milo--adobecom.hlx.page/drafts/rparrish/marquee/marquee-rtl?martech=off
- After: https://rparrish-marquee-rtl--milo--adobecom.hlx.page/drafts/rparrish/marquee/marquee-rtl?martech=o …
=> MWPW-147867 - [marquee] support RTL for loc

libs/utils/utils.js
* Allows mep param to be empty and still proceed with MEP on page that does not otherwise have it
Resolves: [155568](https://jira.corp.adobe.com/browse/MWPW-155568)
QA instructions:
1. Go to a production URL that does not use MEP at all (Target off, no personalization or promos)
2. Add the mep parameter
3. Override the utils.js file with this one
4. Reload
**Test URLs:**
- https://milo.adobe.com/?mep
Psi-check: https://mepbuttonwithemptyparam--milo--adobecom.hlx.page/?martech=off
=> MWPW-155568 [MILO][MEP] If MEP is completely off, mep param should still show button

libs/blocks/marquee/marquee.css
Reverts adobecom/milo#2640 due to findings from @NadiiaSokolova which causes rtl to break in some currently working cases
Test URLs:
Before: https://main--milo--adobecom.hlx.page/drafts/rparrish/marquee/marquee-rtl?martech=off
After: https://revert-2640-rparrish-marquee-rtl--milo--adobecom.hlx.page/drafts/rparrish/marquee/marquee-rtl?martech=off
Doc URLs:
Before: https://main--milo--adobecom.hlx.page/docs/library/blocks/marquee?martech=off
After: https://revert-2640-rparrish-marquee-rtl--milo--adobecom.hlx.page/docs/library/blocks/marquee?martech=off
=> Revert "MWPW-147867 - [marquee] support RTL for loc"

libs/features/personalization/entitlements.js, libs/features/personalization/stage-entitlements.js
* Add 2 new entiltements to MEP.  One has no stage ID
Resolves: [MWPW-146030](https://jira.corp.adobe.com/browse/MWPW-146030) and [MWPW-143704](https://jira.corp.adobe.com/browse/MWPW-143704)
**Test URLs:**
- After: https://mepfrescoccpaid--milo--adobecom.hlx.page/?martech=off
=> MWPW-146030 and MWPW-143704 Add fresco-any and cc-paid-no-stock

libs/navigation/navigation.js
* Some apps are facing issues with dynamically loaded external scripts while bundling. Therefore, we are adding an alternative way of calling the function from the window object.
**Test URLs:**
- After: https://feds--milo--adobecom.hlx.page/?martech=off
QA: https://adobecom.github.io/nav-consumer/navigation.html?env=stage&navbranch=feds
=> Attaching loadblock to window to provide alternative way of loading the script

libs/blocks/table/table.css
This adapts the table's width when it is nested inside a section that has a set grid width via section metadata.
Resolves: [MWPW-153267](https://jira.corp.adobe.com/browse/MWPW-153267)
| <img width="375" alt="Screenshot 2024-07-26 at 15 24 08" src="https://github.com/user-attachments/assets/5adc8235-daa8-4a6d-bb41-d9cfacfe2cc8"> | <img width="769" alt="Screenshot 2024-07-26 at 15 25 01" src="https://github.com/user-attachments/assets/05faa260-ba01-4042-9f6a-8837ef277b80"> |
**Test URLs:**
- Before: https://table-review--milo--overmyheadandbody.hlx.page/drafts/ramuntea/table-tiger-team-kyung-overhaul?martech=off
- After: https://table-in-grid--milo--overmyheadandbody.hlx.page/drafts/ramuntea/table-tiger-team-kyung-overhaul?martech=off
=> [MWPW-153267] Expand table to parent grid size

libs/blocks/notification/notification.css, libs/blocks/notification/notification.js, test/blocks/notification/mocks/body.html
* When using a Pill Notification without a heading, "undefined" would be injected into the markup.
* Furthermore, when using a hex color background with the "flexible" and "no-close" variants, "null" would be injected into the markup.
* This PR fixes the above issues.
Resolves: [MWPW-155316](https://jira.corp.adobe.com/browse/MWPW-155316)
**Test URLs:**
- Before: https://main--milo--adobecom.hlx.page/drafts/ebartholomew/pill-testing?martech=off
- After: https://ebartholomew-pill-bugs--milo--adobecom.hlx.page/drafts/ebartholomew/pill-testing?martech=off
=> MWPW-155316 - Fixing Pill Notification edge cases

libs/blocks/adobetv/adobetv.js
Pass on the dataset like the [video block](https://github.com/adobecom/milo/blob/stage/libs/blocks/video/video.js#L18) to correctly generate posters for videos.
Resolves: [MWPW-155515](https://jira.corp.adobe.com/browse/MWPW-155515)
Ensure the poster attribute is added to the video in the html
**Before**
**After**
Adding and authoring a poster for a video, will lead to a faster LCP in cases where the Geo routing would otherwise be picked.
**Test URLs:**
- Before: https://main--milo--adobecom.hlx.live?martech=off
- After: https://mwpw-155515--milo--adobecom.hlx.live?martech=off
- Before: https://main--bacom--adobecom.hlx.page/drafts/osahin/magento-commerce
- After: https://main--bacom--adobecom.hlx.page/drafts/osahin/magento-commerce?milolibs=mwpw-155515
=> Correctly pass on the dataset

libs/blocks/merch-card-collection/merch-card-collection.js, test/blocks/merch-card-collection/merch-card-collection.test.js, test/blocks/merch-card-collection/mocks/merch-card-collection.html
Sorry for ugly cards in Milo, for shiny cards please check catalog collection.
Use custom index for Preview in Merch Card Collections.
If no preview index is authored, default to Prod Index.
Resolves: https://jira.corp.adobe.com/browse/MWPW-154124
alternate between hlx.page and hlx.live and observe different Photoshop Card content descriptions ('PREVIEW CARD')
In Network tab you can see `query-index-cards.json?sheet=catalog` loading for .live and `query-index-cards-preview.json?sheet=catalog` for .hlx.page.
hlx.live: https://main--cc--adobecom.hlx.live/products/catalog?milolibs=MWPW-154124-pi 
hlx.page: https://main--cc--adobecom.hlx.page/products/catalog?milolibs=MWPW-154124-pi
hlx.live (uses prod index): https://main--cc--adobecom.hlx.live/drafts/mariia/catalog/catalog?milolibs=MWPW-1541 …
=> MWPW-154124: use preview index

libs/blocks/locui/actions/index.js
Due to the video fragments having URL params the de-dupe function was seeing them as different because it was checking the URL href property instead of the pathname. Updating the duplicate function to look at only the pathname to avoid this.
Resolves: [MWPW-155676](https://jira.corp.adobe.com/browse/MWPW-155676)
**Test URLs:**
https://main--cc--adobecom.hlx.page/tools/loc?milolibs=sean-loc&ref=main&repo=cc&owner=adobecom&host=www.adobe.com&project=Creative+Cloud&referrer=https%3A%2F%2Fadobe.sharepoint.com%2F%3Ax%3A%2Fr%2Fsites%2Fadobecom%2F_layouts%2F15%2FDoc.aspx%3Fsourcedoc%3D%257B170d251e-8672-4185-b0b7-440ed60908f9%257D%26action%3Deditnew
=> MWPW-155676 - [LocUI] Find duplicate fragments by pathname

libs/blocks/table/table.css, libs/blocks/table/table.js
On mobile devices, if the table is the first block on the page, it could happen that its decoration took a long time, due to the fact that it depended on another Milo event. The logic has been adapted to prioritize the load of tables that are visible in the initial viewport. Another style quirk has been addressed, where certain table rows were expanding beyond the viewport on mobile devices.
| <img width="413" alt="Table overflow before" src="https://github.com/user-attachments/assets/082d0f87-2b09-4bf0-9298-001d9539090b"> | <img width="413" alt="Table overflow after" src="https://github.com/user-attachments/assets/87d8b0e1-3ed0-4126-8666-f9fcbd05385d"> |
| <img width="413" …
=> [MWPW-153894] Addressing overflowing table content on mobile

libs/blocks/marquee/marquee.css
FYI - I am reposting this PR. The previous one was reverted due to some issues found on stage. I believe this happened due to a selector position I moved for linting purposes that had some default layouts shift. 
Only new selectors are added in this pass, no linting changes, so no regression. 
---
Added an opt in variant `support-rtl` to the [marquee] block to better support localization.
Text alignment in marquee block used on [this page ](https://main--cc--adobecom.hlx.page/mena_ar/products/illustrator/generative-recolor)are not working correctly with RTL geos rollout.
Variation: marquee (split, dark, one-third, xl-button, static-links)
Image and color is used as background.
expected result
actual result
URL: https://main--cc--adobecom.hlx.page/mena_ar/products/illustrator/generative-rec …
=> MWPW-147867 - [marquee] support RTL for loc - RePost

libs/features/personalization/personalization.js, libs/features/personalization/preview.js
* Also check the region as a value when deciding which placeholder column to use
* Add region name to MEP button so it's easy to determine
* moved "value" to the end and added "other" so they can be used as a catch-all for the remaining geos
Resolves: [MWPW-155691](https://jira.corp.adobe.com/browse/MWPW-155691)
**Test URLs:**
- Before: https://main--cc--adobecom.hlx.page/za/products/illustrator?mep=%2Fproducts%2Fillustrator.json--default---%2Fcc-shared%2Ffragments%2Ftests%2F2024%2Fq3%2Fintl0075%2Fintl0075.json--target-var1-challenger
- After: https://main--cc--adobecom.hlx.page/za/products/illustrator?milolibs=mepplaceholderregion&mep=%2Fproducts%2Fillustrator.json--default---%2Fcc-shared%2Ffragments%2Ftests%2F2024%2Fq3%2Fintl0075%2Fintl0075.json--target-var1-challenger
Psi check: …
=> MWPW-155691 [MILO][MEP] Also use region in placeholders decision 

libs/features/personalization/personalization.js, libs/utils/utils.js, test/features/personalization/personalization.test.js
This PR aims to address this scenario: when an experience column is authored to like `desktop & cc-all-apps-any` in MEP Manifest, right now, unless there's coincidently another column like `cc-all-apps-any`, the variant `desktop & cc-all-apps-any` will never get selected. Reason is that current logic in `getPersonalizationVariant()` for splitting variant name doesn't include `&`, so `hasEntitlementTag` will stay false, leading to no entitlement resolution. The code change tries to split by `&` when building out `variantInfo.allNames`. It is used to check if any entitlement tags are used. `variantInfo[name]` is used for variant mapping and thus unmodified.
This bug might again be trickier to reproduce, due to Milo by default doesn't do entitlements when logged out, and IMS only working on …
=> MWPW-155314 [MEP] Enable Entitlements + Operator

libs/blocks/modal/modal.js
* Add daa-ll property to modal curtain
Resolves: [MWPW-155781](https://jira.corp.adobe.com/browse/MWPW-155781)
QA instructions:
1. filter for "collect" in network tab (easier if you clear history after page load)
2. click on the curtain (overlay behind modal) to close the modal
3. check payload tab for first collect after you clicked and expand events.  Should see an event called "localeModal:modalClose:curtainClose"
**Test URLs:**
- Before: https://main--bacom--adobecom.hlx.page/uk/
- After: https://main--bacom--adobecom.hlx.page/uk/?milolibs=modalcurtainanalytic
Psi-check: https://modalcurtainanalytic--milo--adobecom.hlx.page/?martech=off
=> MWPW-155781 [MILO] Geo Modal Tracking on BACOM - Missing custom link

libs/blocks/merch/merch.js, test/blocks/merch/merch.test.js, test/blocks/merch/mocks/body.html
On catalog page we open TWP/D2P page in iframe/modal upon click on "Free trial" CTA. For some users the tab Education or Business need to be preselected. Personalization code will add the meta tag `<meta name="preselect-plan" content="edu">` (or with value `team`) to the page for such users and value of this tag will be read on CTA click and the query parameter `&plan=edu` (or `&plan=team`) will be added to modal page URL.
Test URL: [url](https://main--cc--adobecom.hlx.page/products/catalog?milolibs=mwpw155654--milo--bozojovicic&mep=%2Fproducts%2Fcatalog-devicetype.json--default---%2Fproducts%2Fcatalog.json--default---%2Fdrafts%2Frakaur%2Fdotcom-126722-catalog-test.json--default---%2Fdrafts%2Frakaur%2Fdotcom-126722-catalog-test-ste.json--default---%2Fdrafts%2Frakaur%2Fdotcom-126722-catalog …
=> MWPW-155654 Open TWP modal with preselected tab

libs/martech/martech.js, libs/utils/utils.js
- sendTargetResponse: Added Check for window._satellite and changed direct alloy call to _satellite call
- Added additional parameter as marketingtech to disable martech.  The martech=off also impacts launch.  So they have requested a new parameter that does the same thing in Milo as martech=off but does not impact their code.
Resolves: [ENB-6995](https://jira.corp.adobe.com/browse/ENB-6995)
Test URLs: https://www.adobe.com/products/photoshop.html?marketingtech=off
Psi-check: [https://martechteamupdates--milo--adobecom.hlx.page?marketingtech=off](https://martechteamupdates--milo--adobecom.hlx.page?marketingtech=off)
Note
Currently when passing marketingtech=off page is not loading, Expected behavior is martech bootstrap should not load and page should load as it is
More Information
There …
=> ENB-6995 Query Params update & sendTargetResponse function update Resubmit for #2664

libs/deps/mas/merch-card-all.js, libs/deps/mas/merch-card.js, libs/deps/mas/plans-modal.js, libs/features/mas/web-components/src/global.css.js
Added fallback to "Adobe Clean" font for callout text.
Callout text font before Fix:
Callout text font after Fix: 
Resolves: [MWPW-155627](https://jira.corp.adobe.com/browse/MWPW-155627)
**Test URLs:**
Before: https://main--milo--adobecom.hlx.page/drafts/rosahu/rosahu
After: https://mwpw-155627--milo--rohitsahu.hlx.page/drafts/rosahu/rosahu
=> [MWPW-155627] Merch Callout feature: Missing font cascade

libs/features/webapp-prompt/webapp-prompt.css
* Added some rtl specific styles to position the tooltip correctly when it's on the opposite end of the page
Resolves: [MWPW-153955](https://jira.corp.adobe.com/browse/MWPW-153955)
**Test URLs:**
- After: https://rtl-pep-tooltip--milo--sharmrj.hlx.page/?martech=off
- QA: https://main--cc--adobecom.hlx.page/eg_ar/creativecloud/animation/testdoc/pepphsp1?skipPepEntitlements=true&milolibs=rtl-pep-tooltip--milo--sharmrj
=> MWPW-153955 [PEP ] dismiss tool tip text is seen chopped in RTL locale in ipad and iphone in landscape mode

libs/blocks/marketo/marketo.js, test/blocks/marketo/marketo.test.js
* Fixes issue that was preventing "message" success type for Marketo forms
* FYI there's also a fix needed on the MCZ side for the message to fully work
Resolves: [MWPW-152952](https://jira.corp.adobe.com/browse/MWPW-152952)
**Test URLs:**
- Before: https://main--milo--adobecom.hlx.page/drafts/methomas/marketo-message?martech=off
- After: https://methomas-marketo-message--milo--adobecom.hlx.page/drafts/methomas/marketo-message?martech=off
To verify:
- Note that the form doesn't redirect
- Also, look in the console under "Form Type & Version" -> "success"
- The content should be a thank you message: "Thank you. Your request has been..."
- The type should be "message"
Regression:
(Should redirect)
- https://main--bacom--adobecom.hlx.live/?milolibs=methomas-marketo-message
=> MWPW-152952 Allow message for Marketo form success

libs/utils/utils.js
Revert PR of placeholder function as placeholder value is seen displayed with additional nbsp text in locale product pages in stage
Resolves: [[MWPW-156193]](https://jira.corp.adobe.com/browse/MWPW-NUMBER)
Test URLs:
Before: https://placeholderreplacement--milo--suhjainadobe.hlx.live/drafts/suhjain/performance/marquee-light
After: https://revertPlaceholder--milo--adobecom.hlx.live/drafts/suhjain/performance/marquee-light
=> revert  PR of placeholder function as placeholder value is seen displayed with additional nbsp text in locale product pages in stage

libs/utils/utils.js
**Description:**
* Make the new GNAV (global-navigation and global-footer) the default one.
* Automatically onboard any new Milo consumer to use the new GNAV.
* This approach helps reduce redundant metadata properties, preventing the metadata.xlsx file from becoming unnecessarily to large.
* We have to add config if want to use deprecated version of GNAV (ganv and footer) like this experience is still used with blog and bacom blog.
For example:
`/drafts/devashish/default/**` based on this After URL, we can add the necessary configuration. However, ensure that we remove `/**` and `/drafts/**` entries , as they override the settings when `/drafts/devashish/default/**` is missing or the config values are empty. There’s no need to include anything in `metadata.xlsx` for the new GNAV …
=> Making new GNAV experience default

libs/blocks/global-navigation/global-navigation.js
* Removing unnecessary loading of gnav search JS and CSS files.
Resolves: [MWPW-154608](https://jira.corp.adobe.com/browse/MWPW-154608)
**Test URLs:**
- Before: https://main--milo--adobecom.hlx.live/drafts/blaishram/gnav-search-page?martech=off
- After: https://gnav-search--milo--bandana147.hlx.live/drafts/blaishram/gnav-search-page?martech=off
=> Fix: Load gnav search files only if it is authored

libs/blocks/accordion/accordion.css
This adjusts an accordion style for RTL alignment.
| <img width="499" alt="Screenshot 2024-08-07 at 13 31 05" src="https://github.com/user-attachments/assets/4ba7dae5-4eb0-45c9-8cee-c32a4406a031"> | <img width="499" alt="Screenshot 2024-08-07 at 13 30 35" src="https://github.com/user-attachments/assets/2374232d-e654-4e7d-bf34-1a4f9c0a9b4d"> |
Resolves: [MWPW-154102](https://jira.corp.adobe.com/browse/MWPW-154102)
**Test URLs:**
- Before: https://main--milo--overmyheadandbody.hlx.page/kw_ar/drafts/ramuntea/accordion?martech=off
- After: https://accordion-rtl--milo--overmyheadandbody.hlx.page/kw_ar/drafts/ramuntea/accordion?martech=off
=> [MWPW-154102] Accordion RTL alignment

.github/workflows/high-impact-alert.js, .github/workflows/high-impact-alert.yml
This sends an additional notification to a new Milo channel whenever PRs marked as 'high-impact' are opened. Moving forward, we might want to send just one notification, but both will be needed during this transition period to ensure everyone remains informed.
Resolves: [MWPW-156163](https://jira.corp.adobe.com/browse/MWPW-156163)
**Test URLs:**
- Before: https://main--milo--overmyheadandbody.hlx.page/?martech=off
- After: https://milo-updates-notif--milo--overmyheadandbody.hlx.page/?martech=off
=> [MWPW-156163] Send additional Slack notifications for high impact PRs

libs/blocks/merch/merch.js, test/blocks/merch/merch.test.js
checkout link configuration in addition to product family.
Resolves: [MWPW-156220](https://jira.corp.adobe.com/browse/MWPW-156220)
**Test URLs:**
- Before: https://main--milo--adobecom.hlx.page/drafts/ilyas/checkout-link-config?martech=off
- After: https://mwpw-156220--milo--adobecom.hlx.page/drafts/ilyas/checkout-link-config?martech=off
**CC**
https://main--cc--adobecom.hlx.page/products/catalog?milolibs=mwpw-156220#search=acrobat
=> MWPW-156220: Support pa code and product code for

libs/utils/logWebVitals.js, libs/utils/utils.js, test/utils/logWebVitals.test.js, test/utils/logWebVitalsUtils.test.js
Require performance consent before tracking performance related data. 
Resolves: [MWPW-154969](https://jira.corp.adobe.com/browse/MWPW-154969)
**Test URLs:**
- After: https://performance-consent--milo--mokimo.hlx.page/?martech=off
=> [MWPW-154969] Performance consent

libs/utils/utils.js, test/utils/mocks/body.html, test/utils/utils.test.js
This feature allows you to set the `rel='nofollow'` on a individual link in milo.
* similar to` #_blank` we can append `#_nofollow ` on a link to set the 'rel' attribute of an anchor tag to nofollow.
* eg: https://www.adobe.com/in/creativecloud.html#_nofollow
* updated milo docs https://mwpw-151162--milosh--sharath-kannan.hlx.page/docs/authoring/links
Resolves: [MWPW-151162](https://jira.corp.adobe.com/browse/MWPW-151162)
**Test URLs:**
- Before: https://main--milo--adobecom.hlx.live/drafts/sharathkannan/media-container?martech=off
- After: https://mwpw-151162--milosh--sharath-kannan.hlx.page/drafts/sharathkannan/media-container?martech=off
=> Feat(MWPW:151162):nofollow a individual link.

libs/blocks/quiz/quizcontainer.js, libs/blocks/quiz/quizoption.js, libs/blocks/quiz/utils.js
* Add new function in utils to clean up LTRM unicode in URLs
* Call above function in proper places
Resolves: [MWPW-156094](https://jira.corp.adobe.com/browse/MWPW-156094)
**Test URLs:**
-Before: https://main--cc--adobecom.hlx.page/il_he/creativecloud/plan-recommender/quiz2?martech=off
-After: https://stage--milo--jackysun9.hlx.page/drafts/quiz/plan-recommender-var/quiz?martech=off
How to test?
Test IL Page
https://main--cc--adobecom.hlx.page/il_he/creativecloud/plan-recommender/quiz2?martech=off&milolibs=stage--milo--JackySun9
Test JP page
https://main--cc--adobecom.hlx.page/jp/creativecloud/plan-recommender/quiz?martech=off&milolibs=stage--milo--JackySun9
Test EN Page
https://main--cc--adobecom.hlx.page/creativecloud/plan-recommender/quiz?martech=off&milolibs=stage--milo--JackySun9
Test …
=> MWPW-156094: clean up LTRM in URLs

libs/features/personalization/personalization.js, libs/features/personalization/preview.js
* MEP button was reporting undefined for manifest URL when you hover over the manifest file name
* MEP button was reporting N/A for analytics name for pzn manifests, but giving an analytics name for non-pzn manifests.
Resolves: [MWPW-156545](https://jira.corp.adobe.com/browse/MWPW-156545)
**Test URLs:**
- Before: https://main--cc--adobecom.hlx.page/products/premiere?mep=%2Fproducts%2Fpremiere.json--target-edu_pzn---%2Fcc-shared%2Ffragments%2Fpromos%2F2024%2Famericas%2Fste-back-to-school-q3%2Fste-back-to-school-q3.json--default
- After: https://main--cc--adobecom.hlx.page/products/premiere?milolibs=mepmaniurl&mep=%2Fproducts%2Fpremiere.json--target-edu_pzn---%2Fcc-shared%2Ffragments%2Fpromos%2F2024%2Famericas%2Fste-back-to-school-q3%2Fste-back-to-school-q3.json--default
Psi-check: …
=> MWPW-156545 [MILO][MEP] Info in MEP button panel is incorrect

libs/blocks/modal/modal.js, test/blocks/modals/modals.test.js
* Allow authoring hash value delay=0 for modals authored using promos.
* This is for the performance gain we see when these modals are authored with delay=0 compared to delay=1
Resolves: [MWPW-154970](https://jira.corp.adobe.com/browse/MWPW-154970)
**Test URLs:**
Milo:
- Before: https://stage--milo--adobecom.hlx.page/drafts/ruchika/document?martech=off
- After: https://MWPW-154970--milo--adobecom.hlx.page/drafts/ruchika/document?martech=off
CC
- Before: https://main--cc--adobecom.hlx.page/drafts/ruchika/tiger/promo/illustrator-no-delay?martech=off
- After: https://main--cc--adobecom.hlx.page/drafts/ruchika/tiger/promo/illustrator-no-delay?milolibs=MWPW-154970&martech=off
=> [MWPW-154970] allow authoring hash value delay=0 for promo modals

libs/utils/utils.js, test/utils/mocks/body.html, test/utils/utils.test.js
Media image is seen loaded twice in product page urls in desktop
This fixes the replacing of whole innerHTML if there is any placeholder on the page. It only the specific placeholder text.
Resolves: [MWPW-153810](https://jira.corp.adobe.com/browse/MWPW-NUMBER)
Test URLs:
Before: https://main--milo--adobecom.hlx.page/drafts/suhjain/performance/marquee-light
After: https://placeholderReplace--milo--adobecom.hlx.live/drafts/suhjain/performance/marquee-light
=> MWPW-153810 media image is seen loaded twice in product page urls in desktop

libs/blocks/adobetv/adobetv.js, libs/blocks/video/video.js, libs/utils/decorate.js, test/blocks/adobetv/adobetv.test.js, test/blocks/adobetv/mocks/body.html, test/blocks/marquee/marquee.test.js, test/blocks/video/mocks/body.html, test/blocks/video/video.test.js, web-test-runner.config.mjs
Fixes 0.2 marquee CLS (+10LH points) for videos. The CLS was caused by only adding the video element & source to the page AFTER text has already been rendered next to it, as the intersection observer can only render things in the event cycle. We now only add the source of a video within the scope of the intersection observer, to keep the benefits of not loading videos that aren't displayed, however also dont cause any CLS.
Few related PRs/features that should still work afterwards...
- https://github.com/adobecom/milo/pull/1106
- https://github.com/adobecom/milo/pull/2487
- https://github.com/adobecom/milo/pull/1343
And the CLS should be gone. 
Resolves: [MWPW-155412](https://jira.corp.adobe.com/browse/MWPW-155412)
**Test URLs:**
Onhover play
- Before: …
=> MWPW-155412: Fix video CLS netting +10 lighthouse points

libs/blocks/adobetv/adobetv.js, libs/blocks/video/video.js, libs/utils/decorate.js, test/blocks/adobetv/adobetv.test.js, test/blocks/adobetv/mocks/body.html, test/blocks/marquee/marquee.test.js, test/blocks/video/mocks/body.html, test/blocks/video/video.test.js
Reverts adobecom/milo#2724 due to issues on https://business.stage.adobe.com/products/real-time-customer-data-platform/rtcdp.html?milolibs=stage
- https://revert-2724-cls-marquee--milo--adobecom.hlx.page/
Bacom tests
- Before: https://stage--bacom--adobecom.hlx.live/products/real-time-customer-data-platform/rtcdp?milolibs=stage
- After: https://stage--bacom--adobecom.hlx.live/products/real-time-customer-data-platform/rtcdp?milolibs=revert-2724-cls-marquee
=> Revert "MWPW-155412: Fix video CLS netting +10 lighthouse points"

libs/blocks/table/table.css
This ensures the row heading content wraps correctly when there is a long label along with a tooltip.
| <img width="619" alt="Screenshot 2024-08-14 at 17 42 15" src="https://github.com/user-attachments/assets/e7df026a-97b0-4f0a-b1d6-bce4c02db29f"> | <img width="619" alt="Screenshot 2024-08-14 at 17 41 49" src="https://github.com/user-attachments/assets/cdf90990-76cd-494a-b1b8-1134fac9659f"> |
Resolves: [MWPW-156638](https://jira.corp.adobe.com/browse/MWPW-156638)
**Test URLs:**
- Before: https://table-review--milo--overmyheadandbody.hlx.page/docs/library/kitchen-sink/table?martech=off
- After: https://table-section-row-wrap--milo--overmyheadandbody.hlx.page/docs/library/kitchen-sink/table?martech=off
=> [MWPW-156638] Table row header items wrap

.github/workflows/label-zero-impact.js, package.json
Fixes the paths in the `lint:css` script and adds `package.json` to the files that are considered for the `zero-impact` label, as discussed in a [previous PR](https://github.com/adobecom/milo/pull/2728#issuecomment-2286008339). Originally noticed by @chrischrischris.
Resolves: [MWPW-156746](https://jira.corp.adobe.com/browse/MWPW-156746)
**Test URLs:**
- Before: https://main--milo--overmyheadandbody.hlx.page/?martech=off
- After: https://update-css-lint-command--milo--overmyheadandbody.hlx.page/?martech=off
=> [MWPW-156746] Use correct paths for lint:css script

libs/blocks/accordion/accordion.css, libs/blocks/region-nav/region-nav.css
This PR fixes accordion and hover state bugs found in an initial round of QA of the demo page
- Fixes accordion active state issue
> RE: When I click on the accordion btn, it expands then I click again, it contracts and remains black. I have to click somewhere else to have the btn gray again. Clicking on another accordion btn doesn’t make previous btn gray.
- Fixes accordion height to align with padding in mockup
- Fixes region links hover state
Accordion before:
https://github.com/user-attachments/assets/c0b0155c-ab3b-4903-9a10-36e038b369de
Accordion after:
https://github.com/user-attachments/assets/4e5c9f64-9246-4a97-ab14-fdccf9e426f2
Resolves: [MWPW-151456](https://jira.corp.adobe.com/browse/MWPW-151456)
**Test URLs:**
- Before: …
=> MWPW-151456: Demo page accordion & hover state bug fixes

libs/blocks/notification/notification.css, libs/blocks/notification/notification.js, libs/utils/decorate.js, test/blocks/notification/mocks/body.html, test/blocks/notification/notification.test.js
* This PR accounts for various edge-cases in Ribbon and Banner Notifications.
* Changed default button sizes and labels to align with other Milo blocks.
* Added support for product lockups in Notifications.
* Added a guardrail to `decorateBlockText` so "detail" text styles are not applied to product lockups.
Resolves: [MWPW-155529](https://jira.corp.adobe.com/browse/MWPW-155529)
**Test URLs:**
Test Page from ticket reporter:
- Before: https://main--milo--adobecom.hlx.page/drafts/vmorel/red-team/notification/mwpw-155529?martech=off
- After: https://ebartholomew-general-notification-fixes--milo--adobecom.hlx.page/drafts/vmorel/red-team/notification/mwpw-155529?martech=off
Banners
- Before: https://main--milo--adobecom.hlx.page/drafts/ebartholomew/notifications-pr?martech=off
- After: …
=> MWPW-155529 - Notification design parity

libs/blocks/quiz/quiz.css
* slightly adjusts the blue text color of selected option cards so they have enough accessible color contrast
Resolves: [MWPW-147759](https://jira.corp.adobe.com/browse/MWPW-147759)
**Test URLs:**
- After: https://quiz-color-contrast-fixes--milo--colloyd.hlx.page/drafts/colloyd/quiz/?martech=off
=> MWPW-147759 - quiz option contrast fixes

libs/blocks/table/table.css
This addresses three minor design parity issues:
* checkmark color, which has been updated after the initial request;
* column header spacing, which didn't match the Figma design specs;
* the tooltip icon has been shrunk to `16px` as per the specs.
Resolves: [MWPW-156925](https://jira.corp.adobe.com/browse/MWPW-156925)
**Test URLs:**
- Before: https://table-review--milo--overmyheadandbody.hlx.page/drafts/ramuntea/table-tiger-team-mwpw-152305?martech=off
- After: https://table-review-issues--milo--overmyheadandbody.hlx.page/drafts/ramuntea/table-tiger-team-mwpw-152305?martech=off
=> [MWPW-156925] Table - design parity tweaks after Consonant feedback

libs/blocks/accordion/accordion.css
* A request has been made to add a `no borders` option to the Accordion block. Like the variant name implies, this removes the gray separators in between accordion items.
* Note that this has been marked as a critical update in Jira.
Resolves: [MWPW-156872](https://jira.corp.adobe.com/browse/MWPW-156872)
**Test URLs:**
- Before: https://main--milo--adobecom.hlx.page/drafts/ebartholomew/accordion-no-borders?martech=off
- After: https://ebartholomew-mwpw-156872-no-borders-accordion--milo--adobecom.hlx.page/drafts/ebartholomew/accordion-no-borders?martech=off
=> MWPW-156872 - Add `no borders` variant to Accordion block

libs/features/personalization/entitlements.js
* Add new entitlement (prod only) Details:
ID# 08691170-f6d6-46c7-9f3c-543d7761b64a
Edge | Free users (w/o trial) who are logged-in today
Description: Users who are free and have not taken any trial or paid plan and are logged-in today (last 24hrs).
Tag name: free-no-trial-loggedin-today
Resolves: [MWPW-147803](https://jira.corp.adobe.com/browse/MWPW-147803)
**Test URLs:**
- After: https://mepfreenotrial--milo--adobecom.hlx.page/?martech=off
=> MWPW-147803 [MEP] Request for Logged in Free users tag

libs/styles/styles.css
Prevent a line break before 'ー U+2013', '〜 U+301C', and etc in Japanese.
Refer from https://drafts.csswg.org/css-text-3/#line-break-property
**Before**
<image src="https://github.com/user-attachments/assets/c4e0cee3-5e59-4bf5-adf9-536cf33ea8d2" width="200px" />
**After**
<image src="https://github.com/user-attachments/assets/19c282a8-10ab-4bd3-90bb-beb74c7a040d" width="200px" />
**Test URLs:**
- Before: https://stage--milo--adobecom.hlx.page/jp/drafts/takyoshi/
- After: https://stage--milo--tamanyan.hlx.page/jp/drafts/takyoshi/
=> Prevent a line break before 'ー U+2013', '〜 U+301C', and etc in Japanese

libs/features/personalization/entitlements.js, libs/martech/martech.js, libs/utils/utils.js, test/utils/mocks/mep/head-xlg.html, test/utils/utils-mep.test.js
Although XLG segments can be sent to any user, MEP currently limits using them to logged in users.
Similar to the "target" setting for MEP, we will add an "xlg" setting that allows the use of XLG segments for logged out users.
* add if statement to loadIms to not set entitlements to empty when logged out if setting for xlg is set to loggedout
* move getMepEnablement and it's related functions higher so they are defined for use before loadIms
* call setupEntitlementCallback in martech.js if set to logged out, regardless of logged in status
* this also seems to fix a bug that causes a blank screen if: user is logged out, target enablement is off, and manifest uses xlg segments. we don't have any pages RIGHT NOW that use xlg without Target, but this will be good to fix for that future …
=> MWPW-156898 [MEP] Add setting to use XLG segments in MEP while logged out

libs/blocks/locui/utils/miloc.js
Pass user details (accessToken) to service calls create-project, start-sync, start-project, start-rollout, cancel-project. This will be used for user details storing in data.json and auth purpose.
Resolves: [MWPW-156265](https://jira.corp.adobe.com/browse/MWPW-156265)
**Test URLs:**
- Before: https://locui-debug--milo--raga-adbe-gh.hlx.page/tools/loc?ref=main&repo=milo&owner=adobecom&host=milo.adobe.com&project=Milo&referrer=https%3A%2F%2Fadobe.sharepoint.com%2F%3Ax%3A%2Fr%2Fsites%2Fadobecom%2F_layouts%2F15%2FDoc.aspx%3Fsourcedoc%3D%257B21F1B612-F4BD-484C-8C0E-8D0DBEF3AC03%257D%26file%3Dmilocragatwo1.xlsx%26action%3Ddefault%26mobileredirect%3Dtrue
- After: https://locui-debug--milo--raga-adbe-gh.hlx.page/tools/loc?ref=main&repo=milo&owner=adobecom&host=milo.adobe.com&project=Milo&referrer= …
=> MWPW-156265 - [LocUI] Pass user information to loc service calls

libs/blocks/merch/merch.js
Go live 4th September blocker.
Fix external modals on catalog.
checkoutLinkConfig[columnName] is an external CRM modal `https://www.adobe.com/plans-fragments/modals/individual/modals-content-rich/all-apps/master.modal.html `
that gets localized and becomes '/plans-fragments/modals/individual/modals-content-rich/all-apps/master.modal.html'
that doesn't pass regex later on on openModal
`} else if (/^https?:/.test(url)) {`
Resolves: https://jira.corp.adobe.com/browse/MWPW-157540
**Test URLs:**
- Before: https://main--milo--adobecom.hlx.live/drafts/mariia/pr/price-cta?martech=off
- After: https://MWPW-157540--milo--adobecom.hlx.live/drafts/mariia/pr/price-cta?martech=off
=> MWPW-157540: fix external modals

libs/blocks/hero-marquee/hero-marquee.css, libs/blocks/hero-marquee/hero-marquee.js
Fixed some bugs in the `hero-marquee` that were found in GPW user testing. These changes address the following. 
1) Row type and button variants on con-block rows should style the elements. They are not. ex `con-block-row-text (s-body, xl-button, xxxl-heading)`
2) `:icons:` in the main content area not rendering.
3) Update lockup styles from incoming globals.
4) When background image is smaller than 1199px, the image should be forced to display at 100% in tablet view.
5) When CTA is the ONLY element placed in "con block row text," margin top should be removed.
6) Video elements not displaying for mobile or tablet when authored w/ bg-bottom-mobile, bg-top-tablet variants. 
Resolves: [MWPW-154209](https://jira.corp.adobe.com/browse/MWPW-154209)
**Test URLs:**
- Before: …
=> MWPW-154209 - [hero-marquee] bugs

libs/features/personalization/personalization.js, libs/utils/utils.js
* If a merch-card is added by MEP too late on the page, the function to add highlights is too late. Moving the call to preview.js from loadPostLCP to loadDeferred will ensure the page is fully decorated.
Resolves: [MWPW-157034](https://jira.corp.adobe.com/browse/MWPW-157034)
Note, the change is near the bottom of the page, and the before link sometimes highlights the cards.  But the after link always does
**Test URLs:**
- Before: https://main--cc--adobecom.hlx.page/drafts/mepdev/fragments/2024/q3/mepmovepreviewcall/test?mepHighlight=true
- After: https://main--cc--adobecom.hlx.page/drafts/mepdev/fragments/2024/q3/mepmovepreviewcall/test?mepHighlight=true&milolibs=mepmovepreviewcall
- Psi-check: https://mepmovepreviewcall--milo--adobecom.hlx.page/?martech=off
=> MWPW-157034 [MEP] move call for preview from loadPostLCP to loadDeferred

libs/blocks/mobile-app-banner/mobile-app-banner.js, test/blocks/mobile-app-banner/mobile-app-banner.test.js
* When a user who has opted into both analytics and advertising cookies and is using Android device, their unique ECID is passed to Branch.
* These changes were approved and merged last month ( PR: [2567](https://github.com/adobecom/milo/pull/2567)) but were later reverted as we needed to wait for PIA approval. We are now re-opening this PR as we have received the PIA approval for this.
Resolves: [MWPW-152968](https://jira.corp.adobe.com/browse/MWPW-152968)
**Test URLs:**
- Before: https://main--milo--adobecom.hlx.live/drafts/drashti/milo-banner/branch-banner?martech=off
- After: https://branch-ecid--milo--drashti1712.hlx.live/drafts/drashti/milo-banner/branch-banner
=> [MWPW-152968] mWeb - Passing ECID to Branch.io banner - Implementation

libs/blocks/quiz-entry/quiz-entry.css, libs/blocks/quiz-entry/quizoption.js
* adjustment to colors for better contrast
* aria-label for carousel arrows
* css clean up
Resolves: [MWPW-156126](https://jira.corp.adobe.com/browse/MWPW-156126)
**Test URLs:**
- Before: https://main--milo--adobecom.hlx.page/drafts/colloyd/quiz-entry/?martech=off
- After: https://quiz-entry-contrast-fixes--milo--colloyd.hlx.page/drafts/colloyd/quiz-entry/?martech=off
=> MWPW-156126 - quiz-entry contrast and accessibility

libs/blocks/merch-card/merch-card.js
Resolves: [MWPW-157556](https://jira.corp.adobe.com/browse/MWPW-157556)
**Test URLs:**
- After: https://MWPW-157556--milo--adobecom.hlx.page/?martech=off
- Before: https://main--cc--adobecom.hlx.live/products/photoshop?martech=off&georouting=off&skipBanner=true
- After: https://main--cc--adobecom.hlx.live/products/photoshop?martech=off&georouting=off&skipBanner=true&milolibs=MWPW-157556
Before lit-all.min.js
After lit-all.min.js
=> [MWPW-157556] Eagerly import lit from merch-card block

libs/blocks/table/table.css
This tweaks the font size for strikethrough pricing inside table headers.
Resolves: [MWPW-148140](https://jira.corp.adobe.com/browse/MWPW-148140)
**Test URLs:**
- Before: https://main--milo--overmyheadandbody.hlx.page/drafts/ramuntea/table-tiger-team-kyung-overhaul?martech-off&georouting=off
- After: https://table-strikethrough-font--milo--overmyheadandbody.hlx.page/drafts/ramuntea/table-tiger-team-kyung-overhaul?martech-off&georouting=off
=> [MWPW-148140] Adjust table strikethrough pricing

libs/blocks/section-metadata/section-metadata.css
Added additional section-metadata styles to target tablet viewports with our existing `-ups` grids.
`style: three-up-tablet, four-up-tablet`
In addition, the existing style `one-up-tablet` should be moved into the standard tablet media query. 
(600-1200 instead of 600-900).
Live testing page -> https://main-dc-adobecom.hlx.page/acrobat/business/webinars/document-automation-made-eas[…]th-adobe-acrobat-sign?milolibs=rparrish-ups-grid-tablet  
Resolves: [MWPW-151932](https://jira.corp.adobe.com/browse/MWPW-151932)
**Test URLs:**
- Before: https://main--milo--adobecom.hlx.page/drafts/rparrish/grids/ups-grid-responsive?martech=off
- After: https://rparrish-ups-grid-tablet--milo--adobecom.hlx.page/drafts/rparrish/grids/ups-grid-responsive?martech=off
=> MWPW-151932 - Section metadata style grid enhancement for tablet VP

libs/utils/logWebVitals.js, test/utils/logWebVitals.test.js
Add `isFrag` and `isMep` attributes to lana LCP logging.
Resolves: [MWPW-157445](https://jira.corp.adobe.com/browse/MWPW-157445)
**Test URLs:**
- After: https://mwpw-157445--milo--adobecom.hlx.page/?martech=off
=> MWPW-157445 Additional Lana LCP data

libs/blocks/merch/merch.js
Fixes preselected tab not working in external modals (Twp) on Catalog page.
Resolves: [MWPW-157761](https://jira.corp.adobe.com/browse/MWPW-157761)
**Test URLs:**
- Before: https://main--milo--adobecom.hlx.live/drafts/mariia/pr/price-cta?martech=off
- After: https://MWPW-157761--milo--adobecom.hlx.live/drafts/mariia/pr/price-cta?martech=off
=> MWPW-157761: Tab preselect in external modals [catalog]

libs/features/personalization/personalization.js, test/features/personalization/modifyNonFragmentSelector.test.js
The new action-area MEP simplified selector does not work on hero-marquees because there is no paragraph around the buttons
* Update CSS selector to also be able to catch divs
Resolves: [MWPW-157693](https://jira.corp.adobe.com/browse/MWPW-157693)
QA instructions: We want the action-area selector to start working in hero-marquees but continue to work in regular marquees.  To make it more obvious the content is updated, I added "(pzn)" to the marquee description and to one of the buttons
**Test URLs:**
Hero Marquee:
- Before: https://main--cc--adobecom.hlx.page/drafts/mepdev/fragments/2024/q4/mepactionarea/marquee?martech=off
- After: https://main--cc--adobecom.hlx.page/drafts/mepdev/fragments/2024/q4/mepactionarea/marquee?milolibs=mepactionarea&martech=off
Marquee:
- Before: …
=> MWPW-157693 [MEP] Action area simplified selector does not work well with hero-marquee block

libs/blocks/editorial-card/editorial-card.css, libs/blocks/editorial-card/editorial-card.js, libs/blocks/text/text.css, libs/styles/styles.css, libs/utils/decorate.js
Fixed the following bugs
1) In Editorial card, when image is added per breakpoint, it uses the same decorate bg function with rounded-corder.css where the image unintentionally gets targeted with the class `.background` causing a style naming collision. I am passing this className as a parameter now. 
2) When per-viewport bg images are used, they do not display
3) Button and product lockup override work ONLY ATM
4) Custom device support text should always be body-xxs
5) A [text-block] background doesn't show when it's authored in a wrapping section that also has a background. *bonus
Resolves: [MWPW-156135](https://jira.corp.adobe.com/browse/MWPW-156135)
**Test URLs:**
Before: https://main--milo--adobecom.hlx.page/drafts/rparrish/cards/editorial-cards-bugz?martech=off
After: …
=> MWPW-156135 - [editorial-card] bugs

libs/blocks/aside/aside.js, libs/blocks/notification/notification.js, libs/blocks/section-metadata/section-metadata.css
* Dispatch sticky close event for dynamic chat
* Increase z-index to place above chat (Dynamic chat has 2 second loading delay)
Resolves: [MWPW-155694](https://jira.corp.adobe.com/browse/MWPW-155694)
**Test URLs:**
- Before: https://main--milo--adobecom.hlx.page/drafts/bmarshal/sticky/aside?martech=off
- After: https://bmarshal-chat-promo--milo--adobecom.hlx.page/drafts/bmarshal/sticky/aside?martech=off
- Before: https://main--milo--adobecom.hlx.page/drafts/bmarshal/sticky/notification?martech=off
- After: https://bmarshal-chat-promo--milo--adobecom.hlx.page/drafts/bmarshal/sticky/notification?martech=off
**Bacom URLs:**
- Before: https://business.stage.adobe.com/resources/digital-economy-index.html?martech=on
- After: https://business.stage.adobe.com/resources/digital-economy-index.html?m …
=> MWPW-155694 Dispatch sticky close event for dynamic chat

libs/features/placeholders.js, libs/utils/utils.js, test/utils/mocks/body.html, test/utils/utils.test.js
The phone number on the following pages is appearing correctly in the text but showing random characters in the link. Previously, using the placeholder for both the display text and link text displayed the number correctly.
Resolves: [[MWPW-157292]](https://jira.corp.adobe.com/browse/MWPW-NUMBER)
Test URLs:
Before: https://main--milo--adobecom.hlx.live/drafts/suhjain/performance/marquee-light
After:https://placeholderOriginNew--milo--suhjainadobe.hlx.live/drafts/suhjain/performance/marquee-light
=> MWPW-157292: CC and DC: Phone number links wrong

libs/features/personalization/personalization.js, test/features/personalization/modifyNonFragmentSelector.test.js
It's becoming very common to switch between using the marquee block, interactive-marquee block or the hero-marquee block.
There's an easy CSS selector to get any of these, but if it was a simplified selector it would be easier to use.
Similarly, it can be hard to know which header level to use (h1, h2, h3 etc.) because they can look the same and even get changed by the decoration process. Although it can be achieved in CSS, it would be easier to have a simplified selector.
Resolves: [MWPW-157785](https://jira.corp.adobe.com/browse/MWPW-157785)
Note the examples below use the same manifest with the same selector: "any-marquee primary-cta"
**Test URLs:**
Marquee:
- Before: https://main--cc--adobecom.hlx.page/drafts/mepdev/fragments/2024/q4/mepanymarquee/marquee?martech=off
- After: …
=> MWPW-157785 [MEP] Create "any-marquee" and "header" simplified selectors

libs/blocks/table/table.css
This slightly adapts how prices are displayed in table headers to avoid content exceeding the viewport and ensure the text flows in a natural way.
Resolves: [MWPW-157334](https://jira.corp.adobe.com/browse/MWPW-157334)
| Locale | Before | After |
| ------------- | ------------- | ------------- |
| **IT** | ![Simulator Screenshot - iPhone 15 Pro Max - 2024-09-04 at 17 33 02](https://github.com/user-attachments/assets/456bacbb-5119-4fbd-9363-b680e431ca90) | ![Simulator Screenshot - iPhone 15 Pro Max - 2024-09-04 at 17 32 53](https://github.com/user-attachments/assets/79f0b6d1-223d-466b-a3f7-f43d5ebc3c67) |
| **KR** | ![Simulator Screenshot - iPhone 15 Pro Max - 2024-09-04 at 17 29 54](https://github.com/user-attachments/assets/451e6aa0-083e-4911-8222-d30756284267) | ![Simulator Screenshot - …
=> [MWPW-157334] Table pricing alignment

libs/navigation/navigation.js, libs/utils/utils.js
* Make IMS environment configurable from config in standalone navigation
Resolves: [MWPW-157474](https://jira.corp.adobe.com/browse/MWPW-157474)
**Test URLs:**
- After: https://MWPW-157474--milo--adobecom.hlx.page/?martech=off
**QA**
- https://adobecom.github.io/nav-consumer/navigation.html?navbranch=mwpw-157474
=> Adding support for getting env config through client env

libs/features/personalization/personalization.js, test/features/personalization/modifyNonFragmentSelector.test.js
Detailed Description: selectors involving html elements like body break because MEP is not aware of them.
Changing "header" simplified selector to "any-header" since pages always have a header tag.
URL: https://main--cc--adobecom.hlx.page/drafts/mepdev/fragments/2024/q4/mepmorehtmlels/?mepHighlight=true
1. Go to URL above
Expected Results: should be 2 items highlighted, the new marquee header and a div below the marquee
Actual Results: no highlighted items because nothing is added
Resolves: [MWPW-157887](https://jira.corp.adobe.com/browse/MWPW-157887)
**Test URLs:**
- Before: https://main--cc--adobecom.hlx.page/drafts/mepdev/fragments/2024/q4/mepmorehtmlels/?mepHighlight=t …
=> MWPW-157887 [MEP] HTML elements like body need to be recognized and header simplified selector rename

libs/blocks/region-nav/region-nav.js
Added expiry of 'international' cookie as 1 year for selecting a region from region selector. Similar, like we already have this for AEM dexter pages.
Before:
After:
Resolves: [MWPW-157238](https://jira.corp.adobe.com/browse/MWPW-157238)
**Test URLs:**
- After: https://mwpw-157238--milo--deva309.hlx.page/drafts/devashish/wam?martech=off
=> Set expiry of 'international' cookie for 1 year for selection of region from region selector

libs/features/personalization/personalization.js
Note: this is listed a high priority because it is needed for MAX.
Detailed Description: experience columns using tablet are not catching smaller tablets
URL: https://main--cc--adobecom.hlx.page/products/photoshop-lightroom/features?target=off&mep=
1. Simulate a device that is android and tablet
2. Go to the link above (choosing any samsung tab) should work
Expected Results: MEP button indicates Android & Tablet is chosen
Actual Results: MEP button indicates mobile-device is chosen
Resolves: [MWPW-158059](https://jira.corp.adobe.com/browse/MWPW-158059)
**Test URLs:**
- Before: https://main--cc--adobecom.hlx.page/products/photoshop-lightroom/features?target=off&martech=off …
=> MWPW-158059 [MEP] PHONE_SIZE limit is too large to exclude smaller tablets

libs/blocks/table/table.css
Multiple elements can be added to a table column. There is currently no separation between them; since such columns mostly contain text (wrapped in their own elements), the gap has been set to be close to a space character.
| <img width="1216" alt="Screenshot 2024-09-09 at 17 14 38" src="https://github.com/user-attachments/assets/2297ad4a-24d9-4a55-b941-2d1acab69b8a"> | <img width="1216" alt="Screenshot 2024-09-09 at 17 15 52" src="https://github.com/user-attachments/assets/9b1e8acc-2755-46c8-848a-c45559e46b05"> |
Resolves: [MWPW-157740](https://jira.corp.adobe.com/browse/MWPW-157740)
**Test URLs:**
- Before: https://stage--milo--overmyheadandbody.hlx.page/drafts/ramuntea/table-tiger-team-mwpw-152305?martech=off&georouting=off
- After: …
=> [MWPW-157740] Table pricing gutter

libs/features/personalization/personalization.js, test/features/personalization/modifyNonFragmentSelector.test.js
* Can't use ul, ol or li in MEP selectors because it does not know they are HTML elements
Resolves: [MWPW-158148](https://jira.corp.adobe.com/browse/MWPW-158148)
QA instructions: Should see bippity boppity text in bullet list
**Test URLs:**
- Before: https://main--cc--adobecom.hlx.page/drafts/cgarrett/logged-in-training/li-training-test?mep=%2Fdrafts%2Fcgarrett%2Flogged-in-training%2Fli-training-test.json--heromarquee-bodycopy
- After: https://main--cc--adobecom.hlx.page/drafts/cgarrett/logged-in-training/li-training-test?milolibs=mepul&mep=%2Fdrafts%2Fcgarrett%2Flogged-in-training%2Fli-training-test.json--heromarquee-bodycopy
- Psi-check: https://mepul--milo--adobecom.hlx.page/?martech=off
=> MWPW-158148 [MEP] Can't use ul, ol or li in MEP selectorsf

libs/features/personalization/personalization.js
Reverting https://github.com/adobecom/milo/pull/2844
Resolves: [MWPW-157686](https://jira.corp.adobe.com/browse/MWPW-157686)
**Test URLs:**
- After: https://revertspoofpznexperience--milo--adobecom.hlx.page/?martech=off
=> REVERT MWPW-157686 [MEP] Cannot spoof an experience that exists in manifest but not in Target #2844 

libs/blocks/locui/loc/index.js
Empty space between locales in language config creates blank locale inside the language card. After formatting locales list we will now filter empty strings.
Resolves: [MWPW-157423](https://jira.corp.adobe.com/browse/MWPW-157423)
**Test URLs:**
- Before: https://main--cc--adobecom.hlx.page/tools/loc?milolibs=locui&ref=main&repo=cc&owner=adobecom&host=www.adobe.com&project=Creative+Cloud&referrer=https%3A%2F%2Fadobe.sharepoint.com%2F%3Ax%3A%2Fr%2Fsites%2Fadobecom%2F_layouts%2F15%2FDoc.aspx%3Fsourcedoc%3D%257B8f453a68-7eff-4a10-954d-feb2371c1d76%257D%26action%3Deditnew
- After: https://main--cc--adobecom.hlx.page/tools/loc?milolibs=sean-loc&ref=main&repo=cc&owner=adobecom&host=www.adobe.com&project=Creative+Cloud&referrer=https%3A%2F%2Fadobe.sharepoint.com%2F%3Ax%3A%2Fr%2Fsites%2Fadobecom%2F …
=> MWPW-157423 - [LocUI] Empty spaces in locales configuration

libs/blocks/bulk-publish-v2/components/bulk-publisher.js, libs/blocks/bulk-publish-v2/services.js, libs/tools/utils/publish.js, libs/utils/sidekick-decorate.js, libs/utils/utils.js, test/blocks/bulk-publish-v2/bulk-publish-v2.test.js, test/blocks/bulk-publish-v2/mocks/authentication.js, test/blocks/bulk-publish-v2/mocks/fetch.js, test/blocks/bulk-publish-v2/mocks/response/permissions.json, tools/utils/utils.js
As a web producer, I want to limit who can publish certain files so that files are not published prematurely before planned launches.
New Feature Includes:
- Ability to fetch an optional custom configuration file from path `.milo/publish-permissions-config` to apply advanced publishing rules on a per page basis.
- New functionality will disable the publish button in AEM sidekick if path matches an item (url pathname) in the configuration file and can also reference a group with optional `allow/deny` user list which then compares the list to the email of profile that is currently logged into sidekick.
- Bulk Publish v2 tool will also check paths in the job list for item configuration and refuse to publish urls that have been configured unless of course the currently logged in user has …
=> MWPW-154980 - Milo advanced page publishing

libs/blocks/global-navigation/global-navigation.js, libs/navigation/navigation.js, test/blocks/global-navigation/global-navigation.test.js
Create a container element for search in standalone gnav
Resolves: [MWPW-157417](https://jira.corp.adobe.com/browse/MWPW-157417)
**Test URLs:**
- After: https://mwpw157417--milo--adobecom.hlx.page/?martech=off
**QA**
- https://adobecom.github.io/nav-consumer/navigation.html?searchEnabled=on&navbranch=mwpw157417&env=stage
=> Create a container element for search in standalone gnav

libs/blocks/hero-marquee/hero-marquee.js
The text area in the hero-marquee is coming in CLS with iconography.css being a dependency 
Resolves: [MWPW-157682](https://jira.corp.adobe.com/browse/MWPW-NUMBER)
**Test URLs:**
- Before: https://main--milo--adobecom.hlx.live/drafts/suhjain/hero-marquee
- After: https://heromarquee--milo--suhjainadobe.hlx.live/drafts/suhjain/hero-marquee
=> MWPW-157682 Check CLS for photoshop page

libs/blocks/article-header/article-header.js, test/blocks/article-header/article-header.test.js, test/blocks/article-header/mocks/body.html
* Allow author image to be pulled from data attribute instead of link
* Needed for bacom blog but not brand blog
Resolves: [MWPW-144470](https://jira.corp.adobe.com/browse/MWPW-144470)
**Test URLs:**
(Regression)
- Before: https://main--milo--adobecom.hlx.page/drafts/methomas/blog-migration/article-header/connecting-external-data-sources-to-adobe-experience-manager-guides?martech=off
- After: https://methomas-disable-article-author--milo--adobecom.hlx.page/drafts/methomas/blog-migration/article-header/connecting-external-data-sources-to-adobe-experience-manager-guides?martech=off
Bacom blog:
(Combined with bacom blog feature branch: https://github.com/adobecom/bacom-blog/tree/methomas/disable-author)
- Before: https://main--bacom-blog--adobecom.hlx.live/blog/the-latest/what-a-marketing-sys …
=> MWPW-144470 Support article header author without link

libs/features/personalization/personalization.js, test/features/personalization/mocks/manifestSectionBlock.json, test/features/personalization/modifyNonFragmentSelector.test.js
Detailed Description: If a manifest uses a variant that ends in a number (example: `.aside02`) it is interpreted incorrectly.
URL: https://main--cc--adobecom.hlx.page/drafts/mepdev/fragments/2024/q4/mepclassendinginnumber/?mepHighlight=true
1. Go to the URL above
Expected Results: 2nd aside should be removed
Actual Results: 2nd aside is not removed
Resolves: [MWPW-158475](https://jira.corp.adobe.com/browse/MWPW-158475)
**Test URLs:**
- Before: https://main--cc--adobecom.hlx.page/drafts/mepdev/fragments/2024/q4/mepclassendinginnumber/?mepHighlight=true&martech=off
- After: https://main--cc--adobecom.hlx.page/drafts/mepdev/fragments/2024/q4/mepclassendinginnumber/?milolibs=m …
=> MWPW-158475 [MEP] classes that end in a number are modified when they should not be

libs/blocks/hero-marquee/hero-marquee.css, libs/blocks/hero-marquee/hero-marquee.js
As and author in a milo project using a  [hero-marquee]
1) I want to use this block with out a minimal height so the block has a natural height based on content. 
2) I want to use this block in an ups grid w/ the variant `full-width` and not have the extra left/right padding seen in this scenario. 
Example screenshot - Notice the block height is huge, the l/r padding is causing the block to go outside its bounds. 
---
Fixed
1) Add a `no-min-height` variant to the hero-marquee. 
2) Address padding issue on hero-block. Erroneously comes from the `has-bg` class being added. 
Resolves: [MWPW-157888](https://jira.corp.adobe.com/browse/MWPW-157888)
**Test URLs:**
- Before: https://main--milo--adobecom.hlx.page/drafts/steenmeyer/hero-editorial-layout-pattern-examples/hero-editorial-no-min-height- …
=> MWPW-157888 - Hero marquee w/ `no-min-height` and no l/r padding when using a `full-width` variant

libs/blocks/global-navigation/global-navigation.js, test/blocks/global-navigation/global-navigation.test.js, test/blocks/global-navigation/gnav-brand.test.js, test/blocks/global-navigation/gnav-cross-cloud.test.js, test/blocks/global-navigation/gnav-main-nav-popup.test.js, test/blocks/global-navigation/gnav-main-nav.test.js, test/blocks/global-navigation/gnav-profile.test.js, test/blocks/global-navigation/gnav-promo.test.js, test/blocks/global-navigation/gnav-search.test.js, test/blocks/global-navigation/test-utilities.js
Upgrades the UNav to 1.3
Adding eventListener for reloading Unav once Unav promise resolved as with v1.3 - the window.UniversalNav() returns a promise post which we can use methods like window.UniversalNav().reload() - [ref](https://wiki.corp.adobe.com/display/CCHome/Universal+Nav+Release+Info#:~:text=window.UniversalNav(config))
Also, Unav suggested to not rely on onReady method for triggering PEP modal instead we can wait for promise returned by `window.UniversalNav()` to be resolved.
Resolves: [MWPW-157965](https://jira.corp.adobe.com/browse/MWPW-157965)
**Test URLs:**
- Before: https://main--milo--adobecom.hlx.live/drafts/nishantkaush/test/unav?martech=off
- After: https://feds--milo--adobecom.hlx.live/drafts/nishantkaush/test/unav?martech=off
=> MWPW-157965: Upgrade Universal Nav to Version 1.3

libs/blocks/editorial-card/editorial-card.js, test/blocks/editorial-card/mocks/body.html
There was some feedback from GWP that the editorial-card (open) variant has some authoring issues w/ how the document is structured. At the core, this card type should not support a background row. 
This block has the ability to author w/ minimal content or 4+ rows that represent varying contexts. ex. 
| row count | content types |
| -------- | -------- |
| 3 rows | background, asset, copy |
| 4 rows | background, asset, copy, footer |
This update changes the authoring pattern when using the `open` variant as follows. 
This will allow us to offer a clean .open card example in our library w/ out the need or confusion for an empty background row. 
| row count | content types |
| -------- | -------- |
| 3 rows | 0:bg, 1:media, 2:copy |    
| 3 rows.open | 0:media, 1:copy, 2:card-footer | 
| …
=> MWPW-157024 - Editorial card authoring refinement for the 'open' variant.

libs/blocks/quiz-entry/quiz-entry.css, libs/blocks/quiz-entry/quiz-entry.js, libs/blocks/quiz-entry/quizoption.js
* Heading tags based on seo recommendations
* Adjust disabled button color for bettter contrast
* Focus reset for quiz options after using carousel nav with a keyboard
Resolves: [MWPW-158352](https://jira.corp.adobe.com/browse/MWPW-158352)
**Test URLs:**
- Before: https://main--milo--adobecom.hlx.page/drafts/colloyd/quiz-entry/?martech=off
- After: https://quiz-entry-accessibility-v2--milo--colloyd.hlx.page/drafts/colloyd/quiz-entry/?martech=off
=> Quiz Entry Accessibility Round 2

.github/workflows/run-nala.yml
* Do not run nala tests on all PRs without the specified label, as the `run-nala-default.yaml `will handle this
* Update the configuration to support running Nala tests on consuming projects when the specified label is present
- `run-nala-on-<consuming project>` from Nala repositories
Resolves: [MWPW-158583](https://jira.corp.adobe.com/browse/MWPW-158583)
**Test URLs:**
- After: https://nala-worklflow--milo--adobecom.hlx.page/?martech=off
=> [MWPW-158583] Update old run-nala GitHub action job

libs/blocks/hero-marquee/hero-marquee.css, libs/blocks/hero-marquee/hero-marquee.js
Reverts adobecom/milo#2861
Issue found with missing background images.
**Test URLs:**
- Before: https://main--milo--adobecom.hlx.page/drafts/steenmeyer/hero-editorial-layout-pattern-examples/hero-editorial-no-min-height-masonry1?martech=off
- After: https://revert-2861-rparrish/hero-no-min--milo--adobecom.hlx.page/drafts/steenmeyer/hero-editorial-layout-pattern-examples/hero-editorial-no-min-height-masonry1?martech=off
https://revert-2861-rparrish-hero-no-min--milo--adobecom.hlx.page/
=> Revert "MWPW-157888 - Hero marquee w/ `no-min-height` and no l/r padding when using a `full-width` variant"

libs/blocks/global-navigation/global-navigation.js, libs/blocks/global-navigation/utilities/utilities.js, test/blocks/global-navigation/global-navigation.test.js
This change prevents any NavItem from being marked as active by appending the hash `#_noActiveItem` to the `gnav-source`. The hash can be added either in the `metadata.xlsx` file or at the page level for the `gnav-source` metadata. If the hash is present, the Active Element Detection functionality is disabled.
For example:
Before (creativity & design is active NavItem):
After (No NavItem is active):
Resolves: [MWPW-157924](https://jira.corp.adobe.com/browse/MWPW-157924)
**Test URLs:**
- After: https://mwpw-157924--milo--deva309.hlx.page/?martech=off
QA:
https://main--cc--adobecom.hlx.page/drafts/devashish/vh?milolibs=mwpw-157924--milo--deva309
=> [MWPW-157924] - Added functionality to disable Active Element Detection

libs/blocks/library-config/library-config.css, libs/blocks/library-config/library-config.js, libs/blocks/library-config/library-utils.js, libs/blocks/library-config/lists/blocks.js, libs/blocks/library-config/lists/templates.js, libs/blocks/library-metadata/library-metadata.css, test/blocks/library-config/library-config.test.js
* Allows `template-metadata` block to be pasted as `metadata` block in template
* Fixes initial listing order
* Adds search ability to templates
Resolves: [MWPW-154059](https://jira.corp.adobe.com/browse/MWPW-154059)
**Test URLs:**
- Before: https://main--milo--adobecom.hlx.page/tools/library?martech=off
- After: https://template-library-updates--milo--adobecom.hlx.page/tools/library?martech=off
**BACOM Test URLs:**
- Before: https://main--milo--adobecom.hlx.page/tools/library?ref=main&repo=bacom&owner=adobecom&host=business.adobe.com&project=BACOM&martech=off
- After: https://template-library-updates--milo--adobecom.hlx.page/tools/library?ref=main&repo=bacom&owner=adobecom&host=business.adobe.com&project=BACOM&martech=off
**Testing notes:**
With the updated features, the template named …
=> MWPW-154059 - Milo templates library

libs/utils/utils.js
This PR enhances the stage links conversion feature to handle cross-domain localization.
Resolves: [MWPW-158756](https://jira.corp.adobe.com/browse/MWPW-158756)
1. open the after test URL
2. using the developer tools, overwrite scrips.js to :
- have `'business.adobe.com'` in the `prodDomains` array;
- have 
```
'--milo--robert-bogos.hlx.page': {
'business.adobe.com': 'main--bacom--adobecom.hlx.page'
}
```
in the `stageDomainsMap` config.
3. the business.adobe.com url should be converted and localized
**Milo:**
- Before: https://stage--milo--adobecom.hlx.page/de/drafts/rbogos/env-relative-urls?martech=off
- After: https://mwpw-158756-enhance-links-conversion--milo--robert-bogos.hlx.page/de/drafts/rbogos/env-relative-urls?martech=off
=> [MWPW-158756] Enhance stage links conversion for cross-domain localization

README.md, nala/utils/nala.run.js
* Update Milo README  with Nala commands details 
Resolves: [MWPW-158021](https://jira.corp.adobe.com/browse/MWPW-158021)
**Test URLs:**
- After: https://nala-docs--milo--adobecom.hlx.page/?martech=off
=> [MWPW-158021] Update Milo README with Nala commands details 

libs/martech/martech.js
Resolves: [MWPW-158777](https://jira.corp.adobe.com/browse/MWPW-NUMBER)
**Test URLs:**
- After: https://MWPW-158777--milo--npeltier.hlx.page/?martech=off
=> MWPW-158777 returning proper response in case of error

libs/blocks/locui/actions/index.js
In federal when finding fragments on a configured fragment URL finding fragments returns a URL found in the page META property `og:url`. Adding a condition in the find meta fragments functionality that will Ignore meta fragment URLs with that property.
Resolves: [MWPW-157476](https://jira.corp.adobe.com/browse/MWPW-157476)
**Test URLs:**
- Before: https://main--federal--adobecom.hlx.page/tools/loc?milolibs=locui&ref=main&repo=federal&owner=adobecom&referrer=https%3A%2F%2Fadobe.sharepoint.com%2F%3Ax%3A%2Fr%2Fsites%2Fadobecom%2F_layouts%2F15%2FDoc.aspx%3Fsourcedoc%3D%257Bddfa50c7-1f5c-46f0-8132-6fb507ab6d89%257D%26action%3Deditnew
- After: https://main--federal--adobecom.hlx.page/tools/loc?milolibs=sean-loc&ref=main&repo=federal&owner=adobecom&referrer=https%3A%2F%2Fadobe.sharepoint.com%2F%3 …
=> MWPW-157476 - [LocUI] Ignore OG property in find meta fragments

libs/blocks/floodgateui/actions/index.js, libs/blocks/floodgateui/actions/view.js, libs/blocks/floodgateui/floodgate/index.js, libs/blocks/locui/loc/index.js
Additional changes on validation of found fragments that will set new fragments and URLs in excel with validated URLs.
Resolves: [MWPW-155333](https://jira.corp.adobe.com/browse/MWPW-155333)
**Test URLs: (find fragments and see URL has been validated "NOT AEM URL")**
- Before: https://main--cc--adobecom.hlx.page/tools/floodgate?milolibs=floodgateui&ref=main&repo=cc&owner=adobecom&host=www.adobe.com&project=Creative+Cloud&referrer=https%3A%2F%2Fadobe.sharepoint.com%2F%3Ax%3A%2Fr%2Fsites%2Fadobecom%2F_layouts%2F15%2FDoc.aspx%3Fsourcedoc%3D%257Bdb7db426-1b49-4eea-8b5f-706c4010edbe%257D%26action%3Deditnew
- After: https://main--cc--adobecom.hlx.page/tools/floodgate?milolibs=sean-loc&ref=main&repo=cc&owner=adobecom&host=www.adobe.com&project=Creative+Cloud&referrer=https%3A%2F%2Fadobe.sharepoin …
=> MWPW-155333 - [FloodgateUI] Fragment Validation Updates

nala/utils/global.setup.js, nala/utils/pr.run.sh
* Update Nala global.setup.js for GitHub Action run to handle Bot generated PR ( Stage->Main) correctly
**Test URLs:**
- After: https://nala-jobs--milo--adobecom.hlx.page/?martech=off
=> [MWPW-158872 : NALA] Update Nala GitHub Action runs to correctly handle bot-generated PR details.

libs/blocks/global-navigation/global-navigation.js, libs/navigation/navigation.js
* Add option to configure children for unav's help component
* Universal nav has option to add custom children - [link](https://wiki.corp.adobe.com/display/CCHome/Universal+Nav+Integration+Guidelines#UniversalNavIntegrationGuidelines-HelpConfiguration)
* Need to add support for that from milo gnav.
Resolves: [MWPW-158737](https://jira.corp.adobe.com/browse/MWPW-158737)
**Test URLs:**
- After: https://unav-configurable--milo--adobecom.hlx.page/?martech=off
Qa: https://adobecom.github.io/nav-consumer/navigation.html?authoringpath=/federal/dev&env=stage&navbranch=unav-configurable
=> Add option to configure children for unav's help component

libs/utils/decorate.js
Added a conditional check in a shared function `decorateIconStack()` that was causing this. 
(This brick list authoring was triggering some shared link checking logic that wasn't properly verifying for null values) 
Resolves: [MWPW-155984](https://jira.corp.adobe.com/browse/MWPW-155984)
**Test URLs:**
- Before: https://main--milo--adobecom.hlx.page/drafts/rparrish/masonry/brick-list?martech=off
- After: https://rparrish-brick-lists--milo--adobecom.hlx.page/drafts/rparrish/masonry/brick-list?martech=off
**Live URLs:**
- Before: https://main--dc--adobecom.hlx.page/drafts/ntran/brick-null-bug?martech=off
- After: https://main--dc--adobecom.hlx.page/drafts/ntran/brick-null-bug?milolibs=rparrish-brick-lists&martech=off
**Regression:** blocks that use this function (aside, brick)
- aside …
=> MWPW-155984 - Brick list showing null value in link label

libs/utils/utils.js, test/utils/mocks/marquee.html, test/utils/utils.test.js
It's relatively hard to track performance beforehand, however we observed a +500MS (13%) gain on CC pages speeding up loading [placeholders](https://github.com/adobecom/milo/pull/2752). We've also seen good success with [preloading](https://github.com/orgs/adobecom/discussions/2719)
[This PR](https://github.com/adobecom/milo/pull/2493) initially introduced the idea of preloading `decorate.js` for a performance gain, but introduced _too much_ flexibility. The idea of preloading `decorate.js` for specifically the two common (hero-)marquees blocks is valuable and worth the added 3 lines of code, as neither is likely to change anytime soon.
This should provide good benefits on a wide arrange of blocks, consumers and pages by optimizing the load order and chains, however we will want to …
=> MWPW-158071: Optimize LCP loading times

libs/blocks/home/home.css
Allowing the Gnav to appear on the Milo Start Page
Resolves: [MWPW-154047](https://jira.corp.adobe.com/browse/MWPW-154047)
**Test URLs:**
- After: https://mwpw-154047--milo--akanshaa-18.hlx.page/?martech=off
=> GNav - Remove Header Display none

libs/blocks/caas-config/caas-config.js, test/blocks/caas-config/caas-config.test.html
* Removes defaults from state before creating caas config link
* Reduces caas link length by 25-30% for the longest links
Related to discussion: https://github.com/orgs/adobecom/discussions/2876
Resolves: [MWPW-158480](https://jira.corp.adobe.com/browse/MWPW-158480)
**Test URLs:**
Page with old/new links
- Before: https://main--milo--adobecom.hlx.page/drafts/methomas/caas-link-v2?martech=off
- After: https://methomas-caas-link-len--milo--adobecom.hlx.page/drafts/methomas/caas-link-v3?martech=off
=> MWPW-158480 Exclude defaults from caas links

nala/blocks/marquee-anchors/marquee-anchors.page.js, nala/blocks/marquee-anchors/marquee-anchors.spec.js, nala/blocks/marquee-anchors/marquee-anchors.test.js, nala/blocks/marquee/marquee.page.js, nala/blocks/marquee/marquee.spec.js, nala/blocks/marquee/marquee.test.js
* Update console error steps
* Add test scripts for new marquee variants.
- Marquee (large, standard) 
- Marquee (large, compact) 
- Marquee anchors 
- Marquee anchors (transparent) 
- Marquee background image focal point) 
Resolves: [MWPW-158314 ](https://jira.corp.adobe.com/browse/MWPW-158314 )
**Test URLs:**
- After: https://marquee-test-updates--milo--adobecom.hlx.page/?martech=off
=> [MWPW-158314 : NALA] Add nala tests for additional marquee variants

libs/blocks/global-navigation/global-navigation.js
Due to our specific viewport breakpoints, PEP was being served to iPhone/iPad users browsing with their device held horizontally. This lead to a requirement for serving PEP only to desktop users. 
- We've used the same check MEP uses to determine if the user is on a mobile device or not
- We haven't imported the MEP check since, in pages where personalization is turned off, the browser would needlessly download and parse the personalization.js just for the User Agent check.
- Requirements for MEP and PEP won't necessarily move in lockstep, so it makes sense to maintain our own list of User Agents we'll check for in PEP.
Note: As [MDN recommends](https://developer.mozilla.org/en-US/docs/Web/HTTP/Browser_detection_using_the_user_agent#avoiding_user_agent_detection), it's preferable to not …
=> MWPW-155489 [PEP] Add device type as PEP criteria

libs/features/jarvis-chat.js, test/features/jarvis-chat/jarvis-chat.test.js
Updated Jarvis chat client URL for the a.com stage environment.
Resolves: [MWPW-156443](https://jira.corp.adobe.com/browse/MWPW-156443)
Test URLs:
After: https://mwpw-156443--milo--akanshaa-18.aem.page/?martech=off
QA: https://main--cc--adobecom.hlx.page/products/adobe-extension-builder?milolibs=mwpw-156443--milo--akanshaa-18
=> Jarvis stage URL for Acom stage env

libs/blocks/region-nav/region-nav.js, test/blocks/region-nav/mocks/regions.html, test/blocks/region-nav/region-nav.test.js
This makes a few adjustments to the link interaction logic inside the region nav modal. Currently, there are a few scenarios where we might confuse users. Clicking on a link makes a HEAD fetch request to check whether the analog page exists on the newly chosen locale. If so, the user gets redirected to that page. Otherwise, they are being redirected to the root of the newly chosen locale. Most other interactions with region nav links can lead to unexpected outcomes, which this PR tries to minimize.
| **Scenario** | Current behavior | Updated behavior |
| ------------- | ------------- | ------------- |
| **User clicks the link** | gets redirected to the equivalent page or locale root, international cookie set | gets redirected to the equivalent page or locale root, international cookie set …
=> [MWPW-153616] Update 404 links in region selector

libs/blocks/tag-selector/tag-selector.js
* Prevent prototype pollution detected by kodiak by using `Object.create(null)` and controlled keys.
* Add lana message for consumer tag errors.
Resolves: [MWPW-144360](https://jira.corp.adobe.com/browse/MWPW-144360)
**Test URLs:**
- Before: https://main--milo--adobecom.hlx.page/tools/tag-selector/?martech=off
- After: https://bmarshal-tag-prototype--milo--adobecom.hlx.page/tools/tag-selector?martech=off
=> MWPW-144360 Prototype pollution tag selector

libs/blocks/chart/chart.js
* Fixes duplicate percent in donut chart tooltip. Now, the automatically calculated percent will only show if the unit isn't percent ("%").
Resolves: [MWPW-159236](https://jira.corp.adobe.com/browse/MWPW-159236)
**Test URLs:**
Milo:
- Before: https://main--milo--adobecom.hlx.page/drafts/methomas/chart-donut-percent
- After: https://methomas-donut-percent--milo--adobecom.hlx.page/drafts/methomas/chart-donut-percent?martech=off
Bacom:
- Before: https://main--bacom--adobecom.hlx.live/resources/holiday-shopping-report
- After: https://main--bacom--adobecom.hlx.live/resources/holiday-shopping-report?milolibs=methomas-donut-percent
=> MWPW-159236 Fix duplicate percent in donut chart tooltip

libs/blocks/global-navigation/global-navigation.js, libs/navigation/navigation.js, test/navigation/bootstrapper.test.js
* With recent release, Jarvis is not under help component in Unav. Added jarvis as a child component.
* Make appID of unav's notifications component configurable
* Unav has a isSectionDividerRequired feature which gnav needs to support. Global navigation component will take it in the config and pass it to unav config
Resolves: [MWPW-159217](https://jira.corp.adobe.com/browse/MWPW-159217) and [MWPW-159143](https://jira.corp.adobe.com/browse/MWPW-159143)
**Test URLs:**
- After: https://unav-jarvis--milo--adobecom.hlx.page/?martech=off
**Qa**: https://adobecom.github.io/nav-consumer/navigation.html?env=stage&navbranch=unav-jarvis&showUnavSectionDivider=true
=> Add support for Jarvis through Unav and make appID of notifications configurable

libs/deps/mas/mas.js, libs/deps/mas/merch-card.js, libs/deps/mas/plans-modal.js, libs/features/mas/web-components/src/global.css.js
For RTL, make callout texts right aligned
Resolves: [MWPW-159265](https://jira.corp.adobe.com/browse/MWPW-159265)
**Test URLs:**
- Before: https://main--milo--adobecom.hlx.page/ae_ar/drafts/mili/kitchen-sink/merch-card
- After: https://MWPW-159265--milo--rohitsahu.hlx.page/ae_ar/drafts/mili/kitchen-sink/merch-card
=> [MWPW-159265] Callout text in RTL not properly aligned

libs/blocks/merch/merch.js, test/blocks/merch/merch.test.js
Reverts https://github.com/adobecom/milo/pull/2906 which is causing prices and CTAs to not resolve in Safari browsers.
Resolves: [MWPW-159404](https://jira.corp.adobe.com/browse/MWPW-159404)
**Test URLs:**
- Before:https://main--milo--adobecom.hlx.page/docs/library/kitchen-sink/merch-card
- After: https://MWPW-157555-revert--milo--adobecom.hlx.page/docs/library/kitchen-sink/merch-card?martech=off
=> Reverts MWPW-157555: Causing prices and CTAs to fail in Safari

libs/blocks/media/media.css
We added support for a new class in the media block: 'space-between', which when added will add additional space between the right and left parts of the media block, see [Figma](https://www.figma.com/proto/Bvg6OTmb7WnzN8RcA3VrSC/Q4-24-BF%2FCM-All-Apps-Promo?page-id=0%3A1&node-id=10010-40784&viewport=3084%2C3842%2C0.07&t=emC0Wy3D2f49ELvt-1&scaling=scale-down-width&content-scaling=fixed&starting-point-node-id=1%3A2&disable-default-keyboard-nav=1).
Updated authoring documentation: https://main--milo--mirafedas.hlx.page/docs/authoring/promotions/delayed-modal
Resolves: [MWPW-159157](https://jira.corp.adobe.com/browse/MWPW-159157)
**Test URLs:**
- Before: https://main--cc--adobecom.hlx.page/products/aftereffects/free-trial-download?instant=2024-11-15T14:00:00.000Z 
- After: …
=> MWPW-159157: Update modal to account for new image size

libs/blocks/global-navigation/global-navigation.js, test/blocks/global-navigation/test-utilities.js
We now do `await gnav.init()` so that `onReady` is called only when `gnav.init` is finished executing
Resolves: [MWPW-159197](https://jira.corp.adobe.com/browse/MWPW-159197) [MWPW-159364](https://jira.corp.adobe.com/browse/MWPW-159364)
Test URLs:
After: https://await-gnav-init--milo--sharmrj.hlx.page/?martech=off
QA: https://adobecom.github.io/nav-consumer/navigation.html?env=stage&navbranch=await-gnav-init
Added changes from: https://github.com/adobecom/milo/pull/2963
=> MWPW-159197 Invoke onReady of standalone gnav when it is rendered #2962

libs/blocks/adobetv/adobetv.js, libs/blocks/figure/figure.js, libs/blocks/marquee/marquee.js, libs/blocks/video/video.js, libs/utils/decorate.js, test/blocks/adobetv/adobetv.test.js, test/blocks/adobetv/mocks/body.html, test/blocks/figure/figure.test.js, test/blocks/figure/mocks/body.html, test/blocks/marquee/marquee.test.js, test/blocks/video/mocks/body.html, test/blocks/video/video.test.js
Follow up for the reverted PR https://github.com/adobecom/milo/pull/2849
Resolves: [MWPW-158776](https://jira.corp.adobe.com/browse/MWPW-158776)
This should still work: https://github.com/adobecom/milo/pull/1936
**Test URLs:**
Onhover play
- Before: https://main--milo--mokimo.hlx.live/drafts/ruchika/videoplay-onhover?martech=off
- After: https://marquee-cls--milo--mokimo.hlx.live/drafts/ruchika/videoplay-onhover?martech=off
Onviewport play
- Before: https://main--milo--mokimo.hlx.live/drafts/siva/products/videoplay-onviewport?martech=off
- After: https://marquee-cls--milo--mokimo.hlx.live/drafts/siva/products/videoplay-onviewport?martech=off
Only desktop (mobile should not load the video for perf reasons)
- Before: https://main--milo--mokimo.hlx.live/drafts/seanchoi/marquee-video?martech=o …
=> MWPW-158776 Fix video CLS 

libs/blocks/hero-marquee/hero-marquee.css, libs/blocks/hero-marquee/hero-marquee.js, libs/utils/decorate.js, test/blocks/hero-marquee/mocks/body.html
FYI: This a repost from [reverted PR](https://github.com/adobecom/milo/pull/2905#event-14314262936) due to some issues seen w/ bg images not showing. Testing pages didn't have these examples initially so i've added em. Sorry for the bump. :) 
---
As and author in a milo project using a [hero-marquee]
I want to use this block with out a minimal height so the block has a natural height based on content.
I want to use this block in a masonry grid w/ the variant `full-width` and not have the extra left/right padding seen in this scenario.
Example screenshot - Notice the block height is huge, the l/r padding is causing the block to go outside its bounds.
Fixed
Add a no-min-height variant to the hero-marquee.
Address padding issue on hero-block. Erroneously comes from the has-bg class being …
=> MWPW-157888 - Hero marquee w/ no-min-height and no l/r padding when using a full-width variant in masonry(repost)

libs/utils/utils.js
Resolves: 
- [MWPW-158407](https://jira.corp.adobe.com/browse/MWPW-158407)
- [MWPW-158461](https://jira.corp.adobe.com/browse/MWPW-158461)
- [MWPW-158404](https://jira.corp.adobe.com/browse/MWPW-158404)
- [MWPW-158406](https://jira.corp.adobe.com/browse/MWPW-158406)
- [MWPW-158408](https://jira.corp.adobe.com/browse/MWPW-158408)
**Test URLs:**
- Before: https://main--milo--adobecom.hlx.page?martech=off&georouting=off
- After: https://MWPW-158407--milo--adobecom.hlx.page?martech=off&georouting=off
**Consumer test w/ real case:**
- Before: https://main--homepage--adobecom.hlx.page/homepage/index-loggedout?lanadebug=1
- After: https://main--homepage--adobecom.hlx.page/homepage/index-loggedout?lanadebug=1&milolibs=MWPW-158407
=> MWPW-158407, 158404, 158406, 158408, 158461: Ignoring decorateMeta if the metadata is from promo.

libs/blocks/graybox-promote/components/graybox-promote-lit.js, libs/tools/sharepoint/login.js, libs/tools/sharepoint/msal.js
This PR updates the Graybox promote to fetch the Milo config from the current .hlx.page origin of the UI, instead of .hlx.live, which previously failed due to authentication issues.
Resolves: [MWPW-159701](https://jira.corp.adobe.com/browse/MWPW-159701)
Before: https://grayboxui--milo--adobecom.hlx.page/drafts/rbogos/page-default?martech=off
After: https://mwpw-159701-milo-config--milo--robert-bogos.hlx.page/drafts/rbogos/page-default?martech=off
=> [MWPW-159701] [Graybox] Cannot read the milo config when behind auth

libs/blocks/hero-marquee/hero-marquee.css, libs/blocks/hero-marquee/hero-marquee.js, test/blocks/hero-marquee/mocks/body.html
Reverts adobecom/milo#2923
Before: https://main--cc--adobecom.hlx.page/creativecloud/business/teams/lush?milolibs=stage
After: https://main--cc--adobecom.hlx.page/creativecloud/business/teams/lush?milolibs=revert-2923-rparrish-hero-bg-fix-2
Before: - https://stage--milo--adobecom.hlx.page?martech=off
After: - https://revert-2923-rparrish-hero-bg-fix-2--milo--adobecom.hlx.page?martech=off
=> Revert "MWPW-157888 - Hero marquee w/ no-min-height and no l/r padding when using a full-width variant in masonry(repost)"

libs/navigation/navigation.css
Added a CSS class for full-width GNAV on Adobe home, applied from tablet size and above.
Resolves: [MWPW-159129](https://jira.corp.adobe.com/browse/MWPW-159129)
**Test URLs:**
- After: https://mwpw-159129--milo--deva309.hlx.page/?martech=off
QA:
https://adobecom.github.io/nav-consumer/navigation-full-width.html?env=stage&navbranch=mwpw-159129&authoringpath=/federal/test-website
=> [MWPW-159129] - Add full width GNAV css for adobe home

libs/features/personalization/personalization.js, test/features/personalization/parseNestedPlaceholders.test.js
- Handle a case where there are not placeholders available in replacePlaceholders() function and prevent the page from throwing an error
Resolves: [MWPW-159328](https://jira.corp.adobe.com/browse/MWPW-159328)
Steps to QA: 
Check the console.logs of the Before and After links. Before will include "MEP Error: TypeError: Cannot read properties of undefined (reading 'free-trial')" and After will not.
**Test URLs:**
- Before: https://main--cc--adobecom.hlx.page/drafts/suhjain/vivanchanges/photoshop?mep=%2Fdrafts%2Fsuhjain%2Fvivanchanges%2Fphotoshop.json--phone+%26+not+photoshop-any%2C+phone+%26+not+cc-all-apps-any
- After: https://main--cc--adobecom.hlx.page/drafts/suhjain/vivanchanges/photoshop?mep=%2Fdrafts%2Fsuhjain%2Fvivanchanges%2Fphotoshop.json--phone+%26+not+photoshop-any%2C+phone+%26+no …
=> [MWPW-159328] handle a case where there are not placeholders available

libs/utils/decorate.js
**Clone of https://github.com/adobecom/milo/pull/3009 which went into stage**
Fixes quiz video marquees
Resolves: https://jira.corp.adobe.com/browse/MWPW-159903
**Test URLs:**
- After: https://main-fix-quiz-marquee--milo--mokimo.hlx.page/?martech=off
Quiz Marquees
Before: https://main--cc--adobecom.hlx.page/cc-shared/fragments/uar/marquee/illustrator?debug=quiz-results
After: https://main--cc--adobecom.hlx.page/cc-shared/fragments/uar/marquee/illustrator?debug=quiz-results&milolibs=main-fix-quiz-marquees--milo--mokimo
=> [MWPW-159903] Fix quiz video marquees (#3009)

CODEOWNERS
Currently we have looping in a group of [20 people](https://github.com/orgs/adobecom/teams/admins) within basically *every* milo PR, which creates a lot of spam and stops us from seeing messages we are _actually_ looped in on.
**Test URLs:**
- After: https://remove-admins-from-code-owners--milo--mokimo.hlx.page/?martech=off
=> Remove @adobecom/admins from codeowners

.github/workflows/merge-to-stage.js
Seems like this [workflow run](https://github.com/adobecom/milo/actions/runs/11436722238/job/31814762385) errors out `TypeError: Cannot read properties of null (reading 'length')` ... we always have a string for the body, so I'm not sure how this is happening, but let's safeguard this. Related to https://github.com/adobecom/milo/pull/3062
Resolves: [MWPW-157289](https://jira.corp.adobe.com/browse/MWPW-157289)
**Test URLs:**
- After: https://fix-stage-process--milo--mokimo.hlx.page/?martech=off
=> Fix the merge to stage process

libs/navigation/navigation.js
* Add `stageDomainsMap` to the standalone gnav configuration to ensure the `convertStageLinks` function works properly for standalone nav consumers
Resolves: [MWPW-160204](https://jira.corp.adobe.com/browse/MWPW-160204)
**Test URLs:**
- After: https://MWPW-160204--milo--adobecom.hlx.page/?martech=off
**QA:**
- https://adobecom.github.io/nav-consumer/navigation.html?authoringpath=/federal/home&navbranch=MWPW-160204
=> Adding support for environment aware link feature to standalone Gnav

libs/blocks/section-metadata/sticky-section.js, libs/utils/decorate.js
As an author, I would like to be able to have the current Aside notification functionalities to be available in the new Notification block.
**Bugs:**
**_1 & 2_** the `notification.ribbon` block (when nested in section with `.sticky-bottom` style) is not using the same default functionality as the original `aside.promobar` block that it was created to replace.
1. The notification ribbon block should hide when the user scrolls to the bottom of the page.
2. The notification ribbon block should only show up once the user scrolls to the element position in the document.
3. The multi view port decorator wasn't setup to differentiate between a two column layout and a three column layout.
**Solutions:**
1. Adjusted selector in the section for sticky functionality to query for all notifications …
=> MWPW-158014 - [Notification] bugs

libs/blocks/fragment/fragment.js, test/blocks/fragment/fragment.test.js, test/blocks/fragment/mocks/fragments/frag-b.plain.html, test/blocks/fragment/mocks/fragments/frag-c.plain.html, test/blocks/fragment/tree.test.js
Detecting recursive fragments had a very simplistic check, but would incorrectly mark a fragment as recursive and therefore not load it.  This updates the algo to explicitly look up the fragment loading tree and see if the fragment about to load will end up loading the current fragment - aka start an infinite fragment loading loop.
This was happening when a fragment that has a nested fragment is used in different sections of a page.  In this case  the photoshop card fragment was being used multiple times in different sections (each tab is in its own section).
Resolves: [MWPW-159291](https://jira.corp.adobe.com/browse/MWPW-159291)
---
Circular Fragment Verification:
- Before: https://main--milo--adobecom.hlx.page/drafts/cpeyer/load-circ-frag?martech=off
- After: …
=> MWPW-159291 Fix fragment recursive check algo

libs/blocks/global-navigation/global-navigation.js, libs/navigation/navigation.css, test/blocks/global-navigation/global-navigation.test.js, test/blocks/global-navigation/test-utilities.js
MWPW-160014 : Search container for Standalone Gnav on devices
Resolves: [MWPW-160014](https://jira.corp.adobe.com/browse/MWPW-160014)
**Test URLs:**
- After: https://ahsearch--milo--adobecom.hlx.page/?martech=off
**QA:**
- https://adobecom.github.io/nav-consumer/navigation.html?env=stage&navbranch=ahsearch&showUnavSectionDivider=true&searchEnabled=on
=> MWPW-160014 : Search container for Standalone Gnav on devices

libs/blocks/how-to/how-to.css, libs/blocks/how-to/how-to.js, libs/styles/styles.css, libs/utils/decorate.js, test/blocks/how-to/how-to.test.js, test/blocks/how-to/mocks/body.html
* How-to block video support for mp4 and Adobe TV
Resolves: [MWPW-157618](https://jira.corp.adobe.com/browse/MWPW-157618)
**Test URLs:**
- https://mwpw-157618--milo--joaquinrivero.hlx.page/
HOW TO
- Before: https://main--dc--adobecom.hlx.page/drafts/rivero/jpg-to-pdf?martech=off
- After: https://main--dc--adobecom.hlx.page/drafts/rivero/jpg-to-pdf?martech=off&milolibs=mwpw-157618--milo--joaquinrivero
Onhover play
- Before: https://main--milo--adobecom.hlx.live/drafts/ruchika/videoplay-onhover?martech=off
- After: https://main--milo--adobecom.hlx.live/drafts/ruchika/videoplay-onhover?martech=off&milolibs=mwpw-157618--milo--joaquinrivero
Onviewport play
- Before: https://main--milo--adobecom.hlx.live/drafts/siva/products/videoplay-onviewport?martech=off
- After: …
=> MWPW-157618: How-to block video support for mp4 and adobetv

libs/features/google-login.js, libs/scripts/delayed.js, libs/utils/utils.js, test/features/google-login/google-login.test.js, test/scripts/delayed.test.js
Resolves: [MWPW-158182](https://jira.corp.adobe.com/browse/MWPW-158182)
**Test URLs:**
- After: https://vhargrave-MWPW-142878-events--milo--adobecom.hlx.page/?martech=off
This branch was originally built to listen to the two events to load both additional analytics and then get the primary cta url for google yolo which we redirect to.
Now after discussion with Rareș & Okan we've decided to just add a callback which resolves the url when necessary for the google yolo login. 
- https://github.com/adobecom/express-milo/pull/56/files
- https://main--express-milo--adobecom.hlx.page/express/colors/blue?milolibs=vhargrave-MWPW-142878-events
=> MWPW-158182 add callback of URL for google yolo 

libs/features/personalization/personalization.js, test/features/personalization/parseNestedPlaceholders.test.js
* added handling of "no placeholders" case for parsePlaceholders()
Resolves: [MWPW-152455](https://jira.corp.adobe.com/browse/MWPW-152455)
QA Instructions: The before link has an error message the after link does not:
MEP Error parsing manifests: TypeError: undefined is not iterable (cannot read property Symbol(Symbol.iterator))
**Test URLs:**
- Before: https://main--cc--adobecom.hlx.page/drafts/mepdev/fragments/2024/q4/placeholders/placeholders
- After: https://main--cc--adobecom.hlx.page/drafts/mepdev/fragments/2024/q4/placeholders/placeholders?milolibs=MWPW-152455
Psi-check: https://mwpw-152455--milo--adobecom.hlx.page/?martech=off
=> MWPW-152455 added handling of "no placeholders" case for parsePlaceholders()

libs/blocks/caas-config/caas-config.js, libs/blocks/caas/utils.js, test/blocks/caas-config/caas-config.test.html, test/blocks/caas-config/expectedConfigs/defaultConfig.js, test/blocks/caas/caas.test.html, test/blocks/caas/utils.test.js
- Add "Partial Load Enabled" checkbox to Basics panel
- Add "Partial Load Count" input field when partial load is enabled
- Update config object to include partialLoadWithBackgroundFetch settings
- add tests for partial load settings
- add test for partial load initialization
This feature allows authors to optimize page load times for large card collections by initially loading a subset of cards and fetching the rest in the background. 
Authors can enable partial loading and specify the initial load count through the CaaS configurator tool.
Resolves: [MWPW-150610](https://jira.corp.adobe.com/browse/MWPW-150610)
- Before: https://main--milo--adobecom.hlx.page/drafts/sanrai/foo?martech=off
- After: https://MWPW-150610--milo--adobecom.hlx.page/drafts/sanrai/foo?martech=off
=> MWPW-150610: implement partial load options in configurator

libs/blocks/global-navigation/global-navigation.js, libs/blocks/global-navigation/utilities/utilities.js, libs/navigation/bootstrapper.js, libs/navigation/navigation.css, libs/navigation/navigation.js, test/blocks/global-navigation/global-navigation.test.js, test/blocks/global-navigation/mocks/navigation-with-custom-links.plain.js, test/navigation/bootstrapper.test.js, test/navigation/mocks/gnav.html
Things covered as part of this PR:
1) Add config as `layout` for supporting full width in Standalone GNAV.
2) Add config for `noBorder` for removing border for adobe home.
3) Relative url href removal added for custom Links
4) Add Jarvis call for standalone GNAV
Resolves: 
[MWPW-159905](https://jira.corp.adobe.com/browse/MWPW-159905)
[MWPW-160508](https://jira.corp.adobe.com/browse/MWPW-160508)
**Test URLs:**
- After: https://mwpw-159905--milo--deva309.hlx.page/?martech=off
QA:
- https://adobecom.github.io/nav-consumer/navigation.html?env=stage&navbranch=mwpw-159905&authoringpath=/federal/test-website&layout=fullWidth (full width)
- https://adobecom.github.io/nav-consumer/navigation.html?env=stage&navbranch=mwpw-159905&authoringp …
=> [MWPW-159905] - Add config for full width and no border along with jarvis fix for standalone GNAV

libs/blocks/modal/modal.js, test/blocks/modals/modals.test.js
Removing a modal fragment does not prevent the creation of the overlay. This code checks if the modal fragment is removed by mep and exist function if so.
Resolves: [MWPW-148185](https://jira.corp.adobe.com/browse/MWPW-148185)
**Test URLs:**
- Before: https://main--cc--adobecom.hlx.page/drafts/mepdev/fragments/2024/q4/mepsuppressmodal/?martech=off
- After: https://main--cc--adobecom.hlx.page/drafts/mepdev/fragments/2024/q4/mepsuppressmodal/?martech=off&milolibs=modalsuppression
- Psi Check: https://modalsuppression--milo--adobecom.hlx.page/?martech=off
=> MWPW-148185 [MILO][MEP] Promo modal suppression mechanism

libs/navigation/navigation.js
* Added support to convert links authored with _creativecloud.adobe.com_ to _stage.creativecloud.adobe.com_ on stage environment
Resolves: [MWPW-160934](https://jira.corp.adobe.com/browse/MWPW-160934)
**Test URLs:**
- After: https://cc-stage-link--milo--adobecom.hlx.page/?martech=off
**QA:**
https://adobecom.github.io/nav-consumer/navigation.html?authoringpath=/federal/dev/blaishram&customlinks=home,discover&navbranch=cc-stage-link
=> Adding creative cloud stage link to stageDomainsMap

libs/deps/mas/mas.js, libs/deps/mas/merch-card.js, libs/features/mas/web-components/src/merch-card.css.js
centre align "secure transactions" in footer
Resolves: [MWPW-155061](https://jira.corp.adobe.com/browse/MWPW-155061)
Test URLs:
Before: https://main--milo--adobecom.hlx.page/drafts/rosahu/footeralignement
After: https://mwpw-155061--milo--rohitsahu.hlx.page/drafts/rosahu/footeralignement
=> [MWPW-155061] Secure transaction label is not center aligned with CTA 

libs/scripts/scripts.js
This PR removes the fork specific configuration from the `stageDomainsMap`
Resolves: [MWPW-159901](https://jira.corp.adobe.com/browse/MWPW-159901)
No QA nedded
- Before:  https://stage--milo--adobecom.hlx.page/drafts/rbogos/env-relative-urls?martech=off
- After: https://mwpw-159901--milo--robert-bogos.hlx.page/drafts/rbogos/env-relative-urls?martech=off
=> [MWPW-159901] Removed testing code

libs/martech/attributes.js, libs/martech/attributes.md
* support for .no-track to skip addition of daa-ll
* information on how to opt out added to .md
Resolves: [MWPW-160447](https://jira.corp.adobe.com/browse/MWPW-160447)
**Test URLs:**
- After: https://daa-ll-opt-out--milo--colloyd.hlx.page/drafts/colloyd/quiz/?martech=off
Note: This addition has no effect until the .no-track is added to a link or button inside a block. This change is strictly to support that opt-out class, and can't be tested using the supplied urls. For clarity, I've opted to keep the changes to martech/attributes separate from changes to quiz blocks. A subsequent PR will be forthcoming to add .no-track to quiz blocks that need the opt out.
For reference, the ticket associated with quiz …
=> Opt-out class to prevent automatic addition of daa-ll

libs/features/personalization/personalization.js, test/features/personalization/actions.test.js, test/features/personalization/mocks/actions/manifestCustomAction.json
* check for and update selector and content if it's a federal link for in-block selectors
Resolves: [MWPW-148129](https://jira.corp.adobe.com/browse/MWPW-148129)
QA instructions: if you extend the gnav's first menu (Creativity & Design) it will now match the 2nd menu's content (PDF & E-signatures)
**Test URLs:**
- Before: https://main--cc--adobecom.hlx.page/drafts/mepdev/fragments/2024/q4/mepgnavfedlink/
- After: https://main--cc--adobecom.hlx.page/drafts/mepdev/fragments/2024/q4/mepgnavfedlink/?milolibs=mepgnavfedlink
- Psi-check: https://mepgnavfedlink--milo--adobecom.hlx.page/?martech=off
=> MWPW-148129 [MILO][MEP][GNAV] Able to use select by url feature with federated link

libs/blocks/notification/notification.js, libs/blocks/ost/ctaTextOption.js, test/blocks/ost/textOption.test.js
Add "Save now" to the OST CTAs options
Ignore the below urls for testing. Provide adobe.com token to test the functionality in OST.
Before:
After:
Resolves: [MWPW-160862](https://jira.corp.adobe.com/browse/MWPW-160862)
Test URLs:
- Before: https://main--milo--adobecom.hlx.page/drafts/rosahu/innovatex/badgealign
- After: https://mwpw-160862--milo--rohitsahu.hlx.page/drafts/rosahu/innovatex/badgealign
=> [MWPW-160862] [Milo OST] Add 'Save now' to dropdown of CTA text options

libs/blocks/global-navigation/global-navigation.js, libs/features/dynamic-navigation/dynamic-navigation.js, libs/features/dynamic-navigation/status.css, libs/features/dynamic-navigation/status.js, libs/utils/utils.js, test/features/dynamic-nav/dynamicNav.test.js, test/features/dynamic-nav/mocks/status.html, test/features/dynamic-nav/status.test.js
* Adds a status button to appear in the nav to inform content QA and QA whether or not the Dynamic Nav is active and to provide additional information about Dynamic Nav and it's settings. 
* The experience is set for tablet and up, since the core user is QA. 
Context: 
The milo repo does not have the dynamicNavKey in the config, so the first two links will not show the feature.
Resolves: [MWPW-157147](https://jira.corp.adobe.com/browse/MWPW-157147)
**Test URLs:**
- Before: https://main--milo--jasonhowellslavin.hlx.page/drafts/slavin/dynamic-nav/bacom-sample-on?martech=off
- After: https://dynamic-nav-status-button--milo--jasonhowellslavin.hlx.page/drafts/slavin/dynamic-nav/bacom-sample-on?martech=off
Bacom
- Before: https://main--bacom--adobecom.hlx.page/drafts/slavin/dynamic-nav/aem-rtcdp …
=> MWPW-157147: Dynamic Nav Status Button

libs/utils/lana.js, libs/utils/lana.md, test/utils/lana.test.js
The `lana-sample` query param will override any sample rate defined elsewhere.  Setting it to "100" will force lana to send everything to splunk.
Resolves: [MWPW-159555](https://jira.corp.adobe.com/browse/MWPW-159555)
**Test URLs:**
- After: https://mwpw-159555--milo--adobecom.hlx.page/?martech=off
=> MWPW-159555 Add support for lana-sample query param

libs/blocks/hero-marquee/hero-marquee.css, libs/blocks/hero-marquee/hero-marquee.js, libs/styles/breakpoint-theme.css, libs/styles/styles.css, test/blocks/hero-marquee/mocks/body.html
**1) Hero marquee doesn't render as expected when authored with a split content row and an empty first cell.** 
The hero marquee copy area can be authored w/ a two column row (split-cell), indicating that there is a content division of either `asset | copy` or `empty(whitespace) | copy` etc. When the first cell in this row is empty, the content appears on the left when it should stay divided and appear in the authored right position. 
Solution: display `.empty-asset:empty` as block, instead of 'hidden' 
Resolves: [MWPW-159651](https://jira.corp.adobe.com/browse/MWPW-159651) - [Hero marquee] Main content can't be placed on right correctly
**Test URLs:**
- Before: https://main--milo--adobecom.hlx.page/drafts/vmorel/hero-marquee-content-on-right?martech=off
- After: …
=> MWPW-159651 && MWPW-160196 - [Hero marquee] bug fixes

libs/blocks/modal/modal.css, libs/features/georoutingv2/georoutingv2.css, libs/features/georoutingv2/georoutingv2.js
Georouting modal loading is being controlled by 2 css files - modal and georouting v2.
The georouting v2 wrapper has content and close button but the close button css if added in the modal css.
When modal loads there are additional shift in the top left positioning and close button display along with wrapper being displayed. The loading step looks somewhat like this -
Making the georouting modal keep the content hidden till the modal is ready to render. This will avoid cls due to close button
Results from local test on the same test page with cls reducing to 0
Resolves: [MWPW-156242](https://jira.corp.adobe.com/browse/MWPW-156242)
**Test URLs:**
- Before: https://main--milo--adobecom.hlx.page/drafts/mathuria/georouting?georouting=on&martech=off
- Before: …
=> MWPW-156242 | [Performance] Georouting modal creating cls

libs/blocks/graybox/graybox.css
* ensure that the graybox block will never be seen, regardless of page content or setup
Resolves: [MWPW-160469](https://jira.corp.adobe.com/browse/MWPW-160469)
**Test URLs:**
- Before: https://main--milo--adobecom.hlx.page/drafts/colloyd/graybox/graybox-masonry?martech=off
- After: https://graybox-display-specificity-fix--milo--colloyd.hlx.page/drafts/colloyd/graybox/graybox-masonry?martech=off
Note: This small fix will ensure that the graybox block is always properly hidden. This is necessary if a graybox block is placed in such a way that the outside css overrides diplay with more specificity, such as if the block is placed inside masonry, where its display is then overridden from display: none, to display: grid.
=> Graybox display specificity fix

libs/blocks/article-header/article-header.js
* Adds tabindex to the properties used to create the social share icons to ensure users can navigate via keyboard. I checked with voiceover as well to ensure the correct alt text was being represented. 
Resolves: [MWPW-160233](https://jira.corp.adobe.com/browse/MWPW-160233)
**Test URLs:**
- Before: https://main--bacom-blog--adobecom.hlx.live/blog/the-latest/samsung-proves-real-time-data-is-a-catalyst-for-better-customer-experiences?martech=off
- After: https://article-header-a11y--bacom-blog--adobecom.hlx.live/blog/the-latest/samsung-proves-real-time-data-is-a-catalyst-for-better-customer-experiences?martech=off
=> MWPW-160233: Adding tabindex to social share icons

libs/blocks/bulk-publish-v2/services.js, libs/blocks/preflight/panels/general.js, libs/blocks/preflight/panels/seo.js, libs/features/personalization/preview.js, libs/utils/sidekick.js, libs/utils/utils.js
* Adds support for [AEM Next-Gen Sidekick](https://chromewebstore.google.com/detail/aem-sidekick-nextgen/igkmdomcgoebiipaifhmpfjhbjccggml?pli=1) (AKA `<aem-sidekick>`)
* Backwards compatible with current AEM Sidekick (AKA `<helix-sidekick>`)
Resolves: [MWPW-159791](https://jira.corp.adobe.com/browse/MWPW-159791)
Note: The next-gen sidekick doesn't appear to have an options page, so "edit" and "prod" plugins can't be tested until after release.
**Test URLs:**
- Before: https://main--milo--adobecom.hlx.page/drafts/methomas/send-to-caas?martech=off
- After: https://methomas-next-gen-sidekick--milo--adobecom.hlx.page/drafts/methomas/send-to-caas?martech=off
=> MWPW-159791 Support Next-Gen Sidekick

libs/blocks/media/media.css, libs/blocks/media/media.js
Small addition to https://github.com/adobecom/milo/pull/3021 to resolve the buttons being on top of eachother.
Before:
After:
Resolves: [MWPW-160834](https://jira.corp.adobe.com/browse/MWPW-160834)
**Test URLs:**
Milo
- Before: https://main--milo--adobecom.hlx.page/drafts/sara/media?martech=off
- After: https://mwpw-160061-layout--milo--mokimo.hlx.page/drafts/sara/media?martech=off
CC
- Before: https://main--cc--adobecom.hlx.page/in/creativecloud/roc/mobile-apps?milolibs=stage
- After: https://main--cc--adobecom.hlx.page/in/creativecloud/roc/mobile-apps?milolibs=mwpw-160061-layout--milo--mokimo
=> MWPW-160834: Clickable App and Playstore links

libs/utils/utils.js
* After DC frictionless pages are switched to using the IMS guest token, we observed a small percentage of users may get an IMS timeout error. In the past we didn't log the error. The investigation is in [MWPW-158350](https://jira.corp.adobe.com/browse/MWPW-158350).  
* This change allows a consumer app to adjust the IMS timeout value. The DC team can fine tune the value to reduce the error rate.
Resolves: [MWPW-159605](https://jira.corp.adobe.com/browse/MWPW-159605)
**Test URLs:**
- After: https://mwpw-159605--milo--adobecom.hlx.page/?martech=off
=> MWPW-159605 Allow consumer apps set IMS timeout value

libs/blocks/article-feed/article-feed.js, libs/blocks/library-config/library-config.js, libs/blocks/library-config/lists/blocks.js, libs/blocks/library-config/lists/icons.js, libs/blocks/library-config/lists/personalization.js, libs/blocks/library-config/lists/placeholders.js, libs/scripts/delayed.js, libs/templates/404/404.js, libs/utils/samplerum.js, libs/utils/utils.js, test/utils/samplerum.test.js
- Upgrade to the latest RUM and RUM Enhancer. As far as I can tell, no [production project](https://github.com/search?q=org%3Aadobecom+samplerum.observe&type=code) uses `rum.observe` which does not exist anymore after this upgrade. 
- Adds the block loading status to properly track blocks
- Ensure RUM data is properly captured to `https://rum.hlx.page/.rum`
Resolves: [MWPW-160590](https://jira.corp.adobe.com/browse/MWPW-160590)
**Test URLs:**
- After: https://upgrade-rum--milo--mokimo.hlx.page/?martech=off&rum=on
CC:
- Before:https://main--cc--adobecom.hlx.live/de/products/photoshop?mep=off&rum=on
- After: https://main--cc--adobecom.hlx.live/de/products/photoshop?milolibs=upgrade-rum--milo--mokimo&mep=off&rum=on
=> Upgrade to RUM V2.7.0

libs/blocks/preflight/panels/performance.js, libs/blocks/preflight/panels/seo.js, libs/blocks/preflight/preflight.css, libs/blocks/preflight/preflight.js, libs/utils/utils.js, test/blocks/preflight/panels/performance/mocks/marquee.html, test/blocks/preflight/panels/performance/performance.test.js, test/helpers/generalHelpers.js, web-test-runner.config.mjs
A few todo's here and there but the features and flow should work and this should be ready for feedback and a first batch of testing.
- Adds a new performance preflight tab
- adds new&polished performance docs: https://main--milo--adobecom.aem.page/docs/authoring/performance/ (Needs a bit more polishing and hands-on-advice)
Resolves: [MWPW-157715](https://jira.corp.adobe.com/browse/MWPW-157715)
Use the provided sample URLs, try to destroy the thing, close it, open it, open it on incognito, have pages with LCP, without, use production pages from bacom etc. to test this. I've encountered a lot of issues during development and I'm sure theres still many issues out there.
**Test URLs:**
- Before: https://main--milo--adobecom.hlx.page/drafts/osahin/preflight-performance/marquee-fragment?martech …
=> Added performance tab to the Preflight tool (#2773)

libs/blocks/merch/merch.js, libs/features/mas/commerce/test/settings.test.js, test/blocks/merch/merch.test.js
Fixes CLI parameter in checkout links in milo consumer projects like DC, CC.
Resolves: [MWPW-161191](https://jira.corp.adobe.com/browse/MWPW-161191)
Actual test URL (needs to be tested from milo consumer project): https://main--dc--adobecom.hlx.live/acrobat/features?milolibs=MWPW-161191--milo--adobecom
**Test URLs:**
- Before: https://main--milo--adobecom.hlx.page/docs/library/kitchen-sink/merch-card?martech=off
- After: https://MWPW-161191--milo--adobecom.hlx.page/docs/library/kitchen-sink/merch-card?martech=off
=> MWPW-161191:  Checkout cli parameter does not get rendered correctly

libs/utils/logWebVitals.js, test/utils/logWebVitalsUtils.test.js
Logs if the LCP Element is in Section One of the page.
Resolves: [MWPW-159561](https://jira.corp.adobe.com/browse/MWPW-159561)
**Test URLs:**
- After: https://mwpw-159561--milo--adobecom.hlx.page/?martech=off
=> MWPW-159561 Add lcpSectionOne metric to web vitals

nala/blocks/text/text.page.js
* Adds this.textBlocks and this.textIntroBlocks to enable a count()
* Adds headlineAlt and introHeadlineAlt for an alternate way to obtain the headline in a text block
* Adds a .nth to this.textIntro
this.textIntro = this.page.locator('.text.intro').nth(nth);
Resolves: [MWPW-161293](https://jira.corp.adobe.com/browse/MWPW-161293)
**Test URLs:**
- After: https://new-textblock-selectors--milo--adobecom.hlx.page/?martech=off
=> MWPW-161293 [MEP] add some selectors for the text blocks

libs/utils/utils.js
This exist before, and we are getting request by accessibility to added again for unity project
Defaults to empty alt tag on the image if no alt text is authored. Per accessibility best practices this declares the image as "decorative".
Resolves: [MWPW-159032](https://jira.corp.adobe.com/browse/MWPW-159032)
**Test URLs:**
- https://mwpw-159032-svg--milo--joaquinrivero.hlx.page/
- Before: https://main--dc--adobecom.hlx.page/acrobat/online/test/sign-pdf-projectunity?martech=off
- After: https://main--dc--adobecom.hlx.page/acrobat/online/test/sign-pdf-projectunity?martech=off&milolibs=MWPW-159032-svg--milo--joaquinrivero
=> MWPW-159032: Defaults to empty alt tag on the svg - Accessibility requirement

libs/features/placeholders.js, test/features/placeholders/placeholders.test.js
When we search for placeholders, we are looking for a pattern of text within double curly brackets.  However, when a placeholder is used inside a URL, the double curly brackets are URL encoded.
Example URL: https://main--cc--adobecom.hlx.page/cc-shared/fragments/trial-modals/product-labeledu#mini-plans-web-ctaproduct-label-card-sb
Becomes: /cc-shared/fragments/trial-modals/%7B%7Bproduct-label%7D%7D-edu#mini-plans-web-cta-%7B%7Bproduct-label%7D%7D-card-sb
I want to add support for these encoded brackets.
**QA instructions**
Check the first link for data-modal-path or data-modal-hash on the Free trial anchor. Placeholders will be unresolved. This should be fixed on the second link.
Resolves:  [MWPW-160239](https://jira.corp.adobe.com/browse/MWPW-160239)
**Test URLs:**
- Before: …
=> MWPW-160239 [MEP] Support searching for placeholders in URLs

libs/blocks/library-config/library-config.js
Hi, our `.hlx.live` page is protected with an access.live.allow rule in .config. and because of this we are not able to add our blocks to the library in sidekick. You can find more information here: https://github.com/orgs/adobecom/discussions/3121 
We found that there is a possibility to fetch library blocks data from custom url by adding `library` query param to library URL in `config.json`, but we found the bug in `library-config.js` and because of this bug, custom library URL will be fetched two times, and milo library data will be skipped. 
We propose solution that when `library` query param is present, additional blocks data will  be fetched from custom url specified in this param and then added to existing milo blocks. 
Resolves: …
=> MWPW-161174 fixed library query param

libs/blocks/modal/modal.js, libs/martech/attributes.js, test/blocks/modals/modals.test.js
Analytics are automatically added to main, but are modals outside of main? Modals should have analytics automatically added as well.
- Updated modal creation function to add analytics upon modal creation.
- Update martech function to accept a string or index as the analytic value.
Resolves: [MWPW-148000](https://jira.corp.adobe.com/browse/MWPW-148000)
QA instructions
Check Test modal for daa-lh values and links for daa-ll values. 
**Test URLs:**
- Before: https://main--cc--adobecom.hlx.page/drafts/mepdev/fragments/2024/q4/modalanalytics/marquee
- After: https://main--cc--adobecom.hlx.page/drafts/mepdev/fragments/2024/q4/modalanalytics/marquee?milolibs=modalanalytics
- Psi: https://modalanalytics--milo--adobecom.hlx.page/?martech=off
=> [MWPW-148000] [ANALYTICS] Add analytics to Modals

libs/blocks/global-navigation/utilities/keyboard/index.js
* Added client's search component class to exclude from getting it clicked on keydown
Resolves: [MWPW-161627](https://jira.corp.adobe.com/browse/MWPW-161627)
**Test URLs:**
- After: https://search-fix--milo--adobecom.hlx.page/?martech=off
Qa: https://www.stage.adobe.com/home?navbranch=search-fix
=> Adding client's search component class to exclude from getting it clicked on keydown

nala/features/commerce/commerce.spec.js
Fixing  failing promo code in Nala tests
- https://nala-updates--milo--afmicka.hlx.page/
=> [Nala] Fix failing promo code in Nala tests

libs/blocks/global-navigation/utilities/utilities.js
* Adding main menu placeholder
Resolves: [MWPW-161777](https://jira.corp.adobe.com/browse/MWPW-161777)
**Test URLs:**
- After: https://mobile-gnav-main-menu--milo--adobecom.hlx.page/?martech=off
Qa: https://main--federal--adobecom.hlx.page/federal/dev/blaishram/page?milolibs=mobile-gnav-main-menu&newNav=true
=> Adding main menu placeholder

libs/blocks/preflight/panels/seo.js
* Fixes console errors in preflight seo functionality when using next-gen sidekick
Resolves: [MWPW-160966](https://jira.corp.adobe.com/browse/MWPW-160966)
**Test URLs:**
- Before: https://main--milo--meganthecoder.hlx.page/drafts/methomas/send-to-caas
- After: https://preflight-errors--milo--meganthecoder.hlx.page/drafts/methomas/send-to-caas?martech=off
Note: Next-Gen sidekick is required to test
=> MWPW-160966 Fix next-gen sidekick preflight

libs/blocks/editorial-card/editorial-card.css, libs/blocks/editorial-card/editorial-card.js, test/blocks/editorial-card/editorial-card.test.js, test/blocks/editorial-card/mocks/body.html
This PR will add support to have only media in Editorial card. When there is no copy content in the editorial-card, the media will fill the container. 
Resolves: [MWPW-160719](https://jira.corp.adobe.com/browse/MWPW-160719)
**Test URLs:**
- Before: https://main--milo--adobecom.hlx.page/drafts/saugat/editorial-card/media-card?martech=off
- After: https://smalla-editorial-card-media-card--milo--adobecom.hlx.page/drafts/saugat/editorial-card/media-card?martech=off
=> [MWPW-160719] - Support media only in Editorial-Card

libs/blocks/global-navigation/global-navigation.css, libs/blocks/global-navigation/global-navigation.js, libs/blocks/global-navigation/utilities/utilities.js
* Added new design for localnav
* Added event listeners for button and headlines
* Added option to author first element's text of localnav(overview)
Resolves: [MWPW-159673](https://jira.corp.adobe.com/browse/MWPW-159673)
**Test URLs:**
- After: https://mobile-gnav-localnav--milo--adobecom.hlx.page/?martech=off
QA: 
- https://main--federal--adobecom.hlx.page/federal/dev/blaishram/page-with-localnav?milolibs=mobile-gnav-localnav&newNav=true
- Nested localNav -> https://stage--dc--adobecom.hlx.page/drafts/soujanya/integrations?milolibs=mobile-gnav-localnav&newNav=true
- Page without localnav -> https://main--federal--adobecom.hlx.page/federal/dev/blaishram/page?milolibs=mobile-gnav-localnav&newNav=true
=> Localnav design and event listeners

libs/styles/styles.css
This ensures that styling texts as Quotes in Word does not add additional spacing in the final UI.
**Context**: accessibility standards require that quoted text be marked as such by using the `blockquote` tag. This can be easily achieved by applying a `Quote` style in Word. However, doing so will result in additional spacing due to the element's default styles. We want to make sure the layout remains consistent with what we have on production today.
**Usage notes**: this concerns simple text or text blocks. The `quote` block in Milo automatically uses the correct markup.
**GWP notes**: authors will need to edit the non-compliant pages and mark the texts surrounded by quotes (`"..."`) as `Quote` in Word. The JIRA story should link to all the non-compliant pages.
**Testing notes**: I've set …
=> [MWPW-160948] Remove blockquote default spacing

libs/blocks/caas/utils.js, test/blocks/caas/utils.test.js
This PR introduces support for CaaS cards within the **environment-aware links** feature.
More info about the **environment-aware links** feature can be found in [this discussion](https://github.com/orgs/adobecom/discussions/2880).
Resolves: [MWPW-161098](https://jira.corp.adobe.com/browse/MWPW-161098)
Using the before and after urls, compare the links to which the CaaS cards are directing to. 
Conversions will be done relative to the `stageDomainsMap` set in [the consumer config](https://github.com/adobecom/milo/blob/stage/libs/scripts/scripts.js#L24L44).
**Before**
**After**
**Milo:**
- Before: https://main--milo--adobecom.hlx.page/drafts/rbogos/caas?martech=off
- After: https://mwpw-160399-caas-support--milo--robert-bogos.hlx.page/drafts/rbogos/caas?martech=off
=> [MWPW-161098] Environment-aware links support for CaaS

libs/blocks/brick/brick.css, libs/blocks/card-horizontal/card-horizontal.css, libs/blocks/global-footer/global-footer.css, libs/blocks/marquee-anchors/marquee-anchors.css, libs/blocks/text/link-farms.css, libs/styles/iconography.css, libs/styles/styles.css
Credits: this is largely based on @ryanmparrish's work [here](https://github.com/adobecom/milo/compare/stage...rparrish/links).
To comply with accessibility standards, we need to adapt link styles to be underlined. The story contains all the details, but here are some highlights:
- any blue link becomes blue and underlined, hover/focus state remains the same;
- any gray link stays gray and underlined, hover/focus state remains the same;
- no action needed for:
- CTAs;
- Gnav/Footer;
- larger elements that act as links.
- links that are part of a link farm receive double underline on hover/focus;
- for links inside headlines, underline and keep the headline's color.
This has a massive blast radius, as links are likely present on each and every adobe.com page, so please test thoroughly. To …
=> Global links underlined by default

libs/styles/styles.css
https://github.com/adobecom/milo/pull/3166 introduced an issue where the blue color is applied to links on focus and active. This change will remove the states and will only keep hover.
Resolves: [MWPW-145672](https://jira.corp.adobe.com/browse/MWPW-145672)
**Test URLs:**
- Before: https://main--milo--adobecom.hlx.page/docs/library/kitchen-sink/accordion?martech=off&georouting=off
- After: https://mwpw-145672-fix--milo--narcis-radu.hlx.page/docs/library/kitchen-sink/accordion?martech=off&georouting=off
Additional test URLs
- https://main--bacom--adobecom.hlx.page/products/real-time-customer-data-platform/rtcdp?milolibs=mwpw-145672-fix--milo--narcis-radu
- see previous PR for testing
=> [MWPW-145672] Change link color only on hover

libs/utils/sidekick-decorate.js, libs/utils/sidekick.js, libs/utils/utils.js, tools/sidekick/config.json
* Supports publish permissions in Next-Gen Sidekick
* Enables AEM EDS Publish Confirm option in Next-Gen Sidekick (https://github.com/adobe/aem-sidekick/pull/262)
Resolves: [MWPW-160292](https://jira.corp.adobe.com/browse/MWPW-160292)
**Test URLs:**
- Before: https://main--milo--adobecom.hlx.page/drafts/methomas/send-to-caas
- After: https://methomas-sk-publish--milo--adobecom.hlx.page/drafts/methomas/send-to-caas?martech=off
Notes:
- Next-Gen sidekick is required to test
- Publish confirmation functionality isn't testable on lower environments at this time
- To test permissions, you need to be added to the next-gen tab in the [permissions config](https://adobe.sharepoint.com/:x:/r/sites/adobecom/Shared%20Documents/milo/.milo/publish-permissions-config.xlsx?d=w09132f8c4cd24298aeac8d6edb0da …
=> MWPW-160292 Next gen sidekick publish button

libs/blocks/editorial-card/editorial-card.css
This PR will allow to have two up layout in mobile with `two-up-mobile`. 
Resolves: [MWPW-161698](https://jira.corp.adobe.com/browse/MWPW-161698)
**Test URLs:**
- Before: https://stage--milo--adobecom.hlx.page/drafts/saugat/editorial-card/editorial-card-2-up?martech=off
- After: https://smalla-editorial-card-2-up--milo--adobecom.hlx.page/drafts/saugat/editorial-card/editorial-card-2-up?martech=off
Before:
After:
=>  [MWPW-161698] - Add two up in mobile for Editorial Card

libs/features/seotech/README.md, libs/features/seotech/seotech.js, test/features/seotech/seotech.test.js, test/utils/utils.test.js
Update `seotech-video-url` feature to use new version of API endpoint behind adobe.com.
Resolves: [MWPW-141870](https://jira.corp.adobe.com/browse/MWPW-141870)
I update the implementation of the [seotech-video-url](https://milo.adobe.com/docs/authoring/features/seotech-video-url) feature to use a new version of seotech API endpoint which allows for proper caching and sits behind adobe.com. We now parse video urls locally first and call the endpoint if url is supported. There are no visible changes to the user.
I also update the seotech README for future developers.
I updated all unit tests and added extensive tests for regex.
Use the following snippet in dev console to confirm added VideoObject JSON-LD on each non-error page:
```js …
```
=> MWPW-141870: Update seotech-video-url API endpoint

tools/floodbox/graybox/graybox.css, tools/floodbox/graybox/graybox.js
* misc ui polishing
Resolves: [MWPW-161925](https://jira.corp.adobe.com/browse/MWPW-161925)
**Test URLs:**
- After: https://da.live/app/colloyd/milo/tools/graybox?ref=graybox-ui-polish
=> graybox ui initial polish

libs/blocks/global-navigation/global-navigation.css, libs/blocks/global-navigation/global-navigation.js, libs/blocks/global-navigation/utilities/utilities.js, libs/navigation/bootstrapper.js, libs/navigation/navigation.js, libs/styles/styles.css, libs/utils/utils.js
* Adding a container for localnav before gnav loads to avoid cls
* Support for Local nav first title from document first and defaults to placeholder value of overview key
* Adding a new design feature flag through metadata
Resolves: 
- [MWPW-161998](https://jira.corp.adobe.com/browse/MWPW-161998) 
- [MWPW-161197](https://jira.corp.adobe.com/browse/MWPW-161197) 
**Test URLs:**
- After: https://mobile-gnav-localnav--milo--adobecom.hlx.page/?martech=off
QA: 
- https://main--federal--adobecom.hlx.page/federal/dev/blaishram/page-with-localnav?milolibs=mobile-gnav-cls
- Nested localNav -> https://stage--dc--adobecom.hlx.page/drafts/soujanya/integrations?milolibs=mobile-gnav-cls
- Page without localnav -> …
=> Handling CLS issue for localnav - mobile gnav redesign

test/tools/floodbox/graybox/graybox-config.test.js, tools/floodbox/graybox/graybox-config.js, tools/floodbox/graybox/graybox.js
- Adds config support to enable/disable promote at
- per experience level 
- global level
- Adds options to ignore specific paths during promote
- Adds options to promote drafts only for testing at 
- per experience level
- global level
Resolves: [MWPW-161929](https://jira.corp.adobe.com/browse/MWPW-161929)
**Test URLs:**
- After: https://da.live/app/adobecom/milo/tools/graybox?ref=graybox-config 
The config has been temporarily added here for testing:
https://da.live/#/sukamat/da-bacom-graybox/.milo/graybox
This can be copied into your own org for testing. It will be moved to the `adobecom` org later.
=> MWPW-161929: Central configuration support for Graybox on DA

libs/blocks/table/table.css, libs/utils/utils.js
In reference to the [new federal icons work that was reverted](https://github.com/adobecom/milo/pull/2986), icons within tables were not having their respective SVG assets injected or tooltips being decorated. This was because the table block moves the icons around. I was able to see the icons being decorated by reselecting all icons before passing to icon js to be decorated and loaded.
There is also an issue where the expand/collapse icons wrapped to the bottom because of the new node index margin that was added. Unsetting that for this individual icon in the table.css.
Resolves: [MWPW-140452](https://jira.corp.adobe.com/browse/MWPW-140452)
**Test URLs:**
- Before: https://rparrish-fed-icons--milo--adobecom.hlx.page/drafts/sarchibeque/table-icons?martech=off
- After: …
=> Fed Icons - Table icon decoration and collapse icon wrapping

libs/blocks/global-navigation/global-navigation.css, libs/blocks/global-navigation/global-navigation.js, libs/styles/styles.css, libs/utils/utils.js
LocalNavs must include the string 'localnav' in their name; otherwise, they will encounter CLS issues with the mobile design for localnav.
* Adding a check for localnav string on gnav source and preserving space
* Adding Lana log if content is localnav but file name doesn't include localnav
Resolves: [MWPW-161998](https://jira.corp.adobe.com/browse/MWPW-161998)
**Test URLs:**
- After: https://mgnav-cls--milo--adobecom.aem.page/?martech=off
QA: 
- Without localnav string -  https://main--federal--adobecom.hlx.page/federal/dev/blaishram/page-with-localnav?milolibs=mgnav-cls
- With localnav string - https://main--federal--adobecom.hlx.page/federal/dev/blaishram/express/express?milolibs=mgnav-cls
=> Handle CLS issue on localnav: mobile redesign

libs/blocks/locui-create/input-urls/view.js
* Used for removing duplicate urls from enter urls textarea.
* Duplicate urls will be removed onBlur event.
Resolves: https://jira.corp.adobe.com/browse/MWPW-162874
**Test URLs:**
- After: https://mwpw-162874-duplicate-urls--milo--saurabhsircar11.hlx.page/drafts/sircar/locui-create?martech=off
=> [LOC] MWPW 162874: Removing duplicate urls from enter urls textarea

tools/floodbox/crawl-tree.js, tools/floodbox/floodgate/floodgate.js, tools/floodbox/graybox/graybox.js
- Caters to "drafts only" global flag when performing promote
- Updates both FG and GB apps on DA
Resolves: [MWPW-161916](https://jira.corp.adobe.com/browse/MWPW-161916), [MWPW-161936](https://jira.corp.adobe.com/browse/MWPW-161936)
**Test URLs:**
- After: https://da.live/app/adobecom/milo/tools/graybox?ref=draftsonly
- After: https://da.live/app/adobecom/milo/tools/floodgate?ref=draftsonly
=> Handles promote on drafts path only

libs/blocks/locui-create/fragments/view.js, libs/blocks/locui-create/input-urls/index.js, libs/blocks/locui-create/input-urls/view.js
* Moved form errors related to fragments to parent component.
* reset form errors related to fragments when include fragments is disabled
Resolves: https://jira.corp.adobe.com/browse/MWPW-163183
**Test URLs:**
- Before: https://main--milo--adobecom.hlx.page/drafts/sircar/locui-create?martech=off
- After: https://MWPW-163183-next-cta-issue--milo--saurabhsircar11.hlx.page/drafts/sircar/locui-create?martech=off
=> [LOC] MWPW-163183 - fixed cta issue when no fragments is selected

libs/blocks/locui-create/input-urls/view.js
* Set fragments to empty array and disabled the include fragments switch when there is an invalid or no url present.
Resolves: https://jira.corp.adobe.com/browse/MWPW-163209
**Test URLs:**
- After: https://MWPW-163209-remove-fragment-section--milo--saurabhsircar11.hlx.page/drafts/sircar/locui-create?martech=off
=> [LOC] MWPW-163209 - Removed Fragment sections when invalid or empty urls

libs/blocks/global-navigation/utilities/utilities.js
**Test URLs:**
- After: https://mobile-gnav-analytics--milo--sharmrj.aem.page/?martech=off
- 
https://main--cc--adobecom.hlx.page/drafts/devashish/vh?milolibs=mobile-gnav-analytics--milo--sharmrj
=>  Added Analytics Attributes to Tabs and Tabpanels

libs/blocks/global-navigation/global-navigation.js
* Drill down the matching column in second screen and if no match is found then drill down the first column
Resolves: [MWPW-163266](https://jira.corp.adobe.com/browse/MWPW-163266)
**Test URLs:**
- After: https://mgnav-activelink--milo--adobecom.aem.page/?martech=off
**Qa**:
- Default - https://main--federal--adobecom.hlx.page/federal/dev/blaishram/express/express-2?milolibs=mgnav-activelink
- Link in second column - https://main--federal--adobecom.hlx.page/federal/dev/blaishram/express/express?milolibs=mgnav-activelink
=> Adding active column logic in a large menu

nala/features/personalization/personalization.spec.js, nala/features/personalization/personalization.test.js
This PR adds 2 legacy tests to the personalization.test.js file using an old version of a MEP manifest: removeContent and replaceFragment
Resolves: [MWPW-162093](https://jira.corp.adobe.com/browse/MWPW-162093)
**Test URLs:**
- After: https://legacy2--milo--adobecom.hlx.page/?martech=off
Test pages:
https://main--milo--adobecom.hlx.live/drafts/nala/features/personalization/legacy/remove-content
and the default version: https://main--milo--adobecom.hlx.live/drafts/nala/features/personalization/legacy/remove-content?mep=%2Fdrafts%2Fnala%2Ffeatures%2Fpersonalization%2Flegacy%2Fremove-content.json--default
https://main--milo--adobecom.hlx.page/drafts/nala/features/personalization/legacy/replace-fragment
and the default version of the …
=> MWPW-162093 [MEP][NALA] add 2 more legacy tests

nala/features/personalization/any-marquee-section.spec.js, nala/features/personalization/any-marquee-section.test.js
This nala tests checks the "any-marquee-section" selector per PR request 2884: 
Resolves: [MWPW-162833](https://jira.corp.adobe.com/browse/MWPW-NUMBER)
**Test URLs:**
- After: https://any-marquee-section--milo--adobecom.aem.page/?martech=off
- PSI check: https://any-marquee-section--milo--adobecom.aem.page/?martech=off
Here is an example of the nala test:
https://main--milo--adobecom.hlx.page/drafts/nala/features/personalization/any-marquee-section/any-marquee-section
compare with the default base page: https://main--milo--adobecom.hlx.page/drafts/nala/features/personalization/any-marquee-section/any-marquee-section?mep=%2Fdrafts%2Fnala%2Ffeatures%2Fpersonalization%2Fany-marquee-section%2Fany-marquee-section.json--default
Note …
=> MWPW-162833 [nala][MEP] confirm the "any-marquee-section" selector

libs/blocks/article-feed/article-helpers.js, test/blocks/article-feed/article-helpers.test.js
* Supports type-safe query indexes
Resolves: [MWPW-161587](https://jira.corp.adobe.com/browse/MWPW-161587)
**Milo URLs:**
- https://main--milo--adobecom.hlx.live/blog/
- https://typedqi--milo--adobecom.hlx.live/blog/
**Test URLs:**
- Before: https://ogmilo--da-bacom-blog--adobecom.hlx.page/de/blog/
- After: https://ogmilo--da-bacom-blog--adobecom.hlx.page/de/blog/?milolibs=typedqi
- Existing: https://ogmilo--da-bacom-blog--adobecom.hlx.page/de/blog/?milolibs=typedqi (no regressions / impact)
**How to test:**
Note: there are unrelated errors that can be [reproduced on the existing site](https://main--bacom-blog--adobecom.hlx.page/de/blog/). Something related to `status.js`.
1. Navigate to the test before page. 
* Note that there is not a list of cards under the featured article (top area). …
=> MWPW-161587 - Support typed query indexes

libs/blocks/modal-metadata/modal-metadata.js, libs/blocks/modal/modal.css, libs/blocks/section-metadata/section-metadata.js
**New tall video modal option**
* Adds ability to display tall/portrait style videos in modal
* Opt in feature - add `modal-metadata` block to fragment and apply new `style` "`tall-video`"
This new feature is enabled by adding a `modal-metadata` block to a fragment that will be used as a modal. Adding a new `style` value of "`tall-video`" will enable the feature. 
This use case is for the Photoshop mobile launch.
Resolves: [MWPW-162482](https://jira.corp.adobe.com/browse/MWPW-162482)
**Test URLs:**
- Before: https://main--milo--adobecom.hlx.page/drafts/rclayton/tall-video?martech=off
- After: https://modal-tall-video--milo--adobecom.hlx.page/drafts/rclayton/tall-video?martech=off
---
=> New modal option to support tall videos

libs/features/placeholders.js, test/features/placeholders/bg/placeholders.json, test/features/placeholders/placeholders.json, test/features/placeholders/placeholders.test.js
* Adds functionality to conditionally use geo-specific placeholders based on `disable-geo-placeholders` meta tag. 
* If the tag is absent or set to `"off"`, the application receives geo-specific placeholders. If the tag is set to `"on"`, it defaults to generic placeholders.
Resolves: [MWPW-157506](https://jira.corp.adobe.com/browse/MWPW-157506)
GH: https://github.com/orgs/adobecom/discussions/2791
**Milo**
- Before: https://main--milo--adobecom.hlx.page/drafts/siva/157506/placeholder-example
- After: https://mwpw-157506--milo--sivasadobe.hlx.page/drafts/siva/157506/placeholder-example
**CC**
- Before: https://main--cc--adobecom.hlx.page/bg/drafts/siva/157506/elements-family?martech=off
- After: https://main--cc--adobecom.hlx.page/bg/drafts/siva/157506/elements-family?milolibs=mwpw-157506-- …
=> MWPW-157506: Localized Placeholder Texts on English Pages

playwright.config.js
* Increase the GitHub worker count to `[ 7 ]` to support more parallel execution.
* Validate that execution time is significantly reduced from the current 8-minute duration.
Resolves: [MWPW-162258](https://jira.corp.adobe.com/browse/MWPW-162258)
**Test URLs:**
- After: https://nala-workers--milo--adobecom.hlx.page/?martech=off
=> [MWPW-162258][NALA] Increase GitHub Test Execution Worker Count for Nala to Improve Execution Speed

helix-query.yaml
* Add your
* Specific
Resolves: https://jira.corp.adobe.com/browse/DOTCOM-140152
We want to enable blog article to share updates on milo.adobe.com
https://milo.adobe.com/blog/
The actual helix-query is missing information
date, author, category, tags
**Test URLs:**
- Before: https://stage--milo--adobecom.hlx.live/blog/?martech=off
- After: https://update-helix-query-blog-usage--milo--elaineskpt.hlx.live/blog/?martech=off
=> DOTCOM-140152 - Update helix-query for Blog usage

libs/blocks/quiz/quizoption.js, libs/blocks/quiz/stepIndicator.js
* aria-label on button made dynamic to match the text
* accessibility additions to the progress indicator
Resolves: [MWPW-161333](https://jira.corp.adobe.com/browse/MWPW-161333)
**Test URLs:**
- After: https://quiz-q4-accessibility--milo--colloyd.aem.page/drafts/colloyd/quiz/?martech=off
Testing notes: 
In the "After" page, observe the progress indicator and look for the aria-current="step" and aria-label="Step [X] of [Total] on the current indicator.
For the button, choose options and go through the quiz until the button says, "Get your results", note how the aria-label on the button is representative of the text in the button and is no longer the hard coded "Next".
=> quiz button and indicator accessibility

libs/features/personalization/preview.css
This PR excludes the mep button from rtl styling updates that cause some formatting issues when viewed on rtl pages. 
Resolves: [MWPW-162990](https://jira.corp.adobe.com/browse/MWPW-162990)
**Test URLs:**
- After: https://main--homepage--adobecom.hlx.page/il_he/homepage/index-loggedout?milolibs=removemepfromrtl
- Psi-check: https://removemepfromrtl--milo--adobecom.aem.page/?martech=off
=> MWPW-162990 [MEP] Exclude MEP button from rtl formatting

test/tools/floodbox/search-replace.test.js, tools/floodbox/search-replace.js
- Retains image URL domain as-is for graybox during promote
Resolves: [MWPW-161937](https://jira.corp.adobe.com/browse/MWPW-161937)
**Test URLs:**
- After: https://da.live/app/adobecom/milo/tools/graybox?ref=imagefix
=> MWPW-161937: Handles images during promote

libs/features/dynamic-navigation/dynamic-navigation.js, libs/features/dynamic-navigation/status.js, libs/utils/utils.js, test/features/dynamic-nav/dynamicNav.test.js, test/features/dynamic-nav/status.test.js
* Adds the ability to add a group metadata attribute to dynamic nav 
* Groups will allow the nav to be disabled when groups do not match
* Group should not effect nav if not enabled
Resolves: [MWPW-155723](https://jira.corp.adobe.com/browse/MWPW-155723)
**Test URLs:**
- Before: https://main--milo--jasonhowellslavin.hlx.page/drafts/slavin/dynamic-nav/bacom-sample-on?martech=off
- After: https://dynamic-nav-groups--milo--jasonhowellslavin.hlx.page/drafts/slavin/dynamic-nav/bacom-sample-on?martech=off
Bacom
- Before: https://main--bacom--adobecom.hlx.page/drafts/slavin/dynamic-nav/aem-rtcdp-entry?martech=off
- After: https://main--bacom--adobecom.hlx.page/drafts/slavin/dynamic-nav/aem-rtcdp-entry?milolibs=dynamic-nav-groups&martech=off
=> MWPW-155723 - Adds group metadata to ensure dyanmic nav continuity 

libs/blocks/table/table.css, libs/blocks/table/table.js
Similar to the `table (left)` variant which sets horizontal alignment on the table body cells, this adds a `table (top)` variant for setting the vertical alignment on table body cells.
Resolves: [MWPW-160774](https://jira.corp.adobe.com/browse/MWPW-160774)
**Test URLs:**
- Before: https://main--milo--adobecom.hlx.page/drafts/sarchibeque/table-alignment?martech=off
- After: https://sartxi-table-align--milo--adobecom.hlx.page/drafts/sarchibeque/table-alignment?martech=off
=> MWPW-160774 - [Table] top variant

.github/workflows/merge-to-stage.js
Add Express Team SOTs, now that they're joining the Milo family.
**Test URLs:**
- After: https://update-members--milo--overmyheadandbody.aem.page/?martech=off
=> Add Express SOTs

libs/navigation/navigation.js, test/navigation/navigation.test.js
* removed the /dist/ from the css paths where it's incorrect
Resolves: [MWPW-163606](https://jira.corp.adobe.com/browse/MWPW-163606)
**Test URLs:**
- After: https://fix-css-dist-path--milo--adobecom.aem.page/?martech=off
=> MWPW-163606 removed the /dist/ from the css paths where it's incorrect

libs/blocks/media/media.js
The media block was opinionated when it came to `alt` attributes, defaulting them to the block's heading. This is an accessibility anti-pattern, thus removing this behavior and relying on authors to add the relevant attribute values when needed.
Resolves: [MWPW-161403](https://jira.corp.adobe.com/browse/MWPW-161403)
**Test URLs:**
- Before: https://main--milo--adobecom.hlx.page/drafts/ramuntea/accessibility/default-alt-in-media-block?martech=off
- After: https://rm-default-media-alt--milo--overmyheadandbody.hlx.page/drafts/ramuntea/accessibility/default-alt-in-media-block?martech=off
=> [MWPW-161403] Remove default alt from media block

libs/navigation/navigation.js
* Adding prodDomains and allowed origin for standalone gnav 
Resolves: [MWPW-163701](https://jira.corp.adobe.com/browse/MWPW-163701)
**Test URLs:**
- After: https://gnav-prodDomains--milo--adobecom.aem.page/?martech=off
Qa: 
- Before: https://adobecom.github.io/nav-consumer/navigation.html?authoringpath=/federal/home&locale=jp
- After: https://adobecom.github.io/nav-consumer/navigation.html?authoringpath=/federal/home&navbranch=gnav-prodDomains&locale=jp
=> Adding prodDomains and allowed origin for standalone gnav

nala/features/personalization/ul-ol-li.spec.js, nala/features/personalization/ul-ol-li.test.js
This tests the ul and li selectors (and skips ol because we don't have anything in the library that uses ol in the plain html)
Resolves: [MWPW-162847](https://jira.corp.adobe.com/browse/MWPW-162847)
**Test URLs:**
- After: https://ul-ol-li--milo--adobecom.aem.page/?martech=off
tests li selectors: https://main--milo--adobecom.hlx.page/drafts/nala/features/personalization/ul-ol-li/li-selectors
tests ul selector: https://main--milo--adobecom.hlx.page/drafts/nala/features/personalization/ul-ol-li/ul-selector
compare with their default pages:
https://main--milo--adobecom.hlx.page/drafts/nala/features/personalization/ul-ol-li/ul-selector?mep=%2Fdrafts%2Fnala%2Ffeatures%2Fpersonalization%2Ful-ol-li%2Ful-selector.json--default …
=> MWPW-162847 [MEP][nala] add ul-li selector test

nala/blocks/table/table.page.js, nala/blocks/table/table.spec.js, nala/blocks/table/table.test.js
* Validate tooltip information in table header rows
* Validate tooltip information in table section rows
* Add tests for new table variants 
* **Table (merch, pricing-bottom)**
* **Table (merch, button-right)**
Resolves: [MWPW-162711](https://jira.corp.adobe.com/browse/MWPW-162711)
**Test URLs:**
- After: https://table-update--milo--adobecom.aem.page/?martech=off
=> [MWPW-162711][NALA] Update Table block tests to validate tooltip information

libs/utils/utils.js, nala/blocks/video/video.spec.js, test/utils/mocks/body.html, test/utils/utils.test.js
This allows authors to set individual `aria-label` values for links in order to make them accessibility-compliant. A few things that were considered (also available on the test page):
- certain links may have non-text children, such as icons;
- some links may actually need to have a pipe in their text, so just the text after the last pipe is considered for the `aria-label` value;
- I've queried a few projects for the presence of `|` inside links and came short, meaning there should be no links currently on production that would get affected by this change;
Resolves: [MWPW-161396](https://jira.corp.adobe.com/browse/MWPW-161396)
**Test URLs:**
- Before: https://main--milo--adobecom.hlx.page/drafts/ramuntea/accessibility/aria-label-with-icon?martech=off
- After: …
=> Allow setting of aria label text for links

libs/blocks/global-footer/global-footer.js
* Fix for CSO issue caused by #3132  (Revert PR: #3319). See https://main--bacom-blog--adobecom.hlx.page/blog/?milolibs=bundled-standalone-gnav-fix
* Other notes can be found in the description of #3132 
Resolves: [MWPW-163734](https://jira.corp.adobe.com/browse/MWPW-163734)
**Test URLs:**
- After: https://bundled-standalone-gnav-fix--milo--adobecom.aem.page/?martech=off
=> MWPW-161273 Standalone Gnav needs a release cycle [Bundle]

libs/blocks/global-navigation/global-navigation.css, libs/blocks/global-navigation/global-navigation.js, libs/blocks/global-navigation/utilities/keyboard/index.js, libs/blocks/global-navigation/utilities/keyboard/localNav.js, libs/blocks/global-navigation/utilities/keyboard/utils.js, libs/blocks/global-navigation/utilities/utilities.js, libs/styles/styles.css
Added keyboard navigation for Local nav as part of mobile redesign along with some a11y changes.
Resolves: [MWPW-163735](https://jira.corp.adobe.com/browse/MWPW-163735)
**Test URLs:**
- After: https://mobile-localnav-a11y--milo--deva309.aem.page/?martech=off
QA:
https://main--federal--adobecom.hlx.page/federal/dev/blaishram/express/express?milolibs=mobile-localnav-a11y--milo--deva309
=> [MWPW-163735] - Added Local Nav keyboard navigation for mobile GNAV redesign

libs/navigation/navigation.js
* Added default alllowedOrigins for standalone gnav from which content will be picked
Resolves: - [MWPW-163797](https://jira.corp.adobe.com/browse/MWPW-163797) ,  [MWPW-162745](https://jira.corp.adobe.com/browse/MWPW-162745)
**Test URLs:**
- After: https://gnav-allowedOrigins--milo--adobecom.aem.page/?martech=off
QA:
- Before: https://adobecom.github.io/nav-consumer/navigation.html?env=stage&authoringpath=/federal/home
- After: https://adobecom.github.io/nav-consumer/navigation.html?env=stage&navbranch=gnav-allowedOrigins&authoringpath=/federal/home
=> Adding Standalone gnav's default allowed origins

libs/blocks/table/table.css, libs/blocks/text/text.css, libs/features/georoutingv2/georoutingv2.css, libs/features/georoutingv2/georoutingv2.js, libs/features/icons/icons.css, libs/features/icons/icons.js, libs/styles/styles.css, libs/utils/utils.js, test/features/icons/icons.test.js, test/features/icons/mocks/body.html
This initial [PR](https://github.com/adobecom/milo/pull/2986) was reverted due to some issues found w/ tooltips in the table block. re-submitting as this has been resolved. 
---
To streamline icon management across Milo and other consuming sites, a centralized repository, federal, along with a directory named `icons/svgs`, will be established. This will provide shared access to a unified set of icons. The transition will maintain the current authoring experience, while also introducing new opportunities for contributors to expand the icon set. The key points of this change are outlined below:
Key Points:
**Centralized Icon Repository:** A new [/assets/icons/svgs](https://adobe.sharepoint.com/sites/adobecom/Shared%20Documents/Forms/AllItems.aspx?id=%2Fsites%2Fadobecom%2FShared%20Documents%2 …
=> MWPW-140452 - Icon authoring in milo using the federal repo and individual SVG assets

.github/workflows/helpers.js, .github/workflows/merge-to-main.js, .github/workflows/merge-to-main.yaml, .github/workflows/merge-to-stage.js, .github/workflows/rcp-notifier.js
This tries to address a few issues with the current RCP workflow logic:
* don't block the merge to stage pipe for RCPs shorter than 24h. The merge to main pipe will continue to be blocked;
* don't send Slack notifications for RCPs lasting less than a day to avoid confusion;
* adapt the logic that decides when to send the Slack notifications to avoid sending the same alert multiple times;
* take the offset into account for the `isWithinRCP` method;
* declare the number of minimum required SOT approvals as a secret.
Resolves: [MWPW-163539](https://jira.corp.adobe.com/browse/MWPW-163539)
**Test URLs:**
- After: https://upate-rcp-workflow--milo--overmyheadandbody.aem.page/?martech=off
=> [MWPW-163539] Update RCP workflow

.github/workflows/run-nala-circleci.yml
* The current CircleCI job using a self-hosted runner is experiencing issues, causing delays as the automated trigger in the pipeline frequently hangs. This impacts the merge process.
* By default, Nala tests are already running on the stage branch as part of the pipeline, making this additional CircleCI job redundant in most cases.
Updating the workflow to use a manual trigger (workflow_dispatch) temporarily. This allows the CircleCI job to be executed only on demand, avoiding pipeline hangs while maintaining the flexibility to run the job when needed. Once the self-hosted runner issues are resolved, the automated trigger can be reinstated if required
Resolves: [MWPW-163723](https://jira.corp.adobe.com/browse/MWPW-163723)
**Test URLs:**
- Before: …
=> [MWPW-163723] [NALA] Update Nala CircleCI Job to Manual Trigger

libs/martech/helpers.js, libs/utils/utils.js
Bug 1:
prod: https://www.adobe.com/experienceedge/ee/v2/interact (based on domain name)
stage: https://www.stage.adobe.com/experienceedge/ee/v2/interact
dev/hlx: https://edge.adobedc.net/ee/v2/interact
Bug 2:
Fix campaign applying without target=on ( when personalization is present)
https://main--cc--adobecom.hlx.live/drafts/suhjain/swati-pages/photoshop-v2?target=on&milolibs=ENB-7556-update-api-endpoints--milo--swamu#
Resolves: [ENB-7556](https://jira.corp.adobe.com/browse/ENB-7556)
Test URLs:
After: https://ENB-7556-update-api-endpoints--milo--swamu.aem.page/?martech=off
=> [ENB-7566] Change domain names for stage, remove personalization logic for not signed in

.gitignore
Ignore tmp folders
**Test URLs:**
- After: https://chore-tmp--milo--hparra.aem.page/?martech=off
=> chore: Ignore tmp folders

libs/utils/sidekick-decorate.js
Fixes an undefined error within the sidekick
**Test URLs:**
- Before: https://hlx-5--dc--adobecom.aem.live/uk/acrobat/business/industries/government
- After: https://hlx-5--dc--adobecom.aem.live/uk/acrobat/business/industries/government?milolibs=fix-sidekick-err--milo--mokimo
To get the psi check running:
- https://fix-sidekick-err--milo--mokimo.hlx.live/
=> Fix optional profile page detail in the sidekick

libs/blocks/table/table.css, libs/blocks/text/text.css, libs/features/georoutingv2/georoutingv2.css, libs/features/georoutingv2/georoutingv2.js, libs/features/icons/icons.css, libs/features/icons/icons.js, libs/styles/styles.css, libs/utils/utils.js, test/features/icons/icons.test.js, test/features/icons/mocks/body.html
Reverts adobecom/milo#3259 due to missing consumer icons and 404s on production for other use-cases such as project unity.
- https://stage--milo--adobecom.hlx.page/
- https://revert-3259-rparrish-fed-icons--milo--adobecom.hlx.page/
=> Revert "MWPW-140452 - Icon authoring in milo using the federal repo and individual SVG assets"

libs/styles/styles.css
Reverts adobecom/milo#3330
Reverting as home page is getting affected by the same.
**Test URLs:**
- Before: https://darkcta--milo--suhjainadobe.hlx.live/drafts/suhjain/dark-cta
- After: https://revert-3330-darkcta--milo--adobecom.hlx.live/drafts/suhjain/dark-cta
=> Revert "MWPW-163754 Color difference is seen in the milo pages"

libs/blocks/global-navigation/global-navigation.css, libs/blocks/global-navigation/global-navigation.js, libs/blocks/global-navigation/utilities/utilities.js
* Making localnav auto dismiss on click outside
Resolves: [MWPW-163915](https://jira.corp.adobe.com/browse/MWPW-163915)
**Test URLs:**
- After: https://localnav-auto--milo--adobecom.aem.page/?martech=off
**QA**
- https://main--cc--adobecom.hlx.live/creativecloud?milolibs=localnav-auto
=> Making localnav auto dismiss on click outside

.github/workflows/helpers.js
This updates the 2025 RCP dates to ensure workflows continue to work as expected. The logic has also been slightly adapted to avoid referencing a hardcoded year.
Resolves: [MWPW-164170](https://jira.corp.adobe.com/browse/MWPW-164170)
**Test URLs:**
- After: https://update-rcp-dates--milo--overmyheadandbody.aem.page/?martech=off
=> [MWPW-164170] Update RCP dates for 2025

libs/blocks/locui-create/input-urls/view.js
* Fixed regional edit behavior value "override
Resolves: [MWPW-164169](https://jira.corp.adobe.com/browse/MWPW-164169)
**Test URLs:**
- After: https://mwpw-164169-overwrite-fix--milo--zweihand3r.hlx.page/drafts/arnab/locui-create?martech=off
=> MWPW-164169: Fixed value from override to overwrite

tools/floodbox/floodbox.css, tools/floodbox/floodgate/floodgate.css, tools/floodbox/floodgate/floodgate.js, tools/floodbox/floodgate/utils.js, tools/floodgate.html
* UI for the promote option
Resolves: [MWPW-161908](https://jira.corp.adobe.com/browse/MWPW-161908)
**Test URLs:**
- After: https://da.live/app/colloyd/milo/tools/floodgate?ref=da-floodgate-promote-ui
=> DA Floodgate Promote UI

libs/blocks/locui-create/input-locale/index.js, libs/blocks/locui-create/input-locale/view.js, libs/blocks/locui-create/input-urls/view.js, libs/blocks/locui-create/locui-create.css, libs/blocks/locui-create/utils/utils.js
* Fixes design feedback for loc v3 screen
Resolves: https://jira.corp.adobe.com/browse/MWPW-163903
**Test URLs:**
- Before: https://main--milo--adobecom.hlx.page/drafts/sircar/locui-create?martech=off
- After: https://mwpw-163903-design-feedback--milo--saurabhsircar11.hlx.page/drafts/sircar/locui-create?martech=off
=> [Loc]Mwpw-163903: fixes for design feedback on loc create screen

libs/blocks/global-navigation/global-navigation.css
* We now use `dvh` to account for the iphone home bar
* We use `safe-area-inset-bottom` to fix the scroll flickering issue
* Changes were tested using an XCode Simulator
Resolves: 
* [MWPW-163856](https://jira.corp.adobe.com/browse/MWPW-163856)
* [MWPW-164378](https://jira.corp.adobe.com/browse/MWPW-164378)
**Test URLs:**
- After: https://dvh-mobile-gnav--milo--adobecom.aem.page/?martech=off
=> [mobile gnav] view plans and pricing CTA added is not seen visible in iphone 15 in landscape and portrait mode

libs/blocks/locui-create/locui-create.css
Added Padding to the project success modal
Resolves: https://jira.corp.adobe.com/browse/MWPW-163949
**Test URLs:**
- After: https://mwpw-163949-view-popup-padding--milo--saurabhsircar11.hlx.page/drafts/sircar/locui-create?martech=off
=> [Loc] MWPW-163949: Project creation success message is not wrapping properly

libs/blocks/locui-create/input-urls/index.js
* Used locui state variable to prevent duplicity
Resolves: https://jira.corp.adobe.com/browse/MWPW-164350
**Test URLs:**
- After: https://MWPW-164350-edit-duplicate-fragments--milo--saurabhsircar11.hlx.page/drafts/sircar/locui-create?martech=off
=> [Loc]MWPW-164350 - Fragments are getting added multiple times in the Enter urls 

tools/floodbox/floodbox.css, tools/floodbox/floodbox.js, tools/floodbox/floodgate/floodgate.css, tools/floodbox/floodgate/floodgate.js
* UI for the copy option
Resolves: [MWPW-161908](https://jira.corp.adobe.com/browse/MWPW-161908)
**Test URLs:**
- After: https://da.live/app/colloyd/milo/tools/floodgate?ref=da-floodgate-copy-ui
=> DA Floodgate Copy UI

test/tools/floodbox/bulk-action.test.js, test/tools/floodbox/floodgate/utils.test.js, test/tools/floodbox/promote.test.js, tools/floodbox/bulk-action.js, tools/floodbox/floodgate/utils.js
- Unit tests added/updated for DA FloodBox App
Resolves: [MWPW-161575](https://jira.corp.adobe.com/browse/MWPW-161575)
**Test URLs:**
- After: https://da.live/app/adobecom/milo/tools/floodgate?ref=utfb
=> MWPW-161575: Unit tests added for DA FB

libs/blocks/locui-create/input-urls/view.js
* HTML Localization Flow checkbox does no longer gets checked when clicking next
Resolves: [MWPW-163901](https://jira.corp.adobe.com/browse/MWPW-163901)
**Test URLs:**
- After: https://mwpw-163901-html-flow-fix--milo--zweihand3r.hlx.page/drafts/arnab/locui-create?martech=off&projectKey=5657983f53c3869b2e81f17e5297a39c
=> MWPW-163901: Fixed check when setting htmlFlow in UI

libs/blocks/locui-create/input-actions/modal.js
* Closing modal on clicking of view
Resolves: https://jira.corp.adobe.com/browse/MWPW-164482 
**Test URLs:**
- After: https://MWPW-164482-close-modal-view--milo--saurabhsircar11.hlx.page/drafts/sircar/locui-create?martech=off
=> [LOC] MWPW-164482 - close view modal on button click

nala/features/personalization/mep-actions.spec.js, nala/features/personalization/mep-actions.test.js
This test checks the basic mep actions found in a mep manifest. It is different than the personalization.test.js file because personalization.test.js covers legacy commands from old manifests.
Resolves: [MWPW-163490](https://jira.corp.adobe.com/browse/MWPW-163490)
**Test URLs:**
- After: https://mep-actions--milo--adobecom.aem.page/?martech=off
This nala test uses the following 4 pages:
https://stage--milo--adobecom.hlx.live/drafts/nala/features/personalization/mep-actions/insert-script
https://stage--milo--adobecom.hlx.live/drafts/nala/features/personalization/mep-actions/pzn-actions
https://stage--milo--adobecom.hlx.live/drafts/nala/features/personalization/mep-actions/use-block-code …
=> MWPW-163490[MEP][NALA] add basic mep-actions test

libs/blocks/action-item/action-item.css, libs/blocks/action-scroller/action-scroller.css
This adapts the focus state for action items to ensure that the whole clickable area is focused when a user is tabbing through these elements. This is needed for accessibility purposes.
Resolves: [MWPW-160864](https://jira.corp.adobe.com/browse/MWPW-160864)
Screenshots:
| <img width="508" alt="Screenshot 2024-12-19 at 15 55 13" src="https://github.com/user-attachments/assets/bf40389f-5eeb-428a-8edc-c9de0798e619" /> | <img width="508" alt="Screenshot 2024-12-19 at 15 55 39" src="https://github.com/user-attachments/assets/f4f1eb82-c48b-4ac0-bf54-5bbb40e2490e" /> |
Note that items with floating icons will have an irregular outline when focused. I've confirmed with our accessibility experts that this is not a concern:
**Test URLs:**
- …
=> [MWPW-160864] Adapt action item focus state

libs/utils/utils.js, test/utils/mocks/body.html, test/utils/utils.test.js
This adapts the logic that allows authors to define `aria-label` attribute values for links, in order to allow the use of special characters. We're now using capturing groups to identify the pattern match at the end of the link's text content, which simplifies the logic and also addresses the bug.
Resolves: [MWPW-164097](https://jira.corp.adobe.com/browse/MWPW-164097)
**Test URLs:**
- Before: https://main--milo--overmyheadandbody.aem.page/drafts/ramuntea/accessibility/aria-label-with-icon?martech=off
- After: https://aria-label-special-chars--milo--overmyheadandbody.aem.page/drafts/ramuntea/accessibility/aria-label-with-icon?martech=off
=> [MWPW-164097] Allow special chars in aria-label definition

libs/blocks/section-metadata/sticky-section.js
When the footer is in the view screen, sections with sticky-bottom will have the "hide-sticky-section" class added.
Resolves: [MWPW-161858](https://jira.corp.adobe.com/browse/MWPW-161858)
1. Expand window height size to 1440px
2. Reload the page
3. Scroll down the page until the footer is in view
4. The sticky banner should not be visible
**Before**
**After**
- Before: https://main--cc--adobecom.hlx.page/products/special-offers?martech=off
- After: https://main--cc--adobecom.hlx.page/products/special-offers?milolibs=mwpw-161858-consonant&martech=off
PSI check url: https://mwpw-161858-consonant--milo--adobecom.hlx.page/drafts/rbogos/page-default?martech=off
=> [MWPW-161858] Remove sticky section when footer is visible

libs/blocks/global-navigation/utilities/menu/menu.js
Adds daa-lh value for promo column and daa-ll value for promo link in GNav. The 1st requirement for daa-lh value for mega menu dropdowns will be added as part of mobile-gnav changes.
Resolves: [MWPW-156410](https://jira.corp.adobe.com/browse/MWPW-156410)
**Test URLs:**
- After: https://mwpw-156410-gnav-analytics--milo--nishantka.aem.page/?martech=off
QA:
https://main--cc--adobecom.hlx.page/creativecloud/design?milolibs=mwpw-156410-gnav-analytics--milo--nishantka
=> MWPW-156410: add daa-lh/ll values for gnav promo

libs/blocks/global-navigation/global-navigation.css, libs/blocks/global-navigation/global-navigation.js, libs/blocks/global-navigation/utilities/utilities.js, libs/styles/styles.css
* on iOS Safari `overflow: hidden` does not prevent the screen from scrolling. Scrolling can still happen under the following circumstances:
* when the bottom toolbar is collapsed
* When the keyboard is visible
* When focusing on an input (which centers it it)
* So we do `position:fixed` to prevetn scrolling. But this jumps the scroll to the top of the page. So we offset the old scroll height using `top`. 
* Once the background becomes scrollable again, we retrieve our original scroll value from `body`'s style and set the window scroll to that. 
Resolves: [MWPW-163916](https://jira.corp.adobe.com/browse/MWPW-163916)
**Test URLs:**
- After: https://mobile-gnav-ios-scroll-flicker--milo--adobecom.aem.page/?martech=off …
=> MWPW-163916 [Mobile GNAV] | Flickering issue while scrolling when LNAV is opened

libs/blocks/global-navigation/global-navigation.css, libs/blocks/global-navigation/global-navigation.js
If a gnav has no megamenu but some links are present then they are now treated as localnav. So, with this change
1. Hamburger will no longer appear for such navs
2. Local nav will appear
Resolves: [MWPW-164314](https://jira.corp.adobe.com/browse/MWPW-164314)
**Test URLs:**
- After: https://mgnav-no-megamenu--milo--adobecom.aem.page/?martech=off
Qa - https://main--dc--adobecom.hlx.page/acrobat/hub/10-benefits-of-digitizing-documents?milolibs=mgnav-no-megamenu&newNav=true
=> Adding support for no megamenu localnav

test/blocks/global-navigation/global-navigation.test.js, test/blocks/global-navigation/gnav-promo.test.js, test/blocks/global-navigation/keyboard/keyboard.test.js, test/blocks/global-navigation/test-utilities.js
Fixed unit tests after changing the order of operations in the gnav to do aside first
Test URLs:
After: https://mobile-gnav-tests--milo--adobecom.aem.page/?martech=off
=> Mobile gnav tests

libs/blocks/locui/actions/index.js, libs/blocks/locui/langs/modal.js, libs/blocks/locui/loc/index.js, libs/blocks/locui/url/view.js, libs/blocks/locui/utils/miloc.js
As part of Loc V3 and single file rollout (MWPW-162683), loc service needs to support langstore/ urls.
This locui PR is for supporting those changes. Current flows would work as usual.
Resolves: MWPW-164043
Test URLs:
Before: https://locui--milo--adobecom.hlx.page/tools/loc?milolibs=locui&repo=milo&owner=adobecom&host=milo.adobe.com&project=Milo&referrer=https%3A%2F%2Fadobe.sharepoint.com%2F%3Ax%3A%2Fr%2Fsites%2Fadobecom%2F_layouts%2F15%2FDoc.aspx%3Fsourcedoc%3D%257B3e761436-39f0-4c33-8f17-f202b559f236%257D%26action%3Deditnew
After: https://locui-debug--milo--raga-adbe-gh.hlx.page/tools/loc?milolibs=locui&repo=milo&owner=adobecom&host=milo.adobe.com&project=Milo&referrer=https%3A%2F%2Fadobe.sharepoint.com%2F%3Ax%3A%2Fr%2Fsites%2Fadobecom%2F_layouts%2F15%2FDoc.aspx%3Fsourcedoc%3D%257B3e7614 …
=> [LOC UI] MWPW-164043 - Changes for supporting langstore urls

libs/navigation/navigation.css
* Some styles in styles.css necessary for localnav to function were missing from standalone gnav
**Test URLs:**
- After: https://mobile-gnav-standalone--milo--adobecom.aem.page/?martech=off
https://adobecom.github.io/nav-consumer/navigation.html?env=stage&navbranch=mobile-gnav-standalone&newNav=true
=> Mobile Gnav Standalone Localnav curtain was missing some styles

libs/blocks/global-navigation/global-navigation.js
With promo: https://main--cc--adobecom.hlx.page/ae_ar/creativecloud/photography/discover/how-to-read-a-histogram?milolibs=mobile-gnav-popup&newNav=true
without promo: https://main--cc--adobecom.hlx.live/creativecloud?milolibs=mobile-gnav-popup&newNav=true
=> Fixed the popup position for when there is no promo

libs/blocks/locui-create/input-locale/index.js, libs/blocks/locui-create/input-locale/view.js, libs/blocks/locui-create/input-urls/view.js, libs/blocks/locui-create/locui-create.css, libs/blocks/locui-create/locui-create.js, libs/blocks/locui-create/store.js, libs/blocks/locui-create/utils/constant.js, libs/blocks/locui-create/utils/utils.js
* Added single url rollout flow for loc
* fixed an issue related to prefill languages with workflow and action.
Resolves: https://jira.corp.adobe.com/browse/MWPW-164734
**Test URLs:**
- After: https://MWPW-164734-single-rollout--milo--saurabhsircar11.hlx.page/drafts/sircar/locui-create?martech=off
=> [LOC] MWPW-164734 - single rollout for loc

libs/blocks/section-metadata/sticky-section.js, test/blocks/section-metadata/mocks/body.html, test/blocks/section-metadata/section-meta.test.js
- Fixed sticky top promo banner that hides under breadcrumbs while scrolling.
- Fixed sticky bottom promo banner not being visible when no-delay option is obtained.
Resolves: [MWPW-162722](https://jira.corp.adobe.com/browse/MWPW-162722)
**Milo**
- Before: https://main--milo--sivasadobe.hlx.live/drafts/siva/162722/bf-promo-pepe-banner
- After: https://mwpw-162722--milo--sivasadobe.hlx.live/drafts/siva/162722/bf-promo-pepe-banner
**CC**
Promo Sticky Top
- Before: https://main--cc--adobecom.hlx.page/drafts/siva/162722/elements-family?martech=off
- After: https://main--cc--adobecom.hlx.page/drafts/siva/162722/elements-family?milolibs=mwpw-162722--milo--sivasadobe&martech=off
Promo Sticky Bottom
- Before: https://main--cc--adobecom.hlx.page/drafts/siva/162722/black-friday-sticky-banner-example? …
=> MWPW-162722: Sticky promo banner loading issue

tools/floodbox/bulk-action.js, tools/floodbox/floodgate/floodgate.js, tools/floodbox/graybox/graybox.js, tools/floodbox/references.js
- For preview/publish Helix API call, the auth token is passed in as the site is behind auth
Resolves: [MWPW-161920](https://jira.corp.adobe.com/browse/MWPW-161920)
**Test URLs:**
- After: https://da.live/app/adobecom/milo/tools/floodgate?ref=authsupport
- After: https://da.live/app/adobecom/milo/tools/graybox?ref=authsupport
=> MWPW-161920: Authenticated site support for preview

libs/blocks/global-navigation/utilities/menu/menu.js
Adds daa-ll value for new gnav-image element in GNav
Resolves: [MWPW-164737](https://jira.corp.adobe.com/browse/MWPW-164737)
**Test URLs:**
- After: https://mwpw-164737a--milo--adobecom.aem.page/?martech=off
QA: https://main--federal--adobecom.hlx.page/federal/dev/prats/mobileredesign/image/nav-test?milolibs=mwpw-164737a&newNav=true
=> MWPW-164737: add daa-ll for new gnav-image element

libs/navigation/package.json
* Updating package version for bundled standalone gnav
**Test URLs:**
- After: https://gnav-version--milo--adobecom.aem.page/?martech=off
=> Updating package version for bundled standalone gnav

libs/blocks/marketo/marketo.css
* Update Marketo form focus to convey state
Resolves: [MWPW-162308](https://jira.corp.adobe.com/browse/MWPW-162308)
**Test URLs:**
- Before: https://main--milo--adobecom.aem.page/drafts/bmarshal/mcz/marketo?martech=off
- After: https://bmarshal-form-focus--milo--adobecom.aem.page/drafts/bmarshal/mcz/marketo?martech=off
- Before: https://main--bacom--adobecom.hlx.live/request-consultation/experience-cloud?martech=off
- After: https://main--bacom--adobecom.hlx.live/request-consultation/experience-cloud?martech=off&milolibs=bmarshal-form-focus
=> MWPW-162308 Update focus to convey state

libs/blocks/marketo/marketo.js
* Enables scrollTo functionality for ungated Marketo forms 
Resolves: [MWPW-163166](https://jira.corp.adobe.com/browse/MWPW-163166)
**Test URLs:**
- Before: https://main--milo--jasonhowellslavin.hlx.live/drafts/slavin/gartner-mq-multichannel-marketing-hubs-2024?martech=off&form=off
- After: https://anchor-to-mkto-forms--milo--jasonhowellslavin.hlx.live/drafts/slavin/gartner-mq-multichannel-marketing-hubs-2024?martech=off&form=off
=> MWPW-163166: Enables scroll to on ungated forms 

libs/blocks/section-metadata/section-metadata.css
Adding a 16px spacing between the pill notification and the bottom of the browser to get it the appearance of "floating.
Note: The ribbon notification variant does not get this spacing.
Resolves: [MWPW-163581](https://jira.corp.adobe.com/browse/MWPW-163581)
**Test URLs:**
- Before: https://main--milo--adobecom.hlx.page/drafts/rclayton/notification-banner?martech=off
- After:https://pill-notification-padding--milo--adobecom.hlx.page/drafts/rclayton/notification-banner?martech=off
=> Notification pill variant needs 16px spacing below it

libs/blocks/ost/ctaTextOption.js, test/blocks/ost/textOption.test.js
Resolves: [MWPW-164811](https://jira.corp.adobe.com/browse/MWPW-164811)
**Test URLs:**
- After: https://MWPW-164811--milo--adobecom.aem.page/?martech=off
=> Adding save today to ctaTextOption

libs/blocks/global-navigation/global-navigation.js
* Changing the override character to :: for localnav title
Resolves: [MWPW-165395](https://jira.corp.adobe.com/browse/MWPW-165395)
**Test URLs:**
- After: https://mgnav-override--milo--adobecom.aem.page/?martech=off
QA: https://main--cc--adobecom.hlx.page/drafts/prativa/promobar/mobileredesignpromobar?milolibs=mgnav-override&newNav=true
=> Changing the override character to :: for localnav title

libs/blocks/tabs/tabs.js
* With Mobile Gnav the global navigation is no longer sticky on mobile if there is a local nav.
* This breaks `scrollStackedMobile` in tabs.js since `navHeight` is no longer correct.
* The solution is to first check for a localnav, since that is always guaranteed to be sticky instead of the global nav, and if that does not exist, look for the global nav.
Resolves: [MWPW-165391](https://jira.corp.adobe.com/browse/MWPW-165391)
**Test URLs:**
- After: https://mobile-gnav-tabs--milo--adobecom.aem.page/?martech=off
Test URL: https://main--cc--adobecom.hlx.live/creativecloud?milolibs=mobile-gnav-tabs&newNav=true
=> MWPW-165391 [Mobile-GNav] when the page is opened and navigated till center and clicked on tabs the screen is taken up

libs/blocks/preflight/panels/seo.js
The preflight dialog is added to the body of the actual page. And currently the lorem ipsum text is checked inside the entire innerHTML (thus including the preflight dialog). So once the preflight dialog opens for the first time it introduces the "Lorem Ipsum" text in the body and hence for all consecutive checks, it incorrectly fails even if the page does not have the "Lorem Ipsum" text.
Handled it by eliminating the preflight dialog content and checking in the actual body of the page instead.
Resolves: [MWPW-163381](https://jira.corp.adobe.com/browse/MWPW-163381)
**Test URLs:**
- Before: https://main--da-bacom--adobecom.aem.page/drafts/ancy/content-analytics?martech=off
- After: https://main--da-bacom--adobecom.aem.page/drafts/ancy/content-analytics?milolibs=mwpw-163381--milo--sharmeeata …
=> [MWPW-163381] : Removed lorem ipsum text check from preflight modal

libs/blocks/section-metadata/sticky-section.js, libs/mep/ace0861/section-metadata/sticky-section.js
* Adding check for localnav before setting the top for sticky top metadata
Resolves: [MWPW-165638](https://jira.corp.adobe.com/browse/MWPW-165638)
**Test URLs:**
- After: https://mgnav-sticky-top--milo--adobecom.aem.page/?martech=off
QA: https://main--dc--adobecom.hlx.page/acrobat/hub/how-to-convert-heic-to-jpg-on-a-mac?milolibs=mgnav-sticky-top&newNav=true
=> Adding check for localnav before setting the top for sticky top section metadata

libs/features/personalization/personalization.js
Add pageview send event, fix window.satellite empty issue
https://main--cc--adobecom.hlx.live/drafts/suhjain/swati-pages/photoshop-v2?target=on&milolibs=ENB-7645-wait-pageview-call--milo--swamu#
Resolves: [ENB-7645](https://jira.corp.adobe.com/browse/ENB-7645)
Test URLs:
After: https://ENB-7645-wait-pageview-call--milo--swamu.aem.page/?martech=off
=> [ENB-7645] Add page-view send event, fix window.satellite empty issue

libs/blocks/global-navigation/utilities/utilities.js
Resolves: [MWPW-165774](https://jira.corp.adobe.com/browse/MWPW-165774)
**Test URLs:**
- After: https://mobile-gnav--milo--adobecom.aem.page/?martech=off
=> MWPW-165774 [Mobile-GNAV] page is not scrollable in live page

.github/workflows/merge-to-stage.js
@npeltier pointed out that https://github.com/adobecom/milo/pull/3460 got merged with failing tests. This is because the workflow to merge to stage, ran while I restarted the tests for #3460. We need to account for running tests as well.
**Test URLs:**
- After: https://safeguard-pr-merges--milo--mokimo.aem.live/?martech=off
=> Don't merge PRs with running tests

libs/blocks/accordion/accordion.js
This solves the issue where aria-expanded was applied to the <dd tag which it shouldn't because it is content, it should only be applied to the button causing the expansion.
Resolves: [MWPW-[165790](https://jira.corp.adobe.com/browse/MWPW-165790)]
**Test URLs:**
- Before: https://main--milo--adobecom.hlx.live/drafts/nala/blocks/accordion/accordion-seo-editorial?martech=off
- After: https://accordion-aria-expanded--milo--adobecom.hlx.live/drafts/nala/blocks/accordion/accordion-seo-editorial?martech=off
=> [MWPW-165790] accordion aria-expanded fix

libs/blocks/locui-create/input-locale/view.js
* Added strong tag in locale selection
Resolves:https://jira.corp.adobe.com/browse/MWPW-166032
**Test URLs:**
- After: https://MWPW-166032-project-name-bold--milo--saurabhsircar11.hlx.page/drafts/sircar/locui-create?martech=off
=> [LOC] MWPW-166032: fix for project name on locale selection screen

test/features/branch-quick-links/branch-quick-links.test.js
* Fixed and added unit tests to increase code coverage of branch-quick-links.js
Resolves: [MWPW-164132](https://jira.corp.adobe.com/browse/MWPW-164132)
**Test URLs:**
- After: https://UT-fix--milo--adobecom.aem.page/?martech=off
=> Fixing unit tests for branch-quick-links.js

libs/blocks/rollout/rollout.js, test/blocks/rollout/rollout.test.js, tools/sidekick/config.json
This is a followup of https://github.com/adobecom/milo/pull/3463.
Updating `miloLibs` based on environment selected. Special case for Milo where the branch needs to be overridden.
Resolves: https://jira.corp.adobe.com/browse/MWPW-146930
Test URLs:
After: https://rollout-tool-update--milo--sabyamon.hlx.page/?martech=off
This feature can be tested in Milo and in BACOM by selecting the Test project configuration locally and providing the URL ```https://rollout-tool-update--milo--sabyamon.hlx.page```
=> MWPW-146930 - Rollout Tool Plugin - environment specific miloLibs

libs/blocks/tabs/tabs.css, libs/blocks/tabs/tabs.js, libs/features/georoutingv2/georoutingv2.css, nala/blocks/tabs/tabs.page.js, test/blocks/tabs/tabs.test.js
This resolves the issue where the buttons were nested in a div and not selectable with keyboard and screenreader, which is needed for accessability.
Resolves: [MWPW-161923](https://jira.corp.adobe.com/browse/MWPW-161923)
| Before     | After      |
|------------|------------|
| <img width="584" alt="Screenshot 2024-12-24 at 13 09 00" src="https://github.com/user-attachments/assets/a08cd56c-0070-4edb-8fe6-24cfe376adc3" />|  <img width="572" alt="Screenshot 2024-12-24 at 13 07 49" src="https://github.com/user-attachments/assets/19a1269b-830d-4f5b-910b-9278fa36802e" /> |
| <img width="970" alt="Screenshot 2024-12-24 at 13 16 01" src="https://github.com/user-attachments/assets/d4bf9dbf-4c52-44c4-9074-467cbe256e06" />| <img width="983" alt="Screenshot 2024-12-24 at 13 16 21" …
=> [MWPW-161923] tab nested focus

libs/blocks/mmm/mmm.js
* Added search criteria local cacheing to avoid potential repetitive API calls.
Resolves: [MWPW-165303](https://jira.corp.adobe.com/browse/MWPW-165303)
**Test URLs:**
- Before: https://main--milo--adobecom.hlx.page/drafts/mepdev/2024/q4/mmm/mmm
- After: https://mmm-api-fix--milo--adobecom.hlx.page/drafts/mepdev/2024/q4/mmm/mmm
=> MWPW-165303: Fixed potential repetative API calls

.github/workflows/helpers.js
It can happen that the `merge-to-stage` workflow doesn't correctly identify reviews for a PR due to limitations on the github APIs. By increasing the limit from the default 30 to 100 on the [list review endpoint](https://docs.github.com/en/rest/pulls/reviews?apiVersion=2022-11-28#list-reviews-for-a-pull-request) we should be very unlikely to run into a scenario where a PR has 2 approvals but we can't know due to pagination limits.
We ran into this on two occasions that I know of with a limit of 30, so with a limit of 100 we can be virtually "safe" from PRs preventing to get merged due to "insufficient approvals" by misdetection.
**Test URLs:**
- After: https://improve-pr-checks--milo--adobecom.aem.page/?martech=off
=> [Merge-to-stage worfklow] Increase Github APIs listReview per_page limit

libs/blocks/locui-create/input-urls/view.js, libs/blocks/locui-create/locui-create.css
* Added max length to restrict more than 50 chars
Resolves:https://jira.corp.adobe.com/browse/MWPW-165573
**Test URLs:**
- After: https://MWPW-165573-project-name-limit--milo--saurabhsircar11.hlx.page/drafts/sircar/locui-create?martech=off
- Before: https://main--bacom--adobecom.hlx.page/tools/locui-create?milolibs=milostudio-stage&ref=main&repo=bacom&owner=adobecom&host=business.adobe.com&project=BACOM&env=stage
- After: https://main--bacom--adobecom.hlx.page/tools/locui-create?milolibs=MWPW-165573-project-name-limit--milo--saurabhsircar11&ref=main&repo=bacom&owner=adobecom&host=business.adobe.com&project=BACOM&env=stage
=> MWPW-165573 - limit for project name

libs/blocks/locui-create/input-urls/index.js
* Added a regex for url validation
Resolves: https://jira.corp.adobe.com/browse/MWPW-165575
**Test URLs:**
- After: https://MWPW-165575-url-validation--milo--saurabhsircar11.hlx.page/drafts/sircar/locui-create?martech=off
- Before: https://main--bacom--adobecom.hlx.page/tools/locui-create?milolibs=milostudio-stage&ref=main&repo=bacom&owner=adobecom&host=business.adobe.com&project=BACOM&env=local
- After: https://main--bacom--adobecom.hlx.page/tools/locui-create?milolibs=MWPW-165575-url-validation--milo--saurabhsircar11&ref=main&repo=bacom&owner=adobecom&host=business.adobe.com&project=BACOM&env=local
=> [LOC] MWPW-165575: Url validation in url input screen

libs/features/personalization/preview.css
* Override font family for MEP button because it stays in English and the font family for RTL languages makes the numbers and symbols the wrong size
Resolves: [MWPW-166355](https://jira.corp.adobe.com/browse/MWPW-166355)
**Test URLs:**
- Before: https://main--cc--adobecom.hlx.page/mena_ar/creativecloud/buy/students/illustrator
- After: https://main--cc--adobecom.hlx.page/mena_ar/creativecloud/buy/students/illustrator?milolibs=meprtlnumbers
- Psi-check: https://meprtlnumbers--milo--adobecom.aem.page/?martech=off
=> MWPW-166355 [MEP] Number and symbols are very small in MEP button on RTL pages

libs/features/personalization/personalization.js, test/features/personalization/mocks/manifestLists/two-manifests-one-from-target.json, test/features/personalization/personalization.test.js
* For the prod env when Target experience is chosen, the manifest served by Target will be used.
Resolves: [MWPW-166002](https://jira.corp.adobe.com/browse/MWPW-166002)
**Test URLs:**
- Psi-check: https://manifest-server-vs-target--milo--adobecom.aem.page/?martech=off
QA Links:
For all After links the expected text header has been provided.
- Before: 
https://main--cc--adobecom.hlx.page/drafts/mepdev/fragments/2025/q1/manifest-server-vs-target/page?audience=edu&env=prod
https://main--cc--adobecom.hlx.page/drafts/mepdev/fragments/2025/q1/manifest-server-vs-target/page?audience=edu
https://main--cc--adobecom.hlx.page/drafts/mepdev/fragments/2025/q1/manifest-server-vs-target/page?env=prod …
=> MWPW-166002 | [MEP] Use Target served version of manifest in prod when Target experience is chosen

libs/features/personalization/personalization.js, libs/martech/martech.js
* Set sample rate to be lower
Resolves: [MWPW-159369](https://jira.corp.adobe.com/browse/MWPW-159369)
**Test URLs:**
- After: https://mepreducelana--milo--adobecom.aem.page/?martech=off
=> MWPW-159369 [cc][LANA] Error reported: target response time: 0.5

nala/blocks/aside/aside.page.js, nala/blocks/aside/aside.test.js, test/blocks/aside/aside.test.js
This adds a double check for the background color allowing us to change color via authoring after merge without bringing down tests for everyone else and fixing the accessibility color contrast issue. After merging and authoring the background color, a new PR will be made to revert back to checking only the single new background color.
Resolves: [MWPW-165793](https://jira.corp.adobe.com/browse/MWPW-165793)
**Test URLs:**
- Before: https://main--milo--adobecom.hlx.live/drafts/nala/blocks/aside/aside-small?martech=off
- After: https://aside-small-background-fix--milo--adobecom.aem.page/drafts/nala/blocks/aside/aside-small?martech=off
=> [MWPW-165793] aside temporary double background check added

libs/blocks/tabs/tabs.js, nala/blocks/tabs/tabs.spec.js, nala/blocks/tabs/tabs.test.js, test/blocks/tabs/tabs.test.js
Updated Milo tabs to support linking to separate pages as was previously supported in the Dexter Navigation List component. 
Authoring:
1. A separate page should be created for each tab;
2. On each page the `section-metadata` of each tab should have the `link` field. The value should be a relative path to the page related to that tab:
The `tab` parameter in the URL works as before:
If specified, it determines which tab is selected. The tab parameter takes precedence. For example, if you navigate to the page associated with tab 1 but include the tab parameter to select tab 2, tab 2 will be selected, and the page will update to reflect the content associated with tab 2.
See example: https://mwpw-162519-tabs-with-links--milo--mirafedas.hlx.live/drafts/mirafedas/tabs/tabs-page-2?tab=demo-2&mar …
=> MWPW-162519: Nav List - Link to external page

libs/blocks/media/media.css
Using an actual heading in the Media block leads to different text treatment as opposed to using a paragraph as a heading. Depending on this, the simple link on the last line of the text section can have either a bold or a regular font weight.
The aim of this PR is to ensure that all such regular links are bolded by default. This treatment may be required in other areas as well, but it was decided to handle just this use-case for the moment.
Resolves: [MWPW-162043](https://jira.corp.adobe.com/browse/MWPW-162043)
**Test URLs:**
- Before: https://main--milo--overmyheadandbody.aem.page/drafts/ramuntea/accessibility/media-heading-style?martech=off
- After: https://media-last-link-bold--milo--overmyheadandbody.aem.page/drafts/ramuntea/accessibility/media-heading-style?martech=off
- Before: …
=> [MWPW-162043] Bolded last link in Media block

libs/utils/utils.js
This PR fixes a bug where part of the non-localized URL pathname matches the current locale, leading to unwanted link transformations.
Resolves: [MWPW-166151](https://jira.corp.adobe.com/browse/MWPW-166151)
1.Launch the after URL
2.Log in with the stage account shared in the Jira ticket description.
3.Make sure gnav is visible.
4.Change the locale from english to **Suomi**.
5.Click on files tab (_"Tiedostot"_) in side nav.
6.Should not lead to a 404 page.
**Before:** 
**After:**
- Before: https://adobecom.github.io/nav-consumer/navigation.html?authoringpath=/federal/home&locale=fi&customlinks=files,apps&navbranch=stage
- After: https://adobecom.github.io/nav-consumer/navigation.html?authoringpath=/federal/home&locale=fi&customlinks=files,apps&navbranch=mwpw-166151-stage-links-conversion …
=> [MWPW-166151] Mobile gnav links transformations

libs/features/webapp-prompt/webapp-prompt.css, libs/features/webapp-prompt/webapp-prompt.js, test/features/webapp-prompt/mocks/pep-prompt-content.js, test/features/webapp-prompt/webapp-prompt.test.js
**Implemented the 'Pause On Hover' feature for Feds PEP content, allowing it to adopt the same functionality available for Express PEP.**
Authoring changes via section metadata in the PEP content to support the ability to author this feature:
Due deligence wiki: https://wiki.corp.adobe.com/display/WEBT/%5BDue+Diligence%5D+PEP+-+Federalizing+Express
Resolves: [MWPW-157116](https://jira.corp.adobe.com/browse/MWPW-157116)
**Test URLs:**
- After: https://mwpw-157116--milo--deva309.aem.page/?martech=off
QA:
- https://feds--milo--adobecom.hlx.page/drafts/devashish/pep/pep-prompt?skipPepEntitlements=true (without pause on hover)
- https://feds--milo--adobecom.hlx.page/drafts/devashish/pep/pause/pep-prompt-pause-animation?skipPepEntitlem …
=> [MWPW-157116] - Add feature for pause animation on hover for PEP

libs/blocks/locui-create/utils/utils.js
* Now we are checking language details for provided "language" query (in single rollout) by lowercasing it first. This is required for languages with pattern xy-AB (say "fr-CA"), which gets converted to lowercase as part of Preview URL by franklin 
Resolves: [MWPW-166465](https://jira.corp.adobe.com/browse/MWPW-166465)
**Test URLs:**
- After: https://MWPW-166465-language-check--milo--nkthakur48.hlx.page/drafts/sircar/locui-create?martech=off
=> MWPW-166465 Checking language details after lowercasing

libs/features/personalization/personalization.js
Detailed Description: 
When in preview mode, removed elements are not actually removed, but rather tagged to be hidden and highlighted when toggled by the highlight checkbox in the MEP button.  Because ost links are replaced by M@S, they lose the attribute to show them as hidden, thus making it impossible to tell they will be removed in production.
URL: https://main--cc--adobecom.hlx.page/drafts/fredw/try-buy-test/catalog?mep=%2Fdrafts%2Fpromos%2F2025%2Fglobal%2Ffred-test-try-buy.json--secondary-cta
1. Look in the merch-card on the page above
Expected Results: Free trial button is removed
Actual Results: Free trail buttons is not removed
Resolves: …
=> MWPW-166639 [MEP] Removing OST links doesn't work when MEP button is on

libs/tools/utils/publish.js, test/blocks/bulk-publish-v2/mocks/fetch.js
Fixes a blocking issue where the publishing restrictions were not enforced because the configuration object was not properly read. This is a critical issue because publishing restrictions need to be enforced now.
Resolves: [MWPW-166427](https://jira.corp.adobe.com/browse/MWPW-166427)
**Test URLs:**
- After: https://permissions-config--milo--narcis-radu.hlx.page/drafts/narcis/default?martech=off
URL to test functionality change: https://main--cc--adobecom.hlx.page/hu/products/photoshop?milolibs=permissions-config--milo--narcis-radu
=> [MWPW-166427] Increase limit for publishing configuration object

libs/blocks/global-navigation/features/breadcrumbs/breadcrumbs.js, libs/blocks/global-navigation/global-navigation.css, test/blocks/global-navigation/features/breadcrumbs.test.js
Breadcrumb region is missing appropriate roles and/or attributes - Gnav
* Ref ticket : [DOTCOM-129358](https://jira.corp.adobe.com/browse/DOTCOM-129358)
Resolves: [MWPW-165969](https://jira.corp.adobe.com/browse/MWPW-165969)
**Test URLs:**
- After: https://mwpw-165969--milo--adobecom.aem.page/?martech=off
Test URL: https://main--dc--adobecom.hlx.page/acrobat/pdf-reader?milolibs=mwpw-165969
=> MWPW-165969 : Breadcrumb region is missing appropriate roles and/or attributes - Gnav

libs/blocks/locui-create/input-urls/index.js, libs/blocks/locui-create/utils/utils.js, libs/blocks/locui/loc/index.js
* Added support for both hlx and aem pages for urls validation and fragments search
Resolves: https://jira.corp.adobe.com/browse/MWPW-166758
**Test URLs:**
- Before: https://main--milo--adobecom.aem.page/tools/locui-create?martech=off
- After: https://hlx-updates--milo--saurabhsircar11.aem.page/tools/locui-create?martech=off
- Before: https://main--bacom--adobecom.hlx.page/tools/locui-create?milolibs=milostudio-stage&ref=main&repo=bacom&owner=adobecom&host=business.adobe.com&project=BACOM&env=local
- After: https://main--bacom--adobecom.hlx.page/tools/locui-create?milolibs=hlx-updates--milo--saurabhsircar11&ref=main&repo=bacom&owner=adobecom&host=business.adobe.com&project=BACOM&env=local
=> [LOC] MWPW-166758: Support for hlx and aem urls for fragments and url validations

libs/blocks/modal/modal.js
Fixed the issue where the modal would open even when no hash value was present in the URL
Resolves: [MWPW-160808](https://jira.corp.adobe.com/browse/MWPW-160808)
**Milo**
- Before: https://main--milo--adobecom.hlx.live/docs/authoring/create-modal
- After: https://mwpw-160808--milo--sivasadobe.hlx.live/docs/authoring/create-modal
**CC**
- Before: https://main--cc--adobecom.hlx.page/drafts/siva/160808/enterprise?martech=off
- After: https://main--cc--adobecom.hlx.page/drafts/siva/160808/enterprise?milolibs=mwpw-160808--milo--sivasadobe&martech=off
=> MWPW-160808: fassform is seen displayed without the #id and not able to close

libs/blocks/global-navigation/utilities/utilities.js
In some cases the logo is coming as undefined for the new mobile GNAV.
We have added a empty space instead of 'undefined' text showing in the new Mobile GNAV.
Error Screenshot:
Resolves: [MWPW-166027](https://jira.corp.adobe.com/browse/MWPW-166027)
**Test URLs:**
- After: https://mwpw-166027--milo--deva309.aem.page/?martech=off
=> [MWPW-166027] - Add empty space if the logo is undefined

libs/blocks/locui-create/input-locale/index.js, libs/blocks/locui-create/utils/utils.js
* Updated available locales on toggle of locales
Resolves:https://jira.corp.adobe.com/browse/MWPW-165589
**Test URLs:**
- After: https://MWPW-165589-lang-unchecked--milo--saurabhsircar11.hlx.page/drafts/sircar/locui-create?martech=off
**Bacom Test Urls:**
- Before:https://main--bacom--adobecom.hlx.page/tools/locui-create?milolibs=milostudio-stage&ref=main&repo=bacom&owner=adobecom&host=business.adobe.com&project=BACOM&env=local
- After: https://main--bacom--adobecom.hlx.page/tools/locui-create?milolibs=mwpw-165589-lang-unchecked--milo--saurabhsircar11&ref=main&repo=bacom&owner=adobecom&host=business.adobe.com&project=BACOM&env=local
=> [LOC]MWPW-165589 - Deselect languages when there are no respective locales selected

libs/blocks/locui-create/components/stepControls.js
* disabled next button
Resolves:https://jira.corp.adobe.com/browse/MWPW-166822
**Test URLs:**
- After: https://MWPW-166822-disabled-next-button--milo--saurabhsircar11.hlx.page/drafts/sircar/locui-create?martech=off
=> [LOC]MWPW-166822 - Disabled next button on validation error

libs/blocks/locui/actions/index.js, libs/blocks/locui/loc/index.js
* removed not condition
* passed domain origin
Resolves:https://jira.corp.adobe.com/browse/MWPW-166758
For URL - https://main--express-milo--adobecom.aem.page/drafts/fragments/page-frag, below are errors reported:
**Test URLs:**
- After: https://MWPW-166758-fragment-validations--milo--saurabhsircar11.hlx.page/drafts/sircar/locui-create?martech=off
=> [LOC]MWPW-166758 - fragment validations

libs/blocks/global-navigation/global-navigation.css, libs/blocks/global-navigation/global-navigation.js, libs/utils/utils.js, test/blocks/global-navigation/global-navigation.test.js, test/blocks/global-navigation/test-utilities.js
Upgrade Universal Nav to version 1.4
* Add messageEventListener to avoid onMessage event listener ([Ref](https://wiki.corp.adobe.com/pages/viewpage.action?spaceKey=IdentityACCM&title=Account+Menu+Mini-App#AccountMenuMiniApp-CustomeventscommunicationandonMessagedeprecationcustom_event_migration))
* Support Profile Switching in Account Menu ([Ref1](https://jira.corp.adobe.com/browse/CCH-25502), [Ref2](https://wiki.corp.adobe.com/pages/viewpage.action?spaceKey=IdentityACCM&title=Profile+Switching+Integration+Guide#ProfileSwitchingIntegrationGuide-ProfileSwitchMiniApp-ProfileSwitch-IMSScopes:~:text=5.1.4.-,IMS%20Scopes%C2%A0,-The%20access%20token))
* Support new Mobile UX designs for Unav ([Ref](https://jira.corp.adobe.com/browse/CCH-25381))
* Enable shopping cart …
=> MWPW-158537 : Upgrade Universal Nav to version 1.4

libs/blocks/mmm/mmm.js, test/blocks/mmm/mmm.test.js
* Added ability to filter page list by last seen manifest
Resolves: [MWPW-166134](https://jira.corp.adobe.com/browse/MWPW-166134)
**Test URLs:**
- Before: https://main--milo--adobecom.hlx.page/docs/authoring/features/mmm
- After: https://mmm-last-seen-manifest-filter--milo--adobecom.hlx.page/docs/authoring/features/mmm
=> [MWPW-166134] MMM: added last seen manifest search

libs/blocks/section-metadata/section-metadata.css
Resolves: [MWPW-163512](https://jira.corp.adobe.com/browse/MWPW-163512)
**Test URLs:**
- Before: https://main--milo--adobecom.hlx.page/drafts/ratko/mwpw-163512/brick-bg?martech=off
- After: https://mwpw-163512-bg-image-tablet--milo--adobecom.hlx.page/drafts/ratko/mwpw-163512/brick-bg?martech=off
=> MWPW-163512: Fix masonry full-width for tablet

libs/blocks/table/table.css, libs/blocks/table/table.js
This changes the caret for table from "Title +/-" to ">/⌄ Title"
Resolves: [MWPW-156760](https://jira.corp.adobe.com/browse/MWPW-156760)
| Before       | After        |
|--------------|--------------|
|<img width="230" alt="Screenshot 2025-01-28 at 16 29 46" src="https://github.com/user-attachments/assets/d635dac6-842f-42c8-870b-b46f0d79ad80" />|<img width="226" alt="Screenshot 2025-01-28 at 16 29 39" src="https://github.com/user-attachments/assets/cc5b057d-6363-4131-8a7f-27464e789040" />|
**Test URLs:**
- After: https://table-caret-position--milo--adobecom.aem.page/docs/library/kitchen-sink/table?martech=off
=> [MWPW-156760] Table caret position

libs/blocks/rollout/rollout.js, test/blocks/rollout/rollout.test.js
Changes for Rollout Plugin
1. Extract the domain suffix of aem.page or hlx.page from referrer url
2. Pass over same to Loc V3
3. Mandatory checks for optional parameters like host removed (Federal does not have host)
Resolves: [MWPW-166684](https://jira.corp.adobe.com/browse/MWPW-166684)
**Test URLs:**
- After: https://rolloutplugin2--milo--raga-adbe-gh.hlx.page/?martech=off
=> MWPW-166684 Rollout plugin support for hlx5 

libs/features/mas/docs/benchmarks.html
82 was network ressource measure i did, here initTime performance marker duration was 35, which will more than double adjusted limit
**Test URLs:**
- After: https://MWPW-166838--milo--npeltier.aem.page/?martech=off
=> MWPW-166838 fixed referential time

libs/blocks/locui/actions/index.js, libs/blocks/locui/loc/index.js
Porting cross domain fragment validation change from MiloStudio branch PRs to locui branch
Resolves: [MWPW-166758](https://jira.corp.adobe.com/browse/MWPW-166758)
**Test URLs:**
- Before: https://locui--milo--adobecom.aem.page/tools/loc?ref=main&repo=milo&owner=adobecom&host=milo.adobe.com&project=Milo&referrer=https%3A%2F%2Fadobe.sharepoint.com%2F%3Ax%3A%2Fr%2Fsites%2Fadobecom%2F_layouts%2F15%2FDoc.aspx%3Fsourcedoc%3D%257B21a05280-fe1b-4d36-84cc-e301c6416083%257D%26action%3Deditnew
- After: https://locui-debug--milo--raga-adbe-gh.aem.page/tools/loc?ref=main&repo=milo&owner=adobecom&host=milo.adobe.com&project=Milo&referrer=https%3A%2F%2Fadobe.sharepoint.com%2F%3Ax%3A%2Fr%2Fsites%2Fadobecom%2F_layouts%2F15%2FDoc.aspx%3Fsourcedoc%3D%257B21a05280-fe1b-4d36-84cc-e301c6416083%257D%26action%3De …
=> MWPW-166758 Cross domain fragment validation in locui

libs/blocks/locui/actions/index.js
* Removed langstore prefix from url pathname of the fragment
Resolves:https://jira.corp.adobe.com/browse/MWPW-166855
**Test URLs:**
- After: https://MWPW-166855-express-fragment-validation--milo--saurabhsircar11.hlx.page/drafts/sircar/locui-create?martech=off
=> MWPW-166855 - Express fragment Validation

libs/blocks/locui-create/locui-create.css
* Updated styles for Express tenant, which has been overriding tool's style
Resolves: https://jira.corp.adobe.com/browse/MWPW-166762
Validated that now styles are correct:
**Test URLs:**
- Before: https://main--express-milo--adobecom.aem.page/tools/locui-create?milolibs=milostudio-stage&ref=main&repo=express-milo&owner=adobecom&host=www.adobe.com&env=local
- After: https://main--express-milo--adobecom.aem.page/tools/locui-create?milolibs=mwpw-166762-express-create-project&ref=main&repo=express-milo&owner=adobecom&host=www.adobe.com&env=local
=> MWPW-166762 [Loc][Create Project] Updated styles for Express tenant

libs/blocks/locui/actions/index.js
* Added condition to handle undefined original url
Resolves:https://jira.corp.adobe.com/browse/MWPW-166855
**Test URLs:**
- After: https://MWPW-166855-express-undefined-urls--milo--saurabhsircar11.hlx.page/drafts/sircar/locui-create?martech=off
**Express Test URLs:**
- Before: https://main--express-milo--adobecom.aem.page/tools/locui-create?milolibs=milostudio-stage&ref=main&repo=express-milo&owner=adobecom&host=www.adobe.com&env=stage&martech=off
- After: https://main--express-milo--adobecom.aem.page/tools/locui-create?milolibs=MWPW-166855-express-undefined-urls--milo--saurabhsircar11&ref=main&repo=express-milo&owner=adobecom&host=www.adobe.com&env=stage
=> [LOC] MWPW-166855 - handled when fragment url comes undefined

codecov.yaml
This PR is:
- increasing the tolerance threshold for codecov to 0.5%.
- including only what's under the `libs/` folder for codecov.
- excluding `libs/deps` from codecov.
Resolves: [MWPW-165978](https://jira.corp.adobe.com/browse/MWPW-165978)
- no QA needed
**Milo:**
- Before: https://stage--milo--adobecom.hlx.page/drafts/rbogos/page-default?martech=off
- After: https://mwpw-165978-coverage--robert-bogos--adobecom.hlx.page/drafts/rbogos/page-default?martech=off
=> [MWPW-165978] Make codecov tests more reliable

libs/blocks/tabs/tabs.css, libs/blocks/tabs/tabs.js
* Fix bug where clicking on a tab in the georouting modal scrolls the page underneath on mobile
* Fix bug where paddles add line to stacked mobile tabs
Resolves: [MWPW-165428](https://jira.corp.adobe.com/browse/MWPW-165428)
**Test URLs:**
- Before: https://main--cc--adobecom.hlx.live/creativecloud?georouting=on&akamaiLocale=in
- After: https://main--cc--adobecom.hlx.live/creativecloud?georouting=on&akamaiLocale=in&milolibs=georouting-scroll--milo--meganthecoder&martech=off
- Before: https://main--milo--adobecom.aem.page/drafts/methomas/tabs-stacked-mobile
- After: https://georouting-scroll--milo--meganthecoder.aem.page/drafts/methomas/tabs-stacked-mobile?martech=off
=> MWPW-165428 Fix georouting tab scroll

libs/blocks/locui-create/input-locale/index.js
* Changed condition,  used some instead of includes for avoiding partial match.
Resolves: https://jira.corp.adobe.com/browse/MWPW-166896
**Test URLs:**
- Before:https://stage--milo--adobecom.hlx.page/drafts/sircar/locui-create?martech=off
- After:https://MWPW-166896-swedish-locales--milo--saurabhsircar11.hlx.page/drafts/sircar/locui-create?martech=off
=> MWPW-166896 - all locales not getting selected

libs/blocks/marketo/marketo.js, test/blocks/marketo/marketo.test.html, test/blocks/marketo/marketo.test.js, test/blocks/marketo/mocks/marketo-utils.js
* Show multiple success sections to allow for additional layout options
Resolves: [MWPW-164405](https://jira.corp.adobe.com/browse/MWPW-164405)
**Test URLs:**
- Before: https://main--milo--adobecom.aem.page/drafts/bmarshal/one-page/one-page-multi?form=off&martech=off
- After: https://bmarshal-marketo-success--milo--adobecom.aem.page/drafts/bmarshal/one-page/one-page-multi?form=off&martech=off
- Before: https://main--milo--adobecom.hlx.page/drafts/bmarshal/marketo/one-page-marquee?form=off&martech=off
- After: https://bmarshal-marketo-success--milo--adobecom.hlx.page/drafts/bmarshal/marketo/one-page-marquee?form=off&martech=off
- Before: https://main--bacom--adobecom.hlx.page/drafts/bmarshal/marketo/one-page/technical-content-assessing-business-value-and-impact?martech=off&f …
=> MWPW-164405 Show multiple success sections

libs/blocks/table/table.js
This resolves the issue where navigating through the table with Tab causes the navigation to be stuck when getting to cells that have a caret for toggling rows.
Resolves: [MWPW-166755](https://jira.corp.adobe.com/browse/MWPW-166755)
**Test URLs:**
- After: https://table-keyboard-nav-stuck--milo--adobecom.hlx.page/docs/library/kitchen-sink/table?martech=off
=> [MWPW-166755] table tab navigation stuck fix

libs/martech/helpers.js
Fixed Bug for incorrect Datastream Id
https://main--cc--adobecom.hlx.live/drafts/suhjain/swati-pages/photoshop-v2?target=on&milolibs=ENB-7656-DatastreamBug--milo--akanshaa-18
Resolves: [ENB-7656](https://jira.corp.adobe.com/browse/ENB-7656)
Test URLs:
After: https://ENB-7656-DatastreamBug--milo--akanshaa-18.aem.page/?martech=off
=> Datastream Bug

libs/blocks/global-footer/global-footer.js
Brief description of the issue:
Text appears and functions like a section heading but is not marked up as such.
Note: changes has been tested using macos's voice over.
Resolves: [MWPW-165806](https://jira.corp.adobe.com/browse/MWPW-165806)
**Test URLs:**
- After: https://mwpw-165806--milo--patel-prince.aem.page/?martech=off
**QA URL:**
Before: https://main--cc--adobecom.hlx.page/creativecloud?martech=off
After: https://main--cc--adobecom.hlx.page/creativecloud?martech=off&milolibs=mwpw-165806--milo--patel-prince
=> MWPW-165806 Visual heading text reading fix

libs/blocks/merch-card-collection/merch-card-collection.js, test/blocks/merch-card-collection/merch-card-collection.test.js
Currently, the merch-card-collection block creates the HTML for its merch-cards dynamically during decoration. Therefore, MEP never has a chance to execute commands against the cards being created, and is limited to only _swapping_ out cards for a brand new one (a new fragment). 
This PR introduces a feature that treats cards within a collection like fragments: if a MEP action is specified to run on fragments, merch-card-collection can access those commands. Hence, we will be able to directly edit the cards in the collection, instead of needing to make completely new replacement cards to make the edits. 
Features/Notes
- Remove elements within the merch-card-collection block
- Insert/append text and HTML
- Cannot insert fragments 
- Cannot replace elements _with_ a fragment 
Resolves: …
=> MWPW-167066 [MEP] Add capabilty for merch-card-collection block to run MEP commands

libs/blocks/locui-create/input-locale/index.js, libs/blocks/locui/actions/index.js
* checked if the locale is not present.
* in find meta fragments checked for duplicate fragments and urls.
Resolves: https://jira.corp.adobe.com/browse/MWPW-167503
**Test URLs:**
- After: https://MWPW-167503-select-all--milo--saurabhsircar11.hlx.page/drafts/sircar/locui-create?martech=off
=> [LOC]MWPW-167503:  select all during edit project

libs/blocks/text/text.css
Resolves: [MWPW-164756](https://jira.corp.adobe.com/browse/MWPW-164756)
**Test URLs:**
- Before: https://main--milo--adobecom.hlx.page/drafts/ratko/mwpw-164756/text?martech=off
- After: https://mwpw-164756-ol-inset-text--milo--adobecom.hlx.page/drafts/ratko/mwpw-164756/text?martech=off
=> MWPW-164756: Fix inset text ol

libs/blocks/merch-card/merch-card.js, nala/blocks/merchcard/merchcard.pages.js
Resolves: [MWPW-166878](https://jira.corp.adobe.com/browse/MWPW-166878)
* This should remove not only A link with empty content but any empty elements also from Merch cards.
**Test URLs:**
- After: https://MWPW-166878--milo--adobecom.hlx.page/?martech=off
**Test for consumer site:**
- Before: https://main--cc--adobecom.hlx.page/products/catalog?martech=off
- After: https://main--cc--adobecom.hlx.page/products/catalog?martech=off&milolibs=MWPW-166878
- Before: https://main--cc--adobecom.hlx.page/products/special-offers?martech=off
- After: https://main--cc--adobecom.hlx.page/products/special-offers?martech=off&milolibs=MWPW-166878
=> MWPW-166878: Remove the empty A link element left from icon

libs/blocks/adobetv/adobetv.js, libs/blocks/figure/figure.js, libs/utils/decorate.js, nala/blocks/video/video.page.js
This ensures that Sharepoint and MPC videos that aren't authored to be played automatically are paused when they are no longer in the viewport.
A few dev notes:
- although we already have a method to define intersection observers, it is currently set up to execute a callback only on intersection. For this requirement we need the exact opposite. I've fiddled around to augment the method from `utils.js`, but ultimately decided against it, since it created impractical overhead. We'd also have to call it twice under certain circumstances, since the `rootMargin` value is different;
- I've noticed that the `figure` block uses node cloning to decorate the content, I've created https://jira.corp.adobe.com/browse/MWPW-167455 to update this behavior
Resolves: …
=> [MWPW-161562] Auto pause videos

libs/blocks/global-navigation/global-navigation.css, libs/blocks/global-navigation/utilities/utilities.js
* Adding support for secondary CTA for new mobile gnav
Resolves: [MWPW-165807](https://jira.corp.adobe.com/browse/MWPW-165807)
**Test URLs:**
- After: https://mgnav-secondary-btn--milo--adobecom.aem.page/?martech=off
QA: https://main--homepage--adobecom.hlx.page/hu/homepage/index-loggedout?milolibs=mgnav-secondary-btn&newNav=true
=> Adding support for secondary CTA for new mobile gnav

libs/features/dynamic-navigation/status.js, test/features/dynamic-nav/status.test.js
* Adds a check for the feds nav wrapper element before appending. Error only occured on gnav v1 uses. 
Resolves: [MWPW-164470](https://jira.corp.adobe.com/browse/MWPW-164470)
**Test URLs:**
- After: https://console-error-dynamic-nav--milo--jasonhowellslavin.aem.page/?martech=off
To see that error is gone: 
https://main--bacom-blog--adobecom.hlx.live/fr/blog/the-latest/deliver-winning-campaigns-at-speed-and-scale-with-adobe-genstudio-for-performance-marketing?milolibs=console-error-dynamic-nav
=> MWPW-164470: Console error dynamic nav

libs/features/personalization/preview.js
Currently, the MEP button indicates the Target feature is "on" when it is actually set to 'postLCP'. 
Go to URL
Open MEP button
Check Target integration status in Page Info section.
Expected Results: Target integration feature is on
Actual Results: Target integration feature is postLCP
Resolves: [MWPW-167481](https://jira.corp.adobe.com/browse/MWPW-167481)
**Test URLs:**
- Psi-check: https://mepfixtargetmsg--milo--adobecom.aem.page/?martech=off
- Before: https://main--bacom--adobecom.hlx.page/products/adobe-analytics/customer-journey-analytics/actionable-intelligence
- After: https://main--bacom--adobecom.hlx.page/products/adobe-analytics/customer-journey-analytics/actionable-intelligence?milolibs=mepfixtargetmsg
=> [MEP] Update mep target message to include postlcp

libs/blocks/table/table.js, libs/features/icons/icons.css, test/blocks/table/mocks/body.html, test/blocks/table/table.test.js
This enables the user to close the tooltip with escape without shifting focus
Resolves: [MWPW-167312](https://jira.corp.adobe.com/browse/MWPW-167312)
**Test URLs:**
- After: https://tooltip-dismiss--milo--adobecom.aem.page/docs/library/kitchen-sink/table?martech=off
=> [MWPW-167312] tooltip dismiss escape

libs/blocks/aside/aside.css
Resolves: [MWPW-167292](https://jira.corp.adobe.com/browse/MWPW-167292)
**Milo:**
- Before: https://main--milo--adobecom.hlx.page/drafts/ratko/mwpw-167292/aside-promobar?martech=off
- After: https://mwpw-167292-aside-promobar-btn--milo--adobecom.hlx.page/drafts/ratko/mwpw-167292/aside-promobar?martech=off
=> MWPW-167292: Fix aside promobar buttons overflow

nala/blocks/accordion/accordion.test.js, nala/blocks/aside/aside.page.js, nala/blocks/aside/aside.test.js, nala/blocks/carousel/carousel.test.js, nala/blocks/chart/chart.test.js, nala/blocks/columns/columns.test.js, nala/blocks/figure/figure.test.js, nala/blocks/howto/howto.test.js, nala/blocks/marquee-anchors/marquee-anchors.test.js, nala/blocks/marquee/marquee.page.js, nala/blocks/marquee/marquee.test.js, nala/blocks/text/text.test.js, nala/blocks/video/video.test.js, nala/blocks/zpattern/zpattern.test.js, test/blocks/aside/aside.test.js, test/blocks/aside/mocks/standard.html
This PR removes skipA11yTest flag from tests where we can fix the a11y issue.
**Tests where skipA11yTest will be left on because of dark background class contrast issue with blue link:**
1. Aside - [Test Id - 11]
2. Marquee - [Test Id - 11], [Test id - 13]
3. Text - [Test Id - 6]
**Test where skipA11yTest will be left on because of Violation: Ensure all ARIA attributes have valid values**
1. Video - [Test Id - 4]
Resolves: [MWPW-165792](https://jira.corp.adobe.com/browse/MWPW-165792)
**Test URLs:**
- After: https://remove-skip-a11y-flags--milo--adobecom.aem.page/?martech=off
=> [MWPW-165792] - Remove skip a11y flags

libs/blocks/global-navigation/utilities/menu/menu.js
* Applying width of active gnav element after bolding of text is done
Resolves: [MWPW-165143](https://jira.corp.adobe.com/browse/MWPW-165143)
**Test URLs:**
- After: https://MWPW-165143--milo--adobecom.aem.page/?martech=off
QA: 
- Before: https://adobecom.github.io/nav-consumer/navigation.html?env=stage&authoringpath=/federal/dev/blaishram/learn-copy
- After: https://adobecom.github.io/nav-consumer/navigation.html?env=stage&authoringpath=/federal/dev/blaishram/learn-copy&navbranch=MWPW-165143
=> Apply width of active gnav element after bolding of text is done

libs/features/personalization/personalization.js, test/features/personalization/personalization.test.js
* Prevents modifying the absolute path to a script hosted in DAM when using insertScript action
Resolves: [MWPW-168109](https://jira.corp.adobe.com/browse/MWPW-168109)
**Test URLs:**
- Psi check: https://insert-script-abs-path--milo--adobecom.aem.page/?martech=off
QA links :
- Before: https://main--cc--adobecom.hlx.page/cc-shared/fragments/tests/2025/q1/insert-script-absolute-path/marquee
- After: https://main--cc--adobecom.hlx.page/cc-shared/fragments/tests/2025/q1/insert-script-absolute-path/marquee?milolibs=insert-script-abs-path ( you should see a h1  tag at the bottom of the page saying `I am an appended header via an external script!` and the network tab should show that test.js came from acom not the preview domain)
=> MWPW-168109: do not modify absolute path to a script hosted in DAM when using insertScript action

libs/blocks/chart/chartLightTheme.js
* Updates chart font family to match milo body font
* Fixes issue where incorrect font is sometimes seen on Safari
Resolves: [MWPW-165992](https://jira.corp.adobe.com/browse/MWPW-165992)
**Test URLs:**
- After: https://chart-font--milo--meganthecoder.aem.page/drafts/methomas/chart-two-up?martech=off
=> MWPW-165992 Fix Chart Font Family

.github/workflows/rcp-notifier.js
This updates the Slack message sent out for upcoming RCPs. Currently it sends the message on the correct days (13/6 days before) with the wrong remaining days (10/4 days).
Resolves: [MWPW-168268](https://jira.corp.adobe.com/browse/MWPW-168268)
**Test URLs:**
- After: https://rcp-msg-erratum--milo--overmyheadandbody.aem.page/?martech=off
=> [MWPW-168268] Correct RCP dates in Slack comms

libs/blocks/locui-create/locui-create.js
* Fix blocker for singe rollout functionality.
* For single rollout, list of urls are non editable and pre populated, locale are pre populated.
Resolves: [MWPW-168422](https://jira.corp.adobe.com/browse/MWPW-168422)
**Test URLs:**
- Before: https://milostudio-stage--milo--adobecom.hlx.page/drafts/sircar/locui-create?martech=off
- After: https://MWPW-168422-single-rollout-bug--milo--maagrawal16.hlx.page/drafts/sircar/locui-create?martech=off
=> [MWPW-168422] Fix for broken single rollout functionality

libs/features/personalization/personalization.js, test/features/personalization/normalizePath.test.js
This PR enhances the **normalizePath** function to ensure that hash values included in full URLs are retained.
- Retains Hash Values: Ensures that hash values in full URLs are preserved during normalization.
- Consistency: Aligns the handling of hash values with the existing path processing logic.
Resolves: [MWPW-167217](https://jira.corp.adobe.com/browse/MWPW-167217)
1. Using the before and after URLS, got to url and open dev tools.
**The expected gnav-source value(After)**: 
**The actual gnav-source value(Before)**:
**Test URLs:**
- Psi-check: https://meppreservehash--milo--adobecom.aem.page/?martech=off
- Before: https://main--cc--adobecom.hlx.page/products/catalog?mep=%2Fproducts%2Fcatalog.json--default---%2Fcc-shared%2Ffragments%2Fpromos%2F2025%2Famericas%2Fcci-all-apps-q1%2Fcci-all-a …
=> MWPW-167217 [MEP] preserve hash in normalizePath

libs/blocks/section-metadata/section-metadata.js, libs/styles/styles.css, test/blocks/section-metadata/mocks/body.html, test/blocks/section-metadata/section-meta.test.js
New feature that allows authors to set anchors using section metadata. The [previous PR](https://github.com/adobecom/milo/pull/3694) has been closed in favour of this approach.
Resolves: [MWPW-159511](https://jira.corp.adobe.com/browse/MWPW-159511)
**Test URLs:**
- After: https://anchor2--milo--narcis-radu.aem.page/?martech=off
Test URL - https://anchor2--milo--narcis-radu.aem.page/drafts/narcis/anchors/default
=> [MWPW-159511] Create anchor (ID) elements

libs/blocks/marketo/marketo-multi.js, libs/blocks/marketo/marketo.css, libs/blocks/marketo/marketo.js, test/blocks/marketo/marketo-multi.test.js, test/blocks/marketo/mocks/multi-step-2.html
* Marketo multi-step form with 2 & 3 step variations
Resolves: [MWPW-160954](https://jira.corp.adobe.com/browse/MWPW-160954)
**Test URLs:**
- Before: https://main--milo--adobecom.aem.page/drafts/bmarshal/marketo/multi-2?martech=off
- After: https://bmarshal-multi-step--milo--adobecom.aem.page/drafts/bmarshal/marketo/multi-2?martech=off
- Before: https://main--milo--adobecom.aem.page/drafts/bmarshal/marketo/multi-3?martech=off
- After: https://bmarshal-multi-step--milo--adobecom.aem.page/drafts/bmarshal/marketo/multi-3?martech=off
- Before: https://main--bacom--adobecom.hlx.live/request-consultation/experience-cloud?martech=off
- After: https://main--bacom--adobecom.hlx.live/request-consultation/experience-cloud?martech=off&milolibs=bmarshal-multi-step
=> MWPW-160954 Marketo Multi-step

libs/utils/utils.js
This resolves the issue where the youtube link was being processed into a block because the link was first in the paragraph and not text.
Resolves: [MWPW-162639](https://jira.corp.adobe.com/browse/MWPW-162639)
**Test URLs:**
- Before: https://main--milo--adobecom.aem.page/drafts/cpeyer/temp/og-issue?martech=off
- After: https://inline-youtube-link--milo--adobecom.aem.page/drafts/cpeyer/temp/og-issue?martech=off
=> [MWPW-162639] youtube block a tag fix

libs/navigation/package.json
* Upgrading standalone gnav version to 0.0.5
**Test URLs:**
- After: https://gnav-version--milo--adobecom.aem.page/?martech=off
=> Upgrading standalone gnav version to 0.0.5

libs/blocks/locui/loc/index.js, libs/blocks/locui/utils/franklin.js
Changes
1. When both aem and hlx page URLs are mixed in a project, an alert message is shown, prompting the user to enter either one of them, but not both.
2. When a mismatch is found between the project URL (e.g., Sidekick) and the page URLs in the project, the page is redirected appropriately to avoid displaying "Page Not Found" messages.
3. Helix Admin URLs are also updated to use either aem.page or hlx.page.
Resolves: [MWPW-166940](https://jira.corp.adobe.com/browse/MWPW-166940)
**Test URLs:**
- Before: https://locui--milo--adobecom.aem.page/tools/loc?ref=main&repo=milo&owner=adobecom&host=milo.adobe.com&project=Milo&referrer=https%3A%2F%2Fadobe.sharepoint.com%2F%3Ax%3A%2Fr%2Fsites%2Fadobecom%2F_layouts%2F15%2FDoc.aspx%3Fsourcedoc%3D%257B21a05280-fe1b-4d36-84cc-e301c6416083%257D%26acti …
=> [LOC UI] MWPW-166940 Hlx5 - Handling mixed URLs in Loc Urls and mismatch in project and page urls

libs/blocks/marketo/marketo.js
* Allow setting Marketo POI values on the block level
Resolves: [MWPW-167928](https://jira.corp.adobe.com/browse/MWPW-167928)
**Test URLs:**
- Before: https://main--milo--adobecom.aem.page/drafts/bmarshal/marketo/poi?martech=off&preview=1
- After: https://bmarshal-poi--milo--adobecom.aem.page/drafts/bmarshal/marketo/poi?martech=off&preview=1
=> MWPW-167928 Override Marketo POI

.github/workflows/merge-to-stage.js
In an effort to keep up efficiency within this automated label driven pipeline, we want to start merging PRs in the same batch despite file overlaps. As discussed in https://github.com/orgs/adobecom/discussions/3722
Resolves: [MWPW-168512](https://jira.corp.adobe.com/browse/MWPW-168512)
**Test URLs:**
- After: https://remove-file-overlap-wf--milo--mokimo.aem.page/?martech=off
=> Remove file overlap condition from merge to stage workflow

libs/blocks/global-navigation/base.css
* Adding a class to convert group link title to a simple header instead of link
* And hide the chevron icon
Resolves: [MWPW-168548](https://jira.corp.adobe.com/browse/MWPW-168548)
**Test URLs:**
- After: https://link-group-header--milo--adobecom.aem.page/?martech=off
QA: https://business.stage.adobe.com/?milolibs=link-group-header
=> Adding a class to convert group link title to a simple header instead of a link

libs/blocks/adobetv/adobetv.js, libs/blocks/modal/modal.css, libs/blocks/modal/modal.js, test/blocks/modals/modals.test.js
This ensures all elements within a modal window are focusable and that focus seamlessly loops through them.
Additionally, it fixes an issue that is logging a console error when a modal containing an MPC video is closed.
QA note: this change adds the close button a bit earlier in the markup. I wasn't able to find proof that this has any impact, but it should be checked nevertheless.
Resolves: [MWPW-167752](https://jira.corp.adobe.com/browse/MWPW-167752)
**Test URLs:**
- Before: https://main--milo--overmyheadandbody.aem.page/drafts/ramuntea/accessibility/mpc-in-modal?martech=off
- After: https://loop-modal-focus--milo--overmyheadandbody.aem.page/drafts/ramuntea/accessibility/mpc-in-modal?martech=off
**Initial page where issue was reported, click "Watch the video":**
- Before: …
=> [MWPW-167752] Loop focus in modals containing iframes

libs/blocks/preflight/panels/general.js
* Adds a check for urls picked up while using the preflight tool to see if they are part of the AEM EDS / Helix 5 content bus
Resolves: [MWPW-163228](https://jira.corp.adobe.com/browse/MWPW-163228)
**Test URLs:**
- After: https://preflight-svg-issue--milo--jasonhowellslavin.aem.page/?martech=off
The SVG will not load in milo, in order to test it should be done on bacom in the following pages:
- https://main--bacom--adobecom.hlx.page/products/journey-optimizer/journey-orchestration
- https://main--bacom--adobecom.hlx.page/products/journey-optimizer/journey-orchestration?milolibs=preflight-svg-issue
=> MWPW-163228: Preflight svg issue

tools/floodgate/js/config.js, tools/loc/config.js, tools/loc/utils.js
* Added check for `referrer` query param when starting localization process
Resolves: [MWPW-151376](https://jira.corp.adobe.com/browse/MWPW-151376)
Kodiak tiket: https://jira.corp.adobe.com/browse/MWPW-144376
**Test URLs:**
- After: https://mwpw-151376-security-ssrf--milo--adobecom.aem.page/?martech=off
[Test url](https://mwpw-151376-security-ssrf--milo--adobecom.hlx.page/tools/loc/index.html?project=milo--adobecom&referrer=https%3A%2F%2Fadobe.sharepoint.com%2F%3Ax%3A%2Fr%2Fsites%2Fadobecom%2F_layouts%2F15%2FDoc.aspx%3Fsourcedoc%3D%257Bdea6e39b-6f38-4471-9239-54af68cd1463%257D%26action%3Deditnew)
=> MWPW-151376: Check sharepoint url

libs/blocks/hero-marquee/hero-marquee.css
This ensures that the background image of a Hero Marquee is glued to the bottom of the block on tablet devices when the `bg-bottom-tablet` variant is applied. There were a few ways to achieve this, but ultimately I decided to follow the strategy already used for mobile on [L291](https://github.com/overmyheadandbody/milo/blob/6e63771a3a717070b79447f67335c0e10cd62681/libs/blocks/hero-marquee/hero-marquee.css#L291).
The file had quite a lot of extra space characters which got removed, the only code difference is on [L325](https://github.com/overmyheadandbody/milo/blob/6e63771a3a717070b79447f67335c0e10cd62681/libs/blocks/hero-marquee/hero-marquee.css#L325).
Before | After
--- | ---
Resolves: [MWPW-167759](https://jira.corp.adobe.com/browse/MWPW-167759)
**Test URLs:**
- Before: …
=> [MWPW-167759] Hero marquee bg-bottom-tablet fix

libs/blocks/article-header/article-header.css, libs/blocks/article-header/article-header.js, test/blocks/article-header/article-header.test.js, test/blocks/article-header/mocks/body-video.html
* Allow videos in the Article Header
* Has the same video features across milo: https://milo.adobe.com/docs/authoring/videos (with the exception that uploaded mp4s aren't supported in DA)
Resolves: [MWPW-166689](https://jira.corp.adobe.com/browse/MWPW-166689)
**Test URLs:**
MP4:
- Before: https://main--milo--adobecom.aem.page/drafts/methomas/article-header-mp4?martech=off
- After: https://article-header-video--milo--meganthecoder.aem.page/drafts/methomas/article-header-mp4?martech=off
More examples in comment below
=> MWPW-166689 Add video support to Article Header

libs/blocks/global-navigation/global-navigation.css
Brief description of the issue:
Gnav Promo CTA overflowing issue - BACOM Global Nav
Resolves: [MWPW-163320](https://jira.corp.adobe.com/browse/MWPW-163320)
**Test URLs:**
- After: https://mwpw-163320--milo--patel-prince.aem.page/?martech=off
**QA URL:**
Before: https://main--bacom--adobecom.hlx.page/es?martech=off
After: https://main--bacom--adobecom.hlx.page/es/?milolibs=mwpw-163320--milo--patel-prince
=> MWPW-163320 Gnav Promo CTA overflowing issue - BACOM Global Nav

libs/blocks/locui-create/utils/utils.js
* Bug Fix: On editing the translation project all the preselected Action for the languages and workflow will get deselected and Action will set to "Rollout".
Resolves: [MWPW-169281](https://jira.corp.adobe.com/browse/MWPW-169281)
**Test URLs:**
- After: https://mwpw-168684-single-language-rollout--milo--adobecom.aem.page/?martech=off
=> [MWPW-169281] Bug fix for edit workflow

libs/blocks/chart/chartLightTheme.js
* Have Chart inherit the font family rather than it being explicitly set
* Follow-up from https://github.com/adobecom/milo/pull/3685#discussion_r1963743810
Resolves: [MWPW-165992](https://jira.corp.adobe.com/browse/MWPW-165992)
**Test URLs:**
- Before: https://stage--milo--meganthecoder.aem.page/drafts/methomas/chart-two-up?martech=off
- After: https://chart-font-inherit--milo--meganthecoder.aem.page/drafts/methomas/chart-two-up?martech=off
=> MWPW-165992 Chart inherit font

libs/features/branch-quick-links/branch-quick-links.js
* Fixed the ecid value getting concatenated with other params in branch quick links
Resolves: [MWPW-168637](https://jira.corp.adobe.com/browse/MWPW-168637)
**Test URLs:**
- Before: https://main--milo--adobecom.aem.live/drafts/drashti/milo-banner/ql-noloader
- After: https://ecid-query--milo--drashti1712.aem.live/drafts/drashti/milo-banner/ql-noloader
=> [MWPW-168637] paramaters appended to ecid value - bug fix

libs/utils/sidekick.js
* The preflight listener is now debounced as it was being called multiple times creating two dom nodes for preflight modal.
Resolves: [MWPW-167810](https://jira.corp.adobe.com/browse/MWPW-167810)
**Test URLs:**
- Before: https://main--milo--adobecom.aem.page/drafts/sharathkannan/video-accessibility/fragments/hero-marquee1?martech=off
- After: https://mwpw-167810--milosh--sharath-kannan.aem.page/drafts/sharathkannan/video-accessibility/fragments/hero-marquee1?martech=off
=> Fix(MWPW-167810): Sidekick preflight - Lorem ipsum bug.

libs/blocks/global-navigation/global-navigation.js, libs/utils/utils.js
* Moving getGnavSource back to utils as DME team is consuming it through utils.js
**Test URLs:**
- After: https://gnav-source--milo--adobecom.aem.page/?martech=off
QA: 
- https://stage--dme-partners--adobecom.hlx.page/channelpartners/home/?milolibs=gnav-source
- https://main--cc--adobecom.hlx.page/products/catalog?milolibs=gnav-source
=> Moving getGnavSource back to utils

libs/blocks/global-navigation/global-navigation.js
Profile menu complex config for standalone Gnav
* This is required by Adobe Home to enable static local section in profile menu
Resolves: [MWPW-167523](https://jira.corp.adobe.com/browse/MWPW-167523)
**Test URLs:**
- After: https://mwpw167523--milo--adobecom.aem.page/?martech=off
=> Profile menu complex config for standalone Gnav

libs/blocks/caas/utils.js
This PR introduces a new query parameter value (`alpha`) that allows loading the alpha version of CaaS assets directly from GitHub Pages. This enables automated testing of pre-release CaaS code before it is merged and deployed.  
- Check for the `alpha` query parameter value in `loadCaasFiles`.  
- If present, update `cssFile` and `jsFile` to point to the latest alpha assets on GitHub Pages.  
- This allows testing new CaaS code without requiring a full release.  
Currently, there's no easy way to test pre-PR CaaS code before release. By adding this query parameter, we can pull the alpha version of CaaS and validate changes via automation before merging into production.  
- Append `?caasver=alpha` to the URL and verify that the CaaS alpha assets are loaded.  
- Ensure the existing …
=> feat(MWPW-168628): Add support for loading CaaS alpha releases via query parameter

libs/blocks/accordion/accordion.css, libs/blocks/accordion/accordion.js
Improve accessibility of expand-all-button feature in accordion block:
* Offset keyboard focus
* Move focus on button click
* Remove disabled button from tab order
Resolves: [MWPW-166497](https://jira.corp.adobe.com/browse/MWPW-166497)
**Test URLs:**
- Before: https://main--milo--adobecom.aem.page/drafts/methomas/accordion-open-all
- After: https://accordion-expand-focus--milo--meganthecoder.aem.page/drafts/methomas/accordion-open-all?martech=off
=> MWPW-166497 [Accordion] Improve Expand All Button Accessibility

libs/blocks/media/media.css
This updates the list styles inside the Media block to fix an alignment issue for multiline list items. It also ensures RTL is correctly supported.
The suggested changes don't match Figma specs, as all lists are currently being analyzed from a design perspective; we'll be getting a more comprehensive list of updates once that is concluded. Additional details are available in the comments section of the story. However, these suggested updates make it easier to update styles in the future.
Before | After
--- | ---
Resolves: [MWPW-167137](https://jira.corp.adobe.com/browse/MWPW-167137)
**Test URLs:**
- Before: https://main--milo--overmyheadandbody.hlx.page/drafts/ramuntea/media-list-alignment?martech=off
- After: https://li-in-media--milo--overmyheadandbody.hlx.page/drafts/ramuntea/media-list …
=> [MWPW-167137] LI alignment in Media block

libs/blocks/aside/aside.css
* Img css rule made specific to accessibility controls.
Resolves: [MWPW-169096](https://jira.corp.adobe.com/browse/MWPW-169096)
**Test URLs:**
- Before: https://main--milo--adobecom.aem.page/drafts/vmorel/bug-aside-split-one-third-missing?martech=off
- After: https://mwpw-169096--milosh--sharath-kannan.aem.page/drafts/vmorel/bug-aside-split-one-third-missing?martech=off
=> Fix(MWPW-169096): Aside split no longer has 1/3 as default with images.

libs/blocks/section-metadata/section-metadata.js, libs/features/personalization/personalization.js, test/features/personalization/mocks/personalization.html, test/features/personalization/modifyNonFragmentSelector.test.js, test/features/personalization/personalization.test.js
* Expand `anchor` `section-metadata` property to MEP
`anchor` property adds `id` to the section
Section is targeted with `id` selector
Resolves: [MWPW-164462](https://jira.corp.adobe.com/browse/MWPW-164462)
**Test URLs:**
- Before: https://main--milo--adobecom.aem.page/drafts/ratko/marquee-container/demo/marquee-container-demo?martech=off
- After: https://mwpw-164462-marquee-container2--milo--adobecom.aem.page/drafts/ratko/marquee-container/demo/marquee-container-demo?martech=off
[Manifest](https://adobe.sharepoint.com/:x:/r/sites/adobecom/_layouts/15/doc2.aspx?sourcedoc=%7BB12B9C30-FBF1-45F9-8689-835C919160A6%7D&file=personalization.xlsx&action=default&mobileredirect=true)
**NOTE:** Manifest option `param-five=true` looks broken because heading element is target and swapped (just wanted …
=> MWPW-164462 [MEP] Add ability for MEP to select sections by section-metadata anchor value 

libs/features/personalization/personalization.js, test/features/personalization/normalizePath.test.js
Marked high priority because it is causing issues in live personalization
* Remove #_dnt from hash in normalize path
Resolves: [MWPW-169629 [MEP] DNT hash should not be preserved like other hashes](https://jira.corp.adobe.com/browse/MWPW-169629)
**Test URLs:**
Example 1: sticky banner does not work in before link (scroll down to test)
- Before: https://main--cc--adobecom.aem.page/products/illustrator?audience=edu&mep=%2Fproducts%2Fillustrator.json--target-edu_pzn
- After: https://main--cc--adobecom.aem.page/products/illustrator?audience=edu&mep=%2Fproducts%2Fillustrator.json--target-edu_pzn&milolibs=mepdontpreservednt&martech=off
Example 2: page is blank and does not render in before link
- Before: https://main--cc--adobecom.aem.page/uk/products/photoshop?mep=%2Fcc-shared%2Ffragments%2Ftes …
=> MWPW-169629 [MEP] DNT hash should not be preserved like other hashes

libs/blocks/global-footer/global-footer.js, libs/navigation/bootstrapper.js, libs/navigation/navigation.js
* Adding onError and onReady call specific to header and footer component
* Since footer's init has a setTimeout, we cannot call the onError and onReady like header in the try/catch. It has to be called from the component itself.
Resolves: [MWPW-159105](https://jira.corp.adobe.com/browse/MWPW-159105)
**Test URLs:**
- After: https://footer-callback--milo--adobecom.aem.page/?martech=off
QA: https://adobecom.github.io/nav-consumer/?env=stage&authoringpath=/federal/home&navbranch=footer-callback
=> Adding onReady and onError callback for standalone footer

libs/blocks/modal/modal.js
* Fix focus in georouting modal with tabs
Resolves: [MWPW-167748](https://jira.corp.adobe.com/browse/MWPW-167748)
**Test URLs:**
- After: https://geo-focus--milo--meganthecoder.aem.page/?martech=off
Bacom:
- https://main--bacom--adobecom.aem.live/?milolibs=geo-focus--milo--meganthecoder&akamaiLocale=IN
=> MWPW-167748 Fix focus in georouting modal with tabs

libs/blocks/global-navigation/global-navigation.js
Adding countryCode config to UNav for the cart component, which will be used for logged out users
Resolves: [MWPW-169371](https://jira.corp.adobe.com/browse/MWPW-169371)
**Test URLs:**
- After: https://gnav--milo--adobecom.aem.page/?martech=off
=> MWPW-169371 : Adding countryCode config to UNav

libs/blocks/preflight/panels/seo.js
This PR is fixing the SEO links check from Preflight
Resolves: [MWPW-169500](https://jira.corp.adobe.com/browse/MWPW-169500)
1. Open preflight
2. Open the SEO tab
3. Wait for the links check to finish
**Before:**
**After:**
**Milo:**
- Before: https://main--milo--adobecom.aem.page/drafts/rbogos/page-default?martech=off
- After: https://mwpw-169500-preflight--milo--adobecom.aem.page/drafts/rbogos/page-default?martech=off
=> [MWPW-169500] SEO- Links check failing breaks Preflight

libs/navigation/navigation.js
* Added some logic to determine whether to use `www.adobe.com` or `www.stage.adobe.com` for the standalone gnav 
* There's some defensive logic in case the env is neither stage nor prod.
Resolves: [MWPW-169732](https://jira.corp.adobe.com/browse/MWPW-169732)
**Test URLs:**
- After: https://standalone-prod-content--milo--adobecom.aem.page/?martech=off
qa url: https://adobecom.github.io/nav-consumer/navigation.html?env=stage&navbranch=standalone-prod-content
=> MWPW-169732 Fetch resources from adobe.com/federal instead of https://main--federal--adobecom.aem.live/federal

libs/blocks/caas-config/caas-config.js
Description:
Adds a new option to the Default Text Caas Card collection options in the MIlo Configurator
Resolves: [MWPW-169194](https://jira.corp.adobe.com/browse/MWPW-169194)
**Test URLs:**
- Before: https://main--milo--adobecom.aem.page/drafts/cmiqueo/test-page?martech=off
- After: https://MWPW-169194--milo--adobecom.aem.page/drafts/cmiqueo/test-page?martech=off
=> MWPW-169194: adds new detailText option for staticDate

libs/blocks/global-navigation/global-navigation.css
Merges https://github.com/adobecom/milo/pull/3630 to prod.
- After: https://3630-to-prod--milo--adobecom.aem.live/?martech=off
=> MWPW-167191 Removed an unnecessary css url() that was causing a console error

libs/scripts/delayed.js
Updated domains for `adobe.com`, `hlx.page`, `aem.page`, `hlx.live`, and `aem.live` as part of the UAT OneTrust upgrade. Additionally, the `privacy-standalone.js` script is now sourced from the AEM build. For testing on the stage environment on milo, the script URL from the dev01 AEM domain was added.
Resolves: [MWPW-158311](https://jira.corp.adobe.com/browse/MWPW-158311)
**Test URLs:**
- After: https://mwpw-158311--milo--deva309.aem.page/?martech=off
QA:
https://main--cc--adobecom.hlx.page/creativecloud?milolibs=mwpw-158311--milo--deva309&privacyEnv=dev02
https://main--cc--adobecom.hlx.page/creativecloud?milolibs=mwpw-158311--milo--deva309&privacyEnv=dev01
=> [MWPW-158311] - Onetrust uat upgrade

libs/blocks/preflight/panels/seo.js
This PR is fixing the SEO _lorem ipsum_ check from Preflight, where lower case _lorem ipsum_ is not detected.
Resolves: [MWPW-169501](https://jira.corp.adobe.com/browse/MWPW-169501)
1. Open preflight
2. Open the SEO tab
3. See the _lorem ipsum_ check
**Before:**
**After:**
PSI check URL:  https://mwpw-169501-preflight--milo--adobecom.aem.page/drafts/rbogos/page-default?martech=off
**Milo:**
- Before: https://main--milo--adobecom.aem.page/drafts/rbogos/lorem-ipsum?martech=off
- After: https://mwpw-169501-preflight--milo--adobecom.aem.page/drafts/rbogos/lorem-ipsum?martech=off
=> [MWPW-169501] SEO- Fixed Lorem ipsum check on Preflight

.github/workflows/README.md, .github/workflows/code-compatibility.yaml, .github/workflows/codeql.yml, .github/workflows/dispatch.yml, .github/workflows/fg-sync-repos.yml, .github/workflows/high-impact-alert.yml, .github/workflows/label-zero-impact.yaml, .github/workflows/mark-stale-prs.yaml, .github/workflows/merge-to-main.yaml, .github/workflows/merge-to-stage.yaml, .github/workflows/pr-reminders.yaml, .github/workflows/rcp-notifier.yml, .github/workflows/release-standalone-feds.yml, .github/workflows/run-lint.yaml, .github/workflows/run-mas-tests.yaml, .github/workflows/run-nala-default.yml, .github/workflows/run-nala-milolibs.yaml, .github/workflows/run-nala.yml, .github/workflows/run-tests.yaml, .github/workflows/servicenow.yaml, .github/workflows/update-dependencies.yaml
Following this [incident](https://www.wiz.io/blog/github-action-tj-actions-changed-files-supply-chain-attack-cve-2025-30066) we want to harden the security for our Github actions by [pinning actions](https://docs.github.com/en/actions/security-for-github-actions/security-guides/security-hardening-for-github-actions#using-third-party-actions) to full length commit SHAs. Its the recommended approach in terms of security from Github and while we won't get any minor versions OOTB, security and stability is more important than the latest and greatest features in this case.
Resolves: [MWPW-169958](https://jira.corp.adobe.com/browse/MWPW-169958)
Checkout https://github.com/actions/checkout/commit/11bd71901bbe5b1630ceea73d27597364c9af683
CodeQL …
=> Harden Github Action security by pinning to commit SHAs (versions)

libs/blocks/global-navigation/global-navigation.css
Reverts adobecom/milo#3815
https://github.com/adobecom/milo/pull/3819#pullrequestreview-2706717736 
This functionality was not tested on firefox + phone + RTL locales. 
As a result of this PR, firefox is added to device automation. @spadmasa 
**Test URLs:**
- After: https://revert-3815-mwpw-161097-fix--milo--patel-prince.aem.page/?martech=off
=> Revert "Tooltips are hidden while hovering over top four icons on Safari browser."

libs/blocks/tabs/tabs.css
* Prevent inheriting radio tab button text `color` from pill tab if nested
* Disable `text-shadow` set by pill if nested
Resolves: [MWPW-170114](https://jira.corp.adobe.com/browse/MWPW-170114)
**Test URLs:**
- Before: https://main--adobecom.hlx.page/docs/library/kitchen-sink/tab-block?martech=off
- After: https://mwpw-170114-nested-radio-btn--milo--adobecom.hlx.page/docs/library/kitchen-sink/tab-block?martech=off
- Before: https://main--cc--adobecom.hlx.page/cc-shared/fragments/creativecloud/all-apps/tutorials-tabs-blade
- After: https://main--cc--adobecom.hlx.page/cc-shared/fragments/creativecloud/all-apps/tutorials-tabs-blade?milolibs=MWPW-170114-nested-radio-btn
**NOTE:** Changes are not visible on kitchen sink link because there is no radio tab nested inside pill tab …
=> MWPW-170114: Fix nested radion btn text color

libs/mep/emea1435/susi-light/susi-light.css, libs/mep/emea1435/susi-light/susi-light.js
* Copying Express susi-light block into Milo MEP test folder to more easily assess the LOE on testing this on a CC page
Marked as high priority as test development is blocked until the code is merged.
Resolves: [OPT-31058](https://jira.corp.adobe.com/browse/OPT-31058)
**Test URLs:**
- After: https://emea1435--milo--adobecom.aem.page/?martech=off
=> [OPT-31058] Test block support for EMEA-1435

libs/blocks/preflight/panels/accessibility.js, libs/blocks/preflight/panels/assets.js, libs/blocks/preflight/panels/seo.js, libs/blocks/preflight/preflight.css, libs/blocks/preflight/preflight.js
This proposes a new Assets tab for the Preflight tool to enable authors to easily check whether the image assets on a page are meeting our [asset governance](https://milo.adobe.com/docs/authoring/asset-governance) recommendations. In short, the images need to be uploaded at 2x (or 1.5x for full width images) the size of the area they will be used in.
There are two layers to how (mis)matches are communicated, detailed below.
This clearly separates the images into two categories: those that match and those that don't match the asset governance rules. A multiplication factor is outlined, along with uploaded image size, the size at which it is displayed and its recommended size (in case of a mismatch).
Once the Preflight modal is closed, the image details are added over each individual image, …
=> [MWPW-168529] New Assets tab in Preflight

libs/blocks/preflight/preflight.css
Adjusting the `max-height `limit so Preflight doesn't truncate/cut off sections with a long list of items.
Resolves: [MWPW-160751](https://jira.corp.adobe.com/browse/MWPW-160751)
**Test URLs:**
- After: https://preflight-scrolling--milo--adobecom.hlx.page/?martech=off
**Homepage Test URLs:**
- Before: https://main--homepage--adobecom.hlx.page/kr/homepage/index-loggedout?martech=off
- After: https://main--homepage--adobecom.hlx.page/kr/homepage/index-loggedout?milolibs=preflight-scrolling&martech=off
**Testing notes:**
- Open a page that has a lot of fragments being used (10+). 
- Launch Preflight.
- Under the general tab, you should see the full list of fragments. The section shouldn't be truncated/cut off.
- The homepage test …
=> MWPW-160751 - Preflight - Adjust section height limit

libs/blocks/mas-autoblock/mas-autoblock.js
Resolves: [MWPW-169084](https://jira.corp.adobe.com/browse/MWPW-169084)
**Test URLs:**
- Before: https://main--milo--adobecom.aem.page/drafts/seanchoi/merch-card-comm?martech=off
- After: https://MWPW-169084--milo--adobecom.aem.page/drafts/seanchoi/merch-card-comm?martech=off
=> MWPW-169084: mas-autoblock to listen ?query as well.

libs/features/personalization/personalization.js, test/features/personalization/actions.test.js, test/features/personalization/mocks/actions/manifestUpdateAttribute.json, test/features/personalization/mocks/personalization.html
Resolves: [MWPW-169943](https://jira.corp.adobe.com/browse/MWPW-169943)
**Test URLs:**
- After: https://placeholders-updateAttribute4--milo--adobecom.aem.page/?martech=off
Before: https://main--cc--adobecom.aem.page/drafts/mepdev/fragments/2025/q2/mepattributeplaceholder/
After: https://main--cc--adobecom.aem.page/drafts/mepdev/fragments/2025/q2/mepattributeplaceholder/?milolibs=placeholders-updateAttribute4
Note how in the "Before URL" the aria-label value of the blue button in the marquee is the place-holder code: {{my-aria-test}}
But in the After URL, it is the placeholder value "Hello world" per the manifest value.
=> MWPW-169943 [MEP] add ability to use placeholders in updateAttribute

libs/features/personalization/preview.js
This update enables the MEP button to display a spoofed target integration status(i.e., target was set via query parameters), if one is available, and if not, it will continue to show the actual target integration status. 
Steps to QA:
Navigate to the before and after links below and check the Target Integration status on the MEP button:
-Expected(After): 'Target Integration   Off'
-Actual(Before): 'Target Integration    On'
Note: to confirm that mmm is not impacted by this PR and is still only reporting the actual target integration status, I overwrote the preview.js file in my browser, navigated to the photoshop page with ?target=off in the URL, and then checked status listed on the MMM page to confirm that it is still set to "On":
Resolves: …
=> MWPW-169423 [MEP] MEP button not reporting spoofed Target value

libs/features/personalization/personalization.js, test/features/personalization/cleanAndSortManifestList.test.js, test/features/personalization/mocks/manifestLists/two-manifests-one-from-target.json, test/utils/utils.test.js
* MEP Button manifest links: made sure that non-target manifest urls match with the the current domain
Resolves: [MWPW-169160](https://jira.corp.adobe.com/browse/MWPW-169160)
Instructions:
Toggle MEP button and hover over [manifest_name].json link. In BEFORE you will see link has .hlx. in it, which doesn't match the current url(with .aem. instead of .hlx.). In AFTER you will see matching domain.
- Before: https://main--cc--adobecom.aem.page/drafts/dfedotov/marquee?target=on&mep
- After: https://main--cc--adobecom.aem.page/drafts/dfedotov/marquee?target=on&milolibs=mep-manifest-links&mep
- Psi-check: https://mep-manifest-links--milo--adobecom.aem.page/?martech=off
=> MWPW-169160 [MEP] MEP button - made sure that non-target manifest paths match the current domain

libs/navigation/package.json
* Upgrading standalone gnav version to 0.0.7
**Test URLs:**
- After: https://gnav-version--milo--adobecom.aem.page/?martech=off
=> Upgrading package version for bundled gnav to 0.0.7

libs/blocks/global-footer/global-footer.css
* Fix horizontal scroll bug that occurs on Windows Chrome from window widths 1504px - 1520px
* Caused by the global footer
Resolves: [MWPW-170007](https://jira.corp.adobe.com/browse/MWPW-170007)
**Test URLs:**
- Before: https://main--milo--adobecom.aem.page/drafts/methomas/default?martech=off
- After: https://horz-scroll--milo--meganthecoder.aem.page/drafts/methomas/default?martech=off
Bacom: https://main--bacom--adobecom.aem.live/?milolibs=horz-scroll--milo--meganthecoder
CC: https://main--cc--adobecom.aem.live/products/photoshop?milolibs=horz-scroll--milo--meganthecoder
DC: https://main--dc--adobecom.aem.live/acrobat/business?milolibs=horz-scroll--milo--meganthecoder
=> MWPW-170007 [Footer] Fix horizontal scroll

libs/blocks/table/table.js
Expand / Collapse functionality is not working on 3-column tables on mobile devices. 
Resolves: [MWPW-170340](https://jira.corp.adobe.com/browse/MWPW-170340)
**Test URLs:**
- Before: https://main--milo--adobecom.aem.page/drafts/gunn/mwpw-170340?martech=off
- After: https://mwpw-170340--milo--adobecom.aem.page/drafts/gunn/mwpw-170340?martech=off
- Before: https://main--milo--adobecom.aem.page/drafts/gunn/mwpw-170340-3?martech=off
- After: https://mwpw-170340--milo--adobecom.aem.page/drafts/gunn/mwpw-170340-3?martech=off
- Before: https://main--milo--adobecom.aem.page/drafts/gunn/mwpw-170340-merch?martech=off
- After: https://mwpw-170340--milo--adobecom.aem.page/drafts/gunn/mwpw-170340-merch?martech=off
=> MWPW-170340 Table Block Expand / Collapse Functionality Broken on Mobiles

libs/utils/utils.js
MWPW-170254 Placeholder are not getting replaced for aria-label
Adding functionality to read all the attributes in an element node to be replaced for placeholders.
Resolves: [MWPW-170254](https://jira.corp.adobe.com/browse/MWPW-NUMBER)
**Test URLs:**
Before: https://main--cc--adobecom.aem.live/drafts/suhjain/placeholder/placeholder
After: https://placeholder--milo--suhjainadobe.aem.live?martech=off
**Test URLs for placeholders:**
Before: https://main--cc--adobecom.aem.live/drafts/suhjain/placeholder/placeholder
After: https://main--cc--adobecom.aem.live/drafts/suhjain/placeholder/placeholder?milolibs=placeholder--milo--suhjainadobe
=> MWPW-170254 Placeholder are not getting replaced for aria-label

libs/blocks/notification/notification.css, libs/blocks/notification/notification.js, package.json, test/blocks/notification/mocks/body.html, test/blocks/notification/notification.test.js
Change box shadow for new split notification variant created for https://jira.corp.adobe.com/browse/MWPW-169814
Clicking a button in notification authored with #_close will close the notification block.
Resolves: [MWPW-169814](https://jira.corp.adobe.com/browse/MWPW-169814) | [MWPW-170780](https://jira.corp.adobe.com/browse/MWPW-170780)
**Test URLs:**
- Before: https://main--milo--adobecom.aem.page/drafts/mathuria/promobar/creativecloud?martech=off
- After: https://mwpw-170780--milo--adobecom.aem.page/drafts/mathuria/promobar/creativecloud?martech=off
=> MWPW-169814 | Change box shadow and button to close for split notification

libs/features/personalization/preview.css, libs/features/personalization/preview.js
Fixes MEP button width with long manifests names. Adds a title hover to each option. Options will still be wider than the overlay as they can't be styled.
Resolves: [MWPW-170917](https://jira.corp.adobe.com/browse/MWPW-170917)
**Test URLs:**
- Before: https://main--cc--adobecom.aem.page/drafts/mepdev/fragments/2025/q2/mep-button-options-fix/marquee
- After: https://main--cc--adobecom.aem.page/drafts/mepdev/fragments/2025/q2/mep-button-options-fix/marquee?milolibs=mep-button-options-fix
https://mep-button-options-fix--milo--adobecom.hlx.live/&martech=off
=> Initial checkin. Good state.

.github/workflows/pr-merge-notification.yaml
This [newly introduced workflow](https://github.com/adobecom/milo/pull/3838) runs well in isolation, however not on the CI as the script name changed during development.
**Test URLs:**
- After: https://fix-merge-to-stage--milo--adobecom.aem.page/?martech=off
=> Fix the pr merge notification workflow

.github/workflows/pr-merge-notification.yaml
To properly access secrets from forks, we'll need to run the action on the _target_ branch (stage) since forks are not passed any secrets. Thanks @overmyheadandbody to initially find this little gem within his high-impact label workflow.
**Test URLs:**
- After: https://use-pull-request-target--milo--adobecom.aem.page/?martech=off
=> Use pull_request_target to properly access secrets

.github/workflows/dynamic-pr-template.yml
* The replace regex is not matching with the test url header and appending the test urls every time it runs
* So, updated the regex to match the header correctly
Test PR - https://github.com/bandana147/milo/pull/10 - Rerunning the dynamic template workflow in this PR will not append the test urls.
**Test URLs:**
- After: https://gnav-dynamic-pr--milo--adobecom.aem.page/?martech=off
=> Gnav dynamic pr updating replace regex

libs/blocks/table/table.css, libs/blocks/table/table.js, test/blocks/table/table.test.js
This resolves the issue where aria-labels were missing from Table CTA's, the main problem here was that Table.js and Merch.js are being executed in parallel and in the Table.js we were earlier using innerHtml to change the Table when the user resized or filtered the the tables in mobile mode, this caused the aria-labels that were being set in Merch.js to be set on the old table which was being replaced with a new table in Table.js, also columns were being removed from the DOM in curtain situations which was an additional problem causing the removal of aria-labels.
**Dev Notes**
Leaving this part in`.table .hide-mobile {
display: none !important;
}`. We would need to list at least 5 classes with high css specificity to override the display properties of some elements that need to be …
=> [MWPW-169395] - Table aria labels missing

libs/blocks/global-navigation/dark-nav.css
* This commit went in feds-standalone 0.0.6 as a hotfix but is missing in 0.0.7. We need to merge it to stage to get it into 0.0.7
**Test URLs:**
- After: https://dark-gnav-gradient--milo--adobecom.aem.page/?martech=off
=> Fix the gradient feds navLink on dark mode

libs/blocks/graybox/graybox.js
* Adds support for screen size MEP previewing
* Hides the MEP button on the device previews
Resolves: [MWPW-170088](https://jira.corp.adobe.com/browse/MWPW-170088)
For the test page below, view the previews for phone and tablet to see the changes
**Test URLs:**
- Before: https://main--milo--adobecom.aem.page/drafts/cpeyer/graybox/graybox-changed
- After: https://mwpw-170088--milo--adobecom.aem.page/drafts/cpeyer/graybox/graybox-changed
=> MWPW-170088 Graybox MEP support

libs/blocks/global-navigation/dark-nav.css
* Making mobile and desktop background color consistent for Gnav
Resolves: [MWPW-169322](https://jira.corp.adobe.com/browse/MWPW-169322)
**Test URLs:**
- After: https://mgnav-bgcolor--milo--adobecom.aem.page/?martech=off
Standalone Gnav: https://adobecom.github.io/nav-consumer/navigation.html?env=stage&authoringpath=/federal/home&customlinks=home,apps,learn,files,discover&theme=dark&navbranch=mgnav-bgcolor&newNav=on
- Acrobat: https://main--dc--adobecom.hlx.live/acrobat?martech=off&milolibs=mgnav-bgcolor--milo--adobecom
- BACOM: https://main--bacom--adobecom.hlx.live/?martech=off&milolibs=mgnav-bgcolor--milo--adobecom
- CC: https://main--cc--adobecom.aem.live/creativecloud?martech=off&milo …
=> Color mismatch in the Gnav in dark mode on mobile device

nala/blocks/notification/notification.page.js, nala/blocks/notification/notification.spec.js, nala/blocks/notification/notification.test.js
* Nala automation test scripts for notification block
* Default notification block variant
Resolves: [MWPW-170695](https://jira.corp.adobe.com/browse/MWPW-170695)
**Test URLs:**
- After: https://notification--milo--adobecom.aem.page/?martech=off
=> [NALA][MWPW-170695] Add automation tests for Notification Block

libs/blocks/global-navigation/global-navigation.js, libs/blocks/global-navigation/utilities/utilities.js
* Currently the promo hides the gnav if it overflows. Now, we are pushing gnav down with a lana log that there is potential CLS.
Resolves: [MWPW-170784](https://jira.corp.adobe.com/browse/MWPW-170784)
**Test URLs:**
- Before: https://main--milo--adobecom.aem.page/drafts/blaishram/test-urls/page-with-promo-overflow?martech=off
- After: https://gnav-promo--milo--adobecom.aem.page/drafts/blaishram/test-urls/page-with-promo-overflow?martech=off
- Acrobat: https://main--dc--adobecom.hlx.live/acrobat?martech=off&milolibs=gnav-promo--milo--adobecom
- BACOM: https://main--bacom--adobecom.hlx.live/?martech=off&milolibs=gnav-promo--milo--adobecom
- CC: https://main--cc--adobecom.aem.live/creativecloud?martech=off&milolibs=gnav-promo--milo--adobecom
- Milo: …
=> Handle gnav promo bar overflowing gracefully

libs/blocks/article-header/article-header.js, test/blocks/article-header/article-header.test.js, test/blocks/article-header/mocks/body-without-author-link.html
* Add new support to turn off author link in article header block via metadata `article-author-link` set to `off`
* Change backup behavior to try to get author image from text rather than no image
Resolves: [MWPW-170349](https://jira.corp.adobe.com/browse/MWPW-170349)
**Test URLs:**
With link + metadata
--See links in comments--
Regression (link still supported):
- Before: https://main--milo--adobecom.aem.page/drafts/methomas/blog-migration/article-header/connecting-external-data-sources-to-adobe-experience-manager-guides?martech=off
- After: https://author-link--milo--meganthecoder.aem.page/drafts/methomas/blog-migration/article-header/connecting-external-data-sources-to-adobe-experience-manager-guides?martech=off
=> MWPW-170349 [Article Header] Support no author link

libs/features/georoutingv2/georoutingv2.js, libs/features/personalization/personalization.js, libs/utils/utils.js, test/features/personalization/mepGeolocation.test.js, test/features/personalization/mepGeolocationSettings.js, test/features/personalization/mocks/manifestMEPCountryChoice.json, test/features/personalization/mocks/manifestMEPCountryIP.json, test/features/personalization/mocks/metadata-mepgeolocation.html, test/utils/mocks/head-personalization.html, test/utils/mocks/mep/head-mepgeolocation-off.html, test/utils/mocks/mep/head-mepgeolocation-on.html, test/utils/utils-mep-with-params.test.js, test/utils/utils-mep.test.js, test/utils/utils.test.js
This feature provides two new options for delivering location-based content with MEP which can be used in experience names and placeholders:
**countryIP** and **countryChoice**
Both are enabled by setting mepgeolocation to "on" in the metadata or via query parameter.
CountyIP leverages the existing getAkamaiCode function from georoutingv2.js, relying on query parameter (akamaiLocale), session storage(akamai) and lastly the geo2 api to set the config.mep.countryIP value the manifest will match against.
CountryChoice relies on the country query parameter, the international cookie and will fallback to mep.countryIP if it's available. 
Steps to test:
Using your vpn, select Singpore. Check the value of akamai in session storage, you will need to delete it and reload.
You should see this in the …
=> MWPW-170928[MEP] Add MEP pzn tags for a user's country

libs/blocks/merch-card/merch-card.js, test/blocks/merch-card/merch-offer-select.test.js, test/blocks/merch-card/mocks/selection-cards.html
Add a LOC-robust Quantity Selector approach:
Instead of adding QS as unsorted list it can be added as a Link:
HREF:
#qs&min=1&max=10&step=1&default=2&max-input=180
Link TITLE: QS title (translatable)
For backwards compatibility old approach will keep working for some time & will be removed once GWP does content updates. Check https://mwpw-169204--milo--adobecom.aem.live/drafts/mariia/pr/qs1?martech=off to see 'old' approach still working
Resolves: https://jira.corp.adobe.com/browse/MWPW-169204
**Test URLs:**
- Before: https://main--milo--adobecom.aem.live/drafts/mariia/pr/qs?martech=off
- After: https://mwpw-169204--milo--adobecom.aem.live/drafts/mariia/pr/qs?martech=off
=> MWPW-169204: create QS from the link

tools/da-apps/auth.js
Fixed da bacom blog mapping & added ref in session storage
Error:
**Test URLs:**
- After: https://fix-bacom-blog--milo--adobecom.aem.page/?martech=off
=> [DA] Fixed da bacom blog mapping & added ref in session storage

libs/blocks/global-navigation/global-navigation.js, libs/features/dynamic-navigation/dynamic-navigation.js, libs/features/dynamic-navigation/status.css, libs/features/dynamic-navigation/status.js, test/features/dynamic-nav/dynamicNav.test.js, test/features/dynamic-nav/mocks/reset.html, test/features/dynamic-nav/mocks/status.html, test/features/dynamic-nav/status.test.js
* Adds a "reset" functionality to the dynamic nav, allowing pages to reset the experience entirely
* Adds the dispatching of a custom event when the global-navigation is done loading to address code execution order issue with status.js 
Resolves: [MWPW-MWPW-170175](https://jira.corp.adobe.com/browse/MWPW-MWPW-170175)
**Test URLs:**
- Before: https://main--milo--jasonhowellslavin.hlx.page/drafts/slavin/dynamic-nav/bacom-sample-on?martech=off
- After: https://dynamic-nav-reset--milo--jasonhowellslavin.hlx.page/drafts/slavin/dynamic-nav/bacom-sample-on?martech=off
Bacom
- Before: https://main--bacom--adobecom.hlx.page/drafts/slavin/dynamic-nav/aem-rtcdp-entry?martech=off
- After: https://main--bacom--adobecom.hlx.page/drafts/slavin/dynamic-nav/aem-rtcdp-entry?milolibs=dynamic-nav-reset&martec …
=> MWPW-170175: Dynamic Nav Reset

libs/navigation/navigation.css
* As part of Spectrum's latest guidance, the gnav height has to be reduced to 56px for adobe home
* Starting this with standalone Gnav
Resolves: [MWPW-169766](https://jira.corp.adobe.com/browse/MWPW-169766)
**Test URLs:**
- After: https://gnav-compact--milo--adobecom.aem.page/?martech=off
Standalone Gnav: https://adobecom.github.io/nav-consumer/navigation.html?env=stage&authoringpath=/federal/home&navbranch=gnav-compact&unav=appswitcher,profile,notifications,help
=> Changing gnav height for standalone Gnav

libs/blocks/mmm/mmm.js
Recently introduced code that should only affect *Filter* text area is affecting dropdowns as well, turning values like `us,ca,ca_fr` to `usca,ca_fr` by replacing first coma. 
Resolves: [MWPW-171526](https://jira.corp.adobe.com/browse/MWPW-171526)
**Test URLs:**
- Before: https://main--milo--adobecom.hlx.page/docs/authoring/features/mmm
- After: https://mmm-filter-bug--milo--adobecom.hlx.page/docs/authoring/features/mmm
QA Steps:
Choose NA REGION in `Top Regions/Geos` dropdown. In the broken *BEFORE* state you won't see US pages
=> MWPW-171526 [MMM][MEP] MMM North America filter does not show US pages

libs/blocks/graybox/graybox.css, libs/blocks/graybox/graybox.js, libs/styles/styles.css
Modals and MEP now appear at correct z-index.
Resolves: [MWPW-170913](https://jira.corp.adobe.com/browse/MWPW-170913)
**Test URLs:**
- Before: https://main--milo--adobecom.aem.page/drafts/cpeyer/graybox/graybox-changed?martech=off
- After: https://mwpw-170913--milo--adobecom.aem.page/drafts/cpeyer/graybox/graybox-changed?martech=off
=> MWPW-170913 Fix graybox z-index issues

libs/utils/utils.js
Resolves: [MWPW-171546](https://jira.corp.adobe.com/browse/MWPW-171546)
**Test URLs:**
- After: https://vhargrave-MWPW-171546-locales-added-twice--milo--adobecom.aem.page/?martech=off
You have to override the utils.js code, but you can see it fixed here for example.  
https://news.stage.adobe.com/ja/
**News**
- Before: https://stage--news--adobecom.aem.page/ko/drafts/ruchika/testpage
- After: https://stage--news--adobecom.aem.page/ko/drafts/ruchika/testpage?milolibs=vhargrave-MWPW-171546-locales-added-twice
- Before: https://stage-site--news--adobecom.aem.page/en/gb/
- After: https://stage--news--adobecom.aem.page/en/gb/?milolibs=vhargrave-MWPW-171546-locales-added-twice
**CC & other consumers should not be affected by this**
- …
=> MWPW-171546 fix issue with localized links being localized again. 

libs/blocks/notification/notification.css, libs/blocks/notification/notification.js, libs/blocks/section-metadata/section-metadata.css, test/blocks/notification/mocks/body.html, test/blocks/notification/notification.test.js
Adding a **focus** variant to split notification to add focus curtain for the notification block.
Resolves: [MWPW-171550](https://jira.corp.adobe.com/browse/MWPW-171550)
**Test URLs:**
- Before: https://main--milo--adobecom.aem.page/drafts/mathuria/promobar/creativecloud?martech=off
- After: https://mwpw-171550--milo--adobecom.aem.page/drafts/mathuria/promobar/creativecloud?martech=off
=> MWPW-171550 | Focus for split notification

libs/blocks/iframe/iframe.js, libs/blocks/modal/modal.js
This resolves the issue where iframe title was missing when opening via CTA, fixed by applying the CTA's aria-label as the iframe title.
Resolves: [MWPW-171113](https://jira.corp.adobe.com/browse/MWPW-171113)
**Test URLs:**
- After: https://automated-iframe-title-cta--milo--adobecom.aem.page/?martech=off
**QA Test URLs:**
- Before: https://main--cc--adobecom.aem.page/products/catalog
- After: https://main--cc--adobecom.aem.page/products/catalog?milolibs=automated-iframe-title-cta
=> [MWPW-171113] - Automated iframe title cta

libs/blocks/modal/modal.css, libs/blocks/modal/modal.js
This adapts the focus state of the Modal's close button for accessibility purposes, by inverting the icon's colors.
Resolves: [MWPW-170383](https://jira.corp.adobe.com/browse/MWPW-170383)
**Test URLs:**
- Before: https://main--milo--overmyheadandbody.aem.page/docs/authoring/create-modal
- After: https://modal-close-a11y--milo--overmyheadandbody.aem.page/docs/authoring/create-modal
- Before: https://main--dc--adobecom.aem.page/acrobat/generative-ai-pdf?martech=off
- After: https://main--dc--adobecom.aem.page/acrobat/generative-ai-pdf?milolibs=modal-close-a11y--milo--overmyheadandbody&martech=off
=> [MWPW-170383] Modal close button focus a11y

libs/blocks/caas/caas.js
This PR addresses an SEO issue where card collections using lazy loading aren't being properly indexed by search engines. Google's crawler executes JavaScript but doesn't trigger the scroll events needed to load our lazy-loaded CAAS components at mobile viewport widths.
- Added a isLikelyBot() function to detect search engine crawlers and headless browsers
- Modified the CAAS initialization to bypass lazy loading for search bots and small viewports
- This ensures card content is properly indexed while maintaining performance benefits of lazy loading for regular users
- Tested with Puppeteer simulating Googlebot at 412px width
- Verified card collections load without requiring scroll events
- Confirmed regular desktop users still benefit from lazy loading
The solution leverages the …
=> MWPW-169639: Fix SEO visibility of CAAS card collections for search engine crawlers

libs/blocks/global-navigation/global-navigation.css
Reverts adobecom/milo#3976
- Acrobat: https://main--dc--adobecom.hlx.live/acrobat?martech=off&milolibs=revert-3976-MWPW-168480--milo--adobecom
- BACOM: https://main--bacom--adobecom.hlx.live/?martech=off&milolibs=revert-3976-MWPW-168480--milo--adobecom
- CC: https://main--cc--adobecom.aem.live/creativecloud?martech=off&milolibs=revert-3976-MWPW-168480--milo--adobecom
- Milo: https://revert-3976-MWPW-168480--milo--adobecom.aem.page/drafts/blaishram/test-urls/page?martech=off
- Express: https://main--express-milo--adobecom.aem.live/express/?martech=off&milolibs=revert-3976-MWPW-168480--milo--adobecom
- News: https://main--news--adobecom.aem.live/?martech=off&milolibs=revert-3976-MWPW-168480--milo--adobecom
- Homepage: …
=> Revert "Gap is seen between promo banner and G-nav when page is scrolled."

libs/mep/emea1441/table/README.md, libs/mep/emea1441/table/table.css, libs/mep/emea1441/table/table.js
* Creates MEP test version of table block
* adds classes for the dark table required for EMEA1441
Figma that shows the dark table layout: 
https://www.figma.com/proto/IZD9qy0ir6GMB7SfHj0OJg/0719---OPT-31672---AX-Go-Big-UK-Macro-v4-Test?page-id=4001%3A42&node-id=4001-25557&p=f&viewport=121%2C282%2C0.02&t=2GedUvWgi0Zo2hgh-1&scaling=scale-down-width&content-scaling=fixed
Resolves: [OPT-31767](https://jira.corp.adobe.com/browse/OPT-31767)
**Test URLs:**
- Psi-check: https://emea1441-dark-table--milo--adobecom.aem.page/?martech=off
- Before: https://main--cc--adobecom.aem.page/uk/products/photoshop
- After: https://main--cc--adobecom.aem.page/uk/products/photoshop?mep=%2Fproducts%2Fphotoshop.json--default---%2Fcc-shared%2Ffragments%2Ftests%2Femea-latam%2F2025%2Fq2%2Femea1441%2Fmep%2Fphotoshop%2 …
=> [OPT-31767] MEP test: Add dark-table class for the emea1441 test

libs/features/placeholders.js, libs/utils/utils.js
When on non-prod sites, placeholder code will also look for a placeholders-stage.json and overlay those values on top of the placeholders.json values.
NOTE: This only adds support for stage placeholders for regular placeholders.  Feds and Pallet support will have to be done in another PR
**Implementation Details:**
In utils.js `decoratePlaceholders` used to fetch a single path to the placeholders file and initiate a fetch request that's passed into placeholders.js `decoratePlaceholderArea` function.  This is to start the load of the placeholders file before loading placeholders.js
Now `decoratePlaceholders` will check if on a stage env and start the fetch of both the placeholders.json and placeholders-stage.json.  Those are combined in a Promise.all  and passed to …
=> MWPW-171967 Support for placeholders-stage

libs/blocks/table/table.js, libs/features/icons/icons.js, test/blocks/table/table.test.js, test/features/icons/icons.test.js
This moves the tooltip event listeners to the icons file so that relevant events are attached wherever tooltips are used.
Resolves: [MWPW-170177](https://jira.corp.adobe.com/browse/MWPW-170177)
**Test URLs:**
- Before (Milo, table w/ tooltips): https://main--milo--overmyheadandbody.aem.page/docs/library/kitchen-sink/table
- After (Milo, table w/ tooltips): https://tooltip-icon-listeners--milo--overmyheadandbody.aem.page/docs/library/kitchen-sink/table
- Before (DC, pricing w/ tooltips): https://main--dc--adobecom.hlx.page/acrobat/pricing?martech=off
- After (DC, pricing w/ tooltips): https://main--dc--adobecom.hlx.page/acrobat/pricing?milolibs=tooltip-icon-listeners--milo--overmyheadandbody&martech=off
=> [MWPW-170177] Move tooltip icon listeners

libs/features/placeholders.js, libs/utils/utils.js
Also will not attempt to fetch placeholders-stage.json unless `placeholders-stage` metadata is set to `on`
**Test URLs:**
- Before: https://main--milo--adobecom.aem.page/drafts/cpeyer/test?martech=off
- After: https://171967-stage-pl-fix--milo--adobecom.aem.page/drafts/cpeyer/test?martech=off
=> MWPW-171967 Handle non-json

libs/mep/ace1068/hero-marquee/hero-marquee.css, libs/mep/ace1068/hero-marquee/hero-marquee.js, libs/mep/ace1068/notification/notification.css, libs/mep/ace1068/notification/notification.js, libs/mep/ace1068/section-metadata/section-metadata.css, libs/mep/ace1068/section-metadata/section-metadata.js, libs/mep/ace1068/section-metadata/sticky-section.js
Designed for mobile. Works on all break points.
- Adds marquee H1 typography variant.
- Adds sticky notification 100% width button(s) variant to match Figma mock.
- Adds sticky notification hide-at-intersection metadata and intersection observer functionality. 
Update:
- Adds marquee styles to match Figma designs.
Using the the All experience compare to figma mock or charter:
1. Check marquee layout var1 and var2 on both pages.
2. Check sticky notification stretched sticky button.
3. Check that sticky notification hides at the selector main > div:nth-child(6) (Get Lightroom section) and below, then reappears above.
4. Verify that no other scroll/hide functionality breaks; IE should hide when marquee is in viewport.
Resolves: https://jira.corp.adobe.com/browse/OPT-32422
Figma: …
=> Ace1068 Marquee and Notification variant

libs/navigation/package.json
Upgrading package version for bundled Gnav to 0.0.8
**Test URLs:**
- After: https://gnav-version--milo--adobecom.aem.page/?martech=off
Test Url - https://adobecom.github.io/nav-consumer/?authoringpath=/federal/home&theme=dark&usebundle=true
=> Upgrading package version for bundled Gnav to 0.0.8

libs/blocks/table/table.js
* Fix line break issues with long content with links in tables
Resolves: [MWPW-170630](https://jira.corp.adobe.com/browse/MWPW-170630)
**Test URLs:**
- Before: https://main--milo--adobecom.aem.live/docs/library/kitchen-sink/table?martech=off
- After: https://bmarshal-table-links--milo--adobecom.aem.live/docs/library/kitchen-sink/table?martech=off
- Before: https://main--da-bacom-blog--adobecom.aem.page/drafts/bmarshal/scope-creep?martech=off
- After: https://main--da-bacom-blog--adobecom.aem.page/drafts/bmarshal/scope-creep?martech=off&milolibs=bmarshal-table-links
- Before: https://main--da-bacom-blog--adobecom.aem.live/drafts/bmarshal/table?martech=off
- After: https://main--da-bacom-blog--adobecom.aem.live/drafts/bmarshal/table?martech=off&milolibs=bmarshal-table-links
=> MWPW-170630 Fix table link line break

libs/blocks/tabs/tabs.css, libs/blocks/tabs/tabs.js
This resolves the issue where group labels weren't associated with controls, also resolves the issue where we were using wrong roles and aria attributes for radio buttons.
Resolves: [MWPW-170098](https://jira.corp.adobe.com/browse/MWPW-170098)
**Test URLs:**
- Before: https://main--milo--adobecom.aem.page/docs/library/kitchen-sink/tab-block?martech=off
- After: https://tabs-group-label-second--milo--adobecom.aem.page/docs/library/kitchen-sink/tab-block?martech=off
**DC Test URLs:**
- Before: https://main--dc--adobecom.hlx.page/dc-shared/fragments/tests/2024/q4/dc1031/individual-pill-tab
- After: https://main--dc--adobecom.hlx.page/dc-shared/fragments/tests/2024/q4/dc1031/individual-pill-tab?milolibs=tabs-group-label-second
**Nested radio button use case Test URLs:**
Before: …
=> [MWPW-170098] - Tabs group label

libs/blocks/table/table.css, libs/blocks/table/table.js
Issue: If text spacing is applied, text overflows table heading container that have add on content (e.g. price). In tables that don't have add on content, you can reproduce this issue by resizing the window and then applying text spacing. 
* Replace `height` with `min-height`
* Set `max-width: 100%` to all descendants.
**Screenshots:**
Resolves: [MWPW-171326](https://jira.corp.adobe.com/browse/MWPW-171326)
To test use this [extension](https://chromewebstore.google.com/detail/text-spacing-editor/amnelgbfbdlfjeaobejkfmjjnmeddaoj)
**Test URLs:**
- Before: https://main--milo--adobecom.aem.page/drafts/ratko/mwpw-171326-table-text-spacing/table?martech=off
- After: https://mwpw-171326-table-text-spacing--milo--adobecom.aem.page/drafts/ratko/mwpw-171326-table-text-spacing/table?martech=off
- …
=> MWPW-171326: Fix text overflow in table heading

libs/styles/styles.css
* Add `xxs-spacing` to `con-block`
Screenshots: 
Before:
After:
Resolves: [MWPW-171335](https://jira.corp.adobe.com/browse/MWPW-171335)
**Test URLs:**
- Before: https://main--milo--adobecom.aem.page/drafts/ratko/mwpw-171335-con-block-xxs-spacing/document?martech=off
- After: https://mwpw-171335-xxs-con-block--milo--adobecom.aem.page/drafts/ratko/mwpw-171335-con-block-xxs-spacing/document?martech=off
=> MWPW-171335: Add xxs-spacing to con-block

libs/blocks/region-nav/region-nav.js, libs/utils/utils.js, test/blocks/region-nav/region-nav.test.js
* Update to region-nav to support url formats with /language/region/
Resolves: [MWPW-171040 ](https://jira.corp.adobe.com/browse/MWPW-171040 )
**Test URLs:**
- After: https://MWPW-171040--milo--adobecom.aem.page/?martech=off
Express
Before: https://main--express-milo--adobecom.aem.page/express/feature/image/editor?milolibs=stage#langnav
After: https://main--express-milo--adobecom.aem.page/express/feature/image/editor?milolibs=MWPW-171040#langnav
News
Before: https://lang-nav--news--adobecom.hlx.page/en/gb/drafts/ruchika/document?milolibs=stage#langnav
After:https://lang-nav--news--adobecom.hlx.page/en/gb/drafts/ruchika/document?milolibs=MWPW-171040#langnav
CC
Before: https://stage--cc--adobecom.hlx.page/products/photoshop#langnav …
=> MWPW-171040: support for url formats lan/reg

libs/utils/decorate.js
This resolves the issue where an aria-label was missing from the pause/play button.
Resolves: [MWPW-171958](https://jira.corp.adobe.com/browse/MWPW-171958)
**Test URLs:**
- After: https://video-element-name-missing--milo--adobecom.aem.page/?martech=off
- Before: https://main--cc--adobecom.hlx.page/cc-shared/fragments/products/substance3d/painter/aside-non-destructive
- After: https://main--cc--adobecom.hlx.page/cc-shared/fragments/products/substance3d/painter/aside-non-destructive?milolibs=video-element-name-missing
=> [MWPW-171958] - video pause/play a11y

libs/blocks/tabs/tabs.js
This resolves the issue where when on mobile and clicking on stacked tabs, the action scrolls you to the content and the tab buttons go out of view.
Resolves: [MWPW-172157](https://jira.corp.adobe.com/browse/MWPW-172157)
**Test URLs:**
- Before: https://main--milo--adobecom.aem.page/docs/library/kitchen-sink/tab-block?martech=off
- After: https://tab-mobile-scroll--milo--adobecom.aem.page/docs/library/kitchen-sink/tab-block?martech=off
=> [MWPW-172157] - tab stacked mobile scroll fix

libs/blocks/tabs/tabs.js
This PR reverts https://github.com/adobecom/milo/pull/4068 and https://github.com/adobecom/milo/pull/4104.
Resolves: [MWPW-172157](https://jira.corp.adobe.com/browse/MWPW-172157)
**Test URLs:**
Before: https://main--milo--adobecom.aem.page/docs/library/kitchen-sink/tab-block?martech=off
After: https://revert-tab-stacked-scroll--milo--adobecom.aem.page/docs/library/kitchen-sink/tab-block?martech=off
**DC Test URLs:**
Before: https://main--dc--adobecom.aem.live/acrobat/features?milolibs=stage
After: https://main--dc--adobecom.aem.live/acrobat/features?milolibs=revert-tab-stacked-scroll
=> [MWPW-172157] - revert tabs stacked mobile

libs/blocks/icon-block/icon-block.css, libs/blocks/icon-block/icon-block.js, libs/styles/styles.css
This resolves an issue in the Icon block where the focus block was missing for a link whose content is an image.
Resolves: [MWPW-171328](https://jira.corp.adobe.com/browse/MWPW-171328)
**Test URLs:**
- Before: https://main--milo--adobecom.aem.page/docs/library/kitchen-sink/icon-block?martech=off
- After: https://link-image-focus--milo--adobecom.aem.page/docs/library/kitchen-sink/icon-block?martech=off
- Before: https://main--cc--adobecom.hlx.page/cc-shared/fragments/products/substance3d/s3d-family-apps-blade-grey-links?martech=off
- After: https://main--cc--adobecom.hlx.page/cc-shared/fragments/products/substance3d/s3d-family-apps-blade-grey-links?milolibs=link-image-focus&martech=off
=> [MWPW-171328] - Icon block link image focus

libs/blocks/susi-light-login/susi-light-login.js, test/blocks/susi-light-login/susi-light-login.test.js
Adds support for passing DCP ID in SUSI Light Login.
Resolves: [MWPW-173467](https://jira.corp.adobe.com/browse/MWPW-173467)
**Test URLs:**
- After: https://susi-dcp--milo--adobecom.aem.page/?martech=off
**QA:**
- Before: https://main--cc--adobecom.aem.page/drafts/nishantkaush/products/photoshop/test?martech=off
- After: https://main--cc--adobecom.aem.page/drafts/nishantkaush/products/photoshop/test?milolibs=susi-dcp?martech=off
=> MWPW-173467: add support for dcp in susi light login

libs/blocks/notification/notification.css, libs/blocks/notification/notification.js, test/blocks/notification/notification.test.js
This resolves the issue where the notification container was missing a role and an aria-label, the aria-label was changed for the close button, added an announcement for the screen reader "Banner closed" after closing the banner and focusing on the next element after finishing the announcement.
Update:
After a meeting with Taryn, it was decided that when closing the banner the focus after the closing announcement would shift to the previous sections selected/checked element like an active tab/element if it has one and if not then the last focusable element in the previous section.
Resolves: [MWPW-170108](https://jira.corp.adobe.com/browse/MWPW-170108)
**Previous section last focusable element Test URLs:**
- Before: https://main--milo--adobecom.aem.page/drafts/dusan/notification-close-testi …
=> [MWPW-170108] - Notification a11y

tools/sidekick/config.json
After: https://trusted-hosts--milo--adobecom.aem.page/?martech=off
=> chore: Configure Trusted Hosts for Sidekick

libs/blocks/global-navigation/global-navigation.css
* Removing zoom behaviour on localnav headline
Resolves: [MWPW-166841](https://jira.corp.adobe.com/browse/MWPW-166841)
**Test URLs:**
- After: https://MWPW-166841--milo--adobecom.aem.page/?martech=off
- Acrobat: https://main--dc--adobecom.hlx.live/acrobat?martech=off&milolibs=MWPW-166841--milo--adobecom
- BACOM: https://main--bacom--adobecom.hlx.live/?martech=off&milolibs=MWPW-166841--milo--adobecom
- CC: https://main--cc--adobecom.aem.live/creativecloud?martech=off&milolibs=MWPW-166841--milo--adobecom
- Milo: https://MWPW-166841--milo--adobecom.aem.page/drafts/blaishram/test-urls/page?martech=off
- Express: https://main--express-milo--adobecom.aem.live/express/?martech=off&milolibs=MWPW-1 …
=> No zoom behaviour on localnav headline

libs/utils/utils.js
* Parallelize favicon.js import
* Change "first section" performance optimizations to "lcp section" to account for breadcrumbs being put in first section
Resolves: [MWPW-171825](https://jira.corp.adobe.com/browse/MWPW-171825)
**Test URLs:**
- After: https://favicon-perf--milo--meganthecoder.aem.page/drafts/methomas/default?martech=off
Bacom:
- Before: https://main--bacom--adobecom.aem.live/ai/adobe-genai
- After: https://main--bacom--adobecom.aem.live/ai/adobe-genai?milolibs=favicon-perf--milo--meganthecoder
Acom:
- Before: https://main--cc--adobecom.aem.live/ai/overview
- After: https://main--cc--adobecom.aem.live/ai/overview?milolibs=favicon-perf--milo--meganthecoder
=> MWPW-171825 Improve lcp performance for favicon and breadcrumb

libs/styles/styles.css
This resolves an issue where a Chrome update caused the strong element to have a font weight of bolder(900) instead of bold(700).
Resolves: [MWPW-172403](https://jira.corp.adobe.com/browse/MWPW-172403)
**Test URLs:**
- Before: https://main--milo--adobecom.aem.live/docs/library/kitchen-sink/hero-marquee
- After: https://text-headings-font-weight--milo--adobecom.aem.live/docs/library/kitchen-sink/hero-marquee
=> [MWPW-172403] - Text headings strong font weight

libs/blocks/global-navigation/utilities/utilities.js
Bring https://github.com/adobecom/milo/pull/4150 to `stage` as well, as that one had to be merged directly to `main` to resolve a critical issue.
**Test URLs:**
- After: https://gnav-lanaflood-sync--milo--overmyheadandbody.aem.page/?martech=off
=> Reduce gnav lana sampleRate to 0.01%

libs/blocks/global-navigation/utilities/menu/menu.js
Reverts adobecom/milo#4084
PR causing break in the footer as css is not merged.
- Acrobat: https://main--dc--adobecom.hlx.live/acrobat?martech=off&milolibs=revert-4084-mwpw-170454--milo--adobecom
- BACOM: https://main--bacom--adobecom.hlx.live/?martech=off&milolibs=revert-4084-mwpw-170454--milo--adobecom
- CC: https://main--cc--adobecom.aem.live/creativecloud?martech=off&milolibs=revert-4084-mwpw-170454--milo--adobecom
- Milo: https://revert-4084-mwpw-170454--milo--adobecom.aem.page/drafts/blaishram/test-urls/page?martech=off
- Express: https://main--express-milo--adobecom.aem.live/express/?martech=off&milolibs=revert-4084-mwpw-170454--milo--adobecom
- News: https://main--news--adobecom.aem.live/?martech=off&milolibs=revert-4084-mwpw-170454--milo--a …
=> Revert "MWPW-170454 : Visual list is not marked up as list"

libs/blocks/redirects-formatter/redirects-formatter.css, libs/blocks/redirects-formatter/redirects-formatter.js, libs/blocks/redirects-formatter/utils/checkboxes.js, libs/blocks/redirects-formatter/utils/process-redirects.js, libs/blocks/redirects-formatter/utils/redirect-inputs.js, test/blocks/redirects-formatter/checkboxes.test.js, test/blocks/redirects-formatter/mocks/locale-config.json, test/blocks/redirects-formatter/mocks/redirects-formatter.html, test/blocks/redirects-formatter/process-redirects.test.js, test/blocks/redirects-formatter/redirect-inputs.test.js, test/blocks/redirects-formatter/redirects-formatter.test.js
* Adds a Redirects Formatter tool that is currently used in Bacom to Milo.
* Adds additional functionality to the formatter currently on Bacom:
** Ability to create checkbox groupings for locals
** Ability to add single redirects as well as bulk redirects 
** Instructions can be authored 
** Styling changes
Resolves: [MWPW-145857](https://jira.corp.adobe.com/browse/MWPW-145857)
**Test URLs:**
- Before: https://main--milo--jasonhowellslavin.hlx.live/drafts/slavin/tools/redirects-formatter?martech=off
- After: https://redirects-formatter-milo--milo--jasonhowellslavin.hlx.live/drafts/slavin/tools/redirects-formatter?martech=off
=> MWPW-145857: Redirects formatter clean

libs/blocks/quiz/quiz.css
* fix padding for icon only cards
Resolves: [MWPW-172996](https://jira.corp.adobe.com/browse/MWPW-172996)
**Test URLs:**
- After: https://quiz-icon-bug-fix--milo--colloyd.aem.page/drafts/colloyd/quiz/?martech=off
=> quiz icon bug fix

libs/blocks/carousel/carousel.css, libs/blocks/carousel/carousel.js, nala/blocks/carousel/carousel.page.js, nala/blocks/carousel/carousel.test.js
Issues: Missing slide content announcement when navigating carousel and select slide indicator missing correct state. 
* Added `aria-live` [docs](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Reference/Attributes/aria-live)
* Update `aria-live` with slide text content, so it gets announced to the user
* Set correct `aria-label` attributes to the slide indicators
* Set `aria-current` attribute to the active indicator
Resolves: [MWPW-171960](https://jira.corp.adobe.com/browse/MWPW-171960) and [MWPW-172184](https://jira.corp.adobe.com/browse/MWPW-172184)
**Test URLs:**
- Before: https://main--milo--adobecom.aem.page/drafts/ratko/mwpw-171960-carousel-dots/carousel?martech=off
- After: https://accessibility-carousel--milo--adobecom.aem.page/drafts/ratko/mwpw-171960-carousel-do …
=> Improve carousel accessibility

libs/blocks/graybox/graybox.css, libs/blocks/graybox/graybox.js, libs/utils/injectblock.js, libs/utils/utils.js, test/blocks/graybox/globalnoclick.test.js, test/blocks/graybox/graybox.test.js
Adds support for `injectblock` metadata property, which when specified takes a comma delimited list of blocks to add to the page.  The blocks are added after initial page render to not affect performance, and a generic block with no variation is added to the bottom of the page.
PR also has:
* a few slight ui tweaks to graybox
* Graybox flyout is only open if there is a custom title or description
Resolves: [MWPW-164457](https://jira.corp.adobe.com/browse/MWPW-164457)
**Test URLs:**
- Before: https://main--milo--adobecom.aem.page/drafts/cpeyer/temp/insertblock?martech=off
- After: https://injectblock--milo--adobecom.aem.page/drafts/cpeyer/temp/insertblock?martech=off
=> MWPW-164457 Add injectblock metadata support

tools/sidekick/config.json
The libraries flag does not match the [sidekick schema](https://tools.aem.live/sidekick/config.schema.json) and is not used within the config service anymore. Thus we should remove it from Github as well. [MWPW-Ticket](https://jira.corp.adobe.com/browse/MWPW-173458)
**Test URLs:**
- After: https://remove-unused-flag--milo--adobecom.aem.page/?martech=off
=> Remove libraries flag

libs/blocks/mmm/mmm.js
This PR enables the _Regions/Top Geos_ dropdown filter on the MMM Target Cleanup report page. 
**The expected behavior is:**
- New users (no local storage cookie settings) should see 'Show all' selected by default
- Returning users (with local storage cookie settings) should retain their previous filter selections from previous session/on refresh
- Like the Last Seen and Text filters, _Geo_ dropdown should fire an api call and refresh the table on dropdown change
- Cookie value for MMM Cleanup is _mmm_report_filter_settings_, which is decoupled from the main MMM report cookie (_mmm_filter_settings_)
- API call on first hit (user has no local storage cookie settings) will not explicitly add _geo_ value to payload. This is fine as api returns all pages if no value is set, and this works …
=> MWPW-173501 [MMM][MEP] Add geo filter to MMM Target cleanup report

libs/blocks/region-nav/region-nav.js, libs/navigation/navigation.css
* Adding Color white css variable for standalone Gnav
* Adding a check for hasPrefix while decorating the region nav links to support page which doesn't have locale as its prefix in the url
Resolves: [MWPW-173662](https://jira.corp.adobe.com/browse/MWPW-173662)
**Test URLs:**
- After: https://sgnav-modal-icon--milo--adobecom.aem.page/?martech=off
QA:
- Before: https://adobecom.github.io/nav-consumer/navigation.html?env=prod&theme=light&navbranch=main&authoringpath=/federal/learn&locale=jp#langnav
- After: https://adobecom.github.io/nav-consumer/navigation.html?env=prod&theme=light&navbranch=sgnav-modal-icon&authoringpath=/federal/learn&locale=jp#langnav
=> Adding Color white variable for standalone gnav and adding non milo locale path link transform in region nav

libs/blocks/merch/merch.js, test/blocks/merch/merch.test.js, test/blocks/merch/mocks/body.html
If its a 3in1 Modal, but 3in1 is disabled - turn '3in1' style deeplinks into dexter deeplinks.
ms=e becomes plan=edu
cs=t becomes plan=team
To test on Milo you need modheader (cors issues on feature branches)
To test without modheader use CC test page: https://main--cc--adobecom.aem.page/drafts/mariia/3in1off?milolibs=mwpw-173586 
https://jira.corp.adobe.com/browse/MWPW-173586
**Test URLs:**
- Before: https://main--milo--adobecom.aem.page/drafts/mariia/pr/3in1off?martech=off
- After: https://mwpw-173586--milo--adobecom.aem.page/drafts/mariia/pr/3in1off?martech=off
=> MWPW-173586: Dexter modals deeplink -backwards compatibility for 3in1

libs/blocks/text/text.css, libs/blocks/text/text.js
This resolves the issue where bold text was breaking into a new line in the text block in curtain situations.
Resolves: [MWPW-158022](https://jira.corp.adobe.com/browse/MWPW-158022)
**Test URLs:**
- Before: https://main--milo--adobecom.aem.page/docs/library/kitchen-sink/text?martech=off
- After: https://text-block-bold-break--milo--adobecom.aem.page/docs/library/kitchen-sink/text?martech=off
**1st CC Test URLs:**
- Before: https://main--dc--adobecom.hlx.page/au/drafts/dholmes/text-block-bolded-text
- After: https://main--dc--adobecom.hlx.page/au/drafts/dholmes/text-block-bolded-text?milolibs=text-block-bold-break
**2nd CC Test URLs:**
- Before: https://main--dc--adobecom.aem.page/de/acrobat/resources/academic-writing/test-files-geert/bold-text-testing
- After: …
=> [MWPW-158022] - Text block bold break

.github/workflows/dynamic-pr-template.yml
* Updated workflow so that test Urls are added when PR is created from fork repo
* Included watch for navigation folder, region nav block and styles.css
* styles.css is added in the watchlist as standalone gnav has to update any styles added in styles.css which impacts feds component
Resolves: [MWPW-173601](https://jira.corp.adobe.com/browse/MWPW-173601)
**Test URLs:**
- After: https://gnav-template--milo--adobecom.aem.page/?martech=off
=> Test Urls are not getting added when PR is created from fork repo

libs/utils/logWebVitals.js, test/utils/logWebVitals.test.js, test/utils/logWebVitalsUtils.test.js
Updated the CWV logging piece. It can now run on Chrome browsers on modern iOS devices (not sure if this was intentional or not). I will also report on whether the device is a tablet and if the OS is iOS/iPadOS
Resolves: [MWPW-173649](https://jira.corp.adobe.com/browse/MWPW-173649)
**Test URLs:**
- After: https://mwpw-173649--milo--adobecom.aem.page/?martech=off
=> MWPW-173649 CWV Logging Updates

libs/blocks/mmm/mmm.js, libs/features/personalization/preview.js
This PR adds functionality to the single 'Open <repo> Spreadsheet' button on the MMM Metadata Lookup page. 
**The expected behavior is:** 
- User with no local storage cookie settings will default to the CC button messaging: _Open CC Spreadsheet_
- Returning users (with local storage cookie settings) should retain their previous repo selection with the appropriate messaging: _Open CC|DC|BACOM|EXPRESS_ Spreadsheet
- HREF of button will change to the matching Sharepoint metadata spreadsheet for selected repo (copied from the CC spreadsheet _readme_ tab)
- Clicking on button opens a new window, which leads to the selected reop's metadata spreadhseet
**Fixes/Features:**
- Added new button cta to open spreadsheet for selected repo (button is authored via sharepoint)
- Dependency: added class …
=> MWPW-173732 [MMM][MEP] Add contextually relevant button in Target Metadata Lookup Report

libs/blocks/section-metadata/section-metadata.css
This resolves the issue where when on mobile the spaces between the cards is missing, and the section metadata two-up from the resolution 1070px to 1199px ended up making 3 items instead of 2 per row.
Resolves: [MWPW-170714](https://jira.corp.adobe.com/browse/MWPW-170714)
**PR Note:**
#Example2 looks to be intended functionality, which is explained in the ticket comment https://jira.corp.adobe.com/browse/MWPW-170714#comment-47764490, will need more discussion with Consonant and won't be addressed in this PR, while #Example1 will be addressed.
**Test URLs:**
- Before: https://main--milo--adobecom.aem.page/drafts/klee/jira-ticket/mwpw-170714-section-metadata-gap-ups?martech=off
- After: https://section-metadata-grid--milo--adobecom.aem.page/drafts/klee/jira-ticket/mwpw-170714-section-metadat …
=> [MWPW-170714] - Section metadata grid

nala/features/mas/acom/masacom.test.js
Removes checks for stock checkbox until switched to the full functionality. This is needed to prevent Nala exutions failures during transition period
Resolves: [MWPW-173816](https://jira.corp.adobe.com/browse/MWPW-173816)
**Test URLs:**
- After: https://MWPW-173816--milo--adobecom.aem.page/?martech=off
=> MWPW-173816: remove stock checks temporarily

libs/styles/styles.css
This allows hyphenation when long words are present in headings with a large font size on mobile devices. A few notes:
* I've updated the previous media query, which was wrong; if tablet devices are considered to start from `600px`, then it means mobile screens go up to `599px`;
* I've excluded Japanese pages from having hyphenation rules, as it already has rigorous word break rules set in place;
* From my design knowledge, ideally the two parts of a hyphenated word aren't too imbalanced, that's why the rule I've set is: break words longer than 15 characters, but never have one part of the word be less than 5 characters. This should provide a good visual balance, also from the perspective of how many lines of text a heading has;
Resolves: …
=> [MWPW-173717] Hyphenate large headings on mobile

libs/blocks/card-horizontal/card-horizontal.css
Issue: When text spacing is applied via extension, `card-horizontal` content text overflows. 
* Removed container `max-height`, to let container expand when line spacing is applied (height is determined by [.card-image](https://github.com/adobecom/milo/blob/stage/libs/blocks/card-horizontal/card-horizontal.css#L108))
* Removed `margin` from `.card-content` because it increases height of the container when there is no `max-height`
* `-webkit-line-clamp: 5` in combination with [align-items](https://github.com/adobecom/milo/blob/stage/libs/blocks/card-horizontal/card-horizontal.css#L70) will keep content height as before
Screenshots: 
[Text spacing extension](https://chromewebstore.google.com/detail/text-spacing-editor/amnelgbfbdlfjeaobejkfmjjnmeddaoj)
Resolves: …
=> MWPW-173425: Allow container to expand based on line height

libs/blocks/notification/notification.css
Fix delay in notification load by adding specific z-index value as var load is delayed
Resolves: [MWPW-173436](https://jira.corp.adobe.com/browse/MWPW-173436)
**Test URLs:**
- Before: https://main--milo--adobecom.aem.page/drafts/mathuria/promobar/creativecloud/?martech=off
- After: https://mwpw-173436--milo--adobecom.aem.page/drafts/mathuria/promobar/creativecloud?martech=off
https://stage--cc--adobecom.aem.page/products/photoshop?milolibs=mwpw-173436--milo--adobecom
https://stage--dc--adobecom.aem.page/acrobat/pdf-reader?milolibs=mwpw-173436--milo--adobecom
This fix is critical for acrobat 6/5 release
=> MWPW-173436 | Fix delay in split notification load

tools/send-to-caas/send-utils.js
When using the bulk send to caas tool, a phantom secondary CTA was being added to the card data.  This PR remedies this and also fixes the behavior for the primary CTA.
Resolves: [MWPW-171937](https://jira.corp.adobe.com/browse/MWPW-171937)
**Test URLs:**
- Before: https://main--milo--adobecom.aem.page/drafts/cmiqueo/test-page
- After: https://MWPW-171937--milo--sheridansunier.aem.page/drafts/cmiqueo/test-page
=> MWPW-171937: fix cta urls for bulk publisher

libs/blocks/merch/merch.js, test/blocks/merch/merch.test.js
PR was already approved to stage: https://github.com/adobecom/milo/pull/4225 & this PR to main exists to fast-track this to production without affecting the current stage batch
Resolves: [MWPW-173888](https://jira.corp.adobe.com/browse/MWPW-173888), [MWPW-173919](https://jira.corp.adobe.com/browse/MWPW-173919)
GWP staged content with 3in1 modals on Stage. Planned go live 5th June.
Warriors implemented feature flag "mas-ff-3in1", to enable GWP publish 3in1 modals before 5th June. Until metadata flag is removed/switched to "on", 3in1 modals will fallback to be shown as legacy Dexter Modals.
However we've identified 2 issues with fallback mechanism:
deeplinking with ms=e and cs=t is not working on fallback legacy modals
if there are multiple modals with same hash, then opening the page with …
=> MWPW-173888 + MWPW-173919: Appending extra options for relative urls & multiple cta reopen fix

libs/utils/logWebVitals.js, test/utils/logWebVitals.test.js, test/utils/logWebVitalsUtils.test.js
Update to performance logs
Returns whether it's a tablet or not
doesn't break on hydrated elements
get country fromfeds_location as a backup when akamai fails
Resolves: [MWPW-173875](https://jira.corp.adobe.com/browse/MWPW-NUMBER)
Test URLs:
After: https://mwpw-173875--milo--adobecom.aem.page/?martech=off
=> MWPW-173875 direct to main

libs/blocks/locui-create/utils/utils.js
Getting due date on edit workflow 
Resolves: Observation 2: [MWPW-173706](https://jira.corp.adobe.com/browse/MWPW-173706)
**Test URLs:**
- After: https://loc-due-date-fix--milo--adobecom.aem.page/?martech=off
=> [Loc] Fix due date in edit workflow

libs/blocks/locui-create/utils/utils.js
Getting due date on edit workflow
Resolves: Observation 2: [MWPW-173706](https://jira.corp.adobe.com/browse/MWPW-173706)
Test URLs:
Before: https://milostudio-d--milo--adobecom.aem.page/?martech=off
After: https://dev-loc-due-date-fix--milo--adobecom.aem.page/?martech=off
=> [Dev][Loc] Fix due date in edit workflow

libs/blocks/table/table.css, libs/blocks/table/table.js
This is an attempt to address the accessibility issues related to tables that make use of highlights. What it tries to address:
* stop announcing highlight content as the first row; these are visually tied to a column heading, thus highlights should not be announced individually;
* announce highlight text along with heading content when navigating through table cells, as that is what the visual representation suggests;
* make sure the highlight row isn't counted, so that the heading row is announced as the first one;
* reduce possibilities of new layout regressions being introduced.
This is likely a suboptimal fix, as the table structure would need to be completely rebuilt to account for all accessibility requirements; that redesign is currently being discussed, but in the interim, this …
=> [MWPW-170178] Table highlight a11y

libs/utils/utils.js
This allows defining decorative images when using the image links feature.
Resolves: [MWPW-171062](https://jira.corp.adobe.com/browse/MWPW-171062)
**Test URLs:**
- Before: https://main--milo--overmyheadandbody.aem.page/drafts/ramuntea/accessibility/decorative-image-link?martech=off
- After: https://vid-img-alt--milo--overmyheadandbody.aem.page/drafts/ramuntea/accessibility/decorative-image-link?martech=off
=> [MWPW-171062] Allow decorative images through image links

libs/utils/image-video-link.js
* Accessibility fix: Play link was not reading alt text in NVDA screen reader for windows
Resolves: [MWPW-174092](https://jira.corp.adobe.com/browse/MWPW-174092)
**Test URLs:**
- Before: https://main--milo--adobecom.aem.live/drafts/drashti/a11y/document?martech=off
- After: https://play-a11y--milo--drashti1712.aem.live/drafts/drashti/a11y/document?martech=off
=> [MWPW-174092] Authors cannot edit purpose of Play button

libs/mep/ace1052/aside/aside.css, libs/mep/ace1052/brick/brick.css, libs/mep/ace1052/brick/brick.js, libs/mep/ace1052/editorial-card/editorial-card.css, libs/mep/ace1052/hero-marquee/hero-marquee.css, libs/mep/ace1052/text/text.css
This addresses the latest comments from the mweb stories:
* [MWPW-174167](https://jira.corp.adobe.com/browse/MWPW-174167) - remove `min-height` for the Brick block on mobile;
* [MWPW-171640](https://jira.corp.adobe.com/browse/MWPW-171640) - set the correct paddings for the Aside content on mobile;
* [MWPW-171432](https://jira.corp.adobe.com/browse/MWPW-171432) - reduce the gap between the CTA and regular link in the context of a Hero Marquee on mobile;
* [MWPW-174314](https://jira.corp.adobe.com/browse/MWPW-174314) - reduce the gap between CTAs from a Text block on mobile.
Additionally, based on recent conversations, a tweak has been made to adapt the layout of sections containing an expandable list of editorial cards.
**Test URLs:**
- Before (bricks): …
=> Minor tweaks for mweb blocks

libs/blocks/table/table.js
Changing table heading roles to not have them treated as text.
Resolves: [MWPW-174220](https://jira.corp.adobe.com/browse/MWPW-174220)
**Test URLs:**
- Before: https://main--milo--adobecom.hlx.page/docs/library/blocks/table?martech=off
- After: https://MWPW-174220--milo--adobecom.hlx.page/docs/library/blocks/table?martech=off
Test url : https://main--cc--adobecom.aem.live/products/elements-family?milolibs=MWPW-174220
=> MWPW-174220 | Accessibility | Changing table heading roles to not have them treated as text.

libs/blocks/modal/modal.css
Issue: Jarvis popup is not hidden behind the modal curtain
Resolves: [MWPW-173966](https://jira.corp.adobe.com/browse/MWPW-173966)
**Test URLs:**
- After: https://mwpw-173966-jarvis-modals--milo--adobecom.aem.page/?martech=off
**CC URLs:**
- Before: https://main--cc--adobecom.aem.page/creativecloud/business/teams
- After: https://main--cc--adobecom.aem.page/creativecloud/business/teams?milolibs=mwpw-173966-jarvis-modals
- Before: https://main--cc--adobecom.aem.page/creativecloud/business/teams/free-trial-download
- After: https://main--cc--adobecom.aem.page/creativecloud/business/teams/free-trial-download?milolibs=mwpw-173966-jarvis-modals
- Before: https://main--cc--adobecom.aem.page/creativecloud/business/teams
- After: …
=> MWPW-173966: Hide jarvis popup behind modal

libs/styles/styles.css
Reverts adobecom/milo#4199
- Acrobat: https://main--dc--adobecom.hlx.live/acrobat?martech=off&milolibs=revert-4199-large-heading-a11y--milo--adobecom
- BACOM: https://main--bacom--adobecom.hlx.live/?martech=off&milolibs=revert-4199-large-heading-a11y--milo--adobecom
- CC: https://main--cc--adobecom.aem.live/creativecloud?martech=off&milolibs=revert-4199-large-heading-a11y--milo--adobecom
- Milo: https://revert-4199-large-heading-a11y--milo--adobecom.aem.page/drafts/blaishram/test-urls/page?martech=off
- Express: https://main--express-milo--adobecom.aem.live/express/?martech=off&milolibs=revert-4199-large-heading-a11y--milo--adobecom
- News: …
=> Revert "[MWPW-173717] Hyphenate large headings on mobile"

libs/blocks/global-navigation/utilities/utilities.js
Making a change to the utilities file
* Adding a comment to flush the utilities file
Resolves: [MWPW-174472](https://jira.corp.adobe.com/browse/MWPW-174472)
**Test URLs:**
- After: https://salonijain3--milo--adobecom.aem.page/?martech=off
- Acrobat: https://main--dc--adobecom.hlx.live/acrobat?martech=off&milolibs=salonijain3-patch-1--milo--adobecom
- BACOM: https://main--bacom--adobecom.hlx.live/?martech=off&milolibs=salonijain3-patch-1--milo--adobecom
- CC: https://main--cc--adobecom.aem.live/creativecloud?martech=off&milolibs=salonijain3-patch-1--milo--adobecom
- Milo: …
=> [Comment update PR] Update utilities.js

libs/blocks/locui-create/input-urls/index.js
Validated that now, when an invalid or empty date is added through UI, it gets converted to an empty string
**_Empty Date_**
**_Invalid Date (missing minutes)_**
Resolves: [MWPW-174028](https://jira.corp.adobe.com/browse/MWPW-174028)
**Test URLs:**
- Before: https://milostudio-stage--milo--adobecom.aem.page/tools/locui-create?ref=main&repo=milo&owner=adobecom&host=milo.adobe.com&project=Milo&env=local&workflow=normal
- After: https://mwpw-174028-due-date--milo--nkthakur48.aem.page/tools/locui-create?ref=main&repo=milo&owner=adobecom&host=milo.adobe.com&project=Milo&env=local&workflow=normal
=> MWPW-174028 Invalid date is formatted as NaN

libs/blocks/card/card.js
Set heading role to presentation for accessibility for half height card.
Resolves: [MWPW-174127](https://jira.corp.adobe.com/browse/MWPW-174127)
**Test URLs:**
- Before: https://main--milo--adobecom.hlx.page/docs/library/blocks/card?martech=off
- After: https://MWPW-174127--milo--adobecom.hlx.page/docs/library/blocks/card?martech=off
https://main--cc--adobecom.aem.live/se/products/premiere/ai-video-editing?milolibs=mwpw-174127--milo--adobecom
=> MWPW-174127 | Accessibility | Set heading role for half height card

libs/blocks/table/table.css
Fixes the issue where images in a table cell weren't in a horizontal line because of the picture tag having a different height than the image that's inside it.
Resolves: [MWPW-171655](https://jira.corp.adobe.com/browse/MWPW-171655)
**Test URLs:**
- After: https://table-icon-missalignement--milo--adobecom.hlx.page/docs/library/kitchen-sink/table?martech=off
- Before: https://main--cc--adobecom.aem.page/in/cc-shared/fragments/roc/mep/products/photoshop/merch-table-146492
- After: https://main--cc--adobecom.aem.page/in/cc-shared/fragments/roc/mep/products/photoshop/merch-table-146492?milolibs=table-icon-missalignement
=> [MWPW-171655] - table icon missalignement fix

libs/blocks/global-navigation/global-navigation.js, libs/blocks/global-navigation/utilities/utilities.js
Added missing parent role for LNAV A11Y
Resolves: [MWPW-174313](https://jira.corp.adobe.com/browse/MWPW-174313)
**Test URLs:**
- After: https://mwpw-174313--milo--deva309.aem.page/?martech=off
QA:
https://main--cc--adobecom.hlx.page/legal/adobe-whistleblowing-notice?milolibs=mwpw-174313--milo--deva309
- Acrobat: https://main--dc--adobecom.hlx.live/acrobat?martech=off&milolibs=mwpw-174313--milo--adobecom
- BACOM: https://main--bacom--adobecom.hlx.live/?martech=off&milolibs=mwpw-174313--milo--adobecom
- CC: https://main--cc--adobecom.aem.live/creativecloud?martech=off&milolibs=mwpw-174313--milo--adobecom
- Milo: …
=> [MWPW-174313] - Added missing parent role for localnav A11Y

libs/blocks/action-scroller/action-scroller.js
Issue: Action scroller navigation doesn't work properly on rtl pages
* Add support for rtl
Resolves: [MWPW-170541](https://jira.corp.adobe.com/browse/MWPW-170541)
**Test URLs:**
- Before: https://main--milo--adobecom.aem.page/ae_ar/drafts/ratko/action-scroller-tabs?martech=off
- After: https://mwpw-170541-scroller-rtl--milo--adobecom.aem.page/ae_ar/drafts/ratko/action-scroller-tabs?martech=off
- Before: https://main--milo--adobecom.aem.page/ae_ar/drafts/ratko/action-scroller?martech=off
- After: https://mwpw-170541-scroller-rtl--milo--adobecom.aem.page/ae_ar/drafts/ratko/action-scroller?martech=off
- Before: https://main--milo--adobecom.aem.page/docs/library/kitchen-sink/action-items?martech=off
- After: https://mwpw-170541-scroller-rtl--milo--adobecom.aem.page/docs/library/kitchen-sink/ac …
=> MWPW-170541: Add support for rtl

libs/mep/ace1052/aside/aside.css, libs/mep/ace1052/aside/aside.js, libs/mep/ace1052/carousel/carousel.css, libs/mep/ace1052/carousel/carousel.js, libs/mep/ace1052/notification/notification.css, libs/mep/ace1052/section-metadata/section-metadata.css, libs/mep/ace1052/tabs/tabs.js, libs/mep/ace1052/text/text.css
As the title says, this aims to apply all the recent stage changes to the blocks that have been edited for the purposes of the mweb test. These updates include important accessibility and layout updates.
**Test URLs:**
- Before: https://main--cc--adobecom.aem.page/drafts/ramuntea/mweb/ps-product-page-v2?milolibs=mweb-dev&georouting=off
- After: https://main--cc--adobecom.aem.page/drafts/ramuntea/mweb/ps-product-page-v2?milolibs=mweb-tweaks--milo--overmyheadandbody&georouting=off
=> Bring the latest block changes into the mweb feature branch

libs/blocks/locui-create/input-urls/index.js
Dev PR - https://github.com/adobecom/milo/pull/4344
Validated that now, "dueDate" is correctly getting skipped during rollout workflow
**_Rollout Workflow_** (check for due-date is getting skipped)
**_Translation Workflow_** (check for due-date is performed)
Resolves: [MWPW-174737](https://jira.corp.adobe.com/browse/MWPW-174737)
**Test URLs:**
- Before: https://milostudio-stage--milo--adobecom.aem.page/tools/locui-create?ref=main&repo=milo&owner=adobecom&host=milo.adobe.com&project=Milo&env=local&workflow=normal
- After: https://mwpw-174737-stage--milo--nkthakur48.aem.page/tools/locui-create?ref=main&repo=milo&owner=adobecom&host=milo.adobe.com&project=Milo&env=local&workflow=normal
=> [Stage][Loc] MWPW-174737 Skip validation for "dueDate" during rollout workflow

libs/blocks/notification/notification.css, libs/blocks/notification/notification.js
Issue: Content from notification pill desktop is not available on notification pill tablet/mobile.
* Add tooltip icon with notification desktop textContent to tablet and mobile if tablet/mobile textContent is different from desktop.
**NOTE:** I thought of avoiding code duplication (https://github.com/adobecom/milo/pull/4204) by maybe moving `addTooltip` to `accessibility.js`, but block structures are different and I feel it will be harder to maintain this if there is some changes to either `aside` or `notification`. 
Resolves: [MWPW-173830](https://jira.corp.adobe.com/browse/MWPW-173830)
**Test URLs:**
- Before: https://main--milo--adobecom.aem.page/docs/library/kitchen-sink/notification-pill?martech=off
- After: https://mwpw-173830-a11y-notification--milo--adobecom.aem.page/docs/library/k …
=> MWPW-173830: Add tooltip to notification pill

libs/blocks/graybox/graybox.css, libs/blocks/graybox/graybox.js, test/blocks/graybox/graybox.test.js
This will map any production urls to their equivalent graybox urls so that the user is kept within the graybox environment.
Resolves: [MWPW-174265](https://jira.corp.adobe.com/browse/MWPW-174265)
**Test URLs:**
- After: https://170201-gb-url--milo--adobecom.aem.page/?martech=off
=> MWPW-174265 Add url mapping to graybox envs

libs/mep/ace1052/text/text.css
This excludes simple single non-CTA links inside centered-content text blocks from being automatically left-aligned.
Resolves: [MWPW-174951](https://jira.corp.adobe.com/browse/MWPW-174951)
**Test URLs:**
- Before: https://main--cc--adobecom.aem.page/cc-shared/fragments/tests/2025/q2/ace1052/ace1052-mweb-ps-free-trial-download?milolibs=mweb-dev&mep=/drafts/ramuntea/mweb/ps-product-mweb-pzn.json&georouting=off
- After: https://main--cc--adobecom.aem.page/cc-shared/fragments/tests/2025/q2/ace1052/ace1052-mweb-ps-free-trial-download?milolibs=mweb-tweaks--milo--overmyheadandbody&mep=/drafts/ramuntea/mweb/ps-product-mweb-pzn.json&georouting=off
=> [MWPW-174951] Allow centered text block link for mweb

libs/blocks/mmm/mmm.js, libs/features/personalization/personalization.js, libs/utils/utils.js
* Enhance report button to open Slack link in a new tab
* update error handling to return an empty object
* remove geolocation relationship to martech being disabled.
Resolves: [MWPW-174845](https://jira.corp.adobe.com/browse/MWPW-174845)
**Test URLs:**
- After: https://mepfixes--milo--adobecom.aem.page/?martech=off
=> MWPW-174845 [MEP][MMM] 3 tiny fixes

.github/workflows/merge-to-stage.js
This will ensure that zero-impact PRs get merged regardless if it will exceed the merge limit.
**Test URLs:**
- After: https://zero-impact-merge--milo--adobecom.aem.page/?martech=off
=> Merge ZeroImpact PRs before checking the mergeLimit 

libs/blocks/global-navigation/global-navigation.js
* Adding the mutation observer of promo height change to support responsive view port changes.
Resolves: [MWPW-174961](https://jira.corp.adobe.com/browse/MWPW-174961)
**Test URLs:**
- After: https://gnav-promo-height--milo--adobecom.aem.page/?martech=off
- Acrobat: https://main--dc--adobecom.hlx.live/acrobat?martech=off&milolibs=gnav-promo-height--milo--adobecom
- BACOM: https://main--bacom--adobecom.hlx.live/?martech=off&milolibs=gnav-promo-height--milo--adobecom
- CC: https://main--cc--adobecom.aem.live/creativecloud?martech=off&milolibs=gnav-promo-height--milo--adobecom
- Milo: …
=> Adding mutation observer to support viewport change

libs/martech/attributes.js
The decorateSectionAnalytics function is skipping over the tabs block when adding the main, block-level daa-lh value because it (and Milo generally) does not expect blocks to exist within blocks. This PR adds the daa-lh value to tabs by making an exception for the tabs block.
Resolves: [MWPW-174735](https://jira.corp.adobe.com/browse/MWPW-174735)
Steps to QA:
check before and after links below for the daa-lh value for tabs.
Expected (After): daa-lh --> 'b1|tabs|nopzn|plans-pzn'
Actual (Before): no daa-lh value
**Test URLs:**
- Before: https://main--cc--adobecom.aem.page/creativecloud/plans
- After: https://main--cc--adobecom.aem.page/creativecloud/plans?milolibs=tabanalytics
- Psi-check: https://tabanalytics--milo--adobecom.aem.page/?martech=off
=> MWPW-174735 [Milo][Analytics] Tabs do not have a daa-lh attribute on the block

libs/blocks/global-navigation/global-navigation.js
When gnav promo is enabled in photoshop login page in mobile mode gap is seen between promo and gnav logo in UK locale. This is due to addition of local-nav class incorrectly.
Resolves: [MWPW-174786](https://jira.corp.adobe.com/browse/MWPW-174786)
**Test URLs:**
- After: https://mwpw-174786--milo--adobecom.aem.page/?martech=off
**QA:**
- Before: https://main--cc--adobecom.aem.page/uk/products/photoshop/login?martech=off
- After: https://main--cc--adobecom.aem.page/uk/products/photoshop/login?milolibs=mwpw-174786&martech=off
- Acrobat: https://main--dc--adobecom.hlx.live/acrobat?martech=off&milolibs=MWPW-174786--milo--adobecom
- …
=> MWPW-174786: remove local-nav class from empty gnav

libs/blocks/preflight/preflight.css
Since the navigation bar had a `z-index: 10`, i lowered the `z-index:` of the Metadata on hover so that it wouldnt show on top of the navigation bar when scrolling up
Resolves: [MWPW-174568](https://jira.corp.adobe.com/browse/MWPW-174568)
**Test URLs:**
- Before: https://main--bacom--adobecom.aem.page/sg/products/genstudio-for-performance-marketing
- After: https://mwpw-174568-metadata-overlaping--milo--skholkhojaev.aem.page/ 
**TEST Link:**
-  https://main--bacom--adobecom.aem.page/sg/products/genstudio-for-performance-marketing?milolibs=MWPW-174568-Metadata-overlaping--milo--skholkhojaev
=> MWPW-174568: [Preflight] Metadata on hover overlaps with navigation bar

.github/workflows/servicenow.py, .github/workflows/servicenow.yaml, .github/workflows/snow-cr-notification.js, .github/workflows/snow-pr-comment.js
Fixes these issues:
- ServiceNow Registry InstanceID that was retired has now been changed to correct ID
- Back-off timer has been updated to have an hour timeout since in high peak times the Kafka queue for the SNOW Change Request API may take a long time to complete requests.
- GitHub action only runs when merges are closed against the production branch. This now includes branches from forks being directly merged into the production branch for hot-fixes.
- Fixed API payload values for planned start and end time to be whole integers rather than timestamp floats.
Enhancements:
- Leveraging Python F-strings where needed
- Cleaned up functions to follow linting rules
- Updated release summary information for Change Requests to include PR URLs.
- Updated print statements to provide clarity …
=> ServiceNow CMR Fixes - [MWPW=173724]

libs/blocks/media/media.js
Fixes an issue where when using media checklist and adding a link, the sentence is rendered in a wrong way.
Resolves: [MWPW-173618](https://jira.corp.adobe.com/browse/MWPW-173618)
**Test URLs:**
- Before: https://main--milo--adobecom.aem.page/docs/library/kitchen-sink/media?martech=off
- After: https://media-checklist-link-fix--milo--adobecom.aem.page/docs/library/kitchen-sink/media?martech=off
**CC Test URLs**
- Before: https://main--cc--adobecom.aem.page/drafts/chrwil/media-checklist-bug
- After: https://main--cc--adobecom.aem.page/drafts/chrwil/media-checklist-bug?milolibs=media-checklist-link-fix
**2nd CC Test URLs**
- Before: https://main--cc--adobecom.aem.page/drafts/vmorel/chris-media-checklist-bug
- After: https://main--cc--adobecom.aem.page/drafts/vmorel/chris-media-checklist-bug? …
=> [MWPW-173618] - Media checklist link fix

libs/blocks/table/table.js
Resolves: [MWPW-174861](https://jira.corp.adobe.com/browse/MWPW-174861)
**QA Note**
The following PR https://github.com/adobecom/milo/pull/4042 should also be tested as this issue was introduced there and we still need to keep what that PR fixed in terms of accessibility.
**Test URLs for https://github.com/adobecom/milo/pull/4042:**
- Before: https://main--cc--adobecom.aem.page/products/photoshop-lightroom/plans
- After: https://main--cc--adobecom.aem.page/products/photoshop-lightroom/plans?milolibs=table-res-heading-fix
**1st & 2nd use case Test URLs:**
- Before: https://main--milo--adobecom.aem.page/drafts/dusan/table-in-tab-expand?martech=off
- After: https://table-res-heading-fix--milo--adobecom.aem.page/drafts/dusan/table-in-tab-expand?martech=off
**3d use case Test URLs:**
- Before: …
=> [MWPW-174861] - table heading content height increase fix

libs/utils/utils.js
An authoring pattern such as `Videó megtekintése | Lejátszás – Egyéni dizájn bármilyen felületen:play:` instead of 
`:play:Videó megtekintése | Lejátszás – Egyéni dizájn bármilyen felületen` will lead to a JS error and stop rendering.
Resolves: https://jira.corp.adobe.com/browse/MWPW-175388
**Test URLs:**
- Before: https://main--milo--adobecom.aem.page/drafts/osahin/video-megtekintese-lejatszas-egyeni-dizajn-barmilyen-felu
- After: https://safeguard-aria-labels--milo--adobecom.aem.page/drafts/osahin/video-megtekintese-lejatszas-egyeni-dizajn-barmilyen-felu?martech=off
=> Safeguard aria-label check to avoid JS errors

libs/blocks/action-scroller/action-scroller.js
Although the action item was not intended to be used without actual actions (links), it seems that there are cases where it is used in that manner. The arrows that move the items left or right are accessible, but axe is suggesting that the whole area needs to be focusable as well. This is what the current PR aims to implement. Nothing changes for action scrollers that do have nested links.
axe suggestion:
Resolves: [MWPW-175255](https://jira.corp.adobe.com/browse/MWPW-175255)
**Test URLs:**
- Before: https://main--milo--overmyheadandbody.aem.live/docs/library/kitchen-sink/action-items?martech=off
- After: https://actionless-action-item--milo--overmyheadandbody.aem.live/docs/library/kitchen-sink/action-items?martech=off
- Before (original issue): …
=> [MWPW-175255] Actionless action item a11y

libs/blocks/merch-card/merch-card.js
Previously, the collapsible footer rows always displayed the plus icon by default, regardless of whether their initial state was set to open or close.
With this PR, the icon now reflects the actual default state:
- If the row is initially closed, the plus icon is shown.
- If the row is initially open, the minus icon is shown.
Before:
After:
Resolves: [MWPW-175427](https://jira.corp.adobe.com/browse/MWPW-175427)
**Test URLs:**
- Before: https://main--milo--adobecom.aem.page/drafts/mirafedas/mini-compare-charts/mini-compare-bullet-list?martech=off
- After: https://mwpw-175427-collapsible--milo--mirafedas.aem.page/drafts/mirafedas/mini-compare-charts/mini-compare-bullet-list?martech=off
=> MWPW-175427: mini-compare-chart bullet-list collapse icon fix

libs/blocks/mmm/mmm.js
Detailed Description: https://milo.adobe.com/docs/authoring/features/mmm/target-metadata-lookup does not always reflect updates to the JSON.
URL: https://milo.adobe.com/docs/authoring/features/mmm/target-metadata-lookup
1. Go to the report
2. Choose CC
3. Paste in this URL: https://www.adobe.com/za/not-real
Expected Results: should show as Target on
Actual Results: shows as not in spreadsheet
Causes: JSON auto limits to first 1,000 rows. Might cache response.
Resolves: [MWPW-175550](https://jira.corp.adobe.com/browse/MWPW-175550)
**Test URLs:**
- Before: https://main--milo--adobecom.aem.page/docs/authoring/features/mmm/target-metadata-lookup?martech=off
- After: …
=> MWPW-175550 [MMM][MEP] Updates to metada-optimization json does not always reflect in MMM

libs/blocks/global-navigation/global-navigation.js
* Adding support to close the desktop gnav through `window.closeGnav()`
Resolves: [MWPW-175152](https://jira.corp.adobe.com/browse/MWPW-175152)
**Test URLs:**
- After: https://gnav-close--milo--adobecom.aem.page/?martech=off
Standalone gnav app - https://adobecom.github.io/nav-consumer/navigation.html?env=stage&navbranch=gnav-close
- Acrobat: https://main--dc--adobecom.hlx.live/acrobat?martech=off&milolibs=gnav-close--milo--adobecom
- BACOM: https://main--bacom--adobecom.hlx.live/?martech=off&milolibs=gnav-close--milo--adobecom
- CC: https://main--cc--adobecom.aem.live/creativecloud?martech=off&milolibs=gnav-close--milo--adobecom …
=> Updating close gnav function to support desktop mode

libs/blocks/merch/merch.js
* enable preview on stage.adobe.com
can only be verified via browser overrides, since its only reproducible on www.stage
(https://www.stage.adobe.com/cc-shared/fragments/drafts/mariia/document)
Resolves: [MWPW-175097](https://jira.corp.adobe.com/browse/MWPW-175097)
**Test URLs:**
- Before: https://main--milo--adobecom.aem.live/drafts/nala/features/commerce/plans?martech=off&georouting=off
- After: https://MWPW-175097--milo--markovicpredrag1209.aem.live/drafts/nala/features/commerce/plans?martech=off&georouting=off
=> MWPW-175097: Enable preview for stage.adobe.com

libs/utils/lana.js
* Support the DC's vanity domains: `sign.ing` and `edit.ing`.
* Refactor the conditions with `endsWith()`. It's short and clear.
* Web Test Runner can't mock window.location. No unit test coverage for the change. 
Resolves: [MWPW-167847](https://jira.corp.adobe.com/browse/MWPW-167847)
**Test URLs:**
- After: https://mwpw-167847--milo--adobecom.aem.page/?martech=off
=> MWPW-167847 Support .ing domains for LANA

libs/blocks/reading-time/reading-time.css, nala/blocks/reading-time/reading-time.test.js, nala/utils/nala.run.js
This adapts the color of the reading time block to be a darker shade of gray in order to meet minimum contrast for accessibility purposes. It's not clear what the usage of this block is across the website, so updating the color should be very low risk. The chosen gray is Spectrum 2-compliant and is the first option that actually meets the 4.5:1 color contrast.
Resolves: [MWPW-175634](https://jira.corp.adobe.com/browse/MWPW-175634)
**Test URLs:**
- Before: https://main--milo--overmyheadandbody.aem.page/drafts/nala/blocks/reading-time/reading-time-block?martech=off
- After: https://reading-time-color--milo--overmyheadandbody.aem.page/drafts/nala/blocks/reading-time/reading-time-block?martech=off
=> [MWPW-175634] Reading time color update for a11y

libs/blocks/global-navigation/global-navigation.js
when promobar is present and switched between portrait and landscape without refresh the gap is seen
Resolves: [MWPW-175590](https://jira.corp.adobe.com/browse/MWPW-175590)
**Test URLs:**
- After: https://mwpw-175590--milo--patel-prince.aem.page/?martech=off
**QA URL:**
- https://main--homepage--adobecom.aem.live/fr/homepage/index-loggedout?milolibs=mwpw-175590--milo--patel-prince
- https://main--cc--adobecom.aem.live/pl/creativecloud?milolibs=mwpw-175590--milo--patel-prince
- Acrobat: https://main--dc--adobecom.hlx.live/acrobat?martech=off&milolibs=MWPW-175590--milo--adobecom
- BACOM: …
=> switched between portrait and landscape without refresh the gap is seen

libs/blocks/merch/merch.js, libs/blocks/merch/merch.md, libs/blocks/merch/three-in-one.js, libs/blocks/modal/modal.js, nala/blocks/merch/three-in-one.test.js, test/blocks/merch/merch.test.js, test/blocks/merch/three-in-one.test.js
This PR fixes modal functionality for the following scenarios:
1. Browser navigation with modals: When a user opens a modal, navigates to another page, then clicks the browser's back button (or directly visits a URL with a modal hash), the modal will now properly reopen.
3. Filter preservation on catalog page (and any page that uses the merch-card-collection with the merch-sidebar):
When users have applied filters on the catalog page (like https://main--cc--adobecom.aem.live/products/catalog#category=graphic-design&types=desktop), opened the modal and clicked "Back" in the browser- the hash should change to the previous one (it does), and the modal should get closed (this was not working).  Also added checking to make sure the modal gets (re)opened only once, even if there are multiple …
=> MWPW-175589 and MWPW-175712: Modal does not reopen when navigation back

libs/blocks/preflight/checks/assets.js, libs/blocks/preflight/checks/constants.js, libs/blocks/preflight/checks/seo.js, libs/blocks/preflight/panels/accessibility.js, libs/blocks/preflight/panels/assets.js, libs/blocks/preflight/panels/general.js, libs/blocks/preflight/preflight.css, libs/utils/decorate.js, test/blocks/preflight/checks/assets.test.js, test/blocks/preflight/panels/assets.test.js
This adapts the Assets checks from the Preflight suite to also check videos, not only images. To keep a god balance between performance and quality, a factor of `1` has been chosen for video assets; meaning a video's dimensions should be at least those of its container. It considers:
* videos uploaded through Sharepoint, used in regular `video` tags. These are marked as _Video (Sharepoint)_;
* MPC videos, embedded through `iframe` tags. These are marked as _Video (MPC)_;
* videos uploaded through MPC with their source used in regular `video` tags. These are marked as _Video (MPC source)_.
A couple of additional checks can populate a new Notes field, as suggested [here](https://milo.adobe.com/docs/authoring/videos), should one of these conditions be met:
* if a Sharepoint video has …
=> [MWPW-170376] Preflight assets tab updates

libs/scripts/delayed.js, test/scripts/delayed.test.js
* Add support to track GenStudio campaign tags via RUM
**Test URLs:**
- After: https://integrate-genstudio-tracking--milo--cwjwisse.aem.live/?martech=off
=> feat: integrate GenStudio tracking

libs/features/jarvis-chat.js
Uses app id/ver from section metadata present in footer if not present in project config.
Resolves: [MWPW-176120](https://jira.corp.adobe.com/browse/MWPW-176120)
**Test URLs:**
- After: https://mwpw-176120--milo--adobecom.aem.page/?martech=off
QA:
Events: (no jarvis config)
- Before: https://main--events-milo--adobecom.aem.page/events?martech=off
- After: https://main--events-milo--adobecom.aem.page/events?martech=off&milolibs=MWPW-176120
Milo:
https://mwpw-176120--milo--adobecom.aem.page/drafts/nishantkaush/test/jarvis-footer/jarvis-on-demand?martech=off
=> MWPW-176120: use app id/ver from section metadata if not present in config

libs/blocks/hero-marquee/hero-marquee.css, libs/blocks/hero-marquee/hero-marquee.js
This fixes an edge case in the Hero Marquee when a return is added between the lockup image and its text inside a `con-block-row`. The lockup pattern is used in the Editorial Card, Hero Marquee, Aside and Notification Ribbon & Pill. Based on the lockup pattern used in those blocks, I tried to make the 3 possible use-cases look uniform when used inside the Hero Marquee:
* return between image(s) and text in a `con-block-row`;
* space between image(s) and text in a `con-block-row`;
* lockup as part of the main Hero Marquee content.
| <img width="491" alt="Screenshot 2025-07-09 at 17 35 18" src="https://github.com/user-attachments/assets/30b959ba-9739-4dc5-a34c-be040d133299" /> | <img width="491" alt="Screenshot 2025-07-09 at 17 35 33" …
=> [MWPW-175533] Hero Marquee lockup text overlap fix

libs/ui/controls/tagSelector.css
Provide a positioning context for the absolutely-positioned `.cb` checkbox by making its parent `.search-item` relative. This fixes overlap/placement issues with checkboxes in the search list.
Resolves: [MWPW-176102](https://jira.corp.adobe.com/browse/MWPW-176102)
**Test URLs:**
- Before: [https://main--milo--adobecom.aem.page/?martech=off](https://main--milo--adobecom.aem.page/?martech=off)
- After: [https://mwpw-176102-stage--milo--adobecom.aem.page/?martech=off](https://mwpw-176102-stage--milo--adobecom.aem.page/?martech=off)
Before:
After:
=> fix(css): TagSelector - add position: relative to .search-item to support absolute .cb checkbox

libs/blocks/preflight/checks/assets.js
This also includes MPC videos rendered in open modals in the assets checks being run on the page, as suggested in https://github.com/adobecom/milo/pull/4510#discussion_r2194555272.
Resolves: [MWPW-176288](https://jira.corp.adobe.com/browse/MWPW-176288)
**Test URLs:**
- Before: https://main--milo--overmyheadandbody.aem.page/docs/authoring/tall-video-modal?martech=off
- After: https://preflight-vid-modal--milo--overmyheadandbody.aem.page/docs/authoring/tall-video-modal?martech=off
=> [MWPW-176288] Preflight check vids from open modal

nala/utils/global.setup.js, nala/utils/nala.run.js, nala/utils/pr.run.sh
* Redirect Nala test runs targeting `main` branch to [milo.adobe.com](http://milo.adobe.com/) instead of `main--milo--adobecom.aem.live`
* This change aims to reduce/remove unnecessary automated test traffic from `main--milo--adobecom.aem.live`
`
* Context
* As per slack conversation, starting July 4th, Its observed that traffic spikes on` main--milo--adobecom.hlx.live` every 5 hours without `x-forwarded-host`.
* This PR ensures automated Nala test runs on `main` branch are routed to `milo.adobe.com `
Resolves: [MWPW-176044](https://jira.corp.adobe.com/browse/MWPW-176044)
**Test URLs:**
- After: https://nala-config--milo--adobecom.aem.page/?martech=off
=> [NALA][MWPW-176044] Redirect Nala test runs targeting main branch to milo.adobe.com

libs/blocks/caas/utils.js, test/blocks/caas/send-to-caas.test.js, test/blocks/caas/utils.test.js, tools/send-to-caas/bulk-publish-to-caas.js, tools/send-to-caas/send-utils.js
This PR introduces **Graybox Experience ID support for CaaS**. The changes ensure that when a page is served from a graybox domain, the experience ID is correctly detected and included in the CaaS card metadata. This enables more accurate experience mapping for graybox environments, which will be used for executive reviews.
- **Graybox Experience ID Extraction:**  
- Added a utility (`getGrayboxExperienceId`) that extracts the experience ID from both standard graybox domains (e.g., `https://myexp.us-graybox.adobe.com/`) and stage graybox domains (e.g., `https://stage--us-graybox-adobecom.aem.page/myexp/`).
- The logic is robust and handles malformed or non-graybox URLs gracefully.
- **CaaS Metadata Enhancement:**  
- The CaaS card metadata now includes a `gbExperienceID` property when a …
=> MWPW-172799: Graybox Support for CaaS

libs/blocks/preflight/accessibility/audit-image-alt-text.js
This brings back the `alt` attribute values over images once Preflight is enabled on a page.
| <img width="1035" height="591" alt="Screenshot 2025-07-16 at 17 23 52" src="https://github.com/user-attachments/assets/a87178c1-8a7a-4f76-86ec-456d059d97a2" /> | <img width="1035" height="591" alt="Screenshot 2025-07-16 at 17 24 07" src="https://github.com/user-attachments/assets/b59c933e-f9d2-4637-9fdc-0b0b67fc4755" /> |
Resolves: [MWPW-176491](https://jira.corp.adobe.com/browse/MWPW-176491)
**Test URLs:**
- Before (PSI): https://main--milo--overmyheadandbody.aem.page/?martech=off
- After (PSI): https://preflight-alt-labels--milo--overmyheadandbody.aem.page/?martech=off
- Before (PS page): …
=> [MWPW-176491] Re-add alt labels from Preflight

libs/blocks/preflight/preflight.css
* It fixes the Text is overlapping in the Preflight Accessibility tab when the right column has multiple entries
Resolves: [MWPW-176564](https://jira.corp.adobe.com/browse/MWPW-176564)
**Test URLs:**
- After: https://text-overlap--milo--adobecom.aem.page/?martech=off
Fixes following Issue
Issue: 
Test URL: https://main--cc--adobecom.aem.page/products/illustrator?milolibs=text-overlap--milo--skumar09&mep=off&martech=off
=> [MILO][Preflight] Text overlapping in the Preflight Accessibility tab

libs/blocks/section-metadata/section-metadata.css
Adding `top` and `bottom` specific spacing tokens to sections. Can be used in combination to have different spacing on top than bottom.
* Static options also updated to work with top/bottom options.
* Minor CSS clean up for spacing tokens
Resolves: [MWPW-174422](https://jira.corp.adobe.com/browse/MWPW-174422)
**Test URLs:**
- Before: https://main--milo--adobecom.aem.page/drafts/rclayton/poc/section-spacing?martech=off
- After: https://section-spacing-tokens-update--milo--adobecom.aem.page/drafts/rclayton/poc/section-spacing?martech=off
=> MWPW-174422 - Section metadata spacing tokens update

libs/blocks/library-config/library-config.js
This PR is fixing the issue where icons are not loading for the sidekick library.
Resolves: [MWPW-176806](https://jira.corp.adobe.com/browse/MWPW-176806)
1. open test URL
2. go to icons
3. icons should load
**Before:**
**After:**
**For PSI check:**
- Before: https://stage--milo--adobecom.aem.page/drafts/rbogos/page-default?martech=off
- After: https://mwpw-176806-federal-icons--milo--robert-bogos.aem.page/drafts/rbogos/page-default?martech=off
**Test on the below:**
- Before: https://stage--milo--adobecom.aem.page/tools/library
- After: https://mwpw-176806-federal-icons--milo--robert-bogos.aem.page/tools/library
=> [MWPW-176806] Icons not loading for the sidekick library

libs/features/personalization/personalization.js, libs/martech/martech.js
When a user has just logged in, they are normally taken to Adobe home.  However, if you use the button in the marquee on https://www.adobe.com/creativecloud/perks.html, the user is returned to the same page and the adobeIMS function MEP is using is incorrectly returning that they are logged out.  Test shows the function does return the correct answer later in the page's life cycle, but it would cause a page performance impact to wait until the function returns the correct answer.
It looks like the isSignedOut function in utils that is used for pznV2 gives an accurate result immediately.  So we will switch to using that function instead.
Resolves: [MWPW-176743](https://jira.corp.adobe.com/browse/MWPW-176743)
**Test URLs:**
- …
=> MWPW-176743 [MEP] loggedin tag does not work if user logs in and is taken directly back to a page

libs/blocks/preflight/checks/asoApi.js
Adds the IMS/Spacecat implementation to obtain a session token.
- We can't always ensure an author is logged in
- We don't have a "not-logged-in" screen/scenario (TODO: Create follow up ticket)
- As far as I can see, there's no feedback at all when the fails timeout.
I only implemented the scenario of a signed in user on da-bacom trying to get results from the ASO preflight.
Upon launching the test link, this should make a request to the login and job endpoints of spacecat.
Resolves: [MWPW-176919](https://jira.corp.adobe.com/browse/MWPW-176919)
**Test URLs:**
PSI Check:
- https://preflight-poc-auth--milo--adobecom.aem.live/
- Before: https://main--da-bacom--adobecom.aem.live/
- After: https://main--da-bacom--adobecom.aem.live/?milolibs=preflight-poc-auth
=> ASO Preflight authentication

libs/blocks/fragment/fragment.js, libs/utils/utils.js
Reverts adobecom/milo#4595 as this breaks placeholders
https://main--dc--adobecom.aem.live/acrobat/features?milolibs=stage
Before: https://main--dc--adobecom.aem.live/acrobat/features?milolibs=stage
After: https://main--dc--adobecom.aem.live/acrobat/features?milolibs=revert-4595-inlinefragfedplaceholders
=> Revert "MWPW-176866 Placeholders within fragments are not resolved anymore"

libs/blocks/locui-create/input-urls/view.js
Stage merge for - https://github.com/adobecom/milo/pull/4593
Custom merge option in the "regional edit behavior" dropdown is eliminated in milo studio.
Resolves: [MWPW-176763](https://jira.corp.adobe.com/browse/MWPW-176763)
Test URLs:
Before: https://milostudio-stage--milo--adobecom.aem.page/tools/locui-create
After: https://miostudiosync--milo--adobecom.aem.page/tools/locui-create
=> [Loc] | Stage Deployment | Eliminating custom merge option from regional editing

libs/blocks/fragment/fragment.js
In a previous PR, we started passing inline fragments through loadArea like non-inline fragments. However, this function normally also processes placeholders found in the fragment. This causes fed placeholders in gnav to break.  We need a solution that keeps the processing of nested fragments while not processing placeholders like before.
Resolves: [MWPW-176866](https://jira.corp.adobe.com/browse/MWPW-176866)
**Test URLs:**
- After: https://inlinefragconditionalloadarea--milo--adobecom.aem.page/?martech=off
QA links:
Needs to still have a blue button
Before: https://main--cc--adobecom.aem.page/drafts/mepdev/fragments/2025/q3/pznfailswithinline/inline-no-mep
After: https://main--cc--adobecom.aem.page/drafts/mepdev/fragments/2025/q …
=> MWPW-176866 v2 Placeholders within fragments are not resolved anymore

libs/blocks/share/share.css, libs/blocks/share/share.js
Issues: 
- When user clicks copy button, `Copied`  text is not announced by the screen reader.
- Hovering tooltip popup is not possible
I added [\u200b](https://unicode-explorer.com/c/200B) char because if user clicks button again, reader will ignore it because text is the same as before.
Resolves: [MWPW-176818](https://jira.corp.adobe.com/browse/MWPW-176818) , [MWPW-176923](https://jira.corp.adobe.com/browse/MWPW-176923)
**Test URLs:**
- Before: https://main--milo--adobecom.aem.page/docs/library/kitchen-sink/share?martech=off
- After: https://share-copy-a11y--milo--adobecom.aem.page/docs/library/kitchen-sink/share?martech=off
**CC URLs:**
- Before: https://main--cc--adobecom.aem.page/es/creativecloud/video/discover/how-to-trim-video?akamaiLocale=es
- After: …
=> Improve share block accessibility

libs/blocks/locui-create/input-locale/index.js
* Passed locales  in the correct format ${languagecode}|${locale} to get removed when region is deselected
Resolves: https://jira.corp.adobe.com/browse/MWPW-177102
**Test URLs:**
- Before: https://stage--milo--adobecom.hlx.page/tools/loc?martech=off
- After: https://MWPW-175128-locales-select-deselect--milo--saurabhsircar11.hlx.page/tools/loc?martech=off
**CC URLs: **
- Before: https://main--cc--adobecom.aem.page/tools/locui-create?milolibs=milostudio-dev&ref=main&repo=cc&owner=adobecom&host=www.adobe.com&project=Creative+Cloud&env=local&workflow=normal
- After:[ https://MWPW-175128-locales-select-deselect--milo--saurabhsircar11.hlx.page/tools/loc?martech=off](https://main--cc--adobecom.aem.page/tools/locui-create?milolibs=MWPW-175128-locales-select-deselect--milo--saurabhsircar11&ref=main …
=> [LOC]MWPW-177102 - Deselect region related locales

libs/blocks/locui-create/input-urls/view.js
Prod merge for - https://github.com/adobecom/milo/pull/4593
Custom merge option in the "regional edit behavior" dropdown is eliminated in milo studio.
Resolves: [MWPW-176763](https://jira.corp.adobe.com/browse/MWPW-176763)
Test URLs:
Before: https://milostudio--milo--adobecom.aem.page/tools/locui-create
After: https://studioprodsync--milo--adobecom.aem.page/tools/locui-create
=> [Loc] | Prod Deployment | Eliminating custom merge option from regional editing

libs/blocks/locui-create/utils/utils.js
*  remove concatenation of ${languagecode}|${liveCopy} as livecopiesArr has concatenated values.
Resolves: https://jira.corp.adobe.com/browse/MWPW-177461
**Test URLs:**
- Before: https://stage--milo--adobecom.aem.page/tools/locui-create?martech=off
- After: https://MWPW-177461-edit-locales-issue--milo--saurabhsircar11.aem.page/tools/locui-create?martech=off
**CC URLs: **
- Before: https://main--cc--adobecom.aem.page/tools/locui-create?milolibs=milostudio-dev&ref=main&repo=cc&owner=adobecom&host=www.adobe.com&project=Creative+Cloud&env=local&workflow=normal
- After: https://main--cc--adobecom.aem.page/tools/locui-create?milolibs=MWPW-177461-edit-locales-issue--milo--saurabhsircar11&ref=main&repo=cc&owner=adobecom&host=www.adobe.com&project=Creative+Cloud&env=local&workflow=normal
=> MWPW-175128 - Edit locales issue on 3rd step

libs/blocks/global-navigation/global-navigation.js, libs/blocks/global-navigation/utilities/keyboard/mobilePopup.js
* Mobile global footer arrow keyboard navigation fixed
* Added the functionality of closing lnav if clicked on active item
Resolves: [MWPW-177039](https://jira.corp.adobe.com/browse/MWPW-177039), [MWPW-167705](https://jira.corp.adobe.com/browse/MWPW-167705)
**Test URLs:**
- After: https://footer-keyboard--milo--adobecom.aem.page/?martech=off
- Acrobat: https://main--dc--adobecom.hlx.live/acrobat?martech=off&milolibs=footer-keyboard--milo--adobecom
- BACOM: https://main--bacom--adobecom.hlx.live/?martech=off&milolibs=footer-keyboard--milo--adobecom
- CC: https://main--cc--adobecom.aem.live/creativecloud?martech=off&milolibs=footer- …
=> Mobile global footer arrow keyboard navigation fixed

.github/workflows/import/index.js
I've noticed that the DC rolling import flow failed due to running out of memory. https://github.com/adobecom/milo/actions/runs/16802946956/job/47588605400 
I remember a similar PR safeguard against circular fragment references which lead to issues on the FE code, so let's also safeguard it within the importer, in case a fragment is accidentally referring to itself causing a loop.
Resolves: [MWPW-174328](https://jira.corp.adobe.com/browse/MWPW-174328)
**Test URLs:**
- After: https://dont-crash-on-circular-fragments--milo--mokimo.aem.page/?martech=off
=> Fix memory issues when fetching nested circular fragments

nala/blocks/actionitem/actionitem.test.js, nala/blocks/marketo/marketo.test.js
* Currently `Marketo` block tests are f`reaky/failing in GitHub CI/CD` run due to `delays`.
* This PR will disable the execution of `Marketo Block` tests, till we fix the delay issue
Resolves: [MWPW-177991](https://jira.corp.adobe.com/browse/MWPW-177991)
**Test URLs:**
- After: https://disable-marketo--milo--adobecom.aem.page/?martech=off
=> [MWPW-177991][NALA]Disable Marketo block ui tests till we fix the delay issues

libs/mep/dc1059/notification/notification.css, libs/mep/dc1059/notification/notification.js, libs/mep/dc1059/section-metadata/section-metadata.css, libs/mep/dc1059/section-metadata/section-metadata.js, libs/mep/dc1059/section-metadata/sticky-section.js
This PR adds a temp variant ('tempvariant') to the MEP folder for the notifications block. 
libs/mep/ace1052 was used as the starting point, but the only actual changes from those files should be found in the notifications.css file. 
Resolves: [MWPW-177302](https://jira.corp.adobe.com/browse/MWPW-177302)
Steps to QA have been copied to the comment section of the above ticket, to ensure that it doesn't interfere with the PSI check. 
**Test URLs:**
- After: https://frictionlessstickyctasupport--milo--adobecom.aem.page/?martech=off
=> MWPW-177302[Milo] Add support for Frictionless Sticky CTA

tools/send-to-caas/send-utils.js
ID lookup tool broken when primary CTA is missing. We need to make sure that we are picking up a cta when authors do not explicitly author one to ensure the ID lookup tool will work correctly downstream.
Resolves: [MWPW-174582](https://jira.corp.adobe.com/browse/MWPW-174582)
Test URLs:
After: https://mwpw-174582-2--milo--sheridansunier.aem.page/?martech=off
=> MWPW-174582: retrying to fix id lookup

libs/blocks/adobetv/adobetv.js, libs/utils/utils.js, test/blocks/adobetv/adobetv.test.js, test/blocks/adobetv/mocks/body.html
Adding support for rewriting the AdobeTV iframe URL to update captions (if available) based on the tenant locale mapping.
Below changes
1. Added a tenant mapping JSON in Federal at /federal/assets/data/adobetv-captions.json. This contains sheets per key to support tenant-specific mappings.
2. Added a config field atvCaptionsKey – this needs to be set by tenants.
3. In the AdobeTV block a. Rendering of the iframe is moved to a separate function. b. Load the captions mapping when captions exist in the URL and atvCaptionsKey is defined. c. Rewrite the captions based on the geo and mapping. Add an eng fallback to the mapping — i.e., if the derived caption is ger, add both ger,eng.
Resolves: [MWPW-168315](https://jira.corp.adobe.com/browse/MWPW-168315)
**Test URLs:**
- Before: …
=> MWPW-168315 Auto set close captions for videos

libs/blocks/language-selector/language-selector.js, libs/utils/utils.js, test/utils/utils.test.js
* Move languages-mapping.json data to languages-config.json This will reduce one extra network call.
Resolves: [MWPW-175711](https://jira.corp.adobe.com/browse/MWPW-175711)
**Test URLs:**
- Before: https://main--milo--adobecom.aem.page/drafts/ruchika/language/document1?martech=off
- After: https://lang-selector--milo--adobecom.aem.page/drafts/ruchika/language/document1?martech=off
News:
- Before: https://main--news--adobecom.hlx.page/news?milolibs=stage&martech=off
- After: https://main--news--adobecom.hlx.page/news?milolibs=lang-selector&martech=off
Testing Notes:
1. Expected behavior can be properly tested on newsroom link provided above as that has proper language object created in config.
2. Make sure search functionality works as before and user is able to search by exact string …
=> [MWPW-175711] Optimize network calls for langauge selector on language based sites

libs/blocks/card/card.css, libs/blocks/card/card.js
This increases the number of lines shown before adding an ellipsis in the card content, if the default letter or word spacing have been adapted, usually via the "Text Spacing Editor" extension. This aims to keep a balance between the original UI specs (clipping the title after 2 lines and the text after 3 lines) and accessibility requirements of ensuring that the same content is visible for users requiring text spacing adaptations and those who don't.
| <img width="1250" height="516" alt="Screenshot 2025-08-12 at 14 26 10" src="https://github.com/user-attachments/assets/1db6a789-a334-46e8-9d01-2538278eb0e8" /> | <img width="1250" height="610" alt="Screenshot 2025-08-12 at 14 25 03" …
=> [MWPW-177247] Adapt card if text extension is active

libs/blocks/marketo-config/context.js, libs/blocks/marketo-config/marketo-config.css, libs/blocks/marketo-config/marketo-config.js, libs/blocks/marketo-config/step-panel.js, libs/blocks/marketo/marketo-multi.js, libs/blocks/marketo/marketo.js, test/blocks/marketo-config/marketo-config.test.js
* Configure Marketo multi-step form with 2 & 3 step variations via step panel.
* Fields can be added to any step.
* Configurator now loads from iframe to allow for form reinitialization.
* Copied template code out of MCZ and passed template config via messages.
Resolves: [MWPW-175124](https://jira.corp.adobe.com/browse/MWPW-175124)
**Test URLs:**
- Before: https://main--milo--adobecom.aem.page/drafts/bmarshal/marketo/step-2?martech=off
- After: https://bmarshal-step-config--milo--adobecom.aem.page/drafts/bmarshal/marketo/step-2?martech=off
- Before: https://main--milo--adobecom.aem.page/drafts/bmarshal/marketo/step-3?martech=off
- After: https://bmarshal-step-config--milo--adobecom.aem.page/drafts/bmarshal/marketo/step-3?martech=off
- Before: …
=> MWPW-175124 Configurable Multi-Step

libs/blocks/merch/merch.js, test/blocks/merch/merch.test.js, test/blocks/merch/mocks/body.html
This change fixes an issue where the #_button-fill link decorator was not being applied to “merch” CTAs in a hero marquee block in Milo. Previously, only the default blue button style was available for merch links, because the merch link handler did not recognize or strip the #_button-fill fragment.
Here's the slack thread for additional context:
🧵: [https://adobedotcom.slack.com/archives/C03B0BUA75E/p1742958293820199](https://adobedotcom.slack.com/archives/C03B0BUA75E/p1742958293820199)
📸: <img width="1915" height="680" alt="image" src="https://github.com/user-attachments/assets/fd6d0ab2-a691-443a-a745-19a5199c8e9d" />
🔗: https://main--cc--adobecom.aem.page/drafts/aullal/backup/mwpw-170462?milolibs=mwpw-170462-merch-cta-style-fix--milo--ajullal
Resolves: …
=> fix(merch): extract button styling classes from URL hash parameters

libs/blocks/share/share.css, libs/blocks/share/share.js, test/blocks/share/share.test.js
This ensures that the text above the share icons from the Share block is announced as a heading. An option would be to actually use a heading element, but that leads to different styling needs, so I've chosen to address the issue via attributes on the existing element.
An interesting addition is the `getPrevHeadingLevel` method, which tries to find the heading level of the first `h` tag preceding a given element. This could prove useful in the future, since Adobe Accessibility rules state that the heading hierarchy should be clear on the page (i.e. no jumping from `h2` to `h4` or viceversa).
LE: After @zagi25's note, I noticed a few other small details to address:
* the `tracking-header` class was applied inconsistently, sometimes it didn't even include the heading text;
* the code …
=> [MWPW-177996] Use heading for share block title

libs/scripts/delayed.js, libs/styles/block-notifications.css, libs/utils/block-notifications.js
Analyzes blocks on a page and compares with what's been entered in the referenced `.json` file. If matches are found blocks get labeled with:
* Obsolete - with optional link to related documentation via info icon.
* Not consonant
Additional details:
* Code is executed after page has loaded - via `delayed.js`. 
* Only ran on `.page` urls.
* Includes "Hide notifications" button to toggle showing/hiding labels. This also works with labels applied via Preflight (blocks marked as Obsolete do not get hidden).
* If there are not any blocks found on a page referenced from the .json nothing is applied and the toggle button is not added.
Resolves:
* [MWPW-171611](https://jira.corp.adobe.com/browse/MWPW-171611)
* [MWPW-170416](https://jira.corp.adobe.com/browse/MWPW-170416)
**Test URLs:**
- Before: …
=> MWPW-171611 - Block notifications

libs/blocks/caas/utils.js
* Update graybox domain regex to support subdomain patterns
* Change regex from ([a-z]+-) to ([a-z-]+-) to allow hyphens in subdomain
* Now supports patterns like homepage-graybox.adobe.com while maintaining security
Resolves: [MWPW-177660](https://jira.corp.adobe.com/browse/MWPW-177660)
**Test URLs:**
- After: https://MWPW-177660--milo--adobecom.aem.page/?martech=off
=> MWPW-177660: More lenient regex to support - and not

libs/deps/mas/merch-card.js, libs/features/mas/dist/mas.js, libs/features/mas/src/variants/plans.css.js
Fixes horizontal scroll in plans collection. 
Resolves: [MWPW-178287](https://jira.corp.adobe.com/browse/MWPW-178287)
Plans URL: `https://main--cc--adobecom.aem.page/creativecloud/plans?milolibs=MWPW-178287`
**Test URLs:**
- After: https://MWPW-178287--milo--adobecom.aem.page/?martech=off
=> MWPW-178287: Fix horizontal scroll in plans collection

libs/utils/utils.js
intermittently seen the issue of multiple slash (/) in gnav links in news US page
Solution:
Added a fix to handle cases where localeString or split[2] are empty.
Earlier, the logic intermittently prefixed values with /, which resulted in incorrect paths like / or //xyz. With the new change, we only add the / when a value actually exists, ensuring clean and valid path generation for both locale and path segments.
Resolves: [MWPW-178137](https://jira.corp.adobe.com/browse/MWPW-178137)
**Test URLs:**
- After: https://mwpw-178137--milo--patel-prince.aem.page/?martech=off
**QA URL:**
- https://main--news--adobecom.aem.page/news?milolibs=mwpw-178137--milo--patel-prince
- https://main--cc--adobecom.aem.page/creativecloud?milolibs=mwpw-1 …
=> intermittently seen the issue of multiple slash (/) in gnav links in news US page

.github/workflows/import/index.js
* Skip complex files in for da-express-milo's content sync, as they will stay in Sharepoint for now
Resolves: https://jira.corp.adobe.com/browse/MWPW-179661
**Test URLs:**
- Before: https://stage--milo--adobecom.aem.live/?martech=off
- After: https://da-express-import-exclude--milo--adobecom.aem.live/?martech=off
=> [DA Express Migration] Exclude Complex Sheets from Sync

libs/blocks/brand-concierge/brand-concierge.js, test/blocks/brand-concierge/brand-concierge.test.js
* Hide the brand concierge block if the user has not consented to performance cookies
Resolves: [MWPW-178626](https://jira.corp.adobe.com/browse/MWPW-178626)
**Test URLs:**
- After: https://bc-consent--milo--meganthecoder.aem.page/drafts/methomas/brand-concierge?martech=off
=> MWPW-178626 Brand Concierge - add consent check

libs/utils/utils.js, test/utils/utils.test.js
Currently, when a link with #_dnt appears within deeply-nested inline fragments (#_inline), they get passed through decorateLinks more than once. During the first pass, #_dnt is removed, so on the second pass the link is localized when it should not be. 
This PR adds an attribute and a check for it to #_dnt links within deeply-nested inline fragments so they do not get localized.
Steps to QA: 
Check the before and after test urls below.
If you hover over the LinkedIn Premium card cta, at the bottom of the page, the before link should show the localized link (inlcudes "dk") and the after link should not show "dk".
after image example:
Resolves: [MWPW-178444](https://jira.corp.adobe.com/browse/MWPW-178444)
**Test URLs:**
- Before: https://main--cc--adobecom.aem.page/dk/drafts/mepdev/fragment …
=> [MWPW-178444] #_dnt within deeply nested inline fragments still gets localized

libs/blocks/brand-concierge/brand-concierge.js
* Fix bug where clicking on a Brand Concierge prompt card generated two clicks, one on the card and one on the submit button
Resolves: [MWPW-179461](https://jira.corp.adobe.com/browse/MWPW-179461)
**Test URLs:**
- After: https://bc-analytics-bug--milo--meganthecoder.aem.page/drafts/methomas/brand-concierge?martech=off
(To test, remove ?martech=off and look in the console for click event logs)
=> MWPW-179461 Brand Concierge - Fix duplicate analytics

libs/blocks/global-navigation/global-navigation.js
when the different app banner height is present the primary cta will not be visible in landscape mode completely
Resolves: [MWPW-167998](https://jira.corp.adobe.com/browse/MWPW-167998)
**Test URLs:**
- After: https://mwpw-167998--milo--patel-prince.aem.page/?martech=off
**QA URL:**
- https://main--milo--adobecom.aem.page/drafts/devashish/banner/branch-banner-inline
- Acrobat: https://main--dc--adobecom.hlx.live/acrobat?martech=off&milolibs=MWPW-167998--milo--adobecom
- BACOM: https://main--bacom--adobecom.hlx.live/?martech=off&milolibs=MWPW-167998--milo--adobecom
- CC: https://main--cc--adobecom.aem.live/creativecloud?martech=off& …
=> MWPW-167998 when the different app banner height is present the primary cta will not be visible in landscape mode completely

nala/blocks/merch/default-flags.test.js, nala/blocks/merch/three-in-one.test.js, nala/blocks/merchcard/merchcard.test.js, nala/blocks/tabs/tabs.test.js, nala/features/commerce/commerce.test.js, nala/features/mas/acom/plans/plans.test.js, nala/features/mas/acom/plans/plansdocs.test.js, nala/features/mas/benchmark/benchmark.test.js, nala/features/mas/ccd/masccd.test.js, nala/features/mas/docs/masdocs.test.js, nala/features/mas/express/express.spec.js, nala/features/mas/express/express.test.js, nala/features/promotions/promotions.test.js, nala/libs/commerce.js
- As part of integrating milo tests in MAS PR workflow, we need to enable `?maslibs` parameter in the test urls
- Refactors helper functions used in commerce tests
Resolves: [MWPW-179632](https://jira.corp.adobe.com/browse/MWPW-179632)
**Test URLs:**
- After: https://MWPW-179632--milo--afmicka.aem.live/?martech=off
=> MWPW-179632 [NALA]: enable maslibs usage in commerce tests

libs/blocks/carousel/carousel.css, libs/blocks/carousel/carousel.js, libs/blocks/editorial-card/editorial-card.css, libs/blocks/editorial-card/editorial-card.js
This adapts the behavior of when Editorial Card blocks are used inside the Carousel; the requirement in the context of the Mweb project was to allow authors to use a new variant on the carousel block (`ups-desktop`) that transitions from the regular slides on mobile devices (below `900px`) to a grid (similar to the `n-up` pattern) on desktop (starting from `900px`). Additionally, Editorial Card blocks used under these circumstances should automatically switch from the "closed" design on mobile (~content has some padding and border around it) to the "open" one on desktop.
Resolves: [MWPW-177653](https://jira.corp.adobe.com/browse/MWPW-177653)
**Test URLs:**
- Before: https://main--milo--overmyheadandbody.aem.page/drafts/ramuntea/carousel-x-editorial?martech=off
- After: …
=> [MWPW-177653] Mobile carousel desktop ups

libs/blocks/merch/three-in-one.js
Excludes inline preloading of 3-in-1 for iOS Safari since it's not supported.
More info: 
https://caniuse.com/?search=loading%3D%22lazy%22
https://stackoverflow.com/questions/72491824/why-lazy-loading-on-img-is-broken-on-mobile-browser-ios#:~:text=It%20says%20right%20here%20on%20the%20CanIUse%20that%20the%20loading%3D%22lazy%22%20attribute%20is%20not%20yet%20supported%20on%20any%20version%20of%20Safari%20unless%20the%20browser%20is%20manually%20put%20in%20Experimental%20Mode.%20For%20browser%20specific%20issues%20it%20is%20always%20good%20to%20check%20caniuse%20for%20compatibility.
`CC test URL (has to be tested from mobile safari): https://main--cc--adobecom.aem.live/creativecloud/photography?milolibs=MWPW-180866`
Resolves: [MWPW-180866](https://jira.corp.adobe.com/browse/MWPW-180866) …
=> MWPW-180866: Excludes iOS Safari from inline preloading 3-in-1

libs/blocks/library-config/lists/icons.js, libs/features/icons/icons.js
DA uses 'key, icon' while milo uses 'name, url' .. let's switch to what DA does so that we can re-use the federal icon sheet. For backwards compatibility, I added both versions to the sheet, so this PR shouldn't break anything and be forward-compatible.
Resolves: [MWPW-180007](https://jira.corp.adobe.com/browse/MWPW-180007)
Tested this on DA and Sharepoint using the new format using a local overwrite for the json // icon code.
- Remove name/url/dnt sheet from the federal sheet
- add the right federal sheet to the DA project configs.
**Test URLs:**
- After: https://refactor-icon-library--milo--adobecom.aem.page/?martech=off
=> Refactor icon library to adhere to the DA standard

libs/utils/utils.js
Treat `aem.reviews` as stage env, similar to `.page, .live, .graybox` etc. 
This PR is also required for https://github.com/adobecom/milo/pull/4812 to work
Resolves: [MWPW-179804](https://jira.corp.adobe.com/browse/MWPW-179804)
Test link on aem reviews: https://osahin--osahin-mwpw-179804--milo--adobecom.aem.reviews/docs/library/kitchen-sink/accordion/40
**Test URLs:**
- After: https://osahin-mwpw-179804--milo--adobecom.aem.page/?martech=off
=> Treat aem.reviews as stage environment

libs/blocks/susi-light-login/susi-light-login.css, libs/blocks/susi-light-login/susi-light-login.js
* Adds the ability to add the layout string expected by the susi config to the block as a classname to allow Susi to use that layout. Small style considerations. 
Resolves: [MWPW-178197](https://jira.corp.adobe.com/browse/MWPW-178197)
**Test URLs:**
- Before: https://main--milo--jasonhowellslavin.aem.live/?martech=off
- After: https://susi-config-layout--milo--jasonhowellslavin.aem.live/?martech=off
To test that the it works as expected, use: 
https://ims--milo--adobecom.aem.page/drafts/slavin/scratch in incognito
=> MWPW-178197: SUSI Light Layouts

libs/blocks/brand-concierge/brand-concierge.css, libs/blocks/brand-concierge/chat-ui-config.js
* Update inline and chat disclaimer font to 11px
* Remove extra spacing under chat disclaimer
Resolves: [MWPW-181021](https://jira.corp.adobe.com/browse/MWPW-181021)
**Test URLs:**
- After: https://bc-disclaimer--milo--adobecom.aem.page/drafts/methomas/brand-concierge?martech=off
=> MWPW-181021 Brand Concierge - Disclaimer text styles

.github/workflows/import/index.js
Port from https://github.com/adobe/da-nx/commit/481b8ba74bdc021c0b6ecfdf1082cecc58c3ef84
No QE required for this zero impact port.
**Test URLs:**
- After: https://nx-sync--milo--adobecom.aem.page/?martech=off
=> [DA Importer] Fix hlx vs aem domains

libs/blocks/brand-concierge/chat-ui-config.js
* Disable image carousel from Brand Concierge chat responses
Resolves: [MWPW-181071](https://jira.corp.adobe.com/browse/MWPW-181071)
**Test URLs:**
- After: https://bc-carousel--milo--adobecom.aem.page/drafts/methomas/brand-concierge?martech=off
Click "I’d like to explore templates to see what I can create." - on main this should generate a carousel and on the feature branch it should not.
=> MWPW-181071 Brand Concierge - Remove image carousel

libs/blocks/icon-block/icon-block.css
Double borders were coming when icon block was used inside the fragment for mweb
* Add your
* Specific
Resolves: [MWPW-181155](https://jira.corp.adobe.com/browse/MWPW-NUMBER)
**Test URLs:**
- Before: https://main--milo--adobecom.aem.page/drafts/klee/jira-ticket/mwpw-181155-iconblock-doublemargin
- After: https://mwpw-181155--milo--suhjainadobe.aem.page/drafts/klee/jira-ticket/mwpw-181155-iconblock-doublemargin
=> MWPW-181155 mWeb icon block fragment double margin

libs/features/mep/addons/lob.js
* We are trying to do performance testing for this feature on prod, but the cookie we rely on seems to sometimes be saved under a different value.  Will investigate if this is an error or not.  But to unblock performance testing, for now I will just check for both values.
Resolves: [MWPW-172886](https://jira.corp.adobe.com/browse/MWPW-172886)
**Test URLs:**
- After: https://lobecidtempfix--milo--adobecom.aem.page/?martech=off
=> MWPW-172886 [MEP] Support MEP AICS pzn tags recieved from API - cookie fix

nala/features/mas/acom/plans/plans.test.js
fix failing deeplink test on stage. 
Test was failing all along on the PR introducing the change but somehow with the last commit it became green without updating Nala test
Resolves: nojira
**Test URLs:**
- After: https://nojira-1--milo--afmicka.aem.page/?martech=off
=> MAS: fix deeplink Nala test
