- blocks/header/header.css
- blocks/header/header.js
- blocks/section/section.js
Please always provide the [GitHub issue(s)](../issues) your PR is for, as well as test URLs where your change can be observed (before and after):
Resolves: <gh-issue-id>
Test URLs:
- After: https://remove_home--milo--adobecom.hlx.page/
> Fix home nav.

- scripts/scripts.js
- test/scripts/scripts.test.js
* Change makeRelative to swap emdashes for double hyphen.
Resolves: MWPW-108710
Test URLs:
- After: https://handle-emdash--milo--adobecom.hlx.page/fr/
> MWPW-108710 - Handle Emdashes

- libs/blocks/modals/modals.js
- test/blocks/modals/modals.test.js
@auniverseaway, here is new PR that removes modal on close.
Resolves: [MWPW-110446](https://jira.corp.adobe.com/browse/MWPW-110446)
Test URLs:
- Before: https://main--milo--adobecom.hlx.page/docs/authoring/how-to-videos
- After: https://video-control--milo--adobecom.hlx.page/docs/authoring/how-to-videos
There are two ways to close the modal
1. Click the `x` on the right top corner of the modal.
2. Click outside of modal then press ESC key.
With case 2, it doesn't only keep playing the video in background but it doesn't also let user reopening same modal because the hash value doesn't get cleared.
This PR will fix the bug for both scenarios of closing  modal and clear the hash value as well.
I also added the `how to videos` link on https://milo.adobe.com/docs/authoring/.  I hope this is …
> modal removal on close.

- libs/blocks/list.js
Reverting list.js as it introduced breaking changes to consumers. 
**Test URLs:**
- After: https://libs-hotfix--milo--adobecom.hlx.page/
> Hotfix to revert list.js

- libs/blocks/faas/utils.js
- libs/utils/utils.js
- test/libs/blocks/faas/utils.test.js
This patch is just for development and QA.
* Added a functionality that can listen parameter of `env` to switch different environment of FaaS form.
**Test URLs:**
Before: https://main--milo--adobecom.hlx.page/tools/faas?env=dev
After: https://faas-env--milo--adobecom.hlx.page/tools/faas?env=dev
QA note:
You will get CORS error with `faas-env` branch URL, and that is expected result. It means that actually trying to hit faas API from dev environment. (while main branch will pull from `qa` which is the default setting now)
You can also double check this from browser inspect -> network tab and lookup `jquery.faas-current.js` file to make sure it is getting from https://`dev`.apps.enterprise.adobe.com/faas/service/jquery.faas-current.js.
If you're having trouble with loading API with `qa` …
> Environment switch on FaaS form page for testing.

- libs/utils/lana.js
When lana.js is loaded via a script tag vars declared at the root were polluting the global space.  This wraps the code in an IIFE to not do that.
Also switched an arrow func to use "function" as the script may need to run on IE11
Resolves: [MWPW-112289](https://jira.corp.adobe.com/browse/MWPW-112289)
**Test URLs:**
- After: https://lana112289--milo--adobecom.hlx.page/
> MWPW-112289 Wrap lana in IIFE

- libs/utils/lana.js
* Dxdc team has hardcoded lana to send errors 100% of the time
* It will take some time for them to get a fix in, so for now any dxdc lana logs are hardcoded to 1% sample rate.
https://jira.corp.adobe.com/browse/MWPW-112699
When DXDC has fixed the issue, https://jira.corp.adobe.com/browse/MWPW-112700 will track the reverting of this PR
> MWPW-112699 Hardcode lana to 1% for dxdc client

- libs/utils/lana.js
Lana needs to be IE11 compatible (unlike the rest of milo)
Resolves: [MWPW-112820](https://jira.corp.adobe.com/browse/MWPW-112820)
**Test URLs:**
- After: https://lanaIeFix--milo--adobecom.hlx.page/
> MWPW-112820 Don't use arrow func for IE11 compatibility

- libs/blocks/chart/chart.css
- libs/blocks/chart/chart.js
* Move color, size, and container styles from section metadata to chart
* Auto-assign size based on number of children in order to reduce authoring
* Rename chart container to border to reduce confusion with section container
Resolves: [MWPW-113827](https://jira.corp.adobe.com/browse/MWPW-113827)
**Test URLs:**
- Before: https://main--milo--adobecom.hlx.page/drafts/methomas/data-viz
- After: https://move-chart-styles--milo--adobecom.hlx.page/drafts/methomas/data-viz
> Move section metadata to chart, auto assign size, rename chart container to border MWPW-113827

- libs/blocks/chart/chart.js
- libs/blocks/chart/chartLightTheme.js
- test/blocks/chart/chart.test.js
* Move label options for mark line and mark area out of theme
* Fix mark area label being cut off
Resolves: [MWPW-113006](https://jira.corp.adobe.com/browse/MWPW-113006)
**Test URLs:**
- After: https://line-chart-mark--milo--adobecom.hlx.page/drafts/methomas/data-viz
> Move mark label options out of theme MWPW-113006

- libs/blocks/chart/chart.js
* Reverting from using `hasOwn` to `hasOwnProperty`
* `hasOwn` is not supported on safari versions below 15.4 (see browser compatibility for [hasOwn](https://caniuse.com/mdn-javascript_builtins_object_hasown) and [hasOwnProperty](https://caniuse.com/?search=hasOwnProperty))
* Since `colorPalette` is a pre-defined object and not created using `Object.create(null)`, which is the reason why using `hasOwn` is preferred, it is OK to stick with `hasOwnProperty` in this case  (see [MDN section](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/hasOwnProperty#:~:text=Using%20hasOwnProperty%20as%20a%20property%20name) for more details)
Resolves: [MWPW-114061](https://jira.corp.adobe.com/browse/MWPW-114061)
**Test URLs:**
- Before: …
> MWPW-114061 Fixing charts not displaying on older safari versions

- libs/blocks/chart/chart.js
* Reduce premature chart render by asynchronously loading the chart data to completing block initializing without waiting.
* Run `updateContainerSize` without waiting for the chart data JSON to download.
* Reduce load time by loading chart data and chart library at the same time.
Resolves: [MWPW-113747](https://jira.corp.adobe.com/browse/MWPW-113747)
**Test URLs:**
- Before: https://data-viz--milo--adobecom.hlx.page/drafts/bmarshal/many-charts
- After: https://async-chart-data--milo--adobecom.hlx.page/drafts/bmarshal/many-charts
> MWPW-113747 load chart data without blocking

- libs/blocks/caas/utils.js
* `.at()` is only supported in Safari starting with version 15.4 (released March 15, 2022)
**Test URLs:**
- After: https://caasSafariFix--milo--adobecom.hlx.page/
> Don't use .at() as it is relatively new

- libs/blocks/caas/utils.js
* The caas library loaded defaults to `latest`.  If the user wants a different version, they can pass the `?caasver=0.102` param to specify the version to load.
* Note that there is no error checking done on the version, the exact string will be used in the caas urls.
Resolves: [MWPW-113070](https://jira.corp.adobe.com/browse/MWPW-113070)
**Test URLs:**
- After: https://caasVersion_MWPW-113070--milo--adobecom.hlx.page/
> MWPW-113070 Add ability to specify caas version via `caasver` query param

- libs/blocks/chart/chart.js
* Updating default inactive color for the legend categories to the spectrum gray (#6C6C6C) color to meet color contrast requirements
Resolves: [MWPW-113969](https://jira.corp.adobe.com/browse/MWPW-113969)
**Test URLs:**
- Before: https://data-viz--milo--adobecom.hlx.page/drafts/saravana/data-viz
- After: https://legend-deselected-color--milo--adobecom.hlx.page/drafts/saravana/data-viz
> MWPW-113969 Updating legend inactive color per a11y standards

- libs/utils/lana.js
- libs/utils/lana.md
- test/libs/utils/lana.test.js
* Reverts a fix for dxdc where the sample rate was fixed at 1% (Dxdc has fixed their end)
* Any traffic that is not from prod (dev/stage/author) gets funneled to lana stage so that lana prod only displays customer facing issues.
* ClientID is a required option parameter
Resolves:
[MWPW-114528](https://jira.corp.adobe.com/browse/MWPW-114528)
[MWPW-112700](https://jira.corp.adobe.com/browse/MWPW-112700)
[MWPW-112723](https://jira.corp.adobe.com/browse/MWPW-112723)
**Test URLs:**
- After: https://lanaStage_MWPW-114528--milo--adobecom.hlx.page/
> MWPW-114528 MWPW-112700 All dev/stage/author traffic goes to stage lana; revert dxdc fix

- libs/blocks/gnav/gnav.css
- libs/blocks/gnav/gnav.js
Allows for authoring an svg in the gnav brand section.
**Test URLs:**
- Before: https://main--stock--adobecom.hlx.page/pages/artisthub/drafts/?milolibs=customer-stories
- After:
> fix(gnav): allow for authoring SVGs in the gnav brand section

- libs/blocks/chart/chart.js
- test/blocks/chart/chart.test.js
* Update chart color palette to the Spectrum data visualization categorical [12-color palette](https://spectrum.corp.adobe.com/page/color-for-data-visualization/)
Resolves: [MWPW-113921](https://jira.corp.adobe.com/browse/MWPW-113921)
**Test URLs:**
- After: https://chart-colors--milo--adobecom.hlx.page/drafts/data-viz/holiday-report-dev
> Update chart color palette MWPW-113921

- libs/blocks/chart/chart.css
- libs/blocks/chart/list.js
- test/blocks/chart/list.test.js
* Add carousel to list chart if more than one list.
* Fix lists not rendering if named sheet is missing.
Resolves: [MWPW-114550](https://jira.corp.adobe.com/browse/MWPW-114550)
**Test URLs:**
- Before: https://data-viz--milo--adobecom.hlx.page/drafts/bmarshal/list-chart
- After: https://list-carousel--milo--adobecom.hlx.page/drafts/bmarshal/list-chart
> Add list chart carousel MWPW-114550

- libs/utils/utils.js
- test/blocks/faas/faas-modal.test.js
- test/blocks/faas/faas.test.js
- test/blocks/faas/utils.test.js
- test/blocks/fragment/fragment.test.js
- test/blocks/gnav/gnav.test.js
- test/utils/fonts.test.js
- test/utils/utils.test.js
* Change codeRoot from requiring consumers to use window.location.origin
**Test URLs:**
- Before: https://main--milo--adobecom.hlx.page/drafts/cmillar/marquee
- After: https://simple-code-root--milo--adobecom.hlx.page/drafts/cmillar/marquee
> Simplify codeRoot

- libs/blocks/section-metadata/section-metadata.css
* Change "heading center" section metadata style to "center"
* And include p tags to center
Resolves: [MWPW-115557](https://jira.corp.adobe.com/browse/MWPW-115557)
**Test URLs:**
- Before: https://main--milo--adobecom.hlx.page/drafts/methomas/text-center
- After: https://text-center--milo--adobecom.hlx.page/drafts/methomas/text-center
> Add text center style MWPW-115557

- libs/blocks/chart/chart.js
- test/blocks/chart/chart.test.js
* Because of the hardcoding of libs, charts currently do not work on consumers.
Resolves: https://github.com/adobecom/milo/pull/141#issuecomment-1228935411
**Test URLs:**
- After: https://chart-libs-base-path--milo--adobecom.hlx.page/drafts/data-viz/holiday-report-dev
> Updating chart libs base path for consumers

- libs/blocks/section-metadata/section-metadata.js
* Fix safari bug where charts wouldn't display as 2-up or 3-up
Resolves: [MWPW-116005](https://jira.corp.adobe.com/browse/MWPW-116005)
**Test URLs:**
- Before: https://data-viz--milo--adobecom.hlx.page/drafts/data-viz/chartsqa
- After: https://chart-bug-safari--milo--adobecom.hlx.page/drafts/data-viz/chartsqa
> Fix chart 2up/3up safari bug MWPW-116005

- libs/blocks/chart/list.css
* Temporary fix for numbers in ordered list in list chart being cut off on safari
Resolves: [MWPW-115996](https://jira.corp.adobe.com/browse/MWPW-115996)
**Test URLs:**
- Before: https://data-viz--milo--adobecom.hlx.page/drafts/data-viz/list-qa
- After: https://list-safari--milo--adobecom.hlx.page/drafts/data-viz/list-qa
> Fix cut off numbers on list MWPW-115996

- tools/send-to-caas/send-to-caas.css
- tools/send-to-caas/send-to-caas.js
- tools/send-to-caas/sidekick.js
- tools/sidekick/config.js
* Adds ability to specify if page should only be registered as draft in CaaS
* Refactor sidekick code so that it can be consumed in other projects
**Test URLs:**
- After: https://draftSidekick--milo--adobecom.hlx.page/
> Add draft support; Update sidekick for bacom consumption

- libs/utils/lana.js
* Using a default function param is not supported in IE11
Resolves: [MWPW-116262](https://jira.corp.adobe.com/browse/MWPW-116262)
**Test URLs:**
- After: https://lanaIeSucks--milo--adobecom.hlx.page/
> MWPW-116262 IE11 doesn't support default param vals

- libs/utils/utils.js
- Added privacy.standalone.js (OneTrust)
- Supports privacy modal open without being taken to new page.
Resolves: [MWPW-115566](https://jira.corp.adobe.com/browse/MWPW-115566)
**Test URL:**
https://main--bacom--adobecom.hlx.page/customer-success-stories/?milolibs=privacy-load
**Note:** Testing requires being logged into VPN.
> MWPW-115566 - OneTrust

- tools/send-to-caas/send-to-caas.js
Support for new metadata keys, `cardimagepath` and `badgeimage` .
* Add your
* Specicic
Resolves: [MWPW-116415](MWPW-URL)
**Test URLs:**
- After: https://badgeCardMd--milo--adobecom.hlx.page/?martech=off
Note that this can't be tested without using a url redirector as send-to-caas files are loaded directly from milo.adobe.com.
> MWPW-116415 Use import metadata if avail

- libs/blocks/caas/utils.js
CaaS does not support latest Alloy, so until it's fixed on their end this spoofs the object expected by CaaS
Resolves: [MWPW-116732](https://jira.corp.adobe.com/browse/MWPW-116732)
**Test URLs:**
- Before: https://main--milo--adobecom.hlx.page/drafts/cpeyer/caas-target
- After: https://caas-target--milo--adobecom.hlx.page/drafts/cpeyer/caas-target
> MWPW-116732 Spoof VisitorAPI for CaaS

- libs/blocks/chart/list.css
- libs/blocks/chart/list.js
* Update aria-live region so it only announces the slide title 
* Move aria-live region to the bottom so that speedy screen reader users don't get to it
* Clear aria-live region text after 5 seconds so it is not read after the chart content
Resolves: [MWPW-116066](https://jira.corp.adobe.com/browse/MWPW-116066)
**Test URLs:**
- Before: https://main--milo--adobecom.hlx.page/drafts/bmarshal/list-qa?martech=off
- After: https://list-aria-live--milo--adobecom.hlx.page/drafts/bmarshal/list-qa?martech=off
> MWPW-116066 Fixing list chart voiceover items

- libs/blocks/footer/footer.css
- libs/blocks/modal/modal.css
* Adds base styling for region modal
* Moved region selector styles from footer.css to modal.css to keep region modal styles all in one place.
* Updated breakpoints so content doesn't feel so cramped.
Resolves: [DOTCOM-72238](https://jira.corp.adobe.com/browse/DOTCOM-72238), [DOTCOM-71906](https://jira.corp.adobe.com/browse/DOTCOM-71906)
**Test URLs:**
- Before: https://main--milo--adobecom.hlx.page/?martech=off#langnav
- After: https://region-modal-styling--milo--adobecom.hlx.page/?martech=off#langnav
> Region Modal Styling

- libs/blocks/marquee/marquee.js
* Fixes bug in marquee where video doesn't play on iOS
Resolves: [MWPW-117337](https://jira.corp.adobe.com/browse/MWPW-117337)
**Test URLs:**
- Before: https://main--milo--adobecom.hlx.page/drafts/methomas/marquee?martech=off
- After: https://ios-video-bug--milo--adobecom.hlx.page/drafts/methomas/marquee?martech=off
> Fix iOS bug for animated marquee MWPW-117337

- libs/blocks/marquee/marquee.css
- libs/blocks/marquee/marquee.js
- libs/blocks/media/media.js
- libs/utils/analytics.js
- libs/utils/analytics.md
- libs/utils/decorate.js
* Added analytics utility script to include tracking attributes to a given block
* Imported `decorateBlockAnalytics` into the media.js and `decorateLinkAnalytics` into the shared decorateText() utility 
Resolves: Hidden - no jira ticket
**Test URLs:**
- Before: https://main--milo--adobecom.hlx.page/docs/library/blocks/media
- After: https://analytics--milo--adobecom.hlx.page/docs/library/blocks/media
**Testing notes**
- Inspect the DOM to ensure the following data attributes are included. (daa-im, daa-lh, daa-ll) see utils/analytics.md for more details. 
- FYI these are opt in. Needed blocks will require an include update to add these in their constructor.
> Include analytics utility

- libs/blocks/section-metadata/section-metadata.css
- libs/styles/styles.css
Related Issue: [MWPW-116998](https://jira.corp.adobe.com/browse/MWPW-116998)
**Test URLs:**
- Before: https://main--business-website--adobe.hlx.page/jp/blog/basics/account-based-marketing
- After: https://main--business-website--adobe.hlx.page/jp/blog/basics/account-based-marketing?milolibs=section-metadata-hide
> Set display none at section-metadata.css so consumer sites can have it.

- libs/utils/utils.js
- test/blocks/section-metadata/mocks/body.html
- test/blocks/section-metadata/section-meta.test.js
- test/utils/mocks/body.html
- test/utils/utils.test.js
* Unwrap a fragment if it is the only child of a paragraph tag.
* Gracefully handles scenarios where fragments are placed in lists or have sibling content.
Previous selector hierarchy:
```
.section > .content > p > .fragment
```
After this change:
```
.section > div > .fragment
```
Resolves: [MWPW-116861](https://jira.corp.adobe.com/browse/MWPW-116861)
**Milo Test URLs:**
- Before: https://main--milo--adobecom.hlx.page/drafts/rclayton/fragment-test?martech=off
- After: https://fragment-unwrap-update--milo--adobecom.hlx.page/drafts/rclayton/fragment-test?martech=off
- Before: https://main--bacom--adobecom.hlx.page/customer-success-stories/princess-cruises-case-study?martech=off
- After: https://main--bacom--adobecom.hlx.page/customer-success-stories/princess-cruises-cas …
> MWPW-116861 - Fragment Unwrap

- libs/blocks/manual-card/manual-card.js
- test/blocks/manual-card/manual-card.test.js
- test/blocks/manual-card/mocks/double-width.html
- test/blocks/manual-card/mocks/half-height.html
* Fix bug where "undefined" shows up when there's no description
* Also added similar catches for image, title, and links
Resolves: [MWPW-117924](https://jira.corp.adobe.com/browse/MWPW-117924)
**Test URLs:**
- Before: https://main--milo--adobecom.hlx.page/drafts/denli/manualconsonantcards?martech=off
- After: https://manual-card-undefined--milo--adobecom.hlx.page/drafts/denli/manualconsonantcards?martech=off
> Remove undefined on Manual Card if no description MWPW-117924

- libs/blocks/manual-card/manual-card.css
* Fix Manual Card title characters cut off on bottom
Resolves: [MWPW-118021](https://jira.corp.adobe.com/browse/MWPW-118021)
**Test URLs:**
- Before: https://main--milo--adobecom.hlx.page/drafts/denli/manualconsonantcards?martech=off
- After: https://title-cut-off--milo--adobecom.hlx.page/drafts/denli/manualconsonantcards?martech=off
> Fix Manual Card title characters cut off on bottom MWPW-118021

- libs/blocks/caas/caas.css
Fixes a UI styling issue in Milo/Bacom where CaaS topFilters blue border, of the active filter, is getting cut off.
This should ultimately be fixed by the Chimera team.
https://github.com/adobecom/milo/blob/main/libs/blocks/caas/utils.js#L21
This problem is also present in AEM/Dexter:
https://www-author.corp.adobe.com/content/floodgate-pink-www/us/en/max/2022/shop/marketplace.html?wcmmode=disabled
Resolves: [MWPW-116265](https://jira.corp.adobe.com/browse/MWPW-116265)
**Test URLs:**
- Before: https://main--bacom--adobecom.hlx.page/customer-success-stories/?martech=off
- After: https://main--bacom--adobecom.hlx.page/customer-success-stories?milolibs=caas-filter-ui&martech=off
> Fix for CaaS Top Filters UI

- libs/blocks/youtube/youtube.js
- test/blocks/youtube/youtube.test.js
* Add Youtube to an InOb because loading=lazy is not reliable.
* Better title support
* Slightly streamlined API
Resolves: [MWPW-118492](https://jira.corp.adobe.com/browse/MWPW-118492)
**Test URLs:**
- Before: https://main--milo--adobecom.hlx.page/drafts/cmillar/section-container-yt?martech=off
- After: https://youtube-perf--milo--adobecom.hlx.page/drafts/cmillar/section-container-yt?martech=off
> MWPW-118492 - Fix youtube performance

- libs/blocks/section-metadata/section-metadata.js
Prevent section metadata from loading styles that don't exist.
> Fix bad styles

- libs/blocks/caas-config/caas-config.js
- libs/blocks/caas/utils.js
- test/blocks/caas-config/caas-config.test.html
- test/blocks/caas-config/expectedConfigs/defaultConfig.js
- test/blocks/caas/utils.test.js
* Do not set default size to 2000
* use Total Cards To Show as the size
* Adds a field "Collection Size" to the Advanced panel which enables user to override
**Test URLs:**
- After: https://caassize--milo--adobecom.hlx.page/?martech=off
> CaaS Performance Improvement

- libs/blocks/table-of-contents/table-of-contents.js
* Safari 15.3 and below and Firefox 103 does not support the :has selector
Resolves: [MWPW-118743](https://jira.corp.adobe.com/browse/MWPW-118743)
**Test URLs:**
- Before: https://main--milo--adobecom.hlx.page/drafts/denli/table-of-contentsmartech=off
- After: https://toc-has-fix--milo--adobecom.hlx.page/drafts/denli/table-of-contents?martech=off
> MWPW-118743 table of contents error on older Safari and Firefox

- libs/blocks/caas/caas.js
* Adds the ability for a CaaS collection to be loaded without using an IntersectionObserver
* To enable, the CaaS link "Content as a Service" text needs to be modified to include "no-lazy"
* e.g: "Content as a Service no-lazy"
**Test URLs:**
- Before: https://main--milo--adobecom.hlx.page/drafts/cpeyer/caas-target?martech=off
- After: https://caas_nolazy--milo--adobecom.hlx.page/drafts/cpeyer/caas-target?martech=off
> Add no-lazy option to CaaS

- .github/workflows/run-janus.yml
- .github/workflows/run-tests.yaml
* Run Janus when a pull request is submitted
* Runs Janus against the pull request branch name (?milolibs=the-branch)
* Only runs when the run-janus label is attached
Resolves: [MWPW-109693](https://jira.corp.adobe.com/browse/MWPW-109693)
- https://integrate-janus--milo--adobecom.hlx.page/
> Integrate Janus

- libs/blocks/aside/aside.js
* Fixes Aside loading error when no description body is provided
**Test URLs:**
- Before: https://main--bacom--adobecom.hlx.page/customer-success-stories/adobe-inside-adobe-case-study
- After: https://main--bacom--adobecom.hlx.page/customer-success-stories/adobe-inside-adobe-case-study?milolibs=methomas-aside-load-error
Milo:
- https://methomas-aside-load-error--milo--adobecom.hlx.page/drafts/methomas/aside?martech=off
> Aside hotfix - failure with no body

- libs/blocks/tabs/tabs.css
- libs/blocks/tabs/tabs.js
While updating a customer story document, We noticed the images in normal content was using our `not block` styles because the tab panel had no class. This caused the images to scale 100% width. 
* Updated our tab panels to have a class assigned. 
* Added box-sizing property to tab list to prevent app.min styles layout shift. 
**Test URLs:**
- [Before](https://main--bacom--adobecom.hlx.page/drafts/parrish/tabs)
- [After](https://main--bacom--adobecom.hlx.page/drafts/parrish/tabs?milolibs=tabs-fix)
> Tabs hot fix: `not block` styles are applied to tab content incorrectly

- libs/blocks/list.js
Changes made:
- I removed 'section-metadata' as a supported block.
> Remove section-metadata as a supported block

- libs/blocks/tabs/tabs.js
- This change allows for the tab names to contain multiple spaces without breaking.
I don't have access to the Milo project, so I'm not sure how to create a test URL for these PR's, but the fix is quite straightforward so it might not be necessary anyways.
> fix(tabs): Allow for tab names to have multiple spaces

- libs/utils/utils.js
- Adds writing direction ( `rtl` , `ltr` ) to `config.direction` , based on active language.
- Sets the writing direction in the `dir` attribute in `html`  element.
Resolves: [MWPW-118172](https://jira.corp.adobe.com/browse/MWPW-118172)
**Test URLs:**
- After: https://MWPW-118172--milo--adobecom.hlx.page/?martech=off
> MWPW-118172 RTL support

- libs/blocks/share/share.js
I noticed an error that would come up if the icon doesn't exist:
This PR should prevent it from happening
> fix potential JS error (reading 'firstChild' of null)

- libs/utils/utils.js
Sometimes we don't want pages to ever run martech (mostly /tools pages)
**Test URLs:**
- After: https://c3-martechmd--milo--adobecom.hlx.page/?martech=off
> Add ability to turn off martech via metadata

- libs/blocks/library-config/library-config.js
Consumers can add additional block library locations using the query param `blocks`
Either:
* A fully qualified URL - e.g: https://main--bacom--adobecom.hlx.page/docs/library/blocks.json
* The `ref--repo--owner` string which will default to the above json location
**Test URLs:**
- After: https://c3-lib-additional-block-support--milo--adobecom.hlx.page/?martech=off
> Add ability to pass in additional block library locations

- libs/blocks/gnav/gnav.js
- libs/scripts/scripts.js
- libs/utils/utils.js
- test/utils/utils.test.js
- tools/loc/config.js
- tools/loc/sharepoint.js
- tools/loc/utils.js
- tools/sidekick/config.json
- Update config to config.json instead of config-v3.json
- Fix Rollout Timestamp issue which can lead to accidental merging of word docs
- Update gnav to use locale.contentRoot instead of locale.prefix
- Add support for langstore in locales and locale prefix
- Add tests and increase coverage for getLocale method.
Resolves: MWPW-97626
**Test URLs:**
- Before: https://main--milo--adobecom.hlx.page/langstore/en-gb/drafts/bhagwath/gnav-testing/gnav-embed?martech=off
- After:  https://loc--milo--adobecom.hlx.page/langstore/en-gb/drafts/bhagwath/gnav-testing/gnav-embed?martech=off
> Localization MVP - Rollout Fixes, GNAV Support

- libs/blocks/gnav/gnav.css
Small visual fix for the gnav search in an empty state - Resolves: [120914](https://jira.corp.adobe.com/browse/MWPW-120914)
**Before**
**After**
**Test URLs:**
- Before: https://main--milo--adobecom.hlx.page/drafts/osahin/document?martech=off
- After: https://gnav-remove-white-bar--milo--adobecom.hlx.page/drafts/osahin/document?martech=off
- Before: https://main--bacom--adobecom.hlx.page/customer-success-stories?martech=off
- After: https://main--bacom--adobecom.hlx.page/customer-success-stories?milolibs=gnav-remove-white-bar&martech=off
> Remove unnecessary white bar for the GNAV

- libs/blocks/article-feed/article-feed.js
- libs/blocks/article-feed/article-helpers.js
- libs/scripts/taxonomy.js
* Fixed language specific paths for taxonomy and article-feed
* `query-index.json` path was pointing to the root english folder on other languages
* Taxonomy topics sub-pages was pointing to the root english page on other languages
Resolves: [Article Feed Block](https://github.com/orgs/adobecom/projects/1/views/1)
**Test URLs:**
- Before: https://main--blog--adobecom.hlx.page/de/drafts/article-feed?martech=off
- After: https://main--blog--adobecom.hlx.page/de/drafts/article-feed?martech=off&milolibs=article-feed-locale
> Fixed language specific paths for taxonomy and article-feed

- libs/blocks/caas-config/caas-config.js
- libs/blocks/faas-config/faas-config.js
- libs/blocks/footer/footer.js
- libs/blocks/fragment/fragment.js
- libs/blocks/gnav/gnav.js
- libs/martech/attributes.js
- libs/utils/utils.js
- test/blocks/caas-config/caas-config.test.html
- test/blocks/caas/mocks/utils.js
- test/utils/getUuid.test.js
- test/utils/utils.test.js
Move funcs used in only one place out of utils
Trying to keep utils as small as possible.
**Test URLs:**
- After: https://c3-utilcleanup--milo--adobecom.hlx.page/?martech=off
> Cleanup of utils.js

- libs/blocks/pdf-viewer/pdf-viewer.js
- libs/scripts/scripts.js
- libs/utils/utils.js
- test/blocks/pdf-viewer/pdf-viewer.test.js
* Move PDF Viewer client ids into env-specific config
* Add support for hlx.live domain, which cannot share client id with hlx.page
Resolves: [MWPW-120503](https://jira.corp.adobe.com/browse/MWPW-120503)
**Test URLs:**
- Before: https://main--milo--adobecom.hlx.page/drafts/methomas/pdf-viewsdk?martech=off
- After: https://methomas-move-pdf-config--milo--adobecom.hlx.page/drafts/methomas/pdf-viewsdk?martech=off
Note: With the feature branch url, the PDF will show an error "Preview not available: This application domain is not authorized..." because the Viewer's client id is specifically for "main--milo--adobecom.hlx.page". We'll verify once it's merge into main. Any other errors should be flagged though.
> MWPW-120503 - Move PDF Viewer Config

- libs/blocks/faas/utils.js
Resolves: [MWPW-121015](https://jira.corp.adobe.com/browse/MWPW-121015)
**Test URLs:**
- Before: https://main--milo--adobecom.hlx.page/tools/faas?env=qa
- After: https://faas-fix--milo--adobecom.hlx.page/tools/faas?env=qa
QA note: Open the inspect and search for `faas-form-setting` then check if this empty space is removed for internal campaign id.
> Removing whitespace for internal campaign id.

- libs/blocks/marketo/marketo.js
- test/blocks/marketo/marketo.test.js
* Fixes Marketo forms field with errors not getting scrolled into view on iOS devices.
* Places field in middle of screen to account for Android shift when opening keyboard.
Resolves: [MWPW-121127](https://jira.corp.adobe.com/browse/MWPW-121127)
**Test URLs:**
- Before: https://main--milo--adobecom.hlx.page/drafts/bmarshal/marketo-example?martech=off
- After: https://bmarshal-marketo-scroll--milo--adobecom.hlx.page/drafts/bmarshal/marketo-example?martech=off
> Fix Marketo form scroll on iOS

- libs/blocks/gnav/gnav.css
This fixes a width inconsistency issue for the search results dropdown between `1200px` and `1400px`.
**Before**
**After**
[MWPW-121449](https://jira.corp.adobe.com/browse/MWPW-121449)
- Before: https://main--milo--adobecom.hlx.page/drafts/ramuntea/hello-milo?martech=off
- After: https://consistent-search-dropdown-width--milo--overmyheadandbody.hlx.page/drafts/ramuntea/hello-milo?martech=off
> [MWPW-121449] Search dropdown width between 1200-1400px

- libs/blocks/tabs/tabs.css
- libs/blocks/tabs/tabs.js
Addressed a few bugs that were reported w/ the `tabs` block. 
* Section metadata keyword reference is case sensitive
* Section metadata tab row only works when it's in the first table row
* Section metadata background has a z-index issue when used inside tab content
Resolves: [MWPW-121295](https://jira.corp.adobe.com/browse/MWPW-121295)
**Test URLs:**
- [Before](https://main--milo--adobecom.hlx.page/drafts/rparrish/tabs-content-model?martech=off)
- [After](https://rparrish-tabs-bug--milo--adobecom.hlx.page/drafts/rparrish/tabs-content-model?martech=off)
> MWPW-121295 - Tabs block authoring bugs

- libs/blocks/gnav/gnav-search.js
- libs/blocks/gnav/gnav.css
- libs/blocks/gnav/gnav.js
This PR ensures proper alignment between the search input and the results dropdown. Both from a positioning perspective and a border continuity one - if the input is not populated, all of its corners will be rounded. If it is populated, then the results dropdown will be shown and thus the input's bottom corners will not be rounded anymore, to ensure continuity. Additionally, the bottom borders of the search results dropdown element have been updated to match those of the input.
| Before  | After |
| ![Before-search-alignment-updates](https://user-images.githubusercontent.com/11267498/202473252-28fab301-6292-4e92-a822-21ac9e9f77dd.gif)  | ![After-search-alignment-updates](https://user-images.githubusercontent.com/11267498/202471851-3d4ec539-ad7a-4b5c-8a37-5 …
> [MWPW-121159] Gnav Search dropdown positioning

- libs/utils/lana.js
- test/utils/lana.test.js
If a promised has been rejected without a reason, the lana code will currently throw a JS error. IMO it still makes sense to log the error to get an indication of which pages have a lot of errors.
Resolves: [121954](https://jira.corp.adobe.com/browse/MWPW-121954)
**Test URLs:**
- After: https://MWPW-121954-lana-fix--milo--adobecom.hlx.page/?martech=off
> Fix lana bug found in MWPW-121954

- libs/blocks/faas/faas.css
Small style update.
This is how an AEM form looks like:
Ours:
Before: https://main--bacom--adobecom.hlx.page/fragments/resources/modal/forms/achieve-content-personalization-with-adobe-experience-manager-and-adobe-analytics
After: https://main--bacom--adobecom.hlx.page/fragments/resources/modal/forms/achieve-content-personalization-with-adobe-experience-manager-and-adobe-analytics?milolibs=faas-style
> This is to match with AEM FaaS style.

- libs/blocks/tabs/tabs.css
- libs/blocks/tabs/tabs.js
Fixed the following issues
1) The Milo `Tabs` block skips the first tab when using keyboard navigation to select tabs and view its related content.
2) When using special characters ex. `&` in a tab key, the associated tab content doesn't work. 
Resolves: [MWPW-122039](https://jira.corp.adobe.com/browse/MWPW-122039)
**Test URLs:**
- [Before](https://main--milo--adobecom.hlx.page/drafts/rparrish/tabs-content-model?martech=off)
- [After](https://rparrish-tabs-bug--milo--adobecom.hlx.page/drafts/rparrish/tabs-content-model?martech=off)
FYI, I also addressed a number of linting warnings in the tabs.js file
> MWPW-122039 Tabs bugs

- libs/utils/utils.js
* Fixes issue where pdfs weren't autoblocking due to relative links
* Update: PDF will embed inline if ".pdf" is included in the link text (previously link text was require to be same as link href). Otherwise, it will remain a link and open in a new tab.
Resolves: [MWPW-122629](https://jira.corp.adobe.com/browse/MWPW-122629)
**Test URLs:**
- Before: https://main--milo--adobecom.hlx.page/drafts/methomas/pdf-viewsdk1?martech=off
- After: https://methomas-pdf-relative-link--milo--adobecom.hlx.page/drafts/methomas/pdf-viewsdk1?martech=off
> MWPW-122629 - Fix PDF Relative Link

- libs/martech/martech.js
Required by CaaS implementation.
See https://git.corp.adobe.com/Dexter/dexter/pull/2641/files
**Test URLs:**
- Before: https://main--bacom--adobecom.hlx.page/customer-success-stories/helly-hansen-case-study
- After: https://main--bacom--adobecom.hlx.page/customer-success-stories/helly-hansen-case-study?milolibs=c3-windowedgeconfigid
> Set the edgeConfigId on window

- libs/blocks/chart/chart.js
- test/blocks/chart/chart.test.js
* Adds support for "date" as the "Unit" in the data file for a Chart
* Maintains support for "date-" for backwards compatibility
Resolves: [MWPW-119166](https://jira.corp.adobe.com/browse/MWPW-119166)
**Test URLs:**
- Before: https://main--milo--adobecom.hlx.page/drafts/methomas/chart-date-dash?martech=off
- After: https://methomas-chart-date-dash--milo--adobecom.hlx.page/drafts/methomas/chart-date-dash?martech=off
For regression testing:
https://main--bacom--adobecom.hlx.page/resources/holiday-shopping-report?milolibs=methomas-chart-date-dash&martech=off
https://methomas-chart-date-dash--milo--adobecom.hlx.page/docs/library/blocks/chart?martech=off
> MWPW-119166 - Fix chart date unit

- libs/blocks/pdf-viewer/pdf-viewer.js
* Fix PDF Viewer getting incorrect client id on consumer on `.hlx.live`
Resolves: [MWPW-122756](https://jira.corp.adobe.com/browse/MWPW-122756)
**Test URLs:**
- Before: https://main--milo--adobecom.hlx.page/drafts/methomas/pdf-viewsdk1-a?martech=off
- After: https://methomas-pdf-consumer-live--milo--adobecom.hlx.page/drafts/methomas/pdf-viewsdk1-a?martech=off ("After" is expected to have errors because it has the branch name in the url)
- Consumer: https://main--bacom--adobecom.hlx.live/ab-test/resources/guides/take-the-road-to-implementation/thank-you?martech=off&milolibs=methomas-pdf-consumer-live
> MWPW-122756 - Fix PDF Viewer on Consumer Live

- libs/scripts/scripts.js
- libs/utils/utils.js
Consumers can then import and call `loadLana` in their scripts.js file.
Resolves: [119602](https://jira.corp.adobe.com/browse/MWPW-119602)
**Test URLs:**
- After: https://c3-loadlanautils--milo--adobecom.hlx.page/?martech=off
> Move loadLana to utils

- libs/utils/lana.js
- test/scripts/scripts.test.js
- test/utils/lana.test.js
- test/utils/lanaDefaultOptions.test.js
Also remove deprecated functions, I verified that they are not used by any consuming clients.
Resolves: [MWPW-119602](https://jira.corp.adobe.com/browse/MWPW-119602)
**Test URLs:**
- After: https://c3-lanadefaultopt--milo--adobecom.hlx.page/?martech=off
> Lana options hardening

- libs/blocks/chart/chart.js
- libs/blocks/fragment/fragment.js
- libs/blocks/gnav/gnav-appLauncher.js
- libs/blocks/gnav/gnav.js
- libs/blocks/milonav/milonav.js
- libs/blocks/modal/modal.js
- libs/scripts/scripts.js
- libs/utils/utils.js
- test/blocks/chart/chart.test.js
- test/blocks/gnav/gnav.test.js
- test/blocks/modals/modals.test.js
- test/utils/utils.test.js
* makeRelative renamed to localizeLink
* removed PROJECT_NAME check since Franklin handles it by default
* production domains added to `script.js` so consumers can update their domains. 
*  removeHash method in `fragments.js` updated to not remove `#_dnt` if present.
* removed localizeLink from `gnav-appLauncher.js` and `chart.js` and updated tests accordingly
* Added tests for localizeLink 
* Fixed scripts.js for RTL lang codes
* Added tests for RTL support
Resolves: MWPW-120796
**Test URLs:**
- Before: https://main--milo--adobecom.hlx.page/fr/drafts/bhagwath/demo/demo?martech=off
- After: https://link-transform--milo--adobecom.hlx.page/fr/drafts/bhagwath/demo/demo?martech=off
> MWPW-120796: Link Transformation Support for Relative and Absolute Links

- libs/blocks/global-navigation/blocks/appLauncher/appLauncher.js
- libs/blocks/global-navigation/blocks/navMenu/menu.css
- libs/blocks/global-navigation/blocks/navMenu/menu.js
- libs/blocks/global-navigation/blocks/profile/profile.js
- libs/blocks/global-navigation/delayed-utilities.js
- libs/blocks/global-navigation/global-navigation.css
- libs/blocks/global-navigation/global-navigation.js
- libs/blocks/global-navigation/utilities.js
As preparation for the Eurovision team to take over the GNAV block, this PR contains some refactorings that we are exploring and would like to have in our feds-gnav branch.
- Add a loadDelayed section which delays loading navigation related code not needed for LCP
- Refactor menu's and put them in their own file
- Start refactoring the profile/applauncher and put them in their own files
- adopt the toTemplate`` helper from @overmyheadandbody and start introducing it within the `global-navigation.js`
- Start splitting CSS|JS for into smaller chunks
Resolves: [MWPW-122222](https://jira.corp.adobe.com/browse/MWPW-122222)
**Test URLs:**
- Before: https://main--milo--adobecom.hlx.page/drafts/osahin/document2?martech=off
- After: https://feds-gnav-menu-refactoring--milo--mokimo.hlx.page/drafts/o …
> [MWPW-122222] Feds gnav menu refactoring

- libs/blocks/pdf-viewer/pdf-viewer.css
* Issue rarely happens on local, disable caching and don't use network throttling to see height issue on main branch.
* PDF Viewer will error on non-main branch but height should be correct.
Resolves: [MWPW-122993](https://jira.corp.adobe.com/browse/MWPW-122993)
**Test URLs:**
- Before: https://main--milo--adobecom.hlx.page/drafts/bmarshal/pdf-viewer-demo?martech=off
- After: https://bmarshal-pdf-initial-load--milo--adobecom.hlx.page/drafts/bmarshal/pdf-viewer-demo?martech=off
> MWPW-122993 Increase pdf viewer specificity to avoid initial load issue

- libs/blocks/icon-block/icon-block.css
Removing a style that is causing the links in the icon block body to get the same style as the CTA action area links. Turns out that with the updated decorators the style in question was no longer needed, but got overlooked.
Resolves: [MWPW-123765](https://jira.corp.adobe.com/browse/MWPW-123765)
**Test URLs:**
- Before: https://main--milo--adobecom.hlx.page/docs/library/blocks/icon-block?martech=off
- After: https://MWPW-123765_linked_text_fix--milo--adobecom.hlx.page/docs/library/blocks/icon-block?martech=off
> MWPW-123765 - Fix link styles in icon block body

- libs/blocks/chart/chart.js
- test/blocks/chart/chart.test.js
* Fix the Chart block color palette to match Spectrum's order
Resolves: [MWPW-120782](https://jira.corp.adobe.com/browse/MWPW-120782)
**Test URLs:**
- Before: https://main--milo--adobecom.hlx.page/drafts/methomas/chart-spectrum-colors?martech=off
- After: https://methomas-chart-spectrum-colors--milo--adobecom.hlx.page/drafts/methomas/chart-spectrum-colors?martech=off
- After: https://main--bacom--adobecom.hlx.page/resources/holiday-shopping-report?milolibs=methomas-chart-spectrum-colors
> MWPW-120782 - Fix Chart Color Order

- libs/blocks/gnav/gnav.js
Adds the ability to remove the Adobe logo on the right. Currently if the `Adobe Logo` block is missing the rendering of the complete gnav fails.
Resolves: [MWPW-124631](https://jira.corp.adobe.com/browse/MWPW-124631)
**Test URLs:**
- Before: https://main--milo--adobecom.hlx.page/drafts/msagolj/testpage
- After:  https://mwpw-124631--milo--adobecom.hlx.page/drafts/msagolj/testpage
To Test:
- open Before link: Navigation fails to load, error in browser console
- open After link: Navigation renders without adobe logo on the right
> MWPW-124631 check if adobe logo block exists in document

- libs/blocks/review/components/review/Comments.js
- libs/blocks/review/review.css
Adds the character counter for the ratings comment textarea, same as in currently active version e.g.[ here](https://www.adobe.com/ch_de/acrobat/online/rearrange-pdf.html).
Resolves: [MWPW-124632](https://jira.corp.adobe.com/browse/MWPW-124632)
**Test URLs:**
Before: https://main--milo--adobecom.hlx.page/drafts/msagolj/testpage
After: https://mwpw-124632--milo--adobecom.hlx.page/drafts/msagolj/testpage
To Test:
- open page
- scroll down to review rating
- select from 1 to 3 stars (4-5 will submit rating directly)
- Comment box opens
=> Before Page: No counter in the bottom left corner
=> After Page: char counter in bottom left, max 500 chars.
> MWPW-124632 [Milo] No character count in the review component text box

- libs/blocks/gnav/gnav.js
* Allows option to pass site specific function to `adobeid.onReady`. The frictionless pages need this option to go live. These new functions will be added to the consumer's script config options.
Resolves: [MWPW-124584](https://jira.corp.adobe.com/browse/MWPW-124584)
**Test URLs:**
- After: https://MWPW-124584--milo--adobecom.hlx.page/?martech=off
> MWPW-124584

- libs/blocks/footer/footer.js
- libs/blocks/gnav/gnav.js
- libs/scripts/scripts.js
- libs/utils/utils.js
- test/blocks/gnav/gnav.test.js
- test/blocks/gnav/mocks/simple-gnav.plain.html
- test/utils/utils.test.js
- call decorateLinks for gnav in gnav init instead of individual blocks
- removed decorateSVG and localizeLink instances as it is called in decorateLinks
- added tests to verify link localization in gnav menu, breadcrumb, cta, brand link
- call decorateLinks for footer links in init method
- added try catch in utils for empty href or malformed href
- fix https://business.adobe.com/au getting converted to https://business.adobe.com/au/au
- add test for this fix
- Support http://www.adobe.com/ link localization and add test for the same
Resolves: MWPW-124277
**Test URLs:**
- Before: https://main--bacom--adobecom.hlx.page/kr/customer-success-stories?martech=off
- After: https://main--bacom--adobecom.hlx.page/kr/customer-success-stories?milolibs=link-transform&martech=off
> MWPW-124277 - Link Localization not working for some links in Gnav and Footer

- libs/blocks/gnav/gnav.js
- Retaining the per menu localize link to avoid regression issue noticed with few links not being localized.
Resolves: MWPW-124277
**Test URLs:**
- Before: https://main--bacom--adobecom.hlx.page/kr/customer-success-stories?martech=off
- After: https://main--bacom--adobecom.hlx.page/kr/customer-success-stories?milolibs=regressionFix&martech=off
> MWPW-124277 - Regression Fix Link Localization

- libs/blocks/card/card.js
- libs/blocks/fragment/fragment.js
- libs/blocks/modal-metadata/modal-metadata.css
- libs/blocks/modal-metadata/modal-metadata.js
- libs/blocks/modal/modal.js
- libs/blocks/section-metadata/README.md
- libs/blocks/section-metadata/section-metadata.js
- libs/scripts/scripts.js
- libs/utils/utils.js
- test/blocks/fragment/fragment.test.js
- test/blocks/modals/modals.test.js
- test/blocks/section-metadata/section-meta.test.js
* Ability to open a modal with a custom event
* Ability to customize the look and behavior of a modal
* Can add class names to modal via modal-metadata
* Can turn off curtain for modal via modal-metadata 
* Turned on GeoRouting for Milo
* Minor updates to tests
* Non-breaking updates to Section Metadata
Resolves: [MWPW-120020](https://jira.corp.adobe.com/browse/MWPW-120020)
**Test URLs:**
- After: https://event-modal--milo--adobecom.hlx.page/?martech=off
> MWPW-120020 - Event-driven Modals

- tools/loc/fragments.js
- Change starts with to includes similar to the fragment block.
Resolves: MWPW-124846
**Test URLs:**
N/A
> MWPW-124846 - Loc Support fragments at any level in hierarchy

- libs/blocks/gnav/gnav.js
When trying to add a link to a SVG Logo in Brand Block like this:
the rendering of the complete gnav block fails with:
```
gnav.js:635 Could not create global navigation: TypeError: Failed to execute 'insertAdjacentElement' on 'Element': parameter 2 is not of type 'Element'.
at Gnav.decorateBrand (gnav.js:148:15)
at Gnav.init (gnav.js:61:24)
at init (gnav.js:629:10)
at async utils.js:345:9
```
Resolves: [MWPW-125032](https://jira.corp.adobe.com/browse/MWPW-125032)
**Test URLs:**
- Before: https://main--milo--adobecom.hlx.page/drafts/msagolj/mwpw-125032?martech=off
- After: https://mwpw-125032--milo--adobecom.hlx.page/drafts/msagolj/mwpw-125032?martech=off
> MWPW-125032 Brand Block: using an SVG link for logo breaks gnav rendering

- test/utils/mocks/body.html
- test/utils/utils.test.js
* Added coverage for svg's
* Added coverage for #_blank
**Test URLs:**
- After: https://svg-tests--milo--adobecom.hlx.page/?martech=off
> Add utils test coverage

- libs/blocks/accordion/accordion.css
Small patch to remove unnecessary display:none from accordion css that was causing clash with other components. 
**Test URLs:**
Before: https://main--milo--adobecom.hlx.page/drafts/bradjohn/accordion-how-to?martech=off
After: https://accordion-patch--milo--adobecom.hlx.page/drafts/bradjohn/accordion-how-to?martech=off
Bacom
- Before: https://main--bacom--adobecom.hlx.page/layouts/products/product-benefit?milolibs=accordion-patch?martech=off
- After: https://main--bacom--adobecom.hlx.page/layouts/products/product-benefit?milolibs=accordion-patch?martech=off
> removing display none from accordion

- libs/blocks/gnav/gnav.js
- Call decorateLinks for gnav sign in
Resolves: MWPW-124277
**Test URLs:**
- https://main--bacom--adobecom.hlx.page/kr/customer-success-stories
- https://main--bacom--adobecom.hlx.page/kr/customer-success-stories?milolibs=link-transform
> MWPW-124277: Localize Gnav Sign In Link

- libs/blocks/global-navigation/blocks/profile/profile.css
- libs/blocks/global-navigation/blocks/search/gnav-search.css
- libs/blocks/global-navigation/blocks/search/gnav-search.js
- libs/blocks/global-navigation/delayed-utilities.js
- libs/blocks/global-navigation/global-navigation.css
- libs/blocks/global-navigation/global-navigation.js
- libs/features/placeholders.js
- libs/styles/styles.css
- libs/utils/utils.js
- test/features/placeholders/placeholders.json
- test/features/placeholders/placeholders.test.js
This PR includes:
* placeholder logic with fallback mechanism;
* use of placeholders in the Search block;
* refactor of the main global navigation styles - going away from grid and fixed positioning, since they weren't set up correctly, nor did they take all use-cases into consideration, such as elements that might be added before the navigation. The styles were also a risk for maintainability, since the same (or even slightly different) values were added in multiple places, with varying degrees of specificity;
* first steps for refactoring the brand block;
* first steps for breadcrumbs style refactoring.
Resolves: [MWPW-123840](https://jira.corp.adobe.com/browse/MWPW-123840) & [MWPW-125090](https://jira.corp.adobe.com/browse/MWPW-125090)
**Test URLs:**
- Before: …
> [MWPW-123840] Gnav centralised placeholders & main style refactor

- libs/blocks/modal/modal.js
* Adds a 'milo:modal:closed' event on modal close
* Adds a 'milo:modal:loaded' event on modal open/load
* Adds a check to see if the modal item to be removed during close modal is the modal itself - resolves a bug @Brandon32  found while reviewing
Resolves: [MWPW-125464](https://jira.corp.adobe.com/browse/MWPW-125464)
**Test URLs:**
- Before: https://main--milo--adobecom.hlx.page/drafts/slavin/complex-modal?martech=off
- After: https://add-modal-events--milo--adobecom.hlx.page/drafts/slavin/complex-modal?martech=off
**To Test**
You can add the following functions in the console and observe that the console logs out when the modal is opened and closed:
```
window.addEventListener('milo:modal:closed', () => {
console.log('closed');
})
window.addEventListener('milo:modal:loaded', () => { …
```
> MWPW-125464 - Adding events to the modal on close and load

- libs/blocks/gnav/gnav.js
- Set locale in adobeid.
Resolves: MWPW-126266
**Test URLs:**
- Before: https://main--bacom--adobecom.hlx.page/vn_vi/customer-success-stories/aaa-northeast-case-study?martech=off
- After: https://main--bacom--adobecom.hlx.page/vn_vi/customer-success-stories/aaa-northeast-case-study?milolibs=fixImsLogin&martech=off
> MWPW-126266 - IMS Login URL is not locale specific

- libs/blocks/card-horizontal/card-horizontal.css
Removes all unneeded flex-grow values on card image element so that rendering of images with different aspect-ratio/sizes are always at the proper widths.
Resolves: [MWPW-126174](https://jira.corp.adobe.com/browse/MWPW-126174)
**Test URLs:**
- Before: https://main--milo--adobecom.hlx.page/fragments/rclayton/cards?martech=off
- After: https://horizontal-card-image--milo--adobecom.hlx.page/fragments/rclayton/cards?martech=off
> MWPW-126174 - Horizontal card block image changes size based on title size

- libs/blocks/tabs/tabs.js
* Fixed an issue w/ the tabs block content associations - The label/section key associated text was removing all non alphanumeric special characters and breaking the selector when a Japanese or Korean tab label/key was used. 
Resolves: [MWPW-126351](https://jira.corp.adobe.com/browse/MWPW-126351)
**Test URLs:**
- Before:
https://main--milo--adobecom.hlx.page/drafts/rparrish/tabs-kanji
https://main--cc--adobecom.hlx.page/drafts/tkato/0209-1640-test-toshi-cc-overview
- After: 
https://rparrish-tabs-kanji--milo--adobecom.hlx.page/drafts/rparrish/tabs-kanji
https://main--cc--adobecom.hlx.page/drafts/tkato/0209-1640-test-toshi-cc-overview?milolibs=rparrish-tabs-kanji
> Tabs block bug - Fix JP and KN label associations. 

- libs/blocks/accordion/accordion.js
For the accordion the background gets darkened when and entry gets selected. This is done using `focusin`, `focusout` events. Safari Browsers dont trigger these events on click so background will not change. We need to keep these events for accessiblity reasons (to be able to tab through the entries). So i added background switching also to the click event itself.
Resolves: [MWPW-125401](https://jira.corp.adobe.com/browse/MWPW-125401)
**Test URLs:**
- Before: https://main--milo--adobecom.hlx.page/drafts/msagolj/mwpw-125401
- After: https://mwpw-125401--milo--adobecom.hlx.page/drafts/msagolj/mwpw-125401
NOTE : To test, open above links on Safari
> MWPW-125401 Add backround color switching to click event for Safari

- libs/blocks/modal/modal.js
MWPW-126597
* Loads modal CSS if it was not already loaded for custom modals. 
* To test on Milo, just try opening the preflight modal in the sidekick
* To test on Bacom, try getting the georouting Modal to open (Clear the site cache and fake change your country if necessary by setting this query param -> ?akamaiLocale=de)
Resolves: [MWPW-126597](https://jira.corp.adobe.com/browse/MWPW-126597)
**Test URLs:**
- Before: https://main--milo--adobecom.hlx.page/ch_de/?martech=off
- After: https://vhargrave-modal-css--milo--adobecom.hlx.page/ch_de/?martech=off
**Bacom**
- Before: https://main--bacom--adobecom.hlx.page/resources/videos/marketo-product-tour?akamaiLocale=DE
- After: https://main--bacom--adobecom.hlx.page/resources/videos/marketo-product-tour?akamaiLocale=DE&milolibs=vhargrave-modal- …
> MWPW-126597 load css for custom modals

- libs/utils/utils.js
- test/utils/mocks/svg.html
- test/utils/svg.test.js
* Fail faster when not an SVG
* Simpler pipe detection for alt text
* Use FQDN if not a .hlx. link
* Better support for relative links
Resolves: [MWPW-126739](https://jira.corp.adobe.com/browse/MWPW-126739)
**Test URLs:**
- After: https://main--milo--adobecom.hlx.live/?martech=off
> MWPW-126739 - SVG Updates

- libs/blocks/footer/footer.js
- test/blocks/footer/footer.test.js
- test/blocks/footer/mocks/copyright-p.html
- test/blocks/footer/mocks/copyright-ul.html
* Allow footer copyright to be authored as unordered list `ul`
* If authored as `ul`, non-link text will remain visible in copyright
* Maintain support for existing single line `p` authoring
Resolves: [MWPW-126724](https://jira.corp.adobe.com/browse/MWPW-126724)
**Test URLs:**
New Authoring `ul`:
- Before: https://main--milo--adobecom.hlx.page/drafts/methomas/test-footer-text?martech=off
- After: https://methomas-footer-text--milo--adobecom.hlx.page/drafts/methomas/test-footer-text?martech=off
Existing Authoring `p` (for regression):
- Before: https://main--milo--adobecom.hlx.page/drafts/methomas/checkmark?martech=off
- After: https://methomas-footer-text--milo--adobecom.hlx.page/drafts/methomas/checkmark?martech=off
> MWPW-126724 - Support non-link text in copyright

- libs/blocks/gnav/gnav.js
* Fixes gnav so that the cta remains in the order that it's authored
* For example, the telephone number can now be added to the right of the cta
Resolves: [MWPW-126915](https://jira.corp.adobe.com/browse/MWPW-126915)
**Test URLs:**
- Before: https://main--milo--adobecom.hlx.page/drafts/methomas/gnav-phone-right?martech=off
- After: https://methomas-gnav-phone--milo--adobecom.hlx.page/drafts/methomas/gnav-phone-right?martech=off
Regression (gnav with phone authored to the left of the cta still works):
- After: https://methomas-gnav-phone--milo--adobecom.hlx.page/drafts/methomas/checkmark?martech=off
> MWPW-126915 Fix gnav link order

- libs/blocks/global-navigation/blocks/navDropdown/dropdown.css
- libs/blocks/global-navigation/blocks/navDropdown/dropdown.js
- libs/blocks/global-navigation/blocks/profile/milo-wrapper.css
- libs/blocks/global-navigation/blocks/profile/signIn.css
- libs/blocks/global-navigation/blocks/profile/standalone-wrapper.css
- libs/blocks/global-navigation/blocks/search/gnav-search.css
- libs/blocks/global-navigation/blocks/search/gnav-search.js
- libs/blocks/global-navigation/global-navigation.css
- libs/blocks/global-navigation/global-navigation.js
- libs/blocks/global-navigation/utilities/utilities.js
- test/blocks/gnav/gnav.test.js
This is a refactor of the Gnav links decoration, popups/dropdowns (sync or async, normal or mega-menu style), headliness and CTAs. It also scopes the CSS custom properties used by FEDS to avoid collision with other parts of the application.
A few additional improvements worth mentioning:
* the logic will now follow the structure as authored in Word, it is no longer opinionated on item order;
* the headlines now act as accordion headers for subsections on mobile.
This PR also fixes two bugs related to Search:
* https://jira.corp.adobe.com/browse/MWPW-127264 (ensure correct curtain styles when Search is open)
* https://jira.corp.adobe.com/browse/MWPW-127263 (clear Search input and results when trigger is clicked)
Resolves: [MWPW-125175](https://jira.corp.adobe.com/browse/MWPW-125175)
**Test …
> [MWPW-125175] Nav Links refactor

- libs/blocks/global-navigation/utilities/getUserEntitlements.js
- libs/blocks/global-navigation/utilities/getUserEventHistory.js
Resolves: [MWPW-119230](https://jira.corp.adobe.com/browse/MWPW-119230)
I've done an exhaustive review of all the FEDS related utilities that we currently offer in the aem based global navigation.
As a lot of the backwards compatibility isn't needed anymore (example: IMS does not need a wrapper anymore to support V1 and V2 with the same API, but we can just rely on the fact IMS v2 is used) only two crucial utilities will be exported, and users are free to consume them.
They do not occupy any space in the global navigation/FEDS anymore but serve as convenient wrapping functions anyone is free to consume.
The scripts can either be consumed from a milo context or standalone when you import the absolute path equal to lana.
```js
import getUserEntitlements from …
```
> MWPW-119230: Feds Utilities

- libs/utils/utils.js
If there is an unhandled error it will trigger a lana.log message, which tries importing ./lana.js, that will throw an error, which is then caught by the error listener which tries to log a lana message. 
This happens on DC when using the `milolibs` param as the DC CSP (Content Security Policy) doesn't allow loading of files from milobranch--main--adobecom.hlx.page.
**Test URLs:**
> Lana: Remove event handlers before import

- libs/blocks/footer/footer.css
- libs/blocks/footer/footer.js
- test/blocks/footer/footer.test.js
- test/blocks/footer/mocks/copyright-p.html
- test/blocks/footer/mocks/copyright-ul.html
* Support a second line of copyright text, such as in the bacom korean footer
* Fix stylelint errors in footer.css
Resolves: [MWPW-127324](https://jira.corp.adobe.com/browse/MWPW-127324)
**Test URLs:**
- Before: https://main--milo--adobecom.hlx.page/drafts/methomas/footer-kr-page?martech=off
- After: https://methomas-kr-copyright--milo--adobecom.hlx.page/drafts/methomas/footer-kr-page?martech=off
> MWPW-127324 - Second line copyright

- libs/utils/utils.js
This is for fixing sidekick in localhost.
before: https://main--milo--adobecom.hlx.page/
after: https://sidekick-fix--milo--adobecom.hlx.page/
*Tested from localhost:3000 and worked for me.
> Fixing sidekick for localhost.

- libs/blocks/text/text.js
* Updated the text block javascript logic so the override decorator uses a lowercase typography class references. 
It was reported that the `text` block typography overrides were not working as expected. This is in association w/ the previously merged task to address style-lint warnings in our typography.css names.
[MWPW-126441] Unblock style-linting by lowercasing all t-shirt sizes in classnames | https://github.com/adobecom/milo/pull/503
**Test URLs:**
- Before: https://main--milo--adobecom.hlx.page/docs/library/kitchen-sink/text?martech=off
- After: https://rparrish-text-override--milo--adobecom.hlx.page/docs/library/kitchen-sink/text?martech=off
**Testing**
Review the before/after urls and scroll to the bottom of the page where the overrides section is.
Confirm the advertised …
> Text block override - lowercase typography class names

- libs/utils/utils.js
- test/utils/htmlpostfix.test.html
* Removes extra ".html" in url path for US link in region selector (e.g. `https://business.adobe.com/.html/customer-success-stories.html`)
* Fixes all links to US home with hash or query params on .html
Resolves: [MWPW-127043](https://jira.corp.adobe.com/browse/MWPW-127043)
**Test URLs:**
- Before: https://business.stage.adobe.com/customer-success-stories.html?martech=off
- After: https://business.stage.adobe.com/customer-success-stories.html?milolibs=methomas-change-region-html&martech=off
> MWPW-127043 Fix Region Selector US Link

- libs/blocks/global-navigation/blocks/navDropdown/dropdown.css
- libs/blocks/global-navigation/blocks/navDropdown/dropdown.js
- libs/blocks/global-navigation/blocks/profile/profile.css
- libs/blocks/global-navigation/blocks/search/gnav-search.css
- libs/blocks/global-navigation/blocks/search/gnav-search.js
- libs/blocks/global-navigation/global-navigation.css
- libs/blocks/global-navigation/global-navigation.js
- libs/blocks/global-navigation/utilities/utilities.js
This PR adds logic and styles for a few new features and updates:
- support for promos, including a dark theme;
- consistent styling for RTL locales;
- support for secondary CTAs;
- expand mega menu, search and breadcrumbs to the full width of the page when their dropdown is open;
- allow mixed content in non-mega menu dropdowns, we can now add link groups, CTAs and have multiple columns with headings;
- ensure dropdown menus are loaded ASAP after a menu item has been clicked;
- ensure correct focus order across devices for the main navigation, the Search section and the Breadcrumbs section.
Resolves: [MWPW-117906](https://jira.corp.adobe.com/browse/MWPW-117906)
**Test URLs:**
- Before: https://feds-gnav--milo--overmyheadandbody.hlx.page/drafts/ramuntea/gnav-refactor?martech=off
- After: …
> [MWPW-117906] Localnav and dropdown enhancements

- libs/blocks/marquee/marquee.css
Currently, split-variant marquees require some extra spacing token (e.g. in the form of section metadata) if it contains a media credit for the credit to be guaranteed visible on desktop. This shouldn't be how it works -- authors should be able to just drop this block in anywhere and not have to think about extra steps required to make it behave as expected.
This PR updates the spacing token for split marquees that have media credits, allowing it to be more modularized.
**Test URLs:**
- Before: https://main--milo--adobecom.hlx.page/docs/library/kitchen-sink/marquee-split?martech=off
- After: https://ebartholomew-fix-media-credits--milo--adobecom.hlx.page/docs/library/kitchen-sink/marquee-split?martech=off
> Make split marquees fully modularized

- libs/blocks/caas/utils.js
We have moved the location of where CaaS files are located on adobe.com's docroot. 
This PR is needed since this new location has all the latest CaaS code and Milo has been out of sync w/ new CaaS feature development for a couple of weeks at this point.
Resolves: MWPW-128300
**Test URLs:**
**Before:** 
https://main--milo--adobecom.hlx.page/tools/caas
**After:** 
For 0.6.2, CaaS released a breaking change, which can be reflected here (component doesn't load in milo):
- https://mwpw-128300--milo--adobecom.hlx.page/tools/caas?caasver=0.6.2
For 0.6.3, we fixed this breaking change and put that code in stable so milo will just skip caas release 0.6.2
- https://mwpw-128300--milo--adobecom.hlx.page/tools/caas?caasver=0.6.3
- https://mwpw-128300--milo--adobecom.hlx.page/tools/caas
Validating fix …
> Updating milo to point to new location where CaaS files will be hosted

- libs/blocks/gnav/gnav.css
- libs/blocks/gnav/gnav.js
- test/blocks/gnav/gnav.test.js
- test/blocks/gnav/mocks/gnav.plain.html
- web-test-runner.config.mjs
* Fix issue where clicking "Sign in" on safari on mobile device didn't show dropdown
* Fix issue where "Sign in" button is inaccessible on Safari 14 mobile
* Fix issue where "Sign in" dropdown and toggle/hamburger menu can be open at the same time
Resolves: [MWPW-127736](https://jira.corp.adobe.com/browse/MWPW-127736)
**Test URLs:**
- Before: https://main--milo--adobecom.hlx.page/drafts/methomas/checkmark?martech=off
- After: https://methomas-sign-in-mobile--milo--adobecom.hlx.page/drafts/methomas/checkmark?martech=off
BACOM:
- Before: https://main--bacom--adobecom.hlx.page/customer-success-stories?martech=off
- After: https://main--bacom--adobecom.hlx.page/customer-success-stories?milolibs=methomas-sign-in-mobile&martech=off
Note: This only occurs on iOS, so you'll need to use …
> MWPW-127736 Fix Safari sign-in dropdown

- tools/floodgate/js/project.js
* Adds supports for floodgating excel files 
* Project excel documents now expects paths instead of URLs
Resolves: [MWPW-128369](https://jira.corp.adobe.com/browse/MWPW-128369)
Sample FG project excel:
- [Before](https://adobe.sharepoint.com/:x:/r/sites/adobecom/_layouts/15/Doc.aspx?sourcedoc=%7B4EBD6F30-D51F-419B-BD0A-7485D4081302%7D&file=sample_fg_project.xlsx&action=default&mobileredirect=true) 
- [After](https://adobe.sharepoint.com/:x:/r/sites/adobecom/_layouts/15/Doc.aspx?sourcedoc=%7BDD97EC98-F756-4F8D-9F4F-8956523D5456%7D&file=fg_with_paths.xlsx&action=default&mobileredirect=true)
**Test URLs:**
- Before: [https://main--milo--adobecom.hlx.page/tools/floodgate/index.html](https://main--milo--adobecom.hlx.page/tools/floodgate/index.html?project=milo--adobecom&referrer=https%3A%2F%2Fa …
> MWPW-128369: Supports floodgating excel files

- libs/blocks/modal/modal.js
* Fix bug where page body scrolls to bottom when georouting modal is present
Resolves: [MWPW-126981](https://jira.corp.adobe.com/browse/MWPW-126981)
**Test URLs:**
- Before: https://main--milo--adobecom.hlx.page/de/drafts/methomas/georouting?martech=off
- After: https://methomas-georouting-jump--milo--adobecom.hlx.page/de/drafts/methomas/georouting?martech=off
BACOM:
- Before: https://main--bacom--adobecom.hlx.page/jp/customer-success-stories?martech=off
- After: https://main--bacom--adobecom.hlx.page/jp/customer-success-stories?martech=off&milolibs=methomas-georouting-jump
Note: Only saw this happen on Chrome >= 106. To get georouting modal to pop up, open an incognito browser, go to US page first, then go to jp (or other geo).
> MWPW-126981 Fix georouting modal scroll

- libs/blocks/marquee/marquee.js
- test/blocks/marquee/marquee.test.js
- test/blocks/marquee/mocks/body.html
* Allows clickable foreground image in Marquee
* Author by adding link under image in doc
Resolves: [MWPW-128724](https://jira.corp.adobe.com/browse/MWPW-128724)
**Test URLs:**
- Before: https://main--milo--adobecom.hlx.page/drafts/methomas/adobe-real-time-customer-data-platform-demo?martech=off
- After: https://methomas-clickable-image--milo--adobecom.hlx.page/drafts/methomas/adobe-real-time-customer-data-platform-demo?martech=off
Bacom:
- Before: https://main--bacom--adobecom.hlx.page/drafts/methomas/adobe-real-time-customer-data-platform-demo
- After: https://main--bacom--adobecom.hlx.page/drafts/methomas/adobe-real-time-customer-data-platform-demo?milolibs=methomas-clickable-image
> MWPW-128724 Clickable marquee image

- tools/floodgate/js/copy.js
- tools/floodgate/js/promote.js
- tools/loc/sharepoint.js
* With Floodgate Copy/Promote action, processes content sequentially in batches
* Adds a query param to Sharepoint's list children API to return a max of 1000 children (MS defaults it to 200)
* Adds a minor delay in between the batch API calls
Resolves: [MWPW-129018](https://jira.corp.adobe.com/browse/MWPW-129018)
**Test URLs:**
- Before: [https://main--milo--adobecom.hlx.page/tools/floodgate/index.html](https://main--milo--adobecom.hlx.page/tools/floodgate/index.html?project=milo--adobecom&referrer=https%3A%2F%2Fadobe.sharepoint.com%2F%3Ax%3A%2Fr%2Fsites%2Fadobecom%2F_layouts%2F15%2FDoc.aspx%3Fsourcedoc%3D%257B4EBD6F30-D51F-419B-BD0A-7485D4081302%257D%26file%3Dsample-fg-project.xlsx%26action%3Ddefault%26mobileredirect%3Dtrue%26cid%3D01fa655f-8f1e-4a0b-a06e-c32ca7c8110e)
- After: …
> MWPW-129018: Batch process content with some delay

- libs/blocks/chart/chart.js
* Fix bug where chart doesn't display if there's no unit (header) in the data
Resolves: [MWPW-128378](https://jira.corp.adobe.com/browse/MWPW-128378)
**Test URLs:**
- Before: https://main--milo--adobecom.hlx.page/drafts/methomas/chart-column-bug?martech=off
- After: https://methomas-chart-unit--milo--adobecom.hlx.page/drafts/methomas/chart-column-bug?martech=off
BACOM:
- Before: https://main--bacom--adobecom.hlx.page/drafts/methomas/chart-column-bug
- After: https://main--bacom--adobecom.hlx.page/drafts/methomas/chart-column-bug?milolibs=methomas-chart-unit
> MWPW-128378 Missing unit bug

- libs/blocks/gnav/gnav-breadcrumbs.js
- libs/scripts/scripts.js
- package-lock.json
- package.json
- test/blocks/gnav/mocks/breadcrumbs/config-off-metadata-off/level1/index.html
- test/blocks/gnav/mocks/breadcrumbs/config-off-metadata-off/level1/level2/index.html
- test/blocks/gnav/mocks/breadcrumbs/config-off-metadata-off/level1/level2/level3/index.html
- test/blocks/gnav/mocks/breadcrumbs/config-off-metadata-off/level1/level2/level3/page.test.html
- test/blocks/gnav/mocks/breadcrumbs/config-off-metadata-on/level1/index.html
- test/blocks/gnav/mocks/breadcrumbs/config-off-metadata-on/level1/level2/index.html
- test/blocks/gnav/mocks/breadcrumbs/config-off-metadata-on/level1/level2/level3/index.html
- test/blocks/gnav/mocks/breadcrumbs/config-off-metadata-on/level1/level2/level3/page.test.html
- test/blocks/gnav/mocks/breadcrumbs/config-on-metadata-off/level1/index.html
- test/blocks/gnav/mocks/breadcrumbs/config-on-metadata-off/level1/level2/index.html
- test/blocks/gnav/mocks/breadcrumbs/config-on-metadata-off/level1/level2/level3/index.html
- test/blocks/gnav/mocks/breadcrumbs/config-on-metadata-off/level1/level2/level3/page.test.html
- test/blocks/gnav/mocks/breadcrumbs/config-on-metadata-on/level1/index.html
- test/blocks/gnav/mocks/breadcrumbs/config-on-metadata-on/level1/level2/index.html
- test/blocks/gnav/mocks/breadcrumbs/config-on-metadata-on/level1/level2/level3/index.html
- test/blocks/gnav/mocks/breadcrumbs/config-on-metadata-on/level1/level2/level3/page.test.html
- test/blocks/gnav/mocks/breadcrumbs/from-ancestor-file/level1/level2/level3/page.test.html
- test/blocks/gnav/mocks/breadcrumbs/from-url/level1/level2/level3/page.test.html
- test/blocks/gnav/mocks/breadcrumbs/hide-page/level1/level2/level3/page.test.html
- test/blocks/gnav/mocks/breadcrumbs/specific-title/page.test.html
- makes the automatic generation of the breadcrumb block (when a breadcrumb is not defined on the page) disabled by default.
- adds tests
The logic is as follows:
1) the page has a breadcrumbs block
-> render it
2) metadata.breadcrumbs = on
-> render the automated breadcrumbs (from file if any, otherwise from URL)
3) metadata.breadcrumbs = off
-> no breadcrumbs
4) config.breadcrumbs = on
-> render the automated breadcrumbs (from file if any, otherwise from URL)
5) config.breadcrumbs = off or undefined
-> no breadcrumbs
Resolves: 
[MWPW-128614](https://jira.corp.adobe.com/browse/MWPW-128614)
**Test URLs: the breadcrumbs block is defined in the current page:**
- Before: https://main--milo--adobecom.hlx.page/drafts/jck/breadcrumbs/1-from-page/test?martech=off
- After: …
> MWPW-128614 - [Core] breadcrumbs should be disabled by default

- libs/blocks/video/video.js
- test/blocks/video/mocks/body.html
- test/blocks/video/video.test.js
* Adds the functionality to have videos loop once.  Adding `#autoplay1` at the end of a video url will ensure the video only place once instead of looping. 
Resolves: [MWPW-129009](https://jira.corp.adobe.com/browse/129009)
**Test URLs:**
- Before: https://main--milo--adobecom.hlx.page/drafts/slavin/digital-trends-report?martech=off
- After: https://video-loop-options--milo--adobecom.hlx.page/drafts/slavin/digital-trends-report?martech=off
> MWPW-129009: Video Loop Enhancement

- libs/blocks/global-navigation/utilities/getUserEntitlements.js
We got some feedback for https://github.com/adobecom/milo/pull/522 the default response for the getUserEntitlements utility now looks similar to what we provide in the dexter world with `feds.utilities.getUserEntitlements().then(data => console.log(data))` 
An empty response will be provided in any case of error instead of rejecting the promise.
```js
// Example output import getEntitlements from './utilities/getUserEntitlements.js';
const res = await getEntitlements({params, locale});
res = {
"clouds": {
"creative_cloud": false,
"document_cloud": false,
},
"arrangment_codes": {
"arrangment_codes-1": true,
"arrangment_codes-2": true
},
"fulfilled_codes": {
"fulfilled_codes-1": true,
"fulfilled_codes-2": true,
},
"offer_families": {
"offer_families_string": true
},
"list": { …
```
> MWPW-129129: Improve user entitlements

- codecov.yaml
- PRs should have full coverage but allow wiggle room for [unexpected coverage changes](https://docs.codecov.com/docs/unexpected-coverage-changes).
- main should have same wiggle room, just don't let coverage drop
Resolves one issue causing red builds. See https://github.com/orgs/adobecom/discussions/626
Resolves: [MWPW-129597](https://jira.corp.adobe.com/browse/MWPW-129597)
Test URL:
- https://codecov-changes--milo--hparra.hlx.page/
Validation: `curl -X POST --data-binary @codecov.yaml https://codecov.io/validate`
Documentation: https://docs.codecov.com/docs/codecovyml-reference
> Improve Codecov config for unexpected coverage changes

- libs/blocks/tabs/tabs.css
* Addressed tabs style bug. `tabs.css` variable had an incorrect modern color format. 
There was some css linting clean up in the last PR and this was overlooked. 
Resolves: [MWPW-129763](https://jira.corp.adobe.com/browse/MWPW-129763)
**Test URLs:**
- Before: https://main--milo--adobecom.hlx.page/docs/library/blocks/tabs?martech=off
- After: https://rparrish-tabs-style-bug--milo--adobecom.hlx.page/docs/library/blocks/tabs?martech=off
Testing note: Notice the subtle gradient in the tab-list background color on the after url.
> Tabs bug: minor style color format fix

- tools/floodgate/js/floodgate.js
- tools/floodgate/js/project.js
- tools/loc/sharepoint.js
* MS's $batch API did not provide much benefit and error handling with RateLimit headers/429 is complex given how the responses are structured
* Updated to use custom batching similar to how copy/promote is currently done
Resolves: [MWPW-129567](https://jira.corp.adobe.com/browse/MWPW-129567)
**Test URLs:**
- Before: [https://main--milo--adobecom.hlx.page/tools/floodgate/index.html](https://main--milo--adobecom.hlx.page/tools/floodgate/index.html?project=milo--adobecom&referrer=https%3A%2F%2Fadobe.sharepoint.com%2F%3Ax%3A%2Fr%2Fsites%2Fadobecom%2F_layouts%2F15%2FDoc.aspx%3Fsourcedoc%3D%257B2A168441-F440-4552-A195-90CB12A418A0%257D%26file%3Ddemo-fg.xlsx%26action%3Ddefault%26mobileredirect%3Dtrue)
- After: [https://main--milo--sukamat.hlx.page/tools/floodgate/index.html](https://main--milo-- …
> MWPW-129567: $batch API usage replaced in FG

- libs/blocks/global-navigation/blocks/profile/dropdown.js
- libs/blocks/global-navigation/blocks/search/gnav-search.js
- libs/blocks/global-navigation/global-navigation.js
- libs/blocks/global-navigation/utilities/keyboard/index.js
- libs/blocks/global-navigation/utilities/keyboard/mainNav.js
- libs/blocks/global-navigation/utilities/keyboard/mobilePopup.js
- libs/blocks/global-navigation/utilities/keyboard/popup.js
- libs/blocks/global-navigation/utilities/keyboard/utils.js
- libs/blocks/global-navigation/utilities/utilities.js
- test/blocks/global-navigation/keyboard/keyboard.test.js
- test/blocks/global-navigation/keyboard/mocks/global-nav-mobile.html
- test/blocks/global-navigation/keyboard/mocks/global-nav.html
This brings the keyboard navigation feature that current exists in AEM to the milo feds-gnav. This has been a hard requirement for the AEM-Feds-GNAV in the past for accessibility reasons, which is why we need to port this to the milo navigation. Resolves: [MWPW-125255](https://jira.corp.adobe.com/browse/MWPW-125255)
A few of the notable use-cases
- RTL support
- Shift+Tab support
- Cycle through the navigation if the search is open
- Close any open menu when you open a new one (E.g. only search OR profile OR a popup can be open)
- Arrow key support on the main nav & popups, also on mobile
- enter/space/escape keys should work on any element now
- In total ~80 test cases based on the old implementation which had a lot of back and forth with the accessibility team, there's a lot of small …
> Keyboard support

- libs/blocks/global-navigation/global-navigation.js
Fixes a JS error for logged in users 
```
global-navigation.js:268 Uncaught (in promise) TypeError: (intermediate value) is not iterable
at Gnav.decorateProfile (global-navigation.js:268:46)
```
Resolves: No ticket was raised
Log in with a stage account and observe the profile missing on the main branch.
**Test URLs:**
- Before: https://main--milo--adobecom.hlx.page/drafts/ramuntea/gnav-refactor?martech=off#
- After: https://gnav--milo--adobecom.hlx.page/drafts/ramuntea/gnav-refactor?martech=off#
> Correctly parse profile data for global-navigation

- libs/styles/typography.css
- libs/utils/decorate.js
The default `con-button` looks invisible without a `outline`, or `blue` style being set on the class list. 
* Updated the `con-button` default styles to match `outline` and removed any redundant styles
* Add to the `typography.css` file to support `aria-disabled="true"` styles and fixed sort order/css-linting
Resolves: [MWPW-130320](https://jira.corp.adobe.com/browse/MWPW-130320)
**Test URLs:**
- Before: https://main--milo--adobecom.hlx.page/drafts/rparrish/buttons
- After: https://rparrish-button-default--milo--adobecom.hlx.page/drafts/rparrish/buttons
> con-button styles have bad defaults

- libs/blocks/gnav/gnav.js
When using the Milo Gnav, if no menu content is added to the navigation, there shouldn't be a hamburger menu on mobile devices.
Resolves: [MWPW-128317](https://jira.corp.adobe.com/browse/MWPW-128317)
**Test URLs:**
- Before: https://main--milo--overmyheadandbody.hlx.page/drafts/ramuntea/prev/gnav-barebones?martech=off
- After: https://mwpw-128317-no-hamburger-if-not-needed--milo--overmyheadandbody.hlx.page/drafts/ramuntea/prev/gnav-barebones?martech=off
> [MWPW-128317] No hamburger when menu has no content

- .eslintrc.js
- libs/blocks/table-metadata/table-metadata.js
- libs/blocks/table/table.css
- libs/blocks/table/table.js
* removed code for highlight from table-metadata block and moved it to the table block
* removed some temp CSS from table.css. It was causing issues to leave it in and I don't think it was meant to be permanent.
* supports first row being left empty if the author wants to keep it as a placeholder to add a highlight row later
* highlight is now a variant of the table block.  If highlight is on, the first row with content is treated as the highlight row. The 2nd row is assumed to be the header row. Otherwise, if highlight is off, the first row with content is the header row.
* sticky top added as a variant of table block. Locks header row and highlight row (if it exists). Added default background color of white so you cannot see the content of the lower rows passing behind the words.
* …
> Table sticky

- tools/floodgate/js/promote.js
- tools/loc/sharepoint.js
Link to the ticket: https://jira.corp.adobe.com/browse/MWPW-129539
The PR does the following:
Right now, in promote, saveFile() is called if the file exists at the destination. saveFile() makes several calls in order to handle locked files. The updated code in this PR calls saveFile() only if the file is locked or the folder is absent at the destination. Otherwise, it directly copies the file. This reduces the number of calls significantly (about 40%). 
**Test URLs:**
**Before**: https://main--milo--adobecom.hlx.page/tools/floodgate/index.html?project=milo--adobecom&referrer=https%3A%2F%2Fadobe.sharepoint.com%2F%3Ax%3A%2Fr%2Fsites%2Fadobecom%2F_layouts%2F15%2FDoc.aspx%3Fsourcedoc%3D%257B59E5B572-A72C-40B8-96AF-4591908EA744%257D%26file%3Dtest_with_50.xlsx%26action%3Ddefault%26mobileredirect …
> MWPW-129539 Update file overwrite logic during promote copy

- test/blocks/marketo/marketo.test.js
Since the tests fail on the majority/all PRs, skipping them for now until someone has time to further look into them / write new tests.
as per @Brandon32 
> There have been a lot of changes to the Marketo form coming from the Marketo instance that we do not have control over. I haven’t had time to look into this specific issue but we can remove those tests because we have a whole new story map and authoring experience coming to the Marketo forms.
> Skip unreliable marketo tests for now

- tools/floodgate/js/copy.js
- tools/loc/sharepoint.js
Link to the ticket: https://jira.corp.adobe.com/browse/MWPW-129539
The PR does the following:
Right now, in copy action, saveFile() is called if the file exists at the destination. saveFile() makes several calls in order to handle locked files. The updated code in this PR calls saveFile() only if the file is locked or the folder is absent at the destination. Otherwise, it directly copies the file. This reduces the number of calls significantly.
Test URLs:
Before: https://main--milo--adobecom.hlx.page/tools/floodgate/index.html?project=milo--adobecom&referrer=https%3A%2F%2Fadobe.sharepoint.com%2F%3Ax%3A%2Fr%2Fsites%2Fadobecom%2F_layouts%2F15%2Fdoc2.aspx%3Fsourcedoc%3D%257BB2136347-CE65-470B-842E-C1E55C7C86A4%257D%26file%3DfileOverwrite.xlsx%26action%3Ddefault%26mobileredirect%3Dtrue%26cid%3 …
> MWPW-129539 : Update file overwrite logic during copy (COPY action)

- libs/blocks/global-navigation/global-navigation.js
- libs/blocks/global-navigation/utilities/keyboard/index.js
- libs/blocks/global-navigation/utilities/keyboard/mainNav.js
- libs/blocks/global-navigation/utilities/keyboard/mobilePopup.js
- libs/blocks/global-navigation/utilities/keyboard/popup.js
- libs/blocks/global-navigation/utilities/keyboard/utils.js
- libs/blocks/global-navigation/utilities/utilities.js
- test/blocks/global-navigation/global-navigation.test.js
- test/blocks/global-navigation/mocks/global-navigation-only-brand.plain.js
- test/blocks/global-navigation/test-utilities.js
- test/blocks/global-navigation/utilities/getUserEntitlements.test.js
- Correct navigation on the main navigation using the right, left key if document.dir === 'ltr' is not set, example on Firefox
- Do not close innocent dropdowns that don't want to get closed, such as the search when the clear button is clicked.
Resolves: [MWPW-130481](https://jira.corp.adobe.com/browse/MWPW-130481)
**Test URLs:**
- Before: https://gnav--milo--adobecom.hlx.page/drafts/ramuntea/gnav-refactor?martech=off#
- After: https://gnav-improvements--milo--mokimo.hlx.page/drafts/ramuntea/gnav-refactor?martech=off#
> Small global navigation improvements

- libs/blocks/global-navigation/utilities/utilities.js
Correctly fetch placeholders from `.hlx.`-pages from the milo content path and not `/libs or miloLibs`
Resolves: [MWPW-131190](https://jira.corp.adobe.com/browse/MWPW-131190)
- Observe the "sign in" label to be lowercase before, and capitalised after.
- And/or observe `placeholders` in the network tab to correctly return a 200 fetching from https://main--milo--adobecom.hlx.page/placeholders.json?sheet=feds
**Test URLs:**
- Before: https://main--stockpoc--adobecom.hlx.page/blog/?martech=off&headerqa=global-navigation
- After: https://main--stockpoc--adobecom.hlx.page/blog/?martech=off&headerqa=global-navigation&milolibs=mwpw-131190--milo--mokimo
> MWPW-131190: Global-navigation correctly fetch placeholders for consumer .hlx. pages

- tools/floodgate/js/copy.js
- tools/floodgate/js/promote.js
- tools/floodgate/js/utils.js
- The preview API call is now sequential to handle large sets. Also adds a delay per call similar to the bulk publish util.
Resolves: [MWPW-131263](https://jira.corp.adobe.com/browse/MWPW-131263)
**Test URLs:**
- Before: https://main--milo--adobecom.hlx.page/tools/floodgate/index.html?project=milo--adobecom&referrer=https%3A%2F%2Fadobe.sharepoint.com%2F%3Ax%3A%2Fr%2Fsites%2Fadobecom%2F_layouts%2F15%2FDoc.aspx%3Fsourcedoc%3D%257B4EBD6F30-D51F-419B-BD0A-7485D4081302%257D%26file%3Dsample_fg_project.xlsx%26action%3Ddefault%26mobileredirect%3Dtrue
- After: https://main--milo--sukamat.hlx.page/tools/floodgate/index.html?project=milo--adobecom&referrer=https%3A%2F%2Fadobe.sharepoint.com%2F%3Ax%3A%2Fr%2Fsites%2Fadobecom%2F_layouts%2F15%2FDoc.aspx%3Fsourcedoc%3D%257B4EBD6F30-D51F-419B-BD0A-7485D408 …
> MWPW-131263: Preview API call updates for Floodgate

- libs/blocks/uar-results/uar-results.css
- libs/blocks/uar-results/uar-results.js
- test/blocks/uar-results/mocks/body.html
- test/blocks/uar-results/mocks/fragments/basic-frag.plain.html
- test/blocks/uar-results/mocks/fragments/nested-frag.plain.html
- test/blocks/uar-results/mocks/uar-results.mock-data.js
- test/blocks/uar-results/uar-results.test.js
* Lana logging  and a debug param to stop redirects (MWPW-125185)
* Set a value for pageload analytics (MWPW-128939)
* Unit tests (MWPW-130870)
Resolves: [MWPW-125185](https://jira.corp.adobe.com/browse/MWPW-125185)
Resolves: [MWPW-128939](https://jira.corp.adobe.com/browse/MWPW-128939)
Resolves: [MWPW-130870](https://jira.corp.adobe.com/browse/MWPW-130870)
**Test URLs:**
- Before: https://uar-integration--milo--adobecom.hlx.page/drafts/colloyd/uar-results-block/uar-results?quizKey=cc-uar-result&martech=off
- After: https://uar-results-finalized--milo--colloyd.hlx.page/drafts/colloyd/uar-results-block/uar-results?quizKey=cc-uar-result&debug=uar&martech=off
To properly test this, you will need to add data to local storage for the before and after URL's. With quiz URL redirects now in place …
> Finalized UAR Results

- .eslintrc.js
- libs/features/georoutingv2/georoutingv2.js
- libs/scripts/scripts.js
This moves the loading of the country flag svgs from within the milo codebase:
https://milo.adobe.com/libs/features/georoutingv2/img/flag_ch.svg
to within sharepoint where authors can maintain the flag svgs:
https://milo.adobe.com/libs/img/georouting/flag-ch.svg
Note that _ have been changed to - since Franklin automatically converts underscores to dash.  I've also renamed all the flag files in sharepoint to use dashes instead of underscores in sharepoint/milo/libs/img/georouting/*.svg
Once we've verified the fix after merging we will be able to delete all of the flag files in /libs/features/georoutingv2/img
Resolves: [MWPW-131381](https://jira.corp.adobe.com/browse/MWPW-131381)
**Test URLs:**
- Before: https://main--milo--adobecom.hlx.page/drafts/cpeyer/experiment-test?akamaiLocale=ch&mar …
> MWPW-131381 Move flags to sharepoint

- libs/blocks/global-navigation/features/profile/dropdown.js
- libs/blocks/global-navigation/features/search/gnav-search.js
- libs/blocks/global-navigation/global-navigation.js
- libs/blocks/global-navigation/utilities/getUserEntitlements.js
- libs/blocks/global-navigation/utilities/keyboard/mainNav.js
- libs/blocks/global-navigation/utilities/onImsReady.js
- libs/blocks/global-navigation/utilities/utilities.js
- libs/scripts/scripts.js
* Allow Milo consumers to configure ims custom scope
* Create `onImsReady` utility instead of dispatching an event; this should be more suitable for use-cases where logic is loaded **after** ims is ready.
* Call Subscriptions API using Milo configured language / locale
* Remove TODO for closing the search menu on scroll, this is not needed for sticky navigation
* There's a dedicated story for App Launcher, no need for an additional TODO - [MWPW-119227](https://jira.corp.adobe.com/browse/MWPW-119227)
* There's a dedicated story for refactoring the navigation curtain, no need for an additional TODO - [MWPW-131186](https://jira.corp.adobe.com/browse/MWPW-131186)
* Remove TODO for additional checks in Profile Menu dropdown, they are only needed in the standalone implementation which we're not …
> Address TODOs

- libs/blocks/global-navigation/global-navigation.css
Make sure the global navigation is displayed on top of existing page content when scrolling; the z-index value has been increased.
before:
after:
Resolves: [MWPW-131203](https://jira.corp.adobe.com/browse/MWPW-131203)
**Test URLs:**
- After: https://mwpw-131203--milo--narcis-radu.hlx.page/drafts/narcis/default?martech=off
> Ensure the global navigation is displayed on top of page content

- libs/blocks/global-navigation/features/profile/dropdown.js
- libs/blocks/global-navigation/features/search/gnav-search.js
- libs/blocks/global-navigation/global-navigation.js
- libs/blocks/global-navigation/utilities/keyboard/index.js
- libs/blocks/global-navigation/utilities/keyboard/mainNav.js
- libs/blocks/global-navigation/utilities/keyboard/mobilePopup.js
- libs/blocks/global-navigation/utilities/keyboard/popup.js
- libs/blocks/global-navigation/utilities/menu/menu.js
- libs/blocks/global-navigation/utilities/utilities.js
Add lana logs for the global-navigation and a few of its complicated event listeners.
Resolves: [MWPW-127607](https://jira.corp.adobe.com/browse/MWPW-127607)
In the global-navigation we can't rely on implicitly caught errors / promises, as we exist on every page.
We need to ensure (most) of the errors that are originating from our code are also caught by us and our lana clientId. 
Due to the way different modules are dynamically loaded and the very async nature of our code, trying to effectively catch errors originating from _everywhere_ is non-trivial. 
This should provide a good baseline and it might make sense to check consumer lana logs from time to time if we see any uncaught global-navigation related errors, that we didn't catch.
**Test URLs:**
- Before: …
> MWPW-126707: Global navigation lana logs

- libs/scripts/delayed.js
* Default to acom privacy configuration if consumer does not provide a custom ID
Resolves: [MWPW-131663](https://jira.corp.adobe.com/browse/MWPW-131663)
**Test URLs:**
- After: https://default-privacy--milo--narcis-radu.hlx.page/drafts/narcis/default?martech=off
> Provide default id for privacy

- libs/blocks/featured-article/featured-article.css
- libs/styles/article-card.css
- libs/styles/variables.css
* Fixes typography getting cut off in Featured Article block
* Fixes typography getting cut off in  Article Card block
Resolves: [MWPW-129907](https://jira.corp.adobe.com/browse/MWPW-129907)
**Test URLs:**
- Before: https://main--blog--adobecom.hlx.page/fr/?martech=off
- After: https://main--blog--adobecom.hlx.page/fr/?milolibs=blog-article-block-styling&martech=off
> MWPW-129907 Blog Article Typography Corrections

- libs/blocks/tags/tags.js
This fixes a bug where Blog tags were getting stripped down to the point they no longer matched what was listed in the related taxonomy file. Causing tags to not render on the page.
Resolves: [MWPW-129907](https://jira.corp.adobe.com/browse/MWPW-129907)
**Test URLs:**
- Before: https://main--blog--adobecom.hlx.page/ko/publish/2021/04/20/how-to-convert-psd-to-png-or-jpg?martech=off
- After: https://main--blog--adobecom.hlx.page/ko/publish/2021/04/20/how-to-convert-psd-to-png-or-jpg?milolibs=blog-tags&martech=off
- Before: https://main--blog--adobecom.hlx.page/fr/publish/2023/04/27/rapport-rse-2022-d-adobe-donner-du-sens-a-notre-leadership?martech=off
- After: https://main--blog--adobecom.hlx.page/fr/publish/2023/04/27/rapport-rse-2022-d-adobe-donner-du-sens-a-notre-leadership?milolibs=blog- …
> MWPW-129907 Blog Tags

- tools/floodgate/js/project.js
* With copy and promote calls moving to AIO with app based auth, the batched GET calls on page load is added back
Resolves: [MWPW-131266](https://jira.corp.adobe.com/browse/MWPW-131266)
**Test URLs:**
- Before: https://main--milo--adobecom.hlx.page/tools/floodgate/index.html?project=milo--adobecom&referrer=https%3A%2F%2Fadobe.sharepoint.com%2F%3Ax%3A%2Fr%2Fsites%2Fadobecom%2F_layouts%2F15%2FDoc.aspx%3Fsourcedoc%3D%257BFF6518DD-EFA8-4676-9B57-892C6E3C2D2F%257D%26file%3Dlarge-50.xlsx%26action%3Ddefault%26mobileredirect%3Dtrue
- After: https://main--milo--sukamat.hlx.page/tools/floodgate/index.html?project=milo--adobecom&referrer=https%3A%2F%2Fadobe.sharepoint.com%2F%3Ax%3A%2Fr%2Fsites%2Fadobecom%2F_layouts%2F15%2FDoc.aspx%3Fsourcedoc%3D%257BFF6518DD-EFA8-4676-9B57-892C6E3C2D2F%257D%26file%3D …
> MWPW-131266: Update FG project details

- libs/blocks/region-nav/region-nav.js
- Bug fix for region nav when content root is used.
Resolves: [MWPW-131680](https://jira.corp.adobe.com/browse/MWPW-131680)
**Test URLs:**
CC:
- Before: https://main--cc--adobecom.hlx.live/creativecloud/video/hub/ideas/what-is-a-contrast-cut#langnav
- After: https://main--cc--adobecom.hlx.live/creativecloud/video/hub/ideas/what-is-a-contrast-cut?milolibs=region-nav-fix#langnav
DC:
- Before: https://main--dc--adobecom.hlx.live/fr/acrobat/online/word-to-pdf#langnav
- After: https://main--dc--adobecom.hlx.live/fr/acrobat/online/word-to-pdf?milolibs=region-nav-fix#langnav
BACOM (site doesn't have issue now)
- Before: https://main--bacom--adobecom.hlx.page/kr/customer-success-stories
- After: https://main--bacom--adobecom.hlx.page/kr/customer-success-stories?milolibs=region-nav-fix
> Let region nav to use prefix instead content root.

- libs/blocks/modal/modal.js
- libs/features/georoutingv2/georoutingv2.js
* Georouting modal: provide alternate text for country flags
* Modal: disable TAB navigation outside the modal when rendered
* Modal: ignore non-modal content when modal is rendered
Resolves: [MWPW-131868](https://jira.corp.adobe.com/browse/MWPW-131868)
**Test URLs:**
- After: https://accessibility--milo--narcis-radu.hlx.page/drafts/narcis/default?martech=off
> Improve navigation support when modals are displayed

- libs/blocks/section-metadata/section-metadata.css
* Adding a divider style row just adds a divider class.
* Extent the syntax to add an inherit option to not specify the color.
* That way, the divider would just follow the text color and give us what we would like. 
Resolves: [MWPW-131449](https://jira.corp.adobe.com/browse/MWPW-131449)
**Test URLs:**
- Before: https://main--milo--adobecom.hlx.page/fragments/xiasun/divider?martech=off
- After: https://main--milo--JackySun9.hlx.page/fragments/xiasun/divider?martech=off
I need to add an usage example to the section metadata documentation after the PR is merged.
> Add divider-inherit css to support different color divider

- tools/floodgate/js/floodgate.js
- tools/floodgate/js/ui.js
- Updating LastRun status column from AIO action calls instead of reading from Project Excel file
Resolves: [MWPW-131802](https://jira.corp.adobe.com/browse/MWPW-131802)
- milo-fg PR to store start and end times for fg actions - https://github.com/adobecom/milo-fg/pull/31
**Test URLs:**
- Before: https://main--milo--adobecom.hlx.page/tools/floodgate/index.html?project=milo--adobecom&referrer=https%3A%2F%2Fadobe.sharepoint.com%2F%3Ax%3A%2Fr%2Fsites%2Fadobecom%2F_layouts%2F15%2FDoc.aspx%3Fsourcedoc%3D%257B753F31A9-CA16-4B78-AE9C-BAD08AE0688A%257D%26file%3Dfgtest.xlsx%26action%3Ddefault%26mobileredirect%3Dtrue
- After: https://mwpw-131802--milo--sirivuri.hlx.page/tools/floodgate/index.html?project=milo--adobecom&referrer=https%3A%2F%2Fadobe.sharepoint.com%2F%3Ax%3A%2Fr%2Fsites%2Fadobecom%2F_l …
> Updating LastRun status column from AIO action calls instead of reading from Project Excel file

- web-test-runner.config.mjs
**Log if a unit test does a request to an external resource.** 
A step towards: [MWPW-129653](https://jira.corp.adobe.com/browse/MWPW-129653)
This takes up bandwidth, leads to slower unit tests and worst of all sporadically fails them if the resource isn't provided on time.
This should provide some feedback to devs writing unit tests and discourage requesting any resource that does not live on localhost.
> Unit tests - surface external requests

- libs/blocks/bulk-publish/bulk-publish.js
- fix: URLs max = 0 when the request has no limit param
Resolves: [MWPW-125675](https://jira.corp.adobe.com/browse/MWPW-125675)
**Test URLs:**
- Before: https://main--milo--adobecom.hlx.page/tools/bulk-publish?martech=off&limit=25
- After: https://bulk-limit-2--milo--adobecom.hlx.page/tools/bulk-publish?martech=off&limit=25
> MWPW-125675 - [Core] Milo Bulk Publish

- package.json
- web-test-runner.config.mjs
I played around with directly supplying an import map for all tests and mocking [all the utils](https://github.com/mokimo/milo/blob/import-maps-TODO/web-test-runner.config.mjs#L42-L62) but the major drawback of import maps in this specific case are that they aren't compatible with dynamic imports. It leads to a lot of headache and confusion, so I've abandoned that approach.
Instead, we can just log unit-test smells and provide developers with enough guidance https://github.com/orgs/adobecom/discussions/814
Resolves: [MWPW-129653](https://jira.corp.adobe.com/browse/MWPW-129653)
I'm not the biggest fan of having a lot of logs BUT it's the only viable way we can provide guidance to milo core developers on what to look out for when writing unit tests.
When running tests in isolation it's also …
> Surface unit test errors and point to a solution source

- .github/workflows/email-release.yaml
Email bot now supports sending mail to 2 separate group lists.
NEW_FEATURE goes to everyone
HIGH_IMPACT goes to milo and consumer devs
milo email bot PR: https://github.com/adobecom/milo-email-bot/pull/8
Do not merge until changes to email bot and email config have been done.
> Update label email groups

- libs/blocks/bulk-publish/bulk-publish-utils.js
- increase throttling to defend against overwhelming Sharepoint when bulk previewing large set of URLs
**Test URLs:**
- Before: https://main--milo--adobecom.hlx.page/tools/bulk-publish?martech=off
- After: https://bulk-throttling--milo--adobecom.hlx.page/tools/bulk-publish?martech=off
> Bulk preview/publish: increase throttling

- .eslintrc.js
- libs/blocks/article-feed/article-feed.js
- libs/blocks/bulk-publish/bulk-publish-utils.js
- libs/blocks/global-footer/global-footer.js
- libs/blocks/global-navigation/global-navigation.js
- libs/blocks/global-navigation/utilities/menu/menu.js
- libs/blocks/gnav/gnav-contextual-search.js
- libs/blocks/preflight/panels/seo.js
- libs/utils/tree.js
- libs/utils/utils.js
- test/helpers/selectors.js
- tools/floodgate/js/copy.js
- tools/floodgate/js/promote.js
- tools/loc/rollout.js
- tools/loc/sharepoint.js
- tools/send-to-caas/bulk-publish-to-caas.js
- tools/send-to-caas/send-utils.js
We use await inside of for..of loops enough that we don't need to have an eslint warning for it.  Saves a bit of file size too.
> Remove for..of, await in loop eslint warnings

- tools/send-to-caas/send-utils.js
Due to import errors some cards have the description key set to cardDescription.  This allows either of the keys to be used to set the card description.
> Also support cardDescription in caas metadata

- libs/blocks/text/text.css
* This fix resolves the link wrapping issue in link farm block
Resolves: [MWPW-132406](https://jira.corp.adobe.com/browse/MWPW-132406)
Before:
After:
**Test URLs:**
- Before: https://main--milo--adobecom.hlx.page/drafts/Drashti/linkfarmblock
- After: https://linkfarmfix--milo--drashti1712.hlx.page/drafts/Drashti/linkfarmblock
> [MWPW-132406] Long text links are not seen getting wrapped in Linkfarm

- .github/pull_request_template.md
- libs/blocks/global-navigation/global-navigation.js
When no menu items are authored to be added to the navigation, a hamburger menu (toggle) shouldn't be created.
This also fixes a minor typo in the Git PR template.
Resolves: [MWPW-118520](https://jira.corp.adobe.com/browse/MWPW-118520)
**Test URLs:**
- Before: https://main--milo--overmyheadandbody.hlx.page/drafts/ramuntea/limited-gnav?martech=off
- After: https://menuless-gnav--milo--overmyheadandbody.hlx.page/drafts/ramuntea/limited-gnav?martech=off
> [MWPW-118520] Menuless gnav

- libs/blocks/merch/merch.js
- libs/blocks/ost/README.md
- libs/blocks/ost/ost.js
- test/blocks/merch/merch.test.js
- test/blocks/ost/mocks/ost-utils.js
- test/blocks/ost/ost.test.html
- test/blocks/ost/ost.test.html.js
- test/blocks/ost/ost.test.js
- tools/sidekick/config.json
Resolves: [MWPW-127984](https://jira.corp.adobe.com/browse/MWPW-127984)
Milo OST block is updated to:
- accept "owner", "referrer", and "repo" querystring parameters,
- these parameters are normally passed to any sidekick plugin configured with "passConfig" and "passReferrer",
- use these parameters to fetch page preview URL from the admin AP,
- use fetched preview url to:
- determine page locale,
- fetch page metadata,
- initialise OST with country, language and OST-related metadata (checkoutType etc.)
**Test URLs:**
> Please, first add your IMS token at the end test URL by following [this instruction](https://github.com/adobecom/milo/pull/771/files#diff-b8a8e71badbe17831d377dd74d796fa3e1e98ab182354e62bb86364fd01f1720R18)
This URL opens OST as if it was opened for page …
> MWPW-127984: Make OST locale- and metadata-aware

- libs/blocks/text/text.css
- libs/blocks/text/text.js
- test/blocks/text/mocks/body.html
- test/blocks/text/text.test.js
* This extends the functionality of link farm variant of text blocks by allowing the authors to add optional Headings for the link columns. The solution, as discussed in the comments and with the consonant team, would be to add a [No-Heading] placeholder in the authoring for blocking a space for the heading as shown below. 
* Related to - https://jira.corp.adobe.com/browse/MWPW-129911, https://jira.corp.adobe.com/browse/MWPW-132409, https://jira.corp.adobe.com/browse/MWPW-132427
* Update: The solution was revised and we no longer need to add a [No-Heading] placeholder in authoring.
Resolves: [MWPW-132409](https://jira.corp.adobe.com/browse/MWPW-132409)
Authoring (updated):
Before:
After: 
**Test URLs:**
- Before: https://main--milo--adobecom.hlx.page/drafts/Drashti/document
- After: …
> Mwpw 132409 - Optional Headings for Link Farms

- .github/workflows/enforce-labels.yml
Resolves: [MWPW-129654](https://jira.corp.adobe.com/browse/MWPW-129654)
I added 'needs-verification' label: https://github.com/adobecom/milo/issues/labels and changed enforce PR label workflow to accept it.
**Test URLs:**
- Before: https://main--milo--hparra.hlx.page/?martech=off
- After: https://needs-verification--milo--hparra.hlx.page/?martech=off
> MWPW-129654: Add 'needs-verification' to PR label check

- libs/blocks/global-navigation/base.css
- libs/blocks/global-navigation/global-navigation.css
- libs/blocks/global-navigation/utilities/menu/menu.js
- test/blocks/global-navigation/global-navigation.test.js
- test/blocks/global-navigation/mocks/global-navigation.plain.js
The bacom customer success stories have a "last link blue" feature which was previously achieved using section metadata. As we introduced the new global navigation, we also introduced a so called `link group` feature which acts and behaves like a block. The section metadata will have limitations in the future when adding `second-last-link-red` for example and wouldn't be very extensible. To have a more natural milo-style of authoring, we want to add modifiers.
Allow authors to add modifiers to link groups
Style dropdown items, with this PR allow links to become blue.
Resolves: [MWPW-132977](https://jira.corp.adobe.com/browse/MWPW-132977)
**Test URLs:**
- Before: https://main--milo--adobecom.hlx.page/drafts/osahin/gnav-1
- After: https://mwpw-132977--milo--mokimo.hlx.page/drafts/osahin/gnav …
> MWPW-132977: Support global navigation link group modifier 'blue'

- libs/blocks/quiz/quiz.css
* Updating quiz.css to hide default content before the preact app loads. We had some code that previously made the attempt, by hiding sibling div elements of the .quiz-container, but by the time that element loads, it's rather late. 
Resolves: [MWPW-133219](https://jira.corp.adobe.com/browse/MWPW-133219)
**Test URLs:**
- Before: 
https://uar-integration--milo--adobecom.hlx.page/drafts/delta/app-recommender/?martech=off
https://pagespeed.web.dev/analysis/https-uar-integration--milo--adobecom-hlx-page-drafts-delta-app-recommender/ztj24kh6md?form_factor=mobile
- After: 
https://mwpw-133219--milo--echampio-at-adobe.hlx.page/drafts/delta/app-recommender/?martech=off
https://pagespeed.web.dev/analysis/https-mwpw-133219--milo--echampio-at-adobe-hlx-page-drafts-delta-app-recommender/svljqklln9?for …
> MWPW-133219: Hide default content before the preact app loads

- libs/blocks/tabs/tabs.js
- test/blocks/tabs/mocks/body.html
* Fix for tabs in a fragment not loading on a page
Resolves: [MWPW-133063](https://jira.corp.adobe.com/browse/MWPW-133063)
**Test URLs:**
- Before: https://main--milo--adobecom.hlx.page/drafts/ruchika/fragmentpage?martech=off
- After: https://tab-in-fragment--milo--ruchika4.hlx.page/drafts/ruchika/fragmentpage?martech=off
As I am updating a code change that was done to make sure tabs load fine in georouting modal as part of this [PR](https://github.com/adobecom/milo/pull/497/files) hnece adding urls to verify that georouting modal with tabs also works fine after this PR
Georouting URLs to verify tabs in modal
Milo
- Before: https://main--milo--adobecom.hlx.page/drafts/ruchika/fragmentpage?akamaiLocale=in
- After: https://tab-in-fragment--milo--ruchika4.hlx.page/drafts/ruchika/fragmentpage? …
> MWPW-133063-Fix for tabs in a fragment not loading on a page

- libs/blocks/pdf-viewer/pdf-viewer.js
- test/blocks/pdf-viewer/mocks/body.html
- test/utils/mocks/body.html
* update pdf-viewer api url
Resolves: [MWPW-133054](https://jira.corp.adobe.com/browse/MWPW-133054)
**Test URLs:**
Bacom:
- Before: https://main--bacom--adobecom.hlx.page/resources/reports/connecting-the-dam-dots/thank-you?martech=off
- After: https://main--bacom--adobecom.hlx.page/resources/reports/connecting-the-dam-dots/thank-you?milolibs=pdf-viewer--milo--ruchika4&martech=off
CC:
- Before: https://main--cc--adobecom.hlx.page/drafts/ruchika/pdfembed?martech=off
- After: https://main--cc--adobecom.hlx.page/drafts/ruchika/pdfembed?martech=off&milolibs=pdf-viewer--milo--ruchika4
Note: Before after urls should work exactly the same. This is just a domain change from product team and all the features should work as before in pdf-viewer
> Update pdf embed API url

- libs/utils/utils.js
Before running martech a check for `window.marketingtech.adobe.launch` is done to see if it's already loaded.  With the new setup we also need a check for `window._satellite`
**Test URLs:**
- After: https://martechfix--milo--adobecom.hlx.page/?martech=off
> Personalization martech fix: also check for window._satellite presence

- libs/blocks/global-navigation/utilities/getUserEntitlements.js
- test/blocks/global-navigation/mocks/subscriptionsAll.js
- test/blocks/global-navigation/utilities/getUserEntitlements.test.js
* Added the `offers` field in the `entitlements` object. This field will hold the offer IDs and offers data, which will be used on Titans to form the URL for the switch plan flow.
Resolves: [MWPW-131607](https://jira.corp.adobe.com/browse/MWPW-131607)
**Test URLs:**
https://mwpw-131607-entitlements--milo--adobecom.hlx.page/?martech=off - link doesn't work, will add correct later
> MWPW-131607: Extend feds.entitlements with the offer ID

- libs/blocks/global-navigation/global-navigation.js
- test/blocks/global-navigation/test-utilities.js
With merging https://github.com/adobecom/milo/pull/874 the global navigation test suite doesn't seem to run anymore, as @meganthecoder mentioned [here](https://github.com/adobecom/milo/pull/910#issuecomment-1613886656).
This PR fixes the broken global navigation test suite.
You should still be able to log in and see the profile on both URLs.
**Test URLs:**
- Before: https://main--milo--adobecom.hlx.page/drafts/osahin/gnav-1?martech=off#
- After: https://gnav--milo--adobecom.hlx.page/drafts/osahin/gnav-1?martech=off#
> Fix global navigation tests

- libs/blocks/global-navigation/base.css
- libs/blocks/global-navigation/global-navigation.css
- libs/blocks/global-navigation/global-navigation.js
- libs/blocks/global-navigation/utilities/utilities.js
- test/blocks/global-navigation/global-navigation.test.js
- test/blocks/global-navigation/mocks/global-navigation-long.plain.js
- test/blocks/global-navigation/test-utilities.js
Certain Gnav consumers add a lot of navigation content despite [Consonant's recommendations](https://consonant.adobe.com/1975e5ba1/p/48adfd-navigation/b/815684):
> Global nav items | Use five items max.
There have been dozens of discussions on the topic over the past years, but a perfect solution was never found to satisfy marketing/content requirements, ease of authoring, UX and performance concerns.
This PR aims to 'squeeze' a few extra pixels from all navigation items when the content is overflowing the viewport. This does not cover all possible use-cases, but is a good compromise for the moment. If the content overflows, the logic will add a modifier which in turn will:
- remove the brand label;
- remove the (right side) logo entirely;
- lower paddings and font-sizes for all main …
> [MWPW-132444] Save up nav space when content is overflowing

- test/features/personalization/personalization.test.js
Remove unused imports in the personalization tests and the renamed `applyPers` function.
It seems like the test was written & then some refactorings have been made, hence let's skip the test until @chrischrischris has time to look at it properly
**Test URLs:**
- Before: https://main--milo--adobecom.hlx.live
- After: https://fix-pers-tests--milo--mokimo.hlx.live
> Skip personalization test for now

- libs/blocks/global-navigation/utilities/utilities.js
- test/blocks/global-navigation/utilities/utilities.test.js
Do not 404 for the feds placeholders on localhost on milo consuming projects and fetch global navigation placeholders always from https://main--milo--adobecom.hlx.page rather than localhost. 
Resolves: [MWPW-133443](https://jira.corp.adobe.com/browse/MWPW-133443)
**Test URLs:**
- Before: https://main--milo--adobecom.hlx.page/drafts/osahin/gnav-1?martech=off#
- After: https://MWPW-133443--milo--mokimo.hlx.page/drafts/osahin/gnav-1?martech=off#
> MWPW-133443: Fetch gnav placeholders from correct location

- libs/blocks/global-footer/global-footer.js
- libs/blocks/global-navigation/global-navigation.js
- libs/blocks/global-navigation/utilities/menu/menu.js
- libs/blocks/global-navigation/utilities/utilities.js
- test/blocks/global-navigation/global-navigation.test.js
- test/blocks/global-navigation/mocks/global-navigation-only-brand-no-image.plain.js
- test/blocks/global-navigation/mocks/subscriptionsAll.js
- test/blocks/global-navigation/test-utilities.js
- test/blocks/global-navigation/utilities/getUserEntitlements.test.js
- test/blocks/global-navigation/utilities/utilities.test.js
I would usually open this PR from my fork, but I got 404s when trying to use the https://branch--repo--owner.hlx.page approach. This branch will be deleted as soon as it is merged.
---
This aims to handle any gaps noticed while testing the FEDS Gnav on Blog. It:
- ensures the region picker dropdown is closed on outside click;
- adds a `No Logo` option to the 'Gnav Brand' and 'Adobe Logo' features. These blocks can now be authored to be just image, just text or both of them together;
- ensures that placeholders used in the global navigation documents are replaced. This was already in place for dropdown menus and the footer;
- provides an additional fallback (`imsClientId`) for the navigation experience name if one hasn't been explicitly defined.
There are still a few things required for a …
> [MWPW-132443] Gnav updates for Blog migration

- libs/blocks/global-navigation/global-navigation.css
- test/blocks/global-navigation/global-navigation.test.js
An edge case has been uncovered with the merge of https://github.com/adobecom/milo/pull/882 and https://github.com/adobecom/milo/pull/893 - if the brand block is label-only and the navigation contents are overflowing, then the brand label is hidden. This PR ensures that the brand label remains visible in such cases.
Resolves: [MWPW-132443](https://jira.corp.adobe.com/browse/MWPW-132443)
**Test URLs:**
- Before: https://main--milo--overmyheadandbody.hlx.page/drafts/ramuntea/blog-new-gnav?martech=off
- After: https://gnav-blog-enhancements--milo--overmyheadandbody.hlx.page/drafts/ramuntea/blog-new-gnav?martech=off
> [MWPW-132443] Visible brand label if no image exists

- libs/blocks/global-navigation/features/breadcrumbs/breadcrumbs.js
- test/blocks/global-navigation/features/breadcrumbs.test.js
- test/blocks/global-navigation/features/breadcrumbsFromFile.test.html
Change a breadcrumb metadata config to hide the current page by default
`breadcrumbs-hide-current-page: on/off (default: off)` to `breadcrumbs-show-current-page: on/off (default: off)` 
Resolves: [MWPW-117620](https://jira.corp.adobe.com/browse/MWPW-117620)
In the breadcrumbs just under the global navigation you should not see the page title as extra breadcrumb entry.
`What Is Claymation? How Clay Animation Works | Adobe` should be hidden by default.
**Test URLs:**
- Before: https://main--cc--adobecom.hlx.live/creativecloud/animation/discover/claymation
- After: https://main--cc--adobecom.hlx.live/creativecloud/animation/discover/claymation?milolibs=breadcrumbs-default-values--milo--mokimo
> Do not show current breadcrumb page by default

- libs/blocks/global-navigation/global-navigation.js
- libs/blocks/gnav/gnav.js
- libs/utils/utils.js
- test/blocks/global-navigation/global-navigation.test.js
- test/blocks/global-navigation/test-utilities.js
Refactor the milo core utils `loadIms` function so that any consumer can use the it as follows:
```js
loadIms()
.then(() => {}) // ims available and instance has loaded
.catch(() => {}) // error loading IMS and the instance is not ready
```
This is **NOT** a breaking change, as no consumer uses this [function yet]( https://github.com/search?q=org%3Aadobecom%20loadims&type=code)
This provides a more reliable way of knowing when IMS has finished loading and is ready to be used, especially when called from multiple places. (E.g. martech loads IMS, global-navigation loads IMS, consumer code loads IMS)
Observe the sign in button to exist afterwards in the global navigation
Resolves: [MWPW-133665](https://jira.corp.adobe.com/browse/MWPW-133665)
**Test URLs:**
- Before: …
> Ensure multiple places can load IMS from the milo utils

- libs/blocks/commerce/commerce.js
- libs/blocks/global-navigation/features/search/gnav-search.js
- libs/blocks/gnav/gnav.js
- libs/blocks/section-metadata/section-metadata.js
- libs/utils/action.js
- libs/utils/utils.js
- test/blocks/commerce/commerce.test.js
- test/blocks/section-metadata/section-meta.test.js
- test/utils/action.test.js
Refactors debounce away from utils as requested here https://github.com/adobecom/milo/pull/711 
Resolves: [MWPW-133591](https://jira.corp.adobe.com/browse/MWPW-133591)
Test URLs:
Test search at top right in new gnav (debounce should be working)
Before: https://main--milo--adobecom.hlx.page/drafts/vhargrave/empty-page?martech=off&hideGeorouting=on
After: https://vhargrave-remove-debounce-utils--milo--adobecom.hlx.page/drafts/vhargrave/empty-page?martech=off&hideGeorouting=on
Test search at top right in old gnav (debounce should be working)
Before: https://main--bacom--adobecom.hlx.page/?martech=off&hideGeorouting=on
After: https://main--bacom--adobecom.hlx.page/?milolibs=vhargrave-remove-debounce-utils&martech=off&hideGeorouting=on
Before: …
> Refactor debounce from utils

- libs/blocks/merch/merch.css
MWPW-132150 - Strikethrough prices text style fix 
* Fixes line-through style decoration for strikethrough prices generated from OST.
Resolves: [MWPW-132150](https://jira.corp.adobe.com/browse/MWPW-132150)
**Test URLs:**
- Before: https://main--cc--adobecom.hlx.page/drafts/fredw/ost-test
- After: https://main--cc--adobecom.hlx.page/drafts/fredw/ost-test?milolibs=Mwpw-132150
> MWPW-132150 - Strikethrough prices text style fix

- libs/blocks/quiz/utils.js
When processing an object containing question, result-primary and result-secondary values, a comparison was separating the two types of values by assuming questions started with a "q-" prefix. Unfortunately, we can't make that assumption. However, we can enforce the "result-" prefix for the other values, so I just turned the comparison on its head. 
Resolves: [MWPW-133738](https://jira.corp.adobe.com/browse/MWPW-133738)
**Test URLs:**
- Before: https://uar-integration--milo--adobecom.hlx.page/drafts/sabya/quiz-3/?martech=off&hideGeorouting=on
- After: https://mwpw-133738--milo--echampio-at-adobe.hlx.page/drafts/sabya/quiz-3/?martech=off&hideGeorouting=on
> MWPW-133738: Use a different comparison to process question values

- libs/blocks/quiz/utils.js
Adding logic to account for 3 types of rules - 
1. **compound** (which has more than one product that is grouped with `&`). Ex - `(ai,ai-edu,ai-bus,ai-ind)&(ai,ai-edu,ai-bus,ai-ind)`
2. **simple** (which has one exact product **or** multiple comma-separated single products). Ex. 
`(ai,ai-edu,ai-bus,ai-ind,au-edu)`
3. **default** (when no products match based on the user's selection)
URL to test the specific scenario based on the uber data set - https://uar-grouped-single-product--milo--sabyamon.hlx.page/drafts/delta/app-recommender-test/?martech=off&hideGeorouting=on
Resolves (Hopefully): https://jira.corp.adobe.com/browse/MWPW-133759
**Test URLs:**
- Before: https://uar-integration--milo--adobecom.hlx.page/drafts/sabya/quiz-3/?martech=off&hideGeorouting=on
- After: …
> MWPW-133759 - Adding logic to account for single products grouped together

- libs/blocks/caas/utils.js
- test/blocks/caas/utils.test.js
Use locale (ietf) from getConfig instead of from <html lang>.
Same type of change as #916. Needed to prevent adverse effects from https://github.com/adobecom/milo/pull/915. Discovered in https://github.com/adobecom/bacom/pull/130.
We want to maintain existing behavior for CaaS so I've left edge-cased lang/cntry split alone. I also tested using new locale values (lang/reg) but Chimera endpoint returns no cards when `country` parameter is `undefined` or unsupported, eg. new `la` value (419). This will have to be migrated later.
**Test URLs:**
- Before: https://main--milo--hparra.hlx.page/
- Before: https://main--bacom--adobecom.hlx.page/customer-success-stories?martech=off
- Before: https://main--bacom--adobecom.hlx.page/la/customer-success-stories?martech=off
- After: …
> Use locale from getConfig (caas)

- libs/blocks/global-navigation/features/breadcrumbs/breadcrumbs.js
- libs/blocks/global-navigation/global-navigation.css
- test/blocks/global-navigation/features/breadcrumbs-from-file.test.html
This solves two issues for breadcrumbs:
Each breadcrumb element would flow on multiple rows depending on available space. The logic has now been adapted to: 
- keep elements on just one row;
- allow scrolling if available space is exceeded;
- replace all but the first and last two breadcrumb elements with an ellipsis, if more than 3 breadcrumb elements are available. Similar behaviour is currently implemented on the AEM-based Global Navigation.
| <img width="418" alt="Before breadcrumb UI updates" src="https://github.com/adobecom/milo/assets/11267498/850923fa-63c9-4c00-8061-e1eb3e817d42"> | <img width="418" alt="After breadcrumb UI updates" src="https://github.com/adobecom/milo/assets/11267498/479b4af7-e2a2-4595-af33-102ba9f2411f"> |
If …
> [MWPW-133763] Long breadcrumbs UI

- libs/features/title-append/README.md
- libs/features/title-append/title-append.js
- libs/utils/utils.js
- test/features/title-append/mocks/head-social.html
- test/features/title-append/mocks/head.html
- test/features/title-append/title-append.test.js
- test/utils/mocks/head-title-append.html
- test/utils/utils.test.js
The title-append feature allows you to append an arbitrary string to an HTML document's title by populating a "title-append" column for any given row in [Franklin's bulk-metadata](https://www.hlx.live/docs/bulk-metadata). See README for more details.
Resolves: [MWPW-132671](https://jira.corp.adobe.com/browse/MWPW-132671)
**Test URLs:**
- Before: https://main--milo--hparra.hlx.page/drafts/hgpa/test/title-append/title-append?martech=off
- After: https://title-append--milo--hparra.hlx.page/drafts/hgpa/test/title-append/title-append?martech=off
Tip: You can see change happen in realtime -- open the "After" test URL in it own tab so you can see page title and refresh.
> Add title-append feature

- libs/martech/martech.js
DC Needs to load an alternative martech lib
Usage, in `/scipts.js`
```
local: { edgeConfigId: 'da46a629-be9b-40e5-8843-4b1ac848745c', marTechUrl: 'DC Needs This '},
```
Resolves: [MWPW-133942](https://jira.corp.adobe.com/browse/MWPW-133942)
**Test URLs:**
- After: https://mwpw-133942--milo--adobecom.hlx.page/?martech=off
> MWPW-133942 Consumer can change martech urls

- .github/workflows/enforce-labels.yml
- .github/workflows/run-tests.yaml
They seem unnecessary if you're just updating description of PR. Improve dev velocity just a bit and reduce noise.
Reference: https://docs.github.com/en/webhooks-and-events/webhooks/webhook-events-and-payloads?actionType=edited#pull_request
Actual test is editing this PR. Only `helix-psi-check` should need to rerun if body is edited.
**Test URLs:**
- After: https://hparra-patch-1--milo--adobecom.hlx.live/?martech=off
> Don't run UT or label checks if you edit PR title/body

- libs/utils/utils.js
Use "content-language" metadata value as highest priority option for html lang attribute. This allows `<html lang>` to be driven from metadata.xlsx and avoid coupling with `locales`. Named "content-language" because it is similar to adjacent "content-direction" feature. 
Resolves: [MWPW-133115](https://jira.corp.adobe.com/browse/MWPW-133115)
**Test URLs:**
- Before: https://main--milo--hparra.hlx.live/drafts/hgpa/test/content-language/content-language?martech=off
- After: https://lang-metadata--milo--hparra.hlx.live/drafts/hgpa/test/content-language/content-language?martech=off
> Use "content-language" metadata for html lang attribute

- libs/scripts/taxonomy.js
* Fixes issue with malformed link to topic pages on lang pages.
Context:
Taxonmy.js is set up to capture a link from the link column if one is provided in taxonomy.json. If a link is not provided it grabs the category name and creates a url to topic pages.
There is a bug where the link in taxonomy.json is not getting captured so the category name is being used to create a link to topic pages. 
When viewing a landing page out side of english (/ko/, /jp/, /de/, /fr/, /it/) the category name is in the respective language. This creates malformed links to any topic pages in that language, resulting in the link 404ing.
Resolves: [MWPW-129907](https://jira.corp.adobe.com/browse/MWPW-129907)
**Test URLs:**
- Before: …
> [Blog Migration] Topics URL 404s on lang pages

- libs/blocks/global-navigation/global-navigation.css
This is a slight style enhancement for the mobile breadcrumbs. It ensures:
- the ellipsis element has equal spacing on both desktop browsers in responsive view and actual devices when browsing on Firefox or Safari;
- the last breadcrumb has lateral space if the breadcrumbs section is scrollable.
| <img width="324" alt="Ellipsis spacing on FF - before" src="https://github.com/adobecom/milo/assets/11267498/5a534c15-9682-49cc-96c1-722aab7fc48c"> | <img width="324" alt="Ellipsis spacing on FF - after" src="https://github.com/adobecom/milo/assets/11267498/1c9075d6-0dad-4e53-a324-9df780097b13"> |
| <img width="324" alt="Last element spacing on FF - before" src="https://github.com/adobecom/milo/assets/11267498/7dcf99df-e7fd-407f-b425-40e6d8c7f6 …
> [MWPW-133763] Breadcrumbs mobile alignment

- libs/blocks/global-navigation/features/breadcrumbs/breadcrumbs.js
- libs/utils/utils.js
Ensure to show the breadcrumbs element if there is just a "base-breadcrumbs"
Resolves: [MWPW-134085](https://jira.corp.adobe.com/browse/MWPW-134085)
**Test URLs:**
- Before: - https://mwpw-134085--milo--mokimo.hlx.live/
- Before: https://main--bacom--adobecom.hlx.page/resources/leader-in-experiences-breadcrumb-in-url-test
- After: https://main--bacom--adobecom.hlx.page/resources/leader-in-experiences-breadcrumb-in-url-test?milolibs=mwpw-134085--milo--mokimo
> Make sure to always display the breadcrumbs when a base is set

- test/blocks/marquee/marquee.test.js
No details required.
Test URL:
- https://disablemediacredit--milo--adobecom.hlx.page/
> Disable failing media credit test until it can be fixed

- test/helpers/waitfor.js
- test/utils/utils.test.js
Fix my own flakey title-append test using `waitFor` introduced in #986.
Using an explicit delay is a last resort that we can avoid here.
**Test URLs:**
- Before: https://main--milo--hparra.hlx.live/?martech=off
- After: https://fix-title-append-flap--milo--hparra.hlx.live/?martech=off
> Fix flakey title-append test

- .eslintrc.js
- package-lock.json
- package.json
Addresses: [MWPW-134063](https://jira.corp.adobe.com/browse/MWPW-134063)
Only warn on cycles, ignore console in tests and add `npm run lint:js:nibble`.
We have some deep dependency cycles, but expecting others to fix these as part of their PR is too much -- they already exist and can be difficult to unravel. We warn instead of error.
Ignore `console` in tests. These are usually needed to test that an error was sent to LANA.
Add `npm run lint:js:nibble`
**Test URLs:**
- Before: https://main--milo--hparra.hlx.live/?martech=off
- After: https://chore-eslint-improve--milo--hparra.hlx.live/?martech=off
> Improve linting: only warn on cycles, ignore console in tests

- test/blocks/marquee/marquee.test.js
- test/blocks/marquee/mocks/body.html
Fixing the unit test for the Marquee block after introduction of element media credit types.
**Test URLs:**
- https://marquee-test-fix--milo--wbstry.hlx.live/
- Before: https://main--cc--adobecom.hlx.live/
- After: https://main--cc--adobecom.hlx.live/?milolibs=marquee-test-fix--milo--wbstry&martech=off
> feat(marquee): unit test fix

- test/blocks/bulk-publish/bulk-publish-utils.test.js
- test/scripts/scripts.test.js
- test/utils/loadLana.test.js
Moved the test into it's own file and call `loadLana` directly for testing.  When testing via scripts.test.js the lana test intermittently would fail.
**Test URLs:**
- https://loadlana--milo--adobecom.hlx.live/
> Fix loadLana test

- libs/blocks/aside/aside.css
- libs/blocks/table/table.css
* Aside buttons area currently add margin right to all 'a' tags and no right margin in last a tag. As a result when the screen size is previewed in responsive mode the buttons stack on a smaller screen size. The stacked buttons have no spacing.
* Converting the action-area container into a flex container to add a gap of spacing-s between elements and allow flex wrap. With this change if the buttons wrap to next line they will also have a top gap of spacing-s and will not stack without any space.
Screenshots without change
Screenshots with change
Resolves: [MWPW-133028](https://jira.corp.adobe.com/browse/MWPW-133028)
**Test URLs:**
- Before: https://main--milo--adobecom.hlx.page/drafts/mathuria/aside/mwpw-133028?martech=off
- After: …
> MWPW-133028 | Making aside button action area a flex container

- libs/blocks/modal/modal.js
- libs/features/georoutingv2/georoutingv2.js
* Add analytics tracking for:
Modal close
Geourouting load
On click of link on georouting pop up when selecting country other than your region (Visiting jp page from US and selecting JP from georouting modal)
All above events have been added to make it same as we see right now on dexter pages as per discussion with analytics team
Resolves: [MWPW-134229](https://jira.corp.adobe.com/browse/MWPW-134229)
**Test URLs:**
To verify georouting
- Before: https://modal-analytics--milo--adobecom.hlx.page/de/
- After: https://modal-analytics--milo--ruchika4.hlx.page/de/
To verify tracking on close for other modal (Click on Learn More button to open the modal):
- Before: https://modal-analytics--milo--adobecom.hlx.page/drafts/ruchika/iframe
- After: …
> Modal analytics

- libs/blocks/global-navigation/features/breadcrumbs/breadcrumbs.js
- test/blocks/global-navigation/features/breadcrumbs.test.js
The breadcrumbs has a few different configuration options, for this PR important 
- `breadcrumbs-show-current-page` shows the current page as last entry in the breadcrumb
- `breadcrumbs-page-title` alters the title for the last entry in the breadcrumb
Currently BOTH are required to be authored for the `breadcrumbs-page-title` to show up, as per default `breadcrumbs-show-current-page` is OFF. The default exists as otherwise other consumers would have multiple "last entries" in their breadcrumbs.
We should be able to safely assume that IF a `breadcrumbs-page-title` has been authored, the authors want that to show up - otherwise they would just not author it.
- Authored `breadcrumbs-page-title` should always show up when it has been authored.
Resolves: …
> mwpw-134306: always show authored breadcrumbs-page-title

- libs/blocks/global-navigation/global-navigation.js
We currently don't support the app launcher and removed the placeholder function here https://github.com/adobecom/milo/pull/1015/files
This rightfully pops up in the lana logs, no error is seen in the console as it's caught and logged to lana only.
**Test URLs:**
Before: https://main--milo--adobecom.hlx.page?martech=off
After: https://fix-undefined-error--milo--mokimo.hlx.page?martech=off
> [Global-navigation] Fix an undefined error 

- libs/blocks/merch/merch.js
- test/blocks/merch/merch.test.js
Switch Milo to only use 'wcs.adobe.com'.
'wcs.stage.adobe.com' should only be to test experimental features provided by the commerce team.
Resolves: [MWPW-134309](https://jira.corp.adobe.com/browse/MWPW-134309)
**Test URLs:**
- Before: [https://main--milo--adobecom.hlx.live/drafts/ilyas/merch?martech=off](https://main--milo--adobecom.hlx.live/drafts/ilyas/merch?martech=off)
- After: [https://mwpw-134309-wcs--milo--3ch023.hlx.page/drafts/ilyas/merch?martech=off](https://mwpw-134309-wcs--milo--3ch023.hlx.page/drafts/ilyas/merch?martech=off)
> MWPW-134309: Milo to always use Prod WCS

- libs/blocks/aside/aside.css
Medium center notification button are not center aligned. 
Adding the explicit center aligning for button section in notification center
Resolves: [MWPW-134424](https://jira.corp.adobe.com/browse/MWPW-134424)
**Test URLs:**
- Before: https://main--milo--adobecom.hlx.page/drafts/mathuria/aside/aside?martech=off
- After: https://notccenter--milo--aishwaryamathuria.hlx.page/drafts/mathuria/aside/aside?martech=off
> MWPW-134424 | Center notification buttons are not center aligned

- libs/blocks/modal/modal.js
- libs/features/georoutingv2/georoutingv2.js
* Add analytics tracking for:
Modal close
Geourouting load
On click of link on georouting pop up when selecting country other than your region (Visiting jp page from US and selecting JP from georouting modal)
All above events have been added to make it same as we see right now on dexter pages as per discussion with analytics team
Resolves: [MWPW-134229](https://jira.corp.adobe.com/browse/MWPW-134229)
[MWPW-134229](https://jira.corp.adobe.com/browse/MWPW-130145)
**Test URLs:**
To verify georouting
- Before: https://modal-analytics--milo--adobecom.hlx.page/de/
- After: https://modal-analytics--milo--ruchika4.hlx.page/de/
To verify tracking on close for other modal (Click on Learn More button to open the modal):
- Before: https://modal-analytics--milo--adobecom.hlx.page/drafts/ruchika/iframe …
> Add analytics tracking to modal

- libs/blocks/modal/modal.css
- libs/blocks/modal/modal.js
- libs/styles/iframe.css
- test/blocks/modals/mocks/body.html
- test/blocks/modals/modals.test.js
* iframe window opened in mobile view is too small , not able to see the complete details to do the payment flow.
Resolves: [MWPW-133983](https://jira.corp.adobe.com/browse/MWPW-133983)
**Test URLs:**
- Before: https://stage--cc--adobecom.hlx.page/drafts/ruchika/discover1?martech=off#animate
- After: https://stage--cc--adobecom.hlx.page/drafts/ruchika/discover1?martech=off&milolibs=MWPW-133983--milo--sharath-kannan#animate
This is how the modal should look after the PR merge.
> iframe window opened in mobile view is too small 

- libs/blocks/tag-selector/tag-selector.css
- libs/ui/controls/tagSelector.css
* Removes appearance, adds border, adjusts position of button to standardize ui across browsers
Resolves: [MWPW-133747](https://jira.corp.adobe.com/browse/MWPW-133747)
**Test URLs:**
- Before: https://main--milo--adobecom.hlx.page/tools/tag-selector?martech=off
- After: https://mwpw-133747-tag-selector-style--milo--adobecom.hlx.page/tools/tag-selector?martech=off
> MWPW-133747 Tag Selector Safari Style

- libs/utils/utils.js
- test/utils/utils.test.js
Currently RTL attribute is added for RTL regional file, but not for its langstore file.
This adds the RTL attribute for langstore file for RTL regions. One of the region from [locale config](https://github.com/adobecom/milo/blob/main/libs/scripts/scripts.js#L22) with same `lang` is checked for language's dir property.
Resolves: [MWPW-132883](https://jira.corp.adobe.com/browse/MWPW-132883)
**Test URLs:**
RTL langstore:
- Before: https://main--milo--adobecom.hlx.page/langstore/ar/drafts/nishantkaush/direction-issues/rtl-issue?martech=off
- After: https://mwpw-132883--milo--nishantka.hlx.page/langstore/ar/drafts/nishantkaush/direction-issues/rtl-issue?martech=off
LTR langstore: (unchanged)
- Before: https://main--milo--adobecom.hlx.page/langstore/en/drafts/nishantkaush/direction-issues/rtl-is …
> MWPW-132883: Add RTL attribute for RTL region's langstore file

- libs/blocks/global-navigation/features/breadcrumbs/breadcrumbs.js
- test/blocks/global-navigation/features/breadcrumbs.test.js
Breadcrumb links are currently not localised - but they should be.
Resolves: [MWPW-134457](https://jira.corp.adobe.com/browse/MWPW-134457)
**Before**
**After** 
**Test URLs:**
- Before: - https://internationalize-breadcrumbs--milo--mokimo.hlx.live?martech=off
- Before: https://main--bacom--adobecom.hlx.live/jp/customer-success-stories?headerqa=global-navigation
- After: https://main--bacom--adobecom.hlx.live/jp/customer-success-stories?headerqa=global-navigation&milolibs=internationalize-breadcrumbs--milo--mokimo
> [Global-navigation] Localise breadcrumb links

- libs/blocks/section-metadata/section-metadata.js
- libs/utils/action.js
* addresses as few eslint warnings showing up in the `section-metadata.js` & `action.js` files
Resolves: NA
Before
After
**Test URLs:**
This update is all code format, there will be no difference between these before/after urls. 
- Before BG image test: https://main--milo--adobecom.hlx.page/drafts/suhjain/background-image-test?martech=off
- After BG image test: https://rparrish-section-lint--milo--adobecom.hlx.page/drafts/suhjain/background-image-test?martech=off
- Before sticky: https://main--milo--adobecom.hlx.page/drafts/rclayton/poc/sticky?martech=off
- After sticky: https://rparrish-section-lint--milo--adobecom.hlx.page/drafts/rclayton/poc/sticky?martech=off
> ES lint fixes for section metadata and actions files

- libs/blocks/global-navigation/utilities/menu/menu.css
This spaces out consecutive sections in the full width dropdown menu columns to provide a visual representation of context separation. The `12px` value has been taken from how content producers authored the current AEM-based Gnav on production.
Screenshots:
| <img width="1460" alt="No section gap" src="https://github.com/adobecom/milo/assets/11267498/dbb34164-e471-409d-956c-f30526883bce"> | <img width="1460" alt="Section gap" src="https://github.com/adobecom/milo/assets/11267498/e78e596c-4ebd-4450-80b2-8305d3765c22"> |
Resolves: [MWPW-134624](https://jira.corp.adobe.com/browse/MWPW-134624)
**Test URLs:**
- Before: https://main--milo--overmyheadandbody.hlx.page/drafts/ramuntea/gnav-refactor?martech=off
- After: …
> [MWPW-134624] Space out column sections in GNAV full-width dropdown

- libs/utils/utils.js
- test/utils/imageLinks.test.js
- test/utils/mocks/image-links.html
* If there is an image in Milo with alt text having '|' it is replaced with an a tag and the image element is added inside the a tag. The a tag is then added to the end of the parent element of image. This removes the image from its initial position in the parent element and adds it to the end of the container.
* The change in the PR replaces the image in place. The a tag is added before the image and then the image is shifted inside the 'a' tag keeping the image position same.
Resolves: [MWPW-134057](https://jira.corp.adobe.com/browse/MWPW-134057)
**Test URLs:**
- Before: https://main--milo--adobecom.hlx.page/drafts/mathuria/mwpw-134057?martech=off
- After: https://miloimglnk--milo--aishwaryamathuria.hlx.page/drafts/mathuria/mwpw-134057?martech=off
> MWPW-134057 | Replace image links in place

- libs/blocks/marketo/marketo.css
* Adds a wildcard class selector to fix privacy language widths on Marketo forms
* Classnames coming from forms change when countries are selected
Resolves: [MWPW-134429](https://jira.corp.adobe.com/browse/MWPW-134429)
**Test URLs:**
- Before: https://main--milo--jasonhowellslavin.hlx.page/drafts/slavin/bacom-pages/state-of-marketing-automation-b?martech=off
- After: https://mwpw-134429-mkto-privacy-msg--milo--jasonhowellslavin.hlx.page/drafts/slavin/bacom-pages/state-of-marketing-automation-b?martech=off
> [MWPW-134429] Marketo form privacy language width

- .github/workflows/dispatch.yml
* It creates a workflow dispatch to DC repo when there is a change to main
* DC repo will trigger necessary tests to ensure the change in Milo doesn't break DC pages
* Will add PRs later when shift-left is needed
* Other consuming teams can add their dispatches to jobs
Resolves: [MWPW-134543](https://jira.corp.adobe.com/browse/MWPW-134543)
**Test URLs:**
- N/A
> [Workflow] MWPW-134543 Dispatch DC workflow when main is changed

- libs/features/personalization/personalization.js
- libs/martech/martech.js
If a page has the mep parameter, the MEP button should show.  This was not happening if the following conditions were both true:
* Target was on
* There were no manifests
If there were manifests or Target was off, the button properly showed.
**Test URLs:**
- Before: https://main--homepage--adobecom.hlx.page/?mep
- After: https://main--homepage--adobecom.hlx.page/?milolibs=mep-button-on-target-only&mep
> Mep button on target only

- libs/blocks/tag-selector/tag-selector.css
- libs/blocks/tag-selector/tag-selector.js
- libs/ui/controls/TagSelectPicker.js
- libs/utils/utils.js
- test/blocks/tag-selector/tag-selector.test.js
- test/blocks/tag-selector/taxonomy.js
* Allow consumers to create their own Tag Selector with custom tags.
* Add tag groups by appending the name and URL to the tag selector block.
* See: https://main--milo--adobecom.hlx.page/drafts/docs/authoring/tag-selector
Resolves: [MWPW-130312](https://jira.corp.adobe.com/browse/MWPW-130312)
**Test URLs:**
- Before: https://main--milo--adobecom.hlx.page/tools/tag-selector?martech=off
- After: https://bmarshal-consumer-tags--milo--adobecom.hlx.page/tools/tag-selector?martech=off
- Before: https://main--milo--adobecom.hlx.page/tools/caas?martech=off
- After: https://bmarshal-consumer-tags--milo--adobecom.hlx.page/tools/caas?martech=off
**BACOM URLS**
- Before: https://main--bacom--adobecom.hlx.page/tools/tag-selector?martech=off
- After: …
> MWPW-130312 Adding Consumer Tags to Tag Selector

- libs/blocks/global-navigation/global-navigation.js
- test/blocks/global-navigation/global-navigation.test.js
Clicking the `Adobe Account` or Sign in dropdown link should work regardless of the author typing `https://www.adobe.com/?sign-in=true` or `https://www.adobe.com?sign-in=true` ... links might also be influenced when having a `.html` extension or not - hence we want to relax the check for how we connect a sign in button to adobeIms a bit.
Resolves: [MWPW-134874](https://jira.corp.adobe.com/browse/MWPW-134874)
1. Click "Sign in"
2. Click "Adobe Account"
Before: Does not try to sign you in with IMS
After: Tries to sign you in with IMS
**Test URLs:**
- Before: https://main--milo--adobecom.hlx.page/drafts/osahin/prs/mwpw-134874?martech=off
- After: https://mwpw-134874--milo--mokimo.hlx.page/drafts/osahin/prs/mwpw-134874?martech=off
- Before: …
> Relax global navigation sign profile dropdown in check

- libs/blocks/global-navigation/global-navigation.css
- libs/blocks/global-navigation/global-navigation.js
- test/blocks/global-navigation/keyboard/mocks/global-nav-mobile.html
- test/blocks/global-navigation/keyboard/mocks/global-nav.html
When multiple sections/cloud menus are added to the top navigation, the border between elements should be removed.
Simplest way to do this is by using `:only-of-type`, which checks whether a particular tag has just one occurrence in the context of its parent. Since we were calling cloud menus 'section' menus anyway, it made sense to use a `section` tag for this scenario.
I initially removed the `feds-navItem--section` modifier class and switched styles from `.feds-navItem--section` to `section.feds-navItem`, which worked well, but in the end I decided against increasing specificity and tag lookups.
Resolves: [MWPW-134805](https://jira.corp.adobe.com/browse/MWPW-134805)
**Test URLs:**
- Before: https://main--milo--overmyheadandbody.hlx.page/drafts/ramuntea/multiple-clouds?martech=off
- …
> [MWPW-134805] Remove borders when more sections are used

- libs/blocks/table/table.css
**Test URLs:**
- Before: https://main--milo--adobecom.hlx.page/docs/authoring/tables?martech=off
- After: https://table-merch-borader--milo--adobecom.hlx.page/docs/authoring/tables?martech=off
This will fix the issue of the border on text for merch table.
> Merch Table: Fixing the double border and border on cell's text.

- libs/blocks/text/text.css
* The `<hr/>` shorthand in text blocks (`---`) produces a horizontal rule that doesn't quite match Consonant designs. This PR fixes that.
Resolves: [MWPW-131690](https://jira.corp.adobe.com/browse/MWPW-131690)
**Test URLs:**
- Before: https://main--milo--adobecom.hlx.page/drafts/ebartholomew/text-block-hr?martech=off
- After: https://ebartholomew-hr-style-tweak--milo--adobecom.hlx.page/drafts/ebartholomew/text-block-hr?martech=off
> [MWPW-131690] Update horizontal rule styles within text blocks

- .github/workflows/dispatch.yml
Add conditional to prevent this workflow from running and failing on forks.
**Test URLs:**
- Before: https://main--milo--hparra.hlx.live/?martech=off
- After: https://chore-workflow-dispatch-fix--milo--hparra.hlx.live/?martech=off
**References:**
- https://docs.github.com/en/actions/using-jobs/using-conditions-to-control-job-execution
> Run dispatch workflow only for adobecom/milo

- libs/blocks/section-metadata/section-metadata.css
When the spacing variants were added to the section metadata the xxs size was missed. Adding it as an option for block spacing.
Resolves: [MWPW-134481](https://jira.corp.adobe.com/browse/MWPW-134481)
**Test URLs:**
- Before: https://main--milo--adobecom.hlx.page/drafts/klee/doc-test/text?martech=off
- After: https://sarchibeque-section-spacing--milo--adobecom.hlx.page/drafts/klee/doc-test/text?martech=off
> MWPW-134481 - Add section xxs spacing variant

- libs/blocks/quiz-results/quiz-results.js
* Removed a querySelectorAll
* Removed iteration through metadata divs
* Added lana logging if the block has been misconfigured and doesn't implement a proper variant
Resolves: [MWPW-135198](https://jira.corp.adobe.com/browse/MWPW-135198)
**Test URLs:**
- Before: https://uar-integration--milo--adobecom.hlx.page/drafts/colloyd/quiz-results-block/quiz-results?quizKey=cc-quiz-result&debug=quiz-results&martech=off
- After: https://mwpw-135198-quiz-results-dom-optimization--milo--colloyd.hlx.page/drafts/colloyd/quiz-results-block/quiz-results?quizKey=cc-quiz-result&debug=quiz-results&martech=off
To properly test this, hit the test url and open dev tools. Add the 'cc-quiz-result' key to Local Storage and set the value to this:
{"primaryProducts":["lr","pr"],"secondaryProducts":["ps","au"],"umbre …
> MWPW-135198 - Optimizes quiz-results DOM handling

- libs/blocks/global-navigation/global-navigation.js
Do not lana log IMS timeouts as we can't fix those and they unnecessarily pollute our lana logs [MWPW-134861](https://jira.corp.adobe.com/browse/MWPW-134861)
Instead we want to ensure we try to show the sign in/profile button even if the initial `loadIms()` call was rejected if it eventually loads.
**Test URLs:**
- Before: https://main--milo--adobecom.hlx.page/drafts/ramuntea/gnav-refactor?martech=off#
- After: https://reduce-gnav-lana-logs--milo--mokimo.hlx.page/drafts/ramuntea/gnav-refactor?martech=off#
> Do not lana log IMS timeouts for the global nav

- libs/features/personalization/preview.js
* Add if condition inside mep function addMarkerData to avoid error on empty value
**Test URLs:**
- Before: https://main--milo--adobecom.hlx.page/drafts/cpeyer/pers/pers-demo
- After: https://mep-add-marker-data-fix--milo--adobecom.hlx.page/drafts/cpeyer/pers/pers-demo
> mep-add-marker-data-fix

- libs/blocks/marquee/marquee.js
- libs/blocks/video/video.js
- libs/utils/decorate.js
Selector was looking for video links that end in .mp4, but if any hash was appended to video link then it would not match.
Changed selector to `*=` which will match any part of the string
This also adds support for `autoplay1` for marquee background videos (used to always loop).
Resolves: [MWPW-135276](https://jira.corp.adobe.com/browse/MWPW-135276)
**Test URLs:**
- Before: https://main--milo--adobecom.hlx.page/drafts/rclayton/poc/video-samples?martech=off
- After: https://videofix--milo--adobecom.hlx.page/drafts/rclayton/poc/video-samples?martech=off
> MWPW-135276 Fix video selector

- libs/utils/decorate.js
* Add optional chaining operator for hoverplay has value
Resolves: [MWPW-129910](https://jira.corp.adobe.com/browse/MWPW-129910)
**Test URLs:**
- Before: https://main--milo--adobecom.hlx.page/drafts/ruchika/marquee1/?martech=off
- After: https://video--milo--adobecom.hlx.page/drafts/ruchika/marquee1/?martech=off
> add optional chaining operator to get hash value for hoverplay

- libs/features/seotech/README.md
- libs/features/seotech/seotech.js
- libs/utils/utils.js
- test/features/seotech/seotech.test.js
Add support for `seotech-structured-data` feature. We refactor existing support for `seotech-video-url` and add new tests and make improvements to existing ones.
Resolves: [MWPW-133754](https://jira.corp.adobe.com/browse/MWPW-133754)
**Test URLs:**
- Before: https://milo.adobe.com/drafts/hgpa/test/seotech-structured-data/structured-data?martech=off&seotech-sheet-url=https://milo.adobe.com/drafts/hgpa/test/seotech-structured-data/structured-data.json
- After: https://seotech-structured-data--milo--hparra.hlx.live/drafts/hgpa/test/seotech-structured-data/structured-data?martech=off&seotech-sheet-url=https://milo.adobe.com/drafts/hgpa/test/seotech-structured-data/structured-data.json
**Validation:**
The following should return a `FAQPage` JSON-LD object:
```js …
```
> MWPW-133754 - Support structured data API for SEO

- libs/blocks/marquee-anchors/marquee-anchors.js
* The interlinks in marquee anchor block have been fixed by editing the url in anchor tag
* Specific
Resolves: [MWPW-135282](https://jira.corp.adobe.com/browse/MWPW-135282)
**Test URLs:**
- Before: https://main--milo--adobecom.hlx.page/drafts/Soujanya/marqueeanchor-18?martech=off
- After: https://mwpw-135282--milo--sharath-kannan.hlx.page/drafts/Soujanya/marqueeanchor-18?martech=off
> interlinks in marquee anchor block fixed

- libs/blocks/aside/aside.css
* Fix mobile spacing for Aside block, inline variant
Resolves: [MWPW-134677](https://jira.corp.adobe.com/browse/MWPW-134677)
**Test URLs:**
- Before: https://main--milo--adobecom.hlx.page/docs/library/blocks/aside?martech=off
- After: https://methomas-aside-mobile--milo--adobecom.hlx.page/docs/library/blocks/aside?martech=off
Bacom:
- Before: https://main--bacom--adobecom.hlx.page/products/analytics/learning-resources?martech=off
- After: https://main--bacom--adobecom.hlx.page/products/analytics/learning-resources?milolibs=methomas-aside-mobile&martech=off
> MWPW-134677 Fix aside mobile spacing

- libs/utils/utils.js
- test/utils/mocks/body.html
- test/utils/mocks/useDotHtml.html
- test/utils/utils.test.js
Consumer projects can now set `config.useDotHtml = true` to force using .html on all pages for that project.
Resolves: [MWPW-135447](https://jira.corp.adobe.com/browse/MWPW-135447)
**Test URLs:**
Bacom link with working .html links: https://usedothtml--bacom--adobecom.hlx.page/?milolibs=homehtml&martech=off
- After: https://homehtml--milo--adobecom.hlx.page/?martech=off
> MWPW-135447 Add useDotHtml in config to force .html links

- libs/utils/utils.js
Adding both action-item and action-scroller blocks to the `/utils/utils.js` file for consumers.
**Test URLs:**
- Before: https://main--bacom--adobecom.hlx.page/?martech=off
- After: https://main--bacom--adobecom.hlx.page/?martech=off&milolibs=sarchibeque-actions-inlib
> Action Blocks added to config for consumers

- libs/features/personalization/add-preview-to-config.js
- libs/utils/utils.js
`addPreviewToConfig` should only run when either:
1. the `mep` param is added to url
2. We are not on prod and target or MEP is activated for the page
Resolves: No Jira Ticket
**Test URLs:**
- After: https://meppreview--milo--adobecom.hlx.page/?martech=off
> Only run when MEP or MEP param is enabled

- libs/blocks/caas/caas.css
Removes temporary CSS code for Card-Logo from CAAS Configurator
Resolves: [MWPW-135200](https://jira.corp.adobe.com/browse/MWPW-135200)
**Test URLs:**
- Before: https://main--milo--adobecom.hlx.page/tools/caas
- After: https://mwpw-135200--milo--adobecom.hlx.page/tools/caas
> Removes temporary CSS code for Card-Logo from CAAS Configurator

- libs/blocks/global-navigation/global-navigation.css
- libs/features/google-login.js
- libs/scripts/delayed.js
- libs/utils/utils.js
- test/features/google-login/google-login.test.js
- test/features/google-login/mocks/google-login.html
- test/scripts/delayed.test.js
Implement Google Yolo (you only login once) in Milo. The feature will be enabled only if `google-login` metadata is set to `on`. Google scripts are loaded from `delayed.js` to ensure there's no impact on performance.
An additional parameter can be used to specify a redirect page after a successful login.
For security reasons the Google web application is allowed to render the dropdown and exchange tokens in IMS only on certain origins, wildcards are not supported. If you want to test the Google Yolo implementation in your project and your origin is not allowed, please reach out to @narcis-radu, @overmyheadandbody, @mokimo. 
The Google web application will throw an error if the origin is not allowed.
```html
[GSI_LOGGER]: The given origin is not allowed for the given client ID.
```
The …
> Add support for Google Yolo

- libs/martech/attributes.js
* Remove extra spacing and new lines added to analytics tracking attribute value
Resolves: [MWPW-135652](https://jira.corp.adobe.com/browse/MWPW-135652)
**Test URLs:**
Milo
- Before: https://main--milo--adobecom.hlx.page/drafts/ruchika/accordion?martech=off
- After: https://accordion-analytics--milo--ruchika4.hlx.page/drafts/ruchika/accordion?martech=off
CC
- Before: https://main--cc--adobecom.hlx.page/creativecloud/file-types/image/raster/dwf-file
- After: https://main--cc--adobecom.hlx.page/creativecloud/file-types/image/raster/dwf-file?milolibs=accordion-analytics--milo--ruchika4
Note: To test go to accordion on the page and click on + sign to expand the accordion. In network tab search for /ee to see the analytics value.
> Remove extra spaces and new lines from tracking attribute values

- tools/floodgate/index.html
- tools/floodgate/js/floodgate.js
- tools/floodgate/js/ui.js
When the user clicks on the "Delete" button on the FG admin page:
-   Deletes temp folder within root FG project folder (milo-pink)
-   Updates the status of the Delete in the XLSX file
-   Display the deleted status in the FG admin page
Resolves: MWPW-134726 (https://jira.corp.adobe.com/browse/MWPW-134726)
> MWPW-134726: Delete functionality in Floodgate

- libs/blocks/global-navigation/global-navigation.css
This addresses an issue in Safari well elements nested inside parents that have `position: sticky;` might have their `z-index` property disregarded.
Resolves: [MWPW-135717](https://jira.corp.adobe.com/browse/MWPW-135717)
**Test URLs:**
- Before: https://main--milo--overmyheadandbody.hlx.page/drafts/ramuntea/gnav-refactor?martech=off
- After: https://dropdown-visibility--milo--overmyheadandbody.hlx.page/drafts/ramuntea/gnav-refactor?martech=off
**Consumer Test URLs:**
- Before: https://main--bacom--adobecom.hlx.page/products/product-analytics/pricing
- After: https://main--bacom--adobecom.hlx.page/products/product-analytics/pricing?milolibs=dropdown-visibility--milo--overmyheadandbody
> [MWPW-135717] Ensure dropdowns are visible on Safari

- libs/blocks/marquee/marquee.js
The marquee is loading section-metadata.js even when the `textContent` is just whitespace.
**Test URLs:**
- After: https://marqueefocalfix--milo--adobecom.hlx.page/?martech=off
> Marquee: Make sure there's actually text before loading handleFocalPoint

- libs/blocks/global-navigation/features/profile/dropdown.css
- libs/blocks/global-navigation/global-navigation.css
With the latest release of Safari, there are issues with elements' position on the z axis, regardless of their `z-index` value, when `overflow: clip` and/or `position: sticky` are used. Activating hardware acceleration via the `transform` property solves the issue.
Resolves: [MWPW-135765](https://jira.corp.adobe.com/browse/MWPW-135765), [MWPW-135766](https://jira.corp.adobe.com/browse/MWPW-135766)
**Test URLs:**
- Before: https://main--milo--overmyheadandbody.hlx.page/drafts/ramuntea/gnav-refactor?martech=off
- After: https://profile-dropdown-visibility--milo--overmyheadandbody.hlx.page/drafts/ramuntea/gnav-refactor?martech=off
> [MWPW-135765] Visibility of Gnav absolute elements in Safari

- libs/blocks/faas/faas.css
The faas link would sometimes show because autoblocking code had not finished.
Resolves: [MWPW-135787](https://jira.corp.adobe.com/browse/MWPW-135787)
**Test URLs:**
- After: https://hidefaaslink--milo--adobecom.hlx.page/?martech=off
> MWPW-135787 Hide faas link before it's autoblocked

- libs/blocks/quiz/utils.js
With the existing logic, the rows were getting traversed and on the way, the secondary products were matched.
Hence, if the product code is defined in a different order in result resources compared to the product codes array, the fragments are picked in that order.
With this PR, we will be traversing the product array first and will match that with every result resource row.
It's obviously less performant as for each entry in the product code array (which is very small in size), we will be iterating all the rows of the result resources (which is relatively a much bigger array). But, this is a tradeoff we will have to bear to maintain the matched product code order.
Note - This does not fix the order for basic fragments for more than one primary product without an umbrella product. …
> MWPW-134986 - Rendering nested fragments in the order of products

- libs/blocks/global-footer/global-footer.js
- libs/blocks/global-navigation/base.css
- libs/blocks/global-navigation/features/breadcrumbs/breadcrumbs.js
- libs/blocks/global-navigation/global-navigation.js
- libs/blocks/global-navigation/utilities/menu/menu.js
- libs/blocks/global-navigation/utilities/utilities.js
- test/blocks/global-navigation/features/breadcrumbs.test.js
- test/blocks/global-navigation/global-navigation.test.js
- test/blocks/global-navigation/mocks/global-navigation-long.plain.js
- test/blocks/global-navigation/mocks/global-navigation-only-brand-no-image.plain.js
- test/blocks/global-navigation/mocks/global-navigation-only-brand.plain.js
- test/blocks/global-navigation/mocks/global-navigation-only-non-svg-brand.plain.js
- test/blocks/global-navigation/mocks/global-navigation.plain.js
- test/blocks/global-navigation/mocks/large-menu.plain.html
- test/blocks/global-navigation/test-utilities.js
- test/blocks/global-navigation/utilities/utilities.test.js
This PR aims to better follow Milo patterns for link handling in Gnav, to allow authors to use `#_blank`, `#_dnt`, etc. in a consistent way and to ensure all links are localised properly and receive the `.html` extension if needed.
Some additional notes:
- for the footer, `decorateLinks` was called after our decoration logic, we're now calling it before, to follow the same pattern as the (updated) Gnav logic. This causes two loose ends, for which we're opening a follow-up story to address as soon as there is bandwidth (https://jira.corp.adobe.com/browse/MWPW-135656);
- social links in the footer now receive a `target="_blank"` attribute, as these links always lead outside of adobe.com pages;
- dropdown triggers have been transformed into buttons. These shouldn't count towards analytics …
> [MWPW-135217] Use decorateLinks before decorating Gnav

- libs/blocks/quiz/quizoption.js
* The h3 element in the card template in quizoptions.js contains an id that's hardcoded to a lorem ipsum value. It leads to duplicate id warnings in an accessibility checker and should be removed.
Resolves: https://jira.corp.adobe.com/browse/MWPW-134823
**Test URLs:**
- Before: https://uar-integration--milo--adobecom.hlx.page/drafts/borges/end-to-end/?martech=off
- After: https://quiz-cleanup-lorems--milo--elaineskpt.hlx.page/drafts/borges/end-to-end/?martech=off
> MWPW-134823 - QUIZ - Fix Acessibility warning

- libs/blocks/text/text.css
- libs/utils/decorate.js
Applies default body styles to content in blocks that use `decorateBlockText` when no formatting is applied in document. Which supports ability to apply text block style overrides on plain text in the `text` block. Also removes margin in text block for body elements that are an only child.
Resolves: [MWPW-134907](https://jira.corp.adobe.com/browse/MWPW-134907)
**Test URLs:**
- Before: https://main--milo--adobecom.hlx.page/drafts/sarchibeque/format-text?martech=off
- After: https://sarchibeque-mwpw-134907-text-overrides--milo--adobecom.hlx.page/drafts/sarchibeque/format-text?martech=off
> MWPW-134907 - decorate plain text in text block

- tools/loc/rollout.js
Resolves: [MWPW-135645](https://jira.corp.adobe.com/browse/MWPW-135645)
The image label is set as per order of image in the document. So, when an image is added/removed from any section, it changes the label for all the images below it. Hence, the label can be reset in the mdast which is used to generate the docx. The markdown (from docx) generated with and without label in mdast is identical.
[md-without-label](https://main--milo--adobecom.hlx.page/ae_en/drafts/nishantkaush/samples/image-issue/without-label.md)
[md-with-label](https://main--milo--adobecom.hlx.page/ae_en/drafts/nishantkaush/samples/image-issue/with-image-label.md)
After removing 1st image in the doc:
Docx Before (other sections with images shown with track changes): …
> MWPW-135645: remove image label from mdast

- tools/loc/config.js
- tools/loc/sharepoint.js
In the CC folder, whenever "Update Fragments" was clicked, it was expected that the fragments from the documents would be extracted and added to the excel workbook. However, earlier the following error was observed "Fragments found, but failed to update excel. Please try again" and the fragments were not getting added to the excel sheet. 
This PR addresses the above issue by making the necessary configuration changes for folders other than "Milo". Initially the code was written to handle "Update Fragments" only for Milo folder (which is the default folder). With this change, it can handle the functionality for folders other than "Milo" (including CC folder where the issue was first identified).
Resolves: MWPW-134576 (https://jira.corp.adobe.com/browse/MWPW-134576)
**Test URLs:** …
> MWPW-134576: Fixing update fragments in CC folder

- libs/features/personalization/personalization.js
When a line contains a template literal that ends with a $:
`` `^${pattern}$` ``
Chrome devtools will show all the code after this literal as being part of a string literal:
Adding an end-of-line comment that ends in a backtick fixes it:
This is the only relevant chrome bug I could find:
https://bugs.chromium.org/p/chromium/issues/detail?id=659515
Resolves: N/A
**Test URLs:**
- After: https://devtoolssucks--milo--adobecom.hlx.page/?martech=off
> Chrome devtools breaks on parsing $`

- libs/blocks/figure/figure.css
* Adding the "full-height" variant to figure block for bacom-blog infographic replacement
Resolves: [MWPW-135263](https://jira.corp.adobe.com/browse/MWPW-135263)
**Test URLs:**
- Before: https://main--milo--adobecom.hlx.page/drafts/slavin/bacom-blog/infographic-test?martech=off
- After: https://figure-bacom-blog-variant--milo--jasonhowellslavin.hlx.page/drafts/slavin/bacom-blog/infographic-test?martech=off
> [MWPW-135263] Adding variant to figure block

- libs/blocks/quiz/utils.js
- Gathering all the next steps for the selected cards first and then filtering on the entire set to make sure ordering of card selection does not make any difference when it comes to the `NOT` operator.
Resolves: https://jira.corp.adobe.com/browse/MWPW-135442
**Test URLs:**
- Before: https://uar-integration--milo--adobecom.hlx.live/drafts/xiasun/quiz-2/?martech=off
- After: https://uar-skip-order-of-selection--milo--sabyamon.hlx.page/drafts/xiasun/quiz-2/?martech=off
> MWPW-135442 - Fixing the issue of NOT operator when the order of selection is changed

- libs/blocks/quiz/utils.js
When building our array of nested fragments, if we find fragments for the same key for both primary and secondary products, the code currently replaces the primary product result with the secondary result. Instead, we need to concatenate the two. 
Resolves: [MWPW-135903](https://jira.corp.adobe.com/browse/MWPW-135903)
**Test URLs:**
- Before: [https://uar-integration--milo--adobecom.hlx.live/drafts/xiasun/quiz-2/?martech=off](https://uar-integration--milo--adobecom.hlx.live/drafts/xiasun/quiz-2/?martech=off)
- After: [https://mwpw-135903--milo--echampio-at-adobe.hlx.live/drafts/xiasun/quiz-2/?martech=off](https://mwpw-135903--milo--echampio-at-adobe.hlx.live/drafts/xiasun/quiz-2/?martech=off)
Here's a full set of test URLs, along with the value from local storage when you choose: …
> MWPW-135903: If nestedObject[fragKey] exists, append to it instead of replacing

- tools/send-to-caas/send-utils.js
The DC team has their caas tags separated by `;`, which is currently not supported.  Instead or updating all of those pages, this adds support for `;` as a delimiter.
Resolves: [MWPW-135983](https://jira.corp.adobe.com/browse/MWPW-135983)
**Test URLs:**
- After: https://caassemicol--milo--adobecom.hlx.page/?martech=off
> MWPW-135983 Support caas tags delimited by ;

- libs/features/personalization/manifest-utils.js
The manifest must be hosted on a relative path for the page.
**Test URLs:**
- After: https://manifestpath--milo--adobecom.hlx.page/?martech=off
> Personalization: make all manifest paths relative

- .github/gnav.md
Adds a new gnav PR template that can be optionally used by adding a query param to the url. `https://github.com/adobecom/milo/compare/main...mokimo:gnav-pr-template?expand=1` 
-> `https://github.com/adobecom/milo/compare/main...mokimo:gnav-pr-template?expand=1&template=gnav.md`
Resolves: N/A
Can't be tested until after this is merged
Make our lives easier
**Acrobat:**
- After: https://www.stage.adobe.com/acrobat/online/sign-pdf.html?martech=off&milolibs=gnav-pr-template--milo--mokimo
**BACOM:**
- Before: https://business.stage.adobe.com/fr/customer-success-stories.html?martech=off
- After: https://business.stage.adobe.com/fr/customer-success-stories.html?martech=off&milolibs=gnav-pr-template--milo--mokimo …
> Add a gnav PR template

- libs/blocks/article-feed/article-helpers.js
- libs/blocks/featured-article/featured-article.js
- libs/blocks/recommended-articles/recommended-articles.js
- libs/scripts/scripts.js
- test/blocks/article-header/article-header.test.js
- test/blocks/recommended-articles/mocks/body.html
- test/blocks/recommended-articles/recommended-articles.test.js
- test/blocks/tags/tags.test.js
* Add support for a `taxonomyRoot` config to change path of taxonomy (eyebrow) links
* Default to `/topics` for backwards compatibility
Resolves: [MWPW-135804](https://jira.corp.adobe.com/browse/MWPW-135804)
**Test URLs:**
- Before: https://main--milo--adobecom.hlx.page/drafts/methomas/taxonomy?martech=off
- After: https://methomas-taxonomy--milo--adobecom.hlx.page/drafts/methomas/taxonomy?martech=off
(After has no change. Default `/topics`)
Bacom blog: https://methomas-tags--bacom-blog--adobecom.hlx.page/drafts/methomas/taxonomy-config?milolibs=methomas-taxonomy
(taxonomyRoot `/tags`)
Adobe blog: 
-  https://main--blog--adobecom.hlx.page/?milolibs=methomas-taxonomy
- https://main--blog--adobecom.hlx.page/en/publish/2023/08/15/discover-key-visual-trends-for-autumn-2023-from-adobe-stock?mil …
> [Blog to Milo] MWPW-135804 Add taxonomyRoot config

- libs/styles/iframe.css
* A fallback property for iframe is added as dvh unit is not supported in few devices.(ipad 7th gen)
*The fallback value is set to 90vh to resolve the initial [issue](https://jira.corp.adobe.com/browse/MWPW-135324).
Resolves: [MWPW-[135924](https://jira.corp.adobe.com/browse/MWPW-135924)]
Test URLs:
-before: https://stage--cc--adobecom.hlx.page/drafts/ruchika/discover1?martech=off
-After:https://stage--cc--adobecom.hlx.page/drafts/ruchika/discover1?martech=off&milolibs=MWPW-135924--milo--sharath-kannan#animate
> Mwpw 135924 fallback css property added to iframe

- libs/blocks/section-metadata/section-metadata.css
Link and text is not differentiable in case of static links. Currently the default behaviour of links involve no-underline with underline on hover. When static link class is applied the text and links have same color and no underline makes it difficult to differentiate from the text. 
Adding underline in static link by default to be in-sync with notification static link style of a.static.(https://github.com/aishwaryamathuria/milo/blob/main/libs/styles/styles.css). 
Resolves: [MWPW-135814](https://jira.corp.adobe.com/browse/MWPW-135814)
**Test URLs:**
- Before: https://main--milo--adobecom.hlx.page/drafts/mathuria/aside/documentation/sectionmetadatadoc?martech=off
- After: https://staticlink--milo--aishwaryamathuria.hlx.page/drafts/mathuria/aside/documentation/sectionmetadatadoc?martech=off …
> MWPW-135814 Add underline in static link

- libs/blocks/global-navigation/global-navigation.js
This ensures that breadcrumbs are being built on pages using the URL-generated breadcrumbs feature.
Resolves: [MWPW-136078](https://jira.corp.adobe.com/browse/MWPW-136078)
On the Milo page, have a look at the After link and notice that breadcrumbs are being added as expected.
On consumer pages, no change should be visible, as the feature only impacts pages using the automatic breadcrumb generation based on URL.
**Acrobat:**
- After: https://www.stage.adobe.com/acrobat/online/sign-pdf.html?martech=off&milolibs=breadcrumbs-from-url--milo--overmyheadandbody
**BACOM:**
- Before: https://business.stage.adobe.com/fr/customer-success-stories.html?martech=off
- After: …
> [MWPW-136078] Ensure breadcrumbs based on URL are built

- libs/blocks/marketo/marketo.css
* Marketo block: Add error icon to checkboxes for accessibility
Resolves: [MWPW-135977](https://jira.corp.adobe.com/browse/MWPW-135977)
**Test URLs:**
- Before: https://main--milo--adobecom.hlx.page/drafts/bmarshal/mcz/marketo-block?martech=off
- After: https://methomas-marketo-icon--milo--adobecom.hlx.page/drafts/bmarshal/mcz/marketo-block?martech=off
(To test, select "Korea, South" for Country/Region and click submit. The first two checkboxes are required.)
> MWPW-135977 Marketo Checkbox Error Icon

- libs/blocks/section-metadata/section-metadata.css
* Static links style in section meta data doesn't work on modal links because they contain classes.  So I'm just making the static-links rule more specific. The start free trial link in the before URL was not inheriting color.
**Test URLs:**
- Before: https://homepage-brick--homepage--adobecom.hlx.page/homepage/?mep=%2Fhomepage%2Fhomepage.json--target-cc-lapsed
- After: https://homepage-brick--homepage--adobecom.hlx.page/homepage/?mep=%2Fhomepage%2Fhomepage.json--target-cc-lapsed&milolibs=static-links-modal
> Update static links style in section metadata to support modal links

- libs/blocks/instagram/instagram.js
Instagrams that load with IO after the first IG is loaded were not displaying, this uses the instagram api to manually display them (`window.instgrm.Embeds.process`)
Also `/reel/` links were not working, so we replace that with `/p/`
**Test URLs:**
- After: https://instagfix--milo--adobecom.hlx.page/?martech=off
> Fix hidden IG and /reel/ links

- libs/blocks/modal/modal.css
- libs/blocks/modal/modal.js
* body scroll/overflow  is hidden when a modal is open.
Resolves: [MWPW-136057](https://jira.corp.adobe.com/browse/MWPW-136057)
**Test URLs:**
- Before: https://main--cc--adobecom.hlx.page/creativecloud/animation/discover?martech=off
- After: https://main--cc--adobecom.hlx.page/creativecloud/animation/discover?martech=off&milolibs=MWPW-136057--milo--sharath-kannan#animate
**milo URLS**
- Before: https://main--milo--sharath-kannan.hlx.page/eg_ar/drafts/tat28144/blocks/marqueeblock?martech=off
-After: https://mwpw-136057--milo--sharath-kannan.hlx.page/eg_ar/drafts/tat28144/blocks/marqueeblock?martech=off
> fix(MWPW-136057):background scrolls when modal is open fixed

- tools/loc/rollout.js
Resolves: [MWPW-136311](https://jira.corp.adobe.com/browse/MWPW-136311)
**Test URLs:**
- Before: https://main--milo--adobecom.hlx.page/tools/loc/index.html?project=milo--adobecom&referrer=https%3A%2F%2Fadobe.sharepoint.com%2F%3Ax%3A%2Fr%2Fsites%2Fadobecom%2F_layouts%2F15%2FDoc.aspx%3Fsourcedoc%3D%257Bd2ff782a-0c83-4217-b7d0-1e947204e083%257D%26action%3Deditnew
- After: https://fix-dup-block-merge--milo--adobecom.hlx.page/tools/loc/index.html?project=milo--adobecom&referrer=https%3A%2F%2Fadobe.sharepoint.com%2F%3Ax%3A%2Fr%2Fsites%2Fadobecom%2F_layouts%2F15%2FDoc.aspx%3Fsourcedoc%3D%257Bd2ff782a-0c83-4217-b7d0-1e947204e083%257D%26action%3Deditnew
> MWPW-136311: Fixes merge issue with docx having duplicate blocks

- libs/blocks/article-feed/article-feed.js
* Add `lang-root` functionality to Article Feed block.
* * `lang-root` feature was added in https://github.com/adobecom/milo/pull/1101
* Defaults to link passed in (`${getConfig().locale.contentRoot}/query-index.json`) if `lang-root` isn't set.
This allows the Article Feed to use metadata (`lang-root`) to pass in a specific language folder to pull the query-index from.
Resolves: No ticket
**Test URLs:**
- Before: https://main--milo--adobecom.hlx.page/drafts/methomas/taxonomy?martech=off
- After: https://article-feed-langroot--milo--adobecom.hlx.page/drafts/methomas/taxonomy?martech=off
**Blog Test URLs:**
- Before: https://main--blog--adobecom.hlx.page/en/topics/adobe-culture?martech=off
- After: https://main--blog--adobecom.hlx.page/en/topics/adobe-culture?martech=off&milolibs=article-fee …
> [Blog Migration] Article feed update to work with metadata

- libs/blocks/merch-card/merch-card.css
Fixes Segment Merch card variant styles to match Consonant styles.
This PR fixes the following:
- H4 title font-size for `segment` merch card variant.
- CSS Flex design on `segment` merch card variant to set equal width on all columns.
- `Outline` CTA button style on `dark` style of `section-metadata`
Resolves: [MWPW-135988](https://jira.corp.adobe.com/browse/MWPW-135988)
**Test URLs:**
- Before: https://main--milo--adobecom.hlx.page/drafts/axel/bug-fixes/segment-card-fixes?martech=off
- After: https://mwpw-135988--milo--adobecom.hlx.page/drafts/axel/bug-fixes/segment-card-fixes?martech=off
> mwpw-135988 - segment card styling fixes

- libs/blocks/accordion/accordion.js
* Until analytics overhaul can be implemented, the accordion block needs impression tracking.
**Test URLs:**
- Before: https://main--milo--adobecom.hlx.page/docs/library/blocks/accordion?martech=off
- After: https://accordion-impression--milo--adobecom.hlx.page/docs/library/blocks/accordion?martech=off
> turn on impression tracking for accordion block

- libs/blocks/aside/aside.css
Looks like the notification variant of the aside is inheriting a style for setting its text content alignment. So adding the correct alignment property to the notification specific styles.
Update: actually ended up just removing the `align-content: center;` style because the correct alignment is being set from the center variant anyway. 
Resolves: [MWPW-136505](https://jira.corp.adobe.com/browse/MWPW-136505)
**Test URLs:**
- Before: https://main--milo--adobecom.hlx.page/drafts/sarchibeque/aside-notification-poc?martech=off
- After: https://sarchibeque-mwpw-136505-aside-fix--milo--adobecom.hlx.page/drafts/sarchibeque/aside-notification-poc?martech=off
> MWPW-136505 - Aside notification content alignment

- libs/utils/utils.js
Some accordions have carousel fragments used in the block
**Test URLs:**
- After: https://exemptaccordion--milo--adobecom.hlx.page/?martech=off
> Add accordion to donotinline

- CODEOWNERS
Updating CODEOWNERS as requested in https://github.com/adobecom/milo/pull/1264
Resolves: [MWPW-136619](https://jira.corp.adobe.com/browse/MWPW-136619)
Test URLs:
Before: https://main--milo--adobecom.hlx.page/drafts/xiasun/quiz-2/?martech=off
After: https://uar-integration--milo--adobecom.hlx.page/drafts/xiasun/quiz-2/?martech=off
> MWPW-136619: Update CODEOWNERS for quiz and quiz-results

- libs/features/personalization/personalization.js
- libs/martech/martech.js
* manifests from Target not parsed correctly when 2 tabs are present in Excel and forces the manifest to be downloaded unnecessarily.  When comparing the 2 URLs below, the network tab shows that homepage-two-tabs.json is downloaded.  The after URL does not download it.
**Test URLs:**
- Before: https://stage--homepage--adobecom.hlx.page/homepage/index-loggedout?at_preview_token=JUDSndEyhg0ZdtCre6u_pA&at_preview_index=1_2&at_preview_listed_activities_only=true
- After: https://stage--homepage--adobecom.hlx.page/homepage/index-loggedout?milolibs=manifest-data-fix&at_preview_token=JUDSndEyhg0ZdtCre6u_pA&at_preview_index=1_2&at_preview_listed_activities_only=true
> Manifest data fix

- libs/utils/utils.js
Some error has snuck in with https://github.com/adobecom/milo/pull/1081 blocking the log in from working (spotted only on stage environments so far)
@suhjainadobe would be great if you can have a deeper after the bug at hand as been fixed and write an additional unit test to ensure this can't happen in the future
Resolves: [MWPW-136633](https://jira.corp.adobe.com/browse/MWPW-136633)
Try to log in ... the error might be a race condition, I've only managed to reproduce it on https://www.stage.adobe.com/acrobat/online/sign-pdf.html
No screenshot, but for the unit tests it might be valuable to have the output of _what_ failed.
```
Uncaught (in promise) DOMException: Failed to execute 'querySelector' on 'Document': '#property=foo&state=%7B%whatever%22%3A%22v99-v9.99.9-99-319d%22%2C%22test%22%3 …
```
> mwpw-136633: safeguard scrolling

- libs/blocks/modal/modal.css
- libs/blocks/modal/modal.js
* Restrict modal-open css class to commerce modal for CC
Resolves: [MWPW-136656](https://jira.corp.adobe.com/browse/MWPW-136656)
**Test URLs:**
Milo
- Before:  https://main--milo--adobecom.hlx.page/drafts/ruchika/discover1?martech=off
- After: https://modal--milo--ruchika4.hlx.page/drafts/ruchika/discover1?martech=off
DC
- Before:  https://main--dc--adobecom.hlx.page/acrobat/online/convert-pdf?martech=off
- After: https://main--dc--adobecom.hlx.page/acrobat/online/convert-pdf?milolibs=modal--milo--ruchika4&martech=off
CC
- Before: https://main--cc--adobecom.hlx.page/creativecloud/animation/discover?martech=off#after-effects
- After: https://main--cc--adobecom.hlx.page/creativecloud/animation/discover?martech=off&milolibs=modal--milo--ruchika4#after-effects
> Restrict changes done for MWPW-136057 to commerce modal

- libs/blocks/global-navigation/utilities/utilities.js
- test/blocks/global-navigation/utilities/utilities.test.js
The default _gnav_ experience name is not of much use for Analytics purposes, thus we want to replace such strings with the IMS client ID. What is now `gnav|gnav` will become `gnav|acrobatmilo` for an Acrobat page, for example.
Resolves: [MWPW-136611](https://jira.corp.adobe.com/browse/MWPW-136611)
On a test page, run `document.querySelector('.global-navigation').getAttribute('daa-lh')` to check the Analytics value being used. Ideally, there shouldn't be duplicated _gnav_ strings being used.
From the test URLs shared below, just the Acrobat page should see an update in the Analytics tracking attribute.
**Acrobat:**
- After: https://www.stage.adobe.com/acrobat/online/sign-pdf.html?martech=off&milolibs=gnav-analyt …
> [MWPW-136611] Replace default experience name with IMS client ID

- libs/blocks/marquee/marquee.css
* A font size exception was needed specifically for text links in Large Split Marquees, taking the font size from 20px to 18px. This PR adds the requisite CSS for this.
Resolves: [MWPW-135557](https://jira.corp.adobe.com/browse/MWPW-135557)
**Test URLs:**
- Before: https://main--milo--adobecom.hlx.page/docs/library/blocks/marquee?martech=off
- After: https://ebartholomew-marquee-split-font-size--milo--adobecom.hlx.page/docs/library/blocks/marquee?martech=off
> [MWPW-135557] - Font size tweak to text links in Large Split Marquees

- libs/blocks/marquee-anchors/marquee-anchors.js
- test/blocks/marquee-anchors/mocks/body.html
As an author in Milo, I want the following features available to the `marquee-anchor` block so that I can have control over the user experience. 
1. Authoring input sanitization for error prevention. 
Authors & word will use uppercase labels so we lowercase() the label associations to prevent errors. 
2. Add link target and tracking attributes. 
These attributes get automatically included w/ any anchor-link creation so they behave as expected. 
Resolves: [MWPW-133742](https://jira.corp.adobe.com/browse/MWPW-133742)
**Test URLs:**
- Before: https://main--milo--adobecom.hlx.page/drafts/rparrish/marquee-nav?martech=off
- After: https://rparrish-marquee-anchors-fix--milo--adobecom.hlx.page/drafts/rparrish/marquee-nav?martech=off
Testing notes: 
1. In looking at the document, you will see the …
> [marquee-anchors] enhancement - author-proof input, include link attributes.  

- libs/blocks/icon-block/icon-block.css
Update icon block foreground to use max height instead of height on main image in smaller viewports (width of 1170px or less) to stop the image from distorting to fit a fixed height.
Resolves: [MWPW-136515](https://jira.corp.adobe.com/browse/MWPW-136515)
**Test URLs:**
- Before: https://main--milo--adobecom.hlx.page/drafts/sarchibeque/icon-block-imagesize?martech=off
- After: https://sarchibeque-mwpw-136515--milo--adobecom.hlx.page/drafts/sarchibeque/icon-block-imagesize?martech=off
> MWPW-136515 - Icon Block: fix image distortion in smaller viewports

- libs/blocks/library-config/lists/blocks.js
Converts a block in the block library with the name `mock-metadata`  to `metadata` when pasted in to Word.
**Context:**
The block library currently doesn't allow the `metadata` block to be added - due to the huge list of properties and one offs per page.
**Use case:**
For blog.adobe.com every article pages needs to have a metadata block added to it with specific publishing properties. The blog team asked if this metadata block could be added to the block library for easy access and reduced training.
Resolves: No ticket
**Test URLs:**
- After: https://mock-metadata--milo--adobecom.hlx.page/?martech=off
**Testing notes:**
Update your Milo sidekick to point to this branch.
1. Navigate to a Word doc and pull up the block library. …
> Mock metadata block

- libs/blocks/global-footer/global-footer.js
- libs/blocks/global-navigation/utilities/menu/menu.js
- test/blocks/global-navigation/global-navigation.test.js
This adds `daa-ll` tracking attributes to menu accordion headers on mobile devices and misc footer links from the social and legal sections.
Resolves: [MWPW-136612](https://jira.corp.adobe.com/browse/MWPW-136612)
Navigate to any 'after' URL on a mobile device. Inspect the accordion headers in either the header or footer sections and check that a `daa-ll` attribute exists. Inspect the social and legal section from the footer on both mobile and desktop devices and check that they have `daa-lh` and `daa-ll` attributes.
For testing purposes in the footer area, I've added some quick CSS that exposes the values to the UI so they're easier to follow, these styles can be used to make QA a bit easier (note that these will affect layout):
```
@media screen and (max-width: 899px) { …
```
> [MWPW-136612] Gnav/Footer menus mobile accordion tracking

- libs/blocks/modal/modal.js
- test/blocks/modals/modals.test.js
We have a bunch of issues with querySelectors which were fixed here https://github.com/adobecom/milo/pull/1348 or here https://github.com/adobecom/milo/pull/1287 
**Question:** Should we find a more generic solution for this querySelector syntax errors ?
**Issue:** We ran into querySelector syntax errors 3x in a brief time frame now
**Proposal:** A milo utility wrapper for `querySelector/querySelectorAll` that adds a try/catch and you can just use `import {safeQuerySelector} from './action.js'` then
Resolves: [MWPW-136672](https://jira.corp.adobe.com/browse/MWPW-136672)
1. Open a milo page with a modal
2. Change the hash to by pasting  `window.location.hash = '';` in the console
3. No error should appear on the **after** test URLs anymore.
**BACOM:**
- Before: …
> safeguard milo modals from invalid query selectors

- tools/sidekick/config.json
Due to recent update in helix-sidekick extension, the "excludePaths" is functionality is broken. Temporarily removing the exclude-path configuration for Localization's sidekick config to unblock QA for testing localization.
Resolves: [MWPW-137162](https://jira.corp.adobe.com/browse/MWPW-137162)
With this change, the "Localize Project" option will come for all documents not just excel.
> MWPW-137162: [LocUI] Temporarily remove exclude path for localization

- tools/sidekick/config.json
Helix Sidekick v6.30.3 seems to remove the Localize and Floodgate option from the Sidekick. Removing the `excludePaths` config seems to be fixing it. Temporarily removing that option to unblock. A discussion with Franklin team has been started to figure out the root cause.
Resolves: [MWPW-137171](https://jira.corp.adobe.com/browse/MWPW-137171)
**Test URLs:**
- After: https://fix-sidekick-bug--milo--adobecom.hlx.page/
> MWPW-137171: Temp Fix for Sidekick

- libs/features/personalization/personalization.js
Personalization fragments that are inserted are normally wrapped in a p tag, but sections are expected to be wrapped in a div.
Resolves: [MWPW-137130](https://jira.corp.adobe.com/browse/MWPW-137130)
**Test URLs:**
- Before:https://main--milo--adobecom.hlx.page/drafts/cpeyer/mwpw-137130/replace-section?martech=off
- After: https://pers-replace-section--milo--adobecom.hlx.page/drafts/cpeyer/mwpw-137130/replace-section?martech=off
> Add support for sections

- libs/utils/utils.js
Image alt links pointing to .hlx.* were not getting converted to relative links in prod.
Resolves: [MWPW-136429](https://jira.corp.adobe.com/browse/MWPW-136429)
**Test URLs:**
- Before: https://main--milo--adobecom.hlx.page/drafts/cpeyer/mwpw-136429-image-links/image-link-issue-copy?martech=off
- After: https://136429-altlinks--milo--adobecom.hlx.page/drafts/cpeyer/mwpw-136429-image-links/image-link-issue-copy?martech=off
> MWPW-136429 Transform Image alt links

- libs/blocks/quiz-results/quiz-results.css
For quiz-results we use consonants card, they have already grid set.
In our case we need an extra class to correct the alignment as each card will be hold by a fragment, causing that the grid consonant do not get set, for our nested quiz-card-list
https://jira.corp.adobe.com/browse/MWPW-135730
**Test URLs:**
- Before: https://uar-integration--milo--adobecom.hlx.page/drafts/delta/app-recommender-test/?martech=off
- After: https://quiz-card-list--milo--elaineskpt.hlx.page/drafts/delta/app-recommender-test/?martech=off
To test in your own folder please update the card-list nested-fragment
Instead style center, three up
to style quiz-card-list
> UAR - quiz-card-list update

- libs/blocks/global-footer/global-footer.js
- libs/features/personalization/personalization.js
- libs/features/personalization/preview.js
- libs/utils/utils.js
The value for no manifest is "default|default" but the value for default when you have a manifest is "no changes|manifest name".  This changes "no changes" to "default" to be consistent.
For the before and after links, you can look at the data-mep attribute on `body` or the `daa-lh` values on `header` and all blocks to see the difference.
Resolves: [MWPW-135672](https://jira.corp.adobe.com/browse/MWPW-135672)
**Test URLs:**
- Before: https://main--milo--adobecom.hlx.page/drafts/vgoodric/pers-demo?martech=off
- After: https://mwpw-135672-no-changes-fix--milo--adobecom.hlx.page/drafts/vgoodric/pers-demo?martech=off
> MWPW-135672 no changes fix

- libs/utils/utils.js
Reverts adobecom/milo#1367
Following issues have been reported hence the revert PR
1. Alt Text for image that links to video is not working anymore. The static images are not showing: https://main--bacom--adobecom.hlx.page/de/resources/webinars/automotive-dialogues/creativity-in-motion
2. video modal link in the image but video thumbnail is showing up instead of the image in the document: https://main--bacom--adobecom.hlx.page/jp/resources/webinars/best-of-adobe-summit-2023-top#
3. #_dnt not working
> Revert "MWPW-136429 Transform Image alt links"

- libs/utils/utils.js
* Fix absolute links found in alt text
Resolves: [MWPW-120357](https://jira.corp.adobe.com/browse/MWPW-120357)
**Test URLs:**
- Before: https://main--milo--adobecom.hlx.page/drafts/cmillar/about-adobe?martech=off
- After: https://relative-alt-links--milo--adobecom.hlx.page/drafts/cmillar/about-adobe?martech=off
> MWPW-120357 - Make alt text links relative

- libs/blocks/quiz/quiz.css
* Allow section metadata dark with static links style without background
Resolves: [MWPW-136165](https://jira.corp.adobe.com/browse/MWPW-136165)
**Test URLs:**
- Before: https://main--milo--adobecom.hlx.page/drafts/xiasun/quiz-2/?martech=off
- After: https://quiz-footer-link-color--milo--colloyd.hlx.page/drafts/xiasun/quiz-2/?martech=off
With this change, an author can force white text on links by adding section metadata to their footer fragment and adding both 'dark' and 'static links' to style. Unfortunately, using 'dark' also changes the background, where it will need to be transparent for quiz. This will reset the background to ensure that it is displayed properly within the quiz.
- example fragment: https://milo.adobe.com/fragments/xiasun/sample-uar-fragments/footer/footer2
> MWPW-136165 - Background reset for quiz footer

- test/blocks/caas/utils.test.js
CaaS test failing due to change in ctaAction default value
**Test URLs:**
- After: https://fixcaastests--milo--adobecom.hlx.page/?martech=off
> Fix failing caas test

- libs/martech/martech.js
Martech folks would like to be able to easily id milo sites.
Resolves: [MWPW-135875](https://jira.corp.adobe.com/browse/MWPW-135875)
To test: Open after url and check the `window.marketingtech` object for `milo:true`
**Test URLs:**
- Before: https://main--milo--adobecom.hlx.page
- After: https://135875-martech--milo--adobecom.hlx.page
> MWPW-135875 Add milo property to window.marketingtech

- libs/blocks/video/video.js
Make all media_xxx.mp4 videos load from the coderoot so that loc changes are ignored.
Resolves: [137511-NUMBER](https://jira.corp.adobe.com/browse/MWPW-137511)
**Test URLs:**
- After: https://137511-vidloc--milo--adobecom.hlx.page/?martech=off
> MWPW-137511 Loc videos do not load

- .gitignore
- README.md
- package.json
As per the [announcement](https://discord.com/channels/1131492224371277874/1134435772422955109/1158410421309538416) a few names have been changed and we should try our best to keep up with it
I'll also update the wiki and documentation.
Everyone should switch to use the `aem-cli` as the `helix-cli` is deprecated.
Run `npm install -g @adobe/aem-cli --force` to install the `aem-cli` you can then use `aem` instead of `hlx` to use the CLI.
**Test URLs:**
- After: https://hlx-to-aem--milo--mokimo.hlx.page/?martech=off
> Rename helix-cli to aem-cli

- test/blocks/video/video.test.js
Fix failing tests introduced in https://github.com/adobecom/milo/pull/1415/files by applying default configs for the tests.
Consumers need to set configs either way, so this purely test-setup related.
**Test URLs:**
- After: https://mwpw-137511-fix-failing-tests--milo--mokimo.hlx.live/?martech=off
> Fix failing video tests

- libs/features/personalization/personalization.js
Makes the prelink href relative for personalization fragments.
Resolves: [MWPW-137970](https://jira.corp.adobe.com/browse/MWPW-137970)
**Test URLs:**
- Before: https://main--homepage--adobecom.hlx.page/homepage/index-loggedout
- After: https://main--homepage--adobecom.hlx.page/homepage/index-loggedout?milolibs=mwpw-137970--milo--yesil&mep=%2Fhomepage%2Ffragments%2Fmep%2Fhp.json--target-dc
> MWPW-137970: make MEP prelinks relative

- web-test-runner.config.mjs
We already added a bunch of measures to ensure we fix flaky tests. Since we still have an issue with flaky tests, we should enable test retries. 
When a unit test fails, we can now be **sure the test needs to be fixed.**
Developers should not need to re-run tests using the Github UI as it's retried automatically.
2 Retries mean the test would be run a maximum of 3 times when including the initial run. If a test fails 3 times in a row, the test has a serious flaw or it's a legit issue.
Web test runner test framework configs: https://modern-web.dev/docs/test-runner/test-frameworks/mocha/#configuring-mocha-options
Mocha test retries: https://mochajs.org/#-retries-n
Resolves: [MWPW-137972](https://jira.corp.adobe.com/browse/MWPW-137972)
To test if this config works, you can just use a counter …
> Enable web test runner test retries

- libs/utils/utils.js
Image alt links pointing to .hlx.* were not getting converted to relative links in prod.
Resolves: [MWPW-136429](https://jira.corp.adobe.com/browse/MWPW-136429)
* Add your
* Specific
**Test URLs Milo**
- Before: https://main--milo--adobecom.hlx.page/drafts/rclayton/test/image-links?martech=off
- After: https://alt-image-links--milo--adobecom.hlx.page/drafts/rclayton/test/image-links?martech=off
**Test URLs BACOM:**
- Samples of image link, launching modal, background videos set to autoplay
- Before: https://main--bacom--adobecom.hlx.page/drafts/rclayton/test/image-links?martech=off
- After: https://main--bacom--adobecom.hlx.page/drafts/rclayton/test/image-links?milolibs=alt-image-links&martech=off …
> Make alt text links relative

- tools/loc/rollout.js
Resolves: [MWPW-136896]( https://jira.corp.adobe.com/browse/MWPW-136896)
This PR skips adding anchors for `Heading` in langstore version. This is done to have the link point to regional heading which is shown in preview by default.
With this change:
<div class="OutlineElement Ltr SCXW51860322 BCX0" style="margin: 0px; padding: 0px; user-select: text; -webkit-user-drag: none; -webkit-tap-highlight-color: transparent; overflow: visible; cursor: text; clear: both; position: relative; direction: ltr; color: rgb(0, 0, 0); font-family: &quot;Segoe UI&quot;, &quot;Segoe UI Web&quot;, Arial, Verdana, sans-serif; font-size: 12px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; …
> MWPW-136896: Regional edits in-page link support for heading and bookmark

- libs/blocks/global-navigation/global-navigation.js
The homepage has seen some lighthouse score improvements with enabled Martech by aligning the global navigation internal delay of 2000ms with the milo standard of 3000ms.
Resolves: [MWPW-137857](https://jira.corp.adobe.com/browse/MWPW-137857)
Dropdowns, search, profile should still work
**Acrobat:**
- After: https://www.stage.adobe.com/acrobat/online/sign-pdf.html?martech=off&milolibs=mwpw-137857--milo--mokimo
**BACOM:**
- Before: https://business.stage.adobe.com/fr/customer-success-stories.html?martech=off
- After: https://business.stage.adobe.com/fr/customer-success-stories.html?martech=off&milolibs=mwpw-137857--milo--mokimo
**CC:**
- Before: https://main--cc--adobecom.hlx.live/?martech=off
- After: …
> mwpw-137857: increase global navigation loadDelayed delay

- tools/send-to-caas/send-utils.js
- Change the "origin" value while send to caas to use default tree as origin, instead of floodgate tree as origin
Test URLs:
Before: https://main--milo--adobecom.hlx.page/tools/send-to-caas/bulkpublisher.html?martech=off
After: https://main--milo--arshadparwaiz.hlx.page/tools/send-to-caas/bulkpublisher.html?martech=off
Test Data:
Host: milo.adobe.com
Repo: milo-pink
Repo owner: adobecom
Publish to Floodgate: pink
URLs: https://milo.adobe.com/drafts/arshad/caas-fg-card-3
Resolves: [MWPW-138430](https://jira.corp.adobe.com/browse/MWPW-138430)
> MWPW-138430 - Set origin to default repo when FG send to caas

- libs/utils/samplerum.js
This PR updates the `sampleRUM` instrumentation to the latest version we have.
Mainly adds:
* https://github.com/adobe/helix-rum-js/commit/26d9b2e8afd00458d3b050d3fd152fb55a26adcb
* https://github.com/adobe/helix-rum-js/commit/5295681b6c6f7e5c7f541e058a6bde55892ecc32
* https://github.com/adobe/helix-rum-js/commit/d224c64919b92a0b9915ef9a7ee8205e99704cef
* sanitizes URLs before submitting the data
Addresses part of https://github.com/orgs/adobecom/discussions/1442
Resolves: [MWPW-137805](https://jira.corp.adobe.com/browse/MWPW-137805).
Supersedes: https://github.com/adobecom/milo/pull/1448
Before: https://main--dc--adobecom.hlx.page/?martech=off
After: https://main--dc--adobecom.hlx.page/?milolibs=update-samplerum--milo--adobecom&martech=off
Before: …
> fix: update sampleRUM to its latest version

- libs/blocks/aside/aside.css
- libs/blocks/global-navigation/base.css
- libs/blocks/global-navigation/features/aside/aside.js
- libs/blocks/global-navigation/global-navigation.css
- libs/blocks/global-navigation/global-navigation.js
- libs/styles/styles.css
- libs/utils/utils.js
- test/blocks/global-navigation/global-navigation.test.js
- test/blocks/global-navigation/mocks/correctPromoFragment.plain.js
- test/blocks/global-navigation/mocks/global-navigation-only-brand-no-explicit-image.js
- test/blocks/global-navigation/test-utilities.js
This allows authors to include a promo bar on top of the Global Navigation by defining a new `gnav-promo-source` metadata property with its value leading to a fragment which contains an `aside` block. For design purposes, it's important that authors use the `promobar` variation of the block, although we don't currently have a restriction for this from a code perspective.
Some additional notes:
- `utils.js` has been slightly adapted to add a modifier class to the header in case a Gnav promo was authored on a page. Its use can be seen in `style.css` where we adapt the nav height;
- some minimal changes have been made to the `aside` block CSS to ensure content alignment follows Word indentation and that the CTA does not wrap on multiple rows. The latter might be something useful for all …
> [MWPW-117914] Allow promobar use on top of Gnav

- libs/blocks/merch/merch.css
This PR addresses a style regression in promo prices.
actual:
expected:
Resolves: [MWPW-138740](https://jira.corp.adobe.com/browse/MWPW-138740)
**Test URLs:**
- Before: https://main--milo--adobecom.hlx.page/drafts/ilyas/merch?martech=off
- After: https://mwpw-138740--milo--yesil.hlx.live/drafts/ilyas/merch?martech=off
> MWPW-138740: fix strikethrough price

- libs/utils/utils.js
When sending content to CaaS, milo was using the adobecom github repository name as the origin for the content source in CaaS. 
CaaS has it's own source values (legacy from dexter) that should be used, otherwise each site will have separate buckets where their content exists.
This PR creates a hard coded map for where to pull the content from which will update as new consumers onboard onto CaaS and milo.
Resolves: https://jira.corp.adobe.com/browse/MWPW-136763
**Test URLs:**
- Before: https://milo.adobe.com/tools/send-to-caas/bulkpublisher.html?martech=off
- After: https://mwpw-136763--milo--adobecom.hlx.page/tools/send-to-caas/bulkpublisher.html?martech=off
> MWPW-136763: Fixes wrong origins being used by consumers #1325

- tools/send-to-caas/send-utils.js
There was an issue found during Prod Smoke testing where origins where the mapping didn't exist would not fallback to code repo name and return the empty string.
> MWPW-136763: Fixes cases where origin is not in mapping

- libs/templates/404/404.js
* Add analytics tracking attributes to 404 page template
Resolves: [MWPW-138736](https://jira.corp.adobe.com/browse/MWPW-138736)
**Test URLs:**
Milo:
- Before: https://main--milo--adobecom.hlx.page/doesnotexist
- After: https://404-analytics--milo--ruchika4.hlx.page/doesnotexist
DC
- Before: https://main--dc--adobecom.hlx.page/acrobat/resources123
- After: https://main--dc--adobecom.hlx.page/acrobat/resources123?milolibs=404-analytics--milo--ruchika4
CC
- Before: https://stage--cc--adobecom.hlx.page/fr/creativecloud/photography/hub/guides/add-vintage-frame-in-photoshops
- After: https://stage--cc--adobecom.hlx.page/fr/creativecloud/photography/hub/guides/add-vintage-frame-in-photoshops?milolibs=404-analytics--milo--ruchika4
For testing:
Open the before url and inspect any link and button …
> Add analytics to 404 page template

- tools/loc/rollout.js
Resolves: [MWPW-136896]( https://jira.corp.adobe.com/browse/MWPW-136896)
This PR skips adding anchors for `Heading` & `Bookmarks` in langstore version. This is done to have the link point to regional heading which is shown in preview by default.
With this change:
<div class="OutlineElement Ltr SCXW51860322 BCX0" style="margin: 0px; padding: 0px; user-select: text; -webkit-user-drag: none; -webkit-tap-highlight-color: transparent; overflow: visible; cursor: text; clear: both; position: relative; direction: ltr; color: rgb(0, 0, 0); font-family: &quot;Segoe UI&quot;, &quot;Segoe UI Web&quot;, Arial, Verdana, sans-serif; font-size: 12px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; …
> MWPW-136896: Regional edit support for heading/bookmarks

- libs/blocks/quiz/quiz.css
In the quiz block, for rtl locales, mirror the few places were we had specified margin-left or -right. 
Resolves: [MWPW-132437](https://jira.corp.adobe.com/browse/MWPW-132437)
**Test URLs:**
- Before: https://uar-integration--milo--adobecom.hlx.page/drafts/quiz/quiz-2/index-rtl?martech=off
- After: https://mwpw-132437--milo--echampio-at-adobe.hlx.page/drafts/quiz/quiz-2/index-rtl?martech=off
> MWPW-132437: [Q] Mirror margins for RTL locales

- libs/blocks/modal/modal.css
- libs/blocks/modal/modal.js
This PR has been opened because previous 2 (https://github.com/adobecom/milo/pull/1457 &
https://github.com/adobecom/milo/pull/1419) had outdated and broken main origin branch. I am opening this PR after cloning this project from the start, with fresh and up-to-date main branch.
This PR should resolve the issue of scrollable background when modal dialog (which is authored to have a 'curtain') is opened. In other cases (with 'curtain-off') background should be scrollable per requirements.
Resolves: [MWPW-136767](https://jira.corp.adobe.com/browse/MWPW-136767)
Test URLs:
Before: https://main--milo--adobecom.hlx.page/drafts/rclayton/video-examples?martech=off
After: https://mwpw-136767-modal-background-scroll--milo--saragajic11.hlx.page/drafts/rclayton/video-examples?martech=off
Commerce …
> Implemented disabling scroll when modal with curtain is opened

- libs/blocks/recommended-articles/recommended-articles.js
- libs/scripts/taxonomy.js
* Checks for the meta property of category for card titles in the article feed
* Sanitizes taxonomy properties and params passed into get method to avoid case sensitivity issues. 
Additional context: 
We may want to revisit this code since there are now two business logics being used by it, not to mention the new taxonomy pattern introduced with the tag selector. 
There should be no impact on brand blog's recommended articles or cards 
Resolves: [MWPW-138106](https://jira.corp.adobe.com/browse/MWPW-138106)
**Test URLs:**
*Dx Blog*
- Before: https://main--bacom-blog--adobecom.hlx.page/uk/drafts/methomas/?martech=off
- Before: https://main--bacom-blog--adobecom.hlx.page/blog/?martech=off
- After: https://main--bacom-blog--adobecom.hlx.page/uk/drafts/methomas/?milolibs=blog-category-fix&marte …
> MWPW-138106: b.a.com Blog category titles fix

- libs/blocks/gnav/gnav.css
* Fix issue: Adobe icon on right in gnav (old version) wasn't displaying on Safari v15-17.
Resolves: [MWPW-138197](https://jira.corp.adobe.com/browse/MWPW-138197)
**Test URLs:**
Milo:
- Before: https://main--milo--adobecom.hlx.page/drafts/methomas/text-center?headerqa=gnav&footerqa=gnav&martech=off
- After: https://methomas-adobe-logo--milo--adobecom.hlx.page/drafts/methomas/text-center?headerqa=gnav&footerqa=gnav&martech=off
Bacom blog:
- Before: https://main--bacom-blog--adobecom.hlx.page/blog/tags/the-latest
- After: https://main--bacom-blog--adobecom.hlx.page/blog/tags/the-latest?milolibs=methomas-adobe-logo
*Reminder, this is only reproducible on Safari v15-17
> MWPW-138197 Fix Adobe Logo on Safari

- libs/blocks/quiz/utils.js
- test/blocks/quiz/mocks/invalid-user-selection.json
- test/blocks/quiz/utils.test.js
* If you follow a quiz path that doesn't match any results, you'll see an error in storeResultInLocalStorage errors when no matchedResults are found. I'm checking to see whether matchedResults[0] exists before dereferencing it to look for basic and nested fragments.
Resolves: [MWPW-139129](https://jira.corp.adobe.com/browse/MWPW-139129)
**Test URLs:**
- Before: https://uar-integration--milo--adobecom.hlx.page/drafts/quiz/quiz-2/?martech=off
- After: https://uar-integration--milo--echampio-at-adobe.hlx.page/drafts/quiz/quiz-2/?martech=off
> MWPW-139129: Quiz errors when no matchedResults

- libs/blocks/aside/aside.css
With rearrangement of CSS in https://github.com/adobecom/milo/pull/1470 the promoaside icon styles are overriding promoaside popup variant icon styles. Fixing the css to prioritize popup style for popup promo.
Resolves: [MWPW-138921](https://jira.corp.adobe.com/browse/MWPW-138921)
**Test URLs:**
- Before: https://main--milo--adobecom.hlx.page/drafts/mathuria/promobar/popuppromo?martech=off
- After: https://mwpw-138921--milo--aishwaryamathuria.hlx.page/drafts/mathuria/promobar/popuppromo?martech=off
> MWPW-138921 Fixing popup promo image size

- libs/blocks/caas/utils.js
localizeLink API that doesn't correctly work, on prod bacom pages. Adjusted the call to the API to make it work.
Some more information on this issue solution can be found here: 
https://wiki.corp.adobe.com/pages/viewpage.action?pageId=2932205920
The logic is as follows:
1. Fully Qualified URL: --> Localize Link --> getUUID --> Call Chimera IO
2. UUID --> Call Chimera IO
Resolves: [MWPW-133011](https://jira.corp.adobe.com/browse/MWPW-133011)
For the prod test URLs please enable local overrides to test
**Test URLs:**
- Before: https://main--milo--adobecom.hlx.page/drafts/shkhan/mwpw-132559?martech=off
- Before: https://business.adobe.com/mena_en/request-consultation/thankyou.html?martech=off
- After: https://shkhan-featured-mwpw-133011--milo--shkhan91.hlx.page/drafts/shkhan/mwpw-132559?marte …
> Support for prod non milo environment

- libs/blocks/article-feed/article-helpers.js
* Adds logic looking into the config to determine if the site is bacom blog before reassigning the category prop
Resolves: [MWPW-138962](https://jira.corp.adobe.com/browse/MWPW-138962)
**Test URLs:**
_bacom-blog_
- Before: https://main--bacom-blog--adobecom.hlx.page/drafts/staged-content/blog/tags/adobe-analytics?martech=off
- After: https://main--bacom-blog--adobecom.hlx.page/drafts/staged-content/blog/tags/adobe-analytics?martech=off&milolibs=article-feed-category
_brand blog_
- Before: https://main--blog--adobecom.hlx.page/en/topics/customer-stories?martech=off
- After: https://main--blog--adobecom.hlx.page/en/topics/customer-stories?martech=off&milolibs=article-feed-category
> MWPW-138962:  Bacom-blog Article Feed Issue

- test/blocks/gnav/gnav.test.js
- test/blocks/gnav/mocks/head.html
This helps mocking Adobe IMS script for the `gnav.js` unit tests
run `npm run test` in your terminal
**Acrobat:**
- Before: https://main--dc--adobecom.hlx.page/drafts/rbogos/default?martech=off
- After: https://main--dc--adobecom.hlx.page/drafts/rbogos/default?milolibs=mwpw-138031-footer-tests--milo--rbogos&martech=off
**BACOM:**
- Before: https://main--bacom--adobecom.hlx.page/drafts/rbogos/default
- After: https://main--bacom--adobecom.hlx.page/drafts/rbogos/default?milolibs=mwpw-138031-footer-tests--milo--rbogos&martech=off
**CC:**
- Before: https://main--cc--adobecom.hlx.page/drafts/rbogos/default?martech=off
- After: https://main--cc--adobecom.hlx.page/drafts/rbogos/default?milolibs=mwpw-138031-footer-tests--milo--rbogos&martech=off
**Milo:**
- Before: …
> MWPW-139338: mocked ims for gnav.js unit tests

- libs/blocks/table/table.css
- Table CSS update for RTL.
Resolves: [MWPW-139039](https://jira.corp.adobe.com/browse/MWPW-139039)
**Test URLs:**
- Before: https://main--milo--adobecom.hlx.page/mena_ar/drafts/seanchoi/table-rtl?martech=off
- After: https://table-rtl--milo--adobecom.hlx.page/mena_ar/drafts/seanchoi/table-rtl?martech=off
- No RTL: https://table-rtl--milo--adobecom.hlx.page/docs/library/blocks/table?martech=off
> [MWPW-139039] Table css update for RTL

- libs/features/links.js
- test/blocks/links/links-off-origin.test.js
- test/blocks/links/mocks/body.html
- test/blocks/links/mocks/off-origin.json
Adds functionality to open all off-origin links into a new tab via `links.js`
* "off-origin" keyword is added to [links.xlsx](https://main--milo--adobecom.hlx.page/seo/links.json)
**Context:**
Links.js offers the ability to call out specific links and add nofollow, noopener, noreferrer, and/or _blank to the link. More details about the original implementation can be found in https://github.com/adobecom/milo/pull/345
"Links" is opt in and needs to be [enabled per site](https://github.com/adobecom/milo/blob/main/libs/scripts/scripts.js#L121)
**Resolves:** [MWPW-136383](https://jira.corp.adobe.com/browse/MWPW-136383)
**Test URLs:**
- Before: https://main--milo--adobecom.hlx.page/drafts/rclayton/links?martech=off
- After: https://links-off-origin--milo--adobecom.hlx.page/drafts/rclayton/links? …
> MWPW-136383 - Add off-origin ability to links.js

- libs/blocks/global-navigation/base.css
- libs/blocks/global-navigation/global-navigation.css
- libs/blocks/global-navigation/utilities/keyboard/utils.js
- libs/blocks/global-navigation/utilities/menu/menu.css
- libs/blocks/global-navigation/utilities/menu/menu.js
- test/blocks/global-navigation/global-navigation.test.js
- test/blocks/global-navigation/mocks/global-navigation-wide-column.plain.js
- test/blocks/global-navigation/mocks/large-menu-wide-column.plain.js
- test/blocks/global-navigation/test-utilities.js
This enables authors to add gradient backgrounds to _Link Group_ blocks in Gnav navigation documents. This is needed to support an upcoming UI A/B test for the Creativity & Design dropdown menu content. Considering this, we've implemented a minimal set of changes; the features will be expanded or completely removed depending on the test outcome. A few notes, in order of files:
- gradient backgrounds can be added by using some special class names. Since we don't know whether this feature has a future, we didn't yet want to enable authors to define any background possibility on their own. The class names are defined based on the proposed design and which elements require the gradient backgrounds: `photo-gradient, design-gradient, 3d-gradient, pdf-gradient, video-gradient, ai-gradient`. I've …
> [MWPW-136943] Colorful Gnav headings for A/B test

- libs/blocks/global-navigation/utilities/menu/menu.css
- libs/blocks/global-navigation/utilities/menu/menu.js
- test/blocks/global-navigation/global-navigation.test.js
- test/blocks/global-navigation/mocks/global-navigation.plain.js
- test/blocks/global-navigation/test-utilities.js
Links wrapped in `strong` or `em` tags were not decorated when used inside Gnav Promo boxes, part of the main navigation dropdown menus. This is leading to inconsistencies between the Black Friday / Cyber Monday experiences between AEM and Milo pages.
Note that the `parseCtas` argument for the `decorateElements` function has been initially added to support the potential output of a script that transformed AEM Gnav content into Milo Gnav content. Since that path has not been pursued, the extra argument can be removed.
Resolves: [MWPW-139201](https://jira.corp.adobe.com/browse/MWPW-139201)
On the homepage test link, open the _Creativity & Design_ dropdown. Notice the CTA being decorated inside the Promo box. Now open the _Help & Support_ dropdown, notice that nothing changes, as that link …
> [MWPW-139201] Allow CTAs in Gnav Promo boxes

- libs/utils/utils.js
Added the `quiz-marquee` to the /libs/utils.js blocks list for consuming sites
FYI: This was overlooked in the initial PR and the CC site needs access to start testing
Resolves: [MWPW-136152](https://jira.corp.adobe.com/browse/MWPW-136152)
**Test URLs:**
- Before: https://main--cc--adobecom.hlx.page/cc-shared/fragments/uar/marquee/animate?debug=quiz-results&martech=off
- After: https://main--cc--adobecom.hlx.page/cc-shared/fragments/uar/marquee/animate?milolibs=rparrish-quiz-marquee-utils&debug=quiz-results&martech=off
> MWPW-136152 - Added the `quiz-marquee` to the utils blocks list for consuming sites

- libs/blocks/marquee/marquee.css
* Locales that use a language which runs right to left (rtl) would have the placement of marquee text on the opposite site of the block, potentially covering up the media contained in the background. This PR standardizes the placement of the text content without affecting the reading direction. This only applies to the desktop breakpoint.
* Style lint errors were also fixed (the new code for rtl languages is on line 585 of this file)
Resolves: [MWPW-139782](https://jira.corp.adobe.com/browse/MWPW-139782)
**Test URLs:**
- Before: https://main--milo--adobecom.hlx.page/ae_ar/drafts/ebartholomew/rtl-marquee?martech=off
- After: https://ebartholomew-rtl-marquee--milo--adobecom.hlx.page/ae_ar/drafts/ebartholomew/rtl-marquee?martech=off
> MWPW-139782 - Marquee alignment for rtl locales

- libs/features/personalization/personalization.js
Found an issue on personalization that the LCP image has `lazy` tag and media path doesn't get updated when it gets replaced the page.
This will run decorateArea() when personalization replace page by replacing `<main>` element, so homepage can handle those issue.
**Related PRs:**
- #1520
- https://github.com/adobecom/homepage/pull/36
**Test URLs:**
- After: https://decoratearea-personalization--milo--adobecom.hlx.page/?martech=off
> Adding decorateArea() into replaceInner()

- libs/blocks/quiz/quiz.css
* Shows mobile progress indicator at tablet widths
Resolves: [MWPW-138449](https://jira.corp.adobe.com/browse/MWPW-138449)
**Test URLs:**
- Before: https://uar-integration--milo--adobecom.hlx.page/drafts/colloyd/quiz/?martech=off
- After: https://mwpw-138449-mobile-progress-indicator-at-tablet--milo--colloyd.hlx.page/drafts/colloyd/quiz/?martech=off
View the "After" page at widths below 1024px and the progress indicator should be seen below the questions (mobile). Where "Before" swapped to the mobile indicator below 600px
> MWPW-138449 - Mobile progress indicator until 1024px

- libs/blocks/fragment/fragment.js
The recently introduced `decorateArea` function does not support loading an LCP relevant image originating from a fragment. To fully support this, @chrischrischris and I found a way to do this:
- in `fragments.js`, add the current fragment link as additional parameter to the `decorateArea` function
- use a config object in case we want to pass in more stuff in the future without breaking consumer implementations
By passing in the current fragment's link to `decorateArea`, we can do the following on the consumer side:
- check for the first `a` element with class `fragment` and compare it with the passed in fragment link
- this way we know that the current fragment is the first one since milo hasn't processed and swapped out the `a.fragment` element with its actual content from the fragment …
> MWPW-139621 - LCP loading via fragments

- libs/blocks/accordion/accordion.css
* Separated specific styles for ltr and rtl locales
* The +/- sign is on the left side for rtl locales
* Text alignment is right for rtl locales
* The blue border for an opened accordion item is on the right side for rtl locales
Resolves: [MWPW-140160](https://jira.corp.adobe.com/browse/MWPW-140160)
**Test URLs for _ltr_ locale:**
- Before: https://www.stage.adobe.com/acrobat/online/pdf-to-ppt.html
- After: https://www.stage.adobe.com/acrobat/online/pdf-to-ppt.html?milolibs=mwpw-140160-accordion-styles-for-rtl--milo--draganatrajkovic
**Test URLs for _rtl_ locales:**
- Before: 
1. https://www.stage.adobe.com/kw_ar/acrobat/online/pdf-to-ppt.html
2. https://www.stage.adobe.com/il_he/acrobat/online/pdf-to-ppt.html
- After: 
1. https://www.stage.adobe.com/kw_ar/acrobat/online/pdf-to-ppt.html?mi …
> MWPW-140160 - fixed styles for accordion rtl lang

- libs/blocks/global-navigation/base.css
- libs/blocks/global-navigation/utilities/menu/menu.css
To better match Studio specs and AEM implementation for the upcoming A/B test, a few styling tweaks are needed:
* hide links with gradients on mobile devices;
* lower the lateral padding of links with gradients, as well as the distance between the icon and text;
* limit the icon width of link gradients to `18px`. Looking forward to an eventual full implementation of this feature, authors will need to use the correctly-sized icons themselves;
* align the multi-column headline border and text with its inner-content.
Resolves: [MWPW-140401](https://jira.corp.adobe.com/browse/MWPW-140401)
The story contains the link to the current AEM implementation in the comments section. That one and the Milo one should closely match. An outstanding question is regarding gradient elements font weights - …
> [MWPW-140401] Adapt nav gradient link styles

- libs/features/personalization/personalization.js
The schedule is not shown in Preview when the promo is active, see screenshots.
before 
after 
Resolves: [MWPW-140526](https://jira.corp.adobe.com/browse/MWPW-140526)
**Test URLs:**
- Before: https://main--milo--adobecom.hlx.page/products/special-offers?martech=off
- After: https://promofix--milo--adobecom.hlx.page/products/special-offers?martech=off
> Promo Preview in MEP: fix active schedule display

- tools/loc/rollout.js
This makes grouping track changes style consistent with normal track changes. Also, handles the sanitized styles where track changes info is removed by library.
Resolves: [MWPW-140529](https://jira.corp.adobe.com/browse/MWPW-140529)  & [MWPW-140013](https://jira.corp.adobe.com/browse/MWPW-140013)
> MWPW-140529-140013: group block changes + handling sanitize styles

- libs/features/personalization/preview.css
- libs/features/personalization/preview.js
Because the chat feature is located in the same location as the MEP button, they interfere with each other on pages using both.
Solution, move the MEP button to the bottom left corner (both in mobile and desktop view)
Example: https://business.adobe.com/?mep
Resolves: [MWPW-140272](https://jira.corp.adobe.com/browse/MWPW-140272)
**Test URLs:**
- Before: https://main--milo--adobecom.hlx.page/?mep&martech=off
- After: https://move-mep-btn--milo--adobecom.hlx.page/?mep&martech=off
> MWPW-140272 Move MEP button to the left side

- libs/blocks/how-to/how-to.css
- libs/blocks/how-to/how-to.js
Fixed the how-to grid styles to support full container layouts when authored w/ out a supporting content image. 
* Included a class `.has-image` on the `.foreground` element to apply conditional grid logic. 
Resolves: [MWPW-140321](https://jira.corp.adobe.com/browse/MWPW-140321)
**Test LIVE URLs**
- Before: https://main--cc--adobecom.hlx.page/drafts/00-CC-milo-migration/batch02/products/indesign/presentation-maker#how-to-design-a-presentation-from-scratch
- After: https://main--cc--adobecom.hlx.page/drafts/00-CC-milo-migration/batch02/products/indesign/presentation-maker?milolibs=rparrish-howto-patch#how-to-design-a-presentation-from-scratch
**Test Draft URLs:**
- Before: https://main--milo--adobecom.hlx.page/drafts/rparrish/how-to?martech=off
- After: …
> MWPW-140321 - how-to block - Heading area without Image has gap

- libs/features/personalization/personalization.js
- libs/features/personalization/preview.js
- test/features/personalization/mocks/postPersonalization.html
- test/features/personalization/preview.test.js
Updates made by MEP's replaceContent are highlighted if you use mepHighlight, but replaceFragment updates do not highlight in the same way.
Manifest names in highlight are the full path, making it a much longer string.  Name has been truncated to match the preview button panel format.
Resolves: [MWPW-140273](https://jira.corp.adobe.com/browse/MWPW-140273)
**Test URLs:**
- Before: https://main--milo--adobecom.hlx.page/drafts/vgoodrich/fragments/highlight-replace-fragment/?mepHighlight=true&martech=off
- After: https://highlight-replace-fragment--milo--adobecom.hlx.page/drafts/vgoodrich/fragments/highlight-replace-fragment/?mepHighlight=true&martech=off
> MWPW-140273 Highlight replace fragment

- libs/blocks/ost/ost.js
- test/blocks/ost/mocks/ost-utils.js
- test/blocks/ost/ost.test.html.js
Allow opening OST with landscape=DRAFT
Resolves: [MWPW-140470](https://jira.corp.adobe.com/browse/MWPW-140470)
Only affects OST Tool, so no PSI checks trigger.
**Test URLs:**
- Default OST: https://main--milo--adobecom.hlx.page/tools/ost
- Draft OST: https://ostdraft--milo--adobecom.hlx.page/tools/ost?wcsLandscape=draft
> MWPW-140470: allow OST to overwrite landscape

- libs/blocks/global-navigation/global-navigation.css
- libs/blocks/global-navigation/utilities/menu/menu.css
This helps to set consistent padding for the mobile menu sections of the global navigation.
Resolves: [MWPW-131662](https://jira.corp.adobe.com/browse/MWPW-131662)
**Acrobat:**
- After: https://www.stage.adobe.com/acrobat/online/sign-pdf.html?martech=off&milolibs=mwpw-131662-mobile-menu-padding--milo--robert-bogos
**BACOM:**
- Before: https://main--bacom--adobecom.hlx.page/products/real-time-customer-data-platform/rtcdp?martech=off
- After: https://main--bacom--adobecom.hlx.page/products/real-time-customer-data-platform/rtcdp?martech=off&milolibs=mwpw-131662-mobile-menu-padding--milo--robert-bogos
**CC:**
- Before: https://main--cc--adobecom.hlx.page/?martech=off
- After: …
> MWPW-131662: consistent global navigation padding on mobile

- .github/PULL_REQUEST_TEMPLATE/gnav.md
- libs/blocks/global-navigation/utilities/menu/menu.js
- test/blocks/global-navigation/global-navigation.test.js
This ensures that the element order for the Gnav Promo block is maintained in the final UI. This issue has been introduced by a recent commit to add more consistent spacing for some Gnav elements ([link](https://github.com/adobecom/milo/commit/a07d6e51bef9382576e7998a9c8c2ebdfafe2b45)).
Resolves: [MWPW-140788](https://jira.corp.adobe.com/browse/MWPW-140788)
The Milo test page contains all known promo use-cases, their elements should match the order in which they were added to the document.
**Acrobat:**
- After: https://www.stage.adobe.com/acrobat/online/sign-pdf.html?martech=off&milolibs=gnav-promo-order--milo--overmyheadandbody
**BACOM:**
- Before: https://business.stage.adobe.com/fr/customer-success-stories.ht …
> [MWPW-140788] Ensure correct Gnav Promo element order

- test/blocks/gnav/gnav.test.js
Fixes a broken test for the old gnav, that was failing due to some changes in the core utils where `isSignedInUser` might not be a function for _tests_. In production this should not be an issue since we specifically wait for IMS to properly load, thus this is only a mocking/test issue.
**Test URLs:**
- After: https://fix-failing-gnav-test--milo--adobecom.hlx.page/?martech=off
> Fix broken gnav test

- libs/blocks/quiz-marquee/quiz-marquee.css
- libs/blocks/quiz-results/quiz-results.css
There was some design review feedback on the quiz marquee with a few nested components. 
(aside, commerce cards)
---
1) When a .aside.notification fragment is used in the marquee content, it should display inline on mobile view. App Icon | headline/copy. 
Resolves: [MWPW-140877](https://jira.corp.adobe.com/browse/MWPW-140877)
**Test URLs:**
Before: https://main--cc--adobecom.hlx.live/cc-shared/uar/plan-recommender/quiz-results?primary=lr_indiv,ai_indiv,ps_indiv&quizKey=cc-quiz-en-US&martech=off
After: https://main--cc--adobecom.hlx.live/cc-shared/uar/plan-recommender/quiz-results?primary=lr_indiv,ai_indiv,ps_indiv&quizKey=cc-quiz-en-US&milolibs=rparrish-quiz-marquee-style&martech=off
---
2) When a commerce card fragment is used and only 2 cards are shown they should be evenly spaced and …
> MWPW-140877 - Quiz Marquee style updates

- libs/blocks/aside/aside.css
* The Aside block contains some styles that use the :has() selector to target parent elements of a .milo-video element. This selector unfortunately does not fall within the [Browser Support Matrix](https://wiki.corp.adobe.com/pages/viewpage.action?spaceKey=WP4&title=Test+Automation+Framework) that Adobe uses, as it is only now being implemented in Safari and Firefox.
* [Performing a search over the entire milo repo shows that this is only occurring in the Aside block.](https://github.com/search?q=repo%3Aadobecom%2Fmilo%20%3Ahas&type=code)
* After some testing on my part, it appears that the selector was redundant anyways (Before and After URLs should look the same). If someone believes otherwise, please comment here -- however in the meantime, I propose simply removing the uses of the …
> MWPW-140780 - Remove :has() selector from Aside

- libs/blocks/marketo/marketo.js
- test/blocks/marketo/marketo.test.js
* Fix bug in Marketo form destination url where `.html` is added to trailing slash
Resolves: [MWPW-140660](https://jira.corp.adobe.com/browse/MWPW-140660)
**Test URLs:**
NOTE: Bug only seen on .html pages
- Before: https://main--milo--adobecom.hlx.page/drafts/methomas/aemshowcase?martech=off
- After: https://methomas-marketo-html--milo--adobecom.hlx.page/drafts/methomas/aemshowcase?martech=off
BACOM:
- Before: https://business.stage.adobe.com/resources/demo/aemshowcase.html
- After: https://business.stage.adobe.com/resources/demo/aemshowcase.html?milolibs=methomas-marketo-html
> MWPW-140660 Fix Marketo Destination Url

- libs/blocks/icon-block/icon-block.css
When inside of a section grid the icon block shouldn't have auto margin. This PR unsets that rule for inline icon blocks when they are found within a section grid.
Resolves: [MWPW-140538](https://jira.corp.adobe.com/browse/MWPW-140538)
**Test URLs:**
- Before: https://main--milo--adobecom.hlx.page/drafts/sarchibeque/icon-inline-inups?martech=off
- After: https://sarchibeque-mwpw-140538-iconinline--milo--adobecom.hlx.page/drafts/sarchibeque/icon-inline-inups?martech=off
> MWPW-140538 - Icon Block inline margin

- libs/blocks/merch-card/merch-card.js
- libs/deps/merch-card.js
This PR fixes the following: 
* Custom `<hr>` color or gradient when present.
* Cleans up EDS-generated DOM in Merch Card whenever an `<hr>` is present.
* Updates merch-card dependency
* Fixes `inline-heading` and `product` XS-heading positioning ([MWPW-140282](https://jira.corp.adobe.com/browse/MWPW-140282))
Resolves: [MWPW-140191](https://jira.corp.adobe.com/browse/MWPW-140191)
**Test URLs:**
- Before: https://main--milo--adobecom.hlx.page/docs/library/kitchen-sink/merch-card
- After: https://mwpw-140191--milo--adobecom.hlx.page/docs/library/kitchen-sink/merch-card
> MWPW-140191: Fixes Merch Card custom <hr> color, inline heading variant

- libs/blocks/faas/utils.js
- test/blocks/faas/utils.test.js
Resolves: 
https://workfront.slack.com/archives/C03B0BUA75E/p1704493717108139
**Test URLs:**
- Before: https://main-fix--milo--adobecom.hlx.page/drafts/seanchoi/faas-link-test?martech=off
- After: https://faas-fix--milo--adobecom.hlx.page/drafts/seanchoi/faas-link-test?martech=off
Note that `qa` environment requires company network or VPN connection.
> faas-env default qa

- libs/blocks/marquee/marquee.css
* At some point early on in the life of the marquee block, it must have made sense to remove the `.foreground` gap for large marquees. Now, however, the current design of all marquees requires it. This PR gives large marquees consistent spacing.
Resolves: [MWPW-140738](https://jira.corp.adobe.com/browse/MWPW-140738)
**Test URLs:**
- Before: https://main--cc--adobecom.hlx.page/drafts/dmosier/block-exploration-pages/marquee-text-spacing?martech=off
- After: https://main--cc--adobecom.hlx.page/drafts/dmosier/block-exploration-pages/marquee-text-spacing?milolibs=ebartholomew-lg-marquee-gap&martech=off
> MWPW-140738 - Add foreground gap on large marquees

- libs/blocks/quiz-results/quiz-results.css
* set the widths of merch cards as 300px if screen less than 900 
* set the widths of merch cards as 378px if screen up to 900 
Resolves: [MWPW-141124](https://jira.corp.adobe.com/browse/MWPW-141124)
**Test URLs:**
- Before: https://uar-integration--milo--adobecom.hlx.live/drafts/quiz/quiz-2/?martech=off
- After: https://mwpw-141124--milo--jackysun9.hlx.live/drafts/quiz/quiz-2/?martech=off
You can view merch cards from https://main--milo--adobecom.hlx.page/docs/library/kitchen-sink/merch-card
> MWPW-141124: match widths used by standard merch cards

- libs/blocks/global-footer/global-footer.css
This handles the use-case where 3 or fewer columns are authored for the Footer. Right now the columns span to the full width of the footer, regardless of their number or width, leading to suboptimal UI on desktop devices.
Additionally, a `max-width` property has been removed, as its value, `auto`, is invalid - https://developer.mozilla.org/en-US/docs/Web/CSS/max-width
Resolves: [MWPW-140624](https://jira.corp.adobe.com/browse/MWPW-140624)
On a test page, add/remove footer columns to check out the resulting layout.
| <img width="1486" alt="Screenshot 2024-01-11 at 15 22 35" src="https://github.com/adobecom/milo/assets/11267498/341bbbe3-d9f5-45ab-b5be-3f60fa0fe448"> | <img width="1486" alt="Screenshot 2024-01-11 at 15 22 04" …
> [MWPW-140624] Footer layout with few columns

- libs/blocks/quiz-results/quiz-results.js
- libs/blocks/quiz/utils.js
* add a method to remove characters other than alpha-numeric
* standardized on no dashes or spaces in property names
Resolves: [MWPW-137932](https://jira.corp.adobe.com/browse/MWPW-137932)
**Test URLs:**
- Before: https://main--milo--adobecom.hlx.page/drafts/xiasun/quiz-2/?martech=off
- After: https://mwpw-137932-bulletproof-property-names--milo--colloyd.hlx.page/drafts/colloyd/quiz/?martech=off
Testing notes: To test, observe the following URL on milo main: https://main--milo--adobecom.hlx.page/drafts/colloyd/quiz/
Note the odd characters in the property names that are causing block load failure. This is the same page used for the "After" URL above.
The same has been done for two result pages, though you will have to submit a quiz to generate local storage data before observing them and …
> MWPW-137932 - Bullet-proof quiz and result metadata keys

- libs/blocks/merch/merch.js
- test/blocks/merch/merch.test.js
- test/blocks/merch/mocks/body.html
This reverts commit 104ff1a94b878e0b6a711e7d0d81caddeddf0b3e.
Reverts the changes during the backward compatibility. 
Original PR description: 
Title: Cta as linked text
Authors can link text strings with checkout links.
Screenshot 2024-01-17 at 12 48 37 PM
Resolves: [MWPW-135731](https://jira.corp.adobe.com/browse/MWPW-135731)
Test URLs:
Before: https://main--milo--adobecom.hlx.page/drafts/vkniaziev/document9?martech=off
After: https://mwpw-135163--milo--vkniaz.hlx.page/drafts/vkniaziev/document9?martech=off
> Revert "MWPW-1351731 support linked text (#1749)"

- libs/utils/utils.js
Got a suggestion I liked right after merging. Switching to doing an early return if mep is disabled with mep=off flag
Resolves: [MWPW-141639](https://jira.corp.adobe.com/browse/MWPW-141639)
Test URLs:
Before: https://main--milo--adobecom.hlx.page/drafts/vgoodrich/fragments/mepmartechoff/?mep=off
After: https://mepoffearlyreturn--milo--adobecom.hlx.page/drafts/vgoodrich/fragments/mepmartechoff/?mep=off
> MWPW-141639 Quick follow to do an early return if mep=off

- libs/blocks/marquee/marquee.css
- libs/utils/decorate.js
Fixes issue with Marquee block breakpoint background colors not displaying.
**Context:**
When a marquee is authored to use background breakpoints and a hex color or gradient is authored for the background, the background does not display. The reason being, the color or gradient is applied via an inline style to a div element with no content. Making the breakpoint div empty and collapsing when the block renders.
This isn't a problem when using a image or video as those are nested in the breakpoint div with content and styled appropriately. 
Resolves: [MWPW-141387](https://jira.corp.adobe.com/browse/MWPW-141387)
**Test URLs:**
- Before: https://main--milo--adobecom.hlx.page/drafts/rclayton/poc/marquee-breakpoint-bug?martech=off
- After: …
> MWPW-141387 Marquee background colors bug

- libs/blocks/table/table.css
Adding left text alignment option for GWP.
Resolves: https://workfront.slack.com/archives/C03B0BUA75E/p1706138939114819?thread_ts=1706129531.953969&cid=C03B0BUA75E
**Test URLs:**
- Before: https://main--milo--adobecom.hlx.page/docs/library/blocks/table?martech=off
- After: https://table-left--milo--adobecom.hlx.page/docs/library/blocks/table?martech=off
Left example:
https://main--bacom--adobecom.hlx.page/drafts/karchie/premier-support?milolibs=table-left
> left option enabled.

- libs/blocks/global-navigation/global-navigation.js
- libs/scripts/scripts.js
This PR updates the custom ietf locale logic for the universal navigation to match the [mapping received from the Universal Navigation team.](https://git.corp.adobe.com/wcms/hawks/pull/3080/files)
Resolves: [MWPW-141810](https://jira.corp.adobe.com/browse/MWPW-141810)
**Milo:**
- Before:  https://gnav--milo--adobecom.hlx.page/drafts/rbogos/unav?martech=off
- After: https://mwpw-141810-update-locales-unav--milo--robert-bogos.hlx.page/drafts/rbogos/unav?martech=off
> MWPW-141810: updated custom ietf locale logic for unav

- libs/blocks/merch-card/merch-card.js
- test/blocks/merch-card/merch-card.test.js
- test/blocks/merch-card/mocks/mini-compare-chart.html
Adds support for quantity selector in Mini compare chart card.
Resolves: [MWPW-138103](https://jira.corp.adobe.com/browse/MWPW-138103)
**Test URLs:**
- Before: https://main--milo--adobecom.hlx.page/drafts/axel/mini-compare-chart
- After: https://mwpw-141691--milo--adobecom.hlx.page/drafts/axel/mini-compare-chart
> Mwpw 138103:  Quantity selector in mini compare chart card

- libs/blocks/global-navigation/global-navigation.js
- libs/scripts/scripts.js
This PR syncs the analytics from Dunamis to AA
Resolves: [MWPW-140229](https://jira.corp.adobe.com/browse/MWPW-140229)
1. click on any element from the universal navigation;
2. go to the network tab in dev tools;
3. search for 'collect' and you'll find the sent tag inside the payload, as you can see in the screenshot below;
The sent tags can be verified against https://wiki.corp.adobe.com/pages/viewpage.action?spaceKey=marketingtech&title=Universal+Nav+on+Adobe.com+-+Custom+Tracking
**Milo:**
- Before: https://gnav--milo--adobecom.hlx.page/drafts/rbogos/unav?martech=off
- After: https://mwpw-140229-sync-unav-analytics--milo--robert-bogos.hlx.page/drafts/rbogos/unav?martech=off
> MWPW-140229: Sync Universal Nav analytics from Dunamis to AA

- libs/blocks/global-navigation/global-navigation.css
This ensures that the Universal Nav dropdown menus and their tooltips are visible when browsing on a mobile viewport in Safari 16.
Resolves: [MWPW-142055](https://jira.corp.adobe.com/browse/MWPW-142055)
Use Safari 16 on a mobile viewport and log in. Hover and click the Utility Navigation icons and notice that their tooltips and dropdown menus are visible.
**Milo:**
- Before: https://gnav--milo--adobecom.hlx.page/drafts/narcis/default?martech=off
- After: https://gnav--milo--overmyheadandbody.hlx.page/drafts/narcis/default?martech=off
> [MWPW-142055] Ensure UNav dropdowns are visible on Safari

- libs/features/personalization/personalization.js
The personalization fragment preload was not localizing links, therefore loading the us/en page for localized pages.
Resolves: [MWPW-142058](https://jira.corp.adobe.com/browse/MWPW-142058)
Before url will load `emea-cct-arobat-q1-promo-footnote` twice - first is the us/en fragment, 2nd is the africa fragment.
After url will only load the africa fragment.
**Test URLs:**
- Before: https://main--homepage--adobecom.hlx.page/africa/homepage/index-loggedout
- After: https://main--homepage--adobecom.hlx.page/africa/homepage/index-loggedout?milolibs=locfragmentpreload
> MWPW-142058 Localize fragment preload

- libs/features/jarvis-chat.js
Problem: Alloy might throw errors if an incorrect configuration is being used. This will block Jarvis chat to load, since it has a dependency on the user information.
Fix: Handle alloy errors and initialise Jarvis regardless of the response.
Resolves: [MWPW-141779](https://jira.corp.adobe.com/browse/MWPW-141779)
**Test URLs:**
- After: https://jarvis-fix--milo--narcis-radu.hlx.page/drafts/narcis/default?martech=off
> [MWPW-141779] Make sure Jarvis chat gets loaded regardless of alloy response / errors

- libs/blocks/aside/aside.css
When an author uses the `section.static-links` style with an `aside.notification.extra-small`, the link color is not applied because of a style that targets trailing links that aren't styled as buttons. I am adding an additional style that sets color to `inherit` when aside is nested in a section with static links style.
Note: I also removed a duplicate selector that was creating a styleLint error
Resolves: [MWPW-140456](https://jira.corp.adobe.com/browse/MWPW-140456)
**Test URLs:**
- Before: https://main--milo--adobecom.hlx.page/drafts/sarchibeque/aside-links?martech=off
- After: https://sarchibeque-mwpw-140456-aside-links--milo--adobecom.hlx.page/drafts/sarchibeque/aside-links?martech=off
> MWPW-140456 - [Aside] fix notification static links color

- libs/utils/utils.js
* Moves georouting to post-LCP event for performance improvements
* Meaningfully improves georouting pages with low lighthouse scores due to LCP
* Has little/no change on georouting pages with high lighthouse scores
* Has little/no change to pages without georouting
* May increase CLS in some cases on georouting pages but has overall positive effect on lighthouse score because of LCP improvement
Resolves: [MWPW-141594](https://jira.corp.adobe.com/browse/MWPW-141594)
**Bacom FR Homepage:**
Lighthouse score: 79 -> 94
LCP: 5.6s -> 3.0s
**CC Business Card Design Page:**
Lighthouse score: 75 -> 98
LCP: 1.9s -> 1.7s
**Test URLs:**
(Copied from Bacom AEM sites product page)
- Before: https://main--milo--adobecom.hlx.page/de/drafts/methomas/aem-sites?martech=off
- After: …
> MWPW-141594 Move georouting to post LCP

- libs/blocks/section-metadata/section-metadata.css
Z index of sticky bottom section is lesser that carousel buttons and tabList causing an overlap of page content on sticky bottom component on scroll.
Increasing the z-index of sticky bottom to avoid the overlap.
Resolves: [MWPW-140884](https://jira.corp.adobe.com/browse/MWPW-140884)
**Test URLs:**
- Before: https://main--milo--adobecom.hlx.page/drafts/venkatas/testpages/aside-notification?martech=off
- After: https://mwpw-140884--milo--aishwaryamathuria.hlx.page/drafts/venkatas/testpages/aside-notification?martech=off
> MWPW-140884| Increase z index of sticky bottom section

- libs/blocks/brick/brick.css
Full width 12 column grid currently has foreground image that takes L spacing from top and bottom. As per the latest requirement updating the brick foreground image to have 100% height like other bricks without L spacing.
Resolves: [MWPW-142072](https://jira.corp.adobe.com/browse/MWPW-142072)
**Test URLs:**
- Before: https://main--milo--aishwaryamathuria.hlx.page/drafts/mathuria/masonry/poc/poc-7?martech=off
- After: https://mwpw-142072--milo--aishwaryamathuria.hlx.page/drafts/mathuria/masonry/poc/poc-7?martech=off
> MWPW-142072 | Making full width brick foreground image have full height

- libs/blocks/quiz/quiz.css
- libs/blocks/quiz/quizcontainer.js
* simplified background image markup
* minor css adjustments to maintain the current display
Resolves: [MWPW-142089](https://jira.corp.adobe.com/browse/MWPW-142089)
**Test URLs:**
- After: https://mwpw-142089-quiz-bg-markup--milo--colloyd.hlx.page/drafts/colloyd/quiz/?martech=off
Testing notes:
- inspect .quiz-background in the dev tools
- in the "before" page, notice the extraneous markup including picture with source and img
- in the "after" page, notice the simplified img tag only.
> MWPW-142089 - Quiz background markup cleanup

- libs/blocks/merch-card/merch-card.js
- test/blocks/merch-card/mocks/mini-compare-chart.html
Resolves: [MWPW-141691](https://jira.corp.adobe.com/browse/MWPW-141691)
This PR supports merch cards in fragments.
**Test URLs:**
- Before: https://main--milo--adobecom.hlx.page/drafts/axel/mini-compare-chart?martech=off
- After: https://mwpw-141691-2--milo--yesil.hlx.page/drafts/axel/mini-compare-chart?martech=off
**CC**
https://main--cc--adobecom.hlx.page/cc-shared/fragments/merch/products/illustrator/mini-compare/segment-blade?milolibs=mwpw-141691-2--milo--yesil
> MWPW-141691: Footer rows of merch-cards in fragments

- libs/features/personalization/preview.js
Using the edit manifest button only works when you are signed into the sidekick.  Updating message for better feedback.
To test, go to the test urls while signed out of the sidekick, open the MEP preview button panel, then click the pencil icon next to the test name.
**Test URLs:**
- Before: https://main--milo--adobecom.hlx.page/drafts/vgoodrich/fragments/2024/q1/autoselectorubc/?martech=off
- After: https://autoselectorubc--milo--adobecom.hlx.page/drafts/vgoodrich/fragments/2024/q1/autoselectorubc/?martech=off
> improve redirect message for edit manifest button in sidekick

- libs/blocks/global-footer/global-footer.js
- libs/blocks/global-navigation/features/breadcrumbs/breadcrumbs.js
- libs/blocks/global-navigation/features/profile/dropdown.js
- libs/blocks/global-navigation/features/search/gnav-search.js
- libs/blocks/global-navigation/global-navigation.js
- libs/blocks/global-navigation/utilities/menu/menu.js
- libs/blocks/global-navigation/utilities/utilities.js
- test/blocks/global-navigation/global-navigation.test.js
- test/blocks/global-navigation/mocks/global-navigation.plain.js
- test/blocks/global-navigation/test-utilities.js
- test/blocks/global-navigation/utilities/utilities.test.js
Adds the possibility to centralize globalnav content such as large menu's by supplying a link from the project for centralized milo content such as https://main--federal--adobecom.hlx.live/federal/globalnav/drafts/osahin/gnav - which can be reused across any milo consumer.
On (www.|business.|blog.|milo.)adobe.com this would simply be mapped to `/federal/globalnav/drafts/osahin/gnav` and does not require any extra TLS handshake.
**There is no extra setup needed for any milo consumer** - subdomains or domains without any extra setup will simply default fetching central content from `www.adobe.com/federal/...` 
The overarching idea of this is that `https://main--federal--adobecom.hlx.live` serves as a content hub for anything that is shared across consumers. In the (near) future 404s can be …
> GNAV & Footer content centralisation

- libs/blocks/modal/modal.css
Twp Modal not displaying in tablet viewports or smaller on Safari.
This is a relatively well know limitation of Safari, we should use `100vh` instead of `100%`
Resolves: [MWPW-142399](https://jira.corp.adobe.com/browse/MWPW-142399)
Test URLs:
https://mwpw-142399--milo--adobecom.hlx.page/
**Home Page**
Before: https://main--homepage--adobecom.hlx.live/homepage/index-loggedout?martech=off&#mini-plans-web-cta-photoshop-card
After: https://main--homepage--adobecom.hlx.live/homepage/index-loggedout?martech=off&milolibs=mwpw-142399#mini-plans-web-cta-photoshop-card
**CC**
Before: https://main--cc--adobecom.hlx.live/creativecloud/animation/discover?martech=off#animate
After: https://main--cc--adobecom.hlx.live/creativecloud/animation/discover?martech=off&milolibs=mwpw-142399#animate
> MWPW-142399-Fix for TwP modal not displaying in tablet viewports or smaller on Safari

- libs/blocks/text/text.js
* Fix link farm text block failing to load when no heading is added
Resolves: [MWPW-142499](https://jira.corp.adobe.com/browse/MWPW-142499)
**Test URLs:**
- Before: https://main--milo--adobecom.hlx.page/drafts/ruchika/link-farm?martech=off
- After: https://link-farm--milo--ruchika4.hlx.page/drafts/ruchika/link-farm?martech=off
CC:
- Before: https://main--cc--adobecom.hlx.page/creativecloud/file-types/image/comparison?martech=off
- After: https://main--cc--adobecom.hlx.page/creativecloud/file-types/image/comparison?milolibs=link-farm--milo--ruchika4&martech=off
Note: Issue was identified on production page
> MWPW-142499-Fix link farm text block failing to load when no heading is added

- libs/blocks/global-navigation/utilities/utilities.js
Decorate links decorates anchor tags and turns them into images if applicable.
After we have images, we have a method that checks if an image should come from a federal source and not a relative path. 
Resolves: [MWPW-142610](https://jira.corp.adobe.com/browse/MWPW-142610)
The adobe logo on the left side of the gnav should be showing up on centralized navigations, when including as a link to a centralized image/svg
**Acrobat:**
- After: https://www.stage.adobe.com/acrobat/online/sign-pdf.html?martech=off&milolibs=mwpw-142610-svgs--milo--mokimo
**BACOM:**
- Before: https://business.stage.adobe.com/fr/customer-success-stories.html?martech=off
- After: https://business.stage.adobe.com/fr/customer-success-stories.ht …
> Correctly decorate SVGs in central navs

- libs/blocks/merch-card/merch-card.js
- libs/blocks/modal/modal.css
- libs/blocks/modal/modal.js
- test/blocks/modals/modals.test.js
**How it works now:**
In the current implementation, when the commerce modal is open, we establish a message event listener to address two scenarios:
- If the page within the iFrame cannot detect its viewport width due to CORS restrictions, it may request the viewport width from the parent page.
- The page within the iFrame measures its content height and sends this information to adjust the modal height, eliminating any blank space at the bottom.
Upon closing the commerce modal, we remove the message event listener using the abortController.
Additionally, the dynamic import of the debounce function has been optimized by relocating it outside the function that is invoked within the event listener, ensuring that the import is executed only once. The debouncing time decreased from 50 to 10 …
> MWPW-141638: Fix for commerce modals event listeners

- libs/blocks/merch-card/merch-card.js
Fixes scenario where mini compare chart cards are inside individual fragments and container inside tabs. This causes the intersection observer to not trigger at all since the cards are not yet loaded in the DOM. This fixes forces the intersection observer to resize even thought the cards are not intersecting yet.
Resolves: [MWPW-142003](https://jira.corp.adobe.com/browse/MWPW-142003)
**Test URLs:**
- Before: https://main--cc--adobecom.hlx.page/cc-shared/fragments/merch/products/illustrator/mini-compare/segment-blade?martech=off
- After: https://main--cc--adobecom.hlx.page/cc-shared/fragments/merch/products/illustrator/mini-compare/segment-blade?milolibs=MWPW-142003--milo--axelcureno?martech=off
> Mwpw 142003: Mini compare chart edge case scenario

- libs/blocks/merch/merch.js
- test/blocks/merch/merch.test.js
Resolves: [MWPW-142786](https://jira.corp.adobe.com/browse/MWPW-142786)
**Test URLs:**
- Before: https://main--milo--adobecom.hlx.page/drafts/ilyas/checkout-links?martech=off&georouting=off
- After: https://mwpw-142786--milo--yesil.hlx.page/drafts/ilyas/checkout-links?martech=off&georouting=off
**CC Test URLs (with IMS)**:
https://main--cc--adobecom.hlx.page/drafts/ilyas/checkout-links?milolibs=mwpw-142786--milo--yesil
> MWPW-142786: skip Download flow if url is empty

- libs/blocks/marquee/marquee.css
- libs/blocks/marquee/marquee.js
Pages with both Marquee and Media blocks now have cls scores due to the media.css .media padding style being applied to .marquee .media. This PR updates the Marquee's .media classname to instead be .asset to avoid future collisions.
Re-issuing CLS fix sans the style lint error updates that were reverted in this [PR](https://github.com/adobecom/milo/pull/1867)
Resolves: [MWPW-142630](https://jira.corp.adobe.com/browse/MWPW-142630)
**MILO**
Before: https://main--milo--adobecom.hlx.page/drafts/sarchibeque/marquee-cls?martech=off
After: https://sarchibeque-mwpw-142630-marquee-cls--milo--adobecom.hlx.page/drafts/sarchibeque/marquee-cls?martech=off
**BACOM**
Before: https://main--bacom--adobecom.hlx.page/products/experience-manager/adobe-experience-manager?martech=off
After: …
> MWPW-142630 - [Marquee] media CLS

- libs/blocks/share/share.css
* Fix spacing between share icons for RTL pages
Resolves: [MWPW-142937](https://jira.corp.adobe.com/browse/MWPW-142937)
**Test URLs:**
- Before: https://main--milo--adobecom.hlx.page/ae_ar/drafts/ruchika/share1?martech=off
- After: https://share--milo--ruchika4.hlx.page/ae_ar/drafts/ruchika/share1?martech=off
CC:
- Before: https://main--cc--adobecom.hlx.live/ae_ar/creativecloud/file-types/image/comparison?martech=off
- After: https://main--cc--adobecom.hlx.live/ae_ar/creativecloud/file-types/image/comparison?milolibs=share--milo--ruchika4?martech=off
> MWPW-142937-Fix spacing between share icons for RTL pages

- libs/martech/martech.js
Some of the target data is unrelated to manifests, this makes sure we don't try to use that data.
**Test URLs:**
- After: https://verifytargetmanifest--milo--adobecom.hlx.page/?martech=off
> Verify that target content has manifest info

- libs/blocks/icon-block/icon-block.css
Reverts adobecom/milo#1854
from @ryanmparrish:
Hi all. There was a [bug](https://jira.corp.adobe.com/browse/MWPW-142278) w/ tablet/ipad alignment that 
[@dmodasara](https://adobe-mwp.slack.com/team/U03FFSK2MV4)
worked on yesterday however this recently merged [PR](https://github.com/adobecom/milo/pull/1854) broke the alignment on icon-block.inline.
https://main--milo--adobecom.hlx.page/drafts/rparrish/icon/icon-block-inline-milo
https://main--cc--adobecom.hlx.page/products/illustrator/free-trial-download (edited)
> Revert "Mwpw 142278: Thumbnail icons are not aligned vertically on iPad- fix"

- libs/blocks/caas-marquee/caas-marquee.js
- libs/utils/utils.js
Increases LH score for CaaS Marquee from 62 to 93.
Before:
After:
We may be able to further increase this score by making some more optimizations to our backends. Will try next week and see if this bears any fruit.
Resolves: https://jira.corp.adobe.com/browse/MWPW-143183
**Test URLs:**
- Before: https://main--milo--adobecom.hlx.live/drafts/sanrai/marquee-viewer/prod/recommendations
- After: https://caas-marquee-perf-2--milo--adobecom.hlx.live/drafts/sanrai/marquee-viewer/prod/recommendations
> MWPW-143183: CaaS Marquee Performance Improvements

- libs/features/personalization/personalization.js
- test/features/personalization/personalization.test.js
In Milo, some pages have '.html' extensions on Live, but not on Production:
Live: https://www.adobe.com/products/special-offers.html 
Prod: https://main--cc--adobecom.hlx.live/products/special-offers 
When providing a page filter in the MEP manifest, Authors shouldn't be required to put in a regex to match both cases.
MEP can assume and accept the optional HTML extension.
Resolves: [MWPW-143135](https://jira.corp.adobe.com/browse/MWPW-143135)
**Test URLs:**
- Before: https://main--milo--adobecom.hlx.live/drafts/mariia/pr/promo/promo?martech=off
- After:  https://htmlextension--milo--adobecom.hlx.live/drafts/mariia/pr/promo/promo?martech=off
> MWPW-143135: mep page filter to auto match optional .html extension

- libs/blocks/quiz/quiz.js
- test/blocks/quiz/mocks/mock-states.js
- test/blocks/quiz/quiz.test.js
* Renders the quiz at any point as captured in local storage
Resolves: [MWPW-139939](https://jira.corp.adobe.com/browse/MWPW-139939)
**Test URLs:**
- After: https://mwpw-139939-load-userflow-from-local-storage--milo--colloyd.hlx.page/drafts/colloyd/quiz/?martech=off
Testing Notes: To test this code, you will need to load up the URLs above and set the following in local storage for each
- key: stored-quiz-state
- value: {"userFlow":["q-rather","q-photo","q-video","q-design"],"userSelection":[{"selectedQuestion":{"questions":"q-category","max-selections":"3","min-selections":"1"},"selectedCards":{"photo":true,"video":true,"design":true}}]}
In the before page, the quiz will load the first question as normal. In …
> MWPW-139939 - Support for quiz state in local storage

- libs/blocks/locui/locui.css
- libs/blocks/locui/url/index.js
- libs/blocks/locui/url/tabs.js
- libs/blocks/locui/utils/franklin.js
When users sync to `langstore/en` the documents aren't automatically synced to preview. In current implementation when an action is clicked the user is simply navigated to the url in question without actually deploying the preview.
This PR updates UI urls action preview button to pre-request preview process before navigating to the page, also includes error handling for when documents do not exist in the langstore:
Resolves: [MWPW-141132](https://jira.corp.adobe.com/browse/MWPW-141132)
**Test URLs:**
- Before: https://locui--milo--adobecom.hlx.page/tools/loc?ref=main&repo=milo&owner=adobecom&host=milo.adobe.com&project=Milo&referrer=https%3A%2F%2Fadobe.sharepoint.com%2F%3Ax%3A%2Fr%2Fsites%2Fadobecom%2F_layouts%2F15%2FDoc.aspx%3Fsourcedoc%3D%257B7c5698f5-0ae1-4219-b0b1-38bea4c22b84%257D%26a …
> MWPW-141132 - [Milo Loc V2] urls preview

- libs/blocks/locui/actions/index.js
**_As a web producer, we need to allow all nested fragments to be added to LOC pages on a single click._**
**Solution:**
For each url configured in a project, when the `Find Fragments` button is clicked that event will execute a function that will search each fragment for nested fragments, levels deep, until all fragments are found.
**Testing:**
Test this functionality locally by checking out this branch and running `aem up`.
1. Create a new loc v2 project in sharepoint and add test URL (https://main--milo--adobecom.hlx.page/drafts/sarchibeque/find-fragments-test) or add your own page with nested fragments.
2. Finish configuration of loc project.
3. Open loc v2 project and copy pathname to localhost instance to run the new code locally.
4. Click `Find Fragments` after the project has …
> MWPW-130939 - [Milo Loc v2] Find Nested Fragments

- libs/blocks/library-container-end/library-container-end.css
- libs/blocks/library-container-start/library-container-start.css
- libs/blocks/library-metadata/library-metadata.css
- libs/blocks/library-metadata/library-metadata.js
* Fixes layout issues caused by `library-container-start`, `library-container-end` `library-metadata blocks`. 
* Hides `library-container-start` and `library-container-end` blocks from preview example.
*Note: This fix is only for the previewing of blocks from the block library. This code never makes it way to published content.
---
Resolves: [MWPW-143825](https://jira.corp.adobe.com/browse/MWPW-143825)
**Test URLs:**
- Before: https://main--milo--adobecom.hlx.page/docs/library/blocks/patterns?martech=off
- After: https://block-grouping--milo--adobecom.hlx.page/docs/library/blocks/patterns?martech=off
- Before: https://main--milo--adobecom.hlx.page/docs/library/blocks/bricks?martech=off
- After: https://block-grouping--milo--adobecom.hlx.page/docs/library/blocks/bricks?martech=off
- …
> MWPW-143825 - Block library block grouping

- libs/blocks/global-navigation/utilities/utilities.js
- test/blocks/global-navigation/global-navigation.test.js
- test/blocks/global-navigation/test-utilities.js
- test/blocks/global-navigation/utilities/utilities.test.js
EDS [doesn't support](https://discord.com/channels/1131492224371277874/1144495462255185971/1214164790822567936) fetching cross consumer content. We proxy content through the CDN to maintain a good authoring and developers experience.
- **localhost, .hlx.page, .hlx.live:** fetch from www.(stage.)adobe.com (might require VPN)
- **stage/prod:** fetch from (bacom|milo|blog|www).(stage.)adobe.com
Resolves: [MWPW-143811](https://jira.corp.adobe.com/browse/MWPW-143811)
- Be on VPN
- Log in on a consumer page that uses federal content
- See the federal nav popping up, without further authentication 
Regression links
- https://milo.stage.adobe.com/drafts/osahin/gnav-1?martech=off#
- https://milo.adobe.com/drafts/osahin/gnav-1?martech=off# 
**Milo hlx.page now fetches content from stage.adobe.com** …
> Setup the federal stage environment

- libs/scripts/scripts.js
- libs/utils/utils.js
This aims to adapt the IMS `scope` configuration property based on the Universal Navigation enablement on the page.
To make use of the Universal Navigation features, additional scopes need to be used. However, if those scopes are defined, but not configured in IMSS for the respective client ID, the IMS library will fail to load, thus users would no longer be able to sign in or see their profile.
The desire is to define those additional scopes only on pages using the Universal Navigation. This tailors to Milo consumers that have not set their own scopes and instead rely on some sensible defaults.
The change has been made in two places:
* _scripts.js_ - this is where the Milo-specific configs are defined, we want to have this change here to make sure the Universal Navigation feature works …
> [MWPW-143313] IMS scopes based on UNav enablement

- libs/blocks/locui/actions/index.js
Finding nested fragments needs to check for duplicates during search. I have updated the function to filter searched pathnames.
Resolves: [MWPW-144237](https://jira.corp.adobe.com/browse/MWPW-144237)
**Test URLs:**
- Before: https://main--milo--adobecom.hlx.page/drafts/sarchibeque/find-fragments-test?martech=off
- After: https://main--milo--adobecom.hlx.page/drafts/sarchibeque/find-fragments-test?martech=off
> MWPW-144237 - [Loc v2] Fix find deep fragments

- libs/blocks/caas-marquee/caas-marquee.js
Problem:
AEP Audiences unavailable for CaaS Marquees when Target is enabled on a page
This PR fixes some issues that surfaced while integration the caas-marquee code with target for the A-B testing
After this code was merged to main (prod) ant testing began it was noticed that there was problem when martech.js was injected in the page, and as a result the caas-marquee code was never able to catch a windowEvent needed for proper functioning.  
The following fix was provided by @chrischrischris
Resolves: [MWPW-144461](https://jira.corp.adobe.com/browse/MWPW-144461)
Before:  https://www.adobe.com/
After:  https://www.adobe.com/?test=target&mep=
- https://www.adobe.com/?test=target&mep=
- https://caas-marquee--milo--adobecom.hlx.page/
> Caas-Marquee: Fixes integration with martech.js issues

- libs/blocks/quiz/quizcontainer.js
- libs/blocks/quiz/quizoption.js
* Add id to the h1
* set role and aria-labelledby on the option container
* swap to role-checkbox and aria-checked for option buttons
* use disabled instead of tabindex -1 Resolves: [MWPW-143799](https://jira.corp.adobe.com/browse/MWPW-143799)
**Test URLs:**
- After: https://mwpw-143799-accessibility-enhancements--milo--colloyd.hlx.page/drafts/colloyd/quiz/?martech=off
> MWPW-143799 - Quiz Accessibility Refinement

- libs/blocks/modal/modal.merch.js
Fix for commerce modal height breaking in milo.
Affected page: https://www.adobe.com/products/illustrator/campaign/pricing.html?mboxDisable=1&adobe_authoring_enabled=true#cc-all-apps-upsell-blade-swi-link
**Test URLs:**
> MWPW-144575: Fix for commerce modal height

- libs/features/personalization/personalization.js
- libs/features/personalization/preview.js
- test/features/personalization/preview.test.js
Detailed Description: the MEP parameter supports multiple manifests by using a comma to separate the manifest/experience pairs. This delimiter was chosen before the MEP manifests supported commas in the column names. These 2 features collide when trying to spoof a column containing a comma.
URL: https://main--cc--adobecom.hlx.page/products/premiere?mep=%2Fproducts%2Fpremiere.json--cc-all-apps-any%2C+premiere-any%2C%2Fcc-shared%2Ffragments%2Fpromos%2F2024%2Famericas%2Fcci-all-apps-q1%2Fcci-all-apps-q1.json--all
1. Go to the link above
2. Use the MEP button to preview an experience with a comma
3. Check the MEP button panel again.
Expected Results: The experience you previously selected will be chosen …
> [MILO][MEP] MEP parameter spoof breaks if chosen experience has a comma

- libs/features/personalization/personalization.js
- libs/features/personalization/preview.js
- test/features/personalization/actions.test.js
- test/features/personalization/cleanAndSortManifestList.test.js
- test/features/personalization/deprecatedActions.test.js
- test/features/personalization/mocks/manifestLists/three-manifest-types-all-normal.json
- test/features/personalization/mocks/manifestLists/three-manifest-types-one-first.json
- test/features/personalization/mocks/manifestLists/three-manifest-types-one-last.json
- test/features/personalization/mocks/manifestLists/three-manifest-types-one-no-type.json
- test/features/personalization/mocks/manifestLists/three-manifest-types-one-test-or-promo.json
- test/features/personalization/mocks/manifestLists/two-duplicate-manifests-one-from-target.json
- test/features/personalization/mocks/manifestLists/two-duplicate-manifests-other-one-from-target.json
- test/features/personalization/mocks/manifestLists/two-manifests-one-from-target.json
- test/features/personalization/personalization.test.js
- test/features/personalization/preview.test.js
- test/utils/utils.test.js
Redoing the PR.  At some point file changes that weren't mine were being counted as my file updates.
Problem statement: The current order that MEP executes manifests is based on the source of the manifest. Instead, we need to use the manifest type to be sure that the manifests execute in a logical order. 
Requirements:
- Separate Manifest Type "Test or Promo" into 2 separate items in the dropdown.
- Add a Manifest Execution Order, default value "normal", other values "first" and "last"
- Manifest order will first be determined the the manifest execution order field: first, normal then last.
- If there is more than one manifest of the same "execution order", the manifest type will break the tie. First Personalization, Promo then Test.
Note: previously, we would:
1. run `cleanManifestList` …
> [MILO][MEP] Update Manifest Type and Manifest Ordering v2

- libs/blocks/fallback/fallback.js
This ensures that the Cross Cloud Menu block, used as part of Global Navigation dropdown menus is not marked as having errors when previewing navigation documents.
Resolves: [MWPW-144516](https://jira.corp.adobe.com/browse/MWPW-144516)
Scroll to the bottom of the page. Before, the block was surrounded by the pink error box, after it is not.
**Milo:**
- Before: https://main--federal--adobecom.hlx.page/federal/globalnav/acom/sections/section-menu-cc-localnav
- After: https://main--federal--adobecom.hlx.page/federal/globalnav/acom/sections/section-menu-cc-localnav?milolibs=cross-cloud-menu-error--milo--overmyheadandbody
> [MWPW-144516] Handle cross cloud menu block error

- libs/blocks/modal/modal.js
Added check to ensure we do not create a modal when it is already created and present in DOM.
Resolves: [MWPW-144575](https://jira.corp.adobe.com/browse/MWPW-144575)
**Test URLs:**
This bug is not always reproducible, but it is possible to catch it when the page is opened for the first time in incognito mode. This problem is browser agnostic.
- Before: https://www.stage.adobe.com/#mini-plans-web-cta-creative-cloud-card
- After: here are examples of different modals, basically every modal will be 'touched' with this fix, so feel free to test on all possible modals:
[Page with modals](https://mwpw-144575-duplicated-modals--milo--mirafedas.hlx.live/drafts/mirafedas/all-modals)
> MWPW-144575: fix for the modal duplication

- libs/blocks/global-navigation/global-navigation.js
- libs/blocks/global-navigation/utilities/menu/menu.js
Logic was introduced in https://github.com/adobecom/milo/pull/1714 to provide a more general approach to fetch and process content, including decorating links. The footer [logic](https://github.com/adobecom/milo/pull/1714/files#diff-2053e335fb245c2c097c0075eda050e9dbc23f402dea8b75dad5f4621cd2d12bR70-R73) calls it in a certain way, by defining a `shouldDecorateLinks` property. The global navigation [logic](https://github.com/adobecom/milo/pull/1714/files#diff-628bf5a25903978c5b36da4943ec813da171346d24bd64f80907f012a840b098R717) does not use that property. This means that the `decorateLinks` method is called two times, once with that method, once [here](https://github.com/adobecom/milo/blob/stage/libs/blocks/global-navigation/global-navigation.js#L272). For links that have the `#_dnt` style …
> [MWPW-144602] Ensure DNT functionality in top nav

- libs/features/webapp-prompt/webapp-prompt.js
- libs/scripts/delayed.js
This PR enables analytics for PEP
Resolves: [MWPW-141020](https://jira.corp.adobe.com/browse/MWPW-141020)
1. open the `after test URL` and wait for the PEP modal to show up
2. open dev tools and watch the network tab, searching for calls to `https://sstats.adobe.com/ee/irl1/v1/interact`
3. click on the X button
4. the request payload for searched api call should have `events[0].xdm.web.webInteraction.name` equal to `"Close Modal|PEP Modal_Photoshop"` ( see screenshots )
5. delete the `dismissedAppPrompts` cookie so that the modal will show up again on refresh
6. click the "Stay on this page" button
7. the request payload for searched api call should have `events[0].xdm.web.webInteraction.name` equal to `"Stay on this page|PEP Modal_Photoshop"` ( see screenshots )
**Milo:**
- Before: …
> MWPW-141020: [Project PEP] Implement Analytics Enablement

- libs/blocks/global-navigation/global-navigation.js
- libs/blocks/global-navigation/utilities/utilities.js
- libs/features/personalization/entitlements.js
- libs/features/personalization/stage-entitlements.js
- libs/features/webapp-prompt/webapp-prompt.js
- libs/scripts/delayed.js
This adapts the current PEP logic to use the new method of fetching profile data, rather than relying on IMS and cc-collab. Two new utility methods have been created, `setUserProfile` and `getUserProfile` so that the profile data can be used in other parts of the logic, if needed. `getUserProfile` will return a `Promise` that resolves as soon as data becomes available. I've decided to simply resolve with an empty object if errors are encountered or 5 seconds have passed; this is due to the number of edge cases where uncaught errors could be thrown to the console.
PEP-specific segments [1] have also been added and the logic slightly adapted to decide whether the prompt needs to be shown. Because we don't have a clear way of testing this on Milo pages, I've added some test functionality so …
> [MWPW-141050] Fetch profile for PEP

- libs/blocks/locui/actions/index.js
- libs/blocks/locui/actions/view.js
- libs/blocks/locui/loc/index.js
- libs/blocks/locui/utils/miloc.js
- libs/blocks/locui/utils/state.js
Now that fragments are searched and users can select what fragments they want to add from the sync to langstore workflow we do not need the find fragments button any longer. Removing the button and the state signal associated with find fragments button.
Resolves: [MWPW-141134](https://jira.corp.adobe.com/browse/MWPW-141134)
**Test URL:**
https://locui--milo--adobecom.hlx.page/tools/loc?ref=main&repo=milo&owner=adobecom&host=milo.adobe.com&project=Milo&referrer=https%3A%2F%2Fadobe.sharepoint.com%2F%3Ax%3A%2Fr%2Fsites%2Fadobecom%2F_layouts%2F15%2FDoc.aspx%3Fsourcedoc%3D%257Bcae62b28-0603-4424-937c-476ac75d25b4%257D%26action%3Deditnew
> MWPW-141134 - [Loc v2] Remove find fragments

- libs/blocks/global-footer/global-footer.js
- libs/blocks/global-navigation/global-navigation.js
- libs/blocks/global-navigation/utilities/utilities.js
Ensure centralized images always show up - also on non-centralized navigations. Authors should be able to freely link to centralized assets, such as the adobe logo which is used across a lot of consumers.
Initially fixed in https://github.com/adobecom/milo/pull/1929
Regression in https://github.com/adobecom/milo/pull/2020
Writing a unit test would be complex, hence I'm skipping on this. A nala/e2e test would make sense though.
Resolves: [MWPW-145137](https://jira.corp.adobe.com/browse/MWPW-145137)
Images should always show up, in all of those scenarios.
1. Consumer based navigation + consumer based SVGs used
2. Consumer based navigation + centralized SVG
3. Centralised navigation + centralized SVG
a SVG/image can be a promo element within a menu, a logo in the brand block or in the logo …
> Adobe logo not showing up as expected when retrieved from the federal project

- libs/features/personalization/add-preview-to-config.js
MEP parameter breaks when there are 2 manifests. In the example links, the MEP parameter lists 2 manifests.  In the before link, the MEP button only shows 1 manifest.  In the after link, it correctly shows 2.
Resolves a bug related to [MWPW-143067](https://jira.corp.adobe.com/browse/MWPW-143067)
before: https://main--cc--adobecom.hlx.page/products/premiere?milolibs=stage&target=off&mep=%2Fproducts%2Fpremiere.json--default---%2Fcc-shared%2Ffragments%2Ftests%2F2024%2Fq2%2Face0887%2Face0887.json--target-var-newsmb
after: https://main--cc--adobecom.hlx.page/products/premiere?milolibs=mepsplit&target=off&mep=%2Fproducts%2Fpremiere.json--default---%2Fcc-shared%2Ffragments%2Ftests%2F2024%2Fq2%2Face0887%2Face0887.json--target-var-newsmb
Note, psi check will fail because these are links on CC and …
> MWPW-143067 split mep param to ---

- libs/blocks/bulk-publish-v2/components/bulk-publisher.css
- libs/blocks/bulk-publish-v2/components/bulk-publisher.js
- libs/blocks/bulk-publish-v2/components/job-process.css
- libs/blocks/bulk-publish-v2/components/job-process.js
- libs/blocks/bulk-publish-v2/services.js
- libs/blocks/bulk-publish-v2/utils.js
- Refactored the done count and item status to be updated granularly instead of re-rendering components to improve performance when doing super large bulk processes.
- Now sending create requests in batches of 5 to limit concurrency in projects without authentication enabled (100 per request).
- Now in running jobs, creating a queue of status update requests (to do one at a time) to avoid overloading the browser when doing super large bulk processes.
- Added a clear button to the error display to make it more convenient to when managing request errors in the UI.
Resolves: [MWPW-145157](https://jira.corp.adobe.com/browse/MWPW-145157)
**Test URLs:**
- Before: https://main--milo--adobecom.hlx.page/tools/bulk-publish-v2?martech=off
- After: …
> Bulk Publish Performance Enhancements

- libs/features/personalization/personalization.js
* when a pzn manifest is also sent from Target, and the manifest info is using a production URL: duplicates are not merged.
Resolves: [MWPW-145165](https://jira.corp.adobe.com/browse/MWPW-145165)
Also resolves: [Promo manifests not rendered in stage preview](https://jira.corp.adobe.com/browse/MWPW-145203)
**Test URLs:**
- Before: https://main--cc--adobecom.hlx.page/products/illustrator?mep
- After: https://main--cc--adobecom.hlx.page/products/illustrator?mep&milolibs=mepduplicates
Note that the before link shows 2 manifests and the after link shows only 1.
This feature can only be tested with Target enabled pages, so psi-check will fail.
> better check for duplicates when from Target

- .github/workflows/dispatch.yml
- libs/blocks/bulk-publish-v2/components/bulk-publisher.css
- libs/blocks/bulk-publish-v2/components/bulk-publisher.js
- libs/blocks/bulk-publish-v2/components/job-process.css
- libs/blocks/bulk-publish-v2/components/job-process.js
- libs/blocks/bulk-publish-v2/services.js
- libs/blocks/bulk-publish-v2/utils.js
- libs/features/personalization/personalization.js
- https://github.com/adobecom/milo/pull/2056
- https://github.com/adobecom/milo/pull/2050
- https://github.com/adobecom/milo/pull/2034
> [Release][Zero Impact] Stage to Main

- libs/blocks/locui/langs/view.js
* Multiplying by the languages size is no longer needed, the lang's `total` property should be sufficient by itself.
Resolves: [MWPW-144236](https://jira.corp.adobe.com/browse/MWPW-144236)
**Test URLs:**
- Before: https://locui--milo--adobecom.hlx.page/tools/loc?ref=main&repo=milo&owner=adobecom&host=milo.adobe.com&project=Milo&referrer=https%3A%2F%2Fadobe.sharepoint.com%2F%3Ax%3A%2Fr%2Fsites%2Fadobecom%2F_layouts%2F15%2FDoc.aspx%3Fsourcedoc%3D%257B08E1FC5E-2434-497D-9789-992E4190304A%257D%26file%3Delan-test.xlsx%26action%3Ddefault%26mobileredirect%3Dtrue
- After: https://ebartholomew-locui-total--milo--adobecom.hlx.page/tools/loc?ref=main&repo=milo&owner=adobecom&host=milo.adobe.com&project=Milo&referrer=https%3A%2F%2Fadobe.sharepoint.com%2F%3Ax%3A%2Fr%2Fsites%2Fadobecom%2F_layouts%2F15%2 …
> MWPW-144236 - Correct rollout total

- libs/blocks/locui/langs/view.js
* The 'complete label' above the done vs total count section of each language would always show "Rolled Out", even if the language was being translated, not rolled out. This PR should fix this, and generally simplify the way we display the language's status.
Resolves: [MWPW-145783](https://jira.corp.adobe.com/browse/MWPW-145783)
**Test URLs:**
- Before: https://locui--milo--adobecom.hlx.page/tools/loc?ref=main&repo=milo&owner=adobecom&host=milo.adobe.com&project=Milo&referrer=https%3A%2F%2Fadobe.sharepoint.com%2F%3Ax%3A%2Fr%2Fsites%2Fadobecom%2F_layouts%2F15%2FDoc.aspx%3Fsourcedoc%3D%257B08E1FC5E-2434-497D-9789-992E4190304A%257D%26file%3Delan-test.xlsx%26action%3Ddefault%26mobileredirect%3Dtrue
- After: https://ebartholomew-locui-complete-label--milo--adobecom.hlx.page/tools/loc?ref=main&r …
> MWPW-145783 - Show correct complete label for action type

- libs/features/personalization/preview.js
- libs/features/personalization/promo-utils.js
- libs/utils/utils.js
- test/features/personalization/preview.test.js
- test/features/personalization/promo-utils.test.js
Implement the 'instant' parameter for Milo Promotions.
'Instant' param overrides current browser time with provided value and impacts Promo manifests.
'instant' parameter in the format of ISO 8601 with UTC (GMT) timezone allows GWP to see the page 'in the future' and validate upcoming promotions. It compliments `?mep` parameter (allows to preview manifests on the page) with an ability to validate the configured promo schedule.
[Sample Page](https://instant--milo--3ch023.hlx.live/drafts/mariia/pr/promo/promo?instant=2024-06-14T05:00:00.000Z)
1. Open the page with configured promo
2. In MEP Preview click on 'instant'
3. The link with an instant parameter will open in the new tab, you can share the link with anyone for a review
Resolves: …
> MWPW-143145: add instant preview paramter

- libs/utils/utils.js
Currently express is migrating its faq block so that it works with milo code like any other milo college project.There used to be a block in milo named faq, but it was refactored to be called accordion with addtional functionality - https://github.com/adobecom/milo/pull/43. 
Our faq block in express is not working though because milo believes it still has a faq block.
The faq entry in the block array in utils.js in milo needs to have this entry removed, so that our faq block in express works correctly. For milo this is simply code cleanup - less bytes to all our clients  ;)
Resolves: [MWPW-145566](https://jira.corp.adobe.com/browse/MWPW-145566)
**Test URLs:**
- After: https://vhargrave-mwpw-145566-faq-utils-cleanup--milo--adobec …
> MWPW-145566 remove faq from MILO_BLOCKS array

- libs/features/personalization/entitlements.js
- libs/features/personalization/stage-entitlements.js
Adding a few pzn tags to the prod and stage objects.
Resolves: [MWPW-144125](https://jira.corp.adobe.com/browse/MWPW-144125) and [MWPW-144536](https://jira.corp.adobe.com/browse/MWPW-144536)
**Test URLs:**
N/A but for PR check:
- Before: https://main--milo--adobecom.hlx.page?martech=off
- After: https://addmeppzntags--milo--adobecom.hlx.page?martech=off
Note: Psi check will fail since there are no test URL's.
This PR is considered a blocker, but the other team that needs this data is also in a code freeze.  So as long as we can deploy to prod by 4/1 we're fine.
> MWPW-144125 and MWPW-144536 [MILO][MEP] Request for New Personalization Tags

- libs/blocks/locui/langs/view.js
* As an author, I would like the option to individually retry the rollout/translation process on specific languages after they show an error status, as displayed below. In the test URLs I've provided, take a look at German; the Before link will just show the language card, the After link should have a "Retry" button.
Resolves: [MWPW-145643](https://jira.corp.adobe.com/browse/MWPW-145643)
**Test URLs:**
- Before: https://main--cc--adobecom.hlx.page/tools/loc?milolibs=locui&ref=main&repo=cc&owner=adobecom&host=www.adobe.com&project=Creative+Cloud&referrer=https%3A%2F%2Fadobe.sharepoint.com%2F%3Ax%3A%2Fr%2Fsites%2Fadobecom%2F_layouts%2F15%2FDoc.aspx%3Fsourcedoc%3D%257B03be638a-488f-484d-b91f-0593318bc33e%257D%26action%3Deditnew
- After: …
> MWPW-145643 - Add retry button to lang module on error

- libs/utils/utils.js
By defining a metadata property, `adobe-home-redirect`, and setting it to `on`, a user will be redirected to the homepage after logging in. Redirect rules will then reroute them to the appropriate localized Adobe Home page.
Resolves: [MWPW-145189](https://jira.corp.adobe.com/browse/MWPW-145189)
---
This has been deemed critical by leadership and thus was marked as such. The AEM and Milo sides of this implementation need to come together with the redirect rules and Adobe Home implementation on ROW for true E2E testing. The committed date for stage is **April 2nd**. Details surrounding the plan are also available in the comments section of the story.
---
**Testing instructions:**
- visit the URL, log out if needed
- check that `window.adobeid` has a `redirect_uri` defined leading to the …
> [MWPW-145189] Adobe Home post-login redirect

- libs/blocks/locui/langs/view.js
* A special endpoint is required for this button to have the desired effect. Reverting it for now while we wait for that endpoint, to avoid confusion amongst authors.
Resolves: [MWPW-145643](https://jira.corp.adobe.com/browse/MWPW-145643)
**Test URLs:**
- Before: https://locui--milo--adobecom.hlx.page/tools/loc?ref=main&repo=milo&owner=adobecom&host=milo.adobe.com&project=Milo&referrer=https%3A%2F%2Fadobe.sharepoint.com%2F%3Ax%3A%2Fr%2Fsites%2Fadobecom%2F_layouts%2F15%2FDoc.aspx%3Fsourcedoc%3D%257B469f3162-9516-40ef-a7e6-a6295b3faba8%257D%26action%3Deditnew
- After: https://ebartholomew-locui-revert-retry--milo--adobecom.hlx.page/tools/loc?ref=main&repo=milo&owner=adobecom&host=milo.adobe.com&project=Milo&referrer=https%3A%2F%2Fadobe.sharepoint.com%2F%3Ax%3A%2Fr%2Fsites%2Fadobecom%2F_layou …
> MWPW-145643 - Revert retry button for now

- libs/blocks/marquee/marquee.css
- libs/blocks/marquee/marquee.js
- libs/blocks/merch-card/merch-card.js
- libs/blocks/modal/modal.js
- libs/deps/merch-quantity-select.js
- libs/features/personalization/entitlements.js
- libs/features/personalization/preview.js
- libs/features/personalization/promo-utils.js
- libs/features/personalization/stage-entitlements.js
- libs/utils/decorate.js
- libs/utils/utils.js
- test/blocks/modals/modals.test.js
- test/features/personalization/preview.test.js
- test/features/personalization/promo-utils.test.js
- https://github.com/adobecom/milo/pull/1935
- https://github.com/adobecom/milo/pull/1936
- https://github.com/adobecom/milo/pull/1979
- https://github.com/adobecom/milo/pull/1986
- https://github.com/adobecom/milo/pull/2068
- https://github.com/adobecom/milo/pull/1998
- https://github.com/adobecom/milo/pull/2065
- https://github.com/adobecom/milo/pull/2090
> [Release] Stage to Main

- libs/features/personalization/personalization.js
- libs/martech/martech.js
Increase the default timeout to 3.5s.  Also add ability to modify the timeout 
Resolves: [MWPW-145728](https://jira.corp.adobe.com/browse/MWPW-145728)
**Test URLs:**
- After: https://ccc-target-timeout--milo--adobecom.hlx.page/?martech=off
As promised, here is the Jira ticket to create unit tests for martech.js https://jira.corp.adobe.com/browse/MWPW-145975
> MWPW-145728 Increase timeout; add metadata support

- libs/blocks/bulk-publish-v2/bulk-publish-v2.js
- libs/blocks/bulk-publish-v2/services.js
- test/blocks/bulk-publish-v2/mocks/fetch.js
Surprise! The delete and un-publish processes respective api methods were recently deprecated. This PR updates the services to use the new body schema for both processes.
For the delete and un-publish processes:
- uses `POST` instead of `DELETE` request method
- now passing property `delete: true` in the body
- now uses `body.paths` instead of `paths[]` url parameter for urls
- updated testing fetch mocks to use correct mock data if delete property is included in request body
Resolves: [MWPW-145921](https://jira.corp.adobe.com/browse/MWPW-145921)
Will need to test in BACOM because the remove processes are not available in milo due to missing authentication.
Please use the milolibs param with this branch and a draft of your choosing: …
> MWPW-145921 - [Bulk Publish v2] update for deprecated api methods

- libs/blocks/modal/modal.css
This change adds a new `xl-size` class for the modal window, which allows the modal window to fill all available screen height on mobile and tablet, and to be wider on desktop.
We set this class to the modal window that renders an iframe with the following pages:
https://www.adobe.com/creativecloud/whats-included/mini-plans/cci-all-apps-whats-included.html
https://www.adobe.com/creativecloud/whats-included/mini-plans/edu-all-apps-whats-included.html
https://www.adobe.com/creativecloud/whats-included/mini-plans/cct-all-apps-whats-included.html
https://www.adobe.com/creativecloud/whats-included/plans/cci-all-apps-whats-included.html 
https://www.adobe.com/creativecloud/whats-included/plans/edu-all-apps-whats-included.html
https://www.adobe.com/creativecloud/whats-included/plans/cct-all-apps- …
> MWPW-144813: Add 'xl-size' class for dialog-modal

- libs/blocks/merch-card/merch-card.js
- libs/deps/merch-card.js
- test/blocks/merch-card/merch-card.test.js
- test/blocks/merch-card/mocks/twp.html
- TwP merch card 
Resolves: [MWPW-136871](https://jira.corp.adobe.com/browse/MWPW-136871)
**Test URLs:**
- Before: https://main--cc--adobecom.hlx.page/drafts/axel/stories/mwpw-136871?martech=off
- After: https://main--cc--adobecom.hlx.page/drafts/axel/stories/mwpw-136871?milolibs=MWPW-136871--milo--axelcureno&martech=off
> Mwpw-136871: TwP merch card

- libs/blocks/global-navigation/global-navigation.css
- libs/blocks/global-navigation/global-navigation.js
- libs/blocks/global-navigation/utilities/menu/menu.js
- libs/blocks/global-navigation/utilities/utilities.js
- libs/features/webapp-prompt/webapp-prompt.css
- libs/features/webapp-prompt/webapp-prompt.js
This makes the necessary changes to:
* position the PEP prompt relative to the App Switcher;
* focus the App Switcher if the PEP prompt is dismissed;
* cancel displaying the PEP prompt if the App Switcher is open.
This is safe to be merged in the feature branch, but we'll need to have a few things on our radar:
* we need to get confirmation from the UNav team on the 1.1 version release that contains the updates to interact with the App Switcher, currently this is available just on production; we do have safety mechanisms is place in case their methods aren't available;
* currently the Profile menu `adobeProfile.getUserProfile()` public method is throwing errors, thus we can't retrieve profile data, I've reported the issue on the appropriate Slack channel.
This PR also addresses a bunch of …
> [MWPW-142625] PEP relative to App Switcher

- libs/blocks/global-navigation/utilities/utilities.js
@overmyheadandbody has done the initial research and
> We're not localizing fragment links. The main navigation is fetched via the localized path, the same for the dropdown menus; but any fragments nested inside the dropdown menus are no longer localized. 
Resolves: [MWPW-145673](https://jira.corp.adobe.com/browse/MWPW-145673)
Federal fragments should be localizeable
**Initial bug report in the german variant**
- Before: https://main--federal--adobecom.hlx.page/de/federal/globalnav/drafts/ankshukl/document-preview-acom-gnav-plus-footer
- After: https://main--federal--adobecom.hlx.page/de/federal/globalnav/drafts/ankshukl/document-preview-acom-gnav-plus-footer?milolibs=mwpw-145673-federal-fragments--milo--mokimo
**English variant:**
- Before: …
> Localize federal inline fragments before fetching them

- libs/blocks/merch-card/merch-card.js
- test/blocks/merch-card/merch-card.test.js
introducing heading map once talked with Axel, that we can slowly grow to manage all card types. 
Resolves: [MWPW-144254](https://jira.corp.adobe.com/browse/MWPW-144254)
**Test URLs:**
- Before: https://main--milo--adobecom.hlx.live/docs/library/kitchen-sink/merch-card?martech=off
- After: https://mwpw-144254--milo--npeltier.hlx.live/docs/library/kitchen-sink/merch-card?martech=off
> MWPW-144254 [merch-card] per type heading map

- libs/blocks/modal/modal.css
- libs/blocks/section-metadata/section-metadata.css
To create a Terms and Conditions modal like this one: 
https://www.adobe.com/promo/streamyard.html#terms 
two things were missing in Milo: the possibility to add horizontal padding for sections, and the possibility to restrict the modal width on the desktop screen to 650px.
As a rule, modals adjust to the fragment content size, but in case of this modal we need to restrict its width, so we introduce the class 's-size' for the max-width of 650px (only on desktop, on mobile and tablet it will take the whole available screen width).
As for section, classes `xxxl/xl/l/etc-spacing` add vertical padding, but set horizontal padding to 0.
We add classes `xxxl/xl/l/etc-padding` for the section to make it possible to have even horizontal and vertical paddings.
Resolves: …
> MWPW-145302: Added 's-size' class for modal, and horizontal paddings for section

- libs/blocks/locui/langs/view.js
* The API provides a `statusText` field that should be used instead here.
Resolves: [MWPW-145783](https://jira.corp.adobe.com/browse/MWPW-145783)
**Test URLs:**
- Before: https://locui--milo--adobecom.hlx.page/tools/loc?ref=main&repo=milo&owner=adobecom&host=milo.adobe.com&project=Milo&referrer=https%3A%2F%2Fadobe.sharepoint.com%2F%3Ax%3A%2Fr%2Fsites%2Fadobecom%2F_layouts%2F15%2FDoc.aspx%3Fsourcedoc%3D%257B52E189B7-129A-4E48-A985-BCDB99F22DB8%257D%26file%3D150urls.xlsx%26action%3Ddefault%26mobileredirect%3Dtrue
- After: https://ebartholomew-locui-complete-label2--milo--adobecom.hlx.page/tools/loc?ref=main&repo=milo&owner=adobecom&host=milo.adobe.com&project=Milo&referrer=https%3A%2F%2Fadobe.sharepoint.com%2F%3Ax%3A%2Fr%2Fsites%2Fadobecom%2F_layouts%2F15%2FDoc.aspx%3Fsourcedoc%3D%257B52E189 …
> MWPW-145783 - Update completed label

- libs/utils/utils.js
This fixes an omission when checking for the `env` value when defining the `redirect_uri` relevant for the Adobe Home redirect.
Resolves: [MWPW-146274](https://jira.corp.adobe.com/browse/MWPW-146274)
**Test URLs:**
- Before: https://main--cc--adobecom.hlx.page/kr/creativecloud/file-types/image/comparison?martech=off
- After: https://main--cc--adobecom.hlx.page/kr/creativecloud/file-types/image/comparison?milolibs=fix-ah-redirect--milo--overmyheadandbody&martech=off
> [MWPW-146274] Fix AH redirect

- .github/workflows/mark-stale-prs.yaml
Warn and then close issues and PRs that have had no activity for a specified amount of time using the [stale](https://github.com/actions/stale) workflow.
- PRs that have not seen any activity for 7 days are marked as stale
- stale PRs are closed after 7 days
- PRs that are "Ready for Stage" are exempt.
Example: https://github.com/adobecom/milo/pulls?q=is%3Aopen+is%3Apr+label%3AStale
Example message on the PR: https://github.com/adobecom/milo/pull/1881#issuecomment-2020125661
Resolves: [MWPW-143674](https://jira.corp.adobe.com/browse/MWPW-143674)
**Test URLs:**
- After: https://mark-stale-prs--milo--adobecom.hlx.page/?martech=off
> Automatically mark stale PRs & close them after 7 days

- libs/utils/utils.js
Load IMS from the old domain via query parameter `useAlternateImsDomain` to run some LH tests with both the old and new self hosted domain to measure the LH score impact.
Resolves: [MWPW-145710](https://jira.corp.adobe.com/browse/MWPW-145710)
Scenario-1: Load a page, signing in should still work.
Secnario-2: Load a page with `&useAlternateImsDomain=true` and IMS should be loaded from the old domain
Without query param
With query param
**Milo using the old ims url**
- Before: https://main--milo--adobecom.hlx.live/drafts/osahin/gnav-1?martech=off&useAlternateImsDomain=true
- After: https://mwpw-145710-ims-self-hosting--milo--mokimo.hlx.live/drafts/osahin/gnav-1?martech=off&useAlternateImsDomain=true
**Milo using the new self hosted ims url**
- Before: …
> mwpw-145710: load ims via param from old domain

- libs/blocks/mobile-app-banner/mobile-app-banner.js
- test/blocks/mobile-app-banner/mobile-app-banner.test.js
- test/blocks/mobile-app-banner/mocks/body.html
- test/blocks/mobile-app-banner/mocks/branch-io-key.json
* Small authoring update for mobile-app-banner
* Unit tests for mobile-app-banner
Resolves: [MWPW-143904](https://jira.corp.adobe.com/browse/MWPW-143904)
**Test URLs:**
- Before: https://main--milo--adobecom.hlx.page/drafts/ruchika/branch-io/branch-io-page11?martech=off
- After: https://branch-latest--milo--adobecom.hlx.page/drafts/ruchika/branch-io/branch-io-page11?martech=off
CC
- Before: https://main--cc--adobecom.hlx.page/drafts/ruchika/mobile-app-banner1?martech=off
- After: https://main--cc--adobecom.hlx.page/drafts/ruchika/mobile-app-banner1?milolibs=branch-latest&martech=off
Authoring documentation: 
https://main--milo--adobecom.hlx.page/docs/authoring/blocks/mobile-app-banner
> MWPW-143904-Unit test and small authoring update for mobile-app-banner

- libs/blocks/global-navigation/base.css
- Adds a gray background option for link header
- Makes gradient link group header bold 
Resolves: [MWPW-146166](https://jira.corp.adobe.com/browse/MWPW-146166)
**Test URLs:**
- Before: https://main--milo--adobecom.hlx.live/drafts/blaishram/index-loggedout-ace0687v4?martech=off
- After: https://mwpw-146166--milo--bandana147.hlx.live/drafts/blaishram/index-loggedout-ace0687v4?martech=off
> Fix: Adding gray bg and making header bold for group link on gnav

- libs/utils/utils.js
Add an easy hook that's available cross consumers for the ops team to verify all the milo JS has executed and pages are visible.
Resolves: [MWPW-145591](https://jira.corp.adobe.com/browse/MWPW-145591)
An invisible div `<div id="page-load-ok-milo" style="display: none"></div>` should be available on the page after pageload.
Base regression links:
**CC:**
- Before: https://main--cc--adobecom.hlx.live/?martech=off
- After: https://main--cc--adobecom.hlx.live/?martech=off&milolibs=milo-finished-loading--milo--mokimo
**Homepage:**
- Before: https://main--homepage--adobecom.hlx.page/homepage/index-loggedout?martech=off
- After: https://main--homepage--adobecom.hlx.page/homepage/index-loggedout?martech=off&milolibs=milo-finished-loading--milo--mokimo
**Blog:**
- Before: …
> MWPW-145591: Enable dom monitoring hook to verify javascript execution

- libs/blocks/tabs/tabs.css
Pill tab-list styles should support light and dark themes. Currently it doesn't work with dark theme.
- Removes background : unset on `tab.pill` variant
Resolves: [MWPW-146268](https://jira.corp.adobe.com/browse/MWPW-146268)
**Test URLs:**
- Before: https://main--milo--adobecom.hlx.page/drafts/sarchibeque/pill-tabs?martech=off
- After: https://sarchibeque-mwpw-146268-pill-tab-dark--milo--adobecom.hlx.page/drafts/sarchibeque/pill-tabs?martech=off
> MWPW-146268 - [Milo - Tabs] Pill dark/light support

- libs/blocks/quiz-entry/mlField.js
- libs/blocks/quiz-entry/quiz-entry.js
- libs/blocks/quiz-entry/quizoption.js
* resolved accessibility concerns when the ml input is used - cards are now properly disabled with the attribute
* general code refinements for more clarity, specifically for getting string values
Resolves: [MWPW-146034](https://jira.corp.adobe.com/browse/MWPW-146034)
**Test URLs:**
- Before: https://quiz-entry-block--milo--adobecom.hlx.page/drafts/colloyd/quiz-entry/?martech=off
- After: https://quiz-entry-accessibility--milo--colloyd.hlx.page/drafts/colloyd/quiz-entry/?martech=off
> MWPW-146034 - Quiz entry block accessibility

- libs/blocks/locui/actions/index.js
- libs/blocks/locui/langs/index.js
- libs/blocks/locui/langs/view.js
- libs/blocks/locui/utils/miloc.js
* With the introduction of the `/retry` endpoint, users of this UI should be able to retry a language that has an error. This PR extends the pre-existing `rolloutLang` function to handle requests to this new endpoint as well.
Resolves: [MWPW-145643](https://jira.corp.adobe.com/browse/MWPW-145643)
**Test URLs:**
- Before: https://locui--milo--adobecom.hlx.page/tools/loc?ref=main&repo=milo&owner=adobecom&host=milo.adobe.com&project=Milo&referrer=https%3A%2F%2Fadobe.sharepoint.com%2F%3Ax%3A%2Fr%2Fsites%2Fadobecom%2F_layouts%2F15%2FDoc.aspx%3Fsourcedoc%3D%257B52E189B7-129A-4E48-A985-BCDB99F22DB8%257D%26file%3D150urls.xlsx%26action%3Ddefault%26mobileredirect%3Dtrue
- After: https://ebartholomew-locui-retry-lang2--milo--adobecom.hlx.page/tools/loc?ref=main&repo=milo&owner=adobecom&host=milo.adob …
> MWPW-145643 - Add retry button to langs with errors

- libs/features/georoutingv2/georoutingv2.css
Fixes an issue with the picker being cut off on iOS devices. To test you'll ideally use browserstack and open the URL I've provided on an iPhone 14 (or similar device) 
You can also test by opening safari -> Develop -> Enter Responsive Design Mode -> and testing on a screen with 400px x 600px
Resolves: [MWPW-146352](https://jira.corp.adobe.com/browse/MWPW-146352)
**Test URLs:**
**Milo**
- Before: https://main--milo--adobecom.hlx.page/drafts/vhargrave/georouting?martech=off&akamaiLocale=in
- After: https://vhargrave-MWPW-146352-fix-georouting-dropdown--milo--adobecom.hlx.page/drafts/vhargrave/georouting?martech=off&akamaiLocale=in
**Homepage**
- Before: https://main--homepage--adobecom.hlx.page/homepage/index-loggedout?martech=off&akamaiLocale=in
- After: …
> MWPW-146352 fix georouting dropdown on ios

- libs/blocks/locui/actions/index.js
Expanding on filtering of duplicate fragments within find deep fragments function for specific scenarios where a nested fragment is also being nested within other nested fragments on an individual page. Initially the search function was filtering already searched fragments but allowing nested fragments to be added when they were duplicates which is causing a mismatch. This PR adds an additional check for a fragments in found fragments before adding to the list.
Resolves: [MWPW-146459](https://jira.corp.adobe.com/browse/MWPW-146459)
Test URLs:
Will need to pull down branch and serve locally, then try to sync to langstore in [localization project](https://adobe.sharepoint.com/:x:/r/sites/adobecom/_layouts/15/Doc.aspx?sourcedoc=%7B85A38345-56CE-4C93-8213-30A9CF3FD7D9%7D&file=Book.xlsx&action= …
> MWPW-146459 - [LocUI v2] Additional filtering in deep fragment search

- libs/deps/imslib.min.js
- libs/features/webapp-prompt/webapp-prompt.js
This PR fixes the close button a11y issue found on project PEP E2E testing.
Resolves: [MWPW-146582](https://jira.corp.adobe.com/browse/MWPW-146582)
1. go to the test url
2. log in with any account
3. activate voice over
4. when the PEP prompt shows up, select the `X` close button
5. listen to the voice over description
**Milo:**
- Before: https://project-pep--milo--adobecom.hlx.page/drafts/rbogos/pep-prompt?imsClientId=fedsmilo&extraPepEnts=firefly-web-usage#
- After: https://mwpw-146582-pep-fixes--milo--robert-bogos.hlx.page/drafts/rbogos/pep-prompt?imsClientId=fedsmilo&extraPepEnts=firefly-web-usage#
> MWPW-146582: PEP fixes

- libs/blocks/locui/langs/index.js
- libs/blocks/locui/langs/view.js
* Because the click handler to show the error modal is applied to the entire lang container, propagation control was needed for the Retry button to be effective.
* There was a logic error in how the Retry button constructed its request.
Resolves: [MWPW-145643](https://jira.corp.adobe.com/browse/MWPW-145643)
**Test URLs:**
- Before: https://main--milo--adobecom.hlx.page/tools/loc?ref=main&repo=milo&owner=adobecom&host=milo.adobe.com&project=Milo&referrer=https%3A%2F%2Fadobe.sharepoint.com%2F%3Ax%3A%2Fr%2Fsites%2Fadobecom%2F_layouts%2F15%2FDoc.aspx%3Fsourcedoc%3D%257B52E189B7-129A-4E48-A985-BCDB99F22DB8%257D%26file%3D150urls.xlsx%26action%3Ddefault%26mobileredirect%3Dtrue
- After: https://ebartholomew-locui-retry-fix--milo--adobecom.hlx.page/tools/loc?ref=main&repo=milo&owner=adobecom&host=m …
> MWPW-145643 - Stop propagation of lang button, fix retry reqest

- libs/martech/martech.js
I created a PR recently https://github.com/adobecom/milo/pull/2140 that increased the timeout and improved error handling. We're seeing some unexpected results and want to dig in a little further. So we're updating the analytics again.
Fast follow for: [MWPW-146491](https://jira.corp.adobe.com/browse/MWPW-146491)
Test URLs:
After: https://meptimeoutagain--milo--adobecom.hlx.page/?martech=off
Page with Target on:
https://main--homepage--adobecom.hlx.page/homepage/index-loggedout
https://main--homepage--adobecom.hlx.page/homepage/index-loggedout?milolibs=meptimeoutagain
Note: this is listed as high priority because in Dexter, if a Target response came in quite late, the page would "flicker" but they would still get the updates. In …
> MWPW-146491 Fast follow to change timeout analytic and use Date instead of performance

- libs/utils/decorate.js
- test/blocks/media/media.test.js
As an author in Milo, I want the ability to add a 'fill' button to a Milo page. This should be available in the same capacity as the rest of the buttons as shown here: https://milo.adobe.com/docs/authoring/button-mapping  
Resolves: [MWPW-139842](https://jira.corp.adobe.com/browse/MWPW-139842)
**Test URLs:**
- Before: https://main--milo--adobecom.hlx.page/drafts/rparrish/buttons?martech=off
- After: https://rparrish-button-fill--milo--adobecom.hlx.page/drafts/rparrish/buttons?martech=off
Additional live pages can be tested w/ the url param `?miloLibs=rparrrish-button-fill`
(No`fill` buttons should be present on any live content w/ the exception of bricks)
https://main--cc--adobecom.hlx.page/products/illustrator/free-trial-download?miloLibs=rparrrish-button-fill …
> MWPW-139842 - Block button styling - Support button.fill w/ <strong><em> authoring

- libs/blocks/locui/locui.css
- libs/blocks/locui/sync/view.js
When the user has the sidekick open in a localization v2 project and doesn't have "Push Down" enabled, the status toast and connected label is hidden behind the sidekick top bar. This PR updates the status toast and connected label to always be positioned so you can see them, whether the sidekick is open or not. I also gave them fixed position so they are showing even when the user has the page scrolled down a ways.
Resolves: [MWPW-146877](https://jira.corp.adobe.com/browse/MWPW-146877)
> MWPW-146877 [LocUI] - Status Details & Sidekick

- libs/utils/decorate.js
There was some surprise authoring in the wild that this unintentionally impacted. 
A number of documents have unknown 'fill' styles authored because the bold+italic combo also initially resulted in .outline styles. see. https://adobe-mwp.slack.com/archives/C03S7CZU8NN/p1713822664500139
Rikio Kaneko
hi, we’re seeing buttons that used to be black outline/hollow, are now black filled buttons on BACOM.  Sample pages:
https://business.adobe.com/products/magento/magento-commerce.html - marquee
https://business.adobe.com/products/genstudio.html - buttons in the tabs
https://business.adobe.com/products/experience-manager/sites/aem-sites.html - tabs section and “better
The teams want to have a better testing plan to roll this feature out
**Reverts**
MWPW-139842 - Block button styling - Support …
> MWPW-139842 [Revert] Fill button style

- libs/blocks/quiz-entry/mlField.js
- libs/blocks/quiz-entry/quiz-entry.css
- libs/blocks/quiz-entry/quiz-entry.js
- libs/blocks/quiz-entry/utils.js
* Support for ml filtering
* Debug support using ?debug=quiz-entry
* Support for defining a maximum number of questions in the block before it will redirect
* Support for pressing the enter key in the ml field
Resolves: [MWPW-146036](https://jira.corp.adobe.com/browse/MWPW-146036)
**Test URLs:**
- Before: https://quiz-entry-block--milo--adobecom.hlx.page/drafts/colloyd/quiz-entry/?martech=off
- After: https://quiz-entry-continue-button--milo--colloyd.hlx.page/drafts/colloyd/quiz-entry/?martech=off
Testing notes: 
You can now specify the number of questions that it will go through before redirecting to the main quiz, though this may not be used immediately, it does provide some future proofing if they want to try adding a few more questions before redirecting
You can prevent the redirect …
> MWPW-146036 - Rig up quiz entry button

- libs/blocks/preflight/panels/general.js
- libs/blocks/preflight/panels/seo.js
- libs/blocks/preflight/preflight.css
* Filter out empty `hrefs` before sending to spidy.
* Harden link check to be more robust against Spidy API.
* Update link check language.
* Better onboarding support.
* Adds fallbacks if `.milo/config` has not been added. 
* Fix for missing Word doc reference, under general tab.
Resolves: [MWPW-146695](https://jira.corp.adobe.com/browse/MWPW-146695)
**Test URLs:**
- Before: https://main--milo--adobecom.hlx.page/drafts/rclayton/test-template?martech=off
- After: https://preflight-link-check-harden--milo--adobecom.hlx.page/drafts/rclayton/test-template?martech=off
**Bacom Test URLs**
- Before: https://main--bacom--adobecom.hlx.page/lv/products/customer-journey-analytics/adobe-customer-journey-analytics?martech=off
- After:  https://main--bacom--adobecom.hlx.page/lv/products/customer-journey …
> Harden preflight link checking

- libs/features/webapp-prompt/webapp-prompt.js
- test/features/webapp-prompt/test-utilities.js
- test/features/webapp-prompt/webapp-prompt.test.js
This PR is addressing all the leftover TODOs from project PEP and adds more unit tests.
Resolves: [MWPW-147145](https://jira.corp.adobe.com/browse/MWPW-147145)
**Milo:**
- Before: https://project-pep--milo--adobecom.hlx.page/drafts/rbogos/pep-prompt?imsClientId=fedsmilo
- After: https://mwpw-147145-pep-final-touches--milo--robert-bogos.hlx.page/drafts/rbogos/pep-prompt?imsClientId=fedsmilo
> MWPW-147145: PEP final touches

- libs/scripts/scripts.js
Reverting a change required for testing purposes during PEP development.
Resolves: [MWPW-147145](https://jira.corp.adobe.com/browse/MWPW-147145)
**Test URLs:**
- Before: https://main--cc--adobecom.hlx.page/drafts/ramuntea/firefly?milolibs=project-pep
- After: https://main--cc--adobecom.hlx.page/drafts/ramuntea/firefly?milolibs=project-pep--milo--overmyheadandbody
> [MWPW-147145] Remove custom IMS client ID logic

- .github/workflows/dispatch.yml
* Without setting `base`, the paths-filter GHA uses the default branch `stage` as the base to check for differences. When there is a release push to `main`, no difference is found and DC workflow is not triggered. 
Resolves: [MWPW-146562](https://jira.corp.adobe.com/browse/MWPW-146562)
**Test URLs:**
N/A
> MWPW-146562 [Workflow] Add base for paths filter when dispatch DC workflow

- libs/blocks/marquee/marquee.css
- libs/blocks/marquee/marquee.js
This addresses an RTL issue for the split marquee.
I initially saw this as a "patch" and tried to consolidate `flex-direction` for all marquees starting at `600px`. Due to the large number of use-cases, I did a bunch of screenshot diffs and it seems that that approach would have affected multiple types of marquees between 600-1200px. Thus I decided to play it safe for now and address the initially reported issues, since the bug is marked as critical.
**Resolves**: [MWPW-147003](https://jira.corp.adobe.com/browse/MWPW-147003)
- **Before**: https://main--cc--adobecom.hlx.page/mena_ar/products/illustrator
- **After**: https://main--cc--adobecom.hlx.page/mena_ar/products/illustrator?milolibs=marquee-on-rtl--milo--overmyheadandbody
- **Before**: …
> [MWPW-147003] Marquee RTL adaptation

- libs/blocks/locui/url/index.js
Both preview and live buttons currently open a preview url, this PR will update them to look at the proper is preview flag and fetch the correct url to set on each link.
Resolves: [MWPW-147265](https://jira.corp.adobe.com/browse/MWPW-147265)
> MWPW-147265 - [LocUI] Preview and Live Links

- libs/features/webapp-prompt/webapp-prompt.css
- libs/features/webapp-prompt/webapp-prompt.js
This allows the use of SVG icons inside the PEP Prompt document and updates the method used for redirection.
Resolves: [MWPW-147145](https://jira.corp.adobe.com/browse/MWPW-147145)
**Test URLs:**
- Before: https://main--cc--adobecom.hlx.page/products/firefly?milolibs=project-pep
- After: https://main--cc--adobecom.hlx.page/products/firefly?milolibs=project-pep--milo--overmyheadandbody
> [MWPW-147145] Allow SVG in PEP Prompt; change redirect method

- libs/features/jarvis-chat.js
- libs/scripts/delayed.js
- test/features/jarvis-chat/jarvis-chat.test.js
Adds the ability to control the Jarvis `surface id`, `version` and `onDemand` config at the page and directory level.
Resolves: [MWPW-144521](https://jira.corp.adobe.com/browse/MWPW-144521)
**Test URLs:**
- Before: https://main--milo--adobecom.hlx.live/drafts/nishantkaush/test/jarvis?martech=off
- After: https://mwpw-144521--milo--nishantka.hlx.live/drafts/nishantkaush/test/jarvis?martech=off
> MWPW-144521: Jarvis enhancement

- libs/blocks/locui/actions/index.js
- libs/blocks/locui/langs/index.js
- libs/blocks/locui/langs/view.js
- libs/blocks/locui/utils/miloc.js
When polling for status updates and a user triggers an action, the status polling interval can return and re-render according to the status conditions before new updates from the action event are completed. This causes the UI to temporarily show the wrong action buttons until the request is finished and the status API returns a new status.
In this PR I am leveraging a polling state which is toggled on/off when an event is fired so we can avoid rendering updates from the status polling service until the actions event request is completed. I have also dialed in the polling functionality to avoid setting multiple polling intervals.
Resolves: [MWPW-146878](https://jira.corp.adobe.com/browse/MWPW-146878)
> MWPW-146878 [LocUI] - Actions polling state management

- libs/blocks/quiz-entry/mlField.js
- libs/blocks/quiz-entry/quiz-entry.js
- libs/blocks/quiz-entry/utils.js
* add support for fallback fi codes
* add lana logging for ml field failures
* fix so the redirect checks for maxQuestions
Resolves: [MWPW-147482](https://jira.corp.adobe.com/browse/MWPW-147482)
**Test URLs:**
- Before:  https://quiz-entry-block--milo--adobecom.hlx.page/drafts/colloyd/quiz-entry/?martech=off
- After: https://quiz-entry-ml-bulletproofing--milo--colloyd.hlx.page/drafts/colloyd/quiz-entry/?martech=off
Testing notes: 
To test the fallback fi codes, I've created a page that is deliberately broken with invalid ml details (specifically the endpoint is wrong). Notice in the console on this page, when interacting with the ml field, that the messaging now confirms that it is using fallback codes. You can test this through to results by dropping the debug param. Search for something …
> MWPW-147482 - ML Input Bulletproofing

- libs/blocks/table/table.css
* Fix spacing issue between button on table header left variation in RTL
Resolves: [MWPW-147002](https://jira.corp.adobe.com/browse/MWPW-147002)
**Test URLs:**
- Before: https://main--milo--adobecom.hlx.page/fragments/consonant/tables/table-header-left?martech=off
- After: https://table-rtl--milo--adobecom.hlx.page/fragments/consonant/tables/table-header-left?martech=off
CC
- Before: https://main--cc--adobecom.hlx.live/kw_ar/products/illustrator/plans?martech=off
- After: https://main--cc--adobecom.hlx.live/kw_ar/products/illustrator/plans?milolibs=table-rtl&martech=off
Note: for testing milo url please update dir to RTL in your elements tab in developer tools
> MWPW-147002-Fix spacing issue between button on table header left variation in RTL

- libs/tools/sharepoint/excel.js
Randomly seeing a type-error from the `updateExcelTable` function. Catching the error to avoid freezing up the UI when the CORS error happens.
Here is a SS of the typeerror in question:
Resolves: [MWPW-147523](https://jira.corp.adobe.com/browse/MWPW-147523)
> MWPW-147523 - [LocUI] Excel Service Error Handling

- .github/workflows/merge-to-stage.js
- .github/workflows/merge-to-stage.yaml
Follow up for https://github.com/adobecom/milo/pull/2224 - do not spam #milo-changelog with PRs that are not changing anything. Devs can be expected to check the action or reach out to #milo-stage and ping me there.
**Test URLs:**
- Before: https://main--milo--mokimo.hlx.live/?martech=off
- After: https://remove-skipped-pr-slacks--milo--mokimo.hlx.live/?martech=off
> [merge to stage automation] Remove superfluent slacks to the changelog

- libs/blocks/locui/actions/index.js
**Problem:**
In fragment search function we weren't catching fetch errors and this was causing the UI to freeze up when a file had a redirect and caused a CORS error. 
**Solution:**
Moved the fetch into its own function with a try/catch to catch the errors and display them for the user, while also enabling the find fragments to continue searching for fragments.
Resolves: [MWPW-147735](https://jira.corp.adobe.com/browse/MWPW-147735)
> MWPW-147735 - [LocUI] Catch fetch errors in fragment search

- libs/blocks/locui/locui.css
- libs/blocks/locui/status/view.js
Errors displayed in the status popup aren't formatted to be easily readable. This updates the status component to look for a list of errors to render in a list and style properly. I also fixed the problem of clicking in the status description area toggling the expanding of the popup.
Resolves: [MWPW-148094](https://jira.corp.adobe.com/browse/MWPW-148094)
> MWPW-148094 - LocUI Error Status style

- libs/blocks/locui/langs/index.js
- libs/blocks/locui/utils/miloc.js
With certain timing when hitting the rollout button on language cards, the polling Interval fires just before polling state is set to false and the subsequent status function completes a re-rendering of the language card before the rollout request is completed. This adds a polling state check before updating language cards to avoid this turn of events.
Resolves: [MWPW-146681](https://jira.corp.adobe.com/browse/MWPW-146681)
> MWPW-146681 - [LocUI] Language card polling check

- libs/blocks/accordion/accordion.js
* This is a small PR intended to clean up the a11y attributes on the Accordion block. The body of each accordion item had a `role="region"` attribute that was redundant, as we only ever have one element used as the body of the accordion item.
Resolves: [MWPW-141780](https://jira.corp.adobe.com/browse/MWPW-141780)
**Test URLs:**
Milo:
- Before: https://main--milo--adobecom.hlx.page/docs/library/blocks/accordion?martech=off
- After: https://ebartholomew-mwpw-141780-accordion-attr--milo--adobecom.hlx.page/docs/library/blocks/accordion?martech=off
CC:
- Before: https://main--cc--adobecom.hlx.page/drafts/jbrown/batch-02/products/aftereffects?martech=off
- After: https://main--cc--adobecom.hlx.page/drafts/jbrown/batch-02/products/aftereffects?martech=off&milolibs=ebartholomew-mwpw-141780-accordi …
> MWPW-141780 - Clean up Accordion block attributes

- libs/blocks/locui/locui.css
The status label when Retry is triggered changes to black. Adding the correct styling so the badge background color matches the current working status.
Resolves: [MWPW-148257](https://jira.corp.adobe.com/browse/MWPW-148257)
> MWPW-148257 - [LocUI] Retry Language status badge style

- libs/blocks/locui/actions/view.js
As a localization user, I want to be able to see that there are no languages configured so that actions aren't available and loc UI lets me know about it.
Resolves: [MWPW-148084](https://jira.corp.adobe.com/browse/MWPW-148084)
**Test URL:**
https://sean-loc--milo--adobecom.hlx.page/tools/loc?ref=main&repo=milo&owner=adobecom&host=milo.adobe.com&project=Milo&referrer=https%3A%2F%2Fadobe.sharepoint.com%2F%3Ax%3A%2Fr%2Fsites%2Fadobecom%2F_layouts%2F15%2FDoc.aspx%3Fsourcedoc%3D%257B9d18baeb-24a4-4524-8c44-4c074b265c6b%257D%26action%3Deditnew
> MWPW-148084 - [LocUI] No languages messaging

- libs/blocks/review/components/review/RatingSummary.js
- test/blocks/review/mocks/body_jp.html
- test/blocks/review/mocks/head.html
- test/blocks/review/review_jp.test.js
* The bug only happens in JP. When the review component goes through `controlJapaneseLineBreaks()`, somehow text strings are duplicated.
* The bug is reproducible in the unit test I created. 
* The fix is to use `useRef()` for those text elements.
Resolves: [MWPW-147527](https://jira.corp.adobe.com/browse/MWPW-147527)
**Test URLs:**
- Before: https://main--dc--adobecom.hlx.live/jp/acrobat/online/compress-pdf?martech=off
- After: https://main--dc--adobecom.hlx.live/jp/acrobat/online/compress-pdf?milolibs=MWPW-147527&martech=off
- Before: https://main--milo--adobecom.aem.live/
- After: https://mwpw-147527--milo--adobecom.aem.live/
> MWPW-147527 Fix JP text issue in Review component

- libs/blocks/merch/merch.css
- libs/blocks/merch/merch.js
- libs/blocks/modal/modal.merch.js
- test/blocks/modals/mocks/iframe.plain.html
- test/blocks/modals/modal.merch.test.js
of the managed checkout-link modals.
Resolves: [MWPW-147472](https://jira.corp.adobe.com/browse/MWPW-147472)
To test, click on the TWP and D2P modal CTAs at the after URL:
**Test URLs:**
- Before: https://main--milo--adobecom.hlx.page/drafts/ilyas/checkout-links?martech=off&georouting=off
- After: https://mwpw-147472-2--milo--yesil.hlx.page/drafts/ilyas/checkout-links?martech=off&georouting=off
CC Milo Catalog test page: https://main--cc--adobecom.hlx.page/products/catalog?milolibs=mwpw-147472-2--milo--yesil
In order to test the page at the after URL, use the following Modheader config:
You can import the following JSON as profile as well:
```javascript
[
{
"alwaysOn": false,
"cspHeaders": [
{
"appendMode": false,
"enabled": true,
"name": "frame-ancestors",
"value": "'self' …
```
> MWPW-147472: auto adjust commerce iframe

- libs/blocks/share/share.js
Found a BUG w/ the Share block default placeholder
This [PR](https://github.com/adobecom/milo/pull/2240) was release last week and I was going thru it to demo this in the author meet up.... 
Then I noticed the default placeholder wasn't always showing. Derp 👎 
(I found a typo in `share.js` that was not accurately checking for a length)
*This only impacts share block instances when an empty content row is authored in the block table. 
(known live examples use only a single title block table row) - 2nd example
Doesn't work ❌ (no default placeholder)
works ✅ 
works ✅ 
---
Previous related PR https://github.com/adobecom/milo/pull/2240
Resolves: [MWPW-148418](https://jira.corp.adobe.com/browse/MWPW-148418)
LIVE CC page: https://main--cc--adobecom.hlx.page/creativecloud/animation/discover/princi …
> MWPW-148418 - Share default placeholder text not displaying in some cases

- libs/features/jarvis-chat.js
- test/features/jarvis-chat/jarvis-chat.test.js
This adds a condition to map africa region to ZA (similar to aem) because `en_AFRICA` is not a valid locale as per Jarvis and Jarvis fails to load because of this.
Resolves: [MWPW-148640](https://jira.corp.adobe.com/browse/MWPW-148640)
**Test URLs:**
Milo
- Before: https://mwpw-148640--milo--nishantka.hlx.page/africa/drafts/nishantkaush/document
- After: https://main--milo--adobecom.hlx.page/africa/drafts/nishantkaush/document?milolibs=mwpw-148640--milo--nishantka
CC:
- Before: https://main--cc--adobecom.hlx.page/africa/creativecloud
- After: https://main--cc--adobecom.hlx.page/africa/creativecloud?milolibs=mwpw-148640--milo--nishantka
> MWPW-148640: Add Jarvis africa to ZA mapping

- libs/blocks/quiz-entry/quiz-entry.js
- libs/blocks/quiz-entry/utils.js
* bug fix for content flicker before redirect
* bug fix for debug mode where you cannot continue more than once
Resolves: [MWPW-149356](https://jira.corp.adobe.com/browse/MWPW-149356)
**Test URLs:**
- Before: https://stage--milo--adobecom.hlx.page/drafts/colloyd/quiz-entry/?martech=off
- After: https://quiz-entry-flicker-fix--milo--colloyd.hlx.page/drafts/colloyd/quiz-entry/?martech=off
Testing notes: To test the flicker and the fix, turn bandwidth throttling down in dev tools. Make a selection and press continue. Before, the content would disappear just before the page redirects to the quiz page. After, the content persists until the redirect happens.
To test the debug mode fix, add the debug=quiz-entry query param and make a selection and press continue. Alter your selection and press …
> quiz entry block - fix for content disappearing before redirect

- libs/features/personalization/personalization.js
- libs/utils/utils.js
Tweak for an issue found in some circumstances when testing on stage.
Resolves: [MWPW-146214](https://jira.corp.adobe.com/browse/MWPW-146214)
Test URLs for psi-check:
After: https://meptargetgnavonly2--milo--adobecom.hlx.page/?martech=off
Note: I ran the URLs below in PageSpeed Insights, but there is statistical noise.
Test URLS:
Target manifest changing gnav to say "Large menu swap". There should be no visual between these links:
Page with Target fully "on". There is no significant LHS difference between these links:
Before (LHS 88): https://main--cc--adobecom.hlx.live/drafts/mepdev/fragments/2024/q2/gnavinternal/index-target-on?gnav=block
After (LHS 90): https://main--cc--adobecom.hlx.live/drafts/mepdev/fragments/2024/q2/gnavinte …
> fast follow for MWPW-146214 [MILO][MEP] Option to have gnav but not main wait for Target (preserve targetEnabled in config under more circumstances)

- libs/blocks/global-navigation/global-navigation.js
- libs/features/dynamic-navigation.js
- test/blocks/global-navigation/global-navigation.test.js
- test/features/dynamic-nav/dynamicNav.test.js
- test/features/dynamic-nav/mocks/entry.html
- test/features/dynamic-nav/mocks/off.html
- test/features/dynamic-nav/mocks/on.html
Adds functionality to allow consumer projects to opt in to a dynamic nav experience. If a dynamicNavKey is registered in a consumer repo's config, this code adds logic to save the gnav source to sessionStorage allowing for the same nav experience in subsequent clicks.
- `entry` pages will set gnavSource to sessionStorage is a gnav source meta tag is present
- `on` pages will check for a gnavSource in sessionStorage, and if one is found, either modify the gnav-source meta tag, or create one
- pages without the dynamic-nav metadata will do nothing or remove gnavSource from sessionStorage
- projects without the key present, or where the key mismatches with the key saved in storage will use the default gnav experience
Context:
The wiki in the ticket provides more context, but it was desired …
> MWPW-145574 - Dynamic Nav Gnav Implementation

- .github/workflows/high-impact-alert.js
- .github/workflows/high-impact-alert.yml
- .github/workflows/mark-stale-prs.yaml
- .github/workflows/merge-to-stage.js
- .github/workflows/merge-to-stage.yaml
- .github/workflows/pr-reminders.yaml
This defines a new workflow that sends notifications to a Slack channel as soon as a PR with a `high-impact` label is opened. The previous logic from the `merge-to-stage.js` script has been removed, since we want such a notification to be sent out as soon as the PR is opened, not when it eventually reaches the `stage` branch, to ensure it gets visibility early on. Additionally, some workflows have been adapted to only run if the owner is `adobecom` to reduce workflow runs on forks.
Resolves: [MWPW-148268](https://jira.corp.adobe.com/browse/MWPW-148268)
**Test URLs:**
- After: https://high-impact-workflow--milo--overmyheadandbody.hlx.page/?martech=off
> High Impact Alert Workflow

- libs/blocks/locui/status/view.js
- libs/blocks/locui/utils/miloc.js
- Let the user know when the project is in the validation status
- Hide the expand arrow when there is no description
- Hide the service status when an error status is displayed
Resolves: [MWPW-148298](https://jira.corp.adobe.com/browse/MWPW-148298)
> MWPW-148298 - [LocUI] Validation status toast

- libs/martech/martech.js
Some Ad Blockers prevent the call to Target.  Martech fires an event to signal an error when this occurs.  If we add an event listener for this event as well, we can stop waiting for the "success event" that will never fire.  This should lead to improved page performance for these users, thus increasing page performance averages.
Steps to test:
1. install an ad blocker extension that blocks sstats server (I found AdBlocker Ultimate works)
2. Confirm in the network tab that calls to sstats.adobe.com are blocked
3. Observe the performance difference with the new code
Resolves: [MWPW-151189](https://jira.corp.adobe.com/browse/MWPW-151189)
**Test URLs:**
- Before: https://main--cc--adobecom.hlx.page/drafts/mepdev/fragments/2024/q2/gnavinternal/index-target-on
- After: …
> MWPW-151189 [MILO][MEP] Skip Martech timeout if blocked by ad blocker

- libs/features/personalization/personalization.js
- libs/utils/utils.js
2 issues:
Issue 1 Detailed Description: MEP control panel/button does not appear on prod with mep param
URLs:
Before: https://main--cc--adobecom.hlx.page/drafts/mepdev/fragments/2024/q2/gnavinternal/index-pzn-target-gnav?env=prod&mep
After: https://main--cc--adobecom.hlx.page/drafts/mepdev/fragments/2024/q2/gnavinternal/index-pzn-target-gnav?env=prod&mep&milolibs=mepcpfix
1. Go to URL
Expected Results: MEP button appears
Actual Results: no MEP button appears
................................................................................................
Issue 2 Detailed Description: If a page has Target metadata set to "gnav" and has personalization, the personalization …
> MWPW-151476 [MILO][MEP] MEP Control Panel (Button) Bugs

- libs/blocks/quiz-entry/quizoption.js
- libs/blocks/quiz/quizoption.js
* remove heading tags in cards, which have the role of checkbox
* set alt to "" for card icons as they are decorative images
* applied both fixes to the quiz and quiz-entry blocks
Resolves: [MWPW-147763](https://jira.corp.adobe.com/browse/MWPW-147763), [MWPW-147761](https://jira.corp.adobe.com/browse/MWPW-147761)
**Test URLs:**
- Before: https://stage--milo--adobecom.hlx.page/drafts/colloyd/quiz/?martech=off
- After: https://quiz-option-card-accessibility--milo--colloyd.hlx.page/drafts/colloyd/quiz/?martech=off
Additional Notes: Changes have been made in both quiz and quiz-entry blocks. The h2 > p tag change applies to both blocks and can be observed in both. However, the icon alt text change can only be observed in the quiz block urls above, as the quiz-entry block is currently being …
> Quiz option card accessibility fixes

- .github/workflows/high-impact-alert.yml
This attempts to solve a workflow issue where the Slack Webhook secret was not accessible to forks, thus PRs open from forks would not be able to send Slack notifications.
Resolves: [MWPW-148268](https://jira.corp.adobe.com/browse/MWPW-148268)
**Test URLs:**
- Before: https://main--milo--overmyheadandbody.hlx.page/?martech=off
- After: https://adjust-high-impact-workflow--milo--overmyheadandbody.hlx.page/?martech=off
> [MWPW-148268] Adjust high impact workflow

- .github/workflows/pr-reminders.js
Only add PR reminders to PRs raised against stage.
This avoids reminders on branches against [main](https://github.com/adobecom/milo/pull/2359#issuecomment-2128306397) - or simply contributions to loc, which don't need a "Ready for Stage" label for example.
**Test URLs:**
- Before: https://main--milo--mokimo.hlx.live/?martech=off
- After: https://reminders-only-for-stage--milo--mokimo.hlx.live/?martech=off
> Only comment reminders on PRs against stage

- libs/blocks/locui/actions/view.js
- libs/blocks/locui/langs/modal.js
- libs/blocks/locui/loc/index.js
- libs/blocks/locui/status/view.js
- libs/blocks/locui/url/tabs.js
- libs/blocks/locui/utils/miloc.js
Look for link format `[text](link)` in error messages and render a hyperlink to give users troubleshooting documentation.
Resolves: [MWPW-148208](https://jira.corp.adobe.com/browse/MWPW-148208)
> MWPW-148208 - [LocUI] Render links in error messages

- libs/scripts/scripts.js
- libs/styles/styles.css
* Update thai pages to load Adobe Clean Thai
Resolves: [MWPW-130601](https://jira.corp.adobe.com/browse/MWPW-130601)
**Test URLs:**
- Before: https://stage--milo--adobecom.hlx.page/th_th/drafts/ruchika/thai-page?martech=off&georouting=off
- After: https://adobe-clean-thai--milo--adobecom.hlx.page/th_th/drafts/ruchika/thai-page?martech=off&georouting=off
Note: Added georouting=off query param to pass the psi check
> MWPW-130601-Add typekit for adobe clean thai

- libs/blocks/locui/langs/view.js
- libs/blocks/locui/locui.css
When you start a retry it can take some time, so the miloc service is passing a property `rolloutQueued` to let the user know. This PR adds a condition to display that status.
Resolves: [MWPW-148232](https://jira.corp.adobe.com/browse/MWPW-148232)
**Test URLs:**
https://sean-loc--milo--adobecom.hlx.page/tools/loc?ref=main&repo=milo&owner=adobecom&host=milo.adobe.com&project=Milo&referrer=https%3A%2F%2Fadobe.sharepoint.com%2F%3Ax%3A%2Fr%2Fsites%2Fadobecom%2F_layouts%2F15%2FDoc.aspx%3Fsourcedoc%3D%257B03A2B243-669F-43C8-8FEF-94DE3E784073%257D%26file%3DRetry%2520Queued%2520Status.xlsx%26action%3Ddefault%26mobileredirect%3Dtrue
> MWPW-148232 - [LocUI] Retry Queue Label

- .github/workflows/helpers.js
- .github/workflows/merge-to-stage.js
We want to keep `stage` clean in case of CSOs during RCPs to make it easier to contribute changes without pushing unwanted changes to production.
For this reason, we'd want to stop opening PRs to stage **before** the RCP so that nothing is open **during** the RCP.
**Test URLs:**
- Before: https://main--milo--mokimo.hlx.page/?martech=off
- After: https://keep-stage-clean--milo--mokimo.hlx.page/?martech=off
> Start the RCP for stage earlier

- libs/blocks/modal/modal.js
- libs/features/georoutingv2/georoutingv2.js
- libs/utils/utils.js
- test/blocks/modals/modals.test.js
I've been asked by my boss' boss to drop all work to get this out Monday.  Marking high priority.
Geo modal analytics are being sent when the user closes the modal or chooses to stay on the current page.  Analytics are NOT being sent when the modal loads or they choose to change countries.
Issues solved:
1. Load events were being fired but it wasn't working because it relied on something done by martech.js.  So if the geomodal is needed, we await martech before creating the modal (note this is postLCP).
2. It sometimes said gb and sometimes said uk. This is a common issue with just this geo, so added a small fix to force it to always be uk.
3. daa-ll is preferable for capturing user events.  The close button was already using daa-ll.  So daa-ll was added to switch and stay, and the event …
> MWPW-147741 [Geo-Routing] Need to load modal after bootstrap in order to ensure Analytics fires

- libs/blocks/locui/actions/index.js
- libs/blocks/locui/actions/modal.js
- libs/blocks/locui/actions/view.js
- libs/blocks/locui/loc/index.js
- libs/blocks/locui/locui.css
- libs/blocks/locui/status/view.js
Now catching errors in url validation and also validating page fragments and letting user know which fragments are invalid. Also updated the error message for invalid urls in project.
Resolves: [MWPW-151911](https://jira.corp.adobe.com/browse/MWPW-151911)
**Test URLs:**
_Invalid hostname:_
https://main--cc--adobecom.hlx.page/tools/loc?milolibs=sean-loc&ref=main&repo=cc&owner=adobecom&host=www.adobe.com&project=Creative+Cloud&referrer=https%3A%2F%2Fadobe.sharepoint.com%2F%3Ax%3A%2Fr%2Fsites%2Fadobecom%2F_layouts%2F15%2FDoc.aspx%3Fsourcedoc%3D%257B46102d61-fe4c-4711-a05a-1e9130429bc5%257D%26action%3Deditnew
_Invalid Fragments_
https://sean-loc--milo--adobecom.hlx.page/tools/loc?ref=main&repo=milo&owner=adobecom&host=milo.adobe.com&project=Milo&referrer=https%3A%2F%2Fadobe.sharepoint.com%2F%3 …
> MWPW-151911 - [LocUI] URL validation enhancement

- libs/blocks/global-navigation/utilities/utilities.js
As part of the news.adobe.com migration, we want to add news.adobe.com as known federal origin as it was set up for federal from an akamai perspective
Resolves: [MWPW-151236](https://jira.corp.adobe.com/browse/MWPW-151236)
Milolibs don't work on news.adobe.com as the consumer has not set this up yet. Using local overrides to test this change is the most convenient and quickest method to verify this PR works as intended on the consuming pages.
Test link from @Ruchika4 : https://news.stage.adobe.com/news/news-details/test-redirect
**Test URLs:**
- After: https://mwpw-151236--milo--mokimo.hlx.live/?martech=off
> Add news.adobe.com as known federal origin

- libs/utils/utils.js
This is the first step towards Milo supporting Helix (Franklin/EDS) 5. When the time is right, there will be more exhaustive documentation and communication on everything this entails, but for now we just want to ensure Milo has basic support for its consumers when it comes to the domains it uses. A few projects that don't require authentication will be ported over to gather any learnings that might be useful for all Milo consumers.
Naming convention-wise, I went for [SLD](https://developer.mozilla.org/en-US/docs/Glossary/Second-level_Domain) for brevity purposes.
Resolves: [MWPW-150668](https://jira.corp.adobe.com/browse/MWPW-150668)
- After: https://helix-5-utils--milo--adobecom.hlx.page/?martech=off
- Before: …
> [MWPW-150668] Get utils ready for Helix 5

- libs/blocks/section-metadata/section-metadata.css
* Fix overflow causing horizontal scroll when using column for three-up etc with grid width in section metadata
Resolves: [MWPW-151281](https://jira.corp.adobe.com/browse/MWPW-151281)
**Test URLs:**
Milo:
- Before: https://main--milo--adobecom.hlx.page/drafts/ruchika/scroll/photoshop?martech=off
- After: https://section-metadata--milo--adobecom.hlx.page/drafts/ruchika/scroll/photoshop?martech=off
CC:
- Before: https://main--cc--adobecom.hlx.page/drafts/ruchika/scroll/temp/photoshop?martech=off
- After: https://main--cc--adobecom.hlx.page/drafts/ruchika/scroll/temp/photoshop?milolibs=section-metadata&martech=off
> MWPW-151281-Fix overflow causing horizontal scroll

- libs/blocks/carousel/carousel.css
- libs/blocks/carousel/carousel.js
Fixes a CLS issue caused by the carousel controls. It took me multiple attempts to reproduce, but I saved the state [here](https://pagespeed.web.dev/analysis/https-main--cc--adobecom-hlx-live-products-firefly-features-ai-painting-generator/2jogkf78pc?form_factor=mobile). The issue is more often visible on the [carousel demo page](https://pagespeed.web.dev/analysis/https-main--milo--adobecom-hlx-live-docs-library-blocks-carousel/i5pv7gou7a?form_factor=mobile).
Resolves: [MWPW-151474](https://jira.corp.adobe.com/browse/MWPW-151474)
**Test URLs:**
- Before: https://main--cc--adobecom.hlx.live/products/firefly/features/ai-painting-generator?martech=off&georouting=off
- After: https://main--cc--adobecom.hlx.live/products/firefly/features/ai-painting-generator?martech=off&georouting=off&milolibs …
> [MWPW-151474] Ensure carousel navigation is displayed after everything has been loaded

- libs/deps/merch-quantity-select.js
in action (please use firefox) there: https://main--dc--adobecom.hlx.live/acrobat/features?milolibs=mwpw-146254--milo--npeltier
vs https://main--dc--adobecom.hlx.live/acrobat/features
**Test URLs:**
- Before: https://main--milo--adobecom.hlx.live?martech=off
- After: https://mwpw-146254--milo--npeltier.hlx.live?martech=off
- Before: https://main--dc--adobecom.hlx.live/acrobat/features?martech=off
- After: https://main--dc--adobecom.hlx.live/acrobat/features?milolibs=mwpw-146254--milo--npeltier&martech=off
> MWPW-146254 make merch quantity input a textfield for ff

- .github/workflows/code-compatibility.yaml
- .github/workflows/codeql.yml
- .github/workflows/dispatch.yml
- .github/workflows/fg-sync-repos.yml
- .github/workflows/high-impact-alert.yml
- .github/workflows/label-zero-impact.yaml
- .github/workflows/merge-to-main.yaml
- .github/workflows/merge-to-stage.yaml
- .github/workflows/pr-reminders.yaml
- .github/workflows/run-lint.yaml
- .github/workflows/run-nala-milolibs.yaml
- .github/workflows/run-nala.yml
- .github/workflows/run-tests.yaml
- .github/workflows/skms.yaml
- .github/workflows/update-dependencies.yaml
Bump actions dependencies (mostly checkout) and remove fixed dependency versions to always pull the latest version of an action. 
This gets rid of the deprecation annotations of actions using node v16 or deprecated codeql versions (which are stopping to work in december 24)
Resolves: [MWPW-150087](https://jira.corp.adobe.com/browse/MWPW-150087)
**Test URLs:**
- Before: https://main--milo--mokimo.hlx.live/?martech=off
- After: https://bump-all-action-dependencies--milo--mokimo.hlx.live/?martech=off
> mwpw-150087: bump action dependencies

- libs/blocks/how-to/how-to.css
- libs/blocks/how-to/how-to.js
- test/blocks/how-to/how-to.test.js
- test/blocks/how-to/mocks/body.html
The "How-to" block will now support inline MP4 videos.
Resolves: [MWPW-147299](https://jira.corp.adobe.com/browse/MWPW-147299)
**NALA PR** - https://github.com/adobecom/nala/pull/368
**Test URLs:**
- Before: https://main--milo--adobecom.hlx.page/drafts/gunn/how-to-vid?martech=off
- After: https://mwpw-147299--milo--adobecom.hlx.page/drafts/gunn/how-to-vid?martech=off
> MWPW-147299 How-to MP4 Videos

- libs/blocks/global-navigation/utilities/utilities.js
Note: marked high priority because it is holding up test development and jeopardizing the launch date.
Resolves: [MWPW-152041](https://jira.corp.adobe.com/browse/MWPW-152041)
For testing purposes, observe the Buy now button in the gnav. It should be updated to "Swapped buy now!!" in After url. 
**Test URLs:**
- Before: https://main--cc--adobecom.hlx.page/drafts/mepdev/fragments/2024/q3/mepplaceholdersgnav/gnavplaceholders
- After: https://main--cc--adobecom.hlx.page/drafts/mepdev/fragments/2024/q3/mepplaceholdersgnav/gnavplaceholders?milolibs=mepplaceholdersgnav
**Test URLs for psi check:**
- After: https://mepplaceholdersgnav--milo--adobecom.hlx.page/?martech=off
> MWPW-152041[MEP][MILO] Add support for using MEP placeholders in gnav

- libs/blocks/global-navigation/global-navigation.js
- libs/utils/utils.js
- test/blocks/global-navigation/global-navigation.test.js
* Ensures that breadcrumbs do not show up on "on" pages when the dynamic nav is active
Resolves: [MWPW-148278](https://jira.corp.adobe.com/browse/MWPW-148278)
Context: 
Our PMs and SEO teams determined that within the journey where the dynamic nav follows the user, breadcrumbs that do not reflect the path the user has taken may be confusing. However, SEO still wanted the page's breadcrumbs to be visible to Google, so we are only stopping the creation of the feds-breadcrumbs and adjusting the classes to reflect the absence of breadcrumbs. 
Note: You will need to add a gnavSource to the session storage in order to verify that this works:
`window.sessionStorage.setItem('gnavSource', 'https://dynamic-nav-config--bacom--adobecom.hlx.page/gnav/localnav-aem-sites')`
In the normal workflow, a …
> MWPW-148278: Dynamic-Nav hide breadcrumbs

- libs/blocks/graybox/graybox.css
- libs/blocks/graybox/graybox.js
- test/blocks/graybox/globalnoclick.test.js
- test/blocks/graybox/graybox.test.js
- test/blocks/graybox/mocks/noclick-changed-els.html
- test/blocks/graybox/mocks/noclick-no-change.html
Fixes a few small UI bugs found during testing.
Resolves: [MWPW-140906](https://jira.corp.adobe.com/browse/MWPW-140906)
Marking as `zero-impact` as the graybox block is not yet in use (and will only be internal when used).
**Test URLs:**
- After: https://gb-border-fix--milo--adobecom.hlx.page/?martech=off
> MWPW-140906 Graybox Misc UI Fixes

- libs/features/personalization/personalization.js
Detailed Description: There is an entitlement called `not-q-always-on-promo` that gets selected when it should not be because the word `not` is a reverse operator.
Probable solution: update `const COLUMN_NOT_OPERATOR = 'not';` to `const COLUMN_NOT_OPERATOR = 'not ';` (adding a space after not will stop splitting when not is part of the entitlement name.
URL: https://main--cc--adobecom.hlx.page/drafts/mepdev/fragments/2024/q3/mepentitlementswithnot/
1. Use a manifest with a column using `not-q-always-on-promo` on a page where you are not logged in
Expected Results: experience with `not-q-always-on-promo` is not selected
Actual Results: experience with …
> MWPW-152456 [MILO][MEP] using the `not-q-always-on-promo` entitlement is selected when it should not be

- libs/blocks/locui/locui.css
- libs/blocks/locui/locui.js
- libs/utils/utils.js
When a user launches their localization project without having already authenticated, the user is redirected to login and upon return the project details passed as query parameters are then automatically cleared and the user gets the missing block message. This PR adds a pseudo locui block that simply displays a message to the user to re-run their project. (This block would be destroyed if we ever merge the locui branch to main)
Resolves: [MWPW-151885](https://jira.corp.adobe.com/browse/MWPW-151885)
**Test URLs:**
- Before: https://main--milo--adobecom.hlx.page/tools/loc?martech=off
- After: https://sartxi-locui-message--milo--adobecom.hlx.page/tools/loc?martech=off
> MWPW-151885 - [LocUI] messaging for auth redirect

- .github/workflows/merge-to-stage.js
- If PRs are not merged (no approvals, failing tests, overlap in files) the process should an actionable message on the PR in question.
- If the stage batch is created, we also want to post to #milo-stage so SOTs know that they can start testing
Resolves: [MWPW-152624](https://jira.corp.adobe.com/browse/MWPW-152624)
**Test URLs:**
- After: https://mwpw-152624--milo--adobecom.hlx.page/?martech=off
> mwpw-152624: improve stage PR communication

- libs/blocks/modal/modal.js
Note: this PR is flagged as high priority because we're getting pushed from above to resolve this ASAP.
Detailed Description: when using _satellite.track, most of the data that will be sent is already known.  You only need to update specific data.  Attempting to override data with undefined will destroy needed data.   So we need to check if the value is defined before adding it to the object we send to the function.
URL: https://business.adobe.com/uk/ or any geo you are not in
1. Open network tab and filter for the sstats
2. Check collect entry for info on modal load
Expected Results: Call sends _adobe_corpnew info
Actual Results: Call does not send _adobe_corpnew info …
> MWPW-152659 [MILO][MODAL][ANALYTICS] Analytic on modal load is missing

- libs/blocks/locui/actions/index.js
Now that the initial fragment search is sending back constructed URLs the de-dupe function needs to target the href property so that the duplicates can be filtered when finding fragments.
Resolves: [MWPW-152912](https://jira.corp.adobe.com/browse/MWPW-152912)
To Test: sync to langstore and see list of fragments
**Test URLs:** 
- Before: https://main--cc--adobecom.hlx.page/tools/loc?milolibs=locui&ref=main&repo=cc&owner=adobecom&host=www.adobe.com&project=Creative+Cloud&referrer=https%3A%2F%2Fadobe.sharepoint.com%2F%3Ax%3A%2Fr%2Fsites%2Fadobecom%2F_layouts%2F15%2FDoc.aspx%3Fsourcedoc%3D%257Be5fe96dc-817e-44ec-8f48-47c94fd79ecb%257D%26action%3Deditnew%26wdsle%3D0
- After: https://main--cc--adobecom.hlx.page/tools/loc?milolibs=sean-loc&ref=main&repo=cc&owner=adobecom&host=www.adobe.com&projec …
> MWPW-152912 - [LocUI] Fix duplicate fragments in search

- libs/blocks/merch/merch.css
This change sets the strikethrough price font size to 14px and font weight to normal in the merch-card block.
See XD: https://xd.adobe.com/view/fdec345a-503e-436f-af76-f15d375609b6-a8bf/screen/09ce5290-f27e-4b42-8654-8da85bea840a/specs/
Resolves: [MWPW-148002](https://jira.corp.adobe.com/browse/MWPW-148002)
Test URLs:
Before: https://main--milo--adobecom.hlx.page/docs/authoring/commerce/merch-card-product?martech=off
After: https://mwpw-148002-price-font-size-new--milo--mirafedas.hlx.page/docs/authoring/commerce/merch-card-product?martech=off
https://mwpw-148002-price-font-size-new--milo--mirafedas.hlx.live/docs/authoring/commerce/merch-card-product?martech=off
> MWPW-148002: Adjust Strike-through price font size for: merch-card (all variations)

- libs/blocks/locui/langs/modal.js
- libs/blocks/locui/status/view.js
Update skipped messaging to list the language locales for the user.
Resolves: [MWPW-152759](https://jira.corp.adobe.com/browse/MWPW-152759)
**Test URLs:**
https://main--cc--adobecom.hlx.page/tools/loc?milolibs=sean-loc&ref=main&repo=cc&owner=adobecom&host=www.adobe.com&project=Creative+Cloud&referrer=https%3A%2F%2Fadobe.sharepoint.com%2F%3Ax%3A%2Fr%2Fsites%2Fadobecom%2F_layouts%2F15%2FDoc.aspx%3Fsourcedoc%3D%257B400D73C9-2E1E-4E18-802F-884173827D30%257D%26file%3Dcc-prod-sanity-docx-test-2.xlsx%26action%3Ddefault%26mobileredirect%3Dtrue%26wdsle%3D0
> MWPW-152759 - [LocUI] update skipped message

- libs/blocks/global-navigation/global-navigation.css
- libs/blocks/global-navigation/utilities/menu/menu.css
On the landscape orientation for mobile, the user cannot access (scroll to) the lower part of the mega menu.
Resolves: [MWPW-139487](https://jira.corp.adobe.com/browse/MWPW-139487)
Before:
After:
**Test URLs:**
- Before: https://main--milo--adobecom.hlx.page/drafts/devashish/wam?martech=off
- After: https://mwpw-139487--milo--deva309.hlx.page/drafts/devashish/wam?martech=off
> MWPW-139487 - Fix for Gnav scroll issue with Landscape Orientation on devices

- libs/features/georoutingv2/georoutingv2.js
Fixes a small accessibility issue where the georouting language selector image does not have a description text.
Resolves: [MWPW-129964](https://jira.corp.adobe.com/browse/MWPW-129964)
**Test URLs:**
- After: https://mwpw-129964--milo--narcis-radu.hlx.page/drafts/narcis/default?martech=off
Test URL: https://main--cc--adobecom.hlx.page/products/acrobat-pro-cc?milolibs=mwpw-129964--milo--narcis-radu
Test using IN or CH VPN
> [MWPW-129964] Fix accessibility issues for georouting language selector

- libs/martech/martech.js
Currently in Milo MEP, the Target propositionDisplay call is not happening after the Target propositions are rendered on the page.
This update makes the Target propositionDisplay call from the MEP Martech.js file once the Target propositions are applied.
This wiki explains the changes in detail (Testing instructions are available in this wiki):
https://wiki.corp.adobe.com/pages/viewpage.action?pageId=3169882054
Resolves: [MWPW-152627](https://jira.corp.adobe.com/browse/MWPW-152627)
**Test URLs:**
- Before: https://main--homepage--adobecom.hlx.page/homepage/index-loggedout
- After: https://main--homepage--adobecom.hlx.page/homepage/index-loggedout?milolibs=targetpropdisplay
Note: check the network tab for an interact call to sstats.  Should be listed as eventType in events property in …
> MWPW-152627 [MILO][MARTECH] add Target propositionDisplay call

- libs/blocks/locui/actions/index.js
Some pages have the word index in their name and come back 404 because of the find fragments function automatically pulling everything before the word index when it is found in fragment path. This PR tightens up those conditions so it is always checking the last segment of the path and checking that it must always equal `index`.
Resolves: [MWPW-153129](https://jira.corp.adobe.com/browse/MWPW-153129)
**Test URLs: (Sync fragments to test)**
- Before: https://main--bacom--adobecom.hlx.page/tools/loc?milolibs=locui&ref=locui&repo=bacom&owner=adobecom&host=business.adobe.com&project=BACOM&referrer=https%3A%2F%2Fadobe.sharepoint.com%2F%3Ax%3A%2Fr%2Fsites%2Fadobecom%2F_layouts%2F15%2FDoc.aspx%3Fsourcedoc%3D%257B68803fea-30e8-4b22-b56d-a7cd705565f6%257D%26action%3Deditnew%26wdsle%3D0
- After: …
> MWPW-153129 - [LocUI] Index pathname conditions in find fragments

- libs/blocks/merch/merch.css
Reverts adobecom/milo#2459 because the font size change was suppose to be applied not to all strikethrough prices, but only to ones located inside merch cards. The proper fix is coming in this ticket: https://jira.corp.adobe.com/browse/MWPW-153657
Before: https://main--milo--adobecom.hlx.page/docs/authoring/commerce/merch-card-product?martech=off
After: https://revert-2459-mwpw-148002-price-font-size-new--milo--adobecom.hlx.page/docs/authoring/commerce/merch-card-product?martech=off
https://revert-2459-mwpw-148002-price-font-size-new--milo--adobecom.hlx.page/docs/authoring/commerce/merch-card-product?martech=off
> Revert "MWPW-148002: Adjust Strike-through price font size for: merch-card (all variations)"

- libs/blocks/table/table.js
Removes an unnecessary border radius from the first content column of a highlight table when it lacks highlight text.
| <img width="766" alt="Screenshot 2024-07-03 at 13 53 50" src="https://github.com/adobecom/milo/assets/11267498/574694fc-2d77-441b-b620-618ebc25a531"> | <img width="766" alt="Screenshot 2024-07-03 at 13 54 14" src="https://github.com/adobecom/milo/assets/11267498/d313de46-c28e-47b3-941e-0dd23b67bdb4"> |
Resolves: [MWPW-153727](https://jira.corp.adobe.com/browse/MWPW-153727)
**Test URLs:**
- Before: https://table-review--milo--overmyheadandbody.hlx.page/drafts/ramuntea/table-tiger-team-mwpw-152305?martech-off&georouting=off
- After: https://table-extra-radius--milo--overmyheadandbody.hlx.page/drafts/ramuntea/table-tiger-t …
> [MWPW-153727] Remove extra border radius from table highlight

- libs/blocks/global-navigation/global-navigation.js
Exposing the UNav config to be consumed and updated by any consumer like below:
If a Milo Global Navigation consumer wants to change the signInClick callback or listen to messages from the Profile Menu sub-navigation (which is the case for us in Firefly), then we can get the `CONFIG.universalNav.universalNavConfig` object, update anything we need to update, and then call `window.UniversalNav.reload(updatedConfig)`
**Test URLs:**
- After: https://stage--milo--amol-anand.hlx.page/?martech=off
> Exposing the UNav Config for consumers to modify and reload the UNav if needed

- libs/blocks/merch/merch.css
- libs/deps/merch-card.js
In this PR we change the CSS rule to set the strikethrough price font size to 14px only in merch cards.
Corresponding mas PR should be merged first: https://github.com/adobecom/mas/pull/18 
Resolves: [MWPW-153657](https://jira.corp.adobe.com/browse/MWPW-153657)
**Test URLs:**
Before:
- DC: https://main--dc--adobecom.hlx.page/drafts/steenmeyer/acrobat-pricing-samples/acrobat-business-merch-card-product
- Milo: https://main--milo--adobecom.hlx.page/docs/authoring/commerce/merch-card-product
- Mini-compare variation: https://main--milo--adobecom.hlx.live/drafts/axel/mini-compare-chart
After: 
- DC: https://main--dc--adobecom.hlx.page/drafts/steenmeyer/acrobat-pricing-samples/acrobat-business-merch-card-product?milolibs=mwpw-153657-strikethrough-price--milo--mirafedas&mep=off&georouting=off
- …
> MWPW-153657: Set the strikethrough price font size to 14px only in merch cards

- libs/blocks/table/table.css
- libs/blocks/table/table.js
This adapts the logic so that table sections can be expanded on mobile without having to change the filters.
It also brings in a few small changes requested in another thread:
* **Regular links that have more than 1 word should not span multiple lines**
| <img width="612" alt="Screenshot 2024-07-05 at 11 56 31" src="https://github.com/adobecom/milo/assets/11267498/2d8aaefc-320f-49f8-af31-988143baae9a"> | <img width="612" alt="Screenshot 2024-07-05 at 11 56 36" src="https://github.com/adobecom/milo/assets/11267498/95263d51-d6e9-4ed8-87bb-6987a2be4e9a"> |
* **The font size and line height of the first column needs to be increased from XS to S**
| <img width="514" alt="Screenshot …
> [MWPW-153881] Table section not initially expanding on mobile

- libs/utils/utils.js
It has been noticed that requests are made for empty CSS files. For performance purposes, we want to avoid such requests, since they only add overhead and aren't contributing any advantages.
The initial scope of the story was focused on the `fragments.css` file, but a few more auto blocks follow the same pattern, so it made sense to update all of them in one go. Here are the files in question:
Note that `event-rich-results` follows a different pattern and it should not be an issue at this point.
**BEFORE**
Filtering network calls by `/tiktok|slideshare|fragment|marquee/`
**AFTER**
Filtering network calls by `/tiktok|slideshare|fragment|marquee/`
Resolves: [MWPW-152278](https://jira.corp.adobe.com/browse/MWPW-152278)
**Test URLs:**
- Before: …
> [MWPW-152278] Avoid empty CSS requests

- libs/blocks/marketo/marketo.css
* Fix mobile horizontal scroll by only applying negative margin with two-up 
Resolves: [MWPW-152697](https://jira.corp.adobe.com/browse/MWPW-152697)
**Test URLs:**
- Before: https://main--milo--adobecom.hlx.page/drafts/bmarshal/mcz/marketo-scroll?martech=off
- After: https://bmarshal-marketo-horizontal-scroll--milo--adobecom.hlx.page/drafts/bmarshal/mcz/marketo-scroll?martech=off
- Before: https://main--bacom--adobecom.hlx.live/uk/?martech=off
- After: https://main--bacom--adobecom.hlx.live/uk/?martech=off&milolibs=bmarshal-marketo-horizontal-scroll
- Before: https://main--bacom--adobecom.hlx.live/uk/resources/articles/b2b-vs-b2c-marketing?martech=off
- After: https://main--bacom--adobecom.hlx.live/uk/resources/articles/b2b-vs-b2c-marketing?martech=off&milolibs=bmarshal-mar …
> MWPW-152697 Fix Marketo mobile horizontal scroll

- libs/features/personalization/personalization.js
- test/features/personalization/actions.test.js
- test/features/personalization/mocks/actions/manifestPreloadFrags.json
MEP was preloading all fragments that would be changed in the page, but only the first section fragments should be pre-loaded to improve LCP
Resolves: [MWPW-152280](https://jira.corp.adobe.com/browse/MWPW-152280)
Before:
After:
**Test URLs:**
- Before: https://main--milo--adobecom.hlx.page/drafts/cpeyer/pers/mwpw152280
- After: https://meps-fragments--milo--adobecom.hlx.page/drafts/cpeyer/pers/mwpw152280
> MWPW-152280 MEP: Only preload fragments that are in the 1st section

- libs/features/webapp-prompt/webapp-prompt.css
* Changed the transform origin of `.appPrompt-progress` to start on the right instead of at the origin (top left)
Resolves: [MWPW-153600](https://jira.corp.adobe.com/browse/MWPW-153600)
**Test URLs:**
- After: https://pep-rtl--milo--adobecom.hlx.page/?martech=off
- qa url: https://main--cc--adobecom.hlx.page/il_he/creativecloud/animation/testdoc/pepphsp1?milolibs=pep-rtl&skipPepEntitlements=true
> MWPW-153600 [PEP] loader bar on PEP prompt is seen loaded Left to right in RTL locale

- libs/utils/utils.js
This PR adds support for `rtl` localization for transcreation staging in `target-preview` directory. Also updates the function to use the proper locale for `LANGSTORE` instead of only updating the `dir` property.
Resolves: [MWPW-152016](https://jira.corp.adobe.com/browse/MWPW-152016)
**Test URLs:**
- Before: https://main--milo--adobecom.hlx.page/target-preview/he/drafts/sarchibeque/testingpreview?martech=off
- After: https://sartxi-mwpw-152016-locale-preview--milo--adobecom.hlx.page/target-preview/he/drafts/sarchibeque/testingpreview?martech=off
> MWPW-152016 - Localization target preview for transcreation

- libs/blocks/global-navigation/global-navigation.js
- libs/blocks/global-navigation/utilities/utilities.js
This bug was filed in response to this comment: https://github.com/adobecom/milo/pull/2185#pullrequestreview-2019744236
- In mobile viewports, search is now only loaded upon clicking the trigger if the `.search` element is present in the global-navigation content
Resolves: [MWPW-147270](https://jira.corp.adobe.com/browse/MWPW-147270)
**Test URLs:**
- After: https://fix-search-error--milo--sharmrj.hlx.page/?martech=off
QA: https://stage--cc--adobecom.hlx.page/products/photoshop/ai?milolibs=fix-search-error--milo--sharmrj
Note: No behavior is changed by this PR.
> MWPW-147270 Fix the error caused by trying to load Search in Global Navigation

- libs/blocks/global-footer/global-footer.js
- libs/blocks/global-navigation/features/breadcrumbs/breadcrumbs.js
- libs/blocks/global-navigation/utilities/utilities.js
- libs/blocks/modal/modal.js
- libs/utils/federated.js
- test/blocks/global-navigation/utilities/utilities.test.js
- test/utils/federated.test.js
* Adds support for federated URLs in modals to centralize content for the region selector.
* Moved out getFederatedUrl function from utilities file to federated.js file
Resolves: [MWPW-130787](https://jira.corp.adobe.com/browse/MWPW-130787) and [MWPW-153670](https://jira.corp.adobe.com/browse/MWPW-153670)
**Test URLs:**
- Before:  https://main--milo--adobecom.hlx.page/?martech=off
- After:  https://central-regionpicker--milo--bandana147.hlx.page/?martech=off
- Qa url: https://central-regionpicker--milo--bandana147.hlx.page/drafts/blaishram/document?martech=off
> Adding support for federated urls in modals

- libs/blocks/merch-card/merch-card.css
- libs/blocks/merch-card/merch-card.js
- test/blocks/merch-card/merch-card.test.js
- test/blocks/merch-card/mocks/plans-card.html
Allows using 24px font size for prices inside merch card by applying the font styles bold+italic to a price link in Word.
Resolves: [MWPW-147907](https://jira.corp.adobe.com/browse/MWPW-147907)
**Test URLs:**
- Before: https://main--milo--adobecom.hlx.page/drafts/axel/bug-fixes/big-price?martech=off
- After: https://mwpw-147907--milo--adobecom.hlx.page/drafts/axel/bug-fixes/big-price?martech=off
> MWPW-147907: Allow for 24pt font size for price [Merch Card]

- libs/blocks/modal/modal.js
- libs/features/personalization/personalization.js
- test/blocks/modals/modals.test.js
- test/features/personalization/personalization.test.js
When inserting an anchor link for the delayed modal we need to hide not only the link itself but the wrapping `<p>` element, otherwise it brings unwanted blank space.
Resolves: 
[MWPW-154054](https://jira.corp.adobe.com/browse/MWPW-154054)
[MWPW-154192](https://jira.corp.adobe.com/browse/MWPW-154192)
**Test URLs:**
Before: 
- https://main--cc--adobecom.hlx.page/products/aftereffects/free-trial-download?instant=2024-08-19T14:00:00.000Z
- https://main--cc--adobecom.hlx.page/creativecloud/buy/students?instant=2024-08-19T14:00:00.000Z
- https://main--milo--mirafedas.hlx.page/drafts/mirafedas/delayed-modals/delayed-modal
After: 
- https://main--cc--adobecom.hlx.page/products/aftereffects/free-trial-download?instant=2024-08-19T14:00:00.000Z&milolibs=MWPW-154054-blank-space--milo--mirafedas
- …
> MWPW-154054 + MWPW-154192: Blank space caused by delayed modal anchor

- test/blocks/bulk-publish/bulk-publish-utils.test.js
Skip the bulk publish v1 tests as users should be using v2 and there will be no further code changes to v1.  I did not want to delete the files yet just in case it's still being used somewhere.
Resolves: No jira filed
**Test URLs:**
- After: https://skip-bp-v1--milo--adobecom.hlx.page/?martech=off
> Skip bulk publish v1 tests as authors now use v2

- .github/workflows/merge-to-stage.js
#milo-changelog doesn't see individual PRs being merged due to this error: `Error merging 2508: MWPW-147270 Fix the error caused by trying to load Search in Global Navigation SLACK.merge(...).catch is not a function`
Fixes small omission introduced in https://github.com/adobecom/milo/pull/2572 and moves the catch block to the correct promise.
Resolves: [MWPW-152624](https://jira.corp.adobe.com/browse/MWPW-152624)
**Test URLs:**
- After: https://stage-workflow--milo--mokimo.aem.live/?martech=off
> Move the catch to the correct function

- libs/blocks/marketo/marketo.css
* Fix resource form margins on desktop by increasing specificity
* Update calculations after `--grid-margins-width` changes, there should be no margins on mobile
Resolves: [MWPW-154562](https://jira.corp.adobe.com/browse/MWPW-154562)
**Test URLs:**
- Before: https://main--milo--adobecom.hlx.page/drafts/bmarshal/mcz/marketo?martech=off
- After: https://bmarshal-marketo-margin--milo--adobecom.hlx.page/drafts/bmarshal/mcz/marketo?martech=off
- Before: https://main--bacom--adobecom.hlx.live/resources/videos/marketo-product-tour?martech=off
- After: https://main--bacom--adobecom.hlx.live/resources/videos/marketo-product-tour?martech=off&milolibs=bmarshal-marketo-margin
- Before: https://business.stage.adobe.com/resources/experience-magento-compare.html?martech=off
- After: …
> MWPW-154562 Fix resource form margins

- libs/blocks/locui/actions/index.js
- libs/blocks/locui/utils/url.js
Add a function that finds fragment urls set as metadata content.
Resolves: [MWPW-153215](https://jira.corp.adobe.com/browse/MWPW-153215)
**Test URLs:**
https://main--cc--adobecom.hlx.page/tools/loc?milolibs=sean-loc&ref=main&repo=cc&owner=adobecom&host=www.adobe.com&project=Creative+Cloud&referrer=https%3A%2F%2Fadobe.sharepoint.com%2F%3Ax%3A%2Fr%2Fsites%2Fadobecom%2F_layouts%2F15%2FDoc.aspx%3Fsourcedoc%3D%257Be29aea5e-1c23-4a76-b402-5df7db60215e%257D%26action%3Deditnew%26wdsle%3D0
> MWPW-153215 - [LocUI] Find fragments in Metadata

- libs/blocks/modal/modal.js
There exists a race condition that when the same modal hashes appear multiple times on the page, the same fragment could be loaded more than once. More specifically, after the hash change, there is a period when getModal() needs to fetch its content but the dialog-modal hasn't been appended to document yet. If another modal on the page gets its init() called (via section preloadLinks) during this period, all the early-exit safeguard in init() we currently have will fail. This PR aims to cover this condition by keeping track of what dialogs are being loaded but not yet appended.
How to reproduce:
Locally or using overrides, in modal.js, you can fake a longer getPathModal() call by making it into something like `await Promise.all([getPathModal(details.path, dialog), new Promise((r) => …
> [Modal] Dedup Ongoing Dialogs for Same Fragment

- libs/blocks/graybox/graybox.css
This PR solves the issue where the desktop global navigation is not hidden on mobile & tablet view.
Resolves: [MWPW-152674](https://jira.corp.adobe.com/browse/MWPW-152674)
**Before:**
**After:**
- Before: https://main--bacom-graybox--adobecom.hlx.page/pocone/customer-success-stories/graybox-changed
- After: https://main--bacom-graybox--adobecom.hlx.page/pocone/customer-success-stories/graybox-changed?milolibs=mwpw-152674-graybox-gnav--milo--robert-bogos
https://mwpw-152674-graybox-gnav--milo--robert-bogos.hlx.page/drafts/rbogos/page-default?martech=off
> [MWPW-152674] [Gray Box] Desktop gnav not hidden when device view is open

- libs/blocks/global-footer/global-footer.css
Add styling for region picker drop-up variant (without hash)
Resolves: [MWPW-154795](https://jira.corp.adobe.com/browse/MWPW-154795)
**Test URLs:**
- Before: https://main--milo--adobecom.hlx.page/drafts/snehal/unav11
- After: https://dropup--milo--adobecom.hlx.page/drafts/snehal/unav11
Before styles applied : 
After styles applied :
QA : [Sample Page](https://dropup--milo--adobecom.hlx.page/drafts/snehal/unav11)
> [MWPW-154795] Style Feds Global-footer region picker drop-up variant (without hash)

- libs/blocks/global-footer/global-footer.css
Reverts adobecom/milo#2599 based on https://github.com/adobecom/milo/pull/2599#issuecomment-2245428349
> Revert "[MWPW-154795] Style Feds Global-footer region picker drop-up variant (without hash)"

- libs/features/personalization/personalization.js
* asynchronous preload of the manifests (excluding disabled promos)
Resolves: [MWPW-152275](https://jira.corp.adobe.com/browse/MWPW-152275)
QA Instructions: Look at the performance tab in dev tools for when the 3 manifests are loaded.
**Test URLs:**
- Currently on prod (manifests load simultaneously but after interact call): https://main--cc--adobecom.hlx.page/products/illustrator
- Before (manifests load sequentially after interact call): https://main--cc--adobecom.hlx.page/products/illustrator?milolibs=mepmovefromutils
- After (manifests load simultaneously during ims and interact call): https://main--cc--adobecom.hlx.page/products/illustrator?milolibs=preloadmanifests
**Psi Check URL:**
https://preloadmanifests--milo--adobecom.hlx.page/?martech=off
> MWPW-152275 Move manifest.json request up while waiting on sstats / etc.

- libs/blocks/article-header/article-header.js
- test/blocks/article-header/article-header.test.js
- test/blocks/article-header/mocks/body.html
- test/blocks/article-header/mocks/placeholders.json
Made various updates to Article Header in order to reduce LCP on blogs:
* Reduced network requests by pulling code from imports into file
* Delayed placeholder code because it was non-critical
* Only loaded taxonomy if necessary (which it isn't on bacom blog)
* Removed await for build author so requests can be made concurrently
Resolves: [MWPW-146743](https://jira.corp.adobe.com/browse/MWPW-146743)
Results (hlx.live testing):
- Page Speed Index LCP: 0.7s reduction on bacom blog. No change on brand blog.
- DevTools LCP Fast 3G, No CPU throttling: Avg 2.8s reduction on both blogs.
- Incidental reduction in TBT for both blogs
**Test URLs:**
- Before: https://main--milo--adobecom.hlx.page/drafts/methomas/blog-migration/article-header/connecting-external-data-sources-to-adobe-experience-manager …
> MWPW-146743 Improve Article Header Performance

- libs/blocks/locui/actions/index.js
- libs/blocks/locui/actions/modal.js
- libs/blocks/locui/langs/index.js
- libs/blocks/locui/loc/index.js
- libs/blocks/locui/locui.css
- libs/blocks/locui/url/index.js
- libs/blocks/locui/url/tabs.js
- libs/blocks/locui/url/view.js
URL action buttons need better state management. This PR adds better action button state management and updates the validation of both configured URLs and URLs returned in find fragments to verify the page exists and is the same origin.
1. URL actions will be disabled if the URL returns a 404 or is not from the same origin. The Edit and Live actions will also be disabled if theyre sources return a 404.
2. LocUI will now display "not same domain" for URLs with origins that do not match the current project. Updating to show status in URLs, Errors toast, and in fragment scan results.
Resolves: [MWPW-153586](https://jira.corp.adobe.com/browse/MWPW-153586)
**Fragment Validation:**
https://sean-loc--milo--adobecom.hlx.page/tools/loc?ref=main&repo=milo&owner=adobecom&host=milo.adobe.com&project=M …
> MWPW-153586 - [LocUI] Validation and URL Actions state

- libs/features/personalization/personalization.js
- test/utils/utils.test.js
* Adds default execution order to disabled promos
Resolves: [MWPW-154998](https://jira.corp.adobe.com/browse/MWPW-154998)
**Test URLs:**
- After: https://manifestorder--milo--adobecom.hlx.page/?martech=off
> MWPW-154998 [MEP][MILO] Manifests do not execute in the right order when there is a disabled manifest

- libs/blocks/mobile-app-banner/mobile-app-banner.js
- test/blocks/mobile-app-banner/mobile-app-banner.test.js
Reverts adobecom/milo#2567 because the team is still waiting for PIA approval before passing ECID to the live banners.
This was discussed in the CC Backlog grooming on 07/23.
**Test URLs:**
- Before: https://main--milo--adobecom.hlx.live/drafts/drashti/milo-banner/branch-banner
- After: https://revert-2567-branch-ecid--milo--adobecom.hlx.page/drafts/drashti/milo-banner/branch-banner
> Revert "[MWPW-152968] mWeb - Passing ECID to Branch.io banner - Implementation"

- libs/utils/federated.js
- test/blocks/global-navigation/global-navigation.test.js
- test/blocks/global-navigation/test-utilities.js
- test/blocks/global-navigation/utilities/utilities.test.js
- test/utils/federated.test.js
Undo's https://github.com/adobecom/milo/pull/1973 due to several reasons.
- Proxying federal content through stage.adobe.com adds a very visible VPN requirement to viewing a wide variety of pages
- PSI checks on hlx.page can't access stage.adobe.com
- Deviating from the norm (hlx.page fetches hlx.page) leads to a long tail of bugs within authoring tools (preflight, loc, etc.) that don't expect this pattern.
If we ever get a hard requirement to have authentication enabled on the federal project, we can revisit this. Given the negative aspects, I'd consider adding MS-authentication to the federal project a technical limitation for now.
Resolves: [MWPW-154965](https://jira.corp.adobe.com/browse/MWPW-154965)
- Be on VPN
- Log in on a consumer page that uses federal content
- See the federal …
> mwpw-154965: Fetch federal stage content from hlx.page instead of stage.adobe.com

- libs/blocks/graybox-promote/components/graybox-promote-lit.js
- tools/sidekick/config.json
This PR removes the `host` and `referrer` query params from the adminPageUri, in the Graybox promote API call payload, as they are no longer necessary.
Resolves: [MWPW-155103](https://jira.corp.adobe.com/browse/MWPW-155103)
https://grayboxui--milo--adobecom.hlx.page/drafts/rbogos/page-default?martech=off
> [MWPW-155103] Removed query params from the adminPageUri 

- libs/blocks/table/table.css
* force tooltip positioning for row-title in mobile and rtl scenarios so they are always fully visible
Resolves: [MWPW-152336](https://jira.corp.adobe.com/browse/MWPW-152336)
**Test URLs:**
- Before: https://table-review--milo--adobecom.hlx.page/drafts/colloyd/table/sample-table?martech=off
- After: https://table-tooltip-visibility--milo--colloyd.hlx.page/drafts/colloyd/table/sample-table?martech=off
Testing notes: Tooltip positioning in row titles in mobile are truncated in the before, they are forced to be visible in the after. This also applies for rtl in desktop on mobile.
> MWPW-152336 - Table tooltip fixes
